{
  "hash": "f182a9a15d5c922e6db3f910f573ed14",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 Instructions\"\nauthor: \"Matthew Norberg\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"09/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in the hotel bookings data set\ndf <- read_csv('./_data/hotel_bookings.csv')\n```\n:::\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\nFirst, let's look at the columns in the data set and the first few entries to get an idea of what each instance of the data is describing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspec(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncols(\n  hotel = col_character(),\n  is_canceled = col_double(),\n  lead_time = col_double(),\n  arrival_date_year = col_double(),\n  arrival_date_month = col_character(),\n  arrival_date_week_number = col_double(),\n  arrival_date_day_of_month = col_double(),\n  stays_in_weekend_nights = col_double(),\n  stays_in_week_nights = col_double(),\n  adults = col_double(),\n  children = col_double(),\n  babies = col_double(),\n  meal = col_character(),\n  country = col_character(),\n  market_segment = col_character(),\n  distribution_channel = col_character(),\n  is_repeated_guest = col_double(),\n  previous_cancellations = col_double(),\n  previous_bookings_not_canceled = col_double(),\n  reserved_room_type = col_character(),\n  assigned_room_type = col_character(),\n  booking_changes = col_double(),\n  deposit_type = col_character(),\n  agent = col_character(),\n  company = col_character(),\n  days_in_waiting_list = col_double(),\n  customer_type = col_character(),\n  adr = col_double(),\n  required_car_parking_spaces = col_double(),\n  total_of_special_requests = col_double(),\n  reservation_status = col_character(),\n  reservation_status_date = col_date(format = \"\")\n)\n```\n:::\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 32\n  hotel   is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n  <chr>     <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n1 Resort…       0     342    2015 July         27       1       0       0      2\n2 Resort…       0     737    2015 July         27       1       0       0      2\n3 Resort…       0       7    2015 July         27       1       0       1      1\n4 Resort…       0      13    2015 July         27       1       0       1      1\n5 Resort…       0      14    2015 July         27       1       0       2      2\n6 Resort…       0      14    2015 July         27       1       0       2      2\n# … with 22 more variables: children <dbl>, babies <dbl>, meal <chr>,\n#   country <chr>, market_segment <chr>, distribution_channel <chr>,\n#   is_repeated_guest <dbl>, previous_cancellations <dbl>,\n#   previous_bookings_not_canceled <dbl>, reserved_room_type <chr>,\n#   assigned_room_type <chr>, booking_changes <dbl>, deposit_type <chr>,\n#   agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n\nThe output above shows that each row in the data set is describing an instance of a hotel booking.  For each booking, we are recording 32 data parameters as described by the columns.  Additionally, we can see that some of the entries have a value of \"NULL\".  For instance, the first row of the data set has an agent and company listed as \"NULL\".  This is probably used to describe instances in which an travel agent or travel company was not used.  The following code creates a data frame containing all the rows that have a \"NULL\" value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNULLS <- df %>% filter_all(any_vars(. %in% c('NULL')))\nhead(NULLS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 32\n  hotel   is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n  <chr>     <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n1 Resort…       0     342    2015 July         27       1       0       0      2\n2 Resort…       0     737    2015 July         27       1       0       0      2\n3 Resort…       0       7    2015 July         27       1       0       1      1\n4 Resort…       0      13    2015 July         27       1       0       1      1\n5 Resort…       0      14    2015 July         27       1       0       2      2\n6 Resort…       0      14    2015 July         27       1       0       2      2\n# … with 22 more variables: children <dbl>, babies <dbl>, meal <chr>,\n#   country <chr>, market_segment <chr>, distribution_channel <chr>,\n#   is_repeated_guest <dbl>, previous_cancellations <dbl>,\n#   previous_bookings_not_canceled <dbl>, reserved_room_type <chr>,\n#   assigned_room_type <chr>, booking_changes <dbl>, deposit_type <chr>,\n#   agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n\nThe original dataframe had 119,390 rows while the new dataframe called 'NULLS' created above has 119,173 rows.  This shows that the vast majority of the rows in the dataset have at least one \"NULL\" value (99.8%).\n\nLet's find out if there are any missing values in the data set.  The code chunk below finds the columns that contain NA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify columns containing NA\ncolnames(df)[apply(df, 2, anyNA)]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"children\"\n```\n:::\n:::\n\n\nThe 'children' column of the data set contains values that are not available.  We can use the filter function to identify the rows of the data set that contain NA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the rows in the data set containing NA\nfilter(df, is.na(children))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 32\n  hotel   is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n  <chr>     <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n1 City H…       1       2    2015 August       32       3       1       0      2\n2 City H…       1       1    2015 August       32       5       0       2      2\n3 City H…       1       1    2015 August       32       5       0       2      3\n4 City H…       1       8    2015 August       33      13       2       5      2\n# … with 22 more variables: children <dbl>, babies <dbl>, meal <chr>,\n#   country <chr>, market_segment <chr>, distribution_channel <chr>,\n#   is_repeated_guest <dbl>, previous_cancellations <dbl>,\n#   previous_bookings_not_canceled <dbl>, reserved_room_type <chr>,\n#   assigned_room_type <chr>, booking_changes <dbl>, deposit_type <chr>,\n#   agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n\nThe data set has 119,390 rows.  The code above shows that 4 of those rows contain entries that are not available.  Since only a small proportion of rows contain entries that are not available, it is likely safe to remove them.  Running the code cell below will remove the rows listed above and generate a clean data set. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- na.omit(df)\n```\n:::\n\n\nAn analysis of the 'arrival_data_year' column reveals that the data was collected over the course of three years from 2015 to 2017.  This can be shown with the following R command: `summary(df$arrival_date_year)`.  Additionally, we can see that the tibble contains information about hotel bookings from all over the world, as evident by the 'country' column.  The code chunk below reveals that there are 167 unique countries in the data set.  Note that although the tibble generated below has 168 rows, one of those rows is for those data entries whose country is not known.  In these cases, the country is listed as \"NULL\".  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountries <- select(df, country) %>%\n  group_by(country) %>%\n  summarise(TotalBookings = n()) %>%\n  arrange(desc(TotalBookings))\n\ncountries\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 178 × 2\n   country TotalBookings\n   <chr>           <int>\n 1 PRT             48586\n 2 GBR             12129\n 3 FRA             10415\n 4 ESP              8568\n 5 DEU              7287\n 6 ITA              3766\n 7 IRL              3375\n 8 BEL              2342\n 9 BRA              2224\n10 NLD              2104\n# … with 168 more rows\n```\n:::\n\n```{.r .cell-code}\nsummary(countries$TotalBookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n    1.00     2.00    12.50   670.71    74.75 48586.00 \n```\n:::\n\n```{.r .cell-code}\ncountryHist <- ggplot(countries, aes(x=TotalBookings)) + geom_histogram(colour = \"black\", fill = \"white\", bins = 40)\nprint(countryHist + ggtitle(\"Hotel Booking Frequency per Country vs Number of Countries\") + \n        labs(x = \"Number of hotel bookings\", y = \"Number of countries\"))\n```\n\n::: {.cell-output-display}\n![](challenge2_MatthewNorberg_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nAn analysis on the tibble shows that Portugal has the most hotel bookings in the data set.  Additionally, the summary command below reveals that the average number of bookings is 670.71 and the median number of bookings is 12.5.  The histogram derived from the count of each country further reveals that the number of bookings per country is skewed. \n\nThe categorical nature of the 'hotel', 'meal', 'reserved_room_type', and 'customer_type' columns of the data set lead me to believe that the data was collected by a singular Hotel Company that has locations all over the world.  They have categorized their hotels as being in one of two possible categories, \"Resort Hotel\" and \"City Hotel\".  It seems unlikely that multiple hotel companies would use the same categorization.  Additionally, this particular hotel company has a set of meal categories, room type categories, and customer categories.  I would argue that these categorization are not a standard that is being used by multiple hotels which furthers my theory that this data was collected by a singular hotel company.  The code chunk below lists the possible categories for each of the aforementioned columns.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(df$hotel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Resort Hotel\" \"City Hotel\"  \n```\n:::\n\n```{.r .cell-code}\nunique(df$reserved_room_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"C\" \"A\" \"D\" \"E\" \"G\" \"F\" \"H\" \"L\" \"P\" \"B\"\n```\n:::\n\n```{.r .cell-code}\nunique(df$is_repeated_guest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0 1\n```\n:::\n:::\n\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\nLet's look at the set of hotel bookings that took place in the United States.  I was interested in determining how many bookings were made in which the customer got the type of room that they requested.  The code chunk below answers this question.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the rows that contain hotel booking information in the United States\nus <- filter(df, country == \"USA\")\n\n# Find the proportion of bookings where the customer got the correct room type\ncorrectType <- us %>%\n  filter(reserved_room_type == assigned_room_type) %>%\n  summarise(Count = n()) / dim(us)[1]\n\n# Display the answer\ncat(\"The proportion of bookings where the customer got the correct room type in the United States:\", correctType[[1]])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe proportion of bookings where the customer got the correct room type in the United States: 0.8874583\n```\n:::\n:::\n\n\nThe data shows that most people were able to get the room type that they requested in the United States. However, I was in interested in figuring out how the United States compares to other countries in terms of accuracy of hotel bookings.  The following code chunk computes the booking accuracy of all countries listed in the table and sorts them based on accuracy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the booking accuracy of each country\nr <- df %>%\n  group_by(country) %>%\n  filter(reserved_room_type == assigned_room_type) %>%\n  summarise(CorrectRoom = n()) %>%\n  left_join(countries, by = \"country\") %>%\n  mutate(PercentCorrect = CorrectRoom / TotalBookings) %>%\n  arrange(desc(PercentCorrect))\n\n# Display the results\nhead(r)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n  country CorrectRoom TotalBookings PercentCorrect\n  <chr>         <int>         <int>          <dbl>\n1 AIA               1             1              1\n2 ALB              12            12              1\n3 AND               7             7              1\n4 ARM               8             8              1\n5 ASM               1             1              1\n6 ATA               2             2              1\n```\n:::\n\n```{.r .cell-code}\nsummary(r)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   country           CorrectRoom      TotalBookings     PercentCorrect  \n Length:173         Min.   :    1.0   Min.   :    1.0   Min.   :0.3333  \n Class :character   1st Qu.:    2.0   1st Qu.:    3.0   1st Qu.:0.8765  \n Mode  :character   Median :   14.0   Median :   14.0   Median :0.9231  \n                    Mean   :  603.9   Mean   :  690.1   Mean   :0.9107  \n                    3rd Qu.:   67.0   3rd Qu.:   80.0   3rd Qu.:1.0000  \n                    Max.   :42477.0   Max.   :48586.0   Max.   :1.0000  \n```\n:::\n:::\n\n\nThe results from the code chunk above show that there are many countries with perfect booking accuracy.  Furthermore, the average accuracy was 91%.  Therefore, the United States is below average in terms of hotel booking accuracy.  \n\nIn addition to hotel booking accuracy, I was also interested in the total number of nights stayed that each booking incurred in the United States.  The data set has two columns for the number of nights stayed: 'stays_in_weekend_nights' and 'stays_in_week_nights'.  Here, I am defining the total number of nights to be the sum of those two children.  Specifically, I wanted to know if the total number of nights stayed in the hotel is influenced by whether or not the booking included children and babies.  The code chunk below computes the average number of nights and the median number of nights for each (children, babies) pairing in the data set for hotel bookings in the US.    \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute central tendency and dispersion for total number of nights in the united states grouped by children and babies\n# Total number of nights = weekend nights + week nights\ntemp <- us %>%\n  mutate(total_nights = stays_in_weekend_nights + stays_in_week_nights) %>%\n  group_by(children, babies) %>%\n  summarise(AverageNights = mean(total_nights), NumOccurences = n(), MedianNights = median(total_nights))\n\n# Display the information\ntemp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 5\n# Groups:   children [4]\n  children babies AverageNights NumOccurences MedianNights\n     <dbl>  <dbl>         <dbl>         <int>        <dbl>\n1        0      0          2.76          1871          2  \n2        0      1          3.17             6          3.5\n3        1      0          2.51            83          2  \n4        2      0          3.16           132          3  \n5        3      0          1.6              5          1  \n```\n:::\n:::\n\n\nThe results in the table above show that offspring status of a hotel booking does not seem to have an impact on the average number of nights stayed in the hotel.\n\nLastly, I was interested in the lead time attribute for bookings in the United States.  I wanted to determine if some months are more popular than others and therefore have a larger lead time.  The following code chunk computes averaged lead time grouped by 'arrival_date_month' to determine which months are the most popular. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Lets look at lead time statistics grouped by month to see if some months are more popular\nleadTime <- us %>%\n  group_by(arrival_date_month) %>%\n  summarise(AverageLeadTime = mean(lead_time), \n            sdLeadTime = sd(lead_time), \n            maxLeadTime = max(lead_time), \n            minLeadTime = min(lead_time))\n\nleadTime\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 5\n   arrival_date_month AverageLeadTime sdLeadTime maxLeadTime minLeadTime\n   <chr>                        <dbl>      <dbl>       <dbl>       <dbl>\n 1 April                         76.5       74.2         317           0\n 2 August                       101.       104.          504           0\n 3 December                      58.7       63.3         237           0\n 4 February                      24.9       35.8         240           0\n 5 January                       35.3       47.3         343           0\n 6 July                         104.        96.4         476           0\n 7 June                          89.0       77.0         423           0\n 8 March                         54.3       56.6         286           0\n 9 May                           85.2       80.8         340           0\n10 November                      48.4       51.4         260           0\n11 October                       67.4       78.6         241           0\n12 September                     56.6       73.5         542           0\n```\n:::\n:::\n\n\nThe results above show that the summer months seem to have the highest average lead time while some of the winter months have the fewest lead times.  This may indicate that the summer months are the most popular times to go on vacation.  \n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\nI choose to look at hotel bookings in the United States to do my analysis.  The first portion of my analysis looked at hotel booking accuracy in the United States versus the other countries in the data set.  I was surprised that the United States is below the average accuracy in the data set. \n\nI also looked at the total number of nights for each booking the United States.  I wanted to know if having children or babies included in the hotel booking impacted how long people stay.  The idea was interesting, but the results indicated that having children and babies included in the booking did not seem to impact total stay.\n\nLastly, I looked at the amount of lead time in hotel bookings for the United States in order to see which months were the most popular.  Unsurprisingly, the summer months were among the most popular and the least popular were winter months. \n\n",
    "supporting": [
      "challenge2_MatthewNorberg_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}