{
  "hash": "8eab4ab94815a67b5eafbafd135cc0ea",
  "result": {
    "markdown": "---\ntitle: \"Challenge 6 Solutions\"\nauthor: \"Vinitha Maheswaran\"\ndescription: \"Visualizing Time and Relationships\"\ndate: \"12/01/2022\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_6\n  - hotel_bookings\n  - air_bnb\n  - fed_rate\n  - debt\n  - usa_households\n  - abc_poll\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  mutate variables as needed (including sanity checks)\n4)  create at least one graph including time (evolution)\n   - try to make them \"publication\" ready (optional)\n   - Explain why you choose the specific graph type\n5)  Create at least one graph depicting part-whole or flow relationships\n   - try to make them \"publication\" ready (optional)\n   - Explain why you choose the specific graph type\n\n[R Graph Gallery](https://r-graph-gallery.com/) is a good starting point for thinking about what information is conveyed in standard graph types, and includes example R code.\n\n(be sure to only include the category tags for the data you use!)\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n  - debt  ⭐\n  - fed_rate ⭐⭐\n  - abc_poll ⭐⭐⭐\n  - usa_hh ⭐⭐⭐\n  - hotel_bookings ⭐⭐⭐⭐\n  - AB_NYC ⭐⭐⭐⭐⭐\n\n\nFor this challenge I will be working with the \"hotel_bookings\" dataset. It is a publicly available data set containing booking transactions from a city hotel and a resort hotel in Portugal.\n\nI used the \"hotel_bookings\" dataset previously for the Challenge 2 and Challenge 4 and I will be using the same content for the section 1: read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc), section 2: tidy data (as needed, including sanity checks), and section 3: mutate variables as needed (including sanity checks).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reading the hotel_bookings.csv data set and storing in a data frame\nhotel_data <- read_csv(\"_data/hotel_bookings.csv\")\nprint(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 119,390 × 32\n   hotel  is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n   <chr>    <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n 1 Resor…       0     342    2015 July         27       1       0       0      2\n 2 Resor…       0     737    2015 July         27       1       0       0      2\n 3 Resor…       0       7    2015 July         27       1       0       1      1\n 4 Resor…       0      13    2015 July         27       1       0       1      1\n 5 Resor…       0      14    2015 July         27       1       0       2      2\n 6 Resor…       0      14    2015 July         27       1       0       2      2\n 7 Resor…       0       0    2015 July         27       1       0       2      2\n 8 Resor…       0       9    2015 July         27       1       0       2      2\n 9 Resor…       1      85    2015 July         27       1       0       3      2\n10 Resor…       1      75    2015 July         27       1       0       3      2\n# … with 119,380 more rows, 22 more variables: children <dbl>, babies <dbl>,\n#   meal <chr>, country <chr>, market_segment <chr>,\n#   distribution_channel <chr>, is_repeated_guest <dbl>,\n#   previous_cancellations <dbl>, previous_bookings_not_canceled <dbl>,\n#   reserved_room_type <chr>, assigned_room_type <chr>, booking_changes <dbl>,\n#   deposit_type <chr>, agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n\n### Briefly describe the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Finding dimension of the data set\ndim(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 119390     32\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Structure of hotel_data\nstr(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspec_tbl_df [119,390 × 32] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ hotel                         : chr [1:119390] \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" ...\n $ is_canceled                   : num [1:119390] 0 0 0 0 0 0 0 0 1 1 ...\n $ lead_time                     : num [1:119390] 342 737 7 13 14 14 0 9 85 75 ...\n $ arrival_date_year             : num [1:119390] 2015 2015 2015 2015 2015 ...\n $ arrival_date_month            : chr [1:119390] \"July\" \"July\" \"July\" \"July\" ...\n $ arrival_date_week_number      : num [1:119390] 27 27 27 27 27 27 27 27 27 27 ...\n $ arrival_date_day_of_month     : num [1:119390] 1 1 1 1 1 1 1 1 1 1 ...\n $ stays_in_weekend_nights       : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ stays_in_week_nights          : num [1:119390] 0 0 1 1 2 2 2 2 3 3 ...\n $ adults                        : num [1:119390] 2 2 1 1 2 2 2 2 2 2 ...\n $ children                      : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ babies                        : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ meal                          : chr [1:119390] \"BB\" \"BB\" \"BB\" \"BB\" ...\n $ country                       : chr [1:119390] \"PRT\" \"PRT\" \"GBR\" \"GBR\" ...\n $ market_segment                : chr [1:119390] \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ distribution_channel          : chr [1:119390] \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ is_repeated_guest             : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ previous_cancellations        : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ previous_bookings_not_canceled: num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ reserved_room_type            : chr [1:119390] \"C\" \"C\" \"A\" \"A\" ...\n $ assigned_room_type            : chr [1:119390] \"C\" \"C\" \"C\" \"A\" ...\n $ booking_changes               : num [1:119390] 3 4 0 0 0 0 0 0 0 0 ...\n $ deposit_type                  : chr [1:119390] \"No Deposit\" \"No Deposit\" \"No Deposit\" \"No Deposit\" ...\n $ agent                         : chr [1:119390] \"NULL\" \"NULL\" \"NULL\" \"304\" ...\n $ company                       : chr [1:119390] \"NULL\" \"NULL\" \"NULL\" \"NULL\" ...\n $ days_in_waiting_list          : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ customer_type                 : chr [1:119390] \"Transient\" \"Transient\" \"Transient\" \"Transient\" ...\n $ adr                           : num [1:119390] 0 0 75 75 98 ...\n $ required_car_parking_spaces   : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ total_of_special_requests     : num [1:119390] 0 0 0 0 1 1 0 1 1 0 ...\n $ reservation_status            : chr [1:119390] \"Check-Out\" \"Check-Out\" \"Check-Out\" \"Check-Out\" ...\n $ reservation_status_date       : Date[1:119390], format: \"2015-07-01\" \"2015-07-01\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   hotel = col_character(),\n  ..   is_canceled = col_double(),\n  ..   lead_time = col_double(),\n  ..   arrival_date_year = col_double(),\n  ..   arrival_date_month = col_character(),\n  ..   arrival_date_week_number = col_double(),\n  ..   arrival_date_day_of_month = col_double(),\n  ..   stays_in_weekend_nights = col_double(),\n  ..   stays_in_week_nights = col_double(),\n  ..   adults = col_double(),\n  ..   children = col_double(),\n  ..   babies = col_double(),\n  ..   meal = col_character(),\n  ..   country = col_character(),\n  ..   market_segment = col_character(),\n  ..   distribution_channel = col_character(),\n  ..   is_repeated_guest = col_double(),\n  ..   previous_cancellations = col_double(),\n  ..   previous_bookings_not_canceled = col_double(),\n  ..   reserved_room_type = col_character(),\n  ..   assigned_room_type = col_character(),\n  ..   booking_changes = col_double(),\n  ..   deposit_type = col_character(),\n  ..   agent = col_character(),\n  ..   company = col_character(),\n  ..   days_in_waiting_list = col_double(),\n  ..   customer_type = col_character(),\n  ..   adr = col_double(),\n  ..   required_car_parking_spaces = col_double(),\n  ..   total_of_special_requests = col_double(),\n  ..   reservation_status = col_character(),\n  ..   reservation_status_date = col_date(format = \"\")\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Summary of hotel_data\nlibrary(summarytools)\nprint(summarytools::dfSummary(hotel_data,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.60, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>hotel_data</h4>\n<strong>Dimensions</strong>: 119390 x 32\n  <br/><strong>Duplicates</strong>: 31994\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">hotel\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. City Hotel</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Resort Hotel</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">79330</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">66.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">40060</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEgAAAAjCAQAAACd14RVAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAd0lEQVRYw+2WQQqAQAhFNbpjd6jz1B3mlLW1IKIZwb94b+dGHn5B/TQtpmoBhP4yx+IoWqjVX4TMlgKddqvkIkMIIYQQqkZO6HE6Wl+XRDzeU+9uM0Z00I5sH3o/tpQBp70fWdsnFxlCCCGEUDXa114BucgQ+uICqNkLn1NBYVkAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">is_canceled\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.4</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">75166</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">63.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">44224</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">37.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEUAAAAjCAQAAABoKQ/lAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAd0lEQVRYw+2WsQ2AMAwEY8SO7ADzwA6ZElqDgMJYyQvddW6SU96KbXtRYegtgMo7oy+25o0z24NKKVNTkXqqhAJCBRVUUPmxyuXjr7FTUjA/AS18TBR/u2pAa8KSsISfNnlJ+NJrQgGhggoqqGSjOpn7IhQQKnccKlQLn6Fu+0oAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">lead_time\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 104 (106.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 69 &le; 737</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 142 (1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">479 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAA/UlEQVRo3u2bwQ3DIAxFS8WO3aGdh+zQKdtTgyMlKRE0z1b/OxHBwU+yAckkvS6xudIBSIAOoJdsP6ZFQTwSHdwWNsy8nLrNoycdZSPhU0gCNBKgkQCNBGgkQCMBGgnQSIBGAjQSoJEAjQRoJEAjARoJ0EiAJm9PlbmT47fZtCvwaTf5bjaFTyEJ0EiAJrxAbllUTG/f25nQJOD5AUL4FAov0JRCFm83pMMC3m5I4VNIAjSHa6Di43jrEPBxvHUIWLjNdZAAt7kOEqicXRnDBc6ujH/eRr9TVt/2j02snwrU0raJta9VDr7fTnb9FORviLvRSkFi3iR8EUuA5g2eyyOnmO8fmgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0xNFQwNzo1NDo1MSswMDowMIvQGrEAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDD6jaINAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2016.2 (0.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2015 &le; 2016 &le; 2017</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2015</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">21996</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">18.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2016</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">56707</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">47.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2017</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">40687</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">34.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAyCAQAAABSH4t+AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAjElEQVRYw+2X0Q2AIAxEqWFHh3Ae3cEp9bf4gQXKkTR3f4TACy3tgTwJqQ1KC47LenD9JvKQdoTeNJdTe3XhPXy62Lkjjjji8LhPExtvU3WJbqAd/dcgTVgZzHPOS0IFrcmAelTehtiFQBxxxCU6gqscHcHyXXFzBFvWYxcCccQRh8etNKD5ip07MO4FQucR/6/Xhu0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_month\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. August</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. July</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. May</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. October</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. April</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. June</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. September</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. March</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. February</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. November</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 2 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13877</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12661</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11791</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11160</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11089</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10939</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10508</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9794</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8068</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6794</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12709</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABcAAACjCAQAAADLeE1IAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAwUlEQVRYw+3Y0QnDMAxFUSl0x+xQzZPukCmbX8fWSzFRsEyf/wonYIlLWqpf6TlLl36Yv8oPH3eQtwIusjZ4zzsqeRCvIth/cC2rUpeU4s5lNidgU8jbgOtZUu2dHB0WiQ75GD5TkaYXvC6ynSTV3smD+LMBs0jyXEXylUrOIuEkqfZOjs48RZpe8nOR3hyp9k4exIf97DTnaVikf61UiyQP4oOKNPdZUCS6VKpFkgfxeb7kRfhv5z/wO0WOvnsnPwB4iz+0VNKytwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0xNFQwNzo1NDo1MSswMDowMIvQGrEAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDD6jaINAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_week_number\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 27.2 (13.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 28 &le; 53</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">53 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAABEElEQVRo3u2YSw6DMAxEm4o7cof2PHCHnrJs7SAsQj6TkebtsknykO3YpP+Lmzf6AhJAX6CWxS5St2O2U6p9Kw6zmy2Pdylkdatfs33pQ0gCaLrlwDboheyYxDZt2yVtQ4H8G9cURohA/o1HBU1DgWudnkHjoa9C9ALDWomcOGPuFwSYgC8Az/OnQABTZRoKoOpMDH0SSwANvUCYxHPWnQKBUS1xDfQhJAE0EkBDLwBrp2P8CxRNB5MK3H9/6ENIAmgkgMZVIYb2ORSYc2yPoQ8hCaCRABoJoKEXmHQe8Jw6BDPgUAhE/QF9CEkAjQTQSACNBNBIAI0E0NALJNtq7yR/5j5mHkgkd76EPoQkgOYAegsjJsIk1aEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_day_of_month\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 15.8 (8.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 16 &le; 31</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 15 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">31 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAA/UlEQVRo3u2bYQ6CMAxGN7M7cgc9j96BU+ofoyUZdoMtzybf+wOEdPSNNoEM8jPF5kInIAE6gbMUe5AnXOBumuw26AK2b8vhURqTTml5b9cpoq7ANpnWoZfP3toW0CzaLXAsGW8yRhXTpBLypuLsRGACrfT0Q9kL9IceneqXnqIt9dB153bXznsxv/FivL6BSqj9TnqCkMC4dg7/KCEBGgnQSIBGAjQSoJEAjQRoJEAjARoJ0EiARgI0EqCRAI0EaCRAIwGav1wnrmMWBs16ZSCB+sJg+BKSAI0EaCRAIwEaCdBIgCa8QLZf3z2C/A1xNe8DOUjOu4QvIQnQvADhiCwYof4LAAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0xNFQwNzo1NDo1MSswMDowMIvQGrEAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDD6jaINAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">stays_in_weekend_nights\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.9 (1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 1 &le; 19</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (1.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">17 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAwklEQVRo3u3bSw6CQBAA0R4zd+QOeh64A6fUjZA2EcW4qOmk3oagLLqSmQ2fdo/aLvQABtAD/Kvnk2XfELdGD/ZJ3rf99a8pIiJWesIflF9CBtAMoBlAM4BmAM0AmgE0A2gG0AygGUAzgGYAzQCaATQDaOUD+vuf5yJPyw4Dpudx/Kdl5ZeQATQDaAbQDKAZQDOAZgDNAJoBNANo/dxlc3rbd6wbLV8DttFHvdHS8ovUS5GvIa5pDbQiMx8qv4kNoD0ABwoRJ2Mt7BUAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">stays_in_week_nights\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.5 (1.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 50</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.8)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAzUlEQVRo3u3bvQ3CMBgGYRt5R+8A85AdMiUUobAQMUEUl1e6p+On+I7YQiGhPkq2Cz2AAfQA/2rjg+W1IW6VHmtu3LdvR6CXTk/3o/glZADNAJoBNANoBtAMoBlAM4BmAM0AmgE0A2gG0AygGUCLD2ifnryHXKnZDdiu0qz0bIfELyEDaAbQDKAZQDOAZgAtPqDNXtzOC859VjA9Agn3b8UvIQNoBtAMoLXvbzn319mBgF5KWU/7a10db6ReQv4NcR0+xBoy8674TWwA7QkBbRPvXLCQJwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0xNFQwNzo1NDo1MSswMDowMIvQGrEAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDD6jaINAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">adults\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1.9 (0.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 55</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (0.3)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">14 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAnklEQVRo3u3bsQ3CMBBAUYyyI0MwD+zAlNA6gSISxUuk/zorzX3J6c7jfTm3qx6gAD3Av5b58Pz6Ie5DD/jLPOay/nRbnV560h1Of4UK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQNrvT223pxzHfR0wr6eOYE+53+itUgPYBnFoIzZpXvxoAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">children\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 10</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (3.8)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">110796</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">92.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">4861</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3652</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">76</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABOCAQAAAB1N9v1AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAzElEQVRo3u3aQQqCUBRG4XejPbqHWo/twVXWpMF7hREKHn4538yJ3MNTvET1bNku9AAG0APsde0vHiEvxK1WAlqb6Nn+sAxX8Y+QATQDaAbQDKB9fImXbXcBVb/+1ObbHKuf+VyP0PxOu6ccRfs6gSliH/0RkMcAmgE0A2gG0OIDXKcJ/cxuo7T4l9gAmgE0A2gG0OID3EYJp/pxdwiYQ/5qsBqQyACaATQDaAbQDKC5jdLcRmkG0AygGUAzgGYALT6gAve3QfwJGEB7AcFyGB4o2EV1AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAwi9AasQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MSswMDowMPqNog0AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">4\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">babies\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0 (0.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 10</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (12.3)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">118473</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">99.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">900</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">15</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGYAAABOCAQAAAB4KauyAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAvElEQVRo3u3XsQ2EMBAAQR/6Hunh++F7oEpI7ZcIIPHesZM5sbzCSOc4Wh3L7AMY84aYT7/4JfyBvnER09o6+2w37cOq1DUzhsoYKmOojKH6mwD2Z7tARD+OxeNt5unPX+qaDTFbwqn5MiY7Y6iMoTKGyhgqY6hKxdR9Ajg1gxhDZQyVMVTGUBlDVSqm7tScnU8AKmOojKEyhsoYKmOonJqpnJqpjKEyhsoYKmOojKEqFRPJZ8tBqS9jDNUJk1kUkAOXFDYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">meal\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. BB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. FB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. HB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. SC</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">92310</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">77.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">798</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14463</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10650</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1169</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFIAAABOCAQAAAAZMYnwAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAA0UlEQVRo3u3ZwQ3CMBBEUS9Kj/QA9UAPqRIuHGwLiygx7Iz4/5ZL9BRb8sqJR9HvlA0A+cuW+uEutEEvMUCWcs62vVqbJ4vlBglSLZAg1epOnHXfW75c1Md17H7N/GqXxXI3yJvQFDREqgYSpFogQaoF8q+QFqNaM/SOpqBrsn7DXVD+tG6xJ0GCVAskSLUskFxYHcnuwurDqJY9pL1B9qOayg61WG6QINUCCVItpqAj2U1B3W87zR93fl9SNZAg1QIJUi2QswrJiaLL4kuCnNUTjcEaWsVSh8gAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">country\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. PRT</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. GBR</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. FRA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. ESP</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. DEU</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. ITA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. IRL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. BEL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. BRA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. NLD</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 168 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">48590</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">40.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12129</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10415</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8568</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">7.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7287</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3766</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3375</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2342</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2224</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2104</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">18590</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADEAAACjCAQAAACJOz7fAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAABDklEQVRo3u2byw3DIBAFTZQe3UNSD+nBVTpXYr7CCxFP825cGMGuRjbY7txG5zGcIIJ4hoOPWWFeLoPYtt0EcPyMNGoBAgSIOBeBHH2zFONC87nuaa4JZ529UT4h8/ftpVVkblEbjaYFAWI5BKZtTMW09z1bMa1NZTSaFgSI5RCYtjEF01pYNkKEprWrikbTggABIo6GzLOmtfJs1rSWG6bRUSBAgIijYdp/PTbbiTyxit3oZq+AGBEQIEDEwbSNSZjW1rMJ09pHo2lBgFgdgWlzwbQgQIBYCKEgc3/6AR9sS5YbBAgQMghMCwIECBCjI3tAkUvvwUXzz3T9bx4aHQUCxHKI2ZduY6JRiwmIL6XnPPixWbQYAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAwi9AasQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MSswMDowMPqNog0AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">market_segment\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Aviation</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Complementary</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Corporate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Direct</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Groups</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Offline TA/TO</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Online TA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">237</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">743</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5295</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12606</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">19811</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">16.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">24219</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">20.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">56477</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">47.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAB4CAQAAAD83KJ0AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAA5ElEQVRo3u3byw2DMBCE4XGUHlNE6kkRqZIcfGCJQMSxd4HVPxw5fMKvkRCUSZG5hWrJOU3merlMpBVyDyYcHFx6rthjsrgQVjhyMH0aYZMLfjo4ODi4q3HBBXS3N+ZGePrIS056SJLePpayLxU4OLh47usQ8zu+as7RCHPGdsNqI8wZPbi5VyYcHFw8l7sRjhzMvZdU/WW0U0A2I+Y190aAg4MTjTA0TY1Q09MLDY1Q0ze7uTcCHBxcPJe7gP5ohPZH2uB+aYTWLKcn98qEg4OL53I3Ap82wcHBwZ2WK/xLclnuA3H1M43ux6laAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAwi9AasQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MSswMDowMPqNog0AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">distribution_channel\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Corporate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Direct</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. GDS</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. TA/TO</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6677</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14645</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">193</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">97870</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">82.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFYAAABOCAQAAAAQ2imKAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAyUlEQVRo3u3YTQqDMBCGYSO5o4fwPHoHT6kLf5iIgSwMMx+876aUbh7aKRmT9kGn0RsANkLZvlnNAM/Jm3Zm/1O5/Gi6Xjdv42dSYwAWLFiwYPv2OsFinlx3yZ69QdaBIuvTHYOl8tgQZQOrbF22OHMsNQZgwYIFCxbsEyvin1VXxCX4Za3UzIIFCxYsWLBgu6e7dUWv6WLONfNzN1zMeVY+uUiNAViwYMGC7Rt3XX8mu3VxMQcWLFiwYMGClcWm4LtLkdQ3C7ZXB8BNGVt+RHUgAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAwi9AasQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MSswMDowMPqNog0AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">is_repeated_guest\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">115580</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">96.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3810</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGMAAAAjCAQAAAAqanxyAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjMaZS7rAAAAhklEQVRYw+2WsQ2AMAwEbcSO2QHmgR0yJTQUIQiE0vj9+uvcWD7Zlt4PY2CKHkAafBpzW+ypHmXxFw2zEj3bb+qtIjkqaSAhDSSkgYQ0kCDR6MJIHesSjrdp0IfbRNBOznhU2yW45lqLPbZREkX1D42sSAMJaSAhDSSkgQRjws0LyVFJA4kTTuULS0ZN1/wAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTErMDA6MDCL0BqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUxKzAwOjAw+o2iDQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">previous_cancellations\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 26</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (9.7)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">15 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAAn0lEQVRo3u3bwQnCQBBAUVfSo0VYj/ZglXqTjRAIeHgJ/HdKyGU+7N4m4305t6seoAA9wL+W+eW5uhD3oYfbMo+5rD/dvk8vPeVOpz9CBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaD+70/PG9OO4/0ZMa+njuFPuc/ojVID2Aab+CM3x0/HFAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwujgALAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMMtluJAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">previous_bookings_not_canceled\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (1.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 72</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (10.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">73 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAApklEQVRo3u3bsQ2AIBQAUTHs6BDOozs4pXYEoiQai+Mn9yoNzT8DHaZzim2mBzCAHuCvXL/szYFYEz1cTz1mbpeW8nTQU74UfgsZQDOAZgDNAJoBNANoBtAMoBlAM4BmAM0AmgE0A2gG0AygGUAzgGYAzQCaATQDaAbQDKAZQDOAZgDNAFr4gNxf2soV5XFvUd8Cnm9Mb6P9JVF90DTabF+FPwMG0C5xkQrPBJiq2AAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMLo4ACwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMTRUMDc6NTQ6NTIrMDA6MDDLZbiQAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reserved_room_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. B</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. C</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. D</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. E</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. G</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. H</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. L</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. P</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">85994</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">72.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1118</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">932</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">19201</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">16.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6535</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2897</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2094</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">601</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAE0AAACVCAQAAAC3bb95AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAABF0lEQVR42u3aQQ7CIBAF0GK8o3fQ89Q7eEpduLA0tjYThal5f9dN8wIk/ADlPmTNoTcA7bs5Tj+u3RfeuSzQhuHUFXarvhJPKBoaGhpas8w2qlvsLz9Jme7oJfybb2WqqSZ0vI/du8cCLVfQ0NDQ0NBS0/bSPHJlVop6cxZpuYKGhoaGhqZ5xFIdYq03j0vjQd18EdT+5C3xhKKhoaH9G81ty9bsvXm07hkfaK/mkWHNJZ5QNDQ0NLRmUYq2Zqp50zz6d45nZmut7+PXVVqmoKGhoaH1omkei9nJcYx3uWhoaGhoaLFoHpF4/IqGhoaGhhaL5hGJ5oGGhoaGhvZ3tL2UIs0DDS1Z0NDQ0EIpqXb0KolHDS2SB/kLL8QTU5AMAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwujgALAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMMtluJAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">assigned_room_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. D</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. E</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. G</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. C</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. B</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. H</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. I</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. K</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 2 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74053</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">62.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">25322</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">21.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7806</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3751</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2553</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2375</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2163</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">712</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">363</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">279</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEQAAACjCAQAAACZW3ADAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAABIElEQVR42u3cS47CMBAFwPZo7sgdmPPAHTgls2ATLD5RiO3GqrfLJpTSVl4LIco1cuRnNADkWX6XF+fOB+ZYnkAiDh0Zl7urNKMBAQEBmQZSveIv2+6yQ8qy58rm22zL8rNzjua0cg34a/DoNqwBbc5RmtGAgICAfBrtG/F97duiY1dClu3b+7SkGQ0ICAjIp9G+Ed/Uvn1795bqiRy6fgn+AjIuICAgINNArAER92vAg/Yd0b0P2ndU0hxWEBAQkFkh2jfPaKwBbyDjAgICArIzRPsmHc3puvYHYI0hIwMCAgICsne0b52qfZNARgYEBAQEZFpIzjVA+4KAgICAzAzRvnXSjAYEBAQEZFpIzvYdGWsACAgICEjrFH+LCvIm/3opNRNCgp/dAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwujgALAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMMtluJAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">booking_changes\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.2 (0.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 21</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (2.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">21 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAAsklEQVRo3u3bsQ2EMBAAwfPLPdIDXw/0QJWQAPK/AAkRLCftZEByi+zMLnPk9qEHMIAe4KnaPoz7hvgWerAr7b6tv5+6iIiY6AlvSL+EDKAZQDOAZgDNAJoBNANoBtAMoBlAM4BmAM0AmgE0A2gG0AygGUAzgGYAzQCaATQDaAbQDKAZQDOAZgCtHr8e1tO97z6CfBGwHUEe/q4XvC+otBOOSW5D9M1vLElmPpV+ExtAWwDtkw6P7dty4wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMLo4ACwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMTRUMDc6NTQ6NTIrMDA6MDDLZbiQAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">deposit_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. No Deposit</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Non Refund</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Refundable</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">104641</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">87.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14587</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">162</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFsAAAAyCAQAAACZxG+AAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAAmklEQVRo3u3YQQqAIBBGYSe6Y3eo89gdPGVtNZBCSP+R93Zu5KMGGrIreGwZDYCt35ofTulB363CDmEbbauWipPTIYENG7ZUsGHPyn583FPbLd2zfHuy5mt6lEtnGJJYWVwPudfwYXFVnHenQwIbNmypYMN+jQ3w7ybYAAt2lP51WWX7CTZs2FLBhg1bKqdsc7M9FTl92rB7dgOdxw9P8zuHywAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMLo4ACwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMTRUMDc6NTQ6NTIrMDA6MDDLZbiQAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">agent\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 9</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. NULL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 240</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 14</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 7</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 6</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 250</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 241</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 28</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 324 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">31961</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">26.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">16340</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">13.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13922</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7191</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3640</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3539</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3290</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2870</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1721</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1666</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">33250</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">27.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACYAAACjCAQAAABMSaROAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAA+ElEQVRo3u3aUQ6CMBBFUWrYI4tgPXUPrBJ/NLbQMTMtNdNw358xnNihvIAa9um6PC60HGNz+uJpHuAa0kPm/M3FRG09lwkGNhx2uJy2OuWd7EINFUB6fL9lRrGCVtWHVlWQdpJ+twYYmBBa4xNdY5ywUmtYpuh3a4CBCbl7a+i7QsC+rVE3O79bAwzsH5jfCiq2Rk1jTNNpZovxa5KfWFvAwIbD/LZG7xuX2gIqVFBL/G4NMDAdRmsoQmuAgSWhNRShNcDAemFeKyjusenPOMOcADCwm2G0BhgYmC1DPe5Y1yZg9sed/H7O79kEAxPS7wcZV8v0i70AF2c84K6FJZMAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTIrMDA6MDC6OAAsAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwy2W4kAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">company\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. NULL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 40</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 223</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 67</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 45</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 153</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 174</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 219</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 281</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 154</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 343 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">112593</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">927</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">784</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">267</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">250</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">215</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">149</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">141</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">138</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">133</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3793</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGEAAACjCAQAAAAwL7iXAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAABOElEQVR42u3dQUrDUBhG0UTcY/eg69E9dJU6ElKlIh2Y+37OmWUScskLfLPsH9vqns5+AAkzEp6PF+/LfBgv+52Ebbuc/Wx/cr25GnCQJBRIKJBQIKFgQMK3gXF97C6n2o/Lbn/4Nv/t+NQDDtJNwtsyY/tuwpokFEgokFAgoUBCgaVaYKkWSCiQUCChQEKBhAJLtcBSLZBQIKFAQoGEAgkFAxKmjW1LVYKElUkokFAgoUBCwbSluiZju0BCgYQCCQUSCiQUWKoFlmqBhAIJBRIKJBRIKLBUCyzVAgkFEgokFEgokFAwIGHa2LZUJUhYmYQCCQUSCiQUWKoFAw6ShAIJBRIKJBRIKBiQMG2prunmRx5fY/t1ndex/XgLl0V+d/ZLwookFEgokFAgoWDan8LWNOAgSSj4BEfQLG0jOjx0AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwujgALAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMMtluJAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">days_in_waiting_list\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.3 (17.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 391</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (7.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">128 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAApUlEQVRo3u3bTQ5AMBQA4VfpHR3CebiDU7KTEvETkdGY2WHzPml3bZqi7hp6AAH0AE/L5cOwbIgu0YMdVe7bvP7URkTESE94o+qXkAA6AXQC6ATQCaATQCeATgCdADoBdALoBNAJoBNAJ4BOAJ0AOgF0AugE0AmgE0AngE4AnQA6AXQC6ATQVQ/I+6/702sFXzldvQFcPzV9Tnyx4uclb3AI+DlgBlQ1Cs90amnoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwujgALAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMMtluJAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">customer_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Contract</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Group</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Transient</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Transient-Party</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4076</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">577</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">89613</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">75.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">25124</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">21.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFAAAABACAQAAAAnzji9AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAAtElEQVRo3u2ZwQ2AIBAExdAjRViP9mCV+jEGNPEBkV2SmR+/yd0RNkc4Jm9mtQCCfxPzw3YN5BK0Uvm9eFQwTUnr9sK+xQgiqAZBBNXYC8byuKt9XoT8YRZnhJuPsOBHIbga5v+xKugIggiqQRBBNQi2Yh+3isBqk2aySj0StcPqqEz19jOIIIJqEERQjb0gy6MahloeVcWtnn95FXGr75zatxhBBNUgiKCasdKMI/YtRrCVE0kDFVmlgNVsAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwujgALAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMMtluJAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">adr\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 101.8 (50.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">-6.4 &le; 94.6 &le; 5400</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 56.7 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">8879 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAApklEQVRo3u3bUQpAQBRAUU+zR4uwnlmEVfI7o1CUO6/u+SLSu8XfE/uU20wPYAA9wFelPYnuUj19Hms8Pu0n7WDl7salOd7oqS+kf4UMoBlAM4BmAM0AmgE0A2gG0AygGUAzgGYAzQCaATQDaAbQDKAZQDOAZgDNAJoBNANoBtAMoBlAM4BmAC19QLd6XBP+THC7O93vSw+U16yhxzhTvZP+GzCAdgBvwApj46SqIgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMLo4ACwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMTRUMDc6NTQ6NTIrMDA6MDDLZbiQAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">required_car_parking_spaces\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 8</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (3.9)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">111974</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">93.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">7383</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">6.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">28</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">8</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGEAAABOCAQAAACa9bDLAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAAyUlEQVRo3u3YwQnDMAxAUat0x+7QzpPukCnbq1IwhBzqL/HfzZfgT2wiEp9R3W31BkzokXDPi3eZi/GMScIYj9V7O2U/rBocJBMITCAwgcAEgp+v837tKUtFHovi8mP+Le+620HaUtyrzCuZTKqV7kSDg2QCgQkEJhCYQNAgwWF7lemwvZX5p5o1uAsmEJhAYAKBCQQmEDRI6Dap1uSwTWACgQkEJhCYQGACgZMqgZMqgQkEJhCYQGACgQkEDRKi5GR30OAtmEDwBYFgFqucqA7eAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwujgALAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMMtluJAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">total_of_special_requests\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.6 (0.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 5</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (1.4)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">70318</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">58.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">33226</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">27.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12969</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2497</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">340</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">40</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEEAAABcCAQAAACbthCLAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAAy0lEQVRo3u3awQ2DMBBE0d0oPdJDUg/0QJXhQCIZQyLhDd45/Ln5Ak9ei5Es/GXZuWUDIKy5l4up28F4+BeC2dAFMG9WAoOAAAECBEFC9YGe254SipfN5M2POZvyrZtdGBua8hl2B5vyH4MTOI4QIECAIEigKc30BnFc1vE6PkE4KuvrT4fAICBAgAChDk1ppjeItSmvbsY61S70uQD+ScgIBAgQIOgTKOu2C+B49M4CBAgQsgMBwic05Y6QEwgQIECAIEpw/oOG8M4ClU0d4tkGJE0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTIrMDA6MDC6OAAsAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwy2W4kAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reservation_status\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Canceled</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Check-Out</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. No-Show</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">43017</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">36.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">75166</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">63.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1207</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEUAAAAyCAQAAACgo97bAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAAAkElEQVRYw+3ZYQqAIAyG4RbesUN0HrtDp7RfwQyJZCNHvd+/0PCBiROUMkXJPBoA5T5Jf2zmjbNK33y9YKqHFhNkN/0dqEBQoECB8mHK5eC3Hd22iG5Inb3MIXr1qAXK798uVSFcLwm9qXdmoAJBgQIFinfozGeCduaKksuA3tymjA0UKFCgQPkZRXj5gPIwB/HzEXjyZignAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwujgALAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0xNFQwNzo1NDo1MiswMDowMMtluJAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reservation_status_date\n[Date]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min : 2014-10-17</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">med : 2016-08-07</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">max : 2017-09-14</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">range : 2y 10m 28d</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">926 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDA4HNjSEAbtIAAABOklEQVRo3u2aWw6CMBBFwbhH9qDrwT24Sv2QkmoYmaHT3g6550/TYM88WimMryE2F/QEKICeQCnX/MPofPF5abC784Xzvq2cgWmY6v7AdwZaMq9hLMsPTGBYcvMs1GkioOmFpGPtmyYCeay1Yz8i+xpVBGbT9r49elIqOwn81rA15rqRFQUsU7blp5mAhjT1spgDBSyFpSX8f6HwAsCdWMP+tta5wH7XhC+h8AKFJeS7KQEE6qztFsKXEAXQdL4PJOTbmyAZkE83DmdAWkBbL6wFGdiOSv2TIDeBPqAAGgqgoQAaCqChABoKoKEAGgqgoQAaCqChABoKoKEAGgqg+XO87vVaHkxg+wkk/sGqQUCvheNcPSBVfW9lIwpI5ZG+9XxV7AhrILPwjnlwHx1HOucmCUQkfBNTAM0bGapAMig/FXoAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMTRUMDc6NTQ6NTIrMDA6MDC6OAAsAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTE0VDA3OjU0OjUyKzAwOjAwy2W4kAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.1.1)<br/>2022-12-14</p>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check for the period of hotel booking dates\nhotel_data%>%\n  select(hotel, arrival_date_year, arrival_date_month)%>%distinct()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 3\n   hotel        arrival_date_year arrival_date_month\n   <chr>                    <dbl> <chr>             \n 1 Resort Hotel              2015 July              \n 2 Resort Hotel              2015 August            \n 3 Resort Hotel              2015 September         \n 4 Resort Hotel              2015 October           \n 5 Resort Hotel              2015 November          \n 6 Resort Hotel              2015 December          \n 7 Resort Hotel              2016 January           \n 8 Resort Hotel              2016 February          \n 9 Resort Hotel              2016 March             \n10 Resort Hotel              2016 April             \n# … with 42 more rows\n```\n:::\n:::\n\n\nAfter reading the data using read_csv function, it is stored in a dataframe \"hotel_data\". The hotel_bookings data set contains 119390 rows (observations) and 32 columns (attributes/variables) including information such as when the booking was made, length of stay, the number of adults, children, and/or babies, the number of available parking spaces, and many others for the respective hotels. Each row/observation represents a hotel booking. Since this is a public data set, all data elements pertaining to hotel or customer identification are not included in the data set. This data set can have an important role for research and educational purposes in hotel administration, revenue management, machine learning, data mining and other fields. This data set will be helpful for (i) Tourists (people who are booking hotels) to check and understand trends of hotel price over a period of time and plan their travel accordingly within budget, learn about hotel accommodations and features before booking (ii) Hotel Management to keep track of the relevant information about themselves as well as their competitors. Understand and analyze the seasonal trend of hotel booking and accommodate different types of visitors that they have (iii) Tourist / hospitality services - (e.g. travel agency, airlines / car rental companies) to observe the times when hotels in the region are in high demand, analyze the duration of typical stays, and use the information to help plan their own services (iv)  Local Government / independent data analysts to observe the overall trend of tourist activities in the region and analyzing the different types of visitors in the hotels during different seasons.\n\nUsing the \"dfSummary\" function from \"summarytools\" package we find that there are 31994 duplicates in the data. The reason for the identified duplication is that there is no unique id for each booking. It is possible that the booking was made by different tourists and the values for each attribute was exactly the same. This confusion could have been avoided by adding a Booking ID which would be unique for each booking. 66.4% of the data represents city hotel and the remaining 33.6% of the data represents resort hotel. 18.4%, 47.5% and 34.1% of the data correspondingly represents years 2015, 2016 and 2017. I wanted to check the unequal distribution in data for the 3 consecutive years. I further investigated the data and found that the data we have represents hotel bookings from the period July 2015 - August 2017.\n\n## Tidy Data (as needed)\n\nIs your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check for missing/null data in the hotel_data\nsum(is.na(hotel_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n\n```{.r .cell-code}\nsum(is.null(hotel_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nWe find that there are 4 NA's or missing values in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking which columns have NA values\ncol <- colnames(hotel_data)\nfor (c in col){\n  print(paste0(\"NA values in \", c, \": \", sum(is.na(hotel_data[,c]))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"NA values in hotel: 0\"\n[1] \"NA values in is_canceled: 0\"\n[1] \"NA values in lead_time: 0\"\n[1] \"NA values in arrival_date_year: 0\"\n[1] \"NA values in arrival_date_month: 0\"\n[1] \"NA values in arrival_date_week_number: 0\"\n[1] \"NA values in arrival_date_day_of_month: 0\"\n[1] \"NA values in stays_in_weekend_nights: 0\"\n[1] \"NA values in stays_in_week_nights: 0\"\n[1] \"NA values in adults: 0\"\n[1] \"NA values in children: 4\"\n[1] \"NA values in babies: 0\"\n[1] \"NA values in meal: 0\"\n[1] \"NA values in country: 0\"\n[1] \"NA values in market_segment: 0\"\n[1] \"NA values in distribution_channel: 0\"\n[1] \"NA values in is_repeated_guest: 0\"\n[1] \"NA values in previous_cancellations: 0\"\n[1] \"NA values in previous_bookings_not_canceled: 0\"\n[1] \"NA values in reserved_room_type: 0\"\n[1] \"NA values in assigned_room_type: 0\"\n[1] \"NA values in booking_changes: 0\"\n[1] \"NA values in deposit_type: 0\"\n[1] \"NA values in agent: 0\"\n[1] \"NA values in company: 0\"\n[1] \"NA values in days_in_waiting_list: 0\"\n[1] \"NA values in customer_type: 0\"\n[1] \"NA values in adr: 0\"\n[1] \"NA values in required_car_parking_spaces: 0\"\n[1] \"NA values in total_of_special_requests: 0\"\n[1] \"NA values in reservation_status: 0\"\n[1] \"NA values in reservation_status_date: 0\"\n```\n:::\n:::\n\n\nWe can see that all 4 NA's in the hotel booking dataset are from the column \"Children\". We can either replace the missing values with 0 or we can drop the 4 rows with NA values. I chose to drop the 4 rows as removing 4 rows from a huge dataset with 119390 observations/rows would not affect any of the statistics significantly.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking which columns have NULL values\ncol <- colnames(hotel_data)\nfor (c in col){\n  print(paste0(\"NULL values in \", c, \": \", sum(is.null(hotel_data[,c]))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"NULL values in hotel: 0\"\n[1] \"NULL values in is_canceled: 0\"\n[1] \"NULL values in lead_time: 0\"\n[1] \"NULL values in arrival_date_year: 0\"\n[1] \"NULL values in arrival_date_month: 0\"\n[1] \"NULL values in arrival_date_week_number: 0\"\n[1] \"NULL values in arrival_date_day_of_month: 0\"\n[1] \"NULL values in stays_in_weekend_nights: 0\"\n[1] \"NULL values in stays_in_week_nights: 0\"\n[1] \"NULL values in adults: 0\"\n[1] \"NULL values in children: 0\"\n[1] \"NULL values in babies: 0\"\n[1] \"NULL values in meal: 0\"\n[1] \"NULL values in country: 0\"\n[1] \"NULL values in market_segment: 0\"\n[1] \"NULL values in distribution_channel: 0\"\n[1] \"NULL values in is_repeated_guest: 0\"\n[1] \"NULL values in previous_cancellations: 0\"\n[1] \"NULL values in previous_bookings_not_canceled: 0\"\n[1] \"NULL values in reserved_room_type: 0\"\n[1] \"NULL values in assigned_room_type: 0\"\n[1] \"NULL values in booking_changes: 0\"\n[1] \"NULL values in deposit_type: 0\"\n[1] \"NULL values in agent: 0\"\n[1] \"NULL values in company: 0\"\n[1] \"NULL values in days_in_waiting_list: 0\"\n[1] \"NULL values in customer_type: 0\"\n[1] \"NULL values in adr: 0\"\n[1] \"NULL values in required_car_parking_spaces: 0\"\n[1] \"NULL values in total_of_special_requests: 0\"\n[1] \"NULL values in reservation_status: 0\"\n[1] \"NULL values in reservation_status_date: 0\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking which columns have character datatype and have value == \"NULL\"\nhotel_data_subset <- hotel_data%>%\n  select_if(is.character)\ncol <- colnames(hotel_data_subset)\nfor (c in col){\n    print(paste0(\"NULL values in \", c, \": \", sum(hotel_data[,c]==\"NULL\")))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"NULL values in hotel: 0\"\n[1] \"NULL values in arrival_date_month: 0\"\n[1] \"NULL values in meal: 0\"\n[1] \"NULL values in country: 488\"\n[1] \"NULL values in market_segment: 0\"\n[1] \"NULL values in distribution_channel: 0\"\n[1] \"NULL values in reserved_room_type: 0\"\n[1] \"NULL values in assigned_room_type: 0\"\n[1] \"NULL values in deposit_type: 0\"\n[1] \"NULL values in agent: 16340\"\n[1] \"NULL values in company: 112593\"\n[1] \"NULL values in customer_type: 0\"\n[1] \"NULL values in reservation_status: 0\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(unique(hotel_data$country))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 178\n```\n:::\n\n```{.r .cell-code}\ntable(hotel_data$country)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  ABW   AGO   AIA   ALB   AND   ARE   ARG   ARM   ASM   ATA   ATF   AUS   AUT \n    2   362     1    12     7    51   214     8     1     2     1   426  1263 \n  AZE   BDI   BEL   BEN   BFA   BGD   BGR   BHR   BHS   BIH   BLR   BOL   BRA \n   17     1  2342     3     1    12    75     5     1    13    26    10  2224 \n  BRB   BWA   CAF   CHE   CHL   CHN   CIV   CMR    CN   COL   COM   CPV   CRI \n    4     1     5  1730    65   999     6    10  1279    71     2    24    19 \n  CUB   CYM   CYP   CZE   DEU   DJI   DMA   DNK   DOM   DZA   ECU   EGY   ESP \n    8     1    51   171  7287     1     1   435    14   103    27    32  8568 \n  EST   ETH   FIN   FJI   FRA   FRO   GAB   GBR   GEO   GGY   GHA   GIB   GLP \n   83     3   447     1 10415     5     4 12129    22     3     4    18     2 \n  GNB   GRC   GTM   GUY   HKG   HND   HRV   HUN   IDN   IMN   IND   IRL   IRN \n    9   128     4     1    29     1   100   230    35     2   152  3375    83 \n  IRQ   ISL   ISR   ITA   JAM   JEY   JOR   JPN   KAZ   KEN   KHM   KIR   KNA \n   14    57   669  3766     6     8    21   197    19     6     2     1     2 \n  KOR   KWT   LAO   LBN   LBY   LCA   LIE   LKA   LTU   LUX   LVA   MAC   MAR \n  133    16     2    31     8     1     3     7    81   287    55    16   259 \n  MCO   MDG   MDV   MEX   MKD   MLI   MLT   MMR   MNE   MOZ   MRT   MUS   MWI \n    4     1    12    85    10     1    18     1     5    67     1     7     2 \n  MYS   MYT   NAM   NCL   NGA   NIC   NLD   NOR   NPL  NULL   NZL   OMN   PAK \n   28     2     1     1    34     1  2104   607     1   488    74    18    14 \n  PAN   PER   PHL   PLW   POL   PRI   PRT   PRY   PYF   QAT   ROU   RUS   RWA \n    9    29    40     1   919    12 48590     4     1    15   500   632     2 \n  SAU   SDN   SEN   SGP   SLE   SLV   SMR   SRB   STP   SUR   SVK   SVN   SWE \n   48     1    11    39     1     2     1   101     2     5    65    57  1024 \n  SYC   SYR   TGO   THA   TJK   TMP   TUN   TUR   TWN   TZA   UGA   UKR   UMI \n    2     3     2    59     9     3    39   248    51     5     2    68     1 \n  URY   USA   UZB   VEN   VGB   VNM   ZAF   ZMB   ZWE \n   32  2097     4    26     1     8    80     2     4 \n```\n:::\n:::\n\n\nWe can see that there are bookings from people belonging to 178 distinct countries. However, from the output of table() we can see that one country is given \"NULL\" as the value is unknown. Hence, we can say that there are 177 distinct countries in the hotel_bookings dataset. In future, we may have to drop the rows with \"NULL\" country if we plan to plot geospatial visualizations. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(hotel_data$agent)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    1    10   103   104   105   106   107    11   110   111   112   114   115 \n 7191   260    21    53    14     2     2   395    12    16    15     1   225 \n  117   118   119    12   121   122   126   127   128   129    13   132   133 \n    1    69   304   578    37     2    14    45    23    14    82   143    56 \n  134   135   138   139    14   141   142   143   144   146   147   148   149 \n  482     2   287     8  3640     6   137   172     1   124   156     4    28 \n   15   150   151   152   153   154   155   156   157   158   159    16   162 \n  402     5    56   183    25   193    94   190    61     1    89   246    37 \n  163   165   167   168    17   170   171   173   174   175   177   179   180 \n    7     1     3   184   241    93   607    29    22   195   347     2     4 \n  181   182   183   184   185   187    19   191   192   193   195   196   197 \n   59     8    45    52    78    24  1061   198    41    15   193   301     1 \n    2    20   201   205   208    21   210   211   213   214   215   216   219 \n  162   540    42    27   173   875     7     2     1     5    15     1    13 \n   22   220   223   227   229    23   232   234   235   236    24   240   241 \n  382   104    18     2   786    25     2   128    29   247    22 13922  1721 \n  242   243   244   245   247   248   249    25   250   251   252   253   254 \n  780   514     4    37     1   131    51     3  2870   220    29    87    29 \n  256   257   258    26   261   262   265   267   269    27   270   273   275 \n   24    24     3   401    38    22     1     1     2   450     6   349     8 \n  276   278    28   280   281   282   283   285   286   287   288   289    29 \n    8     1  1666     1    82     2     2     1    45     8    14     1   683 \n  290   291   294   295   296   298   299     3    30   300   301   302   303 \n   19     1     1     4    42   472     1  1336   484     1     1     3     2 \n  304   305   306   307   308    31   310   313   314   315    32   321   323 \n    1    45    35    14    54   162    25    36   927   284    15     3    25 \n  324   325   326   327   328    33   330   331   332   333   334   335   336 \n    9     6   165    20     9    31   125     2    55     1    28     4    23 \n  337   339    34   341   344   346   348    35   350   352   354   355   358 \n    1    77   294     4     8     1    22   109    28     1    14     4     1 \n  359    36   360   363   364   367   368    37   370   371   375   378    38 \n   21   100    15     6    19     1    45  1230     3     4    40    36   274 \n  384   385   387   388    39   390   391   393   394   397     4    40   403 \n    2    60    32     1   127    57     2    13    33     1    47  1039     4 \n  404   405   406   408    41   410   411   414   416   418    42   420   423 \n    2     5     1     1    75   133    16     2     1     8   211     3    19 \n  425   426   427   429   430   431   432   433   434   436   438    44   440 \n   16     3     3     5     4     1     1     1    33    49     2   292    56 \n  441   444   446   449    45   450   451   453   454   455   459   461   464 \n    7     1     1     2    32     1     1     1     2    19    16     2    98 \n  467   468   469    47   472   474   475   476   479   480   481   483   484 \n   39    49     2    50     1    17     8     2    32     1     8     1    11 \n  492   493   495   497     5    50   502   508   509   510    52   526   527 \n   28    35    57     1   330    20    24     6    10     2   137    10    35 \n   53   531   535    54    55    56    57    58    59     6    60    61    63 \n   18    68     3     1    16   375    28   335     1  3290    19     2    29 \n   64    66    67    68    69     7    70    71    72    73    74    75    77 \n   23    44   127   211    90  3539     1    73     6     1    20    73    33 \n   78    79     8    81    82    83    85    86    87    88    89     9    90 \n   37    47  1514     6    77   696   554   338    77    19    99 31961     1 \n   91    92    93    94    95    96    98    99  NULL \n   58     7     1   114   135   537   124    68 16340 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(hotel_data$company)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    10    100    101    102    103    104    105    106    107    108    109 \n     1      1      1      1     16      1      8      2      9     11      1 \n    11    110    112    113    115    116    118     12    120    122    126 \n     1     52     13     36      4      6      7     14     14     18      1 \n   127    130    132    135    137    139     14    140    142    143    144 \n    15     12      1     66      4      3      9      1      1     17     27 \n   146    148    149    150    153    154    158    159     16    160    163 \n     3     37      5     19    215    133      2      6      5      1     17 \n   165    167    168    169    174    178    179     18    180    183    184 \n     3      7      2     65    149     27     24      1      5     16      1 \n   185    186    192    193    195    197     20    200    202    203    204 \n     4     12      4     16     38     47     50      3     38     13     34 \n   207    209    210    212    213    215    216    217    218    219     22 \n     9     19      2      1      1      8     21      2     43    141      6 \n   220    221    222    223    224    225    227    229    230    232    233 \n     4     27      2    784      3      7     24      1      3      2    114 \n   234    237    238    240    242    243    245    246    250    251    253 \n     1      1     33      3     62      2      3      3      2     18      1 \n   254    255    257    258    259    260    263    264    268    269    270 \n    10      6      1      1      2      3     14      2     14     33     43 \n   271    272    273    274    275    277    278    279     28    280    281 \n     2      3      1     14      3      5      2      8      5     48    138 \n   282    284    286    287    288    289     29    290    291    292    293 \n     4      1     21      5      1      2      2     17     12     18      5 \n   297    301    302    304    305    307    308    309     31    311    312 \n     7      1      5      2      1     36     33      1     17      2      3 \n   313    314    316    317    318    319     32    320    321    323    324 \n     1      1      2      9      1      3      1      1      2     10      9 \n   325    329    330    331    332    333    334    337    338     34    341 \n     2     12      4     61      2     11      3     25     12      8      5 \n   342    343    346    347    348    349     35    350    351    352    353 \n    48     29     14      1     59      2      1      3      2      1      4 \n   355    356    357    358    360    361    362    364    365    366    367 \n    13     10      5      7     12      2      2      6     29     24     14 \n   368    369     37    370    371    372    373    376    377    378    379 \n     1      5     10      2     11      3      1      1      5      3      9 \n    38    380    382    383    384    385    386    388     39    390    391 \n    51     12      5      6      9     30      1      7      8     13      2 \n   392    393    394    395    396    397    398    399     40    400    401 \n     4      1      6      4     18     15      1     11    927      2      1 \n   402    403    405    407    408    409    410    411    412    413    415 \n     1      2    119     22     15     12      5      2      1      1      1 \n   416    417    418    419     42    420    421    422    423    424    425 \n     1      1     25      1      5      1      9      1      2     24      1 \n   426    428    429     43    433    435    436    437    439    442    443 \n     4     13      2     29      2     12      2      7      6      1      5 \n   444    445    446    447    448     45    450    451    452    454    455 \n     5      4      1      2      4    250     10      6      4      1      1 \n   456    457    458    459     46    460    461    465    466     47    470 \n     2      3      2      5     26      3      1     12      3     72      5 \n   477    478    479     48    481    482    483    484    485    486    487 \n    23      2      1      5      1      2      2      2     14      2      1 \n   489     49    490    491    492    494    496    497    498    499    501 \n     1      5      5      2      2      4      1      1     58      1      1 \n   504    506    507     51    511    512    513    514    515    516    518 \n    11      1     23     99      6      3      2      2      6      1      2 \n    52    520    521    523    525    528     53    530    531    534    539 \n     2      1      7     19     15      2      8      5      1      2      2 \n    54    541    543     59      6     61     62     64     65     67     68 \n     1      1      2      7      1      2     47      1      1    267     46 \n    71     72     73     76     77     78      8     80     81     82     83 \n     2     30      3      1      1     22      1      1     23     14      9 \n    84     85     86     88      9     91     92     93     94     96     99 \n     3      2     32     22     37     48     13      3     87      1     12 \n  NULL \n112593 \n```\n:::\n:::\n\n\nThe datatype is character for both the columns \"agent\" and \"company\" due to which the numbers are not sorted/arranged as expected. From the table() we notice that both the columns have all numerical values except for the \"NULL\" value which is used for the bookings which did not use an agent or a company for booking. If we change these \"NULL\" string values to a numerical value like -1 (as no negative values are being used in these columns), then we can change the column type to numeric.\n\n\nAs the first step of tidying the data, I dropped the rows with NA values in \"children\" column (4 rows to be exact).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dropping the rows with NA values in \"children\" column\nhotel_data <- hotel_data%>%\n  subset(!is.na(children))\nhotel_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 119,386 × 32\n   hotel  is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n   <chr>    <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n 1 Resor…       0     342    2015 July         27       1       0       0      2\n 2 Resor…       0     737    2015 July         27       1       0       0      2\n 3 Resor…       0       7    2015 July         27       1       0       1      1\n 4 Resor…       0      13    2015 July         27       1       0       1      1\n 5 Resor…       0      14    2015 July         27       1       0       2      2\n 6 Resor…       0      14    2015 July         27       1       0       2      2\n 7 Resor…       0       0    2015 July         27       1       0       2      2\n 8 Resor…       0       9    2015 July         27       1       0       2      2\n 9 Resor…       1      85    2015 July         27       1       0       3      2\n10 Resor…       1      75    2015 July         27       1       0       3      2\n# … with 119,376 more rows, 22 more variables: children <dbl>, babies <dbl>,\n#   meal <chr>, country <chr>, market_segment <chr>,\n#   distribution_channel <chr>, is_repeated_guest <dbl>,\n#   previous_cancellations <dbl>, previous_bookings_not_canceled <dbl>,\n#   reserved_room_type <chr>, assigned_room_type <chr>, booking_changes <dbl>,\n#   deposit_type <chr>, agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n\nNext, I replaced the \"NULL\" values with \"-1\" values in \"agent\" and \"company\" columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Replace the \"NULL\" values with \"-1\" in \"agent\" and \"company\" columns\nhotel_data <- hotel_data%>%\n  mutate(agent = str_replace(agent, \"NULL\", \"-1\"))%>%\n  mutate(company = str_replace(company, \"NULL\", \"-1\"))\n```\n:::\n\n\n\nI also checked that all values are numerical in the \"agent\" and \"company\" columns (i.e no \"NULL\" values).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sanity check: Checking that all values are numerical in the \"agent\" and \"company\" columns (i.e no \"NULL\" values)\ntable(hotel_data$agent)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   -1     1    10   103   104   105   106   107    11   110   111   112   114 \n16338  7191   260    21    53    14     2     2   395    12    16    15     1 \n  115   117   118   119    12   121   122   126   127   128   129    13   132 \n  225     1    69   304   578    37     2    14    45    23    14    82   143 \n  133   134   135   138   139    14   141   142   143   144   146   147   148 \n   56   482     2   287     8  3639     6   137   172     1   124   156     4 \n  149    15   150   151   152   153   154   155   156   157   158   159    16 \n   28   402     5    56   183    25   193    94   190    61     1    89   246 \n  162   163   165   167   168    17   170   171   173   174   175   177   179 \n   37     7     1     3   184   241    93   607    29    22   195   347     2 \n  180   181   182   183   184   185   187    19   191   192   193   195   196 \n    4    59     8    45    52    78    24  1061   198    41    15   193   301 \n  197     2    20   201   205   208    21   210   211   213   214   215   216 \n    1   162   540    42    27   173   875     7     2     1     5    15     1 \n  219    22   220   223   227   229    23   232   234   235   236    24   240 \n   13   382   104    18     2   786    25     2   128    29   247    22 13922 \n  241   242   243   244   245   247   248   249    25   250   251   252   253 \n 1721   780   514     4    37     1   131    51     3  2870   220    29    87 \n  254   256   257   258    26   261   262   265   267   269    27   270   273 \n   29    24    24     3   401    38    22     1     1     2   450     6   349 \n  275   276   278    28   280   281   282   283   285   286   287   288   289 \n    8     8     1  1666     1    82     2     2     1    45     8    14     1 \n   29   290   291   294   295   296   298   299     3    30   300   301   302 \n  683    19     1     1     4    42   472     1  1336   484     1     1     3 \n  303   304   305   306   307   308    31   310   313   314   315    32   321 \n    2     1    45    35    14    54   162    25    36   927   284    15     3 \n  323   324   325   326   327   328    33   330   331   332   333   334   335 \n   25     9     6   165    20     9    31   125     2    55     1    28     4 \n  336   337   339    34   341   344   346   348    35   350   352   354   355 \n   23     1    77   294     4     8     1    22   109    28     1    14     4 \n  358   359    36   360   363   364   367   368    37   370   371   375   378 \n    1    21   100    15     6    19     1    45  1230     3     4    40    36 \n   38   384   385   387   388    39   390   391   393   394   397     4    40 \n  274     2    60    32     1   127    57     2    13    33     1    47  1039 \n  403   404   405   406   408    41   410   411   414   416   418    42   420 \n    4     2     5     1     1    75   133    16     2     1     8   211     3 \n  423   425   426   427   429   430   431   432   433   434   436   438    44 \n   19    16     3     3     5     4     1     1     1    33    49     2   292 \n  440   441   444   446   449    45   450   451   453   454   455   459   461 \n   56     7     1     1     2    32     1     1     1     2    19    16     2 \n  464   467   468   469    47   472   474   475   476   479   480   481   483 \n   98    39    49     2    50     1    17     8     2    32     1     8     1 \n  484   492   493   495   497     5    50   502   508   509   510    52   526 \n   11    28    35    57     1   330    20    24     6    10     2   137    10 \n  527    53   531   535    54    55    56    57    58    59     6    60    61 \n   35    18    68     3     1    16   375    28   335     1  3290    19     2 \n   63    64    66    67    68    69     7    70    71    72    73    74    75 \n   29    23    44   127   211    90  3539     1    73     6     1    20    73 \n   77    78    79     8    81    82    83    85    86    87    88    89     9 \n   33    37    47  1514     6    77   696   554   338    77    19    99 31960 \n   90    91    92    93    94    95    96    98    99 \n    1    58     7     1   114   135   537   124    68 \n```\n:::\n\n```{.r .cell-code}\ntable(hotel_data$company)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    -1     10    100    101    102    103    104    105    106    107    108 \n112589      1      1      1      1     16      1      8      2      9     11 \n   109     11    110    112    113    115    116    118     12    120    122 \n     1      1     52     13     36      4      6      7     14     14     18 \n   126    127    130    132    135    137    139     14    140    142    143 \n     1     15     12      1     66      4      3      9      1      1     17 \n   144    146    148    149    150    153    154    158    159     16    160 \n    27      3     37      5     19    215    133      2      6      5      1 \n   163    165    167    168    169    174    178    179     18    180    183 \n    17      3      7      2     65    149     27     24      1      5     16 \n   184    185    186    192    193    195    197     20    200    202    203 \n     1      4     12      4     16     38     47     50      3     38     13 \n   204    207    209    210    212    213    215    216    217    218    219 \n    34      9     19      2      1      1      8     21      2     43    141 \n    22    220    221    222    223    224    225    227    229    230    232 \n     6      4     27      2    784      3      7     24      1      3      2 \n   233    234    237    238    240    242    243    245    246    250    251 \n   114      1      1     33      3     62      2      3      3      2     18 \n   253    254    255    257    258    259    260    263    264    268    269 \n     1     10      6      1      1      2      3     14      2     14     33 \n   270    271    272    273    274    275    277    278    279     28    280 \n    43      2      3      1     14      3      5      2      8      5     48 \n   281    282    284    286    287    288    289     29    290    291    292 \n   138      4      1     21      5      1      2      2     17     12     18 \n   293    297    301    302    304    305    307    308    309     31    311 \n     5      7      1      5      2      1     36     33      1     17      2 \n   312    313    314    316    317    318    319     32    320    321    323 \n     3      1      1      2      9      1      3      1      1      2     10 \n   324    325    329    330    331    332    333    334    337    338     34 \n     9      2     12      4     61      2     11      3     25     12      8 \n   341    342    343    346    347    348    349     35    350    351    352 \n     5     48     29     14      1     59      2      1      3      2      1 \n   353    355    356    357    358    360    361    362    364    365    366 \n     4     13     10      5      7     12      2      2      6     29     24 \n   367    368    369     37    370    371    372    373    376    377    378 \n    14      1      5     10      2     11      3      1      1      5      3 \n   379     38    380    382    383    384    385    386    388     39    390 \n     9     51     12      5      6      9     30      1      7      8     13 \n   391    392    393    394    395    396    397    398    399     40    400 \n     2      4      1      6      4     18     15      1     11    927      2 \n   401    402    403    405    407    408    409    410    411    412    413 \n     1      1      2    119     22     15     12      5      2      1      1 \n   415    416    417    418    419     42    420    421    422    423    424 \n     1      1      1     25      1      5      1      9      1      2     24 \n   425    426    428    429     43    433    435    436    437    439    442 \n     1      4     13      2     29      2     12      2      7      6      1 \n   443    444    445    446    447    448     45    450    451    452    454 \n     5      5      4      1      2      4    250     10      6      4      1 \n   455    456    457    458    459     46    460    461    465    466     47 \n     1      2      3      2      5     26      3      1     12      3     72 \n   470    477    478    479     48    481    482    483    484    485    486 \n     5     23      2      1      5      1      2      2      2     14      2 \n   487    489     49    490    491    492    494    496    497    498    499 \n     1      1      5      5      2      2      4      1      1     58      1 \n   501    504    506    507     51    511    512    513    514    515    516 \n     1     11      1     23     99      6      3      2      2      6      1 \n   518     52    520    521    523    525    528     53    530    531    534 \n     2      2      1      7     19     15      2      8      5      1      2 \n   539     54    541    543     59      6     61     62     64     65     67 \n     2      1      1      2      7      1      2     47      1      1    267 \n    68     71     72     73     76     77     78      8     80     81     82 \n    46      2     30      3      1      1     22      1      1     23     14 \n    83     84     85     86     88      9     91     92     93     94     96 \n     9      3      2     32     22     37     48     13      3     87      1 \n    99 \n    12 \n```\n:::\n:::\n\n\nFinally, I converted the datatype of \"agent\" and \"company\" columns from character to numeric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Converting the datatype of \"agent\" and \"company\" columns from character to numeric\nhotel_data <- hotel_data%>%\n  mutate(agent = as.numeric(agent))%>%\n  mutate(company = as.numeric(company))\n```\n:::\n\n\n\nI verified that the the new datatype of \"agent\" and \"company\" is numeric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sanity check: Verify the new datatype of \"agent\" and \"company\" is numeric\nstr(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [119,386 × 32] (S3: tbl_df/tbl/data.frame)\n $ hotel                         : chr [1:119386] \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" ...\n $ is_canceled                   : num [1:119386] 0 0 0 0 0 0 0 0 1 1 ...\n $ lead_time                     : num [1:119386] 342 737 7 13 14 14 0 9 85 75 ...\n $ arrival_date_year             : num [1:119386] 2015 2015 2015 2015 2015 ...\n $ arrival_date_month            : chr [1:119386] \"July\" \"July\" \"July\" \"July\" ...\n $ arrival_date_week_number      : num [1:119386] 27 27 27 27 27 27 27 27 27 27 ...\n $ arrival_date_day_of_month     : num [1:119386] 1 1 1 1 1 1 1 1 1 1 ...\n $ stays_in_weekend_nights       : num [1:119386] 0 0 0 0 0 0 0 0 0 0 ...\n $ stays_in_week_nights          : num [1:119386] 0 0 1 1 2 2 2 2 3 3 ...\n $ adults                        : num [1:119386] 2 2 1 1 2 2 2 2 2 2 ...\n $ children                      : num [1:119386] 0 0 0 0 0 0 0 0 0 0 ...\n $ babies                        : num [1:119386] 0 0 0 0 0 0 0 0 0 0 ...\n $ meal                          : chr [1:119386] \"BB\" \"BB\" \"BB\" \"BB\" ...\n $ country                       : chr [1:119386] \"PRT\" \"PRT\" \"GBR\" \"GBR\" ...\n $ market_segment                : chr [1:119386] \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ distribution_channel          : chr [1:119386] \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ is_repeated_guest             : num [1:119386] 0 0 0 0 0 0 0 0 0 0 ...\n $ previous_cancellations        : num [1:119386] 0 0 0 0 0 0 0 0 0 0 ...\n $ previous_bookings_not_canceled: num [1:119386] 0 0 0 0 0 0 0 0 0 0 ...\n $ reserved_room_type            : chr [1:119386] \"C\" \"C\" \"A\" \"A\" ...\n $ assigned_room_type            : chr [1:119386] \"C\" \"C\" \"C\" \"A\" ...\n $ booking_changes               : num [1:119386] 3 4 0 0 0 0 0 0 0 0 ...\n $ deposit_type                  : chr [1:119386] \"No Deposit\" \"No Deposit\" \"No Deposit\" \"No Deposit\" ...\n $ agent                         : num [1:119386] -1 -1 -1 304 240 240 -1 303 240 15 ...\n $ company                       : num [1:119386] -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ days_in_waiting_list          : num [1:119386] 0 0 0 0 0 0 0 0 0 0 ...\n $ customer_type                 : chr [1:119386] \"Transient\" \"Transient\" \"Transient\" \"Transient\" ...\n $ adr                           : num [1:119386] 0 0 75 75 98 ...\n $ required_car_parking_spaces   : num [1:119386] 0 0 0 0 0 0 0 0 0 0 ...\n $ total_of_special_requests     : num [1:119386] 0 0 0 0 1 1 0 1 1 0 ...\n $ reservation_status            : chr [1:119386] \"Check-Out\" \"Check-Out\" \"Check-Out\" \"Check-Out\" ...\n $ reservation_status_date       : Date[1:119386], format: \"2015-07-01\" \"2015-07-01\" ...\n```\n:::\n:::\n\n\n\n## Mutate Variables (as needed)\n\nAre there any variables that require mutation to be usable in your analysis stream? For example, do you need to calculate new values in order to graph them? Can string values be represented numerically? Do you need to turn any variables into factors and reorder for ease of graphics and visualization?\n\nDocument your work here.\n\nKnowing the demand i.e total guests staying in the booked hotel during a time frame would help in visualizing trends in the form of line plots. These trends would be helpful for tourists to identify the best time to visit Portugal and book the rooms earlier for a lesser price or for hotel management/travel agents to inflate the prices of the rooms according to the demand. We can calculate demand as the sum of adults, children and babies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate demand as the sum of adults, children and babies\nhotel_data <- hotel_data%>%\n  mutate(demand = adults+children+babies)\nhotel_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 119,386 × 33\n   hotel  is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n   <chr>    <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n 1 Resor…       0     342    2015 July         27       1       0       0      2\n 2 Resor…       0     737    2015 July         27       1       0       0      2\n 3 Resor…       0       7    2015 July         27       1       0       1      1\n 4 Resor…       0      13    2015 July         27       1       0       1      1\n 5 Resor…       0      14    2015 July         27       1       0       2      2\n 6 Resor…       0      14    2015 July         27       1       0       2      2\n 7 Resor…       0       0    2015 July         27       1       0       2      2\n 8 Resor…       0       9    2015 July         27       1       0       2      2\n 9 Resor…       1      85    2015 July         27       1       0       3      2\n10 Resor…       1      75    2015 July         27       1       0       3      2\n# … with 119,376 more rows, 23 more variables: children <dbl>, babies <dbl>,\n#   meal <chr>, country <chr>, market_segment <chr>,\n#   distribution_channel <chr>, is_repeated_guest <dbl>,\n#   previous_cancellations <dbl>, previous_bookings_not_canceled <dbl>,\n#   reserved_room_type <chr>, assigned_room_type <chr>, booking_changes <dbl>,\n#   deposit_type <chr>, agent <dbl>, company <dbl>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Interesting fact about demand\ntable(hotel_data$demand)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    0     1     2     3     4     5     6    10    12    20    26    27    40 \n  180 22581 82048 10494  3929   137     1     2     2     2     5     2     1 \n   50    55 \n    1     1 \n```\n:::\n\n```{.r .cell-code}\nhotel_data_demand0 <- hotel_data%>%\n  subset(demand==0)\n\ntable(hotel_data_demand0$reservation_status)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Canceled Check-Out   No-Show \n       24       155         1 \n```\n:::\n:::\n\n\nInteresting fact! After creating the \"demand\" attribute, I performed the table() and found that there are 180 bookings with the demand listed as 0. On checking the reservation status for these 180 rows, 155 bookings show that the reservation status is \"Check-Out\". According to the dataset, \"Check-Out\" is defined as – customer has checked in but already departed. It is surprising that the customer checked in and out but the demand is 0! Would like to know more about the reason behind this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine the columns \"arrival_date_year\", \"arrival_date_month\", \"arrival_date_day_of_month\" to get the arrival date in a single column. \nlibrary(lubridate)\nhotel_data <- hotel_data%>%\n  mutate(arrival_date = ymd(paste(hotel_data$arrival_date_year, hotel_data$arrival_date_month, hotel_data$arrival_date_day_of_month, sep=\"/\")))\n\n#Removing the columns related to date in the dataset except for the \"arrival_date\" mutated column\nhotel_data <- hotel_data%>%\n  select(-c(arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month))\n```\n:::\n\n\nI created a new column \"arrival_date\" which combined the data from \"arrival_date_year\", \"arrival_date_month\", and \"arrival_date_day_of_month\" to get the arrival date in a single column and removed the columns \"arrival_date_year\", \"arrival_date_month\", \"arrival_date_day_of_month\", and \"arrival_date_week_number\" as they are redundant data. The mutated \"arrival_date\" column will be useful to plot time-series visualizations and analyze trends.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the min and max arrival_date\nmin(hotel_data$arrival_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"2015-07-01\"\n```\n:::\n\n```{.r .cell-code}\nmax(hotel_data$arrival_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"2017-08-31\"\n```\n:::\n:::\n\n\nFrom the mutated variable \"arrival_date\" we can easily understand that the \"hotel_bookings\" dataset has data for the arrival period of \"2015-07-01\" to \"2017-08-31\".\n\n\nCurrently, the data contains information about the \"lead_time\" (Number of days that elapsed between the date of hotel booking and the arrival date) and the \"arrival_date\" at the hotel. It would be useful to create visualizations between the \"arrival_date\", \"booking_date\" and \"adr\" for insights. For this purpose, it would be suitable if the \"booking_date\" was calculated from \"arrival_date\" and the \"lead_time\". This will help customers to understand the right time to book hotels and the demand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating \"booking_date\" variable from \"arrival_date\" and \"lead_time\"\nhotel_data <- hotel_data%>%\n  mutate(booking_date = arrival_date - lead_time)\nhotel_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 119,386 × 31\n   hotel     is_ca…¹ lead_…² stays…³ stays…⁴ adults child…⁵ babies meal  country\n   <chr>       <dbl>   <dbl>   <dbl>   <dbl>  <dbl>   <dbl>  <dbl> <chr> <chr>  \n 1 Resort H…       0     342       0       0      2       0      0 BB    PRT    \n 2 Resort H…       0     737       0       0      2       0      0 BB    PRT    \n 3 Resort H…       0       7       0       1      1       0      0 BB    GBR    \n 4 Resort H…       0      13       0       1      1       0      0 BB    GBR    \n 5 Resort H…       0      14       0       2      2       0      0 BB    GBR    \n 6 Resort H…       0      14       0       2      2       0      0 BB    GBR    \n 7 Resort H…       0       0       0       2      2       0      0 BB    PRT    \n 8 Resort H…       0       9       0       2      2       0      0 FB    PRT    \n 9 Resort H…       1      85       0       3      2       0      0 BB    PRT    \n10 Resort H…       1      75       0       3      2       0      0 HB    PRT    \n# … with 119,376 more rows, 21 more variables: market_segment <chr>,\n#   distribution_channel <chr>, is_repeated_guest <dbl>,\n#   previous_cancellations <dbl>, previous_bookings_not_canceled <dbl>,\n#   reserved_room_type <chr>, assigned_room_type <chr>, booking_changes <dbl>,\n#   deposit_type <chr>, agent <dbl>, company <dbl>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>,\n#   total_of_special_requests <dbl>, reservation_status <chr>, …\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary of booking_date\nsummary(hotel_data$booking_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. \n\"2013-06-24\" \"2015-11-28\" \"2016-05-04\" \"2016-05-16\" \"2016-12-09\" \"2017-08-31\" \n```\n:::\n:::\n\n\nWe can see that the earliest hotel booking for the period of arrival from \"2015-07-01\" to \"2017-08-31\" was done on the date \"2013-06-24\". This is a lead_time of 737 days!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort the dataset based on arrival_date.\nhotel_data <- hotel_data%>%\n  arrange(arrival_date)\n```\n:::\n\n\nThe final dataset is sorted based on \"arrival_date\" in ascending order.\n\nAfter tidying the data and mutating variables, we are left with a dataset of 119386 rows/observations and 31 columns/variables. We can use this dataset to perform Time Dependent visualizations and Part-Whole relationships.\n\n\n## Time Dependent Visualization\n\nI am using line plots for the time dependent visualizations as line plot is an effective method of displaying relationship between two variables when one of the two variables represents time (arrival_date in this case). I want to visualize the demand of the hotels/total guests staying in the hotels on a daily basis for the time period of arrival dates \"2015-07-01\" to \"2017-08-31\".\n\nFirst, I plot a line plot representing the Total Guests count based on Arrival Date grouped by hotel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Line plot representing the Total Guests count based on Arrival Date grouped by hotel.\nggplot(hotel_data, aes(y=demand, x = arrival_date, group = hotel, color = hotel)) + \n  geom_line() +\n  labs(title = \"Total Guests (Adults+Children+Babies) based on Arrival Date\", \n       y = \"Total Guests (Adults+Children+Babies)\", x = \"Arrival Date\") +\n  theme(axis.text.x=element_text(angle=90, hjust=1))\n```\n\n::: {.cell-output-display}\n![](VinithaMaheswaran_Challenge6_files/figure-html/unnamed-chunk-51-1.png){width=960}\n:::\n:::\n\n\nFrom the above visualization, we can observe that the data points are overlapping and congested as the time series is on a daily basis. This makes it difficult to arrive at any insights. In order to make the trends more clear, I decided to group by the dataset on hotel and arrival_date and summarized the sum of demand and adr.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrouped_hotel_data <- hotel_data%>%\n  select(hotel, demand, arrival_date, adr)%>%\n  group_by(hotel, arrival_date)%>%\n  summarise(guest_total = sum(demand, na.rm=TRUE), adr_total = sum(adr, na.rm = TRUE))\ngrouped_hotel_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,586 × 4\n# Groups:   hotel [2]\n   hotel      arrival_date guest_total adr_total\n   <chr>      <date>             <dbl>     <dbl>\n 1 City Hotel 2015-07-01           143     7442.\n 2 City Hotel 2015-07-02            96     3158.\n 3 City Hotel 2015-07-03            28     1184.\n 4 City Hotel 2015-07-04            72     2442 \n 5 City Hotel 2015-07-05            15      532.\n 6 City Hotel 2015-07-06            59     1995.\n 7 City Hotel 2015-07-07            35     1254.\n 8 City Hotel 2015-07-08            79     2490.\n 9 City Hotel 2015-07-09            92     2952.\n10 City Hotel 2015-07-10            19      647.\n# … with 1,576 more rows\n```\n:::\n:::\n\n\n\nNext, I plotted a line plot using the grouped_hotel_data to represent the Total Guests count based on Arrival Date grouped by hotel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Line plot representing the Total Guests count based on Arrival Date .\nggplot(grouped_hotel_data, aes(y=guest_total, x = arrival_date, group = hotel, color = hotel)) + \n  geom_line() +\n  labs(title = \"Total Guests (Adults+Children+Babies) based on Arrival Date\", \n       y = \"Total Guests (Adults+Children+Babies)\", x = \"Arrival Date\") +\n  theme(axis.text.x=element_text(angle=90, hjust=1))\n```\n\n::: {.cell-output-display}\n![](VinithaMaheswaran_Challenge6_files/figure-html/unnamed-chunk-55-1.png){width=960}\n:::\n:::\n\n\nFrom the above visualization, we can observe that for the City Hotel, the months September and October had the highest number of guests as this is the best time to visit Portugal during Fall when the weather is warm and the crowd is relatively less compared to Summer. In general, for both the hotels, May and June had high demand (children and babies in particular) as this is the best time to stay in resort during Summer and enjoy outdoor activities with family. Hence, hotel management can price the rooms accordingly during peak season and off-season. For most of the months, City Hotel has more total guests than Resort Hotel.\n\n\nThen, I plotted a line plot using the grouped_hotel_data to represent the Total ADR based on Arrival Date grouped by hotel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Line plot representing the Total ADR based on Arrival Date .\nggplot(grouped_hotel_data, aes(y=adr_total, x = arrival_date, group = hotel, color = hotel)) + \n  geom_line() +\n  labs(title = \"Total ADR based on Arrival Date\", \n       y = \"Total ADR\", x = \"Arrival Date\") +\n  theme(axis.text.x=element_text(angle=90, hjust=1))\n```\n\n::: {.cell-output-display}\n![](VinithaMaheswaran_Challenge6_files/figure-html/unnamed-chunk-57-1.png){width=960}\n:::\n:::\n\n\nFrom the above visualization, we can observe that for all 3 years, the Resort Hotel has similar ADR as the City Hotel during August month. This may be because August is the best time to stay in resort during Summer and enjoy outdoor activities. Families tend to visit the Resort Hotel more during summer break with their kids and children. For most months of the year, City Hotel has more total ADR than Resort Hotel.\n\n\n## Visualizing Part-Whole Relationships\n\nFor visualizing Part-Whole Relationships, I plotted Grouped Bar graph and Stacked Bar graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouped Bar graph representing the distribution of meal for hotels.\n\nggplot(hotel_data, aes(x = meal, fill = hotel)) + \n  geom_bar(position=\"dodge\") +\n  labs(title = \"Distribution of Meal preference for Hotels\", \n       y = \"Count\", x = \"Meal\")\n```\n\n::: {.cell-output-display}\n![](VinithaMaheswaran_Challenge6_files/figure-html/unnamed-chunk-59-1.png){width=768}\n:::\n:::\n\nThe above visualization depicts the distribution of meal preference of the guests grouped by hotel. I chose a grouped bar graph as it allows us to compare the preference of different meal types by the guests. The grouped bar graph shows how the hotel variable changes within each meal type. The taller a bar is, the larger the count of meal type. Grouped bar graph also allows us to compare both the hotels side by side. From the above visualization, we can say that BB (Bed & Breakfast) meal type is preferred by most guests in both the hotels. We can do further analysis on the data to understand why BB is the most preferred meal type. One reason may be that families with kids and children prefer BB as it is less trouble. The order of preferred meal type for City Hotel is BB, SC, HB and FB.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Stacked Bar graph representing the distribution of Deposit Type for hotels.\n\nggplot(hotel_data, aes(x = deposit_type, fill = hotel)) + \n  geom_bar() +\n  labs(title = \"Distribution of Deposit Type for Hotels\", \n       y = \"Count\", x = \"Deposit Type\")\n```\n\n::: {.cell-output-display}\n![](VinithaMaheswaran_Challenge6_files/figure-html/unnamed-chunk-61-1.png){width=768}\n:::\n:::\n\n\nThe above visualization depicts the distribution of deposit type grouped by hotel. I chose a stacked bar graph as it allows us to compare the percentage of each data point to the overall value. The taller a bar is, the larger the count of deposit type. The stacked bar graph above shows the different deposit types and the proportion of hotel for each deposit type. From the above visualization, we can say that both the hotels have \"No Deposit\" deposit type for most of the bookings made. City hotel does not have any bookings with \"Refundable\" deposit type. City Hotel has more \"No Deposit\" and \"Non Refund\" deposit type than Resort Hotel. This makes sense as we have more hotel booking observations for City Hotel compared to Resort Hotel.\n",
    "supporting": [
      "VinithaMaheswaran_Challenge6_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}