{
  "hash": "53c47b8179b3ae9c071072ca68dd7c4b",
  "result": {
    "markdown": "---\ntitle: \"Challenge-2\"\nauthor: \"Said Arslan\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"09/20/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.5.0 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'stringr' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n\n## Read in the Data\n\n\nI have picked the railroad data for this challenge. It includes information about railroad employees in 2012.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad <- read.csv(\"_data/railroad_2012_clean_county.csv\")\n```\n:::\n\n\n\n\n\n## Describe the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n\n```{.r .cell-code}\nhead(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  state               county total_employees\n1    AE                  APO               2\n2    AK            ANCHORAGE               7\n3    AK FAIRBANKS NORTH STAR               2\n4    AK               JUNEAU               3\n5    AK    MATANUSKA-SUSITNA               2\n6    AK                SITKA               1\n```\n:::\n\n```{.r .cell-code}\nsummary(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n\n\nIn the dataset there are 2930 rows (observations) and 3 columns (variables). Each row gives the number of railroad employees in a county of a state.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(railroad$state))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(railroad$county))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(railroad$total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\nThere are no missing values.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_distinct(railroad$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 53\n```\n:::\n\n```{.r .cell-code}\nn_distinct(railroad$county)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1709\n```\n:::\n:::\n\n\nI would expect 51 distinct values under `state` column but there are 53.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(railroad$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"AE\" \"AK\" \"AL\" \"AP\" \"AR\" \"AZ\" \"CA\" \"CO\" \"CT\" \"DC\" \"DE\" \"FL\" \"GA\" \"HI\" \"IA\"\n[16] \"ID\" \"IL\" \"IN\" \"KS\" \"KY\" \"LA\" \"MA\" \"MD\" \"ME\" \"MI\" \"MN\" \"MO\" \"MS\" \"MT\" \"NC\"\n[31] \"ND\" \"NE\" \"NH\" \"NJ\" \"NM\" \"NV\" \"NY\" \"OH\" \"OK\" \"OR\" \"PA\" \"RI\" \"SC\" \"SD\" \"TN\"\n[46] \"TX\" \"UT\" \"VA\" \"VT\" \"WA\" \"WI\" \"WV\" \"WY\"\n```\n:::\n:::\n\n\nAll are state abbreviations except \"AE\" and \"AP\".\n\n\nOn the other hand, there are 2930 observations but 1709 distinct county names, which implies that there are a lot of counties with same name in different states.\n\n\n\n\n## Provide Grouped Summary Statistics\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(railroad$total_employees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 255432\n```\n:::\n:::\n\n\nThere are total of 255,432 railroad employees in the U.S. in 2012.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad %>% \n  group_by(state) %>% \n  summarise(total_employees= sum(total_employees),  \n            proportion= round(total_employees/sum(railroad$total_employees)*100,1)) %>% \n  arrange(desc(total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 3\n   state total_employees proportion\n   <chr>           <int>      <dbl>\n 1 TX              19839        7.8\n 2 IL              19131        7.5\n 3 NY              17050        6.7\n 4 NE              13176        5.2\n 5 CA              13137        5.1\n 6 PA              12769        5  \n 7 OH               9056        3.5\n 8 GA               8605        3.4\n 9 IN               8537        3.3\n10 MO               8419        3.3\n# … with 43 more rows\n```\n:::\n:::\n\n\nTop 3 states with the largest number of railroad employees are Texas, Illinois and New York. 7.8% of railroad employees in the country are from Texas.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad %>% \n  group_by(state, county) %>% \n  summarise(total_employees= sum(total_employees)) %>% \n  arrange(desc(total_employees)) %>% \n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n# Groups:   state [6]\n  state county           total_employees\n  <chr> <chr>                      <int>\n1 IL    COOK                        8207\n2 TX    TARRANT                     4235\n3 NE    DOUGLAS                     3797\n4 NY    SUFFOLK                     3685\n5 VA    INDEPENDENT CITY            3249\n6 FL    DUVAL                       3073\n```\n:::\n:::\n\n\nCounty Cook of Illiniois has the highest number of employees with 8,207. \n\n\n## Explain and Interpret\n\nGeographically large and populated states like Texas, Illinois have more employment which makes quite sense. If the dataset is merged with other datasets that includes information about such as geographical characteristics of states, population, length of railroads etc., very interesting further analysis can be made.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n:::\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n:::\n\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n:::\n\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}