{
  "hash": "7f1a02bad467042885ed0bc1ac1e9e4f",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Mariia Dubyk\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"10/05/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in the Data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds<-read_csv(\"_data/birds.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrename(birds,Domain.Code=п.їDomain.Code)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `rename()`:\n! Can't rename columns that don't exist.\n✖ Column `п.їDomain.Code` doesn't exist.\n```\n:::\n\n```{.r .cell-code}\nbirds <- birds [,c(\"Domain\", \"Area\", \"Element\", \"Item\", \"Year\", \"Unit\", \"Value\", \"Flag\", \"Flag.Description\")]\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `birds[, c(\"Domain\", \"Area\", \"Element\", \"Item\", \"Year\", \"Unit\", \"Value\", \"Flag\",\n    \"Flag.Description\")]`:\n! Can't subset columns that don't exist.\n✖ Column `Flag.Description` doesn't exist.\n```\n:::\n\n```{.r .cell-code}\nsummary(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Domain Code           Domain            Area Code        Area          \n Length:30977       Length:30977       Min.   :   1   Length:30977      \n Class :character   Class :character   1st Qu.:  79   Class :character  \n Mode  :character   Mode  :character   Median : 156   Mode  :character  \n                                       Mean   :1202                     \n                                       3rd Qu.: 231                     \n                                       Max.   :5504                     \n                                                                        \n  Element Code    Element            Item Code        Item          \n Min.   :5112   Length:30977       Min.   :1057   Length:30977      \n 1st Qu.:5112   Class :character   1st Qu.:1057   Class :character  \n Median :5112   Mode  :character   Median :1068   Mode  :character  \n Mean   :5112                      Mean   :1066                     \n 3rd Qu.:5112                      3rd Qu.:1072                     \n Max.   :5112                      Max.   :1083                     \n                                                                    \n   Year Code         Year          Unit               Value         \n Min.   :1961   Min.   :1961   Length:30977       Min.   :       0  \n 1st Qu.:1976   1st Qu.:1976   Class :character   1st Qu.:     171  \n Median :1992   Median :1992   Mode  :character   Median :    1800  \n Mean   :1991   Mean   :1991                      Mean   :   99411  \n 3rd Qu.:2005   3rd Qu.:2005                      3rd Qu.:   15404  \n Max.   :2018   Max.   :2018                      Max.   :23707134  \n                                                  NA's   :1036      \n     Flag           Flag Description  \n Length:30977       Length:30977      \n Class :character   Class :character  \n Mode  :character   Mode  :character  \n                                      \n                                      \n                                      \n                                      \n```\n:::\n\n```{.r .cell-code}\nlibrary(summarytools)\nprint(dfSummary(birds))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nbirds  \nDimensions: 30977 x 14  \nDuplicates: 0  \n\n----------------------------------------------------------------------------------------------------------------------------\nNo   Variable           Stats / Values                   Freqs (% of Valid)      Graph                  Valid      Missing  \n---- ------------------ -------------------------------- ----------------------- ---------------------- ---------- ---------\n1    Domain Code        1. QA                            30977 (100.0%)          IIIIIIIIIIIIIIIIIIII   30977      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n2    Domain             1. Live Animals                  30977 (100.0%)          IIIIIIIIIIIIIIIIIIII   30977      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n3    Area Code          Mean (sd) : 1201.7 (2099.4)      248 distinct values     :                      30977      0        \n     [numeric]          min < med < max:                                         :                      (100.0%)   (0.0%)   \n                        1 < 156 < 5504                                           :                                          \n                        IQR (CV) : 152 (1.7)                                     :                 .                        \n                                                                                 :                 :                        \n\n4    Area               1. Africa                          290 ( 0.9%)                                  30977      0        \n     [character]        2. Asia                            290 ( 0.9%)                                  (100.0%)   (0.0%)   \n                        3. Eastern Asia                    290 ( 0.9%)                                                      \n                        4. Egypt                           290 ( 0.9%)                                                      \n                        5. Europe                          290 ( 0.9%)                                                      \n                        6. France                          290 ( 0.9%)                                                      \n                        7. Greece                          290 ( 0.9%)                                                      \n                        8. Myanmar                         290 ( 0.9%)                                                      \n                        9. Northern Africa                 290 ( 0.9%)                                                      \n                        10. South-eastern Asia             290 ( 0.9%)                                                      \n                        [ 238 others ]                   28077 (90.6%)           IIIIIIIIIIIIIIIIII                         \n\n5    Element Code       1 distinct value                 5112 : 30977 (100.0%)   IIIIIIIIIIIIIIIIIIII   30977      0        \n     [numeric]                                                                                          (100.0%)   (0.0%)   \n\n6    Element            1. Stocks                        30977 (100.0%)          IIIIIIIIIIIIIIIIIIII   30977      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n7    Item Code          Mean (sd) : 1066.5 (9)           1057 : 13074 (42.2%)    IIIIIIII               30977      0        \n     [numeric]          min < med < max:                 1068 :  6909 (22.3%)    IIII                   (100.0%)   (0.0%)   \n                        1057 < 1068 < 1083               1072 :  4136 (13.4%)    II                                         \n                        IQR (CV) : 15 (0)                1079 :  5693 (18.4%)    III                                        \n                                                         1083 :  1165 ( 3.8%)                                               \n\n8    Item               1. Chickens                      13074 (42.2%)           IIIIIIII               30977      0        \n     [character]        2. Ducks                          6909 (22.3%)           IIII                   (100.0%)   (0.0%)   \n                        3. Geese and guinea fowls         4136 (13.4%)           II                                         \n                        4. Pigeons, other birds           1165 ( 3.8%)                                                      \n                        5. Turkeys                        5693 (18.4%)           III                                        \n\n9    Year Code          Mean (sd) : 1990.6 (16.7)        58 distinct values      . . .   . :   : : :    30977      0        \n     [numeric]          min < med < max:                                         : : : . : : : : : :    (100.0%)   (0.0%)   \n                        1961 < 1992 < 2018                                       : : : : : : : : : :                        \n                        IQR (CV) : 29 (0)                                        : : : : : : : : : :                        \n                                                                                 : : : : : : : : : :                        \n\n10   Year               Mean (sd) : 1990.6 (16.7)        58 distinct values      . . .   . :   : : :    30977      0        \n     [numeric]          min < med < max:                                         : : : . : : : : : :    (100.0%)   (0.0%)   \n                        1961 < 1992 < 2018                                       : : : : : : : : : :                        \n                        IQR (CV) : 29 (0)                                        : : : : : : : : : :                        \n                                                                                 : : : : : : : : : :                        \n\n11   Unit               1. 1000 Head                     30977 (100.0%)          IIIIIIIIIIIIIIIIIIII   30977      0        \n     [character]                                                                                        (100.0%)   (0.0%)   \n\n12   Value              Mean (sd) : 99410.6 (720611.4)   11495 distinct values   :                      29941      1036     \n     [numeric]          min < med < max:                                         :                      (96.7%)    (3.3%)   \n                        0 < 1800 < 23707134                                      :                                          \n                        IQR (CV) : 15233 (7.2)                                   :                                          \n                                                                                 :                                          \n\n13   Flag               1. *                              1494 ( 7.4%)           I                      20204      10773    \n     [character]        2. A                              6488 (32.1%)           IIIIII                 (65.2%)    (34.8%)  \n                        3. F                             10007 (49.5%)           IIIIIIIII                                  \n                        4. Im                             1213 ( 6.0%)           I                                          \n                        5. M                              1002 ( 5.0%)                                                      \n\n14   Flag Description   1. Aggregate, may include of      6488 (20.9%)           IIII                   30977      0        \n     [character]        2. Data not available             1002 ( 3.2%)                                  (100.0%)   (0.0%)   \n                        3. FAO data based on imputat      1213 ( 3.9%)                                                      \n                        4. FAO estimate                  10007 (32.3%)           IIIIII                                     \n                        5. Official data                 10773 (34.8%)           IIIIII                                     \n                        6. Unofficial figure              1494 ( 4.8%)                                                      \n----------------------------------------------------------------------------------------------------------------------------\n```\n:::\n\n```{.r .cell-code}\nview(dfSummary(birds))\narrange(birds, desc(Value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 30,977 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2018  2018\n 2 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2017  2017\n 3 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2016  2016\n 4 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2015  2015\n 5 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2014  2014\n 6 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2013  2013\n 7 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2012  2012\n 8 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2010  2010\n 9 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2011  2011\n10 QA           Live …    5000 World    5112 Stocks     1057 Chic…    2009  2009\n# … with 30,967 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n## Describe the data\n\nData set gives information about number of stocks of 5 types of birds (Chickens; Ducks; Geese and guinea fowls; Pigeons, other birds; Turkeys). We have information about their existence and the quantity in different geographic areas (countries, continents, world) from 1961 to 2018. The data set contains 30977 rows, so we have 30977 cases. Each case contains the name of an animal ('Item'), geographic region ('Area') and year ('Year'). Columns 'Unit' and 'Value' give information about the number of certain type of birds. 'Unit' is 1000 heads and 'Value' contains numbers from 0 (min) to 23707134 (max, refers to world). We also observe columns ‘Flag’ and ‘Flag. Description’ which probably refer to data source or the way data was gathered.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds<-birds%>%\n  filter(Flag == c(\"M\", \"Im\", \"F\",\"*\", \"(Empty string)\"))%>%\n  filter(Item == 'Chickens')\n\nbirds%>%\n  group_by(Year)%>%\n  select(\"Value\")%>%\n  summarise(Median = median (Value, na.rm = TRUE), Mean = mean (Value, na.rm = TRUE), SD = sd (Value, na.rm = TRUE), Min = min (Value, na.rm = TRUE), Max = max (Value, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 6\n    Year Median   Mean      SD   Min    Max\n   <dbl>  <dbl>  <dbl>   <dbl> <dbl>  <dbl>\n 1  1961   2000 31861. 120751.     2 530000\n 2  1962   1525 13065.  32937.    35 170000\n 3  1963   2650 39482. 161735.    10 780000\n 4  1964   2500  8315.  22758.    42 106500\n 5  1965   1095  3110    4125.     2  12000\n 6  1966   2600 41534. 130255.     3 587000\n 7  1967    970  8777.  26745.    27 138000\n 8  1968   4100  7884.  10644.    10  44500\n 9  1969   4250 58425. 208698.    75 912700\n10  1970    575  3367.   5163.     2  16700\n# … with 48 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds%>%\n  group_by(Year)%>%\n  select(\"Value\")%>%\n  summarise(Quantile = quantile (Value, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 290 × 2\n# Groups:   Year [58]\n    Year Quantile\n   <dbl>    <dbl>\n 1  1961       2 \n 2  1961     182.\n 3  1961    2000 \n 4  1961    6400 \n 5  1961  530000 \n 6  1962      35 \n 7  1962     165 \n 8  1962    1525 \n 9  1962    5150 \n10  1962  170000 \n# … with 280 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds%>%\n  group_by(Area)%>%\n  summarise(Median = median(Value, na.rm = TRUE), Mean = mean(Value, na.rm = TRUE), SD = sd (Value, na.rm = TRUE), Min = min (Value, na.rm = TRUE), Max = max (Value, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 181 × 6\n   Area                Median    Mean      SD   Min    Max\n   <chr>                <dbl>   <dbl>   <dbl> <dbl>  <dbl>\n 1 Afghanistan           6300  6180     719.   5000   6800\n 2 Albania               2800  2800      NA    2800   2800\n 3 Algeria             101500 90265.  45927.   9100 135018\n 4 American Samoa          39    42.8    15.9    25     80\n 5 Angola                5700  5471.   1155.   3600   6940\n 6 Antigua and Barbuda     90    92.8    34.6    50    150\n 7 Argentina            82500 79125   21006.  38000 105000\n 8 Armenia               3835  3835      49.5  3800   3870\n 9 Aruba                   NA   NaN      NA     Inf   -Inf\n10 Australia            21145 21145    1209.  20290  22000\n# … with 171 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds%>%\n  group_by(Area)%>%\n  select(\"Value\")%>%\n  summarise(Quantile = quantile (Value, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 905 × 2\n# Groups:   Area [181]\n   Area        Quantile\n   <chr>          <dbl>\n 1 Afghanistan     5000\n 2 Afghanistan     6100\n 3 Afghanistan     6300\n 4 Afghanistan     6700\n 5 Afghanistan     6800\n 6 Albania         2800\n 7 Albania         2800\n 8 Albania         2800\n 9 Albania         2800\n10 Albania         2800\n# … with 895 more rows\n```\n:::\n:::\n\n## Provide Grouped Summary Statistics\n\n - First, I filtered data to look at number of Chickens in different areas from 1961 to 2018.\n - I also removed continents to have only countries.\n - I organized data in two groups (By year and by area).\n\nFirst group organized by year. In the first table we can observe mean, median, sd, max, min of number of chicken stocks in each year. Quantile presented in the second table. In the third and fourth table, there are central tendency and dispersion for data grouped by area.\n\n### Explain and Interpret\n\nSummary statistics for the first group gives information on how the central tendency changed during observed years. We have only one type of birds, so we do not compare different birds, but look at how the number of stocks of chickens changed. Summary for the second group shows how central tendency and dispersion differs among countries.\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}