{
  "hash": "e4e9d6c2ac44687691a0a2723b0e4244",
  "result": {
    "markdown": "---\ntitle: \"Challenge-2\"\nauthor: \"Said Arslan\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"09/28/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(psych)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'psych'\n\nThe following objects are masked from 'package:ggplot2':\n\n    %+%, alpha\n```\n:::\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n## Read in the Data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings <- read.csv(\"_data/hotel_bookings.csv\")\n```\n:::\n\n\n## Describe the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 119390     32\n```\n:::\n\n```{.r .cell-code}\ncolnames(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"hotel\"                          \"is_canceled\"                   \n [3] \"lead_time\"                      \"arrival_date_year\"             \n [5] \"arrival_date_month\"             \"arrival_date_week_number\"      \n [7] \"arrival_date_day_of_month\"      \"stays_in_weekend_nights\"       \n [9] \"stays_in_week_nights\"           \"adults\"                        \n[11] \"children\"                       \"babies\"                        \n[13] \"meal\"                           \"country\"                       \n[15] \"market_segment\"                 \"distribution_channel\"          \n[17] \"is_repeated_guest\"              \"previous_cancellations\"        \n[19] \"previous_bookings_not_canceled\" \"reserved_room_type\"            \n[21] \"assigned_room_type\"             \"booking_changes\"               \n[23] \"deposit_type\"                   \"agent\"                         \n[25] \"company\"                        \"days_in_waiting_list\"          \n[27] \"customer_type\"                  \"adr\"                           \n[29] \"required_car_parking_spaces\"    \"total_of_special_requests\"     \n[31] \"reservation_status\"             \"reservation_status_date\"       \n```\n:::\n\n```{.r .cell-code}\ncolnames(hotel.bookings)[28] <- \"average_daily_rate\"\n\nhead(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         hotel is_canceled lead_time arrival_date_year arrival_date_month\n1 Resort Hotel           0       342              2015               July\n2 Resort Hotel           0       737              2015               July\n3 Resort Hotel           0         7              2015               July\n4 Resort Hotel           0        13              2015               July\n5 Resort Hotel           0        14              2015               July\n6 Resort Hotel           0        14              2015               July\n  arrival_date_week_number arrival_date_day_of_month stays_in_weekend_nights\n1                       27                         1                       0\n2                       27                         1                       0\n3                       27                         1                       0\n4                       27                         1                       0\n5                       27                         1                       0\n6                       27                         1                       0\n  stays_in_week_nights adults children babies meal country market_segment\n1                    0      2        0      0   BB     PRT         Direct\n2                    0      2        0      0   BB     PRT         Direct\n3                    1      1        0      0   BB     GBR         Direct\n4                    1      1        0      0   BB     GBR      Corporate\n5                    2      2        0      0   BB     GBR      Online TA\n6                    2      2        0      0   BB     GBR      Online TA\n  distribution_channel is_repeated_guest previous_cancellations\n1               Direct                 0                      0\n2               Direct                 0                      0\n3               Direct                 0                      0\n4            Corporate                 0                      0\n5                TA/TO                 0                      0\n6                TA/TO                 0                      0\n  previous_bookings_not_canceled reserved_room_type assigned_room_type\n1                              0                  C                  C\n2                              0                  C                  C\n3                              0                  A                  C\n4                              0                  A                  A\n5                              0                  A                  A\n6                              0                  A                  A\n  booking_changes deposit_type agent company days_in_waiting_list customer_type\n1               3   No Deposit  NULL    NULL                    0     Transient\n2               4   No Deposit  NULL    NULL                    0     Transient\n3               0   No Deposit  NULL    NULL                    0     Transient\n4               0   No Deposit   304    NULL                    0     Transient\n5               0   No Deposit   240    NULL                    0     Transient\n6               0   No Deposit   240    NULL                    0     Transient\n  average_daily_rate required_car_parking_spaces total_of_special_requests\n1                  0                           0                         0\n2                  0                           0                         0\n3                 75                           0                         0\n4                 75                           0                         0\n5                 98                           0                         1\n6                 98                           0                         1\n  reservation_status reservation_status_date\n1          Check-Out              2015-07-01\n2          Check-Out              2015-07-01\n3          Check-Out              2015-07-02\n4          Check-Out              2015-07-02\n5          Check-Out              2015-07-03\n6          Check-Out              2015-07-03\n```\n:::\n\n```{.r .cell-code}\ntail(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            hotel is_canceled lead_time arrival_date_year arrival_date_month\n119385 City Hotel           0        21              2017             August\n119386 City Hotel           0        23              2017             August\n119387 City Hotel           0       102              2017             August\n119388 City Hotel           0        34              2017             August\n119389 City Hotel           0       109              2017             August\n119390 City Hotel           0       205              2017             August\n       arrival_date_week_number arrival_date_day_of_month\n119385                       35                        30\n119386                       35                        30\n119387                       35                        31\n119388                       35                        31\n119389                       35                        31\n119390                       35                        29\n       stays_in_weekend_nights stays_in_week_nights adults children babies meal\n119385                       2                    5      2        0      0   BB\n119386                       2                    5      2        0      0   BB\n119387                       2                    5      3        0      0   BB\n119388                       2                    5      2        0      0   BB\n119389                       2                    5      2        0      0   BB\n119390                       2                    7      2        0      0   HB\n       country market_segment distribution_channel is_repeated_guest\n119385     BEL  Offline TA/TO                TA/TO                 0\n119386     BEL  Offline TA/TO                TA/TO                 0\n119387     FRA      Online TA                TA/TO                 0\n119388     DEU      Online TA                TA/TO                 0\n119389     GBR      Online TA                TA/TO                 0\n119390     DEU      Online TA                TA/TO                 0\n       previous_cancellations previous_bookings_not_canceled reserved_room_type\n119385                      0                              0                  A\n119386                      0                              0                  A\n119387                      0                              0                  E\n119388                      0                              0                  D\n119389                      0                              0                  A\n119390                      0                              0                  A\n       assigned_room_type booking_changes deposit_type agent company\n119385                  A               0   No Deposit   394    NULL\n119386                  A               0   No Deposit   394    NULL\n119387                  E               0   No Deposit     9    NULL\n119388                  D               0   No Deposit     9    NULL\n119389                  A               0   No Deposit    89    NULL\n119390                  A               0   No Deposit     9    NULL\n       days_in_waiting_list customer_type average_daily_rate\n119385                    0     Transient              96.14\n119386                    0     Transient              96.14\n119387                    0     Transient             225.43\n119388                    0     Transient             157.71\n119389                    0     Transient             104.40\n119390                    0     Transient             151.20\n       required_car_parking_spaces total_of_special_requests reservation_status\n119385                           0                         2          Check-Out\n119386                           0                         0          Check-Out\n119387                           0                         2          Check-Out\n119388                           0                         4          Check-Out\n119389                           0                         0          Check-Out\n119390                           0                         2          Check-Out\n       reservation_status_date\n119385              2017-09-06\n119386              2017-09-06\n119387              2017-09-07\n119388              2017-09-07\n119389              2017-09-07\n119390              2017-09-07\n```\n:::\n\n```{.r .cell-code}\nstr(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t119390 obs. of  32 variables:\n $ hotel                         : chr  \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" ...\n $ is_canceled                   : int  0 0 0 0 0 0 0 0 1 1 ...\n $ lead_time                     : int  342 737 7 13 14 14 0 9 85 75 ...\n $ arrival_date_year             : int  2015 2015 2015 2015 2015 2015 2015 2015 2015 2015 ...\n $ arrival_date_month            : chr  \"July\" \"July\" \"July\" \"July\" ...\n $ arrival_date_week_number      : int  27 27 27 27 27 27 27 27 27 27 ...\n $ arrival_date_day_of_month     : int  1 1 1 1 1 1 1 1 1 1 ...\n $ stays_in_weekend_nights       : int  0 0 0 0 0 0 0 0 0 0 ...\n $ stays_in_week_nights          : int  0 0 1 1 2 2 2 2 3 3 ...\n $ adults                        : int  2 2 1 1 2 2 2 2 2 2 ...\n $ children                      : int  0 0 0 0 0 0 0 0 0 0 ...\n $ babies                        : int  0 0 0 0 0 0 0 0 0 0 ...\n $ meal                          : chr  \"BB\" \"BB\" \"BB\" \"BB\" ...\n $ country                       : chr  \"PRT\" \"PRT\" \"GBR\" \"GBR\" ...\n $ market_segment                : chr  \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ distribution_channel          : chr  \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ is_repeated_guest             : int  0 0 0 0 0 0 0 0 0 0 ...\n $ previous_cancellations        : int  0 0 0 0 0 0 0 0 0 0 ...\n $ previous_bookings_not_canceled: int  0 0 0 0 0 0 0 0 0 0 ...\n $ reserved_room_type            : chr  \"C\" \"C\" \"A\" \"A\" ...\n $ assigned_room_type            : chr  \"C\" \"C\" \"C\" \"A\" ...\n $ booking_changes               : int  3 4 0 0 0 0 0 0 0 0 ...\n $ deposit_type                  : chr  \"No Deposit\" \"No Deposit\" \"No Deposit\" \"No Deposit\" ...\n $ agent                         : chr  \"NULL\" \"NULL\" \"NULL\" \"304\" ...\n $ company                       : chr  \"NULL\" \"NULL\" \"NULL\" \"NULL\" ...\n $ days_in_waiting_list          : int  0 0 0 0 0 0 0 0 0 0 ...\n $ customer_type                 : chr  \"Transient\" \"Transient\" \"Transient\" \"Transient\" ...\n $ average_daily_rate            : num  0 0 75 75 98 ...\n $ required_car_parking_spaces   : int  0 0 0 0 0 0 0 0 0 0 ...\n $ total_of_special_requests     : int  0 0 0 0 1 1 0 1 1 0 ...\n $ reservation_status            : chr  \"Check-Out\" \"Check-Out\" \"Check-Out\" \"Check-Out\" ...\n $ reservation_status_date       : chr  \"2015-07-01\" \"2015-07-01\" \"2015-07-02\" \"2015-07-02\" ...\n```\n:::\n\n```{.r .cell-code}\ntable(sapply(hotel.bookings, function(x) typeof(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\ncharacter    double   integer \n       14         1        17 \n```\n:::\n\n```{.r .cell-code}\nsapply(\n  hotel.bookings, function(x) n_distinct(x)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         hotel                    is_canceled \n                             2                              2 \n                     lead_time              arrival_date_year \n                           479                              3 \n            arrival_date_month       arrival_date_week_number \n                            12                             53 \n     arrival_date_day_of_month        stays_in_weekend_nights \n                            31                             17 \n          stays_in_week_nights                         adults \n                            35                             14 \n                      children                         babies \n                             6                              5 \n                          meal                        country \n                             5                            178 \n                market_segment           distribution_channel \n                             8                              5 \n             is_repeated_guest         previous_cancellations \n                             2                             15 \nprevious_bookings_not_canceled             reserved_room_type \n                            73                             10 \n            assigned_room_type                booking_changes \n                            12                             21 \n                  deposit_type                          agent \n                             3                            334 \n                       company           days_in_waiting_list \n                           353                            128 \n                 customer_type             average_daily_rate \n                             4                           8879 \n   required_car_parking_spaces      total_of_special_requests \n                             5                              6 \n            reservation_status        reservation_status_date \n                             3                            926 \n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$hotel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Resort Hotel\" \"City Hotel\"  \n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$arrival_date_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2015 2016 2017\n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$reservation_status)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Check-Out\" \"Canceled\"  \"No-Show\"  \n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$distribution_channel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Direct\"    \"Corporate\" \"TA/TO\"     \"Undefined\" \"GDS\"      \n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$customer_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Transient\"       \"Contract\"        \"Transient-Party\" \"Group\"          \n```\n:::\n:::\n\n\n\nIn this dataset there are 32 variables(columns) and 119,390 observations(rows). By looking at the variable names, we can say that the it consists of reservation data of some hotels. 14 of the variables compose of character values, 18 of the variables store numerical values. That being said, some of the character variables and some of the numeric variables are actually indicate dates. \n\nAll of the variable names are descriptive enough except `adr`. After googling \"adr\", I found out that it means \"average daily rate\", which makes great sense for a dataset of hotel reservations. Therefore, I changed original column name `adr` with `average_daily_rate`.\n\nThere are two types of hotels in the dataset: Resort Hotel and City Hotel. Reservations are made in 2015, 2016 and 2017. The data covers reservations from 178 countries. So the data should belong to a big worldwide hotels chain. Both canceled and completed reservations are stored in the dataset as well as no-shows. Thus, each observation includes information about a reservation such as what type of hotel and in which country the reservation is for, number of visitors, dates, daily rates, stay durations and some categorical info about customer and the channel of reservation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings <- mutate(\n  hotel.bookings, \n  number_of_guests = adults + children + babies,\n  total_stay = stays_in_weekend_nights + stays_in_week_nights) # adding two new variables\n\ndescribe(\n  hotel.bookings[, c(\n    \"is_canceled\", \n    \"lead_time\", \n    \"arrival_date_year\",\n    \"arrival_date_week_number\",\n    \"arrival_date_day_of_month\",\n    \"stays_in_weekend_nights\",\n    \"stays_in_week_nights\",\n    \"total_stay\",\n    \"adults\",\n    \"children\",\n    \"babies\",\n    \"number_of_guests\",\n    \"is_repeated_guest\",\n    \"previous_cancellations\",\n    \"previous_bookings_not_canceled\",\n    \"booking_changes\",\n    \"days_in_waiting_list\",\n    \"average_daily_rate\",\n    \"required_car_parking_spaces\",\n    \"total_of_special_requests\"\n    )\n    ])[,c(\"n\", \"mean\", \"sd\", \"median\", \"min\",\"max\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                    n    mean     sd  median     min  max\nis_canceled                    119390    0.37   0.48    0.00    0.00    1\nlead_time                      119390  104.01 106.86   69.00    0.00  737\narrival_date_year              119390 2016.16   0.71 2016.00 2015.00 2017\narrival_date_week_number       119390   27.17  13.61   28.00    1.00   53\narrival_date_day_of_month      119390   15.80   8.78   16.00    1.00   31\nstays_in_weekend_nights        119390    0.93   1.00    1.00    0.00   19\nstays_in_week_nights           119390    2.50   1.91    2.00    0.00   50\ntotal_stay                     119390    3.43   2.56    3.00    0.00   69\nadults                         119390    1.86   0.58    2.00    0.00   55\nchildren                       119386    0.10   0.40    0.00    0.00   10\nbabies                         119390    0.01   0.10    0.00    0.00   10\nnumber_of_guests               119386    1.97   0.72    2.00    0.00   55\nis_repeated_guest              119390    0.03   0.18    0.00    0.00    1\nprevious_cancellations         119390    0.09   0.84    0.00    0.00   26\nprevious_bookings_not_canceled 119390    0.14   1.50    0.00    0.00   72\nbooking_changes                119390    0.22   0.65    0.00    0.00   21\ndays_in_waiting_list           119390    2.32  17.59    0.00    0.00  391\naverage_daily_rate             119390  101.83  50.54   94.58   -6.38 5400\nrequired_car_parking_spaces    119390    0.06   0.25    0.00    0.00    8\ntotal_of_special_requests      119390    0.57   0.79    0.00    0.00    5\n```\n:::\n:::\n\nIn this table, we can see some descriptive statistics for numeric variables in the data. For example, 37% of the reservations are actually canceled. On average, reservations are made 104 days before date of stay. On average, every reservation is made for 1.97 people. Approximately one out of 10 reservations involves a child or a baby. Average stay duration is 3.43 days. 22% of the booking is changed afterwards. Lastly, average daily rate of hotels is $101.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(hotel.bookings))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         hotel                    is_canceled \n                             0                              0 \n                     lead_time              arrival_date_year \n                             0                              0 \n            arrival_date_month       arrival_date_week_number \n                             0                              0 \n     arrival_date_day_of_month        stays_in_weekend_nights \n                             0                              0 \n          stays_in_week_nights                         adults \n                             0                              0 \n                      children                         babies \n                             4                              0 \n                          meal                        country \n                             0                              0 \n                market_segment           distribution_channel \n                             0                              0 \n             is_repeated_guest         previous_cancellations \n                             0                              0 \nprevious_bookings_not_canceled             reserved_room_type \n                             0                              0 \n            assigned_room_type                booking_changes \n                             0                              0 \n                  deposit_type                          agent \n                             0                              0 \n                       company           days_in_waiting_list \n                             0                              0 \n                 customer_type             average_daily_rate \n                             0                              0 \n   required_car_parking_spaces      total_of_special_requests \n                             0                              0 \n            reservation_status        reservation_status_date \n                             0                              0 \n              number_of_guests                     total_stay \n                             4                              0 \n```\n:::\n\n```{.r .cell-code}\nsapply(hotel.bookings, function(x) table(grepl(\"NULL\", x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$hotel\n\n FALSE \n119390 \n\n$is_canceled\n\n FALSE \n119390 \n\n$lead_time\n\n FALSE \n119390 \n\n$arrival_date_year\n\n FALSE \n119390 \n\n$arrival_date_month\n\n FALSE \n119390 \n\n$arrival_date_week_number\n\n FALSE \n119390 \n\n$arrival_date_day_of_month\n\n FALSE \n119390 \n\n$stays_in_weekend_nights\n\n FALSE \n119390 \n\n$stays_in_week_nights\n\n FALSE \n119390 \n\n$adults\n\n FALSE \n119390 \n\n$children\n\n FALSE \n119390 \n\n$babies\n\n FALSE \n119390 \n\n$meal\n\n FALSE \n119390 \n\n$country\n\n FALSE   TRUE \n118902    488 \n\n$market_segment\n\n FALSE \n119390 \n\n$distribution_channel\n\n FALSE \n119390 \n\n$is_repeated_guest\n\n FALSE \n119390 \n\n$previous_cancellations\n\n FALSE \n119390 \n\n$previous_bookings_not_canceled\n\n FALSE \n119390 \n\n$reserved_room_type\n\n FALSE \n119390 \n\n$assigned_room_type\n\n FALSE \n119390 \n\n$booking_changes\n\n FALSE \n119390 \n\n$deposit_type\n\n FALSE \n119390 \n\n$agent\n\n FALSE   TRUE \n103050  16340 \n\n$company\n\n FALSE   TRUE \n  6797 112593 \n\n$days_in_waiting_list\n\n FALSE \n119390 \n\n$customer_type\n\n FALSE \n119390 \n\n$average_daily_rate\n\n FALSE \n119390 \n\n$required_car_parking_spaces\n\n FALSE \n119390 \n\n$total_of_special_requests\n\n FALSE \n119390 \n\n$reservation_status\n\n FALSE \n119390 \n\n$reservation_status_date\n\n FALSE \n119390 \n\n$number_of_guests\n\n FALSE \n119390 \n\n$total_stay\n\n FALSE \n119390 \n```\n:::\n\n```{.r .cell-code}\nround(100*prop.table(table(grepl(\"NULL\", hotel.bookings$country))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n99.59  0.41 \n```\n:::\n\n```{.r .cell-code}\nround(100*prop.table(table(grepl(\"NULL\", hotel.bookings$agent))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n86.31 13.69 \n```\n:::\n\n```{.r .cell-code}\nround(100*prop.table(table(grepl(\"NULL\", hotel.bookings$company))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n 5.69 94.31 \n```\n:::\n:::\n\n\nIn terms of numerical variables, only 4 value is missing. However, 0.41% of country info, 13.89% of agent info and 94.31% of company info of reservations are missing.\n\n\n## Grouped Summary Statistics\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  select(hotel, average_daily_rate) %>% \n  group_by(hotel) %>% \n  summarise_if(is.numeric, list(min = min, max = max, mean = mean, std_dev = sd, median = median), na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  hotel          min   max  mean std_dev median\n  <chr>        <dbl> <dbl> <dbl>   <dbl>  <dbl>\n1 City Hotel    0     5400 105.     43.6   99.9\n2 Resort Hotel -6.38   508  95.0    61.4   75  \n```\n:::\n\n```{.r .cell-code}\nhotel.bookings %>% \n  select(country) %>% \n  group_by(country) %>% \n  count() %>% \n  arrange(desc(n)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n# Groups:   country [10]\n   country     n\n   <chr>   <int>\n 1 PRT     48590\n 2 GBR     12129\n 3 FRA     10415\n 4 ESP      8568\n 5 DEU      7287\n 6 ITA      3766\n 7 IRL      3375\n 8 BEL      2342\n 9 BRA      2224\n10 NLD      2104\n```\n:::\n\n```{.r .cell-code}\nhotel.bookings %>% \n  select(country, is_canceled) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, sum, na.rm = TRUE) %>% \n  arrange(desc(is_canceled)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   country is_canceled\n   <chr>         <int>\n 1 PRT           27519\n 2 GBR            2453\n 3 ESP            2177\n 4 FRA            1934\n 5 ITA            1333\n 6 DEU            1218\n 7 IRL             832\n 8 BRA             830\n 9 USA             501\n10 BEL             474\n```\n:::\n\n```{.r .cell-code}\nhotel.bookings %>% \n  filter(country %in% c(\"PRT\", \"GBR\", \"ESP\", \"FRA\", \"ITA\")) %>% \n  select(country,is_canceled) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, mean, na.rm = TRUE) %>% \n  arrange(desc(is_canceled))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 2\n  country is_canceled\n  <chr>         <dbl>\n1 PRT           0.566\n2 ITA           0.354\n3 ESP           0.254\n4 GBR           0.202\n5 FRA           0.186\n```\n:::\n\n```{.r .cell-code}\nhotel.bookings %>% \n  filter(reservation_status == \"Check-Out\") %>% \n  select(country, number_of_guests) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, sum, na.rm = TRUE) %>% \n  arrange(desc(number_of_guests)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   country number_of_guests\n   <chr>              <int>\n 1 PRT                37670\n 2 GBR                19258\n 3 FRA                17299\n 4 ESP                13213\n 5 DEU                11659\n 6 IRL                 5102\n 7 ITA                 4894\n 8 BEL                 3855\n 9 NLD                 3374\n10 USA                 3212\n```\n:::\n\n```{.r .cell-code}\nhotel.bookings %>% \n  filter(reservation_status == \"Check-Out\") %>% \n  select(country, number_of_guests) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, sum, na.rm = TRUE) %>% \n  arrange(desc(number_of_guests)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   country number_of_guests\n   <chr>              <int>\n 1 PRT                37670\n 2 GBR                19258\n 3 FRA                17299\n 4 ESP                13213\n 5 DEU                11659\n 6 IRL                 5102\n 7 ITA                 4894\n 8 BEL                 3855\n 9 NLD                 3374\n10 USA                 3212\n```\n:::\n\n```{.r .cell-code}\nhotel.bookings %>% \n  select(country, average_daily_rate) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, mean, na.rm = TRUE) %>% \n  arrange(desc(average_daily_rate)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   country average_daily_rate\n   <chr>                <dbl>\n 1 DJI                   273 \n 2 AIA                   265 \n 3 AND                   203.\n 4 UMI                   200 \n 5 LAO                   182.\n 6 MYT                   178.\n 7 NCL                   176.\n 8 GEO                   169.\n 9 COM                   165.\n10 FRO                   155.\n```\n:::\n\n```{.r .cell-code}\ntable(hotel.bookings$arrival_date_month)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    April    August  December  February   January      July      June     March \n    11089     13877      6780      8068      5929     12661     10939      9794 \n      May  November   October September \n    11791      6794     11160     10508 \n```\n:::\n:::\n\n\n### Explain and Interpret\n\nAverage daily rate for City Hotels is $11 higher than Resort Hotels. Another interesting point is price range for City Hotels very large. Daily rate of a city hotel may go up to $5400 while it is only $508 for resort hotels.\n\nThe most popular 10 countries in terms of total reservations are Portugal, Great Britain, France, Spain, Germany, Italy, Ireland, Belgium, Brasil and Netherlands. However, we can see that 56% reservations made for Portugal hotels are actually canceled. This ratio is 35% for Italy and 25% for Spain. \nNevertheless, among all of them, the country that hosts the highest number of guests is Portugal with total of 37,670 guests in 3 years.\n\nInterestingly, in terms of average daily rate, the most expensive hotels are in Djibouti, Anguilla, Andorra, United States Minor Outlying Islands, Laos and so on. It looks that hotels in small countries that host a small number of guests are much more expensive.\n\nAugust, July and May, respectively, are the months when hotels are the busiest throughout the year.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}