{
  "hash": "bf5daa01640fb87b076ba219c4c9acce",
  "result": {
    "markdown": "---\ntitle: \"Challenge-1\"\nauthor: \"Said Arslan\"\ndesription: \"Reading in data and creating a post\"\ndate: \"09/25/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - birds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\nI will analyze the `birds.csv` dataset in this challenge.\n\n## Read Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds <- read.csv(\"_data/birds.csv\")\n```\n:::\n\n\n`birds` variable is created to internalize the dataset so I can analyze and manipulate it.\n\n## Describe the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30977    14\n```\n:::\n\n```{.r .cell-code}\nhead(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Domain.Code       Domain Area.Code        Area Element.Code Element Item.Code\n1          QA Live Animals         2 Afghanistan         5112  Stocks      1057\n2          QA Live Animals         2 Afghanistan         5112  Stocks      1057\n3          QA Live Animals         2 Afghanistan         5112  Stocks      1057\n4          QA Live Animals         2 Afghanistan         5112  Stocks      1057\n5          QA Live Animals         2 Afghanistan         5112  Stocks      1057\n6          QA Live Animals         2 Afghanistan         5112  Stocks      1057\n      Item Year.Code Year      Unit Value Flag Flag.Description\n1 Chickens      1961 1961 1000 Head  4700    F     FAO estimate\n2 Chickens      1962 1962 1000 Head  4900    F     FAO estimate\n3 Chickens      1963 1963 1000 Head  5000    F     FAO estimate\n4 Chickens      1964 1964 1000 Head  5300    F     FAO estimate\n5 Chickens      1965 1965 1000 Head  5500    F     FAO estimate\n6 Chickens      1966 1966 1000 Head  5800    F     FAO estimate\n```\n:::\n\n```{.r .cell-code}\ntail(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Domain.Code       Domain Area.Code      Area Element.Code Element\n30972          QA Live Animals      5504 Polynesia         5112  Stocks\n30973          QA Live Animals      5504 Polynesia         5112  Stocks\n30974          QA Live Animals      5504 Polynesia         5112  Stocks\n30975          QA Live Animals      5504 Polynesia         5112  Stocks\n30976          QA Live Animals      5504 Polynesia         5112  Stocks\n30977          QA Live Animals      5504 Polynesia         5112  Stocks\n      Item.Code  Item Year.Code Year      Unit Value Flag\n30972      1068 Ducks      2013 2013 1000 Head    30    A\n30973      1068 Ducks      2014 2014 1000 Head    30    A\n30974      1068 Ducks      2015 2015 1000 Head    30    A\n30975      1068 Ducks      2016 2016 1000 Head    31    A\n30976      1068 Ducks      2017 2017 1000 Head    30    A\n30977      1068 Ducks      2018 2018 1000 Head    30    A\n                                                                  Flag.Description\n30972 Aggregate, may include official, semi-official, estimated or calculated data\n30973 Aggregate, may include official, semi-official, estimated or calculated data\n30974 Aggregate, may include official, semi-official, estimated or calculated data\n30975 Aggregate, may include official, semi-official, estimated or calculated data\n30976 Aggregate, may include official, semi-official, estimated or calculated data\n30977 Aggregate, may include official, semi-official, estimated or calculated data\n```\n:::\n:::\n\n\n\nIn the dataset, there are 14 variables (columns) and 30977 observations (rows). From head and tail tables, roughly speaking, each observation includes stock level of a specific type of animal in a country in a year.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(birds, function(x) n_distinct(x)) # number of unique values under each column\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Domain.Code           Domain        Area.Code             Area \n               1                1              248              248 \n    Element.Code          Element        Item.Code             Item \n               1                1                5                5 \n       Year.Code             Year             Unit            Value \n              58               58                1            11496 \n            Flag Flag.Description \n               6                6 \n```\n:::\n\n```{.r .cell-code}\ntable(birds$Item) # types of birds\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n              Chickens                  Ducks Geese and guinea fowls \n                 13074                   6909                   4136 \n  Pigeons, other birds                Turkeys \n                  1165                   5693 \n```\n:::\n\n```{.r .cell-code}\ntable(birds$Flag) # flag types\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n          *     A     F    Im     M \n10773  1494  6488 10007  1213  1002 \n```\n:::\n\n```{.r .cell-code}\ncountry.names <- unique(birds$Area) # countries included in the dataset\nprint(country.names)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] \"Afghanistan\"                                         \n  [2] \"Albania\"                                             \n  [3] \"Algeria\"                                             \n  [4] \"American Samoa\"                                      \n  [5] \"Angola\"                                              \n  [6] \"Antigua and Barbuda\"                                 \n  [7] \"Argentina\"                                           \n  [8] \"Armenia\"                                             \n  [9] \"Aruba\"                                               \n [10] \"Australia\"                                           \n [11] \"Austria\"                                             \n [12] \"Azerbaijan\"                                          \n [13] \"Bahamas\"                                             \n [14] \"Bahrain\"                                             \n [15] \"Bangladesh\"                                          \n [16] \"Barbados\"                                            \n [17] \"Belarus\"                                             \n [18] \"Belgium\"                                             \n [19] \"Belgium-Luxembourg\"                                  \n [20] \"Belize\"                                              \n [21] \"Benin\"                                               \n [22] \"Bermuda\"                                             \n [23] \"Bhutan\"                                              \n [24] \"Bolivia (Plurinational State of)\"                    \n [25] \"Bosnia and Herzegovina\"                              \n [26] \"Botswana\"                                            \n [27] \"Brazil\"                                              \n [28] \"Brunei Darussalam\"                                   \n [29] \"Bulgaria\"                                            \n [30] \"Burkina Faso\"                                        \n [31] \"Burundi\"                                             \n [32] \"Cabo Verde\"                                          \n [33] \"Cambodia\"                                            \n [34] \"Cameroon\"                                            \n [35] \"Canada\"                                              \n [36] \"Cayman Islands\"                                      \n [37] \"Central African Republic\"                            \n [38] \"Chad\"                                                \n [39] \"Chile\"                                               \n [40] \"China, Hong Kong SAR\"                                \n [41] \"China, Macao SAR\"                                    \n [42] \"China, mainland\"                                     \n [43] \"China, Taiwan Province of\"                           \n [44] \"Colombia\"                                            \n [45] \"Comoros\"                                             \n [46] \"Congo\"                                               \n [47] \"Cook Islands\"                                        \n [48] \"Costa Rica\"                                          \n [49] \"Côte d'Ivoire\"                                       \n [50] \"Croatia\"                                             \n [51] \"Cuba\"                                                \n [52] \"Cyprus\"                                              \n [53] \"Czechia\"                                             \n [54] \"Czechoslovakia\"                                      \n [55] \"Democratic People's Republic of Korea\"               \n [56] \"Democratic Republic of the Congo\"                    \n [57] \"Denmark\"                                             \n [58] \"Dominica\"                                            \n [59] \"Dominican Republic\"                                  \n [60] \"Ecuador\"                                             \n [61] \"Egypt\"                                               \n [62] \"El Salvador\"                                         \n [63] \"Equatorial Guinea\"                                   \n [64] \"Eritrea\"                                             \n [65] \"Estonia\"                                             \n [66] \"Eswatini\"                                            \n [67] \"Ethiopia\"                                            \n [68] \"Ethiopia PDR\"                                        \n [69] \"Falkland Islands (Malvinas)\"                         \n [70] \"Fiji\"                                                \n [71] \"Finland\"                                             \n [72] \"France\"                                              \n [73] \"French Guyana\"                                       \n [74] \"French Polynesia\"                                    \n [75] \"Gabon\"                                               \n [76] \"Gambia\"                                              \n [77] \"Georgia\"                                             \n [78] \"Germany\"                                             \n [79] \"Ghana\"                                               \n [80] \"Greece\"                                              \n [81] \"Grenada\"                                             \n [82] \"Guadeloupe\"                                          \n [83] \"Guam\"                                                \n [84] \"Guatemala\"                                           \n [85] \"Guinea\"                                              \n [86] \"Guinea-Bissau\"                                       \n [87] \"Guyana\"                                              \n [88] \"Haiti\"                                               \n [89] \"Honduras\"                                            \n [90] \"Hungary\"                                             \n [91] \"Iceland\"                                             \n [92] \"India\"                                               \n [93] \"Indonesia\"                                           \n [94] \"Iran (Islamic Republic of)\"                          \n [95] \"Iraq\"                                                \n [96] \"Ireland\"                                             \n [97] \"Israel\"                                              \n [98] \"Italy\"                                               \n [99] \"Jamaica\"                                             \n[100] \"Japan\"                                               \n[101] \"Jordan\"                                              \n[102] \"Kazakhstan\"                                          \n[103] \"Kenya\"                                               \n[104] \"Kiribati\"                                            \n[105] \"Kuwait\"                                              \n[106] \"Kyrgyzstan\"                                          \n[107] \"Lao People's Democratic Republic\"                    \n[108] \"Latvia\"                                              \n[109] \"Lebanon\"                                             \n[110] \"Lesotho\"                                             \n[111] \"Liberia\"                                             \n[112] \"Libya\"                                               \n[113] \"Liechtenstein\"                                       \n[114] \"Lithuania\"                                           \n[115] \"Luxembourg\"                                          \n[116] \"Madagascar\"                                          \n[117] \"Malawi\"                                              \n[118] \"Malaysia\"                                            \n[119] \"Mali\"                                                \n[120] \"Malta\"                                               \n[121] \"Martinique\"                                          \n[122] \"Mauritania\"                                          \n[123] \"Mauritius\"                                           \n[124] \"Mexico\"                                              \n[125] \"Micronesia (Federated States of)\"                    \n[126] \"Mongolia\"                                            \n[127] \"Montenegro\"                                          \n[128] \"Montserrat\"                                          \n[129] \"Morocco\"                                             \n[130] \"Mozambique\"                                          \n[131] \"Myanmar\"                                             \n[132] \"Namibia\"                                             \n[133] \"Nauru\"                                               \n[134] \"Nepal\"                                               \n[135] \"Netherlands\"                                         \n[136] \"Netherlands Antilles (former)\"                       \n[137] \"New Caledonia\"                                       \n[138] \"New Zealand\"                                         \n[139] \"Nicaragua\"                                           \n[140] \"Niger\"                                               \n[141] \"Nigeria\"                                             \n[142] \"Niue\"                                                \n[143] \"North Macedonia\"                                     \n[144] \"Norway\"                                              \n[145] \"Oman\"                                                \n[146] \"Pacific Islands Trust Territory\"                     \n[147] \"Pakistan\"                                            \n[148] \"Palestine\"                                           \n[149] \"Panama\"                                              \n[150] \"Papua New Guinea\"                                    \n[151] \"Paraguay\"                                            \n[152] \"Peru\"                                                \n[153] \"Philippines\"                                         \n[154] \"Poland\"                                              \n[155] \"Portugal\"                                            \n[156] \"Puerto Rico\"                                         \n[157] \"Qatar\"                                               \n[158] \"Republic of Korea\"                                   \n[159] \"Republic of Moldova\"                                 \n[160] \"Réunion\"                                             \n[161] \"Romania\"                                             \n[162] \"Russian Federation\"                                  \n[163] \"Rwanda\"                                              \n[164] \"Saint Helena, Ascension and Tristan da Cunha\"        \n[165] \"Saint Kitts and Nevis\"                               \n[166] \"Saint Lucia\"                                         \n[167] \"Saint Pierre and Miquelon\"                           \n[168] \"Saint Vincent and the Grenadines\"                    \n[169] \"Samoa\"                                               \n[170] \"Sao Tome and Principe\"                               \n[171] \"Saudi Arabia\"                                        \n[172] \"Senegal\"                                             \n[173] \"Serbia\"                                              \n[174] \"Serbia and Montenegro\"                               \n[175] \"Seychelles\"                                          \n[176] \"Sierra Leone\"                                        \n[177] \"Singapore\"                                           \n[178] \"Slovakia\"                                            \n[179] \"Slovenia\"                                            \n[180] \"Solomon Islands\"                                     \n[181] \"Somalia\"                                             \n[182] \"South Africa\"                                        \n[183] \"South Sudan\"                                         \n[184] \"Spain\"                                               \n[185] \"Sri Lanka\"                                           \n[186] \"Sudan\"                                               \n[187] \"Sudan (former)\"                                      \n[188] \"Suriname\"                                            \n[189] \"Sweden\"                                              \n[190] \"Switzerland\"                                         \n[191] \"Syrian Arab Republic\"                                \n[192] \"Tajikistan\"                                          \n[193] \"Thailand\"                                            \n[194] \"Timor-Leste\"                                         \n[195] \"Togo\"                                                \n[196] \"Tokelau\"                                             \n[197] \"Tonga\"                                               \n[198] \"Trinidad and Tobago\"                                 \n[199] \"Tunisia\"                                             \n[200] \"Turkey\"                                              \n[201] \"Turkmenistan\"                                        \n[202] \"Tuvalu\"                                              \n[203] \"Uganda\"                                              \n[204] \"Ukraine\"                                             \n[205] \"United Arab Emirates\"                                \n[206] \"United Kingdom of Great Britain and Northern Ireland\"\n[207] \"United Republic of Tanzania\"                         \n[208] \"United States of America\"                            \n[209] \"United States Virgin Islands\"                        \n[210] \"Uruguay\"                                             \n[211] \"USSR\"                                                \n[212] \"Uzbekistan\"                                          \n[213] \"Vanuatu\"                                             \n[214] \"Venezuela (Bolivarian Republic of)\"                  \n[215] \"Viet Nam\"                                            \n[216] \"Wallis and Futuna Islands\"                           \n[217] \"Yemen\"                                               \n[218] \"Yugoslav SFR\"                                        \n[219] \"Zambia\"                                              \n[220] \"Zimbabwe\"                                            \n[221] \"World\"                                               \n[222] \"Africa\"                                              \n[223] \"Eastern Africa\"                                      \n[224] \"Middle Africa\"                                       \n[225] \"Northern Africa\"                                     \n[226] \"Southern Africa\"                                     \n[227] \"Western Africa\"                                      \n[228] \"Americas\"                                            \n[229] \"Northern America\"                                    \n[230] \"Central America\"                                     \n[231] \"Caribbean\"                                           \n[232] \"South America\"                                       \n[233] \"Asia\"                                                \n[234] \"Central Asia\"                                        \n[235] \"Eastern Asia\"                                        \n[236] \"Southern Asia\"                                       \n[237] \"South-eastern Asia\"                                  \n[238] \"Western Asia\"                                        \n[239] \"Europe\"                                              \n[240] \"Eastern Europe\"                                      \n[241] \"Northern Europe\"                                     \n[242] \"Southern Europe\"                                     \n[243] \"Western Europe\"                                      \n[244] \"Oceania\"                                             \n[245] \"Australia and New Zealand\"                           \n[246] \"Melanesia\"                                           \n[247] \"Micronesia\"                                          \n[248] \"Polynesia\"                                           \n```\n:::\n\n```{.r .cell-code}\nyears.of.observations <- range(birds$Year) # range of data in terms of years\nyears.of.observations\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1961 2018\n```\n:::\n:::\n\nIf we assess the number of unique values in each column with the names of variables, we can say that this dataset is extracted from a large stock dataset because it includes only live animals as `Domain` and only 5 types of domestic fowl is included under `Item` variable which are chicken, duck, geese, turkey and other types of birds. Besides that, only one type of element (stocks) is included in the data.\n\nObservations are from 248 different countries and regions. Observations are years from 1961 to 2018. The dataset covers almost every region and countries of the World.\n\nThe core of each observation is given under `Value` variable, which should be number of stocks in thousands. All of other variables are basically contain characteristic information about observations.\n\nData might be obtained from poultry farms in each country from 1961 to 2018. It includes aggregated data.\n\n\n## Missing Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(birds$Value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1036\n```\n:::\n\n```{.r .cell-code}\nsum(is.null(birds$Value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nIt looks 1036 value are missing/ not observed in the dataset.\n\n\n## Stock levels by country and by bird type\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds %>% \n  select(Area, Value) %>% \n  group_by(Area) %>% \n  summarize(Total = sum(Value)) %>% \n  arrange(desc(Total))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 248 × 2\n   Area                         Total\n   <chr>                        <int>\n 1 World                    744113376\n 2 Asia                     361468192\n 3 Americas                 198674579\n 4 Eastern Asia             197028391\n 5 China, mainland          170767908\n 6 Europe                   122216094\n 7 Northern America         100752122\n 8 United States of America  93432842\n 9 South-eastern Asia        79669999\n10 South America             68503385\n# … with 238 more rows\n```\n:::\n:::\n\n\nSummarize table shows the total of stock levels in 58 years for each predefined region and country. Among countries, China had the largest stock of poultry over 58 years.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstock.levels <-  birds %>% \n  select(Item, Value) %>% \n  group_by(Item) %>% \n  summarize(Total = sum(Value, na.rm = TRUE)) %>% \n  arrange(desc(Total)) %>% \n  mutate(Percentage = 100*round(proportions(Total), digits=3))\n  \n\nstock.levels\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 3\n  Item                        Total Percentage\n  <chr>                       <dbl>      <dbl>\n1 Chickens               2696862583       90.6\n2 Ducks                   149781301        5  \n3 Turkeys                  81850064        2.7\n4 Geese and guinea fowls   41136874        1.4\n5 Pigeons, other birds      6822856        0.2\n```\n:::\n:::\n\n\nIn terms of bird types, more than 90% of poultry stocks consisted of chickens, 5% ducks and so on.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}