{
  "hash": "f0d02506aa189c1baa156b25d01c98b8",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Instructions\"\nauthor: \"Matthew Norberg\"\ndesription: \"Reading in data and creating a post\"\ndate: \"09/14/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - railroads\n  - faostat\n  - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, using the correct R package and command.\n\n-   railroad_2012_clean_county.csv ⭐\n-   birds.csv ⭐⭐\n-   FAOstat\\*.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n-   StateCounty2012.xls ⭐⭐⭐⭐\n\nFind the `_data` folder, located inside the `posts` folder. Then you can read in the data, using either one of the `readr` standard tidy read commands, or a specialized package such as `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the data from the StateCounty2012 file into a data frame\n# Upon inspection of the file, we see that the relevant data is in columns B, D, and F \n# Furthermore, the relevant data starts at row 4 and ends at row 2986\n# Since columns are non adjacent, we read each column separately and then combine\nstates <- readxl::read_xls('./_data/StateCounty2012.xls', range = readxl::cell_limits(c(4, 2), c(2986, 2)))\ncounty <- readxl::read_xls('./_data/StateCounty2012.xls', range = readxl::cell_limits(c(4, 4), c(2986, 4)))\ntotal <- readxl::read_xls('./_data/StateCounty2012.xls', range = readxl::cell_limits(c(4, 6), c(2986, 6)))\ndf <- bind_cols(states, county, total)\n\n# Remove rows that are missing a county\ndf <- na.omit(df)\n```\n:::\n\n\nAdd any comments or documentation as needed. More challenging data sets may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the number of counties in each state\nstateCount <- group_by(df, STATE) %>% summarize(CountyCount = n())\n\n# Sort in descending order\narrange(stateCount, desc(CountyCount))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   STATE CountyCount\n   <chr>       <int>\n 1 TX            221\n 2 GA            152\n 3 KY            119\n 4 MO            115\n 5 IL            103\n 6 IA             99\n 7 KS             95\n 8 NC             94\n 9 IN             92\n10 VA             92\n# … with 43 more rows\n```\n:::\n\n```{.r .cell-code}\n# Display the summary statistics for state county count\nsummary(stateCount)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    STATE            CountyCount    \n Length:53          Min.   :  1.00  \n Class :character   1st Qu.: 16.00  \n Mode  :character   Median : 53.00  \n                    Mean   : 55.28  \n                    3rd Qu.: 86.00  \n                    Max.   :221.00  \n```\n:::\n:::\n\n\nFrom the code chunks above, we can see that Texas has the most counties out of every state.  The other interesting thing about the data set is the length.  There are 53 different states listed in the data set, not 50.  This indicates that the data set must also include some data entries that are not States.  One guess is that they could be territories.  Additionally, we can see that the average number of counties per state is 55.28. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the total population in each state\nstateEmployment <- group_by(df, STATE) %>% summarize(TotalEmployment = sum(TOTAL))\n\n# Sort in descending order\narrange(stateEmployment, desc(TotalEmployment))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   STATE TotalEmployment\n   <chr>           <dbl>\n 1 TX              19839\n 2 IL              19131\n 3 NY              17050\n 4 NE              13176\n 5 CA              13137\n 6 PA              12769\n 7 OH               9056\n 8 GA               8605\n 9 IN               8537\n10 MO               8419\n# … with 43 more rows\n```\n:::\n\n```{.r .cell-code}\n# Display the summary statistics for state populalation\nsummary(stateEmployment)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    STATE           TotalEmployment\n Length:53          Min.   :    1  \n Class :character   1st Qu.: 1917  \n Mode  :character   Median : 3379  \n                    Mean   : 4819  \n                    3rd Qu.: 6092  \n                    Max.   :19839  \n```\n:::\n:::\n\n\nThe two previous chunks of code calculates the total railroad employment of each state in the data set.  The data set shows that Texas has the largest employment numbers with 19,839 and the average population per state is 4,819.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate average population per county in each state\ntotalInfo <- mutate(stateEmployment, select(stateCount, CountyCount))\ntotalInfo <- mutate(totalInfo, AverageEmploymentPerCounty = TotalEmployment / CountyCount)\narrange(totalInfo, desc(AverageEmploymentPerCounty))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 4\n   STATE TotalEmployment CountyCount AverageEmploymentPerCounty\n   <chr>           <dbl>       <int>                      <dbl>\n 1 DE               1495           3                       498.\n 2 NJ               8329          21                       397.\n 3 CT               2592           8                       324 \n 4 MA               3379          12                       282.\n 5 NY              17050          61                       280.\n 6 DC                279           1                       279 \n 7 CA              13137          55                       239.\n 8 AZ               3153          15                       210.\n 9 PA              12769          65                       196.\n10 MD               4709          24                       196.\n# … with 43 more rows\n```\n:::\n:::\n\n\nThe code chunk above is used to calculate the average employment per county in each state.  This shows that Delaware has the most railroad employees per counties.  \n\nThe data set indicates that the data was collected in 2012.  My best guess is that the data was collected in the census.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}