{
  "hash": "d3525c02bea443cddc9720a6b87030df",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Solutions\"\nauthor: \"Caitlin Rowley\"\ndesription: \"Reading in data and creating a post\"\ndate: \"09/16/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - railroads\n  - faostat\n  - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\nI will be using the \"Railroad_2012\" data set for this Challenge.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install readr function\n\ninstall.packages(\"readr\")\n\n# read in and rename data\n\nrailroad <- read_csv(\"_data\\\\railroad_2012_clean_county.csv\")\nrailroad\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# … with 2,920 more rows\n```\n:::\n\n```{.r .cell-code}\n# note that R does not like back slashes in Windows - needed to add '\\\\' or '/'\n```\n:::\n\n\nThis data set shows the number of railroad employees ('total_employees') by county ('county') by state ('state'). This data was collected in 2012, most likely by a government entity.\n\nThe variables in this data set are (1) state, (2) county, and (3) total employees. The cases are each state's two-letter abbreviation, the name of the county within that state, and the actual number of employees within that count.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# description of data\n# include: (1) how data was collected, (2) cases and variables, (3) interpretation of data and any useful details.\n\n# descriptive statistics\n# run a summary function\n\nsummary(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n\nThere are 2,930 cases in this data set. The minimum value, or number of employees, is 1, and the maximum value is 8,207. The median number of employees is 21, and the average number of employees across counties and states is 87. I will check the dimensions of the data frame to be sure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# descriptive statistics\n# check dimensions to be sure\n\ndim(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n\n```{.r .cell-code}\n# Confirmed that there are 2,930 cases in this data set and 3 variables. \n```\n:::\n\n\nI will next generate a visualization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate scatterplot:\n\nggplot(railroad, aes(total_employees))\n```\n\n::: {.cell-output-display}\n![](Challenge1---Caitlin-Rowley_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(railroad, aes(state, total_employees)) + geom_point()\n```\n\n::: {.cell-output-display}\n![](Challenge1---Caitlin-Rowley_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\nIt is evident in looking at the scatterplot that the county with 8,207 is an outlier.\n\nNext, I will code to identify the 10 counties with the highest number of employees and the 10 counties with the lowest number of employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# slice data:\n\nrailroad %>%\narrange(`total_employees`) %>%\nslice(1:10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n   state county   total_employees\n   <chr> <chr>              <dbl>\n 1 AK    SITKA                  1\n 2 AL    BARBOUR                1\n 3 AL    HENRY                  1\n 4 AP    APO                    1\n 5 AR    NEWTON                 1\n 6 CA    MONO                   1\n 7 CO    BENT                   1\n 8 CO    CHEYENNE               1\n 9 CO    COSTILLA               1\n10 CO    DOLORES                1\n```\n:::\n:::\n\n\nAfter slicing the data to indicate the counties with the lowest numbers of railroad employees, we can see the following:\n\nThe counties with the ten lowest numbers of employees are Sitka County, AK (1), Barbour County, AL (1), Henry County, AL (1), APO County, AP--which appears to be an overseas military address\\--(1), Newton County, AR (1), Mono County, CA (1), Bent County, CO (1), Cheyenne County, CO (1), Costilla County, CO (1), and Dolores County, CO (1).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# arrange the data in descending order:\n\nrailroad %>%\narrange(desc(`total_employees`)) %>%\nslice(1:10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n   state county           total_employees\n   <chr> <chr>                      <dbl>\n 1 IL    COOK                        8207\n 2 TX    TARRANT                     4235\n 3 NE    DOUGLAS                     3797\n 4 NY    SUFFOLK                     3685\n 5 VA    INDEPENDENT CITY            3249\n 6 FL    DUVAL                       3073\n 7 CA    SAN BERNARDINO              2888\n 8 CA    LOS ANGELES                 2545\n 9 TX    HARRIS                      2535\n10 NE    LINCOLN                     2289\n```\n:::\n:::\n\n\nAfter slicing the data to indicate the counties with the highest number of railroad employees, we can see the following:\n\nCook County, IL (8207), Tarrant County, TX (4235), Douglas County, NE (3797), Suffolk County, NY (3685), Independent City, VA--which does not appear to be an existing county or city, so it can be assumed that county or municipal-level data was not readily available for this value\\--(3249), Duval County, FL (3073), San Bernardino County, CA (2888), Los Angeles County, CA (2545), Harris County, TX (2535), and Lincoln County, NE (2289).\n\nIn taking a closer look at the cases in this data set, it can be assumed that these states and counties do not entirely represent existing states in counties within the US. Data may be incomplete or may include international municipalities, counties, etc.\n",
    "supporting": [
      "Challenge1---Caitlin-Rowley_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}