{
  "hash": "664a8ba563d86d99b86ddba5ff0c9a70",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Kavya Harlalka\"\ndesription: \"Reading in Data\"\ndate: \"10/12/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - starwars1\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import important libraries needed for functions\nlibrary(tidyverse)\nlibrary(rmarkdown)\nlibrary(summarytools)\nlibrary(dplyr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read data from the file\nload(\"_data/starwars1.RData\")\n\n# Printing the read data as a paged table\npaged_table(starwars.1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"name\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"birth_year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"homeworld\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"species\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"height.in\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mass.lbs\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"character.origin\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"n.films\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Luke Skywalker\",\"2\":\"19.0\",\"3\":\"Tatooine\",\"4\":\"Human\",\"5\":\"67.7164\",\"6\":\"169.785\",\"7\":\"Original Trilogy\",\"8\":\"5\"},{\"1\":\"C-3PO\",\"2\":\"112.0\",\"3\":\"Tatooine\",\"4\":\"Droid\",\"5\":\"65.7479\",\"6\":\"165.375\",\"7\":\"Original Trilogy\",\"8\":\"6\"},{\"1\":\"R2-D2\",\"2\":\"33.0\",\"3\":\"Naboo\",\"4\":\"Droid\",\"5\":\"37.7952\",\"6\":\"70.560\",\"7\":\"Original Trilogy\",\"8\":\"7\"},{\"1\":\"Darth Vader\",\"2\":\"41.9\",\"3\":\"Tatooine\",\"4\":\"Human\",\"5\":\"79.5274\",\"6\":\"299.880\",\"7\":\"Original Trilogy\",\"8\":\"4\"},{\"1\":\"Leia Organa\",\"2\":\"19.0\",\"3\":\"Alderaan\",\"4\":\"Human\",\"5\":\"59.0550\",\"6\":\"108.045\",\"7\":\"Original Trilogy\",\"8\":\"5\"},{\"1\":\"Owen Lars\",\"2\":\"52.0\",\"3\":\"Tatooine\",\"4\":\"Human\",\"5\":\"70.0786\",\"6\":\"264.600\",\"7\":\"Original Trilogy\",\"8\":\"3\"},{\"1\":\"Beru Whitesun lars\",\"2\":\"47.0\",\"3\":\"Tatooine\",\"4\":\"Human\",\"5\":\"64.9605\",\"6\":\"165.375\",\"7\":\"Original Trilogy\",\"8\":\"3\"},{\"1\":\"R5-D4\",\"2\":\"NA\",\"3\":\"Tatooine\",\"4\":\"Droid\",\"5\":\"38.1889\",\"6\":\"70.560\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Biggs Darklighter\",\"2\":\"24.0\",\"3\":\"Tatooine\",\"4\":\"Human\",\"5\":\"72.0471\",\"6\":\"185.220\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Obi-Wan Kenobi\",\"2\":\"57.0\",\"3\":\"Stewjon\",\"4\":\"Human\",\"5\":\"71.6534\",\"6\":\"169.785\",\"7\":\"Original Trilogy\",\"8\":\"6\"},{\"1\":\"Anakin Skywalker\",\"2\":\"41.9\",\"3\":\"Tatooine\",\"4\":\"Human\",\"5\":\"74.0156\",\"6\":\"185.220\",\"7\":\"Prequels\",\"8\":\"3\"},{\"1\":\"Wilhuff Tarkin\",\"2\":\"64.0\",\"3\":\"Eriadu\",\"4\":\"Human\",\"5\":\"70.8660\",\"6\":\"NA\",\"7\":\"Original Trilogy\",\"8\":\"2\"},{\"1\":\"Chewbacca\",\"2\":\"200.0\",\"3\":\"Kashyyyk\",\"4\":\"Wookiee\",\"5\":\"89.7636\",\"6\":\"246.960\",\"7\":\"Original Trilogy\",\"8\":\"5\"},{\"1\":\"Han Solo\",\"2\":\"29.0\",\"3\":\"Corellia\",\"4\":\"Human\",\"5\":\"70.8660\",\"6\":\"176.400\",\"7\":\"Original Trilogy\",\"8\":\"4\"},{\"1\":\"Greedo\",\"2\":\"44.0\",\"3\":\"Rodia\",\"4\":\"Rodian\",\"5\":\"68.1101\",\"6\":\"163.170\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Jabba Desilijic Tiure\",\"2\":\"600.0\",\"3\":\"Nal Hutta\",\"4\":\"Hutt\",\"5\":\"68.8975\",\"6\":\"2994.390\",\"7\":\"Original Trilogy\",\"8\":\"3\"},{\"1\":\"Wedge Antilles\",\"2\":\"21.0\",\"3\":\"Corellia\",\"4\":\"Human\",\"5\":\"66.9290\",\"6\":\"169.785\",\"7\":\"Original Trilogy\",\"8\":\"3\"},{\"1\":\"Jek Tono Porkins\",\"2\":\"NA\",\"3\":\"Bestine IV\",\"4\":\"Human\",\"5\":\"70.8660\",\"6\":\"242.550\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Yoda\",\"2\":\"896.0\",\"3\":\"NA\",\"4\":\"Yoda's species\",\"5\":\"25.9842\",\"6\":\"37.485\",\"7\":\"Original Trilogy\",\"8\":\"5\"},{\"1\":\"Palpatine\",\"2\":\"82.0\",\"3\":\"Naboo\",\"4\":\"Human\",\"5\":\"66.9290\",\"6\":\"165.375\",\"7\":\"Original Trilogy\",\"8\":\"5\"},{\"1\":\"Boba Fett\",\"2\":\"31.5\",\"3\":\"Kamino\",\"4\":\"Human\",\"5\":\"72.0471\",\"6\":\"172.431\",\"7\":\"Original Trilogy\",\"8\":\"3\"},{\"1\":\"IG-88\",\"2\":\"15.0\",\"3\":\"NA\",\"4\":\"Droid\",\"5\":\"78.7400\",\"6\":\"308.700\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Bossk\",\"2\":\"53.0\",\"3\":\"Trandosha\",\"4\":\"Trandoshan\",\"5\":\"74.8030\",\"6\":\"249.165\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Lando Calrissian\",\"2\":\"31.0\",\"3\":\"Socorro\",\"4\":\"Human\",\"5\":\"69.6849\",\"6\":\"174.195\",\"7\":\"Original Trilogy\",\"8\":\"2\"},{\"1\":\"Lobot\",\"2\":\"37.0\",\"3\":\"Bespin\",\"4\":\"Human\",\"5\":\"68.8975\",\"6\":\"174.195\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Ackbar\",\"2\":\"41.0\",\"3\":\"Mon Cala\",\"4\":\"Mon Calamari\",\"5\":\"70.8660\",\"6\":\"183.015\",\"7\":\"Original Trilogy\",\"8\":\"2\"},{\"1\":\"Mon Mothma\",\"2\":\"48.0\",\"3\":\"Chandrila\",\"4\":\"Human\",\"5\":\"59.0550\",\"6\":\"NA\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Arvel Crynyd\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"Human\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Wicket Systri Warrick\",\"2\":\"8.0\",\"3\":\"Endor\",\"4\":\"Ewok\",\"5\":\"34.6456\",\"6\":\"44.100\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Nien Nunb\",\"2\":\"NA\",\"3\":\"Sullust\",\"4\":\"Sullustan\",\"5\":\"62.9920\",\"6\":\"149.940\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Qui-Gon Jinn\",\"2\":\"92.0\",\"3\":\"NA\",\"4\":\"Human\",\"5\":\"75.9841\",\"6\":\"196.245\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Nute Gunray\",\"2\":\"NA\",\"3\":\"Cato Neimoidia\",\"4\":\"Neimodian\",\"5\":\"75.1967\",\"6\":\"198.450\",\"7\":\"Prequels\",\"8\":\"3\"},{\"1\":\"Finis Valorum\",\"2\":\"91.0\",\"3\":\"Coruscant\",\"4\":\"Human\",\"5\":\"66.9290\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Jar Jar Binks\",\"2\":\"52.0\",\"3\":\"Naboo\",\"4\":\"Gungan\",\"5\":\"77.1652\",\"6\":\"145.530\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Roos Tarpals\",\"2\":\"NA\",\"3\":\"Naboo\",\"4\":\"Gungan\",\"5\":\"88.1888\",\"6\":\"180.810\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Rugor Nass\",\"2\":\"NA\",\"3\":\"Naboo\",\"4\":\"Gungan\",\"5\":\"81.1022\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Ric Olié\",\"2\":\"NA\",\"3\":\"Naboo\",\"4\":\"NA\",\"5\":\"72.0471\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Watto\",\"2\":\"NA\",\"3\":\"Toydaria\",\"4\":\"Toydarian\",\"5\":\"53.9369\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Sebulba\",\"2\":\"NA\",\"3\":\"Malastare\",\"4\":\"Dug\",\"5\":\"44.0944\",\"6\":\"88.200\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Quarsh Panaka\",\"2\":\"62.0\",\"3\":\"Naboo\",\"4\":\"NA\",\"5\":\"72.0471\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Shmi Skywalker\",\"2\":\"72.0\",\"3\":\"Tatooine\",\"4\":\"Human\",\"5\":\"64.1731\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Darth Maul\",\"2\":\"54.0\",\"3\":\"Dathomir\",\"4\":\"Zabrak\",\"5\":\"68.8975\",\"6\":\"176.400\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Bib Fortuna\",\"2\":\"NA\",\"3\":\"Ryloth\",\"4\":\"Twi'lek\",\"5\":\"70.8660\",\"6\":\"NA\",\"7\":\"Original Trilogy\",\"8\":\"1\"},{\"1\":\"Ayla Secura\",\"2\":\"48.0\",\"3\":\"Ryloth\",\"4\":\"Twi'lek\",\"5\":\"70.0786\",\"6\":\"121.275\",\"7\":\"Prequels\",\"8\":\"3\"},{\"1\":\"Dud Bolt\",\"2\":\"NA\",\"3\":\"Vulpter\",\"4\":\"Vulptereen\",\"5\":\"37.0078\",\"6\":\"99.225\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Gasgano\",\"2\":\"NA\",\"3\":\"Troiken\",\"4\":\"Xexto\",\"5\":\"48.0314\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Ben Quadinaros\",\"2\":\"NA\",\"3\":\"Tund\",\"4\":\"Toong\",\"5\":\"64.1731\",\"6\":\"143.325\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Mace Windu\",\"2\":\"72.0\",\"3\":\"Haruun Kal\",\"4\":\"Human\",\"5\":\"74.0156\",\"6\":\"185.220\",\"7\":\"Prequels\",\"8\":\"3\"},{\"1\":\"Ki-Adi-Mundi\",\"2\":\"92.0\",\"3\":\"Cerea\",\"4\":\"Cerean\",\"5\":\"77.9526\",\"6\":\"180.810\",\"7\":\"Prequels\",\"8\":\"3\"},{\"1\":\"Kit Fisto\",\"2\":\"NA\",\"3\":\"Glee Anselm\",\"4\":\"Nautolan\",\"5\":\"77.1652\",\"6\":\"191.835\",\"7\":\"Prequels\",\"8\":\"3\"},{\"1\":\"Eeth Koth\",\"2\":\"NA\",\"3\":\"Iridonia\",\"4\":\"Zabrak\",\"5\":\"67.3227\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Adi Gallia\",\"2\":\"NA\",\"3\":\"Coruscant\",\"4\":\"Tholothian\",\"5\":\"72.4408\",\"6\":\"110.250\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Saesee Tiin\",\"2\":\"NA\",\"3\":\"Iktotch\",\"4\":\"Iktotchi\",\"5\":\"74.0156\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Yarael Poof\",\"2\":\"NA\",\"3\":\"Quermia\",\"4\":\"Quermian\",\"5\":\"103.9368\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Plo Koon\",\"2\":\"22.0\",\"3\":\"Dorin\",\"4\":\"Kel Dor\",\"5\":\"74.0156\",\"6\":\"176.400\",\"7\":\"Prequels\",\"8\":\"3\"},{\"1\":\"Mas Amedda\",\"2\":\"NA\",\"3\":\"Champala\",\"4\":\"Chagrian\",\"5\":\"77.1652\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Gregar Typho\",\"2\":\"NA\",\"3\":\"Naboo\",\"4\":\"Human\",\"5\":\"72.8345\",\"6\":\"187.425\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Cordé\",\"2\":\"NA\",\"3\":\"Naboo\",\"4\":\"Human\",\"5\":\"61.8109\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Cliegg Lars\",\"2\":\"82.0\",\"3\":\"Tatooine\",\"4\":\"Human\",\"5\":\"72.0471\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Poggle the Lesser\",\"2\":\"NA\",\"3\":\"Geonosis\",\"4\":\"Geonosian\",\"5\":\"72.0471\",\"6\":\"176.400\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Luminara Unduli\",\"2\":\"58.0\",\"3\":\"Mirial\",\"4\":\"Mirialan\",\"5\":\"66.9290\",\"6\":\"123.921\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Barriss Offee\",\"2\":\"40.0\",\"3\":\"Mirial\",\"4\":\"Mirialan\",\"5\":\"65.3542\",\"6\":\"110.250\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Dormé\",\"2\":\"NA\",\"3\":\"Naboo\",\"4\":\"Human\",\"5\":\"64.9605\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Dooku\",\"2\":\"102.0\",\"3\":\"Serenno\",\"4\":\"Human\",\"5\":\"75.9841\",\"6\":\"176.400\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Bail Prestor Organa\",\"2\":\"67.0\",\"3\":\"Alderaan\",\"4\":\"Human\",\"5\":\"75.1967\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Jango Fett\",\"2\":\"66.0\",\"3\":\"Concord Dawn\",\"4\":\"Human\",\"5\":\"72.0471\",\"6\":\"174.195\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Zam Wesell\",\"2\":\"NA\",\"3\":\"Zolan\",\"4\":\"Clawdite\",\"5\":\"66.1416\",\"6\":\"121.275\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Dexter Jettster\",\"2\":\"NA\",\"3\":\"Ojom\",\"4\":\"Besalisk\",\"5\":\"77.9526\",\"6\":\"224.910\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Lama Su\",\"2\":\"NA\",\"3\":\"Kamino\",\"4\":\"Kaminoan\",\"5\":\"90.1573\",\"6\":\"194.040\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Taun We\",\"2\":\"NA\",\"3\":\"Kamino\",\"4\":\"Kaminoan\",\"5\":\"83.8581\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Jocasta Nu\",\"2\":\"NA\",\"3\":\"Coruscant\",\"4\":\"Human\",\"5\":\"65.7479\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Ratts Tyerell\",\"2\":\"NA\",\"3\":\"Aleen Minor\",\"4\":\"Aleena\",\"5\":\"31.1023\",\"6\":\"33.075\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"R4-P17\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"Droid\",\"5\":\"37.7952\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Wat Tambor\",\"2\":\"NA\",\"3\":\"Skako\",\"4\":\"Skakoan\",\"5\":\"75.9841\",\"6\":\"105.840\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"San Hill\",\"2\":\"NA\",\"3\":\"Muunilinst\",\"4\":\"Muun\",\"5\":\"75.1967\",\"6\":\"NA\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Shaak Ti\",\"2\":\"NA\",\"3\":\"Shili\",\"4\":\"Togruta\",\"5\":\"70.0786\",\"6\":\"125.685\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Grievous\",\"2\":\"NA\",\"3\":\"Kalee\",\"4\":\"Kaleesh\",\"5\":\"85.0392\",\"6\":\"350.595\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Tarfful\",\"2\":\"NA\",\"3\":\"Kashyyyk\",\"4\":\"Wookiee\",\"5\":\"92.1258\",\"6\":\"299.880\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Raymus Antilles\",\"2\":\"NA\",\"3\":\"Alderaan\",\"4\":\"Human\",\"5\":\"74.0156\",\"6\":\"174.195\",\"7\":\"Original Trilogy\",\"8\":\"2\"},{\"1\":\"Sly Moore\",\"2\":\"NA\",\"3\":\"Umbara\",\"4\":\"NA\",\"5\":\"70.0786\",\"6\":\"105.840\",\"7\":\"Prequels\",\"8\":\"2\"},{\"1\":\"Tion Medon\",\"2\":\"NA\",\"3\":\"Utapau\",\"4\":\"Pau'an\",\"5\":\"81.1022\",\"6\":\"176.400\",\"7\":\"Prequels\",\"8\":\"1\"},{\"1\":\"Finn\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"Human\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"Sequels\",\"8\":\"1\"},{\"1\":\"Rey\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"Human\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"Sequels\",\"8\":\"1\"},{\"1\":\"Poe Dameron\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"Human\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"Sequels\",\"8\":\"1\"},{\"1\":\"BB8\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"Droid\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"Sequels\",\"8\":\"1\"},{\"1\":\"Captain Phasma\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"Sequels\",\"8\":\"1\"},{\"1\":\"Padmé Amidala\",\"2\":\"46.0\",\"3\":\"Naboo\",\"4\":\"Human\",\"5\":\"64.9605\",\"6\":\"99.225\",\"7\":\"Prequels\",\"8\":\"3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThis dataset represents characters in the fictional world of Star Wars. It gives details like their names, species, origin, etc. It also gives the height and mass of each character and the number of films they appeared in.\n\n## Analysis of species wise data\n\nI chose the species column to group the data to provide certain analysis. The first analysis we do is look at the average height, the average mass and average no of films of each species as shown below :-\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group dataset by species, ignoring values that have species as NA\ndataGroupedBySpecies <- starwars.1 %>%\n  group_by(species) %>% \n  filter(!is.na(species))\n\n# Analyze the grouped data by finding the average height mass and noOfFilms per species.\ndataSummary <- dataGroupedBySpecies %>%\n  summarise(\n    avg_height = mean(height.in, na.rm = TRUE),\n    avg_mass = mean(mass.lbs, na.rm = TRUE),\n    avg_number_of_films = mean(n.films, na.rm = TRUE)\n  ) %>%\n  arrange(species)\npaged_table(dataSummary)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"species\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"avg_height\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"avg_mass\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"avg_number_of_films\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Aleena\",\"2\":\"31.10230\",\"3\":\"33.0750\",\"4\":\"1.000000\"},{\"1\":\"Besalisk\",\"2\":\"77.95260\",\"3\":\"224.9100\",\"4\":\"1.000000\"},{\"1\":\"Cerean\",\"2\":\"77.95260\",\"3\":\"180.8100\",\"4\":\"3.000000\"},{\"1\":\"Chagrian\",\"2\":\"77.16520\",\"3\":\"NaN\",\"4\":\"2.000000\"},{\"1\":\"Clawdite\",\"2\":\"66.14160\",\"3\":\"121.2750\",\"4\":\"1.000000\"},{\"1\":\"Droid\",\"2\":\"51.65344\",\"3\":\"153.7987\",\"4\":\"3.000000\"},{\"1\":\"Dug\",\"2\":\"44.09440\",\"3\":\"88.2000\",\"4\":\"1.000000\"},{\"1\":\"Ewok\",\"2\":\"34.64560\",\"3\":\"44.1000\",\"4\":\"1.000000\"},{\"1\":\"Geonosian\",\"2\":\"72.04710\",\"3\":\"176.4000\",\"4\":\"2.000000\"},{\"1\":\"Gungan\",\"2\":\"82.15207\",\"3\":\"163.1700\",\"4\":\"1.333333\"},{\"1\":\"Human\",\"2\":\"69.54520\",\"3\":\"182.5339\",\"4\":\"2.228571\"},{\"1\":\"Hutt\",\"2\":\"68.89750\",\"3\":\"2994.3900\",\"4\":\"3.000000\"},{\"1\":\"Iktotchi\",\"2\":\"74.01560\",\"3\":\"NaN\",\"4\":\"2.000000\"},{\"1\":\"Kaleesh\",\"2\":\"85.03920\",\"3\":\"350.5950\",\"4\":\"1.000000\"},{\"1\":\"Kaminoan\",\"2\":\"87.00770\",\"3\":\"194.0400\",\"4\":\"1.000000\"},{\"1\":\"Kel Dor\",\"2\":\"74.01560\",\"3\":\"176.4000\",\"4\":\"3.000000\"},{\"1\":\"Mirialan\",\"2\":\"66.14160\",\"3\":\"117.0855\",\"4\":\"1.500000\"},{\"1\":\"Mon Calamari\",\"2\":\"70.86600\",\"3\":\"183.0150\",\"4\":\"2.000000\"},{\"1\":\"Muun\",\"2\":\"75.19670\",\"3\":\"NaN\",\"4\":\"1.000000\"},{\"1\":\"Nautolan\",\"2\":\"77.16520\",\"3\":\"191.8350\",\"4\":\"3.000000\"},{\"1\":\"Neimodian\",\"2\":\"75.19670\",\"3\":\"198.4500\",\"4\":\"3.000000\"},{\"1\":\"Pau'an\",\"2\":\"81.10220\",\"3\":\"176.4000\",\"4\":\"1.000000\"},{\"1\":\"Quermian\",\"2\":\"103.93680\",\"3\":\"NaN\",\"4\":\"1.000000\"},{\"1\":\"Rodian\",\"2\":\"68.11010\",\"3\":\"163.1700\",\"4\":\"1.000000\"},{\"1\":\"Skakoan\",\"2\":\"75.98410\",\"3\":\"105.8400\",\"4\":\"1.000000\"},{\"1\":\"Sullustan\",\"2\":\"62.99200\",\"3\":\"149.9400\",\"4\":\"1.000000\"},{\"1\":\"Tholothian\",\"2\":\"72.44080\",\"3\":\"110.2500\",\"4\":\"2.000000\"},{\"1\":\"Togruta\",\"2\":\"70.07860\",\"3\":\"125.6850\",\"4\":\"2.000000\"},{\"1\":\"Toong\",\"2\":\"64.17310\",\"3\":\"143.3250\",\"4\":\"1.000000\"},{\"1\":\"Toydarian\",\"2\":\"53.93690\",\"3\":\"NaN\",\"4\":\"2.000000\"},{\"1\":\"Trandoshan\",\"2\":\"74.80300\",\"3\":\"249.1650\",\"4\":\"1.000000\"},{\"1\":\"Twi'lek\",\"2\":\"70.47230\",\"3\":\"121.2750\",\"4\":\"2.000000\"},{\"1\":\"Vulptereen\",\"2\":\"37.00780\",\"3\":\"99.2250\",\"4\":\"1.000000\"},{\"1\":\"Wookiee\",\"2\":\"90.94470\",\"3\":\"273.4200\",\"4\":\"3.000000\"},{\"1\":\"Xexto\",\"2\":\"48.03140\",\"3\":\"NaN\",\"4\":\"1.000000\"},{\"1\":\"Yoda's species\",\"2\":\"25.98420\",\"3\":\"37.4850\",\"4\":\"5.000000\"},{\"1\":\"Zabrak\",\"2\":\"68.11010\",\"3\":\"176.4000\",\"4\":\"1.500000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThis gives us an insight of how which species have highest appearances in the films as well as how the height and mass varies by the species.\n\nWe can further look at the heights of different characters of certain species to get an insight on how it varies with species using the below graph :-\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use group data to get species with more than 2 rows and plot a graph that shows relation between species and their height\ndataGroupedBySpecies %>%\n  filter(n() >= 2) %>%\n  ggplot(aes(x=species, \n     y=height.in)) +\n     geom_point() +\n     theme_minimal() +\n     xlab(\"Species\") +\n     ylab(\"Height\")\n```\n\n::: {.cell-output-display}\n![](homework2_KavyaHarlalka_files/figure-html/Species to Height graph-1.png){width=672}\n:::\n:::\n\n\nWe take only the species for which we have atleast 2 character data. As can be seen, Droids are usually smaller while Wookies are usually much bigger.\n\nWe can analyze the origin of each species as well which species has more character origins in Original films as compared to prequels or sequels. This can be seen in the table below :-\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Percentage of species origin\nprop.table(table(select(dataGroupedBySpecies, character.origin))) %>% \n  `*`(100) %>% \n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                character.origin\nspecies          Original Trilogy Prequels Sequels\n  Aleena                     0.00     1.20    0.00\n  Besalisk                   0.00     1.20    0.00\n  Cerean                     0.00     1.20    0.00\n  Chagrian                   0.00     1.20    0.00\n  Clawdite                   0.00     1.20    0.00\n  Droid                      4.82     1.20    1.20\n  Dug                        0.00     1.20    0.00\n  Ewok                       1.20     0.00    0.00\n  Geonosian                  0.00     1.20    0.00\n  Gungan                     0.00     3.61    0.00\n  Human                     21.69    16.87    3.61\n  Hutt                       1.20     0.00    0.00\n  Iktotchi                   0.00     1.20    0.00\n  Kaleesh                    0.00     1.20    0.00\n  Kaminoan                   0.00     2.41    0.00\n  Kel Dor                    0.00     1.20    0.00\n  Mirialan                   0.00     2.41    0.00\n  Mon Calamari               1.20     0.00    0.00\n  Muun                       0.00     1.20    0.00\n  Nautolan                   0.00     1.20    0.00\n  Neimodian                  0.00     1.20    0.00\n  Pau'an                     0.00     1.20    0.00\n  Quermian                   0.00     1.20    0.00\n  Rodian                     1.20     0.00    0.00\n  Skakoan                    0.00     1.20    0.00\n  Sullustan                  1.20     0.00    0.00\n  Tholothian                 0.00     1.20    0.00\n  Togruta                    0.00     1.20    0.00\n  Toong                      0.00     1.20    0.00\n  Toydarian                  0.00     1.20    0.00\n  Trandoshan                 1.20     0.00    0.00\n  Twi'lek                    1.20     1.20    0.00\n  Vulptereen                 0.00     1.20    0.00\n  Wookiee                    1.20     1.20    0.00\n  Xexto                      0.00     1.20    0.00\n  Yoda's species             1.20     0.00    0.00\n  Zabrak                     0.00     2.41    0.00\n```\n:::\n:::\n\n\n## Possible research queries\nThough this is not scientific data (since the data is fictional) but just to give an example of possible research queries that can be answered, we could find the correlation between the height and weight in the star wars universe from the complete data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find correlation between height and weight of characters in the star wars universe\ncor.test(starwars.1$height.in, starwars.1$mass.lbs, method=c(\"pearson\", \"kendall\", \"spearman\"), use = \"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  starwars.1$height.in and starwars.1$mass.lbs\nt = 1.02, df = 57, p-value = 0.312\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.1265364  0.3770395\nsample estimates:\n      cor \n0.1338842 \n```\n:::\n:::\n\nThe data seen above is explained using the following terms\n\n* t (1.02) is the t-test statistic value,\n* df (57) is the degrees of freedom,\n* p-value (0.312) is the significance level of the t-test.\n* The correlation coefficient is 0.134.\n\nThe p-value of the test is 0.312, which is not less than the significance level alpha = 0.05. We can conclude that height and weight are not significantly correlated in the Star wars universe.",
    "supporting": [
      "homework2_KavyaHarlalka_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}