{
  "hash": "e5c847bbe4951fc6bc87a6c9a5d556e6",
  "result": {
    "markdown": "---\ntitle: \"Challenge 7 Erika Nagai\"\nauthor: \"Erika Nagai\"\ndescription: \"Visualizing Multiple Dimensions\"\ndate: \"10/31/2022\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_7\n  - air_bnb\neditor: \n  markdown: \n    wrap: sentence\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(summarytools)\nlibrary(knitr)\nlibrary(wordcloud)\nlibrary(ggwordcloud)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in library(ggwordcloud): there is no package called 'ggwordcloud'\n```\n:::\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  mutate variables as needed (including sanity checks)\n4)  Recreate at least two graphs from previous exercises, but introduce at least one additional dimension that you omitted before using ggplot functionality (color, shape, line, facet, etc) The goal is not to create unneeded [chart ink (Tufte)](https://www.edwardtufte.com/tufte/), but to concisely capture variation in additional dimensions that were collapsed in your earlier 2 or 3 dimensional graphs.\n\n-   Explain why you choose the specific graph type\n\n5)  If you haven't tried in previous weeks, work this week to make your graphs \"publication\" ready with titles, captions, and pretty axis labels and other viewer-friendly features\n\n[R Graph Gallery](https://r-graph-gallery.com/) is a good starting point for thinking about what information is conveyed in standard graph types, and includes example R code.\nAnd anyone not familiar with Edward Tufte should check out his [fantastic books](https://www.edwardtufte.com/tufte/books_vdqi) and [courses on data visualizaton.](https://www.edwardtufte.com/tufte/courses)\n\n(be sure to only include the category tags for the data you use!)\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   eggs ⭐\n-   abc_poll ⭐⭐\n-   australian_marriage ⭐⭐\n-   hotel_bookings ⭐⭐⭐\n-   air_bnb ⭐⭐⭐\n-   us_hh ⭐⭐⭐⭐\n-   faostat ⭐⭐⭐⭐⭐\n\nUsing `read_csv` function, I read in AB_NYC_2019.csv as \"ab_df\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nab_df = read_csv(\"_data/AB_NYC_2019.csv\")\n```\n:::\n\n\n### Briefly describe the data\n\nI explored this dataset to understand how it is structured and what kind of data is included\n\nThis dataset consists of 16 columns (variables) and 48895 rows.\nIt includes the follwoing variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ab_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspc_tbl_ [48,895 × 16] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ id                            : num [1:48895] 2539 2595 3647 3831 5022 ...\n $ name                          : chr [1:48895] \"Clean & quiet apt home by the park\" \"Skylit Midtown Castle\" \"THE VILLAGE OF HARLEM....NEW YORK !\" \"Cozy Entire Floor of Brownstone\" ...\n $ host_id                       : num [1:48895] 2787 2845 4632 4869 7192 ...\n $ host_name                     : chr [1:48895] \"John\" \"Jennifer\" \"Elisabeth\" \"LisaRoxanne\" ...\n $ neighbourhood_group           : chr [1:48895] \"Brooklyn\" \"Manhattan\" \"Manhattan\" \"Brooklyn\" ...\n $ neighbourhood                 : chr [1:48895] \"Kensington\" \"Midtown\" \"Harlem\" \"Clinton Hill\" ...\n $ latitude                      : num [1:48895] 40.6 40.8 40.8 40.7 40.8 ...\n $ longitude                     : num [1:48895] -74 -74 -73.9 -74 -73.9 ...\n $ room_type                     : chr [1:48895] \"Private room\" \"Entire home/apt\" \"Private room\" \"Entire home/apt\" ...\n $ price                         : num [1:48895] 149 225 150 89 80 200 60 79 79 150 ...\n $ minimum_nights                : num [1:48895] 1 1 3 1 10 3 45 2 2 1 ...\n $ number_of_reviews             : num [1:48895] 9 45 0 270 9 74 49 430 118 160 ...\n $ last_review                   : Date[1:48895], format: \"2018-10-19\" \"2019-05-21\" ...\n $ reviews_per_month             : num [1:48895] 0.21 0.38 NA 4.64 0.1 0.59 0.4 3.47 0.99 1.33 ...\n $ calculated_host_listings_count: num [1:48895] 6 2 1 1 1 1 1 1 1 4 ...\n $ availability_365              : num [1:48895] 365 355 365 194 0 129 0 220 0 188 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   id = col_double(),\n  ..   name = col_character(),\n  ..   host_id = col_double(),\n  ..   host_name = col_character(),\n  ..   neighbourhood_group = col_character(),\n  ..   neighbourhood = col_character(),\n  ..   latitude = col_double(),\n  ..   longitude = col_double(),\n  ..   room_type = col_character(),\n  ..   price = col_double(),\n  ..   minimum_nights = col_double(),\n  ..   number_of_reviews = col_double(),\n  ..   last_review = col_date(format = \"\"),\n  ..   reviews_per_month = col_double(),\n  ..   calculated_host_listings_count = col_double(),\n  ..   availability_365 = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(ab_df,\n                         varnumbers = FALSE,\n                         plain.ascii  = FALSE,\n                         style        = \"grid\",\n                         graph.magnif = 0.80,\n                        valid.col    = FALSE),\n       method = 'render',\n       table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>ab_df</h4>\n<strong>Dimensions</strong>: 48895 x 16\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">id\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19017143 (10983108)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2539 &le; 19677284 &le; 36487245</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 19680234 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">48895 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAD6LF/2gAAAL1JREFUWMPt1AEOgzAIBdBeYbuB7Q3G/e82pIVVU0xk2dz0ExI1+JIG2qZ07bjtjXvOmR9hTvQABz+S8w6e3F9HxSUvRD4fFQ/jclTjvMwQPMi5+R6vd2i7SR1OkmNO3eL+nHMTuGiHLs+fPteevjhRkZx0JVu8tAL4Pm5TsfHJIIxL3edW66ff8dLeP8D7lQV4X6uw7sAw1/wFrr0J8tUvp+U68SBfJjg4+Ak43wrvcE5wcHDwr/IcjHTteAJmspyw5eBSuwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowMyswMDowMNutungAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDMrMDA6MDCq8ALEAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">name\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Hillside Hotel</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Home away from home</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. New york Multi-unit build</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Brooklyn Apartment</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Loft Suite @ The Box Hous</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Private Room</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Artsy Private BR in Fort </td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Private room</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Beautiful Brooklyn Browns</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Cozy Brooklyn Apartment</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 47884 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">18</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">17</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">16</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">48758</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">99.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAIQAAADWBAMAAADiLDdoAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAGmNuLVQAAAJxJREFUaN7t07ENgDAAA8GswAjABrD/bimgoI4tZMnvAa54yWOw7/ZtfRAQEF2EIGQRhhYQEBAlhCBkEYYWEBAQJYQgZBGGFhAQECWEIGQRhhYQEBAlhCBkEYYWEBAQJYQgZBGGFhAQECWEIGQRhhYQEBAlhCBkEYYWEBAQJYQgZBGGFhAQECWEIGQRh7CXOO/lXRAQEH8RhrOzZxMpGrWQJjetDAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowNiswMDowMImVld8AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDYrMDA6MDD4yC1jAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">16\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">host_id\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 67620011 (78610967)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2438 &le; 30793816 &le; 274321313</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 99612390 (1.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">37457 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAGmNuLVQAAAHtJREFUWMPt12EKgCAMhmGvkDfIbtDuf7cSEpYouFEE+X4wZOADE/1jCHMnnVkXey6+iQgcDofD4XA4HA6H+7jnQ6K4ZwI4/HNuffcVt04Af5JbLq/BLRO8x0cO0eGZllXtjlXf46p2RaLc+xFeSI5U/SDv1R94cibMnQOoJpakbYCuCAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowNiswMDowMImVld8AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDYrMDA6MDD4yC1jAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">host_name\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Michael</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. David</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Sonder (NYC)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. John</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Alex</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Blueground</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Sarah</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Daniel</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Jessica</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Maria</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 11442 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">417</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">403</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">327</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">294</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">279</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">232</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">227</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">226</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">205</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">204</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">46060</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAH0AAADWBAMAAAAOdZA7AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAAJFJREFUaN7t07ERwgAMBEGXYDrApgT6742ECl6BpPFevsFrRseh+5V18jy/3od8jO++H8/zfT7kY3z3/Xie7/MhH+O778fzfJ8P+Rh/8Tz/WB/yMb66n+f5vT7kY3x1P8/ze33Ix/jqfp7n9/qQj/HV/TzP7/UhH+Or+3me3+tDPsbfYe+//3yzeJ6v++r/PrkfFOiFDvwD63UAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjFUMDA6NDg6MDcrMDA6MDAv4p5rAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIxVDAwOjQ4OjA3KzAwOjAwXr8m1wAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">21\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">neighbourhood_group\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Bronx</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Brooklyn</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Manhattan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Queens</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Staten Island</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1091</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">20104</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">41.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">21661</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">44.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5666</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">373</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEIAAABmBAMAAACNR1r7AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAAGNJREFUSMdjYBg8QElREBeAqlAeVTGCVRBOH4KClKtQwgUQLjXGDoxGVYwAFYTTBzVSIQXpVEmJgF+AvhlVMcRVEI59uqZCRdwqoH4ZVTEiVRBOH4K4AfGpcFTFqAqKVAwGAAB5jiP4eW1GrQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowNyswMDowMC/inmsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDcrMDA6MDBevybXAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">neighbourhood\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Williamsburg</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Bedford-Stuyvesant</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Harlem</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Bushwick</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Upper West Side</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Hell's Kitchen</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. East Village</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Upper East Side</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Crown Heights</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Midtown</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 211 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3920</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3714</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">7.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2658</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2465</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1971</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1958</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1853</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1798</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1564</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1545</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">25449</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">52.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEsAAADWBAMAAABrmGJEAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAAIZJREFUaN7t1cEJgDAQRNGU4HZgTAem/95UEG8Z9qAwxD/nd1n4sKV4b7sWwy03a733HQYbsmRIofcNI3LYK8w88ppg56UwmGDJkEKPyGHGzDzyDGvqY8Fg2ZBCj8hhxsw78pq7FAZTLBlS6BE5zJgROWx6RuSw6Zl35HLrc6kc7PcsGZLrDvXBK7/qSbktAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjQ4OjA3KzAwOjAwL+KeawAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDo0ODowNyswMDowMF6/JtcAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">latitude\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 40.7 (0.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">40.5 &le; 40.7 &le; 40.9</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0.1 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">19048 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAALVJREFUWMPt2G0OQDAMBuBdgRuoG+j974bFjK1NrEN8vP3LE8tLpzj372r0aolIPXiAMw9mPl26hvc8gIPbOFFXw5nBwe/nym59lPdy3xRwqW8KuBQAOPjD+DQVVfGFgYODv5K3yYuulCdLuJP7zyo7z/P7KvdB2XkUZ/LdhFfOdxMe+NN4GCysfCtSHncsE49P7it56BuBz/+41lZXeIhf4tnJV3B/9zKerFvnPr+Fk7Hcv2sE6zTW00UtRoMAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjFUMDA6NDg6MDcrMDA6MDAv4p5rAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIxVDAwOjQ4OjA3KzAwOjAwXr8m1wAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">longitude\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : -74 (0)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">-74.2 &le; -74 &le; -73.7</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">14718 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAAG9JREFUWMPt1tEJwCAMRdGs0BV0g3b/3VpCISAJ1XwU0ft+5cgThERk7xxRiiY8/uL1enLC4XA4HD4tDwddHw8rwOFwOBwOh8OX57pK5rnKVbi3Vg9wr8LPvHnBKG8qpLhV8Ll9OJfbHS8vycjeuQEuZKDT2Y3CBwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowNyswMDowMC/inmsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDcrMDA6MDBevybXAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">room_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Entire home/apt</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Private room</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Shared room</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">25409</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">52.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">22326</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">45.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1160</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEsAAAA/BAMAAABa0ygOAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAAEpJREFUSMdjYBjcQAk/UIAqUzbGC0aVjSojThmR6U0QPxAgTRkeCxWRlOHxwqiyUWXEKyMyvVE7kROlTNloVNmoMiooIzK9DVYAALwO82uk95uHAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjQ4OjA3KzAwOjAwL+KeawAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDo0ODowNyswMDowMF6/JtcAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">price\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 152.7 (240.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 106 &le; 10000</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 106 (1.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">674 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAAEFJREFUWMPty6EBgDAQBLBfgRG4bsDvv1sNAv3IJj5VZ0tyXwNvX926ruu6ruu6ruu6ruu6rn97kj999TPuGaqzbWQ3VUNu+6O8AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjQ4OjA3KzAwOjAwL+KeawAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDo0ODowNyswMDowMF6/JtcAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">minimum_nights\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 7 (20.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 3 &le; 1250</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 4 (2.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">109 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAADxJREFUWMPtyzENACAMALBZwAI4YP69ERIMwEWy9m9EbX1r904fmTl1Xdd1Xdd1Xdd1Xdd1Xf+i90dR2wJHU2Td66MYeAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowNyswMDowMC/inmsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDcrMDA6MDBevybXAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">number_of_reviews\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 23.3 (44.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 5 &le; 629</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 23 (1.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">394 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAH79y7wwAAAFpJREFUWMPt2DEOABAMQNFewRHUDfT+d0PSwWCgk/B/YnyNsFXk73SUznNezKzC4XA4HA6Hw+FwOBwOh8Pv5IHVz8wDN3iKj+fLcd6PHYxY8eIjNn7RuQaTv2sSEmtXkXl9ZgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowNyswMDowMC/inmsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDcrMDA6MDBevybXAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">last_review\n[Date]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min : 2011-03-28</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">med : 2019-05-19</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">max : 2019-07-08</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">range : 8y 3m 10d</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">1764 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAIf2OmUgAAAHFJREFUWMPt2MEJgDAMQNGuoBtYNzD772YCCkILNgkepP+f+wgEemhLmbslUNUSfBc54HA4HA6Hw+FwOBwOf2/VB2iGiwgc7sn+PBLc3C/5fdWi/HJebmMfKx/m5rZm7DjXk+1YF2/d97y7rC6vwcrcnTfVc/ACfodUAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjQ4OjA4KzAwOjAw2aruggAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDo0ODowOCswMDowMKj3Vj4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">10052\n(20.6%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reviews_per_month\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1.4 (1.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0.7 &le; 58.5</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1.8 (1.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">937 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAIf2OmUgAAAEpJREFUWMPt2LENwCAQBMFvgRZwB3z/vVlIDkgfEZnZfKSLL+Lu+qzV+/iTmQPHcRzHcRzHcRzHcRzHf8Y3brOVZ33CGd43i7t7AflLZoS+7UKBAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjQ4OjA4KzAwOjAw2aruggAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDo0ODowOCswMDowMKj3Vj4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">10052\n(20.6%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">calculated_host_listings_count\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 7.1 (33)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 1 &le; 327</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (4.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">47 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAIf2OmUgAAAE5JREFUWMPt2LENgDAMRUGv4BEwG5D9dwMlaShoIrrc676sW8ARe1dPudDkZ2sXjuM4juM4juM4juM4juM/8uodmR/Pu3F87Zq8Fou9uwHrGFttGnOZUgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowOCswMDowMNmq7oIAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDgrMDA6MDCo91Y+AAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">availability_365\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 112.8 (131.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 45 &le; 365</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 227 (1.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">366 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAIf2OmUgAAAIdJREFUWMPt2MsNgCAQRVFakA4cOoD+exNBvjFEia64L7MwMgcHliq1dkRk3yZyceMcHA6Hw+FwOBwOh8PhcDj8J/7u142WkMLTAOfCA+uc9dXwuKN/W/fd8Wh7HsrWvHrOyZ8ec91OEqGPSXbAy/HSjQZYWka8ni9dSdcy4m2Zvr7mMhm1dg4dkXf67UQuewAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODowOCswMDowMNmq7oIAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MDgrMDA6MDCo91Y+AAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-12-20</p>\n</div>\n```\n:::\n:::\n\n\n`AB_NYC_2019` documents the information on the accommodation in New York (as you can figure out from the name of the original csv file and the average longitude and latitude) that is registered on Air BnB as of sometime in 2019.\nThe information includes 1) id and name of the accommodation 2) id and name of the host 3) geographic information of the accommodation (neighbourhood_group, latitude, longitude) 4) reservation-related information of the accommodation (room type, price, minimum night per stay) 5) information of the reviews (date of last review, total number of review, average number of review per month) 6) days available of the accommodation per year\n\nThe accommodations without any review have NA (missing value) in `last_review` and `reviews_per_month` as we can see that the number of missing values in `last_review` and `reviews_per_month` (10052) matches the number of accommodations whose `number_of_review` is 0\n\n\n::: {.cell}\n\n```{.r .cell-code}\nab_df %>% filter(`number_of_reviews` == 0) %>%\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n      n\n  <int>\n1 10052\n```\n:::\n:::\n\n\nThis dataset is quite tidy because one row means one observation (one accommodation), however it can be separated into `host_df` dataframe and `accommodation_df` dataframe to make this dataset cleaner and easier to use.\n\n\\###`Accommodation_df`\n\nI created `accommodation_df` as follows removing `host_name`, `calculated_host_listings_count` columns.\n(\\* We should NOT remove `host_id` because it will be necessary if we want to join `accomodation_df` and `host_df`)\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df <- ab_df %>%\n  select(-c(host_name, calculated_host_listings_count))\n\nhead(accommodation_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n     id name       host_id neigh…¹ neigh…² latit…³ longi…⁴ room_…⁵ price minim…⁶\n  <dbl> <chr>        <dbl> <chr>   <chr>     <dbl>   <dbl> <chr>   <dbl>   <dbl>\n1  2539 Clean & q…    2787 Brookl… Kensin…    40.6   -74.0 Privat…   149       1\n2  2595 Skylit Mi…    2845 Manhat… Midtown    40.8   -74.0 Entire…   225       1\n3  3647 THE VILLA…    4632 Manhat… Harlem     40.8   -73.9 Privat…   150       3\n4  3831 Cozy Enti…    4869 Brookl… Clinto…    40.7   -74.0 Entire…    89       1\n5  5022 Entire Ap…    7192 Manhat… East H…    40.8   -73.9 Entire…    80      10\n6  5099 Large Coz…    7322 Manhat… Murray…    40.7   -74.0 Entire…   200       3\n# … with 4 more variables: number_of_reviews <dbl>, last_review <date>,\n#   reviews_per_month <dbl>, availability_365 <dbl>, and abbreviated variable\n#   names ¹​neighbourhood_group, ²​neighbourhood, ³​latitude, ⁴​longitude,\n#   ⁵​room_type, ⁶​minimum_nights\n```\n:::\n:::\n\n\nI realized that there are 17,541 observations with 0 as `price` and/or `availability_365`, which doesn't make sense for an accommodation listing on AirBnB.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(accommodation_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       id               name              host_id          neighbourhood_group\n Min.   :    2539   Length:48895       Min.   :     2438   Length:48895       \n 1st Qu.: 9471945   Class :character   1st Qu.:  7822033   Class :character   \n Median :19677284   Mode  :character   Median : 30793816   Mode  :character   \n Mean   :19017143                      Mean   : 67620011                      \n 3rd Qu.:29152178                      3rd Qu.:107434423                      \n Max.   :36487245                      Max.   :274321313                      \n                                                                              \n neighbourhood         latitude       longitude       room_type        \n Length:48895       Min.   :40.50   Min.   :-74.24   Length:48895      \n Class :character   1st Qu.:40.69   1st Qu.:-73.98   Class :character  \n Mode  :character   Median :40.72   Median :-73.96   Mode  :character  \n                    Mean   :40.73   Mean   :-73.95                     \n                    3rd Qu.:40.76   3rd Qu.:-73.94                     \n                    Max.   :40.91   Max.   :-73.71                     \n                                                                       \n     price         minimum_nights    number_of_reviews  last_review        \n Min.   :    0.0   Min.   :   1.00   Min.   :  0.00    Min.   :2011-03-28  \n 1st Qu.:   69.0   1st Qu.:   1.00   1st Qu.:  1.00    1st Qu.:2018-07-08  \n Median :  106.0   Median :   3.00   Median :  5.00    Median :2019-05-19  \n Mean   :  152.7   Mean   :   7.03   Mean   : 23.27    Mean   :2018-10-04  \n 3rd Qu.:  175.0   3rd Qu.:   5.00   3rd Qu.: 24.00    3rd Qu.:2019-06-23  \n Max.   :10000.0   Max.   :1250.00   Max.   :629.00    Max.   :2019-07-08  \n                                                       NA's   :10052       \n reviews_per_month availability_365\n Min.   : 0.010    Min.   :  0.0   \n 1st Qu.: 0.190    1st Qu.:  0.0   \n Median : 0.720    Median : 45.0   \n Mean   : 1.373    Mean   :112.8   \n 3rd Qu.: 2.020    3rd Qu.:227.0   \n Max.   :58.500    Max.   :365.0   \n NA's   :10052                     \n```\n:::\n\n```{.r .cell-code}\naccommodation_df %>% \n  select(c(\"name\", \"price\", \"availability_365\")) %>%\n  filter(price == 0 | availability_365 == 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 17,541 × 3\n   name                                               price availability_365\n   <chr>                                              <dbl>            <dbl>\n 1 Entire Apt: Spacious Studio/Loft by central park      80                0\n 2 BlissArtsSpace!                                       60                0\n 3 Cozy Clean Guest Room - Family Apt                    79                0\n 4 West Village Nest - Superhost                        120                0\n 5 Sweet and Spacious Brooklyn Loft                     299                0\n 6 Magnifique Suite au N de Manhattan - vue Cloitres     80                0\n 7 bright and stylish duplex                            115                0\n 8 Light-filled 2B duplex in the heart of Park Slope!   225                0\n 9 Great Location for NYC                                50                0\n10 Charming 1 bed GR8 WBurg LOCATION!                   100                0\n# … with 17,531 more rows\n```\n:::\n:::\n\n\nThese listings should be considered unavailable or at least not ready for receiving the travelers, so I created a new column `outlier` (1 = outlier, 0 = no outlier).\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df <- accommodation_df %>%\n  mutate(outlier = case_when(.$price == 0|.$availability_365 == 0 ~ 1, \n                                  TRUE ~ 0))\n```\n:::\n\n\nLooking at `minimum_nights`, I noticed that some accommodations require a lot of days for the minimum nights.\n\nI learned from the below table that 1) The minimum nights of 85% + listings are 7 nights or less.\n2) The minimum nights of 98% + listings are 31 nights or less.\n3) There are small peaks at 30 nights (3760), 60 nights (106), 90 nights (104), and 120 nights (28), inferring that some listings require 1,2,3, or 4 month stay.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df %>%\n  group_by(minimum_nights) %>%\n  dplyr::summarize(\n    frequency = n(),\n  ) %>%\n  mutate(\n    cumulative_percentage = cumsum(frequency)/sum(frequency)*100\n  ) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n| minimum_nights| frequency| cumulative_percentage|\n|--------------:|---------:|---------------------:|\n|              1|     12720|              26.01493|\n|              2|     11696|              49.93558|\n|              3|      7999|              66.29512|\n|              4|      3303|              73.05041|\n|              5|      3034|              79.25555|\n|              6|       752|              80.79354|\n|              7|      2058|              85.00256|\n|              8|       130|              85.26843|\n|              9|        80|              85.43205|\n|             10|       483|              86.41988|\n|             11|        33|              86.48737|\n|             12|        91|              86.67348|\n|             13|        54|              86.78392|\n|             14|       562|              87.93333|\n|             15|       279|              88.50394|\n|             16|        18|              88.54075|\n|             17|        14|              88.56938|\n|             18|        28|              88.62665|\n|             19|         8|              88.64301|\n|             20|       223|              89.09909|\n|             21|       135|              89.37519|\n|             22|         8|              89.39155|\n|             23|         8|              89.40791|\n|             24|        14|              89.43655|\n|             25|        82|              89.60425|\n|             26|        16|              89.63698|\n|             27|        17|              89.67175|\n|             28|       203|              90.08692|\n|             29|       340|              90.78229|\n|             30|      3760|              98.47224|\n|             31|       201|              98.88332|\n|             32|         8|              98.89968|\n|             33|         2|              98.90377|\n|             35|        15|              98.93445|\n|             36|         1|              98.93650|\n|             37|         1|              98.93854|\n|             39|         1|              98.94059|\n|             40|        13|              98.96717|\n|             42|         1|              98.96922|\n|             43|         1|              98.97127|\n|             44|         2|              98.97536|\n|             45|        32|              99.04080|\n|             47|         2|              99.04489|\n|             50|        14|              99.07352|\n|             53|         2|              99.07762|\n|             55|         4|              99.08580|\n|             56|         2|              99.08989|\n|             58|         1|              99.09193|\n|             59|         6|              99.10420|\n|             60|       106|              99.32099|\n|             62|         3|              99.32713|\n|             65|         1|              99.32917|\n|             68|         1|              99.33122|\n|             70|         8|              99.34758|\n|             74|         1|              99.34963|\n|             75|         4|              99.35781|\n|             80|         9|              99.37621|\n|             85|         1|              99.37826|\n|             87|         1|              99.38030|\n|             88|         2|              99.38440|\n|             90|       104|              99.59710|\n|             91|         3|              99.60323|\n|             93|         2|              99.60732|\n|             98|         1|              99.60937|\n|             99|         2|              99.61346|\n|            100|        15|              99.64414|\n|            105|         2|              99.64823|\n|            110|         3|              99.65436|\n|            114|         1|              99.65641|\n|            115|         2|              99.66050|\n|            120|        28|              99.71776|\n|            122|         1|              99.71981|\n|            133|         2|              99.72390|\n|            134|         1|              99.72594|\n|            150|         6|              99.73821|\n|            153|         1|              99.74026|\n|            160|         2|              99.74435|\n|            175|         1|              99.74640|\n|            180|        43|              99.83434|\n|            181|         2|              99.83843|\n|            182|         1|              99.84047|\n|            183|         1|              99.84252|\n|            184|         1|              99.84456|\n|            185|         1|              99.84661|\n|            186|         1|              99.84866|\n|            198|         1|              99.85070|\n|            200|         4|              99.85888|\n|            210|         2|              99.86297|\n|            222|         1|              99.86502|\n|            225|         1|              99.86706|\n|            240|         3|              99.87320|\n|            250|         1|              99.87524|\n|            265|         1|              99.87729|\n|            270|         2|              99.88138|\n|            275|         1|              99.88342|\n|            299|         1|              99.88547|\n|            300|         6|              99.89774|\n|            354|         1|              99.89979|\n|            360|         5|              99.91001|\n|            364|         1|              99.91206|\n|            365|        29|              99.97137|\n|            366|         1|              99.97341|\n|            370|         1|              99.97546|\n|            400|         1|              99.97750|\n|            480|         1|              99.97955|\n|            500|         5|              99.98977|\n|            999|         3|              99.99591|\n|           1000|         1|              99.99795|\n|           1250|         1|             100.00000|\n:::\n:::\n\n\nThus, it is fairly safe to consider that the accommodation that require more than 31 days (1 month) for the minimum nights as outliers.\nSince these accommodations are not available for short-term travelers, I consider them as \"outlier\" (`outlier` = 1)\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df <- accommodation_df %>%\n  mutate(outlier = case_when(.$price == 0|.$availability_365 == 0| minimum_nights > 31 ~ 1, \n                                  TRUE ~ 0))\n\naccommodation_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 48,895 × 15\n      id name      host_id neigh…¹ neigh…² latit…³ longi…⁴ room_…⁵ price minim…⁶\n   <dbl> <chr>       <dbl> <chr>   <chr>     <dbl>   <dbl> <chr>   <dbl>   <dbl>\n 1  2539 Clean & …    2787 Brookl… Kensin…    40.6   -74.0 Privat…   149       1\n 2  2595 Skylit M…    2845 Manhat… Midtown    40.8   -74.0 Entire…   225       1\n 3  3647 THE VILL…    4632 Manhat… Harlem     40.8   -73.9 Privat…   150       3\n 4  3831 Cozy Ent…    4869 Brookl… Clinto…    40.7   -74.0 Entire…    89       1\n 5  5022 Entire A…    7192 Manhat… East H…    40.8   -73.9 Entire…    80      10\n 6  5099 Large Co…    7322 Manhat… Murray…    40.7   -74.0 Entire…   200       3\n 7  5121 BlissArt…    7356 Brookl… Bedfor…    40.7   -74.0 Privat…    60      45\n 8  5178 Large Fu…    8967 Manhat… Hell's…    40.8   -74.0 Privat…    79       2\n 9  5203 Cozy Cle…    7490 Manhat… Upper …    40.8   -74.0 Privat…    79       2\n10  5238 Cute & C…    7549 Manhat… Chinat…    40.7   -74.0 Entire…   150       1\n# … with 48,885 more rows, 5 more variables: number_of_reviews <dbl>,\n#   last_review <date>, reviews_per_month <dbl>, availability_365 <dbl>,\n#   outlier <dbl>, and abbreviated variable names ¹​neighbourhood_group,\n#   ²​neighbourhood, ³​latitude, ⁴​longitude, ⁵​room_type, ⁶​minimum_nights\n```\n:::\n:::\n\n\nSome accommodations cost more than 1000 USD per night, which is extremely expensive.\nLooking at the below table, only less than 0.5% of accommodations charge 1000+ USD per night so I decided to consider those accommodations as outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df %>%\n  group_by(price) %>%\n  dplyr::summarize(\n    frequency = n(),\n  ) %>%\n  mutate(\n    cumulative_percentage = cumsum(frequency)/sum(frequency)*100\n  ) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n| price| frequency| cumulative_percentage|\n|-----:|---------:|---------------------:|\n|     0|        11|             0.0224972|\n|    10|        17|             0.0572656|\n|    11|         3|             0.0634012|\n|    12|         4|             0.0715820|\n|    13|         1|             0.0736272|\n|    15|         6|             0.0858984|\n|    16|         6|             0.0981695|\n|    18|         2|             0.1022599|\n|    19|         4|             0.1104407|\n|    20|        33|             0.1779323|\n|    21|         6|             0.1902035|\n|    22|        16|             0.2229267|\n|    23|         7|             0.2372431|\n|    24|        13|             0.2638307|\n|    25|       100|             0.4683505|\n|    26|        24|             0.5174353|\n|    27|        29|             0.5767461|\n|    28|        55|             0.6892320|\n|    29|        67|             0.8262604|\n|    30|       255|             1.3477861|\n|    31|        46|             1.4418652|\n|    32|        82|             1.6095715|\n|    33|        93|             1.7997750|\n|    34|        84|             1.9715717|\n|    35|       480|             2.9532672|\n|    36|       103|             3.1639227|\n|    37|       132|             3.4338889|\n|    38|       167|             3.7754372|\n|    39|       196|             4.1762961|\n|    40|       771|             5.7531445|\n|    41|        86|             5.9290316|\n|    42|       192|             6.3217098|\n|    43|       113|             6.5528173|\n|    44|       119|             6.7961959|\n|    45|       891|             8.6184681|\n|    46|       102|             8.8270784|\n|    47|       163|             9.1604459|\n|    48|       203|             9.5756212|\n|    49|       345|            10.2812148|\n|    50|      1534|            13.4185500|\n|    51|        96|            13.6148890|\n|    52|       131|            13.8828101|\n|    53|       118|            14.1241436|\n|    54|       112|            14.3532058|\n|    55|       950|            16.2961448|\n|    56|        74|            16.4474895|\n|    57|       109|            16.6704162|\n|    58|       157|            16.9915124|\n|    59|       297|            17.5989365|\n|    60|      1458|            20.5808365|\n|    61|        54|            20.6912772|\n|    62|       140|            20.9776051|\n|    63|       108|            21.1984866|\n|    64|        90|            21.3825545|\n|    65|      1190|            23.8163411|\n|    66|        87|            23.9942734|\n|    67|       107|            24.2131097|\n|    68|       160|            24.5403415|\n|    69|       372|            25.3011555|\n|    70|      1170|            27.6940382|\n|    71|        60|            27.8167502|\n|    72|       124|            28.0703548|\n|    73|        84|            28.2421515|\n|    74|        68|            28.3812251|\n|    75|      1370|            31.1831476|\n|    76|        68|            31.3222211|\n|    77|        90|            31.5062890|\n|    78|       122|            31.7558033|\n|    79|       299|            32.3673177|\n|    80|      1272|            34.9688107|\n|    81|        51|            35.0731159|\n|    82|        71|            35.2183250|\n|    83|        63|            35.3471725|\n|    84|        75|            35.5005624|\n|    85|       877|            37.2942019|\n|    86|        79|            37.4557726|\n|    87|        83|            37.6255241|\n|    88|       115|            37.8607220|\n|    89|       365|            38.6072196|\n|    90|      1021|            40.6953676|\n|    91|        52|            40.8017180|\n|    92|        61|            40.9264751|\n|    93|        64|            41.0573678|\n|    94|        68|            41.1964414|\n|    95|       700|            42.6280806|\n|    96|        64|            42.7589733|\n|    97|        91|            42.9450864|\n|    98|       137|            43.2252787|\n|    99|       742|            44.7428162|\n|   100|      2051|            48.9375192|\n|   101|        46|            49.0315983|\n|   102|        45|            49.1236323|\n|   103|        49|            49.2238470|\n|   104|        44|            49.3138358|\n|   105|       325|            49.9785254|\n|   106|        35|            50.0501074|\n|   107|        42|            50.1360057|\n|   108|        54|            50.2464465|\n|   109|       152|            50.5573167|\n|   110|       739|            52.0687187|\n|   111|        38|            52.1464362|\n|   112|        53|            52.2548318|\n|   113|        42|            52.3407301|\n|   114|        28|            52.3979957|\n|   115|       468|            53.3551488|\n|   116|        34|            53.4246856|\n|   117|        53|            53.5330811|\n|   118|        57|            53.6496574|\n|   119|       191|            54.0402904|\n|   120|      1130|            56.3513652|\n|   121|        23|            56.3984047|\n|   122|        41|            56.4822579|\n|   123|        44|            56.5722467|\n|   124|        47|            56.6683710|\n|   125|      1057|            58.8301462|\n|   126|        33|            58.8976378|\n|   127|        27|            58.9528582|\n|   128|        60|            59.0755701|\n|   129|       207|            59.4989263|\n|   130|       610|            60.7464976|\n|   131|        24|            60.7955824|\n|   132|        36|            60.8692095|\n|   133|        53|            60.9776051|\n|   134|        36|            61.0512322|\n|   135|       415|            61.8999898|\n|   136|        24|            61.9490745|\n|   137|        35|            62.0206565|\n|   138|        38|            62.0983741|\n|   139|       170|            62.4460579|\n|   140|       548|            63.5668269|\n|   141|        11|            63.5893241|\n|   142|        55|            63.7018100|\n|   143|        24|            63.7508948|\n|   144|        31|            63.8142959|\n|   145|       323|            64.4748952|\n|   146|        25|            64.5260252|\n|   147|        32|            64.5914715|\n|   148|        50|            64.6937315|\n|   149|       278|            65.2622968|\n|   150|      2047|            69.4488189|\n|   151|        35|            69.5204009|\n|   152|        24|            69.5694856|\n|   153|        21|            69.6124348|\n|   154|        34|            69.6819716|\n|   155|       183|            70.0562430|\n|   156|        21|            70.0991921|\n|   157|        20|            70.1400961|\n|   158|        37|            70.2157685|\n|   159|       164|            70.5511811|\n|   160|       480|            71.5328766|\n|   161|        15|            71.5635546|\n|   162|        22|            71.6085489|\n|   163|        22|            71.6535433|\n|   164|        23|            71.7005829|\n|   165|       315|            72.3448205|\n|   166|        20|            72.3857245|\n|   167|        23|            72.4327641|\n|   168|        34|            72.5023008|\n|   169|       123|            72.7538603|\n|   170|       295|            73.3571940|\n|   171|        12|            73.3817364|\n|   172|        28|            73.4390019|\n|   173|        16|            73.4717251|\n|   174|        31|            73.5351263|\n|   175|       763|            75.0956130|\n|   176|        19|            75.1344718|\n|   177|        30|            75.1958278|\n|   178|        23|            75.2428674|\n|   179|       143|            75.5353308|\n|   180|       522|            76.6029246|\n|   181|        14|            76.6315574|\n|   182|        21|            76.6745066|\n|   183|         9|            76.6929134|\n|   184|        24|            76.7419982|\n|   185|       236|            77.2246651|\n|   186|        18|            77.2614787|\n|   187|        24|            77.3105635|\n|   188|        30|            77.3719194|\n|   189|       123|            77.6234789|\n|   190|       292|            78.2206770|\n|   191|        13|            78.2472645|\n|   192|        10|            78.2677165|\n|   193|         5|            78.2779425|\n|   194|        15|            78.3086205|\n|   195|       293|            78.9078638|\n|   196|        27|            78.9630842|\n|   197|        28|            79.0203497|\n|   198|        58|            79.1389713|\n|   199|       415|            79.9877288|\n|   200|      1401|            82.8530525|\n|   201|         8|            82.8694141|\n|   202|        15|            82.9000920|\n|   203|         9|            82.9184988|\n|   204|         7|            82.9328152|\n|   205|        50|            83.0350752|\n|   206|        15|            83.0657531|\n|   207|        12|            83.0902955|\n|   208|        13|            83.1168831|\n|   209|        46|            83.2109623|\n|   210|       133|            83.4829737|\n|   211|        12|            83.5075161|\n|   212|        14|            83.5361489|\n|   213|         3|            83.5422845|\n|   214|        14|            83.5709173|\n|   215|       111|            83.7979343|\n|   216|         4|            83.8061151|\n|   217|        12|            83.8306575|\n|   218|        12|            83.8551999|\n|   219|        56|            83.9697311|\n|   220|       254|            84.4892116|\n|   221|         8|            84.5055732|\n|   222|        14|            84.5342060|\n|   223|         6|            84.5464771|\n|   224|        13|            84.5730647|\n|   225|       451|            85.4954494|\n|   226|        12|            85.5199918|\n|   227|        14|            85.5486246|\n|   228|        23|            85.5956642|\n|   229|        64|            85.7265569|\n|   230|       109|            85.9494836|\n|   231|         6|            85.9617548|\n|   232|        10|            85.9822068|\n|   233|        11|            86.0047040|\n|   234|        12|            86.0292463|\n|   235|        66|            86.1642295|\n|   236|        10|            86.1846815|\n|   237|         6|            86.1969527|\n|   238|         6|            86.2092238|\n|   239|       106|            86.4260149|\n|   240|       114|            86.6591676|\n|   241|         9|            86.6775744|\n|   242|         4|            86.6857552|\n|   243|        10|            86.7062072|\n|   244|        15|            86.7368852|\n|   245|        93|            86.9270887|\n|   246|         7|            86.9414051|\n|   247|        11|            86.9639022|\n|   248|        15|            86.9945802|\n|   249|       133|            87.2665917|\n|   250|      1018|            89.3486042|\n|   251|         5|            89.3588301|\n|   252|         7|            89.3731465|\n|   253|         3|            89.3792821|\n|   254|         7|            89.3935985|\n|   255|        42|            89.4794969|\n|   256|         8|            89.4958585|\n|   257|         5|            89.5060845|\n|   258|         5|            89.5163105|\n|   259|        30|            89.5776664|\n|   260|        81|            89.7433275|\n|   261|         5|            89.7535535|\n|   262|         8|            89.7699151|\n|   263|         5|            89.7801411|\n|   264|        12|            89.8046835|\n|   265|        58|            89.9233050|\n|   266|         1|            89.9253502|\n|   267|         9|            89.9437570|\n|   268|         6|            89.9560282|\n|   269|        33|            90.0235198|\n|   270|        42|            90.1094181|\n|   271|        10|            90.1298701|\n|   272|         4|            90.1380509|\n|   273|         5|            90.1482769|\n|   274|         9|            90.1666837|\n|   275|       244|            90.6657122|\n|   276|         8|            90.6820738|\n|   277|         3|            90.6882094|\n|   278|        15|            90.7188874|\n|   279|        23|            90.7659270|\n|   280|        91|            90.9520401|\n|   281|         2|            90.9561305|\n|   282|         5|            90.9663565|\n|   283|         5|            90.9765825|\n|   284|         2|            90.9806729|\n|   285|        65|            91.1136108|\n|   287|         7|            91.1279272|\n|   288|        12|            91.1524696|\n|   289|        38|            91.2301871|\n|   290|        63|            91.3590347|\n|   291|         3|            91.3651703|\n|   292|         1|            91.3672155|\n|   293|         3|            91.3733511|\n|   294|         6|            91.3856223|\n|   295|       114|            91.6187749|\n|   296|         1|            91.6208201|\n|   297|         5|            91.6310461|\n|   298|        13|            91.6576337|\n|   299|       161|            91.9869107|\n|   300|       561|            93.1342673|\n|   301|         1|            93.1363125|\n|   302|         7|            93.1506289|\n|   303|         7|            93.1649453|\n|   304|         3|            93.1710809|\n|   305|        23|            93.2181205|\n|   306|         6|            93.2303917|\n|   307|         5|            93.2406177|\n|   308|         7|            93.2549340|\n|   309|         7|            93.2692504|\n|   310|        21|            93.3121996|\n|   311|         2|            93.3162900|\n|   312|         9|            93.3346968|\n|   313|         1|            93.3367420|\n|   314|         9|            93.3551488|\n|   315|        19|            93.3940076|\n|   316|        13|            93.4205952|\n|   317|         4|            93.4287759|\n|   318|         1|            93.4308211|\n|   319|         8|            93.4471827|\n|   320|        39|            93.5269455|\n|   321|         6|            93.5392167|\n|   322|         1|            93.5412619|\n|   323|         2|            93.5453523|\n|   324|         2|            93.5494427|\n|   325|       120|            93.7948666|\n|   327|         1|            93.7969117|\n|   328|         3|            93.8030473|\n|   329|        13|            93.8296349|\n|   330|        27|            93.8848553|\n|   331|         1|            93.8869005|\n|   332|         3|            93.8930361|\n|   333|         9|            93.9114429|\n|   334|         5|            93.9216689|\n|   335|         8|            93.9380305|\n|   336|         1|            93.9400757|\n|   337|         2|            93.9441661|\n|   338|         1|            93.9462113|\n|   339|        16|            93.9789345|\n|   340|        18|            94.0157480|\n|   341|         4|            94.0239288|\n|   342|         1|            94.0259740|\n|   343|         4|            94.0341548|\n|   344|         1|            94.0362000|\n|   345|        25|            94.0873300|\n|   346|         2|            94.0914204|\n|   347|         4|            94.0996012|\n|   348|         3|            94.1057368|\n|   349|        45|            94.1977707|\n|   350|       381|            94.9769915|\n|   352|         4|            94.9851723|\n|   353|         1|            94.9872175|\n|   355|        10|            95.0076695|\n|   356|         2|            95.0117599|\n|   358|         7|            95.0260763|\n|   359|        13|            95.0526639|\n|   360|        21|            95.0956130|\n|   361|         1|            95.0976582|\n|   362|         1|            95.0997034|\n|   365|        18|            95.1365170|\n|   367|         2|            95.1406074|\n|   369|        19|            95.1794662|\n|   370|        13|            95.2060538|\n|   372|         2|            95.2101442|\n|   373|         1|            95.2121894|\n|   374|         6|            95.2244606|\n|   375|        72|            95.3717149|\n|   376|         3|            95.3778505|\n|   377|         5|            95.3880765|\n|   378|         3|            95.3942121|\n|   379|        16|            95.4269353|\n|   380|        36|            95.5005624|\n|   381|         1|            95.5026076|\n|   382|         3|            95.5087432|\n|   383|         1|            95.5107884|\n|   385|        14|            95.5394212|\n|   386|         1|            95.5414664|\n|   387|         2|            95.5455568|\n|   388|         3|            95.5516924|\n|   389|        10|            95.5721444|\n|   390|        24|            95.6212292|\n|   392|         4|            95.6294100|\n|   393|         2|            95.6335004|\n|   394|         2|            95.6375908|\n|   395|        41|            95.7214439|\n|   396|         6|            95.7337151|\n|   397|         1|            95.7357603|\n|   398|         8|            95.7521219|\n|   399|        89|            95.9341446|\n|   400|       225|            96.3943143|\n|   402|         1|            96.3963595|\n|   403|         2|            96.4004499|\n|   404|         2|            96.4045403|\n|   407|         2|            96.4086307|\n|   408|         3|            96.4147663|\n|   409|         5|            96.4249923|\n|   410|         6|            96.4372635|\n|   412|         5|            96.4474895|\n|   414|         2|            96.4515799|\n|   415|         5|            96.4618059|\n|   416|         4|            96.4699867|\n|   417|         1|            96.4720319|\n|   418|         2|            96.4761223|\n|   419|         5|            96.4863483|\n|   420|        13|            96.5129359|\n|   421|         2|            96.5170263|\n|   422|         1|            96.5190715|\n|   423|         1|            96.5211167|\n|   424|         1|            96.5231619|\n|   425|        50|            96.6254218|\n|   426|         1|            96.6274670|\n|   428|         1|            96.6295122|\n|   429|         5|            96.6397382|\n|   430|         6|            96.6520094|\n|   431|         1|            96.6540546|\n|   432|         2|            96.6581450|\n|   433|         2|            96.6622354|\n|   434|         1|            96.6642806|\n|   435|         3|            96.6704162|\n|   436|         1|            96.6724614|\n|   438|         2|            96.6765518|\n|   439|         2|            96.6806422|\n|   440|         4|            96.6888230|\n|   442|         1|            96.6908682|\n|   443|         3|            96.6970038|\n|   444|         2|            96.7010942|\n|   445|         2|            96.7051846|\n|   446|         1|            96.7072298|\n|   447|         2|            96.7113202|\n|   449|        12|            96.7358626|\n|   450|       156|            97.0549136|\n|   451|         2|            97.0590040|\n|   452|         1|            97.0610492|\n|   453|         1|            97.0630944|\n|   454|         1|            97.0651396|\n|   455|         4|            97.0733204|\n|   459|         5|            97.0835464|\n|   460|         7|            97.0978628|\n|   462|         1|            97.0999080|\n|   463|         1|            97.1019532|\n|   465|         7|            97.1162696|\n|   466|         2|            97.1203600|\n|   468|         2|            97.1244504|\n|   469|         1|            97.1264956|\n|   470|         4|            97.1346763|\n|   471|         1|            97.1367215|\n|   472|         3|            97.1428571|\n|   474|         1|            97.1449023|\n|   475|        23|            97.1919419|\n|   477|         1|            97.1939871|\n|   478|         2|            97.1980775|\n|   479|         5|            97.2083035|\n|   480|         8|            97.2246651|\n|   481|         1|            97.2267103|\n|   483|         1|            97.2287555|\n|   484|         2|            97.2328459|\n|   485|         7|            97.2471623|\n|   487|         2|            97.2512527|\n|   488|         2|            97.2553431|\n|   489|         7|            97.2696595|\n|   490|         7|            97.2839759|\n|   495|        25|            97.3351058|\n|   496|         1|            97.3371510|\n|   497|         1|            97.3391962|\n|   498|         1|            97.3412414|\n|   499|        65|            97.4741794|\n|   500|       191|            97.8648124|\n|   503|         2|            97.8689028|\n|   505|         3|            97.8750383|\n|   506|         1|            97.8770835|\n|   509|         1|            97.8791287|\n|   510|         2|            97.8832191|\n|   515|         3|            97.8893547|\n|   519|         1|            97.8913999|\n|   520|         5|            97.9016259|\n|   524|         1|            97.9036711|\n|   525|        15|            97.9343491|\n|   530|         2|            97.9384395|\n|   531|         1|            97.9404847|\n|   534|         7|            97.9548011|\n|   539|         1|            97.9568463|\n|   540|         3|            97.9629819|\n|   545|         5|            97.9732079|\n|   549|         5|            97.9834339|\n|   550|        51|            98.0877390|\n|   555|         1|            98.0897842|\n|   559|         1|            98.0918294|\n|   560|         5|            98.1020554|\n|   561|         1|            98.1041006|\n|   573|         1|            98.1061458|\n|   575|        12|            98.1306882|\n|   577|         2|            98.1347786|\n|   578|         1|            98.1368238|\n|   580|         1|            98.1388690|\n|   583|         2|            98.1429594|\n|   584|         1|            98.1450046|\n|   585|         5|            98.1552306|\n|   587|         1|            98.1572758|\n|   589|         2|            98.1613662|\n|   590|         8|            98.1777278|\n|   595|        13|            98.2043154|\n|   599|        19|            98.2431741|\n|   600|        81|            98.4088353|\n|   612|         1|            98.4108805|\n|   615|         2|            98.4149709|\n|   616|         1|            98.4170161|\n|   619|         1|            98.4190613|\n|   620|         2|            98.4231517|\n|   625|         4|            98.4313324|\n|   639|         1|            98.4333776|\n|   640|         2|            98.4374680|\n|   643|         1|            98.4395132|\n|   647|         1|            98.4415584|\n|   649|         7|            98.4558748|\n|   650|        55|            98.5683608|\n|   655|         1|            98.5704060|\n|   659|         1|            98.5724512|\n|   670|         2|            98.5765416|\n|   672|         2|            98.5806320|\n|   675|        13|            98.6072196|\n|   680|         1|            98.6092648|\n|   688|         1|            98.6113099|\n|   689|         1|            98.6133551|\n|   690|         4|            98.6215359|\n|   692|         1|            98.6235811|\n|   695|         2|            98.6276715|\n|   699|        35|            98.6992535|\n|   700|        47|            98.7953779|\n|   714|        12|            98.8199202|\n|   718|         1|            98.8219654|\n|   720|         1|            98.8240106|\n|   725|         1|            98.8260558|\n|   737|        10|            98.8465078|\n|   745|         2|            98.8505982|\n|   748|         7|            98.8649146|\n|   749|         2|            98.8690050|\n|   750|        45|            98.9610390|\n|   760|         2|            98.9651294|\n|   766|         1|            98.9671746|\n|   780|         1|            98.9692198|\n|   785|         2|            98.9733102|\n|   789|         1|            98.9753554|\n|   790|         2|            98.9794458|\n|   794|         1|            98.9814909|\n|   795|         6|            98.9937621|\n|   799|        18|            99.0305757|\n|   800|        54|            99.1410165|\n|   805|         1|            99.1430617|\n|   814|         1|            99.1451069|\n|   820|         1|            99.1471521|\n|   822|         1|            99.1491973|\n|   825|         2|            99.1532877|\n|   830|         1|            99.1553329|\n|   840|         2|            99.1594233|\n|   843|         1|            99.1614685|\n|   848|         1|            99.1635137|\n|   850|        19|            99.2023724|\n|   860|         2|            99.2064628|\n|   875|         1|            99.2085080|\n|   888|         1|            99.2105532|\n|   890|         3|            99.2166888|\n|   894|         1|            99.2187340|\n|   895|         3|            99.2248696|\n|   898|         1|            99.2269148|\n|   899|         5|            99.2371408|\n|   900|        20|            99.2780448|\n|   913|         1|            99.2800900|\n|   920|         1|            99.2821352|\n|   930|         1|            99.2841804|\n|   935|         1|            99.2862256|\n|   945|         3|            99.2923612|\n|   949|         2|            99.2964516|\n|   950|        11|            99.3189488|\n|   956|         3|            99.3250844|\n|   974|         1|            99.3271296|\n|   975|         4|            99.3353104|\n|   980|         2|            99.3394008|\n|   985|         1|            99.3414460|\n|   990|         1|            99.3434912|\n|   995|         6|            99.3557623|\n|   999|        17|            99.3905307|\n|  1000|        59|            99.5111975|\n|  1002|         1|            99.5132427|\n|  1020|         1|            99.5152879|\n|  1046|         1|            99.5173331|\n|  1050|         3|            99.5234687|\n|  1066|         1|            99.5255139|\n|  1067|         1|            99.5275591|\n|  1075|         1|            99.5296043|\n|  1080|         1|            99.5316495|\n|  1095|         1|            99.5336947|\n|  1099|         1|            99.5357399|\n|  1100|        12|            99.5602822|\n|  1115|         1|            99.5623274|\n|  1145|         1|            99.5643726|\n|  1150|         2|            99.5684630|\n|  1170|         1|            99.5705082|\n|  1177|         1|            99.5725534|\n|  1195|         2|            99.5766438|\n|  1200|        15|            99.6073218|\n|  1250|         6|            99.6195930|\n|  1295|         1|            99.6216382|\n|  1299|         1|            99.6236834|\n|  1300|         3|            99.6298190|\n|  1306|         1|            99.6318642|\n|  1308|         1|            99.6339094|\n|  1315|         1|            99.6359546|\n|  1333|         1|            99.6379998|\n|  1350|         2|            99.6420902|\n|  1369|         1|            99.6441354|\n|  1395|         1|            99.6461806|\n|  1400|         2|            99.6502710|\n|  1450|         1|            99.6523162|\n|  1475|         1|            99.6543614|\n|  1485|         1|            99.6564066|\n|  1494|         1|            99.6584518|\n|  1495|         1|            99.6604970|\n|  1497|         1|            99.6625422|\n|  1500|        26|            99.7157174|\n|  1550|         1|            99.7177626|\n|  1599|         2|            99.7218530|\n|  1600|         4|            99.7300337|\n|  1680|         1|            99.7320789|\n|  1700|         4|            99.7402597|\n|  1731|         1|            99.7423049|\n|  1749|         1|            99.7443501|\n|  1750|         3|            99.7504857|\n|  1763|         1|            99.7525309|\n|  1795|         1|            99.7545761|\n|  1799|         1|            99.7566213|\n|  1800|         2|            99.7607117|\n|  1880|         1|            99.7627569|\n|  1899|         1|            99.7648021|\n|  1900|         1|            99.7668473|\n|  1978|         1|            99.7688925|\n|  1999|         3|            99.7750281|\n|  2000|        24|            99.8241129|\n|  2010|         1|            99.8261581|\n|  2100|         1|            99.8282033|\n|  2103|         1|            99.8302485|\n|  2200|         1|            99.8322937|\n|  2250|         2|            99.8363841|\n|  2300|         1|            99.8384293|\n|  2350|         1|            99.8404745|\n|  2400|         1|            99.8425197|\n|  2500|        11|            99.8650169|\n|  2545|         1|            99.8670621|\n|  2590|         1|            99.8691073|\n|  2600|         1|            99.8711525|\n|  2626|         1|            99.8731977|\n|  2695|         1|            99.8752429|\n|  2750|         1|            99.8772881|\n|  2800|         1|            99.8793333|\n|  2850|         1|            99.8813785|\n|  2900|         1|            99.8834237|\n|  2990|         1|            99.8854689|\n|  2995|         1|            99.8875141|\n|  2999|         2|            99.8916045|\n|  3000|         8|            99.9079660|\n|  3200|         1|            99.9100112|\n|  3210|         1|            99.9120564|\n|  3512|         1|            99.9141016|\n|  3518|         1|            99.9161468|\n|  3600|         1|            99.9181920|\n|  3613|         1|            99.9202372|\n|  3750|         2|            99.9243276|\n|  3800|         1|            99.9263728|\n|  3900|         1|            99.9284180|\n|  4000|         3|            99.9345536|\n|  4100|         1|            99.9365988|\n|  4160|         1|            99.9386440|\n|  4200|         2|            99.9427344|\n|  4500|         2|            99.9468248|\n|  5000|         6|            99.9590960|\n|  5100|         1|            99.9611412|\n|  5250|         1|            99.9631864|\n|  6000|         2|            99.9672768|\n|  6419|         1|            99.9693220|\n|  6500|         3|            99.9754576|\n|  6800|         1|            99.9775028|\n|  7500|         2|            99.9815932|\n|  7703|         1|            99.9836384|\n|  8000|         1|            99.9856836|\n|  8500|         1|            99.9877288|\n|  9999|         3|            99.9938644|\n| 10000|         3|           100.0000000|\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df <- accommodation_df %>%\n  mutate(outlier = case_when(.$price == 0|.$price > 1000|.$availability_365 == 0| minimum_nights > 31 ~ 1, \n                                  TRUE ~ 0))\n\naccommodation_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 48,895 × 15\n      id name      host_id neigh…¹ neigh…² latit…³ longi…⁴ room_…⁵ price minim…⁶\n   <dbl> <chr>       <dbl> <chr>   <chr>     <dbl>   <dbl> <chr>   <dbl>   <dbl>\n 1  2539 Clean & …    2787 Brookl… Kensin…    40.6   -74.0 Privat…   149       1\n 2  2595 Skylit M…    2845 Manhat… Midtown    40.8   -74.0 Entire…   225       1\n 3  3647 THE VILL…    4632 Manhat… Harlem     40.8   -73.9 Privat…   150       3\n 4  3831 Cozy Ent…    4869 Brookl… Clinto…    40.7   -74.0 Entire…    89       1\n 5  5022 Entire A…    7192 Manhat… East H…    40.8   -73.9 Entire…    80      10\n 6  5099 Large Co…    7322 Manhat… Murray…    40.7   -74.0 Entire…   200       3\n 7  5121 BlissArt…    7356 Brookl… Bedfor…    40.7   -74.0 Privat…    60      45\n 8  5178 Large Fu…    8967 Manhat… Hell's…    40.8   -74.0 Privat…    79       2\n 9  5203 Cozy Cle…    7490 Manhat… Upper …    40.8   -74.0 Privat…    79       2\n10  5238 Cute & C…    7549 Manhat… Chinat…    40.7   -74.0 Entire…   150       1\n# … with 48,885 more rows, 5 more variables: number_of_reviews <dbl>,\n#   last_review <date>, reviews_per_month <dbl>, availability_365 <dbl>,\n#   outlier <dbl>, and abbreviated variable names ¹​neighbourhood_group,\n#   ²​neighbourhood, ³​latitude, ⁴​longitude, ⁵​room_type, ⁶​minimum_nights\n```\n:::\n:::\n\n\n\\###`host_df`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhost_df <- ab_df %>%\n  select(c(host_id, host_name, calculated_host_listings_count))\n\nhead(host_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  host_id host_name   calculated_host_listings_count\n    <dbl> <chr>                                <dbl>\n1    2787 John                                     6\n2    2845 Jennifer                                 2\n3    4632 Elisabeth                                1\n4    4869 LisaRoxanne                              1\n5    7192 Laura                                    1\n6    7322 Chris                                    1\n```\n:::\n:::\n\n\n`host_df` needs to be cleaned because it has several duplicated information.\nFor example, `host_id` should be unique however the same host_id appear multiple times as the below table shows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhost_df %>% group_by(host_id) %>%\n  dplyr::summarise(number =n()) %>%\n  arrange(desc(number))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 37,457 × 2\n     host_id number\n       <dbl>  <int>\n 1 219517861    327\n 2 107434423    232\n 3  30283594    121\n 4 137358866    103\n 5  12243051     96\n 6  16098958     96\n 7  61391963     91\n 8  22541573     87\n 9 200380610     65\n10   1475015     52\n# … with 37,447 more rows\n```\n:::\n:::\n\n\nSo I removed duplicated rows by using `distinct()` function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhost_df <- host_df %>% distinct(host_id, .keep_all = TRUE) %>%\n  arrange(desc(calculated_host_listings_count))\n\nhead(host_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n    host_id host_name      calculated_host_listings_count\n      <dbl> <chr>                                   <dbl>\n1 219517861 Sonder (NYC)                              327\n2 107434423 Blueground                                232\n3  30283594 Kara                                      121\n4 137358866 Kazuya                                    103\n5  16098958 Jeremy & Laura                             96\n6  12243051 Sonder                                     96\n```\n:::\n:::\n\n\nAlso, I renamed the column name `calculated_host_listings_count` to make it easier to understand\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(host_df)[3] <- \"total_accommodation_count\"\nhead(host_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n    host_id host_name      total_accommodation_count\n      <dbl> <chr>                              <dbl>\n1 219517861 Sonder (NYC)                         327\n2 107434423 Blueground                           232\n3  30283594 Kara                                 121\n4 137358866 Kazuya                               103\n5  16098958 Jeremy & Laura                        96\n6  12243051 Sonder                                96\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(host_df,\n                         varnumbers = FALSE,\n                         plain.ascii  = FALSE,\n                         style        = \"grid\",\n                         graph.magnif = 0.80,\n                        valid.col    = FALSE),\n       method = 'render',\n       table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>host_df</h4>\n<strong>Dimensions</strong>: 37457 x 3\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">host_id\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 61445493 (75117502)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2438 &le; 26790498 &le; 274321313</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 81121712 (1.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">37457 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAKkW3HfgAAAHtJREFUWMPt12EKgCAMhuFdoW6Q3UDvf7csJkgkuEUk+H4whj8emegfReZOyNkWe5TvKSU4HA6Hw+FwOBwO/4V7/jMV90wAh7/n1od749YJ4ANxy90/cMsE3/DeAzR42aLEwbVibrESq2539U5eT1LWZ+/krRqCB2dk7hxypZCcM3lMFwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDo0ODoxMCswMDowMCbvoHsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6NDg6MTArMDA6MDBXshjHAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">host_name\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Michael</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. David</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Alex</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Daniel</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Sarah</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. John</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Andrew</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Chris</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Maria</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Anna</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 11442 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">335</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">318</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">226</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">208</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">199</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">188</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">163</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">162</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">161</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">156</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">35323</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAH0AAADWBAMAAAAOdZA7AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAL5mr36AAAAJFJREFUaN7t07ENw0AMBEGVIHdgySWo/96UuIJj8CR+Lp9gCfA47P5kO3meH+9D3savvh/P8+t8yNv41ffjeX6dD3kbf/E8v60PeRtf7ed5fq4PeRtf7ed5fq4PeRtf7ed5fq4PeRtf7ed5fq4PeRtf7ed5fq4PeRtf7ed5fq4PeRt/h/v+/e/JxvN83Vf/d+e9zvuE/qDTS4AAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjFUMDA6NDg6MTErMDA6MDCAmKvPAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIxVDAwOjQ4OjExKzAwOjAw8cUTcwAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">18\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">total_accommodation_count\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1.3 (2.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 1 &le; 327</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (2.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">47 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaBAMAAACIxS+mAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwVADAL5mr36AAAADtJREFUWMPtyzENACAMALBZwAI4YP69wYGCXSRr/0b0Nq9R8PrK3Lqu67qu67qu67qu67qu/9FnUfR2ADUpWiwUMYh+AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjQ4OjExKzAwOjAwgJirzwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDo0ODoxMSswMDowMPHFE3MAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-12-20</p>\n</div>\n```\n:::\n:::\n\n\n## Visualization with Multiple Dimensions\n\n**What are the characteristics of each neighborhood?**\n\nFirst, I decided to visualize the number of accommodation listings by room types and neighborhood groups.\n\n1)  Most listings are located in Manhattan or Brooklyn.\n2)  There are few listings of shared rooms compared to entire home and private rooms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df %>% \n  filter(outlier==0) %>%\n  group_by(neighbourhood_group, room_type)%>%\n  dplyr::summarize(\n    frequency = n()\n  ) %>%\n  ggplot(aes(fill=room_type, y=frequency, x=neighbourhood_group)) + geom_bar(position=\"stack\", stat=\"identity\") +\n  labs(title = \"The number of accommodation listings by room types and neibhgourhood groups\")\n```\n\n::: {.cell-output-display}\n![](challenge7_ErikaNagai_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nI decided to visualize the price data by neighbourhood group with a violin plot because it allows us to see the distribution and the volume for several groups.\n\nI learned that, 1) Manhattan is the most expensive neighbourhood regardless of room types.\n2) Even though Manhattan and Brooklyn are typically more expensive than other neighbourhoods, they offer more reasonable entire home/apartments as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df %>% filter(outlier==0) %>%\n  ggplot(aes(neighbourhood_group, price)) +\n  geom_violin() +\n  facet_wrap(vars(room_type)) + \n  theme(axis.text.x = element_text(angle = 45)) +\n  labs(title = \"Price per night by room types and neighbourhood groups\") +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](challenge7_ErikaNagai_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naccommodation_df %>% filter(outlier == 0) %>%\n  ggplot(aes(reviews_per_month)) + \n  geom_boxplot() + \n  facet_grid(neighbourhood_group~room_type) +\n  scale_x_continuous(limits=c(0,30), breaks=seq(0,30,5)) +\n  labs(title = \"The number of reviews per month by room types and neighbourhood groups\")\n```\n\n::: {.cell-output-display}\n![](challenge7_ErikaNagai_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "challenge7_ErikaNagai_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}