{
  "hash": "ee856a874024006e8c362a14962138bc",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3\"\nauthor: \"Siddharth Nammara Kalyana Raman\"\ndesription: \"Tidy Data: Pivoting\"\ndate: \"12/02/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - animal_weights\n  - eggs\n  - australian_marriage\n  - usa_households\n  - sce_labor\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(summarytools)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1.  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2.  identify what needs to be done to tidy the current data\n3.  anticipate the shape of pivoted data\n4.  pivot the data into tidy format using `pivot_longer`\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   animal_weights.csv ⭐\n-   eggs_tidy.csv ⭐⭐ or organiceggpoultry.xls ⭐⭐⭐\n-   australian_marriage\\*.xls ⭐⭐⭐\n-   USA Households\\*.xlsx ⭐⭐⭐⭐\n-   sce_labor_chart_data_public.xlsx 🌟🌟🌟🌟🌟\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#read data and name it eggs_data\neggs_data<-read.csv('_data/eggs_tidy.csv')\neggs_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        month year large_half_dozen large_dozen extra_large_half_dozen\n1     January 2004          126.000     230.000                132.000\n2    February 2004          128.500     226.250                134.500\n3       March 2004          131.000     225.000                137.000\n4       April 2004          131.000     225.000                137.000\n5         May 2004          131.000     225.000                137.000\n6        June 2004          133.500     231.375                137.000\n7        July 2004          133.500     233.500                137.000\n8      August 2004          133.500     233.500                137.000\n9   September 2004          129.750     233.500                135.875\n10    October 2004          128.500     233.500                135.500\n11   November 2004          128.500     233.500                135.500\n12   December 2004          128.500     233.500                135.500\n13    January 2005          128.500     233.500                135.500\n14   February 2005          128.500     233.500                135.500\n15      March 2005          128.500     233.500                135.500\n16      April 2005          128.500     233.500                135.500\n17        May 2005          128.500     233.500                135.500\n18       June 2005          128.500     233.500                135.500\n19       July 2005          128.500     233.500                135.500\n20     August 2005          128.500     233.500                135.500\n21  September 2005          128.500     233.500                135.500\n22    October 2005          128.500     233.500                135.500\n23   November 2005          128.500     233.500                135.500\n24   December 2005          128.500     233.500                135.500\n25    January 2006          128.500     233.500                135.500\n26   February 2006          128.500     233.500                135.500\n27      March 2006          128.500     233.500                135.500\n28      April 2006          128.500     233.500                135.500\n29        May 2006          128.500     233.500                135.500\n30       June 2006          128.500     233.500                135.500\n31       July 2006          128.500     233.500                135.500\n32     August 2006          128.500     233.500                135.500\n33  September 2006          128.500     233.500                135.500\n34    October 2006          128.500     233.500                135.500\n35   November 2006          128.500     233.500                135.500\n36   December 2006          128.500     233.500                135.500\n37    January 2007          128.500     233.500                135.500\n38   February 2007          131.125     236.125                138.125\n39      March 2007          132.000     237.000                139.000\n40      April 2007          132.000     237.000                139.000\n41        May 2007          132.000     237.000                139.000\n42       June 2007          132.000     237.000                139.000\n43       July 2007          132.000     237.000                139.000\n44     August 2007          132.000     237.000                139.000\n45  September 2007          132.000     237.000                139.000\n46    October 2007          132.000     237.000                139.000\n47   November 2007          132.000     237.000                139.000\n48   December 2007          132.000     237.000                139.000\n49    January 2008          132.000     237.000                139.000\n50   February 2008          132.000     237.000                139.000\n51      March 2008          132.000     237.000                139.000\n52      April 2008          132.000     237.000                139.000\n53        May 2008          132.000     237.000                139.000\n54       June 2008          174.500     277.500                185.500\n55       July 2008          174.500     277.500                185.500\n56     August 2008          174.500     277.500                185.500\n57  September 2008          174.500     277.500                185.500\n58    October 2008          174.500     277.500                185.500\n59   November 2008          174.500     277.500                185.500\n60   December 2008          174.500     277.500                185.500\n61    January 2009          174.500     277.500                185.500\n62   February 2009          174.500     277.500                185.500\n63      March 2009          174.500     277.500                185.500\n64      April 2009          174.500     277.500                185.500\n65        May 2009          174.500     277.500                185.500\n66       June 2009          174.500     277.500                185.500\n67       July 2009          174.500     277.500                185.500\n68     August 2009          174.500     271.500                185.500\n69  September 2009          174.500     271.500                185.500\n70    October 2009          174.500     271.500                185.500\n71   November 2009          174.500     271.500                185.500\n72   December 2009          174.500     271.500                185.500\n73    January 2010          174.500     271.500                185.500\n74   February 2010          174.500     271.500                185.500\n75      March 2010          174.500     268.000                185.500\n76      April 2010          174.500     268.000                185.500\n77        May 2010          174.500     268.000                185.500\n78       June 2010          174.500     268.000                185.500\n79       July 2010          174.500     268.000                185.500\n80     August 2010          174.500     268.000                185.500\n81  September 2010          174.500     268.000                185.500\n82    October 2010          174.500     267.500                185.500\n83   November 2010          174.500     267.500                185.500\n84   December 2010          174.500     267.500                185.500\n85    January 2011          174.500     267.500                185.500\n86   February 2011          174.500     267.500                185.500\n87      March 2011          174.500     267.500                185.500\n88      April 2011          174.500     267.500                185.500\n89        May 2011          174.500     267.500                185.500\n90       June 2011          174.500     270.000                185.500\n91       July 2011          174.500     270.000                185.500\n92     August 2011          174.500     270.000                185.500\n93  September 2011          174.500     270.000                185.500\n94    October 2011          174.500     270.000                185.500\n95   November 2011          174.500     270.000                185.500\n96   December 2011          174.500     270.000                185.500\n97    January 2012          174.500     267.500                185.500\n98   February 2012          174.500     267.500                185.500\n99      March 2012          174.500     267.500                185.500\n100     April 2012          174.500     267.500                185.500\n101       May 2012          173.250     267.500                185.500\n102      June 2012          173.250     267.500                185.500\n103      July 2012          173.250     267.500                185.500\n104    August 2012          173.250     267.500                185.500\n105 September 2012          173.250     267.500                185.500\n106   October 2012          173.250     267.500                185.500\n107  November 2012          178.000     267.500                188.130\n108  December 2012          178.000     267.500                188.130\n109   January 2013          178.000     267.500                188.130\n110  February 2013          178.000     267.500                188.130\n111     March 2013          178.000     267.500                188.130\n112     April 2013          178.000     267.500                188.130\n113       May 2013          178.000     267.500                188.130\n114      June 2013          178.000     267.500                188.130\n115      July 2013          178.000     267.500                188.130\n116    August 2013          178.000     267.500                188.130\n117 September 2013          178.000     267.500                188.130\n118   October 2013          178.000     267.500                188.130\n119  November 2013          178.000     267.500                188.130\n120  December 2013          178.000     267.500                188.130\n    extra_large_dozen\n1             230.000\n2             230.000\n3             230.000\n4             234.500\n5             236.000\n6             241.000\n7             241.000\n8             241.000\n9             241.000\n10            241.000\n11            241.000\n12            241.000\n13            241.000\n14            241.000\n15            241.000\n16            241.000\n17            241.000\n18            241.000\n19            241.000\n20            241.000\n21            241.000\n22            241.000\n23            241.000\n24            241.000\n25            241.000\n26            241.000\n27            241.375\n28            241.500\n29            241.500\n30            241.500\n31            241.500\n32            241.500\n33            241.500\n34            241.500\n35            241.500\n36            241.500\n37            241.500\n38            244.125\n39            245.000\n40            245.000\n41            245.000\n42            245.000\n43            245.000\n44            245.000\n45            245.000\n46            245.000\n47            245.000\n48            245.000\n49            245.000\n50            245.000\n51            245.000\n52            245.000\n53            245.000\n54            285.500\n55            285.500\n56            285.500\n57            285.500\n58            285.500\n59            285.500\n60            285.500\n61            285.500\n62            285.500\n63            285.500\n64            285.500\n65            285.500\n66            285.500\n67            285.500\n68            285.500\n69            285.500\n70            285.500\n71            285.500\n72            285.500\n73            285.500\n74            285.500\n75            285.500\n76            285.500\n77            285.500\n78            285.500\n79            285.500\n80            285.500\n81            285.500\n82            285.500\n83            285.500\n84            285.500\n85            285.500\n86            285.500\n87            285.500\n88            285.500\n89            285.500\n90            285.500\n91            285.500\n92            285.500\n93            285.500\n94            285.500\n95            285.500\n96            285.500\n97            285.500\n98            288.500\n99            288.500\n100           288.500\n101           288.500\n102           288.500\n103           288.500\n104           288.500\n105           288.500\n106           288.500\n107           290.000\n108           290.000\n109           290.000\n110           290.000\n111           290.000\n112           290.000\n113           290.000\n114           290.000\n115           290.000\n116           290.000\n117           290.000\n118           290.000\n119           290.000\n120           290.000\n```\n:::\n:::\n\n\n### Briefly describe the data\n\nDescribe the data, and be sure to comment on why you are planning to pivot it to make it \"tidy\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(dfSummary(eggs_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \neggs_data  \nDimensions: 120 x 6  \nDuplicates: 0  \n\n-------------------------------------------------------------------------------------------------------------------------\nNo   Variable                 Stats / Values             Freqs (% of Valid)    Graph                 Valid      Missing  \n---- ------------------------ -------------------------- --------------------- --------------------- ---------- ---------\n1    month                    1. April                   10 ( 8.3%)            I                     120        0        \n     [character]              2. August                  10 ( 8.3%)            I                     (100.0%)   (0.0%)   \n                              3. December                10 ( 8.3%)            I                                         \n                              4. February                10 ( 8.3%)            I                                         \n                              5. January                 10 ( 8.3%)            I                                         \n                              6. July                    10 ( 8.3%)            I                                         \n                              7. June                    10 ( 8.3%)            I                                         \n                              8. March                   10 ( 8.3%)            I                                         \n                              9. May                     10 ( 8.3%)            I                                         \n                              10. November               10 ( 8.3%)            I                                         \n                              [ 2 others ]               20 (16.7%)            III                                       \n\n2    year                     Mean (sd) : 2008.5 (2.9)   2004 : 12 (10.0%)     II                    120        0        \n     [integer]                min < med < max:           2005 : 12 (10.0%)     II                    (100.0%)   (0.0%)   \n                              2004 < 2008.5 < 2013       2006 : 12 (10.0%)     II                                        \n                              IQR (CV) : 5 (0)           2007 : 12 (10.0%)     II                                        \n                                                         2008 : 12 (10.0%)     II                                        \n                                                         2009 : 12 (10.0%)     II                                        \n                                                         2010 : 12 (10.0%)     II                                        \n                                                         2011 : 12 (10.0%)     II                                        \n                                                         2012 : 12 (10.0%)     II                                        \n                                                         2013 : 12 (10.0%)     II                                        \n\n3    large_half_dozen         Mean (sd) : 155.2 (22.6)   126.00 :  1 ( 0.8%)                         120        0        \n     [numeric]                min < med < max:           128.50 : 29 (24.2%)   IIII                  (100.0%)   (0.0%)   \n                              126 < 174.5 < 178          129.75 :  1 ( 0.8%)                                             \n                              IQR (CV) : 45.1 (0.1)      131.00 :  3 ( 2.5%)                                             \n                                                         131.12!:  1 ( 0.8%)                                             \n                                                         132.00 : 15 (12.5%)   II                                        \n                                                         133.50 :  3 ( 2.5%)                                             \n                                                         173.25 :  6 ( 5.0%)   I                                         \n                                                         174.50 : 47 (39.2%)   IIIIIII                                   \n                                                         178.00 : 14 (11.7%)   II                                        \n                                                         ! rounded                                                       \n\n4    large_dozen              Mean (sd) : 254.2 (18.5)   12 distinct values                    :     120        0        \n     [numeric]                min < med < max:                                                 :     (100.0%)   (0.0%)   \n                              225 < 267.5 < 277.5                                :             :                         \n                              IQR (CV) : 34.5 (0.1)                              : .           : .                       \n                                                                               . : :           : :                       \n\n5    extra_large_half_dozen   Mean (sd) : 164.2 (24.7)   132.00 :  1 ( 0.8%)                         120        0        \n     [numeric]                min < med < max:           134.50 :  1 ( 0.8%)                         (100.0%)   (0.0%)   \n                              132 < 185.5 < 188.1        135.50 : 28 (23.3%)   IIII                                      \n                              IQR (CV) : 49.7 (0.2)      135.88!:  1 ( 0.8%)                                             \n                                                         137.00 :  6 ( 5.0%)   I                                         \n                                                         138.12!:  1 ( 0.8%)                                             \n                                                         139.00 : 15 (12.5%)   II                                        \n                                                         185.50 : 53 (44.2%)   IIIIIIII                                  \n                                                         188.13 : 14 (11.7%)   II                                        \n                                                         ! rounded                                                       \n\n6    extra_large_dozen        Mean (sd) : 266.8 (22.8)   11 distinct values              :           120        0        \n     [numeric]                min < med < max:                                   .       :           (100.0%)   (0.0%)   \n                              230 < 285.5 < 290                                  :       :                               \n                              IQR (CV) : 44 (0.1)                                :       :                               \n                                                                               . :       :                               \n-------------------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# to know the statistics of the eggs dataset\nsummary(eggs_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    month                year      large_half_dozen  large_dozen   \n Length:120         Min.   :2004   Min.   :126.0    Min.   :225.0  \n Class :character   1st Qu.:2006   1st Qu.:129.4    1st Qu.:233.5  \n Mode  :character   Median :2008   Median :174.5    Median :267.5  \n                    Mean   :2008   Mean   :155.2    Mean   :254.2  \n                    3rd Qu.:2011   3rd Qu.:174.5    3rd Qu.:268.0  \n                    Max.   :2013   Max.   :178.0    Max.   :277.5  \n extra_large_half_dozen extra_large_dozen\n Min.   :132.0          Min.   :230.0    \n 1st Qu.:135.8          1st Qu.:241.5    \n Median :185.5          Median :285.5    \n Mean   :164.2          Mean   :266.8    \n 3rd Qu.:185.5          3rd Qu.:285.5    \n Max.   :188.1          Max.   :290.0    \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# review the first few rows of the dataset\nhead(eggs_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     month year large_half_dozen large_dozen extra_large_half_dozen\n1  January 2004            126.0     230.000                  132.0\n2 February 2004            128.5     226.250                  134.5\n3    March 2004            131.0     225.000                  137.0\n4    April 2004            131.0     225.000                  137.0\n5      May 2004            131.0     225.000                  137.0\n6     June 2004            133.5     231.375                  137.0\n  extra_large_dozen\n1             230.0\n2             230.0\n3             230.0\n4             234.5\n5             236.0\n6             241.0\n```\n:::\n:::\n\nWe can see from the rendered data frame summary that there are 6 columns and 120 rows of data, covering the years 2004 through 2013 as well as all 12 months of the year. The remaining 4 columns, with values ranging from 126-290, are large half dozen, large dozen, extra large half dozen, and extra large dozen. \n\n## Anticipate the End Result\n\nThe first step in pivoting the data is to try to come up with a concrete vision of what the end product *should* look like - that way you will know whether or not your pivoting was successful.\n\nOne easy way to do this is to think about the dimensions of your current data (tibble, dataframe, or matrix), and then calculate what the dimensions of the pivoted data should be.\n\nSuppose you have a dataset with $n$ rows and $k$ variables. In our example, 3 of the variables are used to identify a case, so you will be pivoting $k-3$ variables into a longer format where the $k-3$ variable names will move into the `names_to` variable and the current values in each of those columns will move into the `values_to` variable. Therefore, we would expect $n * (k-3)$ rows in the pivoted dataframe!\n\n\n### Example: find current and future data dimensions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Finding the dimensions before pivoting\n#number of rows\nnrow(eggs_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 120\n```\n:::\n\n```{.r .cell-code}\n#number of columns\nncol(eggs_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#expected dimensions after pivot\n\n#expected number of rows\nnrow(eggs_data)*(ncol(eggs_data)-2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 480\n```\n:::\n\n```{.r .cell-code}\n#expected number of cols\n3+2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5\n```\n:::\n:::\n\n\n\nOr simple example has $n = 6$ rows and $k - 3 = 2$ variables being pivoted, so we expect a new dataframe to have $n * 2 = 12$ rows x $3 + 2 = 5$ columns.\n\n### Challenge: Describe the final dimensions\n\nDocument your work here.\n\nDue to the fact that each size-quantity pairing will have its own row, I anticipate the eventual data set to be four times longer (rather than the initial 4 columns after month and year). Since I will delete the names of the four size-quantity columns and replace them with one column each for size, quantity, and average price, I anticipate that the overall number of columns will decrease by one. For this newly reorganized data, see below.\n\n\nAny additional comments?\n\n## Pivot the Data\n\nNow we will pivot the data, and compare our pivoted data dimensions to the dimensions calculated above as a \"sanity\" check.\n\n\n\n::: {.cell tbl-cap='Pivoted Example'}\n\n```{.r .cell-code}\neggs_longer<- eggs_data%>%\n  pivot_longer(cols=contains(\"large\"),\n               names_to = c(\"size\", \"quantity\"),\n               names_sep=\"_\",\n               values_to = \"amount\"\n  )\neggs_longer\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 480 × 5\n   month     year size  quantity amount\n   <chr>    <int> <chr> <chr>     <dbl>\n 1 January   2004 large half       126 \n 2 January   2004 large dozen      230 \n 3 January   2004 extra large      132 \n 4 January   2004 extra large      230 \n 5 February  2004 large half       128.\n 6 February  2004 large dozen      226.\n 7 February  2004 extra large      134.\n 8 February  2004 extra large      230 \n 9 March     2004 large half       131 \n10 March     2004 large dozen      225 \n# … with 470 more rows\n```\n:::\n\n```{.r .cell-code}\n#number of rows\nnrow(eggs_longer)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 480\n```\n:::\n\n```{.r .cell-code}\n#number of cols\nncol(eggs_longer)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5\n```\n:::\n:::\n\n\n\n### Challenge: Pivot the Chosen Data\n\nDocument your work here. What will a new \"case\" be once you have pivoted the data? How does it meet requirements for tidy data?\n\nAs expected, I now have one less column and four times as many rows (120 became 480). (6 became 5). I now have one observation for each row and am prepared to start my analysis. Depending on the nature of my study or if there are more tables to put in at some time, I might want to change the cents into dollars. The data keeps the precise decimals even when the preview tibble below rounds to whole cents.\n\n::: {.cell}\n\n```{.r .cell-code}\neggs_price <- mutate(eggs_longer, \n       avg_USD = amount / 100\n       )%>%\n  select(!contains (\"amount\"))\neggs_price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 480 × 5\n   month     year size  quantity avg_USD\n   <chr>    <int> <chr> <chr>      <dbl>\n 1 January   2004 large half        1.26\n 2 January   2004 large dozen       2.3 \n 3 January   2004 extra large       1.32\n 4 January   2004 extra large       2.3 \n 5 February  2004 large half        1.28\n 6 February  2004 large dozen       2.26\n 7 February  2004 extra large       1.34\n 8 February  2004 extra large       2.3 \n 9 March     2004 large half        1.31\n10 March     2004 large dozen       2.25\n# … with 470 more rows\n```\n:::\n:::\n\n\nAny additional comments?\n",
    "supporting": [
      "challenge3_snammarakaly_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}