{
  "hash": "4035d8057d5b4caba75029c6deb175f6",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Solutions\"\nauthor: \"Vinitha Maheswaran\"\ndesription: \"Reading in data and creating a post\"\ndate: \"10/11/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - railroads\n  - faostat\n  - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nFor this challenge I am reading the \"wild_bird_data\" data set. Since the wild_bird_data.xlsx data set is in Excel format, I am using the 'readxl' package for reading the data. After reading the data is stored in a dataframe \"bird_data\". The data in the first row of the dataframe seems like column names rather than numerical values as seen in the remaining rows. I resolve this issue by skipping the first row while reading the data set and storing in dataframe. Now, if I print the dataframe, I can see both the variables have only numerical values of double-precision floating-point format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages('readxl')\nlibrary(readxl)\n\n# Reading the wild_bird_data.xlsx data set and storing in a data frame\nbird_data <- read_excel(\"_data/wild_bird_data.xlsx\", skip=1)\nprint(bird_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 146 × 2\n   `Wet body weight [g]` `Population size`\n                   <dbl>             <dbl>\n 1                  5.46           532194.\n 2                  7.76          3165107.\n 3                  8.64          2592997.\n 4                 10.7           3524193.\n 5                  7.42           389806.\n 6                  9.12           604766.\n 7                  8.04           192361.\n 8                  8.70           250452.\n 9                  8.89            16997.\n10                  9.52              595.\n# … with 136 more rows\n```\n:::\n:::\n\n\n## Describe the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Finding dimension of the data set\ndim(bird_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 146   2\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Finding column names\ncolnames(bird_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Wet body weight [g]\" \"Population size\"    \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Structure of bird_data\nstr(bird_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [146 × 2] (S3: tbl_df/tbl/data.frame)\n $ Wet body weight [g]: num [1:146] 5.46 7.76 8.64 10.69 7.42 ...\n $ Population size    : num [1:146] 532194 3165107 2592997 3524193 389806 ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Summary of bird_data\nsummary(bird_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Wet body weight [g] Population size  \n Min.   :   5.459    Min.   :      5  \n 1st Qu.:  18.620    1st Qu.:   1821  \n Median :  69.232    Median :  24353  \n Mean   : 363.694    Mean   : 382874  \n 3rd Qu.: 309.826    3rd Qu.: 198515  \n Max.   :9639.845    Max.   :5093378  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check for missing/null data in the bird_data\nsum(is.na(bird_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.null(bird_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Arranging the bird_data in descending order of wet body weight\narrange(bird_data,desc(`Wet body weight [g]`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 146 × 2\n   `Wet body weight [g]` `Population size`\n                   <dbl>             <dbl>\n 1                 9640.            3417. \n 2                 4451.            4789. \n 3                 4224.             433. \n 4                 2320.             151. \n 5                 2054.           20661. \n 6                 1368.            9797. \n 7                 1138.              53.9\n 8                 1106.            3975. \n 9                 1064.             107. \n10                 1042.            1759. \n# … with 136 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Frequency tables for the variables in bird_data\ntable(bird_data$`Wet body weight [g]`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n5.45887180052624 7.41722577905587 7.76456810683605 8.03684333000353 \n               1                1                1                1 \n8.63858738018464 8.70473119796067 8.89032317828959  9.1169347252776 \n               1                1                1                1 \n9.51590845877281 10.0837373583453 10.4227948279533 10.6897349302105 \n               1                1                1                1 \n10.9430490453536 11.0657951888437 11.3325639394677 11.7501765156051 \n               1                1                1                1 \n11.8338885705264  11.911899237195  12.073867120209 12.9107556641051 \n               1                1                1                1 \n13.4190149139047 13.7066181013302 14.5348410462378 14.9327931173702 \n               1                1                1                1 \n 15.250338580451 15.4756001614342 15.5437260853068  16.173314711739 \n               1                1                1                1 \n16.3353638573666  16.713625723242 16.7374033065426 16.8480457069965 \n               1                1                1                1 \n16.9541655530351 17.7715823185348 18.4587461659311 18.4717033015697 \n               1                1                1                1 \n18.5902522391181 18.7105850428847 18.7218421193228 19.1013268966518 \n               1                1                1                1 \n19.3930121740443  19.492233639612 20.4175008347481  20.556216729787 \n               1                1                1                1 \n21.2700694334402 22.2677519174593 22.3057316395665 22.4321177480063 \n               1                1                1                1 \n 22.689316708056 22.7960529394349 23.9762697808197 24.4422047589553 \n               1                1                1                1 \n25.2824793404366 27.1737255667256 27.6790862634083 27.8958488030849 \n               1                1                1                1 \n28.6687569833571 32.2163205913993 33.6261656866144 35.1758377124708 \n               1                1                1                1 \n35.4203082644676 36.9646386454904 37.5910580962782 39.0641452782309 \n               1                1                1                1 \n42.8545510609481 43.1315511306876 44.8797938229394 47.9477535298889 \n               1                1                1                1 \n49.9139486401791  52.312838051431   64.74167603758 66.4645646879698 \n               1                1                1                1 \n67.0724165442755 71.3921665737811 72.4618812159043 79.3893544290883 \n               1                1                1                1 \n82.8877457373263 95.6625004989711 102.577037919272 103.351145634621 \n               1                1                1                1 \n105.251145466066  105.27800534013 110.993242131064 114.163158354383 \n               1                1                1                1 \n116.289475709079 128.395335803439 128.575653541364 135.486491343145 \n               1                1                1                1 \n138.513955740119 163.276223677476 173.454892979421 175.840624652506 \n               1                1                1                1 \n194.303351756182 212.147017049613 221.693442317827 226.218006871375 \n               1                1                1                1 \n232.254993447017  240.78960679855 251.746484961854 251.762544720258 \n               1                1                1                1 \n255.963705031502  263.89604533577 265.463867650509 275.131029910782 \n               1                1                1                1 \n282.288057014247 287.527400278505 293.799587810237 301.332380779176 \n               1                1                1                1 \n303.545552195872 311.918910823616 345.112605430166 352.281226176494 \n               1                1                1                1 \n371.889868196688 380.296824961942 393.854923117015 394.224786249175 \n               1                1                1                1 \n428.549354432903 462.782070038066 479.722220970486 480.965400920035 \n               1                1                1                1 \n486.856962904678 527.513423559442 530.357342971806 603.577402390915 \n               1                1                1                1 \n645.449083461034 672.284528540897 684.506509216141 757.205197645473 \n               1                1                1                1 \n765.921951081732 798.020716987072 820.520151625127  887.34848570896 \n               1                1                1                1 \n923.172177028805 954.839393219695 1003.03939853867 1008.19886351951 \n               1                1                1                1 \n1042.06074444654 1064.32682601983 1106.07510035687 1137.96479906865 \n               1                1                1                1 \n1368.36501582366 2053.74863827143 2320.09569921356 4223.72945322751 \n               1                1                1                1 \n4450.50815600577 9639.84540069595 \n               1                1 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Frequency tables for the variables in bird_data\ntable(bird_data$`Population size`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n4.91634835467142 6.70868864239466 8.73586159709388 9.31902770511663 \n               1                1                1                1 \n15.2869871955882 15.4655672951415 22.3522084608936  30.127933260934 \n               1                1                1                1 \n53.9362035620238 59.0620904204364 59.6194023648399 60.4991412161533 \n               1                1                1                1 \n72.5770178814215 90.9054052719037 106.902249798449 149.890268699652 \n               1                1                1                1 \n151.097182999144 208.885343731786 253.181014123717 281.556308988712 \n               1                1                1                1 \n291.178964028914 385.727617599983 397.264219914397 433.148027881688 \n               1                1                1                1 \n452.038679090149 495.841172633925 544.171979070565 592.145764114067 \n               1                1                1                1 \n592.580758810679  595.09393677964 612.028409808944 628.023224840693 \n               1                1                1                1 \n792.971565300218 864.665387886239 907.937967876158 1162.33256269623 \n               1                1                1                1 \n1758.76989729032 2007.50380975505 2237.33222320424 3069.67346119425 \n               1                1                1                1 \n3417.07357811317 3974.59483110465 4110.35378650503 4111.78379795295 \n               1                1                1                1 \n4165.60888930286 4203.61578270669 4380.25359020738 4596.79968789988 \n               1                1                1                1 \n 4775.8178179398 4788.66353161336 5210.62705096944 5352.59147293765 \n               1                1                1                1 \n7080.77132481909 8449.49796848251 8621.86411771869 9240.89055513834 \n               1                1                1                1 \n9360.77252455304 9797.18806953683 10196.0549227289 10942.0508967534 \n               1                1                1                1 \n12423.3328081174 12525.5435856356 13390.6423878795 15151.7816516081 \n               1                1                1                1 \n15173.7578211317 16997.4156415239 17889.1504645705 20287.3606591725 \n               1                1                1                1 \n 20660.849081157 21007.4914234587 21110.8595100455 21761.5934166234 \n               1                1                1                1 \n23056.4777079282 25649.9515609322 25686.6579025093 25700.0638322942 \n               1                1                1                1 \n30378.3213430714 30656.0846698027 30829.5599923666  32206.460433963 \n               1                1                1                1 \n34547.4925608766 36108.5800741424  38141.260546798 40057.7978966742 \n               1                1                1                1 \n40510.0866666354  48588.014888741 49948.4692178362 54219.7070863559 \n               1                1                1                1 \n57460.3862091927 62266.8051981741 70377.2193951022 73944.9926361407 \n               1                1                1                1 \n74386.4256983317 76836.5900893805 77389.4460799703 81067.9439550841 \n               1                1                1                1 \n86286.0274600145 90663.8017792314 98289.3823961815 102770.468623667 \n               1                1                1                1 \n131929.739792131 143593.859644388 143943.923703849 153007.935788715 \n               1                1                1                1 \n 164390.10921714 192360.511579436 194871.065036599 195278.198371782 \n               1                1                1                1 \n195591.665828951 199489.109295523 250452.449623033 259613.414523361 \n               1                1                1                1 \n272074.336929843 279260.298751568 282801.151970821 283748.186271429 \n               1                1                1                1 \n323395.683066309 331552.480261483 369717.294242925 386610.335143534 \n               1                1                1                1 \n389806.168891807  405284.31744811 413176.502290094 471555.281780475 \n               1                1                1                1 \n472595.269474694 532194.395145161  604765.97978904 642164.626619563 \n               1                1                1                1 \n801278.748155215 815305.139691342 850796.834759033 907294.021838339 \n               1                1                1                1 \n1217093.59903949  1533110.9951272 1546053.00700726 2020904.68541013 \n               1                1                1                1 \n2055446.33281584  2503916.1239288 2592996.86778979 3165107.44544653 \n               1                1                1                1 \n3507479.42637697  3524193.2266336 4131320.19597057 4262042.03813322 \n               1                1                1                1 \n4812996.90520353 5093377.94709106 \n               1                1 \n```\n:::\n:::\n\n\nThe \"wild_bird_data\".xlsx data set is likely gathered from the first figure in a research paper authored by Nee et al as mentioned in the first row of the Excel data before removing it. The \"wild_bird_data\".xlsx data set contains 146 observations (rows) and 2 variables (columns). The data set has 2 variables - Wet boday weight [g] and Population size. Both the variables have only numerical values of double-precision floating-point format. The data set represents the average wet body weight in grams and the size of the population for different species of wild birds. This data may be used to estimate the biomass of wild birds. The data set does not have any missing values or null values. The minimum, maximum, mean and median values for the Wet body weight variable are 5.459 [g], 9639.845 [g], 363.694 [g], and 69.232[g] respectively. The minimum, maximum, mean and median values for the Population size variable are 5, 5093378, 82874, and 24353 respectively.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}