{
  "hash": "c8943a2c25f79327d4b6d5925f3403e7",
  "result": {
    "markdown": "---\ntitle: \"Challenge 6 Instructions\"\nauthor: \"Erika Nagai\"\ndescription: \"Visualizing Time and Relationships\"\ndate: \"10/23/2022\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_6\n  - bechdel_test\n  - movies\n  - Female_Representation\n  - Erika_Nagai\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(rjson)\nlibrary(jsonlite)\nlibrary(summarytools)\nlibrary(ggridges)\nlibrary(grid)\n\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  mutate variables as needed (including sanity checks)\n4)  create at least one graph including time (evolution)\n   - try to make them \"publication\" ready (optional)\n   - Explain why you choose the specific graph type\n5)  Create at least one graph depicting part-whole or flow relationships\n   - try to make them \"publication\" ready (optional)\n   - Explain why you choose the specific graph type\n\n\n\nThis week, I chosed to analyze data about female representation in movies, specifically focusing on Bechdel test.\nAccording to \"Merriam-Webster\", Bechdel test is \"a set of criteria used as a test to evaluate a work of fiction (such as a film) on the basis of its inclusion and representation of female characters\" (<https://www.merriam-webster.com/dictionary/Bechdel%20Test>)\n\n\nIt usually includes \n1)  At least two women are featured\n2)  These women talk to each other\n3)  They discuss something other than a man\n\nI used two datasets.\n\n1)  `imdb_df`: The reviews information taken from IMDb (Internet Movie Database) <https://www.imdb.com/interfaces/>\n2)  `bechdel_df`: <https://bechdeltest.com/api/v1/doc>\n\n\n### Read in data\n\n**`bechdel_df`**\n\nThis data is extracted from `bechdeltest` API, so I used `jsonlite`'s `read_json` function.\nThe values in `imdbid` are missing \"tt\" in the beginning and don't match with the original imdb id so I made a new column `new_imdbid`that concatnate \"tt\" and the value of `imdbid`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# json_file <- \"http://bechdeltest.com/api/v1/getAllMovies\"\n# bechdel_df <- read_json(path = json_file, simplifyVector = TRUE)\n# bechdel_df$titleId <- paste(\"tt\",bechdel_df$imdbid, sep = \"\")\n# \n# \n# head(bechdel_df)\n```\n:::\n\n\n**`imdb_rating`**\n\nI downloaded the tsv file compressed in a gz file from this website. <https://www.imdb.com/interfaces/>\nFirst, I decompressed the gz file by `R.usills::gunzip` function, and then read in the tsv file.\n\nI do NOT read in the original tsv file in this R Quarto because it is huge and it may cause issues.\nHowever, if you want to see what I did to read in the tsv file, you can refer to the below coding.\n\n::: {.cell}\n\n```{.r .cell-code}\n# I ran the below code to read in a huge gz file. I didn't include this in this quarto file because it doesn't allow me to submit a huge data file and it will cause errors.\n\n\n# R.utils::gunzip(\"title.ratings.tsv.gz\")\n# imdb_rating <- read.delim(file = \"title.ratings.tsv\", sep = \"\\t\")\n# \n# write.csv(imdb_rating, \"imdb_rating.csv\")\n\n#imdb_rating <- read_csv()\n\n# colnames(imdb_rating)[1] <- \"titleId\"\n# imdb_rating\n```\n:::\n\n\nThen I joined `bechdel_df` and `imdb_rating` using `titleId` and named the new dataset as `bechdel_imdb`\nAgain, you can see the below code to see how I joined two datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bechdel_imdb <- left_join(bechdel_df, imdb_rating, by=\"titleId\" )\n# \n# write.csv(bechdel_imdb, \"~/DACSS/601/601_Fall_2022/posts/_data/bechdel_imdb.csv\")\nbechdel_imdb <- read_csv(\"~/DACSS/601/601_Fall_2022/posts/_data/bechdel_imdb.csv\")\nbechdel_imdb\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 9,802 × 9\n    ...1 title                 rating  year    id imdbid titleId avera…¹ numVo…²\n   <dbl> <chr>                  <dbl> <dbl> <dbl> <chr>  <chr>     <dbl>   <dbl>\n 1     1 inazuma eleven: the …      3  1010 10556 17947… tt1794…     6.8     284\n 2     2 Passage de Venus           0  1874  9602 31557… tt3155…     6.9    1729\n 3     3 La Rosace Magique          0  1877  9804 14495… tt1449…     6       150\n 4     4 Sallie Gardner at a …      0  1878  9603 22214… tt2221…     7.4    3101\n 5     5 Le singe musicien          0  1878  9806 12592… tt1259…     6.2     258\n 6     6 Athlete Swinging a P…      0  1881  9816 78164… tt7816…     5.2     466\n 7     7 Buffalo Running            0  1883  9831 54597… tt5459…     6.3    1029\n 8     8 L&#39;homme machine        0  1885  9832 85883… tt8588…     5.3     398\n 9     9 Man Walking Around t…      0  1887  9614 20752… tt2075…     5.2    1411\n10    10 Cockatoo Flying            0  1887  9836 81331… tt8133…     5.3     207\n# … with 9,792 more rows, and abbreviated variable names ¹​averageRating,\n#   ²​numVotes\n```\n:::\n:::\n\n\n### Describe the dataset\n\nAs mentioned, `bechdel_imdb` dataset is made of two different data, (1) Reviews on movies from IMDb (2) Rating of Bechdel test of movies.\nThis data set contains 9802 rows and 8 columns. Each row represents a movie and the below information about each movie is contained:\n\n* year: a year when movie was released\n* id: Bechdeltest.com unique id\n* rating: Bechdel test rating (0 means no two women, 1 = no talking between women, 2 = talking about a man, 3 means it passes the test)\n* title: Title of movies\n* imdbid: IMDb unique id \n* titleId: IMDb unique id with \"tt\" in the beginning (this column was used as foreign key when joining the datasets)\n* average rating: weighted average of all the individual user ratings from IMDb\n* numVotes: number of votes the title has received\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(bechdel_imdb),\n      varnumbers = FALSE,\n      plain.ascii  = FALSE,\n      style        = \"grid\",\n      graph.magnif = 0.80,\n      valid.col    = FALSE,\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>bechdel_imdb</h4>\n<strong>Dimensions</strong>: 9802 x 9\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">...1\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 4901.5 (2829.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 4901.5 &le; 9802</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 4900.5 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">9802 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkIt0j1yAAAAGFJREFUaN7t2bENgDAMRcGs4BGADfj774YiUVCBIDSR7jUuIl1vpzV9aR1uqaoT25I9yc14eA4MBoPBYDAYDAabAuu7wG9YHzAYDAaDwWAwGAwGg8FgsBmw8Q/my2FJ7zoAQOcyiNUZQgYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMTU6NTc6MDgrMDA6MDBAx4xYAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDE1OjU3OjA4KzAwOjAwMZo05AAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">title\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Cinderella</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Dracula</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Little Women</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Pride and Prejudice</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Robin Hood</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Shelter</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. A Star Is Born</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Alice in Wonderland</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Anna Karenina</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Annie</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 9547 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9765</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">99.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAKIAAAEKBAMAAABj5JMfAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkJwE/FXgAAAJ5JREFUeNrt1bENg1AUBEFacAlndwD990bijJAT+k/MFjDpbpta5VOLSCQSicSL2APfLYZIJBKJRL8uiyESiUQicZTYAyeJIRKJRCJxlNgDJ4khEolEItFdlxdDJBKJRKJfLy+GSCQSiUS/LoshEolEInGU2AMniSESiUQicZTYAyeJIRKJRCLRXZcXv73+4u9otROJRCLxYbF/Bd3vBGMMzhJcUFjBAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDE1OjU3OjA5KzAwOjAw5rCH7AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQxNTo1NzowOSswMDowMJftP1AAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">rating\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.1 (1.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 3 &le; 3</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1084</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">11.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2124</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">21.7%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1000</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">5594</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">57.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGIAAABmBAMAAADCGlkrAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkJwE/FXgAAAGtJREFUWMPt1bENACEIQFFXcAS5DXT/3a44bC4xQCWa/2teIQmxlHsSrVUzFc/4QiAQp4j4nduDO4T8aqaYuxr2zhAIRAoRv/PqL7WYL/YL3W5HIBCniPidOyY3CPG3+A3WdQQCkULE7/yGXqfc0WzMeLCZAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDE1OjU3OjA5KzAwOjAw5rCH7AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQxNTo1NzowOSswMDowMJftP1AAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1996.2 (27)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1010 &le; 2006 &le; 2022</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 25 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">142 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkJwE/FXgAAAGJJREFUaN7t2bERgDAMBEG1ACWYDnD/vVmGiCEzCgj2Ctj85yO00va5lpVhR+8nDAaDwWAwGAwGg8FguTXrsJRgMBgMBoPBYDAY7AfYfm+dIqxfEgz2aJ63ZdgkXlgrKbTSAM/TI+AyRzxvAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDE1OjU3OjA5KzAwOjAw5rCH7AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQxNTo1NzowOSswMDowMJftP1AAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">id\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 5224.9 (3052.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 5211.5 &le; 10641</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 5233.5 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">9802 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkJwE/FXgAAAJtJREFUaN7t1rENgCAQhWFWgA2EDWT/3YxAcUQIeNIQ/1dc8SSfGCg0hmhiU5xPsdrUWLxzZvJYg6UZJebm/EksVyOyYHmZH2Dh8aCJBcFUmBNvKZjvHtMQk1UQ83yFNb5cj3WrP2LV1fuKVVdPj+U9LcJkBQYGBgYGBga2DVb+f9dgpQIDAwMDAwMDAwMDAwMDAwPbHPNLYogmF+FjEj/20ec2AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDE1OjU3OjA5KzAwOjAw5rCH7AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQxNTo1NzowOSswMDowMJftP1AAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">imdbid\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 0035279</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 0086425</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 0117056</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 2043900</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 2457282</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 0000001</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 0000002</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 0000003</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 0000004</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 0000005</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 9784 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9784</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">99.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAKIAAAEKBAMAAABj5JMfAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkKWUaU5AAAAJ5JREFUeNrt1bENg1AUBEFacAlndwD990bijJAT+k/MFjDpbpta5VOLSCQSicSL2APfLYZIJBKJRL8uiyESiUQicZTYAyeJIRKJRCJxlNgDJ4khEolEItFdlxdDJBKJRKJfLy+GSCQSiUS/LoshEolEInGU2AMniSESiUQicZTYAyeJIRKJRCLRXZcXv73+4u9otROJRCLxYbF/Bd3vBGMMzhJcUFjBAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDE1OjU3OjEwKzAwOjAwv4LCoQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQxNTo1NzoxMCswMDowMM7feh0AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">3\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">titleId\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. tt</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. tt0035279</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. tt0086425</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. tt0117056</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. tt2043900</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. tt2457282</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. tt0000001</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. tt0000002</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. tt0000003</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. tt0000004</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 9785 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9785</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">99.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAKIAAAEKBAMAAABj5JMfAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkKWUaU5AAAAJ5JREFUeNrt1bENg1AUBEFacAlndwD990bijJAT+k/MFjDpbpta5VOLSCQSicSL2APfLYZIJBKJRL8uiyESiUQicZTYAyeJIRKJRCJxlNgDJ4khEolEItFdlxdDJBKJRKJfLy+GSCQSiUS/LoshEolEInGU2AMniSESiUQicZTYAyeJIRKJRCLRXZcXv73+4u9otROJRCLxYbF/Bd3vBGMMzhJcUFjBAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDE1OjU3OjEwKzAwOjAwv4LCoQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQxNTo1NzoxMCswMDowMM7feh0AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">averageRating\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 6.6 (1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1.2 &le; 6.7 &le; 9.4</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1.3 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">81 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkKWUaU5AAAAK1JREFUaN7t1lEKgCAQRVG3UDvIdpD731saBZNNko5QxH3gV3F6iOQ4R1oy1MTHTNqDFmwOIYCB3WDqWavFEpIwtV0tdkBgYGBgYGBgYGBNmJzNzJiEwD6AXcZ3C3ZpBwYGBgb2EWzMb3MTFhQIDAwM7GXsNNdasVO7B9j2l+2GxfcXsB9gx7Hog+3QjzG5X3ZMQCYsb2XDMqiIpQ97BdsaKa2KWFqLwHyXONKSFarhy5CQc7SGAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDE1OjU3OjEwKzAwOjAwv4LCoQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQxNTo1NzoxMCswMDowMM7feh0AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">47\n(0.5%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">numVotes\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 80886.1 (168621.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5 &le; 20558 &le; 2673050</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 77543 (2.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">8833 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5gwWDzkKWUaU5AAAAF5JREFUaN7t2cEJgDAQRNFtwRJMSrD/3lTIIeAtE/DyfgGPhTlulVZqb+cRNrB+PcFgMBgMBoPBYDAYDAaDwWAwGAwGg8FgsH+w+Ps3Y/F5sA1YMukHS8SBtS2VVroBY2EnhZsXjBUAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMTU6NTc6MTArMDA6MDC/gsKhAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDE1OjU3OjEwKzAwOjAwzt96HQAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">47\n(0.5%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-12-22</p>\n</div>\n```\n:::\n:::\n\n\n## Tidy data\n\nThere are three different id columns \"id\", \"imdbid\", and \"titleId\".\nOnly one ID column will be enough so I decided to delete \"id\" and \"imdbid\".\n\nAlso the column \"...1\" is not necessary because this colums only shows the row number, thus I removed the column \"...1\" as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbechdel_imdb <- bechdel_imdb %>% select(-c(id, imdbid, ...1))\ncolnames(bechdel_imdb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"title\"         \"rating\"        \"year\"          \"titleId\"      \n[5] \"averageRating\" \"numVotes\"     \n```\n:::\n:::\n\n\nAlso I changed the name of columns to make them easier to understand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(bechdel_imdb) <- c(\"title\", \"rating\", \"year\", \"titleId\", \"averageRating\", \"numVotes\")\nbechdel_imdb\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 9,802 × 6\n   title                         rating  year titleId    averageRating numVotes\n   <chr>                          <dbl> <dbl> <chr>              <dbl>    <dbl>\n 1 inazuma eleven: the movie          3  1010 tt1794796            6.8      284\n 2 Passage de Venus                   0  1874 tt3155794            6.9     1729\n 3 La Rosace Magique                  0  1877 tt14495706           6        150\n 4 Sallie Gardner at a Gallop         0  1878 tt2221420            7.4     3101\n 5 Le singe musicien                  0  1878 tt12592084           6.2      258\n 6 Athlete Swinging a Pick            0  1881 tt7816420            5.2      466\n 7 Buffalo Running                    0  1883 tt5459794            6.3     1029\n 8 L&#39;homme machine                0  1885 tt8588366            5.3      398\n 9 Man Walking Around the Corner      0  1887 tt2075247            5.2     1411\n10 Cockatoo Flying                    0  1887 tt8133192            5.3      207\n# … with 9,792 more rows\n```\n:::\n:::\n\n\nI realized that the released year of \"inazuma eleven: the movie\" is 1010, which doesn't seem correct. According to the information on the internet, this movie was released in 2010, so I manually corrected this information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbechdel_imdb$year[bechdel_imdb$year==1010] <- 2010\n```\n:::\n\n\n\n\nAfter cleaning the data, the data contains the following information:\n *  year: a year when movie was released\n *  id: Bechdeltest.com unique id\n *  rating: Bechdel test rating (0 means no two women, 1 = no talking between women, 2 = talking about a man, 3 means it passes the test)\n *  title: Title of movies\n *  imdbid: IMDb unique id \n *  titleId: IMDb unique id with \"tt\" in the beginning (this column was added to join two datasets)Ha\n *  average rating: weighted average of all the individual user ratings from IMDb\n *  numVotes: number of votes the title has received\n\n\n## Visualization \n\nBefore analyzing the data, please note that not all movies have the Bechdel test available on http://bechdeltest.com.\nI'm able to analyze only the movies that have the Bechdel test rating available and the number of these movies is as follows.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvis <- bechdel_imdb %>%\n  group_by(year) %>%\n  summarize(\n    Total_number_of_movie = n()\n  )\n\nggplot(vis, aes(x=year, y=Total_number_of_movie)) + \n  geom_line() +\n  labs(title = \"The number of movies that have Bechdel test rating available\")\n```\n\n::: {.cell-output-display}\n![](challenge6_ErikaNagai_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n**1: Has female representation in movies improved over time?** \n\nIt seems like the number of movies that pass the Bechdel test is increasing however we cannot see if it's true because the total number of movies is also increasing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbechdel_imdb$rating <- as.factor(bechdel_imdb$rating)\nvis1 <- bechdel_imdb %>% group_by(year, rating) %>%\n  dplyr::summarize(count = n())\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vis1, aes(x = year, y = count, fill = rating))+\n  geom_area()+\n  labs(title=\"Number of movies by Bechdel test rating\", y = \"Number of movies\", x = \"Year\") +\n  scale_fill_discrete(name = \"Bechdel Test Rating\", labels = c(\"0: No two women\", \"1: No women talking each other\", \"2: Talking about a man\", \"3: Passes the test\"))\n```\n\n::: {.cell-output-display}\n![](challenge6_ErikaNagai_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nI created the graph of proportion of Bechdel Rating instead of number.\nThis graph shows that the % of movies that pass the Bechdel test is constantly increasing since around 1970.\nCurrently, over 70% of the released movies passes the Bechdel test.\nEven though most movies feature more than one female, however around 25% of movies still do NOT show two females talking each other.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vis1, aes(x = year, y = count, fill = rating))+\n  geom_area(position = \"fill\")+\n  labs(title=\"% of movies by Bechdel test rating\", y = \"Number of movies\", x = \"Year\") +\n  scale_y_continuous(labels = scales::percent)+\n  scale_fill_discrete(name = \"Bechdel Test Rating\", labels = c(\"0: No two women\", \"1: No women talking each other\", \"2: Talking about a man\", \"3: Passes the test\")) +\n  annotate(\"segment\", x =1970, xend = 2000, y = 0.35, yend = 0.50, colour = \"black\", arrow = arrow())\n```\n\n::: {.cell-output-display}\n![](challenge6_ErikaNagai_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nSince there is only a small number of rated movies before 1950, the percentage graph does not appear smooth.\nI decided to focus on the movies released in 1950 or after.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vis1 %>% filter(year >= 1950), aes(x = year, y = count, fill = rating))+\n  geom_area(position = \"fill\")+\n  labs(title=\"% of movies by Bechdel test rating\", y = \"Number of movies\", x = \"Year\") +\n  scale_y_continuous(labels = scales::percent)+\n  scale_fill_discrete(name = \"Bechdel Test Rating\", labels = c(\"0: No two women\", \"1: No women talking each other\", \"2: Talking about a man\", \"3: Passes the test\"))+\n  annotate(\"segment\", x =1970, xend = 2000, y = 0.35, yend = 0.50, colour = \"black\", arrow = arrow())\n```\n\n::: {.cell-output-display}\n![](challenge6_ErikaNagai_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n**2: Are movies in which women are represented more popular?**\n\nIf people value female representation in movies, the movies that have a better rating of Bechdel test will score higher on the reviews.\nHowever, the below graph doesn't show such trend clearly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(bechdel_imdb %>% filter(year >= 1950), aes(x=year, y=averageRating)) + \n  geom_point(aes(colour=factor(rating))) +\n  xlab(\"Year\") +\n  ylab(\"IBDm Review Score\") +\n  scale_color_discrete(name = \"Bechdel Test Rating\", labels = c(\"0: No two women\", \"1: No women talking each other\", \"2: Talking about a man\", \"3: Passes the test\"))\n```\n\n::: {.cell-output-display}\n![](challenge6_ErikaNagai_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nI created a facet graph to see the trend more clearly, however, it seems that the rating of Bechdel test doesn't affect the review rating.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(bechdel_imdb %>% filter(year >= 1950), aes(x=year, y=averageRating)) + \n  geom_point() +\n  xlab(\"Year\") +\n  labs(title = \"IMDb review rating by bechdel test rating\")+\n  ylab(\"IBDm Review Score\") +\n  scale_color_discrete(name = \"Bechdel Test Rating\", labels = c(\"0: No two women\", \"1: No women talking each other\", \"2: Talking about a man\", \"3: Passes the test\")) +\n  \n  \n  facet_wrap(vars(factor(rating)))\n```\n\n::: {.cell-output-display}\n![](challenge6_ErikaNagai_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n# Violin plot or line of average \n\n\nFor further study, I would like to find out:\n1)  The trend of the number of proportion of the movies that pass Bechdel Test in different regions (Europe, Asia, Middle East, etc)\n2)  Whether or not a movie passes the Bechdel Test affects the movie's success (audience and expert reviews, revenue)?\n",
    "supporting": [
      "challenge6_ErikaNagai_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}