{
  "hash": "b35b6b76b98ce65c266f34894f3b1035",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Vinitha Maheswaran\"\ndate: \"12/10/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Olympics\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n## Read in data\n\n\nFor this homework I will be working with the 120 years of Olympic history: athletes and results dataset. The Olympics data has two csv files - \"athlete_events.csv\" and \"noc_regions.csv\". This historical dataset contains information on the modern Olympic Games, including all the Games from Athens 1896 to Rio 2016. This data was scraped from www.sports-reference.com in May 2018 and is available on Kaggle. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reading the \"athlete_events.csv\" and \"noc_regions.csv\" files\n\nathlete_data <- read_csv(\"_data/athlete_events.csv\")\nnoc_data <- read_csv(\"_data/noc_regions.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Displaying athlete_data dataset\n\nathlete_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 271,116 × 15\n      ID Name     Sex     Age Height Weight Team  NOC   Games  Year Season City \n   <dbl> <chr>    <chr> <dbl>  <dbl>  <dbl> <chr> <chr> <chr> <dbl> <chr>  <chr>\n 1     1 A Dijia… M        24    180     80 China CHN   1992…  1992 Summer Barc…\n 2     2 A Lamusi M        23    170     60 China CHN   2012…  2012 Summer Lond…\n 3     3 Gunnar … M        24     NA     NA Denm… DEN   1920…  1920 Summer Antw…\n 4     4 Edgar L… M        34     NA     NA Denm… DEN   1900…  1900 Summer Paris\n 5     5 Christi… F        21    185     82 Neth… NED   1988…  1988 Winter Calg…\n 6     5 Christi… F        21    185     82 Neth… NED   1988…  1988 Winter Calg…\n 7     5 Christi… F        25    185     82 Neth… NED   1992…  1992 Winter Albe…\n 8     5 Christi… F        25    185     82 Neth… NED   1992…  1992 Winter Albe…\n 9     5 Christi… F        27    185     82 Neth… NED   1994…  1994 Winter Lill…\n10     5 Christi… F        27    185     82 Neth… NED   1994…  1994 Winter Lill…\n# … with 271,106 more rows, and 3 more variables: Sport <chr>, Event <chr>,\n#   Medal <chr>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Displaying noc_data dataset\n\nnoc_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 230 × 3\n   NOC   region      notes               \n   <chr> <chr>       <chr>               \n 1 AFG   Afghanistan <NA>                \n 2 AHO   Curacao     Netherlands Antilles\n 3 ALB   Albania     <NA>                \n 4 ALG   Algeria     <NA>                \n 5 AND   Andorra     <NA>                \n 6 ANG   Angola      <NA>                \n 7 ANT   Antigua     Antigua and Barbuda \n 8 ANZ   Australia   Australasia         \n 9 ARG   Argentina   <NA>                \n10 ARM   Armenia     <NA>                \n# … with 220 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding dimension of both datasets\n\ndim(athlete_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 271116     15\n```\n:::\n\n```{.r .cell-code}\ndim(noc_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 230   3\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Structure of athlete_data dataset\n\nstr(athlete_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspec_tbl_df [271,116 × 15] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ ID    : num [1:271116] 1 2 3 4 5 5 5 5 5 5 ...\n $ Name  : chr [1:271116] \"A Dijiang\" \"A Lamusi\" \"Gunnar Nielsen Aaby\" \"Edgar Lindenau Aabye\" ...\n $ Sex   : chr [1:271116] \"M\" \"M\" \"M\" \"M\" ...\n $ Age   : num [1:271116] 24 23 24 34 21 21 25 25 27 27 ...\n $ Height: num [1:271116] 180 170 NA NA 185 185 185 185 185 185 ...\n $ Weight: num [1:271116] 80 60 NA NA 82 82 82 82 82 82 ...\n $ Team  : chr [1:271116] \"China\" \"China\" \"Denmark\" \"Denmark/Sweden\" ...\n $ NOC   : chr [1:271116] \"CHN\" \"CHN\" \"DEN\" \"DEN\" ...\n $ Games : chr [1:271116] \"1992 Summer\" \"2012 Summer\" \"1920 Summer\" \"1900 Summer\" ...\n $ Year  : num [1:271116] 1992 2012 1920 1900 1988 ...\n $ Season: chr [1:271116] \"Summer\" \"Summer\" \"Summer\" \"Summer\" ...\n $ City  : chr [1:271116] \"Barcelona\" \"London\" \"Antwerpen\" \"Paris\" ...\n $ Sport : chr [1:271116] \"Basketball\" \"Judo\" \"Football\" \"Tug-Of-War\" ...\n $ Event : chr [1:271116] \"Basketball Men's Basketball\" \"Judo Men's Extra-Lightweight\" \"Football Men's Football\" \"Tug-Of-War Men's Tug-Of-War\" ...\n $ Medal : chr [1:271116] NA NA NA \"Gold\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   ID = col_double(),\n  ..   Name = col_character(),\n  ..   Sex = col_character(),\n  ..   Age = col_double(),\n  ..   Height = col_double(),\n  ..   Weight = col_double(),\n  ..   Team = col_character(),\n  ..   NOC = col_character(),\n  ..   Games = col_character(),\n  ..   Year = col_double(),\n  ..   Season = col_character(),\n  ..   City = col_character(),\n  ..   Sport = col_character(),\n  ..   Event = col_character(),\n  ..   Medal = col_character()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Structure of noc_data dataset\n\nstr(noc_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspec_tbl_df [230 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ NOC   : chr [1:230] \"AFG\" \"AHO\" \"ALB\" \"ALG\" ...\n $ region: chr [1:230] \"Afghanistan\" \"Curacao\" \"Albania\" \"Algeria\" ...\n $ notes : chr [1:230] NA \"Netherlands Antilles\" NA NA ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   NOC = col_character(),\n  ..   region = col_character(),\n  ..   notes = col_character()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Summary of athlete_data\n\nlibrary(summarytools)\nprint(summarytools::dfSummary(athlete_data,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.60, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>athlete_data</h4>\n<strong>Dimensions</strong>: 271116 x 15\n  <br/><strong>Duplicates</strong>: 1385\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">ID\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 68249 (39022.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 68205 &le; 135571</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 67454.2 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">135571 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLisev1GUAAABGUlEQVRo3u2aWxLCIAxFwWGP7MGuB/fgKvWDqpFnReidzNzz4YxVQ04CrR+xD6ObCzoBCqAT+Bcn39hJQcN+sLZZARPkuXXDUZp4Y8z9lAK4sSDHlgjvUv3ai1iA+PvNttZzvSC1pOUSteDxO74YJUcmmmvUetrdQp8qlJJ+pZhe70fJX2uJtrejqy1WqkI7oEym/FloPjXHzk3xNuqN714ZYU6UAwKa+NpCQeEfo6QDK5p8qoA+KICGAmgogIYCaCiAhgJoKICGAmgogIYCaCiAhgJoKICGAmgogIYCaCiAhgJoKICGAmgogGbRzNwq9nEUMRumrAP5MIoygRwKoKEAGvUCVs753ZQM/V3Fc8AqybmK+i1EATRPsl5IxvhbHiQAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMDc6NDY6NDMrMDA6MDAVlTabAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDA3OjQ2OjQzKzAwOjAwZMiOJwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Name\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Robert Tait McKenzie</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Heikki Ilmari Savolainen</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Joseph \"Josy\" Stoffel</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Ioannis Theofilakis</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Takashi Ono</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Alexandros Theofilakis</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Alfrd (Arnold-) Hajs (Gut</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Andreas Wecker</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Jean Lucien Nicolas Jacob</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Alfred August \"Al\" Jochim</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 134721 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">58</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">39</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">36</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">33</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">32</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">32</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">32</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">32</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">31</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">270753</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">99.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGYAAACjCAQAAADS86PuAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAABL0lEQVR42u3XQWoCQRRFUTu4x6wsi3CVOq0OOIiTPvVzjyMRpC628Op43ub4uvoAxfyHmNtzef1s+Adazz/qlylGVYyqGFUxqmJUo2KOdVseV5/mA+v5R/0yp5gdrwBvY3ZXjKoYVTGqYlTFqFrNqlazqhhVMapiVMWoilG1mlWtZlUxqmJUxaiKURWjGhUz9wrQaoYUoypGVYyqGFUxqlExc1fz7roCqIpRFaMqRlWMqhhVq1nValYVoypGVYyqGFUxqlazqtWsKkZVjKoYVTGqYlSjYuZeAVrNkGJUxaiKURWjKkY1KqbVrBr1mBWjKkZVjKoYVTGqUTFzV/Pu7uubLa8Ay+N0P3/yffXR/uhxejfqMStGVYyqGFUxql8L4PHZtyCOHefYO6Mes2JUL7YPNi0555XtAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDA3OjQ2OjQ0KzAwOjAw0DIIFQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQwNzo0Njo0NCswMDowMKFvsKkAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Sex\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. M</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">27.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">196594</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">72.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAE4AAAAjCAQAAACQyfQSAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAAAfUlEQVRYw+3WwQnAIBBE0WywxxSRepIeUmVyXb2pK47hz00EeTDCrr2bbvbZAHAjkvzhrv6Ap0WDPCHlV0fVQ0+0rIh0reDAgQMHbmKK8TV6INXF/KANn+IN8Z51ar0UdnZXX9fKFJ/8z0vXCg4cOHB/x62zlahFulZwrfkAO34MNBanQq0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMDc6NDY6NDQrMDA6MDDQMggVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDA3OjQ2OjQ0KzAwOjAwoW+wqQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Age\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 25.6 (6.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10 &le; 24 &le; 97</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 7 (0.3)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">74 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAAA9ElEQVRo3u2ZUQ7CIBAFxfSO3kHPU+/QU+qHNqCWYME4+5I3P03Tpt2BJSyQbgdtjnQAFqADGGUqb9LH47kYIpfU/NqfKMft1Hr59LwudNQV5FPIAjQWoLEAjQVoLEBjARoL0FiAxgI0zTVxJi/w4yzvdwnEXN7Lp5AFaCxAYwEaC9BYgEZeoFLMzTKnr9Vq9FF7xqo8t5BPIQvQWIDGAjQWoNmxL5RZC40IG1xdApHKDPkUsgCNBWgsQCMv0DWRrUQ4dBoSiHDoNCSQ4aqjF4H+3SCuOnrrgdGk+K4JftlPqfzjVWQ/7lw0QBKJuYr8PGABmjuqdxzJW5jLewAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMlQwNzo0Njo0NCswMDowMNAyCBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjJUMDc6NDY6NDQrMDA6MDChb7CpAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">9474\n(3.5%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Height\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 175.3 (10.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">127 &le; 175 &le; 226</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 15 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">95 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAABEElEQVRo3u2XQQ6CQAxFGeMduYOeB+/gKXVDk9GoMUzbR/W/HQthHvzWtt2m2hzoA0iAPsAox/6iOd98WQvs7Hzjvm6Dv8A8zbEP+LEIebEk9uYQgWkNzjVBoHyEJEDjWgOZxRsikFm8RvkISYAm6I/skaihLk0gsrTLR0gCNBKgkQCNBGgkQFNewGWYI1ZJVwFilTTKR6i8QMpCY0RsZqkCEZVSPkISoJEAjQRoJEAjAZqhWYhcZFwEyEXG+O8IbcVzL0AEPINXPkISoJEADdKFDI92uknAa4TwaKcbvwA/Qhj/VQN7mD6HBKKiM1LMHwWy3ri9lufnfSPU+t9cdhiRV5w6sVbkzG8p34UkQHMHXiUra6vj4U4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMDc6NDY6NDQrMDA6MDDQMggVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDA3OjQ2OjQ0KzAwOjAwoW+wqQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">60171\n(22.2%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Weight\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 70.7 (14.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">25 &le; 70 &le; 214</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 19 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">220 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAAA/klEQVRo3u2aUQ7CIBAFF9M7egc9T72Dp9SvVUKspW7tsMmbvya0YSjwCrQ8LDcnugISoCsQZaovymrx+TVkruuF/0Y9bqetN5/NzOzO1b4hfReSAI0EaCRAszkHHI80MtBCAqMEWvouJAEaCdBIgCa9QGeQzcPuvnQn8SjJ25K+C0mARgI0EqCRAI0EaH7elXDo7ZWwAP2Rl74LSYBGAjQSoJEAjQRoJEAjAZrwesChFja7CVALm68C454KdAp4u454LuCkH8QSoJEAzW454BwdaB8FIvO/B9pRPykvvIF4rr4TpG2OfYVK/fRbguQ1M7tUTVCS1HmR9LOQBGieLDoiYQbxyZIAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMDc6NDY6NDQrMDA6MDDQMggVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDA3OjQ2OjQ0KzAwOjAwoW+wqQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">62875\n(23.2%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Team\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. United States</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. France</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Great Britain</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Italy</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Germany</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Canada</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Japan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Sweden</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Australia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Hungary</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 1174 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">17847</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11988</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11404</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10260</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9326</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9279</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8289</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8052</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7513</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6547</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">170611</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">62.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEUAAACjCAQAAAB2mRs9AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAABKUlEQVR42u3cS27CQBAFwHbEHTlEzpPcIacMqyFjYvORYLqx661ALFxyj/wGLDz9RpV8ZANQrufQv/meLZzP6fWH7w94mH90PL/6GX5WCg0IBQUFZcOUiwv/+Mv9X6a+kAb030X6o1cd0NcZOWKDcJXSNgk5K6bQgFBQUFCeHc3copkfomhmFBQUlBdFM7e8UzNn9PK/s3LsflpPpmQGBQUFZcMUm4SW1fvMmnmZkhkUFBSUDVM0c4uv77dik4CCgoIyIpq5RTPfimZGQUFBGRHN3PI+zZzTywvNnJdCA0JBQUHZD8UmISI0812UzKCgoKDsh6KZI0Iz30XJDAoKCsp+KJo5IkoNaOVf3sPSDWL1IW0jMl+ZhQaEgoKC8uxUveWdm0IDQlnKCW43PPLV6qtpAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDA3OjQ2OjQ0KzAwOjAw0DIIFQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQwNzo0Njo0NCswMDowMKFvsKkAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">NOC\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. USA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. FRA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. GBR</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. ITA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. GER</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. CAN</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. JPN</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. SWE</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. AUS</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. HUN</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 220 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">18853</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">7.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12758</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12256</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10715</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9830</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9733</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8444</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8339</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7638</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6607</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">165943</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">61.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEQAAACjCAQAAACZW3ADAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAABIUlEQVR42u3cQQ6CMBAF0MF4Rw/hefQOnlJXakGpMQIdm/dXGhe8MA2/QnS4Ro7sWgNA5rIv35xHC+Y4rH3w8nD78UeHx6vLxmckzWhAQEBAuoFMLvFbX9ifGcriWb3lJimPnXM0pwdx/S1AFXLfBrRYKWlGAwICAvJrtG+E9v0Con1BQEBAFoj2jfin9t2+e1/OyKG4Cd4U0i4gICAg3UBsAyIqz321byRarCAgICDdQLRvhC/h9dgGgICAgCwd7RuhfevRviAgICBLR/tGaN96tC8ICAhItxDbgIiPD6BbdO+b9m2VNIsVBAQEpFeI9tW+nyDtAgICAtIrRPvmGc3ML6A3SjGC2b8hWz/j9ZhmNCAgICC/Jued55ZJMxqQaW7iVT1LGFHQAgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMlQwNzo0Njo0NCswMDowMNAyCBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjJUMDc6NDY6NDQrMDA6MDChb7CpAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Games\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 2000 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 1996 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 2016 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 2008 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 2004 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 1992 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 2012 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 1988 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 1972 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 1984 Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 41 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13821</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13780</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13688</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13602</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13443</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12977</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12920</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12037</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10304</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9454</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">145090</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">53.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAD0AAACjCAQAAACTB95RAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAAA80lEQVR42u3csQ3CMBRFUQdlxwzBPLADU0IBQg6EAsn+duLzOkRxhBNyJQqme2q1UzN5UHrOX1zfF/481eHyO2tev7WklFK6hXzqMa81Go0+Hv3xII15hD435Q/0Ss3Ilmu9HPilejR/0qKJRqN3SytX8JQreGg0+ni0cgVPuYKHRqPRBTdmNJUreGg0Gl1wY5arlwMXTTQajf5/yhU85QoeGo0+Hq1cwVOu4KHRaHTBjRnNzXJFdOvrWi+vdjWgI4dGo9EFp1zKhUaj0fuixyxXLwd+qf9vNdnBbv5QWWvrO2nMLxcaja60XsoVuzGvdUP6ARreP6GR1W3PAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDA3OjQ2OjQ0KzAwOjAw0DIIFQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQwNzo0Njo0NCswMDowMKFvsKkAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1978.4 (29.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1896 &le; 1988 &le; 2016</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 42 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAABbUlEQVRo3u2ZwQ2DMAxFTcWO7NDOQ3dgyvYAVE5JRCB2vi35nVqphzz87SR0+JBvHugFhAB6Aa2M/MuAXg0Rzb+mfBWXw/t2JHNMRES0VP7afYRCAE0IoAkBNCGAJgTQhACaEEBj8D7A2a835cuN+QpM2wXHrcAZIYDGvQBoCuWmy3zrLSesArnpcjZxTAlIYXwj2ylvaIYFeE+U39YZjlBdRxgWqEM1QudHsXaUK3BnMF7DRBPf28JWjPTA/UqZqEA9W61YTxmpQC3HSjkTOOJeoHsPpBOnZf6ABNZzzcI+1/8jCRVof9ZgAYmnDRPQevqKAumSeeqlURuj+sc4ZYFeCESIn/o1064mID3Zr+E+Qu4FLkYozbjmXVdAIH8lX/OuOdnFBHhz9p8uIgLEFt97uggKlONioS5N+4CFqiQCPd6kSfO3D/Q6gsmRjZCFbDcJWMh2Le6PEgNPy9tJdJ5syAxO1lzEfYRCAM0XAhRD8vGVYLEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMDc6NDY6NDQrMDA6MDDQMggVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDA3OjQ2OjQ0KzAwOjAwoW+wqQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Season\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Summer</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Winter</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">222552</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">82.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">48564</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">17.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFYAAAAjCAQAAACksDUOAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAAAfElEQVRYw+3WwQmAMAyF4UTc0R10Ht2hU+pNaqGIhZgE/nfLJXyUB42ekieTNwBshMz1cAQs8KodrMjibWtSHlOqGoAFCxYsWLB3mu+2jG35KVrfLjq8xi61L28N9tcTcXN9/E8nonejU9UALFiwYMHaJu/VFT2pagDWKhdMwwufxaRY7QAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMlQwNzo0Njo0NCswMDowMNAyCBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjJUMDc6NDY6NDQrMDA6MDChb7CpAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">City\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. London</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Athina</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Sydney</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Atlanta</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Rio de Janeiro</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Beijing</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Barcelona</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Los Angeles</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Seoul</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Munich</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 32 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">22426</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">15556</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13821</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13780</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13688</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13602</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12977</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12423</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12037</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10304</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">130502</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">48.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADgAAACjCAQAAAB1LhUVAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLiyA28Q3AAAA+ElEQVR42u3bQQ7CMAxEUYJ6xx6C88AdOCUscWq1m9gOmvxZFSH10ZpkBFLb51abe7G3ALjZF6/DQB8tBrGn3fq3dnP8TrlC/RkCAgLOBw9bW852ZtPsxhq0V7tYY+4tfZqPElVNl+CvnvJmqb8sAAEBXWiL8Jy0RVZXnLRF5iT1lwUgIKALbREe2gIQEBBwPPr1RFsAAgICjke/LfgxEx79ZQEICOhCW4SHtgAEBBQEaYvw0BaAgICA49GvJ9oCEBAQcDyLtkVeV7gZ7t0TiAVgfgABARcE9dviX/76Co65dRePx0el/17oLwtAQECXuW1REf0ZloNfv/Y/9YycezAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMDc6NDY6NDQrMDA6MDDQMggVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDA3OjQ2OjQ0KzAwOjAwoW+wqQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Sport\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Athletics</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Gymnastics</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Swimming</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Shooting</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Cycling</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Fencing</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Rowing</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Cross Country Skiing</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Alpine Skiing</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Wrestling</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 56 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38624</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">26707</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">23195</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11448</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10859</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10735</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10595</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9133</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8829</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7154</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">113837</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">42.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADIAAACjCAQAAABiDIXcAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLi333PShAAABDElEQVR42u3b2w3CMAxAUYK6Y4dgHroDU8IXUkJemDgptq7/EKJH1NEVQhCel/lzXWA4Qrb4wdFY0C3ILhxfakuf2isveQy9Ez87AQEB6c9HVsbyUZsQh0zYwObE111/u+6F1EsT30Xy1OvsyM8RBgExjlBh0TQrrFHgDEkrrLcfP0cYBMQ4QoVFU6mwVn8LyLvC2pvxc4RBQED64yf1xQrrNjjbyV79+lkRmTMgICB/gvip8HkfuEk9CAjI70OFRUOFQUBAlIcKi4YKg4CAWET8pJ4Kg4CAWERcV1i7wYUKzxg/pwsEBESMGK7w+b98Hprotnz5V0PppLt1e4RBQKwh6z8Lzxo/O1mCvADx1T34HillrgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMlQwNzo0Njo0NSswMDowMHZFA6EAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjJUMDc6NDY6NDUrMDA6MDAHGLsdAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Event\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Football Men's Football</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Ice Hockey Men's Ice Hock</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Hockey Men's Hockey</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Water Polo Men's Water Po</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Basketball Men's Basketba</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Cycling Men's Road Race, </td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Gymnastics Men's Individu</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Rowing Men's Coxed Eights</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Gymnastics Men's Team All</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Handball Men's Handball</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 755 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5733</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4762</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3958</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3358</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3280</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2947</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2500</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2423</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2411</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2264</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">237480</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">87.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFsAAACjCAQAAABP/qpmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLi333PShAAABI0lEQVR42u3dsY0CMRRFUQ+iR4qgHraHrXJINphBCBPZ73vPzRDJ0ciIR4K3vVXsMhuAnd/1+OJnb621+zYb9b7jp/Dlad9m276s6CHBxsaOChv7n7B/Z3u+bDsOlNAN9deHKVWlE/uxP4r8RlvhadcJGxs7KmzsVdkW4MgsQGzsqLCxsaPCHpkFODILEBs7Kmxs7KiwsbutMFwtQGzs2WFjY0eFjd1thQVYJ8MVGzsqbGzsqLBHZgGOzALExo4KGxs7KuyRWYAjswCxsaPCxsaOChu72wrD1QLExp4dNjZ2VNjY3SzAkRU9JNjY2FFhY2NHVZS9wgKs0+nimPDZejgM1/M7uRfHnP/1vughwcbGjgobu9vLt2TJG1jqVPSQYI/sCQpuOt39Eb4hAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDA3OjQ2OjQ1KzAwOjAwdkUDoQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQwNzo0Njo0NSswMDowMAcYux0AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Medal\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Bronze</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Gold</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Silver</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13295</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13372</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACsAAAAyCAQAAABvjeoYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLi333PShAAAAdklEQVRYw+3VQQ6AIAwEwK3xj/4B34N/4JV6MwXipUBjk+2NyyQssMiNFbMtUYOxu15cQ0En+WCBw4wWjxDIkiX7TvN4i03pRnS7iJkBAC15hJDHfiAWI1myjiwbDBMb7Ky2OqnB2jOJdcHIko3IehTj70OIxT5ePRD/71lyKgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMlQwNzo0Njo0NSswMDowMHZFA6EAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjJUMDc6NDY6NDUrMDA6MDAHGLsdAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">231333\n(85.3%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.1.1)<br/>2022-12-22</p>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Summary of noc_data\n\nlibrary(summarytools)\nprint(summarytools::dfSummary(noc_data,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.60, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>noc_data</h4>\n<strong>Dimensions</strong>: 230 x 3\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">NOC\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. AFG</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. AHO</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. ALB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. ALG</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. AND</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. ANG</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. ANT</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. ANZ</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. ARG</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. ARM</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 220 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">220</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">95.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGIAAACjCAQAAADbGAOUAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLi333PShAAABLElEQVR42u3WQWoCQRRFUTu4R1eWRbhKM60WhCSTvvU5x5EIUpcu8R2v2/6+rj6AiEkRt9fy+t7oB7Kee8STEFEhokJEhYgKERUjIo518x1Xn+YP1nOPeBKniJ2m+MeIXYmoEFEhokJEhYgKK7bCiq0QUSGiQkSFiAoRFVZshRVbIaJCRIWIChEVIipGRMyb4lasCBEiMkRUiKgQUTEiYt6K3ZUpXiGiQkSFiAoRFSIqrNgKK7ZCRIWIChEVIipEVFixFVZshYgKERUiKkRUiKgYETFviluxIkSIyBBRIaJCRMWICCu2YsR1ElEhokJEhYgKERUjIuat2F3d1zdbTfHl2tzPnzyuPtovPU/vRlwnERUiKkRUiKh4+8d+/u9bLnbsNJc+GXGdRFT8AE2FNi1RscKVAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIyVDA3OjQ2OjQ1KzAwOjAwdkUDoQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMlQwNzo0Njo0NSswMDowMAcYux0AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">region\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Germany</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Czech Republic</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Malaysia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Russia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Serbia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Yemen</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Australia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Canada</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. China</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Greece</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 196 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">200</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">88.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFwAAACjCAQAAACtIrEfAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLi333PShAAABG0lEQVR42u3dQYrCQBRF0Yq4x15Er0f34CrT00RQih78vF+cOwtCOIQSX0Zu++jZ7WoAeJfux4vnPsbvdjXpc8fvY9snDg4OHho4OHhobeHbcbgE76sxxooj67E/2rzJrfHEOwUODh4aOPjqcOuwOusQHDw0cHDw0MCrsw6rsw7BwUMDBwcPDRx8sjVmrXUIDp4TODh4aODgk62xDjtl1oKDhwYODh4aeHXWYXXWITh4aODg4KGBV2cdVmcdgoOHBg4OHho4+GRrzFrrEBw8J3Bw8NDAwSezDqtre1TAwcFDAwcHD60tfI112KnT3+rEj9rDkbifP/m5mval1+mq7VEBBwcPDRx8srdfztf/7nJBW/o8+VTbowJe3R+auzndk/1uPAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMlQwNzo0Njo0NSswMDowMHZFA6EAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjJUMDc6NDY6NDUrMDA6MDAHGLsdAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">3\n(1.3%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">notes\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Antigua and Barbuda</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Australasia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Bohemia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Crete</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Hong Kong</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Individual Olympic Athlet</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Netherlands Antilles</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Newfoundland</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. North Borneo</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. North Yemen</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 11 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">52.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADwAAACjCAQAAAB8xbVvAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBYHLi333PShAAAA5klEQVR42u3cuw3CMBSGUQdlR4ZgHtiBKaEAIQcBhYVvbN3zdYjiCOfxdyy3sk+HndyE8Fp/uLwu+GnpgdX307r96lhKKeUa8IvzXWMwGDw//PbKjHhZPlrqF3eXZaiqrTGO+tx5Fr/CZhEMBk8BW6ewrFNYYDB4ftg6hWWdwgKDweDm8s2idQoLDAaDm8u3TmMctVkEg8HgX1mnsKxTWGAweH7YOoVlncICg8Hg5vLNonUKCwwGg5uzTs+sExgMBg8E51unMY763Pt/WKoj/TiLfdreP/keJzAY/LfGWKfI8l3j3eA7yEBASZV3hUIAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjJUMDc6NDY6NDUrMDA6MDB2RQOhAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIyVDA3OjQ2OjQ1KzAwOjAwBxi7HQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">209\n(90.9%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.1.1)<br/>2022-12-22</p>\n</div>\n```\n:::\n:::\n\n\n\n### Briefly describe the data\n\nThe dataset contains information on the modern Olympic Games, including all the Games from Athens 1896 to Rio 2016 (the past 120 years). The Winter and Summer Games were held in the same year until 1992. After that, they were staggered such that the Winter Games occur once every 4 years starting with 1994, and the Summer Games occur once every 4 years starting with 1996. The \"athlete_events.csv\" file has 271,116 observations and 15 variables/attributes. Each row in this csv file corresponds to an individual athlete competing in an individual Olympic event (athlete-events). It includes information about the athlete's name, gender, age, height (in cm), weight (in kg), team/country they represent, National Olympic Committee (3-letter code) they are representing, year and season participated, Olympic games host city for that year and season, sport, athlete event and medal won. Each athlete will have multiple observations in the data as they would have participated in multiple events and during different seasons. This csv file has 1385 duplicates which I will be investigating in the next steps. The \"noc_regions.csv\" file has 230 observations and 3 variables/attributes. This file contains information about the 'NOC' National Olympic Committee which is a 3-letter code, the corresponding region and notes. The file has 230 unique codes for the NOC variable. Few of the regions have same NOC code which in some cases is distinguished using the notes. The notes has missing value for 209 observations. The NOC variable is present in both the files and can be used as a key to join both the files into a single dataset.\n\n### Looking into duplicate data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Displaying the duplicate observations in \"athlete_events.csv\" file\n\nduplicate_athlete_data <- athlete_data[duplicated(athlete_data),]\nduplicate_athlete_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,385 × 15\n      ID Name     Sex     Age Height Weight Team  NOC   Games  Year Season City \n   <dbl> <chr>    <chr> <dbl>  <dbl>  <dbl> <chr> <chr> <chr> <dbl> <chr>  <chr>\n 1   704 Dsir An… M        27     NA     NA Belg… BEL   1932…  1932 Summer Los …\n 2  2449 William… M        48     NA     NA Unit… USA   1928…  1928 Summer Amst…\n 3  2449 William… M        48     NA     NA Unit… USA   1928…  1928 Summer Amst…\n 4  2777 Hermann… M        43     NA     NA Germ… GER   1928…  1928 Summer Amst…\n 5  2777 Hermann… M        43     NA     NA Germ… GER   1928…  1928 Summer Amst…\n 6  2777 Hermann… M        51     NA     NA Germ… GER   1936…  1936 Summer Berl…\n 7  2903 Lucien … M        46     NA     NA Fran… FRA   1924…  1924 Summer Paris\n 8  2903 Lucien … M        46     NA     NA Fran… FRA   1924…  1924 Summer Paris\n 9  4319 Ludwig … M        41     NA     NA Germ… GER   1932…  1932 Summer Los …\n10  4319 Ludwig … M        41     NA     NA Germ… GER   1932…  1932 Summer Los …\n# … with 1,375 more rows, and 3 more variables: Sport <chr>, Event <chr>,\n#   Medal <chr>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(duplicate_athlete_data$Sport)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nArt Competitions          Cycling    Equestrianism          Sailing \n            1315               32                1               37 \n```\n:::\n:::\n\n\nThe \"athlete_events.csv\" file has 1385 duplicates as shown above. The table() shows that more than 90% of the duplicate observations are for the Sport 'Art Competitions'. These duplicates could have been introduced during the data collection while performing scraping. The duplicates can be removed from the athlete_data during the data cleaning process and before joining the datasets.\n\n\n## Tidy Data and Mutate Variables (as needed)\n\nThe noc_data has some missing value in 212 observations. Hence, I start by cleaning the noc_data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check for missing/null data in the noc_data\n\nsum(is.na(noc_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 212\n```\n:::\n\n```{.r .cell-code}\nsum(is.null(noc_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking which columns have NA values in noc_data\n\ncol <- colnames(noc_data)\nfor (c in col){\n  print(paste0(\"NA values in \", c, \": \", sum(is.na(noc_data[,c]))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"NA values in NOC: 0\"\n[1] \"NA values in region: 3\"\n[1] \"NA values in notes: 209\"\n```\n:::\n:::\n\n\nThe 'region' variable in noc_data has missing values for 3 observations. The corresponding NOC code for these 3 observations are ROT, TUV, and UNK. I have displayed the 3 observations below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Displaying the observations with missing value in 'region' variable\n\nnoc_data%>%filter(is.na(region))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  NOC   region notes               \n  <chr> <chr>  <chr>               \n1 ROT   <NA>   Refugee Olympic Team\n2 TUV   <NA>   Tuvalu              \n3 UNK   <NA>   Unknown             \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Displaying the observations with same value for both 'region' and 'notes' variables\n\nnoc_data%>%filter(region==notes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 3\n  NOC   region                      notes                      \n  <chr> <chr>                       <chr>                      \n1 IOA   Individual Olympic Athletes Individual Olympic Athletes\n```\n:::\n:::\n\n\nAlthough the 'region' value is missing for these observations, we have the 'notes' for them. From the notes it is evident that ROT stands for Refugee Olympic Team, TUV stands for Tuvalu and UNK stands for Unknown. I further analyzed whether there are any observations in noc_data with the same value for both 'region' and 'notes' variables and found 1 observation. For the NOC code 'IOA', the region and notes is given the value 'Individual Olympic Athletes'. Hence, for the NOC codes 'ROT', 'TUV' and 'UNK' I decided to impute the missing 'region' values with the corresponding 'notes' values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Imputing the missing 'region' values with the corresponding 'notes' values in noc_data\n\nnoc_data <- noc_data%>%\n  mutate(region = coalesce(region,notes))\n\n# Sanity Check: Checking that the 3 observations no longer have missing 'region' values\n\nnoc_data%>%filter(is.na(region))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 × 3\n# … with 3 variables: NOC <chr>, region <chr>, notes <chr>\n```\n:::\n:::\n\n\n\nThe 'notes' variable in noc_data has missing values for 209 observations. Since, this is more than 90% I decided to drop the 'notes' variable. After dropping the 'notes' variable from the noc_data, it is left with 230 observations and 2 variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dropping the 'notes' variable from noc_data\nnoc_data <- noc_data%>%\n  select(-c(3))\n\n# Displaying the noc_data after tidying\n\nnoc_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 230 × 2\n   NOC   region     \n   <chr> <chr>      \n 1 AFG   Afghanistan\n 2 AHO   Curacao    \n 3 ALB   Albania    \n 4 ALG   Algeria    \n 5 AND   Andorra    \n 6 ANG   Angola     \n 7 ANT   Antigua    \n 8 ANZ   Australia  \n 9 ARG   Argentina  \n10 ARM   Armenia    \n# … with 220 more rows\n```\n:::\n:::\n\n\nNext, I cleaned the athlete_data. As the first step of cleaning the athlete_data, I dropped the 1385 duplicate observations which I had identified earlier while exploring the data. After dropping the duplicate observations, the athlete_data has 269,731 observations and 15 variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dropping the 1385 duplicate observations from athlete_data\n\nathlete_data <- athlete_data%>%\n  distinct()\n```\n:::\n\n\nThe athlete_data has 359615 instances of missing values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check for missing/null data in the athlete_data\n\nsum(is.na(athlete_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 359615\n```\n:::\n\n```{.r .cell-code}\nsum(is.null(athlete_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nThe variables 'Age', 'Height', 'Weight' and 'Medal' have missing values in the athlete_data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking which columns have NA values in athlete_data\n\ncol <- colnames(athlete_data)\nfor (c in col){\n  print(paste0(\"NA values in \", c, \": \", sum(is.na(athlete_data[,c]))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"NA values in ID: 0\"\n[1] \"NA values in Name: 0\"\n[1] \"NA values in Sex: 0\"\n[1] \"NA values in Age: 9315\"\n[1] \"NA values in Height: 58814\"\n[1] \"NA values in Weight: 61527\"\n[1] \"NA values in Team: 0\"\n[1] \"NA values in NOC: 0\"\n[1] \"NA values in Games: 0\"\n[1] \"NA values in Year: 0\"\n[1] \"NA values in Season: 0\"\n[1] \"NA values in City: 0\"\n[1] \"NA values in Sport: 0\"\n[1] \"NA values in Event: 0\"\n[1] \"NA values in Medal: 229959\"\n```\n:::\n:::\n\n\nThe 'Medal' variable has 13295 observations with value Bronze, 13108 observations with value Silver, and 13369 observations with value Gold. The remaining values are missing for 'Medal' variable. The missing values indicate that the athlete did not win a medal for that sport event during that year and season.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(athlete_data$Medal)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBronze   Gold Silver \n 13295  13369  13108 \n```\n:::\n:::\n\n\nI handled the missing data in 'Medal' variable by imputing the missing values with 'No Medal' as the athlete did not win a medal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Handling missing data in 'Medal' variable\n\nathlete_data <- athlete_data%>%\n  mutate(Medal = replace(Medal, is.na(Medal), \"No Medal\"))\n\n#Sanity Check: Checking that the 'Medal' variable has no missing values after data imputation\n\nsum(is.na(athlete_data$Medal))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\ntable(athlete_data$Medal)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  Bronze     Gold No Medal   Silver \n   13295    13369   229959    13108 \n```\n:::\n:::\n\n\nThe variables 'Age', 'Height', and 'Weight' have 9315, 58814, and 61527 missing values respectively. This is equivalent to 0.03%, 0.22% and 0.23% of missing values. This is a significantly large number and I performed data imputation for these variables. I imputed the missing values with the average Age, Height and Weight of the athletes grouped by Sex, Season, Year, and Event. I grouped based on those variables as the athletes participating in the various events are usually in the same age, height and weight range. For example, the male athletes participating in the heavy weight wrestling belong to weight categories like 55kg/60kg/etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the percentage of missing values for the variables 'Age', 'Height', and 'Weight'\n\nathlete_data %>% summarize_all(funs(sum(is.na(.)) / length(.)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 15\n     ID  Name   Sex    Age Height Weight  Team   NOC Games  Year Season  City\n  <dbl> <dbl> <dbl>  <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl> <dbl>\n1     0     0     0 0.0345  0.218  0.228     0     0     0     0      0     0\n# … with 3 more variables: Sport <dbl>, Event <dbl>, Medal <dbl>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Handling the missing data in 'Age', 'Height', and 'Weight' variables using data imputation\n\n# Storing the average age, height, and weight for each group\naverage_athlete_data <- athlete_data%>%\n  group_by(Sex, Season, Year, Event)%>%\n  summarise(average_Age = mean(Age, na.rm = TRUE),\n            average_Height = mean(Height, na.rm = TRUE),\n            average_Weight = mean(Weight, na.rm = TRUE))\n\n# Joining the athlete_data and average_athlete_data using Sex, Season, Year and Event as the key\ncleaned_athlete_data = merge(x=athlete_data, y=average_athlete_data, by=c(\"Sex\", \"Season\", \"Year\", \"Event\"), all.x=TRUE)\ncleaned_athlete_data <- tibble(cleaned_athlete_data)\n\n# Replacing the missing values in 'Age', 'Height', and 'Weight' variables with the corresponding values in 'Average_Age', 'Average_Height', and 'Average_Weight' variables\ncleaned_athlete_data <- cleaned_athlete_data%>%\n    mutate(Age = coalesce(Age, average_Age),\n           Height = coalesce(Height, average_Height),\n           Weight = coalesce(Weight, average_Weight))\n\n# Dropping the variables 'Average_Age', 'Average_Height', and 'Average_Weight' from cleaned_athlete_data as they are no longer needed\n\ncleaned_athlete_data <- cleaned_athlete_data%>%\n  select(-c(16,17,18))\n\n# Rounded off the Age', 'Height', and 'Weight' variables to the nearest integer\n\ncleaned_athlete_data <- cleaned_athlete_data%>%\n  mutate(Age = round(Age, digits = 0),\n         Height = round(Height, digits = 0),\n         Weight = round(Weight, digits = 1))\n\n# Finding the percentage of missing values for the variables 'Age', 'Height', and 'Weight' to check whether the percentage of missing values has decreased\n\ncleaned_athlete_data %>% summarize_all(funs(sum(is.na(.)) / length(.)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 15\n    Sex Season  Year Event    ID  Name      Age Height Weight  Team   NOC Games\n  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl>\n1     0      0     0     0     0     0 0.000552 0.0207 0.0452     0     0     0\n# … with 3 more variables: City <dbl>, Sport <dbl>, Medal <dbl>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Displaying the count of missing values in cleaned_athlete_data for each variable\n\ncol <- colnames(cleaned_athlete_data)\nfor (c in col){\n  print(paste0(\"NA values in \", c, \": \", sum(is.na(cleaned_athlete_data[,c]))))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"NA values in Sex: 0\"\n[1] \"NA values in Season: 0\"\n[1] \"NA values in Year: 0\"\n[1] \"NA values in Event: 0\"\n[1] \"NA values in ID: 0\"\n[1] \"NA values in Name: 0\"\n[1] \"NA values in Age: 149\"\n[1] \"NA values in Height: 5586\"\n[1] \"NA values in Weight: 12185\"\n[1] \"NA values in Team: 0\"\n[1] \"NA values in NOC: 0\"\n[1] \"NA values in Games: 0\"\n[1] \"NA values in City: 0\"\n[1] \"NA values in Sport: 0\"\n[1] \"NA values in Medal: 0\"\n```\n:::\n:::\n\n\nThe percentage of missing values for the variables 'Age', 'Height', and 'Weight' has reduced from 0.03%, 0.22% and 0.23% to 0.00056%, 0.02% and 0.046 % respectively which is a significant improvement. The remaining missing values could not be imputed as all the observations in the groups (grouped by Sex, Season, Year and Event) had missing values for 'Age'/'Height'/'Weight' which makes it impossible to get the mean values. One possible solution is to remove all the observations with missing values in any of the variables. This would result in 12,792 observations being dropped which is about 5% of the total data. For now, I am keeping the observations with missing values. However, I can remove the 12,792 observations and store it in another tibble for performing visualization in the future.\n\n\nThe 'Games' variable is redundant as it contains information about the year and season of the Olympic games which is already present in the 'Year' and 'Season' variables. Hence, I dropped the 'Games' variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dropping the 'Games' variable from cleaned_athlete_data\n\ncleaned_athlete_data <- cleaned_athlete_data%>%\n  select(-c(12))\n```\n:::\n\n\nThe cleaned_athlete_data is left with 269731 observations and 14 variables after cleaning.\n\n\n## Join Data\n\nAs the next step after tidying the datasets, I joined the cleaned_athlete_data and noc_data using 'NOC' as the key, into a single dataset. The joined dataset has 269731 observations and 15 variables which makes sense as the cleaned_athlete_data had 269731 observations and cleaned_athlete_data and noc_data datasets had 14 and 2 attributes respectively. Since, the \"NOC\" attribute is common in both datasets we count it only once.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# performed left join for cleaned_athlete_data and noc_data datasets.\nolympic_data = merge(x=cleaned_athlete_data, y=noc_data, by=\"NOC\", all.x=TRUE)\nolympic_data <- tibble(olympic_data)\nolympic_data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 269,731 × 15\n   NOC   Sex   Season  Year Event       ID Name    Age Height Weight Team  City \n   <chr> <chr> <chr>  <dbl> <chr>    <dbl> <chr> <dbl>  <dbl>  <dbl> <chr> <chr>\n 1 AFG   M     Summer  1988 Wrestl…  84618 Ahma…    24    161   53.6 Afgh… Seoul\n 2 AFG   F     Summer  2012 Athlet…  61961 Tahm…    23    160   52   Afgh… Lond…\n 3 AFG   M     Summer  1964 Wrestl…  86829 Nour…    20    162   58.8 Afgh… Tokyo\n 4 AFG   M     Summer  1936 Hockey…   5841 Saye…    22    174   82   Afgh… Berl…\n 5 AFG   M     Summer  1960 Wrestl… 116125 Niza…    34    168  111   Afgh… Roma \n 6 AFG   M     Summer  1948 Hockey…   5844 Moha…    28    176   74.1 Afgh… Lond…\n 7 AFG   M     Summer  1956 Hockey…  87372 Din …    27    177   72.6 Afgh… Melb…\n 8 AFG   M     Summer  1960 Wrestl…  58364 Moha…    20    166   62   Afgh… Roma \n 9 AFG   M     Summer  2012 Judo M…  33817 Ajma…    25    173   66   Afgh… Lond…\n10 AFG   M     Summer  1972 Wrestl…  28855 Ahma…    24    165   52   Afgh… Muni…\n# … with 269,721 more rows, and 3 more variables: Sport <chr>, Medal <chr>,\n#   region <chr>\n```\n:::\n:::\n\n\nI rearranged the order of variables in olympic_data to make the data more understandable and easier for analyzing. I also sorted the olympic_data in ascending order based on 'Season' and 'Year'.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rearranging the columns in olympic_data\n\nolympic_data <- olympic_data%>%\n  select(c(\"Season\", \"Year\", \"ID\", \"Name\", \"Sex\", \"Age\", \"Height\", \"Weight\", \"Team\", \"NOC\", \"region\", \"City\", \"Sport\", \"Event\", \"Medal\"))\n\n# Sorting the olympic_data in ascending order based on 'Season' and 'Year'\n\nolympic_data <- olympic_data%>%\n  arrange(Season, Year)\n```\n:::\n\n\nThe olympic_data is cleaned and can be used for answering various research questions related to the Olympic games.\n\n\n## Potential Research Questions\n\nI have arrived at few potential research questions that can be answered or analyzed using the cleaned olympic_data.\n\n1) What is the ratio of male to female athletes participating in the Olympic games and has gender equality of athletes participating increased over the past 120 years?\n2) Has the performance of female athletes improved over the years for teams?\n3) Does the host city have any advantage in Olympic games in terms of winning more medals?\n4) Is it possible to identify which sport event wins more medals for each team?\n5) Has there been a significant change in the age/height/weight of athletes participating in the various events over the years?\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}