{
  "hash": "7c45b2b548bc0ee0ae98e90890b47124",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Kristin Abijaoude\"\nauthor: \"Kristin Abijaoude\"\ndesription: \"Reading in data and creating a post\"\ndate: \"09/15/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - railroads\n  - kristin_abijaoude\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, using the correct R package and command.\n\n-   railroad_2012_clean_county.csv ⭐\n-   birds.csv ⭐⭐\n-   FAOstat\\*.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n-   StateCounty2012.xls ⭐⭐⭐⭐\n\nFind the `_data` folder, located inside the `posts` folder. Then you can read in the data, using either one of the `readr` standard tidy read commands, or a specialized package such as `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroads<- read_csv(\"_data/railroad_2012_clean_county.csv\")\nrailroads\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# … with 2,920 more rows\n```\n:::\n:::\n\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(railroads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n\nIn total, we have 2930 entries in this dataset, with 2930 counties across the US accounted for. Some counties have a minimum of 1 railroad employee, while Cook County, IL has the most with 8207 railroad employees.\n\nHere are the first 6 rows of the dataset. In total, there are 2930 rows and 3 columns: state, county, and total employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(railroads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               total_employees\n  <chr> <chr>                          <dbl>\n1 AE    APO                                2\n2 AK    ANCHORAGE                          7\n3 AK    FAIRBANKS NORTH STAR               2\n4 AK    JUNEAU                             3\n5 AK    MATANUSKA-SUSITNA                  2\n6 AK    SITKA                              1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(railroads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(railroads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n:::\n\n\nLet's narrow it down to Massachusetts, where we are now. There are 12 counties in Massachusetts, with Barnstable County with the least amount of railroad employees with 44 of them, while Middlesex County has the most with 673 railroad employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(railroads, state == \"MA\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 3\n   state county     total_employees\n   <chr> <chr>                <dbl>\n 1 MA    BARNSTABLE              44\n 2 MA    BERKSHIRE               50\n 3 MA    BRISTOL                232\n 4 MA    ESSEX                  314\n 5 MA    FRANKLIN               113\n 6 MA    HAMPDEN                202\n 7 MA    HAMPSHIRE               68\n 8 MA    MIDDLESEX              673\n 9 MA    NORFOLK                386\n10 MA    PLYMOUTH               429\n11 MA    SUFFOLK                558\n12 MA    WORCESTER              310\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(railroads, `total_employees` > 1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 27 × 3\n   state county         total_employees\n   <chr> <chr>                    <dbl>\n 1 CA    LOS ANGELES               2545\n 2 CA    RIVERSIDE                 1567\n 3 CA    SAN BERNARDINO            2888\n 4 CT    NEW HAVEN                 1561\n 5 DE    NEW CASTLE                1275\n 6 FL    DUVAL                     3073\n 7 IL    COOK                      8207\n 8 IL    WILL                      1784\n 9 IN    LAKE                      1999\n10 KS    JOHNSON                   1286\n# … with 17 more rows\n```\n:::\n:::\n\n\nThere are 27 counties with more than 1000 total railroad employees, while there are 488 counties with fewer than 5 (yes, you read that correctly) railroad employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(railroads, `total_employees` < 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 488 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    FAIRBANKS NORTH STAR               2\n 3 AK    JUNEAU                             3\n 4 AK    MATANUSKA-SUSITNA                  2\n 5 AK    SITKA                              1\n 6 AL    BARBOUR                            1\n 7 AL    FAYETTE                            3\n 8 AL    HENRY                              1\n 9 AL    PERRY                              4\n10 AP    APO                                1\n# … with 478 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(railroads, `total_employees` > 1000 & `state` == \"CA\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  state county         total_employees\n  <chr> <chr>                    <dbl>\n1 CA    LOS ANGELES               2545\n2 CA    RIVERSIDE                 1567\n3 CA    SAN BERNARDINO            2888\n```\n:::\n:::\n\n\nWhen I used the filter code to only show California, the nation's most populous state, it's unsurprising that there would be a lot of railroad employees.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}