<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew O’Neill">
<meta name="dcterms.date" content="2022-12-01">

<title>DACSS 601: Data Science Fundamentals - FALL 2022 - Final Paper</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta name="twitter:title" content="DACSS 601: Data Science Fundamentals - FALL 2022 - Final Paper">
<meta name="twitter:description" content="I will be analyzing a dataset for Massachusetts public schools and districts.">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <img src="../images/UMass White Wordmark Horiz.png" alt="">
    <span class="navbar-title">DACSS 601: Data Science Fundamentals - FALL 2022</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page">Fall 2022 Posts</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">Contributors</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">DACSS</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/601_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 </a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Final Paper</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Course information</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Syllabus.html" class="sidebar-item-text sidebar-link">Overview</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../instructional_team.html" class="sidebar-item-text sidebar-link">Instructional Team</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../course_schedule.html" class="sidebar-item-text sidebar-link">Course Schedule</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Weekly materials</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Posts</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#central-question" id="toc-central-question" class="nav-link" data-scroll-target="#central-question">Central Question</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#mutation" id="toc-mutation" class="nav-link" data-scroll-target="#mutation">Mutation</a></li>
  <li><a href="#teacher-salary-category-first-glance" id="toc-teacher-salary-category-first-glance" class="nav-link" data-scroll-target="#teacher-salary-category-first-glance">Teacher Salary Category First Glance</a></li>
  <li><a href="#multivariate-analysis" id="toc-multivariate-analysis" class="nav-link" data-scroll-target="#multivariate-analysis">Multivariate Analysis</a></li>
  <li><a href="#conclusions-from-multivariate-visuals" id="toc-conclusions-from-multivariate-visuals" class="nav-link" data-scroll-target="#conclusions-from-multivariate-visuals">Conclusions From Multivariate Visuals</a></li>
  <li><a href="#linear-regression-model" id="toc-linear-regression-model" class="nav-link" data-scroll-target="#linear-regression-model">Linear Regression Model</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection">Reflection</a></li>
  <li><a href="#what-i-learned" id="toc-what-i-learned" class="nav-link" data-scroll-target="#what-i-learned">What I Learned</a></li>
  <li><a href="#what-i-would-improve-in-the-future" id="toc-what-i-would-improve-in-the-future" class="nav-link" data-scroll-target="#what-i-would-improve-in-the-future">What I Would Improve In the Future</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">Bibliography</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">Final Paper</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Final Paper</div>
    <div class="quarto-category">Matthew O’Neill</div>
    <div class="quarto-category">MA_Public_Schools_2017</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matthew O’Neill </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 1, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>,<span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>I will be analyzing a dataset for Massachusetts public schools and districts. The dataset was collected from the 2017 academic year and is a combination of several smaller datasets reported by all 288 public school districts in Massachusetts to the Massachusetts Department of Education. Each of the 376 rows of the dataset represents a high school and each school contains socioeconomic data(e.g.&nbsp;% economically disadvantaged, % African American, % White, etc) along with outcomes of students from those schools(% graduated, % pursuing college/university). Test scores(e.g.&nbsp;SAT, AP, MCAS) are also collected and can be used as a secondary metric of student success. Finally, the data includes school finances(e.g.&nbsp;teacher salary, district expenditures) which will be the primary focus of our analysis as predictor variables for student success. Schools in the dataset range from elementary to high school, but I will be working with just the subset of high schools.</p>
<p>I will be making the scope of my analysis more narrow and focus solely on high schools, and as such, many of the MCAS related columns can be omitted to make the dataset easier to work with. The focus of my analysis will be how spending can affect test scores and graduation rates.</p>
</section>
<section id="central-question" class="level2">
<h2 class="anchored" data-anchor-id="central-question">Central Question</h2>
<p>Different school districts vary widely when it comes to how their schools are funded and how their teachers are compensated. Much of the data on how school districts spend their money is public, we can be useful for an analysis of the factors which can lead to better outcomes among students in public schools.</p>
<p>The central question investigated in this paper is: does increasing teacher salary in public schools impact the success of students? Student success will be defined primarily by higher graduation rates but we will also look into higher test scores as a metric of success. During the process of exploring this question, we will also be exploring how the economic background of students and class size impacts school success, especially in conjunction with average teacher salary.</p>
</section>
<section id="data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h2>
<p>The dataset is in fairly nice shape to begin with, but we are only interested in a small portion of the original 300 columns of data and since we are only interested in high schools, we can safely omit Elementary and Middle schools which do not report a Graduation rate.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/MA_Public_Schools_2017.csv"</span>,<span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>keeps <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">10</span>,<span class="dv">13</span>,<span class="dv">14</span>,<span class="dv">15</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">28</span>,<span class="dv">29</span>,<span class="dv">30</span>,<span class="dv">31</span>,<span class="dv">32</span>,<span class="dv">34</span>,<span class="dv">36</span>,<span class="dv">38</span>,<span class="dv">40</span>,<span class="dv">41</span>,<span class="dv">42</span>,<span class="dv">43</span>,<span class="dv">44</span>,<span class="dv">45</span>,<span class="dv">46</span>,<span class="dv">47</span>,<span class="dv">48</span>,<span class="dv">49</span>,<span class="dv">50</span>,<span class="dv">51</span>,<span class="dv">52</span>,<span class="dv">53</span>,<span class="dv">55</span>,<span class="dv">62</span>,<span class="dv">64</span>,<span class="dv">68</span>,<span class="dv">70</span>,<span class="dv">71</span>,<span class="dv">72</span>,<span class="dv">80</span>,<span class="dv">81</span>,<span class="dv">82</span>,<span class="dv">83</span>,<span class="dv">84</span>,<span class="dv">85</span>,<span class="dv">86</span>,<span class="dv">87</span>,<span class="dv">88</span>,<span class="dv">89</span>,<span class="dv">90</span>,<span class="dv">91</span>,<span class="dv">92</span>,<span class="dv">93</span>,<span class="dv">94</span>,<span class="dv">95</span>,<span class="dv">96</span>,<span class="dv">97</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> data[keeps]<span class="sc">%&gt;%</span> </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">subset</span>(<span class="sc">!</span> <span class="fu">is.na</span>(data<span class="sc">$</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(hs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 376  55</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">District Code</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 288</code></pre>
</div>
</div>
<p>After slimming down the dataset to only contain necessary data there are 376 rows, representing 376 Massachusetts high schools, and 53 columns of useful data for each. There are also 288 unique district codes, as larger districts have more than one high school. Districts are important to our central question because most districts have standardized pay scales and multiple schools in the same district will be reported to have the same average salary.</p>
<p>The variables that I am interested in specifically from this dataset are Average Teacher Salary, Graduation Rates, SAT Scores, Average AP Test Scores, Average Class Sizes, and percentage of students who are economically disadvantaged. The last of these may be the most important to our analysis, as economically disadvantaged students will have a harder time in school regardless of teacher salary, so we need to compare across schools with a similar proportion of economically disadvantaged students.</p>
<p>Average teacher salary is reported by district, which is unfortunate of our analysis as some districts have many schools which can vary in performance. However, the only real outlier in regards to this issue is Boston Public Schools. For this reason, our analysis will be done on Massachusetts as a whole, and Massachusetts excluding Boston Public schools. Teacher salary will be the focus of the analysis, as if a correlation with salary can be shown to affect student success then real steps could be taken by policy makers to improve student success by increasing teacher salary. Similarly, if a correlation with class size and student success can be shown, steps could be taken to hire more teachers, thus reducing the average class size.</p>
<p>The percent of economically disadvantaged students in each school will not be explored much explicitly when it comes to predicting student success, but it is very important to the analysis of teacher salary, as it plays a role in explaining some of the variance in the most trivial model of student success with teacher salary.</p>
<p>Since our focus is primarily high school students, the metrics for success will be primarily Graduation rates, AP Scores, and SAT Scores. Graduation rates are recorded across the board, but not every student takes the SATs or AP tests, which can skew the average scores. More specifically, economically disadvantaged students and students who are already performing poorly in school are less likely to pay for these courses, so while we will explore how teacher salary affects these metrics, the focus will be on graduation rates.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Average Salary Breakdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Average Salary Breakdown"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  53763   67556   73404   74267   78802  100731      36 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Graduation Rates Breakdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Graduation Rates Breakdown"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   82.15   92.25   83.33   96.20  100.00 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Percentage Economically Disadvantaged Breakdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Percentage Economically Disadvantaged Breakdown"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   3.10   13.18   25.55   30.82   44.33   93.90 </code></pre>
</div>
</div>
<p>After taking a very short look into some summary statistics for some of the variables we will be diving into, it appears that the average teacher salary across the state is $74000, without too much variance. Graduation rates average 83% statewide but this number appears to be skewed as the median is a fair bit higher at 92%. The percentage of economically disadvantages students in a given school also appears to be skewed a bit by outliers, as the average statewide is 30% but the median is 25.5%, indicating that there are some schools with a very high percentage of economically disadvantaged students.</p>
</section>
<section id="mutation" class="level2">
<h2 class="anchored" data-anchor-id="mutation">Mutation</h2>
<p>Working with the data can be made a lot easier by partitioning some of the variables we’re interested in into sections. For teacher salary, average expenditure, class size, and percentage of economically disadvantaged students, I will be creating a categorical variable placing schools into various brackets of each variable. This will make correlations a bit more clear as there is not necessarily a clear trend across all schools when it comes to student performance when plotted against any of these variables individually.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs,<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">55000</span> <span class="sc">~</span> <span class="st">"$55000 or Less"</span>,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">60000</span> <span class="sc">~</span> <span class="st">"$55000 to $60000"</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">65000</span> <span class="sc">~</span> <span class="st">"$60000 to $65000"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">70000</span> <span class="sc">~</span> <span class="st">"$65000 to $70000"</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">75000</span> <span class="sc">~</span> <span class="st">"$70000 to $75000"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">80000</span> <span class="sc">~</span> <span class="st">"$75000 to $80000"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">85000</span> <span class="sc">~</span> <span class="st">"$80000 to $85000"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="dv">90000</span> <span class="sc">~</span> <span class="st">"$85000 to $90000"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">90000</span> <span class="sc">~</span> <span class="st">"$90000 or more"</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>              ))</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs,<span class="st">`</span><span class="at">Per Pupil Expenditure Bracket</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">12500</span> <span class="sc">~</span> <span class="st">"$12500 or Less"</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">15000</span> <span class="sc">~</span> <span class="st">"$12500 to $15000"</span>,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">17500</span> <span class="sc">~</span> <span class="st">"$15000 to $17500"</span>,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">20000</span> <span class="sc">~</span> <span class="st">"$17500 to $20000"</span>,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">22500</span> <span class="sc">~</span> <span class="st">"$20000 to $22500"</span>,</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="dv">25000</span> <span class="sc">~</span> <span class="st">"$22500 to $25000"</span>,</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">25000</span> <span class="sc">~</span> <span class="st">"$25000 or more"</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>              ))</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs,<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">25.0</span> <span class="sc">~</span> <span class="st">"25% or Less"</span>,</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">50.0</span> <span class="sc">~</span> <span class="st">"25% to 50%"</span>,</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">75.0</span> <span class="sc">~</span> <span class="st">"50% to 75%"</span>,</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">100.0</span> <span class="sc">~</span> <span class="st">"75% or more"</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>              ))</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs, <span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"5 or fewer Students"</span>,</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"5 to 10 Students"</span>,</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">"10 to 15 Students"</span>,</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">"15 to 20 Students"</span>,</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">25</span> <span class="sc">~</span> <span class="st">"20 to 25 Students"</span>,</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"25 to 30 Students"</span>,</span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="dv">35</span> <span class="sc">~</span> <span class="st">"30 to 35 Students"</span>,</span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">35</span> <span class="sc">~</span> <span class="st">"35 or more Students"</span></span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs, <span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span> <span class="ot">=</span> (<span class="st">`</span><span class="at">AP_Score=1</span><span class="st">`</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span><span class="st">`</span><span class="at">AP_Score=2</span><span class="st">`</span> <span class="sc">+</span> <span class="dv">3</span><span class="sc">*</span><span class="st">`</span><span class="at">AP_Score=3</span><span class="st">`</span> <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span><span class="st">`</span><span class="at">AP_Score=4</span><span class="st">`</span> <span class="sc">+</span> <span class="dv">5</span><span class="sc">*</span><span class="st">`</span><span class="at">AP_Score=5</span><span class="st">`</span>)<span class="sc">/</span><span class="st">`</span><span class="at">AP_Tests Taken</span><span class="st">`</span>)</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs, <span class="st">`</span><span class="at">Average Cumulative SAT Score</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">Average SAT_Math</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Average SAT_Reading</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Average SAT_Writing</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="teacher-salary-category-first-glance" class="level2">
<h2 class="anchored" data-anchor-id="teacher-salary-category-first-glance">Teacher Salary Category First Glance</h2>
<p>These categories will be used to look at correlations of teacher salary and student success, while keeping some other key variables constant such as the percentage of economically disadvantaged or average class size. It’s also useful to break salary into brackets so see how student success is grouped across districts with different salaries.</p>
<p>Below are histograms visualizing graduation rates and AP test scores across different salary brackets:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Teacher Salary vs Graduation"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Teacher Salary vs AP Scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>At first glance, there does appear to be a slight trend upward in graduation rate as the average salary increases, but there is a much clearer trend in AP scores improving as average salary increases.</p>
<p>Both graphics have an outlier however in the 85000 to 90000 dollar range. This is because the Boston Public School District falls in this range and it includes many different schools which have various levels of socioeconomic diversity. We will be attempting to account for the variance across schools in Boston Public Schools by including more variables in our analysis and model, but it will also be useful to create a copy of our high school dataset which does not include Boston Public Schools.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>hs_WO_boston <span class="ot">&lt;-</span> <span class="fu">subset</span>(hs, <span class="sc">!</span>(<span class="st">`</span><span class="at">District Name</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Boston"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Below are the same histograms visualizing graduation rates and AP test scores across different salary brackets, but excluding Boston Public Schools:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Teacher Salary vs Graduation"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Teacher Salary vs AP Scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The exclusion of Boston Public Schools doesn’t yet appear to change the trend seen for graduation rate, but the trend for AP test scores become much clearer without Boston Public Schools, which is already suggestive of teacher salary being a predictor variable for student success.</p>
<p>Finally, it would be good to look at how economic disadvantage impact graduation rate, regardless of teacher salary:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Economically Disadvantaged vs Graduation"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The percentage of economically disadvantaged students in a school appears in the graphic above to be very strongly correlated to graduation rates, which is something we will keep an eye on in our analysis.</p>
</section>
<section id="multivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-analysis">Multivariate Analysis</h2>
<p>The box plots from the previous section are useful for demonstrating that we are moving in the right direction with our research question, and that a correlation might be uncovered with a deeper dive into our dataset. The box plots showed some evidence of a trend as salary increases, but there are other factors to consider, and we will create some multivariate visualizations to try and uncover them.</p>
<p>To begin, we’ll look into how salary is correlated with graduation rates while taking into account economic disadvantage and average class size:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Graduation Rate"</span>, </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Partitioned by Economic Disadvantage"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Graduation Rate"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Graduation Rate"</span>, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Partitioned by Class Size"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Graduation Rate"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When partitioning based on the percentage of economically disadvantaged students, a very clear trend begins to come to light. Across all four categories of economically disadvantaged students, there is a positively sloped line of best fit for salary being plotted against graduation rate. The same is not exactly true for average class size, which suggests that if class size does have an impact on student success, it does not make up as much of the variance as economic disadvantage does.</p>
<p>The subset of data which omits Boston Public Schools produces similar trends:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Graduation Rate(without Boston)"</span>, </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Partitioned by Economic Disadvantage"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Graduation Rate"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Graduation Rate(without Boston)"</span>, </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Partitioned by Class Size"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Graduation Rate"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The same positive trends appear across all four categories of economic disadvantage when Boston is omitted, but interestingly a much clearer trend appears for class size after omitting Boston Public Schools, with all seven categories producing positively sloped lines of best fit. This makes intuitive sense, as Boston Public Schools generally have more students and so we would need to take into account both average class size and economic disadvantages.</p>
<p>Another metric of student success which may be correlated with Teacher Salary are test scores. There will be less of an emphasis on class size for these graphics, as not all students take AP courses and not all schools will have classes dedicated to preparing for the SATs.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Average AP Scores"</span>, <span class="at">y =</span> <span class="st">"Average AP Scores"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average Cumulative SAT Score</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs SAT Scores"</span>, <span class="at">y =</span> <span class="st">"Average Cumulative SAT Score"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The trends for test scores aren’t as clear as the trends for graduation rate. However, there does seem to be a collection of low test scores for Boston Public Schools, so it might be worth examining the same trends for the subset without Boston Public Schools. It’s also important to note that there is a positive relationship in the group of schools with fewer than 25% of their students being economically disadvantaged. This could be explained by having a higher proportion of students who can afford tutors, test preparation courses and textbooks, and have more time to study for specific standardized tests outside of their normal coursework.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs AP Scores"</span>, <span class="at">y =</span> <span class="st">"Average AP Scores"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average Cumulative SAT Score</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs SAT Scores"</span>, <span class="at">y =</span> <span class="st">"Average Cumulative SAT Score"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="MatthewONeill_FinalPaper_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The trend for test scores improving as teacher salary improves among schools with a low proportion of economically disadvantaged students appears to become strong when omitting Boston Public schools. There still is not too much of a correlation one way or the other in schools with more students who are lower-income, which might suggest that regardless of teacher salary, students who are economically disadvantaged struggle more with standardized tests. This is a correlation that might be worth investigating deeper during research of the usefulness of standardized tests, but that is out of the scope of this paper.</p>
</section>
<section id="conclusions-from-multivariate-visuals" class="level2">
<h2 class="anchored" data-anchor-id="conclusions-from-multivariate-visuals">Conclusions From Multivariate Visuals</h2>
<p>It appears that there is a correlation between teacher salary and graduation rates of students, especially after holding socioeconomic factors constant. The percentage of economically disadvantaged students in a school produces very clear positive trend lines for the graduation rate improving as salary increases across all categories of economic disadvantage. This appears to be true with and without the Boston Public Schools outliers being included. The trends for the same correlation with class size held constant are smaller and less conclusive, but when omitting Boston Public Schools these trends again begin to show a correlation between average teacher salary and graduation rate.</p>
<p>There doesn’t appear to be as clear of a correlation between average teacher salary and test scores, particularly in our multivariate graphs which consider economic factors and class size. Some potential explanations for this include that not all students take AP or SAT tests, and that performing well on these tests often requires a fair bit of independent studying, often with a tutor or some sort of paid study guides.</p>
</section>
<section id="linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-model">Linear Regression Model</h2>
<p>Our first level of analysis was very high level, just looking at a box plot of graduation rates and test scores for different categories of teacher salary. There seemed to be some trend, so we investigated further with a multivariate analysis of how teacher salary across schools with similar percentages of economically disadvantaged students affects graduation rates and test scores. There was a very clear trend for graduation rates and the trends became even more positively sloped when omitting the outlier of Boston Public Schools.</p>
<p>To finish the analysis, I will be creating Linear Models for graduation rate using the three main variables that were explored so far, teacher salary, percentage of economically disadvantaged students, and class size) as predictor variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>linmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span> <span class="sc">~</span> hs<span class="sc">$</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span><span class="sc">+</span>hs<span class="sc">$</span><span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span><span class="sc">+</span>hs<span class="sc">$</span><span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = hs$`% Graduated` ~ hs$`Average Salary` + hs$`% Economically Disadvantaged` + 
    hs$`Average Class Size`)

Residuals:
    Min      1Q  Median      3Q     Max 
-60.330  -4.758  -0.264   5.833  41.791 

Coefficients:
                                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                        9.041e+01  6.297e+00  14.357  &lt; 2e-16 ***
hs$`Average Salary`               -2.368e-05  8.117e-05  -0.292    0.771    
hs$`% Economically Disadvantaged` -6.800e-01  3.278e-02 -20.741  &lt; 2e-16 ***
hs$`Average Class Size`            1.069e+00  1.964e-01   5.443 1.03e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.12 on 330 degrees of freedom
  (42 observations deleted due to missingness)
Multiple R-squared:  0.6573,    Adjusted R-squared:  0.6542 
F-statistic:   211 on 3 and 330 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The two big takeaways from this model is it has an R-square value of .6542, indicating that 65% of the variance in graduation rate can be explained by our model. The model also shows that the percentage of economically disadvantaged students and average class size have statistically significant impacts on graduation rate. Average salary does not appear to have as big of an impact in this model as we might’ve originally thought, but this is due to the other predictor variables making up a higher percentage of the variance in graduation rate.</p>
<p>To stay consistent, we will create the same model on the subset of data without Boston Public Schools:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>linmod_no_boston <span class="ot">&lt;-</span> <span class="fu">lm</span>(hs_WO_boston<span class="sc">$</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span> <span class="sc">~</span> hs_WO_boston<span class="sc">$</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span><span class="sc">+</span>hs_WO_boston<span class="sc">$</span><span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span><span class="sc">+</span>hs_WO_boston<span class="sc">$</span><span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linmod_no_boston)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = hs_WO_boston$`% Graduated` ~ hs_WO_boston$`Average Salary` + 
    hs_WO_boston$`% Economically Disadvantaged` + hs_WO_boston$`Average Class Size`)

Residuals:
    Min      1Q  Median      3Q     Max 
-58.985  -4.491  -0.261   5.088  41.307 

Coefficients:
                                              Estimate Std. Error t value
(Intercept)                                  9.215e+01  7.660e+00  12.029
hs_WO_boston$`Average Salary`               -3.260e-05  8.958e-05  -0.364
hs_WO_boston$`% Economically Disadvantaged` -6.808e-01  3.618e-02 -18.815
hs_WO_boston$`Average Class Size`            9.940e-01  2.081e-01   4.777
                                            Pr(&gt;|t|)    
(Intercept)                                  &lt; 2e-16 ***
hs_WO_boston$`Average Salary`                  0.716    
hs_WO_boston$`% Economically Disadvantaged`  &lt; 2e-16 ***
hs_WO_boston$`Average Class Size`           2.79e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11.12 on 299 degrees of freedom
  (42 observations deleted due to missingness)
Multiple R-squared:  0.6775,    Adjusted R-squared:  0.6743 
F-statistic: 209.4 on 3 and 299 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>When excluding Boston Public Schools, there is actually a slightly higher R-squared value of .6743, which means this model accounts for a slightly higher proportion of variance for graduation rate excluding Boston, but the p-value of each of the predictor variables is very similar.</p>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>Our multivariate visualizations suggest that increasing teacher salary is correlated with higher rates of graduation across schools with similar numbers of economically disadvantaged students, and similar average class sizes. Increasing teacher salaries does not currently appear to impact SAT or AP test scores, but this might be due to SAT and AP tests requiring a fair bit of studying and tutoring on top of normal classes.</p>
<p>Our linear regression models indicate however, that the percentage of economically disadvantaged is a much more statistically significant predictor of graduation rate than average teacher salary. Which does make sense sociologically, as regardless of the quality or number of teachers you have as a student, making ends meet is going to always take top priority over school work. Many economically disadvantaged students will need to work jobs after school, have less access to quality internet or technology, and be unable to afford extra study materials that more fortunate students may have access to.</p>
<p>However, teacher salary still does appear to play a significant role in student success when economic factors are held constant and it is much easier to improve teacher salaries than it is to reduce the number of economically disadvantaged students. Thus, it would be beneficial to students to increase the average salary of teachers in public schools.</p>
</section>
<section id="reflection" class="level2">
<h2 class="anchored" data-anchor-id="reflection">Reflection</h2>
<p>There are some limitations in my analysis, namely related to the broad scope of the dataset. Salaries are reported on a district by district basis, test scores are reported school wide, as is the percentage of economically disadvantaged students. In some ways, it can be beneficial to have a broad dataset, as it makes our analysis more widely applicable, but there could be a lot of variables which explain variance in student success that are hidden within these broad statistics.</p>
<p>This dataset is also limited in scope when it comes to location. It explores public school data in just one state in the United States. Philosophy on how to run public education varies widely across the country and each state is going to have different levels of economic disadvantage and tax budgets. The question we attempted to answer was on the broad scale of trying to provide statistical evidence to the claim that teachers should be paid more, but due to the scope of the dataset, this claim can only be statistically supported in the context of Massachusetts Public Schools.</p>
<p>Some questions I still have in regards to this topic after doing an analysis is if teacher salary must be increased across the United States, and what predictor variables play a significant role in the variance of individual student success.</p>
</section>
<section id="what-i-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-i-learned">What I Learned</h2>
<p>I learned a lot over the course of the past semester working on this project. At a low level, I learned to use R in a much more in depth way. Previously, my experience in R was limited to creating linear models and doing statistical analysis by hand using variables from the model. I had very limited data visualization experience before now and I had only ever worked with datasets that did not require any cleaning or mutating. I now feel like I have a much stronger grasp on data visualization and cleaning in R and I also know how to learn new things in R very quickly, which will make it easier to learn R in a deeper way in the future.</p>
<p>At a high level, I learned to transform a dataset in a way that is useful for solving a research question. Sometimes your data needs to be cleaned to make it useful, such as removing unneeded columns or rows which won’t contribute effectively to analysis. Once data is in a clean state, it will often require some mutation to get data in the form that would be most useful to your analysis. In my example, it made sense to categorize some of my variables to make comparison easier to understand visually.</p>
</section>
<section id="what-i-would-improve-in-the-future" class="level2">
<h2 class="anchored" data-anchor-id="what-i-would-improve-in-the-future">What I Would Improve In the Future</h2>
<p>My biggest regret for this project was not taking more time to vet my dataset at the beginning. I dove into analysis quickly after cleaning it, but I ended up being left without too many avenues of analysis to go down. In the future I would pose a research question as my first step after finding a dataset and do some simple visualizations to see if I’m on the right track. I also would like to work with a more challenging dataset in the future and integrate more types of visualizations in R.</p>
</section>
<section id="bibliography" class="level2">
<h2 class="anchored" data-anchor-id="bibliography">Bibliography</h2>
<p>[1] R Core Team (2022). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.</p>
<p>[2] H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.</p>
<p>[3] Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). “Welcome to the tidyverse.” <em>Journal of Open Source Software</em>, <em>4</em>(43), 1686. doi:10.21105/joss.01686 <a href="https://doi.org/10.21105/joss.01686" class="uri">https://doi.org/10.21105/joss.01686</a>.</p>
<p>[4] Massachusetts. Department of Education: Statewide Public School Reports 2017, https://profiles.doe.mass.edu/state_report/</p>
<p>[5] Wickham, H., &amp; Grolemund, G. (2016). R for data science: Visualize, model, transform, tidy, and import data. OReilly Media</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/601_Fall_2022" data-repo-id="R_kgDOH564Gw" data-category="Announcements" data-category-id="DIC_kwDOH564G84CRdBB" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb37" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Paper"</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Matthew O'Neill"</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "MA School Distict Data Exploration"</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "12/01/2022"</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - Final Paper</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - Matthew O'Neill</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - MA_Public_Schools_2017</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>,<span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>)</span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>I will be analyzing a dataset for Massachusetts public schools and districts. The dataset was collected from the 2017 academic year and is a combination of several smaller datasets reported by all 288 public school districts in Massachusetts to the Massachusetts Department of Education. Each of the 376 rows of the dataset represents a high school and each school contains socioeconomic data(e.g. % economically disadvantaged, % African American, % White, etc) along with outcomes of students from those schools(% graduated, % pursuing college/university). Test scores(e.g. SAT, AP, MCAS) are also collected and can be used as a secondary metric of student success. Finally, the data includes school finances(e.g. teacher salary, district expenditures) which will be the primary focus of our analysis as predictor variables for student success. Schools in the dataset range from elementary to high school, but I will be working with just the subset of high schools. </span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>I will be making the scope of my analysis more narrow and focus solely on high schools, and as such, many of the MCAS related columns can be omitted to make the dataset easier to work with. The focus of my analysis will be how spending can affect test scores and graduation rates.</span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Central Question</span></span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>Different school districts vary widely when it comes to how their schools are funded and how their teachers are compensated. Much of the data on how school districts spend their money is public, we can be useful for an analysis of the factors which can lead to better outcomes among students in public schools.</span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-41"><a href="#cb37-41" aria-hidden="true" tabindex="-1"></a>The central question investigated in this paper is: does increasing teacher salary in public schools impact the success of students? Student success will be defined primarily by higher graduation rates but we will also look into higher test scores as a metric of success. During the process of exploring this question, we will also be exploring how the economic background of students and class size impacts school success, especially in conjunction with average teacher salary.</span>
<span id="cb37-42"><a href="#cb37-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-43"><a href="#cb37-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-44"><a href="#cb37-44" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Cleaning</span></span>
<span id="cb37-45"><a href="#cb37-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-46"><a href="#cb37-46" aria-hidden="true" tabindex="-1"></a>The dataset is in fairly nice shape to begin with, but we are only interested in a small portion of the original 300 columns of data and since we are only interested in high schools, we can safely omit Elementary and Middle schools which do not report a Graduation rate. </span>
<span id="cb37-47"><a href="#cb37-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-50"><a href="#cb37-50" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-51"><a href="#cb37-51" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/MA_Public_Schools_2017.csv"</span>,<span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-52"><a href="#cb37-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-53"><a href="#cb37-53" aria-hidden="true" tabindex="-1"></a>keeps <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">10</span>,<span class="dv">13</span>,<span class="dv">14</span>,<span class="dv">15</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">28</span>,<span class="dv">29</span>,<span class="dv">30</span>,<span class="dv">31</span>,<span class="dv">32</span>,<span class="dv">34</span>,<span class="dv">36</span>,<span class="dv">38</span>,<span class="dv">40</span>,<span class="dv">41</span>,<span class="dv">42</span>,<span class="dv">43</span>,<span class="dv">44</span>,<span class="dv">45</span>,<span class="dv">46</span>,<span class="dv">47</span>,<span class="dv">48</span>,<span class="dv">49</span>,<span class="dv">50</span>,<span class="dv">51</span>,<span class="dv">52</span>,<span class="dv">53</span>,<span class="dv">55</span>,<span class="dv">62</span>,<span class="dv">64</span>,<span class="dv">68</span>,<span class="dv">70</span>,<span class="dv">71</span>,<span class="dv">72</span>,<span class="dv">80</span>,<span class="dv">81</span>,<span class="dv">82</span>,<span class="dv">83</span>,<span class="dv">84</span>,<span class="dv">85</span>,<span class="dv">86</span>,<span class="dv">87</span>,<span class="dv">88</span>,<span class="dv">89</span>,<span class="dv">90</span>,<span class="dv">91</span>,<span class="dv">92</span>,<span class="dv">93</span>,<span class="dv">94</span>,<span class="dv">95</span>,<span class="dv">96</span>,<span class="dv">97</span>)</span>
<span id="cb37-54"><a href="#cb37-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-55"><a href="#cb37-55" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> data[keeps]<span class="sc">%&gt;%</span> </span>
<span id="cb37-56"><a href="#cb37-56" aria-hidden="true" tabindex="-1"></a>      <span class="fu">subset</span>(<span class="sc">!</span> <span class="fu">is.na</span>(data<span class="sc">$</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>))</span>
<span id="cb37-57"><a href="#cb37-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-58"><a href="#cb37-58" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(hs)</span>
<span id="cb37-59"><a href="#cb37-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-60"><a href="#cb37-60" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">District Code</span><span class="st">`</span>))</span>
<span id="cb37-61"><a href="#cb37-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-62"><a href="#cb37-62" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-63"><a href="#cb37-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-64"><a href="#cb37-64" aria-hidden="true" tabindex="-1"></a>After slimming down the dataset to only contain necessary data there are 376 rows, representing 376 Massachusetts high schools, and 53 columns of useful data for each. There are also 288 unique district codes, as larger districts have more than one high school. Districts are important to our central question because most districts have standardized pay scales and multiple schools in the same district will be reported to have the same average salary. </span>
<span id="cb37-65"><a href="#cb37-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-66"><a href="#cb37-66" aria-hidden="true" tabindex="-1"></a>The variables that I am interested in specifically from this dataset are Average Teacher Salary, Graduation Rates, SAT Scores, Average AP Test Scores, Average Class Sizes, and percentage of students who are economically disadvantaged. The last of these may be the most important to our analysis, as economically disadvantaged students will have a harder time in school regardless of teacher salary, so we need to compare across schools with a similar proportion of economically disadvantaged students.</span>
<span id="cb37-67"><a href="#cb37-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-68"><a href="#cb37-68" aria-hidden="true" tabindex="-1"></a>Average teacher salary is reported by district, which is unfortunate of our analysis as some districts have many schools which can vary in performance. However, the only real outlier in regards to this issue is Boston Public Schools. For this reason, our analysis will be done on Massachusetts as a whole, and Massachusetts excluding Boston Public schools. Teacher salary will be the focus of the analysis, as if a correlation with salary can be shown to affect student success then real steps could be taken by policy makers to improve student success by increasing teacher salary. Similarly, if a correlation with class size and student success can be shown, steps could be taken to hire more teachers, thus reducing the average class size.</span>
<span id="cb37-69"><a href="#cb37-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-70"><a href="#cb37-70" aria-hidden="true" tabindex="-1"></a>The percent of economically disadvantaged students in each school will not be explored much explicitly when it comes to predicting student success, but it is very important to the analysis of teacher salary, as it plays a role in explaining some of the variance in the most trivial model of student success with teacher salary.</span>
<span id="cb37-71"><a href="#cb37-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-72"><a href="#cb37-72" aria-hidden="true" tabindex="-1"></a>Since our focus is primarily high school students, the metrics for success will be primarily Graduation rates, AP Scores, and SAT Scores. Graduation rates are recorded across the board, but not every student takes the SATs or AP tests, which can skew the average scores. More specifically, economically disadvantaged students and students who are already performing poorly in school are less likely to pay for these courses, so while we will explore how teacher salary affects these metrics, the focus will be on graduation rates.</span>
<span id="cb37-73"><a href="#cb37-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-74"><a href="#cb37-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-77"><a href="#cb37-77" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-78"><a href="#cb37-78" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Average Salary Breakdown"</span>)</span>
<span id="cb37-79"><a href="#cb37-79" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb37-80"><a href="#cb37-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-81"><a href="#cb37-81" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Graduation Rates Breakdown"</span>)</span>
<span id="cb37-82"><a href="#cb37-82" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb37-83"><a href="#cb37-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-84"><a href="#cb37-84" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Percentage Economically Disadvantaged Breakdown"</span>)</span>
<span id="cb37-85"><a href="#cb37-85" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb37-86"><a href="#cb37-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-87"><a href="#cb37-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-88"><a href="#cb37-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-89"><a href="#cb37-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-90"><a href="#cb37-90" aria-hidden="true" tabindex="-1"></a>After taking a very short look into some summary statistics for some of the variables we will be diving into, it appears that the average teacher salary across the state is $74000, without too much variance. Graduation rates average 83% statewide but this number appears to be skewed as the median is a fair bit higher at 92%. The percentage of economically disadvantages students in a given school also appears to be skewed a bit by outliers, as the average statewide is 30% but the median is 25.5%, indicating that there are some schools with a very high percentage of economically disadvantaged students.</span>
<span id="cb37-91"><a href="#cb37-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-92"><a href="#cb37-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## Mutation</span></span>
<span id="cb37-93"><a href="#cb37-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-94"><a href="#cb37-94" aria-hidden="true" tabindex="-1"></a>Working with the data can be made a lot easier by partitioning some of the variables we're interested in into sections. For teacher salary, average expenditure, class size, and percentage of economically disadvantaged students, I will be creating a categorical variable placing schools into various brackets of each variable. This will make correlations a bit more clear as there is not necessarily a clear trend across all schools when it comes to student performance when plotted against any of these variables individually.</span>
<span id="cb37-95"><a href="#cb37-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-96"><a href="#cb37-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-99"><a href="#cb37-99" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-100"><a href="#cb37-100" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs,<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb37-101"><a href="#cb37-101" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">55000</span> <span class="sc">~</span> <span class="st">"$55000 or Less"</span>,</span>
<span id="cb37-102"><a href="#cb37-102" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">60000</span> <span class="sc">~</span> <span class="st">"$55000 to $60000"</span>,</span>
<span id="cb37-103"><a href="#cb37-103" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">65000</span> <span class="sc">~</span> <span class="st">"$60000 to $65000"</span>,</span>
<span id="cb37-104"><a href="#cb37-104" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">70000</span> <span class="sc">~</span> <span class="st">"$65000 to $70000"</span>,</span>
<span id="cb37-105"><a href="#cb37-105" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">75000</span> <span class="sc">~</span> <span class="st">"$70000 to $75000"</span>,</span>
<span id="cb37-106"><a href="#cb37-106" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">80000</span> <span class="sc">~</span> <span class="st">"$75000 to $80000"</span>,</span>
<span id="cb37-107"><a href="#cb37-107" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">85000</span> <span class="sc">~</span> <span class="st">"$80000 to $85000"</span>,</span>
<span id="cb37-108"><a href="#cb37-108" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="dv">90000</span> <span class="sc">~</span> <span class="st">"$85000 to $90000"</span>,</span>
<span id="cb37-109"><a href="#cb37-109" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">90000</span> <span class="sc">~</span> <span class="st">"$90000 or more"</span></span>
<span id="cb37-110"><a href="#cb37-110" aria-hidden="true" tabindex="-1"></a>              ))</span>
<span id="cb37-111"><a href="#cb37-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-112"><a href="#cb37-112" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs,<span class="st">`</span><span class="at">Per Pupil Expenditure Bracket</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb37-113"><a href="#cb37-113" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">12500</span> <span class="sc">~</span> <span class="st">"$12500 or Less"</span>,</span>
<span id="cb37-114"><a href="#cb37-114" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">15000</span> <span class="sc">~</span> <span class="st">"$12500 to $15000"</span>,</span>
<span id="cb37-115"><a href="#cb37-115" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">17500</span> <span class="sc">~</span> <span class="st">"$15000 to $17500"</span>,</span>
<span id="cb37-116"><a href="#cb37-116" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">20000</span> <span class="sc">~</span> <span class="st">"$17500 to $20000"</span>,</span>
<span id="cb37-117"><a href="#cb37-117" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">22500</span> <span class="sc">~</span> <span class="st">"$20000 to $22500"</span>,</span>
<span id="cb37-118"><a href="#cb37-118" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="dv">25000</span> <span class="sc">~</span> <span class="st">"$22500 to $25000"</span>,</span>
<span id="cb37-119"><a href="#cb37-119" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Expenditures per Pupil</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">25000</span> <span class="sc">~</span> <span class="st">"$25000 or more"</span></span>
<span id="cb37-120"><a href="#cb37-120" aria-hidden="true" tabindex="-1"></a>              ))</span>
<span id="cb37-121"><a href="#cb37-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-122"><a href="#cb37-122" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs,<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb37-123"><a href="#cb37-123" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">25.0</span> <span class="sc">~</span> <span class="st">"25% or Less"</span>,</span>
<span id="cb37-124"><a href="#cb37-124" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">50.0</span> <span class="sc">~</span> <span class="st">"25% to 50%"</span>,</span>
<span id="cb37-125"><a href="#cb37-125" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">75.0</span> <span class="sc">~</span> <span class="st">"50% to 75%"</span>,</span>
<span id="cb37-126"><a href="#cb37-126" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="fl">100.0</span> <span class="sc">~</span> <span class="st">"75% or more"</span></span>
<span id="cb37-127"><a href="#cb37-127" aria-hidden="true" tabindex="-1"></a>              ))</span>
<span id="cb37-128"><a href="#cb37-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-129"><a href="#cb37-129" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs, <span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb37-130"><a href="#cb37-130" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"5 or fewer Students"</span>,</span>
<span id="cb37-131"><a href="#cb37-131" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"5 to 10 Students"</span>,</span>
<span id="cb37-132"><a href="#cb37-132" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">"10 to 15 Students"</span>,</span>
<span id="cb37-133"><a href="#cb37-133" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">"15 to 20 Students"</span>,</span>
<span id="cb37-134"><a href="#cb37-134" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">25</span> <span class="sc">~</span> <span class="st">"20 to 25 Students"</span>,</span>
<span id="cb37-135"><a href="#cb37-135" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"25 to 30 Students"</span>,</span>
<span id="cb37-136"><a href="#cb37-136" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="dv">35</span> <span class="sc">~</span> <span class="st">"30 to 35 Students"</span>,</span>
<span id="cb37-137"><a href="#cb37-137" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">35</span> <span class="sc">~</span> <span class="st">"35 or more Students"</span></span>
<span id="cb37-138"><a href="#cb37-138" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb37-139"><a href="#cb37-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-140"><a href="#cb37-140" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs, <span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span> <span class="ot">=</span> (<span class="st">`</span><span class="at">AP_Score=1</span><span class="st">`</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span><span class="st">`</span><span class="at">AP_Score=2</span><span class="st">`</span> <span class="sc">+</span> <span class="dv">3</span><span class="sc">*</span><span class="st">`</span><span class="at">AP_Score=3</span><span class="st">`</span> <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span><span class="st">`</span><span class="at">AP_Score=4</span><span class="st">`</span> <span class="sc">+</span> <span class="dv">5</span><span class="sc">*</span><span class="st">`</span><span class="at">AP_Score=5</span><span class="st">`</span>)<span class="sc">/</span><span class="st">`</span><span class="at">AP_Tests Taken</span><span class="st">`</span>)</span>
<span id="cb37-141"><a href="#cb37-141" aria-hidden="true" tabindex="-1"></a>hs <span class="ot">&lt;-</span> <span class="fu">mutate</span>(hs, <span class="st">`</span><span class="at">Average Cumulative SAT Score</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">Average SAT_Math</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Average SAT_Reading</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Average SAT_Writing</span><span class="st">`</span>)</span>
<span id="cb37-142"><a href="#cb37-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-143"><a href="#cb37-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-144"><a href="#cb37-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-145"><a href="#cb37-145" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-146"><a href="#cb37-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-147"><a href="#cb37-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## Teacher Salary Category First Glance</span></span>
<span id="cb37-148"><a href="#cb37-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-149"><a href="#cb37-149" aria-hidden="true" tabindex="-1"></a>These categories will be used to look at correlations of teacher salary and student success, while keeping some other key variables constant such as the percentage of economically disadvantaged or average class size. It's also useful to break salary into brackets so see how student success is grouped across districts with different salaries. </span>
<span id="cb37-150"><a href="#cb37-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-151"><a href="#cb37-151" aria-hidden="true" tabindex="-1"></a>Below are histograms visualizing graduation rates and AP test scores across different salary brackets:</span>
<span id="cb37-152"><a href="#cb37-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-153"><a href="#cb37-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-156"><a href="#cb37-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-157"><a href="#cb37-157" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb37-158"><a href="#cb37-158" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb37-159"><a href="#cb37-159" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb37-160"><a href="#cb37-160" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb37-161"><a href="#cb37-161" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb37-162"><a href="#cb37-162" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb37-163"><a href="#cb37-163" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb37-164"><a href="#cb37-164" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb37-165"><a href="#cb37-165" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Teacher Salary vs Graduation"</span>)</span>
<span id="cb37-166"><a href="#cb37-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-167"><a href="#cb37-167" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb37-168"><a href="#cb37-168" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb37-169"><a href="#cb37-169" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb37-170"><a href="#cb37-170" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb37-171"><a href="#cb37-171" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb37-172"><a href="#cb37-172" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb37-173"><a href="#cb37-173" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb37-174"><a href="#cb37-174" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb37-175"><a href="#cb37-175" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Teacher Salary vs AP Scores"</span>)</span>
<span id="cb37-176"><a href="#cb37-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-177"><a href="#cb37-177" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-178"><a href="#cb37-178" aria-hidden="true" tabindex="-1"></a>At first glance, there does appear to be a slight trend upward in graduation rate as the average salary increases, but there is a much clearer trend in AP scores improving as average salary increases. </span>
<span id="cb37-179"><a href="#cb37-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-180"><a href="#cb37-180" aria-hidden="true" tabindex="-1"></a>Both graphics have an outlier however in the 85000 to 90000 dollar range. This is because the Boston Public School District falls in this range and it includes many different schools which have various levels of socioeconomic diversity. We will be attempting to account for the variance across schools in Boston Public Schools by including more variables in our analysis and model, but it will also be useful to create a copy of our high school dataset which does not include Boston Public Schools. </span>
<span id="cb37-181"><a href="#cb37-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-184"><a href="#cb37-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-185"><a href="#cb37-185" aria-hidden="true" tabindex="-1"></a>hs_WO_boston <span class="ot">&lt;-</span> <span class="fu">subset</span>(hs, <span class="sc">!</span>(<span class="st">`</span><span class="at">District Name</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Boston"</span>))</span>
<span id="cb37-186"><a href="#cb37-186" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-187"><a href="#cb37-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-188"><a href="#cb37-188" aria-hidden="true" tabindex="-1"></a>Below are the same histograms visualizing graduation rates and AP test scores across different salary brackets, but excluding Boston Public Schools:</span>
<span id="cb37-189"><a href="#cb37-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-192"><a href="#cb37-192" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-193"><a href="#cb37-193" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb37-194"><a href="#cb37-194" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb37-195"><a href="#cb37-195" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb37-196"><a href="#cb37-196" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb37-197"><a href="#cb37-197" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb37-198"><a href="#cb37-198" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb37-199"><a href="#cb37-199" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb37-200"><a href="#cb37-200" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb37-201"><a href="#cb37-201" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Teacher Salary vs Graduation"</span>)</span>
<span id="cb37-202"><a href="#cb37-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-203"><a href="#cb37-203" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Salary Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb37-204"><a href="#cb37-204" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb37-205"><a href="#cb37-205" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb37-206"><a href="#cb37-206" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb37-207"><a href="#cb37-207" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb37-208"><a href="#cb37-208" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb37-209"><a href="#cb37-209" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb37-210"><a href="#cb37-210" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb37-211"><a href="#cb37-211" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Teacher Salary vs AP Scores"</span>)</span>
<span id="cb37-212"><a href="#cb37-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-213"><a href="#cb37-213" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-214"><a href="#cb37-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-215"><a href="#cb37-215" aria-hidden="true" tabindex="-1"></a>The exclusion of Boston Public Schools doesn't yet appear to change the trend seen for graduation rate, but the trend for AP test scores become much clearer without Boston Public Schools, which is already suggestive of teacher salary being a predictor variable for student success.</span>
<span id="cb37-216"><a href="#cb37-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-217"><a href="#cb37-217" aria-hidden="true" tabindex="-1"></a>Finally, it would be good to look at how economic disadvantage impact graduation rate, regardless of teacher salary:</span>
<span id="cb37-218"><a href="#cb37-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-221"><a href="#cb37-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-222"><a href="#cb37-222" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>, <span class="at">fill=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb37-223"><a href="#cb37-223" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()  <span class="sc">+</span></span>
<span id="cb37-224"><a href="#cb37-224" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb37-225"><a href="#cb37-225" aria-hidden="true" tabindex="-1"></a>      <span class="at">legend.position=</span><span class="st">"right"</span>,</span>
<span id="cb37-226"><a href="#cb37-226" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>),</span>
<span id="cb37-227"><a href="#cb37-227" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x=</span><span class="fu">element_blank</span>(),</span>
<span id="cb37-228"><a href="#cb37-228" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()</span>
<span id="cb37-229"><a href="#cb37-229" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb37-230"><a href="#cb37-230" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Economically Disadvantaged vs Graduation"</span>)</span>
<span id="cb37-231"><a href="#cb37-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-232"><a href="#cb37-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-233"><a href="#cb37-233" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-234"><a href="#cb37-234" aria-hidden="true" tabindex="-1"></a>The percentage of economically disadvantaged students in a school appears in the graphic above to be very strongly correlated to graduation rates, which is something we will keep an eye on in our analysis.</span>
<span id="cb37-235"><a href="#cb37-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-236"><a href="#cb37-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-237"><a href="#cb37-237" aria-hidden="true" tabindex="-1"></a><span class="fu">## Multivariate Analysis</span></span>
<span id="cb37-238"><a href="#cb37-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-239"><a href="#cb37-239" aria-hidden="true" tabindex="-1"></a>The box plots from the previous section are useful for demonstrating that we are moving in the right direction with our research question, and that a correlation might be uncovered with a deeper dive into our dataset. The box plots showed some evidence of a trend as salary increases, but there are other factors to consider, and we will create some multivariate visualizations to try and uncover them.</span>
<span id="cb37-240"><a href="#cb37-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-241"><a href="#cb37-241" aria-hidden="true" tabindex="-1"></a>To begin, we'll look into how salary is correlated with graduation rates while taking into account economic disadvantage and average class size:</span>
<span id="cb37-242"><a href="#cb37-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-245"><a href="#cb37-245" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-246"><a href="#cb37-246" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb37-247"><a href="#cb37-247" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-248"><a href="#cb37-248" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-249"><a href="#cb37-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Graduation Rate"</span>, </span>
<span id="cb37-250"><a href="#cb37-250" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Partitioned by Economic Disadvantage"</span>,</span>
<span id="cb37-251"><a href="#cb37-251" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Graduation Rate"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span>
<span id="cb37-252"><a href="#cb37-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-253"><a href="#cb37-253" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb37-254"><a href="#cb37-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-255"><a href="#cb37-255" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-256"><a href="#cb37-256" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Graduation Rate"</span>, </span>
<span id="cb37-257"><a href="#cb37-257" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Partitioned by Class Size"</span>,</span>
<span id="cb37-258"><a href="#cb37-258" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Graduation Rate"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span>
<span id="cb37-259"><a href="#cb37-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-260"><a href="#cb37-260" aria-hidden="true" tabindex="-1"></a>When partitioning based on the percentage of economically disadvantaged students, a very clear trend begins to come to light. Across all four categories of economically disadvantaged students, there is a positively sloped line of best fit for salary being plotted against graduation rate. The same is not exactly true for average class size, which suggests that if class size does have an impact on student success, it does not make up as much of the variance as economic disadvantage does.</span>
<span id="cb37-261"><a href="#cb37-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-262"><a href="#cb37-262" aria-hidden="true" tabindex="-1"></a>The subset of data which omits Boston Public Schools produces similar trends:</span>
<span id="cb37-263"><a href="#cb37-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-266"><a href="#cb37-266" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-267"><a href="#cb37-267" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb37-268"><a href="#cb37-268" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-269"><a href="#cb37-269" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-270"><a href="#cb37-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Graduation Rate(without Boston)"</span>, </span>
<span id="cb37-271"><a href="#cb37-271" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Partitioned by Economic Disadvantage"</span>,</span>
<span id="cb37-272"><a href="#cb37-272" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Graduation Rate"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span>
<span id="cb37-273"><a href="#cb37-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-274"><a href="#cb37-274" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Class Size Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb37-275"><a href="#cb37-275" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-276"><a href="#cb37-276" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-277"><a href="#cb37-277" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Graduation Rate(without Boston)"</span>, </span>
<span id="cb37-278"><a href="#cb37-278" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Partitioned by Class Size"</span>,</span>
<span id="cb37-279"><a href="#cb37-279" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Graduation Rate"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span>
<span id="cb37-280"><a href="#cb37-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-281"><a href="#cb37-281" aria-hidden="true" tabindex="-1"></a>The same positive trends appear across all four categories of economic disadvantage when Boston is omitted, but interestingly a much clearer trend appears for class size after omitting Boston Public Schools, with all seven categories producing positively sloped lines of best fit. This makes intuitive sense, as Boston Public Schools generally have more students and so we would need to take into account both average class size and economic disadvantages.</span>
<span id="cb37-282"><a href="#cb37-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-283"><a href="#cb37-283" aria-hidden="true" tabindex="-1"></a>Another metric of student success which may be correlated with Teacher Salary are test scores. There will be less of an emphasis on class size for these graphics, as not all students take AP courses and not all schools will have classes dedicated to preparing for the SATs.</span>
<span id="cb37-284"><a href="#cb37-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-287"><a href="#cb37-287" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-288"><a href="#cb37-288" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb37-289"><a href="#cb37-289" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-290"><a href="#cb37-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-291"><a href="#cb37-291" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs Average AP Scores"</span>, <span class="at">y =</span> <span class="st">"Average AP Scores"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span>
<span id="cb37-292"><a href="#cb37-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-293"><a href="#cb37-293" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average Cumulative SAT Score</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb37-294"><a href="#cb37-294" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-295"><a href="#cb37-295" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-296"><a href="#cb37-296" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs SAT Scores"</span>, <span class="at">y =</span> <span class="st">"Average Cumulative SAT Score"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span>
<span id="cb37-297"><a href="#cb37-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-298"><a href="#cb37-298" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-299"><a href="#cb37-299" aria-hidden="true" tabindex="-1"></a>The trends for test scores aren't as clear as the trends for graduation rate. However, there does seem to be a collection of low test scores for Boston Public Schools, so it might be worth examining the same trends for the subset without Boston Public Schools. It's also important to note that there is a positive relationship in the group of schools with fewer than 25% of their students being economically disadvantaged. This could be explained by having a higher proportion of students who can afford tutors, test preparation courses and textbooks, and have more time to study for specific standardized tests outside of their normal coursework.</span>
<span id="cb37-300"><a href="#cb37-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-303"><a href="#cb37-303" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-304"><a href="#cb37-304" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average AP Score</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb37-305"><a href="#cb37-305" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-306"><a href="#cb37-306" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-307"><a href="#cb37-307" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs AP Scores"</span>, <span class="at">y =</span> <span class="st">"Average AP Scores"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span>
<span id="cb37-308"><a href="#cb37-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-309"><a href="#cb37-309" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">subset</span>(hs_WO_boston,<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)), <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Average Cumulative SAT Score</span><span class="st">`</span>,<span class="at">color=</span><span class="st">`</span><span class="at">Economically Disadvantaged Bracket</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb37-310"><a href="#cb37-310" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-311"><a href="#cb37-311" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb37-312"><a href="#cb37-312" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Average Teacher Salary vs SAT Scores"</span>, <span class="at">y =</span> <span class="st">"Average Cumulative SAT Score"</span>, <span class="at">x =</span> <span class="st">"Average Teacher Salary"</span>)</span>
<span id="cb37-313"><a href="#cb37-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-314"><a href="#cb37-314" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-315"><a href="#cb37-315" aria-hidden="true" tabindex="-1"></a>The trend for test scores improving as teacher salary improves among schools with a low proportion of economically disadvantaged students appears to become strong when omitting Boston Public schools. There still is not too much of a correlation one way or the other in schools with more students who are lower-income, which might suggest that regardless of teacher salary, students who are economically disadvantaged struggle more with standardized tests. This is a correlation that might be worth investigating deeper during research of the usefulness of standardized tests, but that is out of the scope of this paper.</span>
<span id="cb37-316"><a href="#cb37-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-317"><a href="#cb37-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-318"><a href="#cb37-318" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusions From Multivariate Visuals</span></span>
<span id="cb37-319"><a href="#cb37-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-320"><a href="#cb37-320" aria-hidden="true" tabindex="-1"></a>It appears that there is a correlation between teacher salary and graduation rates of students, especially after holding socioeconomic factors constant. The percentage of economically disadvantaged students in a school produces very clear positive trend lines for the graduation rate improving as salary increases across all categories of economic disadvantage. This appears to be true with and without the Boston Public Schools outliers being included. The trends for the same correlation with class size held constant are smaller and less conclusive, but when omitting Boston Public Schools these trends again begin to show a correlation between average teacher salary and graduation rate.</span>
<span id="cb37-321"><a href="#cb37-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-322"><a href="#cb37-322" aria-hidden="true" tabindex="-1"></a>There doesn't appear to be as clear of a correlation between average teacher salary and test scores, particularly in our multivariate graphs which consider economic factors and class size. Some potential explanations for this include that not all students take AP or SAT tests, and that performing well on these tests often requires a fair bit of independent studying, often with a tutor or some sort of paid study guides.</span>
<span id="cb37-323"><a href="#cb37-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-324"><a href="#cb37-324" aria-hidden="true" tabindex="-1"></a><span class="fu">## Linear Regression Model</span></span>
<span id="cb37-325"><a href="#cb37-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-326"><a href="#cb37-326" aria-hidden="true" tabindex="-1"></a>Our first level of analysis was very high level, just looking at a box plot of graduation rates and test scores for different categories of teacher salary. There seemed to be some trend, so we investigated further with a multivariate analysis of how teacher salary across schools with similar percentages of economically disadvantaged students affects graduation rates and test scores. There was a very clear trend for graduation rates and the trends became even more positively sloped when omitting the outlier of Boston Public Schools.</span>
<span id="cb37-327"><a href="#cb37-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-328"><a href="#cb37-328" aria-hidden="true" tabindex="-1"></a>To finish the analysis, I will be creating Linear Models for graduation rate using the three main variables that were explored so far, teacher salary, percentage of economically disadvantaged students, and class size) as predictor variables.</span>
<span id="cb37-329"><a href="#cb37-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-330"><a href="#cb37-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-333"><a href="#cb37-333" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-334"><a href="#cb37-334" aria-hidden="true" tabindex="-1"></a>linmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(hs<span class="sc">$</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span> <span class="sc">~</span> hs<span class="sc">$</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span><span class="sc">+</span>hs<span class="sc">$</span><span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span><span class="sc">+</span>hs<span class="sc">$</span><span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span>)</span>
<span id="cb37-335"><a href="#cb37-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-336"><a href="#cb37-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-337"><a href="#cb37-337" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linmod)</span>
<span id="cb37-338"><a href="#cb37-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-339"><a href="#cb37-339" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-340"><a href="#cb37-340" aria-hidden="true" tabindex="-1"></a>The two big takeaways from this model is it has an R-square value of .6542, indicating that 65% of the variance in graduation rate can be explained by our model. The model also shows that the percentage of economically disadvantaged students and average class size have statistically significant impacts on graduation rate. Average salary does not appear to have as big of an impact in this model as we might've originally thought, but this is due to the other predictor variables making up a higher percentage of the variance in graduation rate.</span>
<span id="cb37-341"><a href="#cb37-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-342"><a href="#cb37-342" aria-hidden="true" tabindex="-1"></a>To stay consistent, we will create the same model on the subset of data without Boston Public Schools:</span>
<span id="cb37-343"><a href="#cb37-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-346"><a href="#cb37-346" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-347"><a href="#cb37-347" aria-hidden="true" tabindex="-1"></a>linmod_no_boston <span class="ot">&lt;-</span> <span class="fu">lm</span>(hs_WO_boston<span class="sc">$</span><span class="st">`</span><span class="at">% Graduated</span><span class="st">`</span> <span class="sc">~</span> hs_WO_boston<span class="sc">$</span><span class="st">`</span><span class="at">Average Salary</span><span class="st">`</span><span class="sc">+</span>hs_WO_boston<span class="sc">$</span><span class="st">`</span><span class="at">% Economically Disadvantaged</span><span class="st">`</span><span class="sc">+</span>hs_WO_boston<span class="sc">$</span><span class="st">`</span><span class="at">Average Class Size</span><span class="st">`</span>)</span>
<span id="cb37-348"><a href="#cb37-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-349"><a href="#cb37-349" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linmod_no_boston)</span>
<span id="cb37-350"><a href="#cb37-350" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-351"><a href="#cb37-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-352"><a href="#cb37-352" aria-hidden="true" tabindex="-1"></a>When excluding Boston Public Schools, there is actually a slightly higher R-squared value of .6743, which means this model accounts for a slightly higher proportion of variance for graduation rate excluding Boston, but the p-value of each of the predictor variables is very similar.</span>
<span id="cb37-353"><a href="#cb37-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-354"><a href="#cb37-354" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusions</span></span>
<span id="cb37-355"><a href="#cb37-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-356"><a href="#cb37-356" aria-hidden="true" tabindex="-1"></a>Our multivariate visualizations suggest that increasing teacher salary is correlated with higher rates of graduation across schools with similar numbers of economically disadvantaged students, and similar average class sizes. Increasing teacher salaries does not currently appear to impact SAT or AP test scores, but this might be due to SAT and AP tests requiring a fair bit of studying and tutoring on top of normal classes.</span>
<span id="cb37-357"><a href="#cb37-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-358"><a href="#cb37-358" aria-hidden="true" tabindex="-1"></a>Our linear regression models indicate however, that the percentage of economically disadvantaged is a much more statistically significant predictor of graduation rate than average teacher salary. Which does make sense sociologically, as regardless of the quality or number of teachers you have as a student, making ends meet is going to always take top priority over school work. Many economically disadvantaged students will need to work jobs after school, have less access to quality internet or technology, and be unable to afford extra study materials that more fortunate students may have access to.</span>
<span id="cb37-359"><a href="#cb37-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-360"><a href="#cb37-360" aria-hidden="true" tabindex="-1"></a>However, teacher salary still does appear to play a significant role in student success when economic factors are held constant and it is much easier to improve teacher salaries than it is to reduce the number of economically disadvantaged students. Thus, it would be beneficial to students to increase the average salary of teachers in public schools.</span>
<span id="cb37-361"><a href="#cb37-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-362"><a href="#cb37-362" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reflection</span></span>
<span id="cb37-363"><a href="#cb37-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-364"><a href="#cb37-364" aria-hidden="true" tabindex="-1"></a>There are some limitations in my analysis, namely related to the broad scope of the dataset. Salaries are reported on a district by district basis, test scores are reported school wide, as is the percentage of economically disadvantaged students. In some ways, it can be beneficial to have a broad dataset, as it makes our analysis more widely applicable, but there could be a lot of variables which explain variance in student success that are hidden within these broad statistics.</span>
<span id="cb37-365"><a href="#cb37-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-366"><a href="#cb37-366" aria-hidden="true" tabindex="-1"></a>This dataset is also limited in scope when it comes to location. It explores public school data in just one state in the United States. Philosophy on how to run public education varies widely across the country and each state is going to have different levels of economic disadvantage and tax budgets. The question we attempted to answer was on the broad scale of trying to provide statistical evidence to the claim that teachers should be paid more, but due to the scope of the dataset, this claim can only be statistically supported in the context of Massachusetts Public Schools.</span>
<span id="cb37-367"><a href="#cb37-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-368"><a href="#cb37-368" aria-hidden="true" tabindex="-1"></a>Some questions I still have in regards to this topic after doing an analysis is if teacher salary must be increased across the United States, and what predictor variables play a significant role in the variance of individual student success.  </span>
<span id="cb37-369"><a href="#cb37-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-370"><a href="#cb37-370" aria-hidden="true" tabindex="-1"></a><span class="fu">## What I Learned</span></span>
<span id="cb37-371"><a href="#cb37-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-372"><a href="#cb37-372" aria-hidden="true" tabindex="-1"></a>I learned a lot over the course of the past semester working on this project. At a low level, I learned to use R in a much more in depth way. Previously, my experience in R was limited to creating linear models and doing statistical analysis by hand using variables from the model. I had very limited data visualization experience before now and I had only ever worked with datasets that did not require any cleaning or mutating. I now feel like I have a much stronger grasp on data visualization and cleaning in R and I also know how to learn new things in R very quickly, which will make it easier to learn R in a deeper way in the future.</span>
<span id="cb37-373"><a href="#cb37-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-374"><a href="#cb37-374" aria-hidden="true" tabindex="-1"></a>At a high level, I learned to transform a dataset in a way that is useful for solving a research question. Sometimes your data needs to be cleaned to make it useful, such as removing unneeded columns or rows which won't contribute effectively to analysis. Once data is in a clean state, it will often require some mutation to get data in the form that would be most useful to your analysis. In my example, it made sense to categorize some of my variables to make comparison easier to understand visually.</span>
<span id="cb37-375"><a href="#cb37-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-376"><a href="#cb37-376" aria-hidden="true" tabindex="-1"></a><span class="fu">## What I Would Improve In the Future</span></span>
<span id="cb37-377"><a href="#cb37-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-378"><a href="#cb37-378" aria-hidden="true" tabindex="-1"></a>My biggest regret for this project was not taking more time to vet my dataset at the beginning. I dove into analysis quickly after cleaning it, but I ended up being left without too many avenues of analysis to go down. In the future I would pose a research question as my first step after finding a dataset and do some simple visualizations to see if I'm on the right track. I also would like to work with a more challenging dataset in the future and integrate more types of visualizations in R. </span>
<span id="cb37-379"><a href="#cb37-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-380"><a href="#cb37-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-381"><a href="#cb37-381" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bibliography</span></span>
<span id="cb37-382"><a href="#cb37-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-383"><a href="#cb37-383" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">1</span><span class="co">]</span> R Core Team (2022). R: A language and environment for statistical computing.</span>
<span id="cb37-384"><a href="#cb37-384" aria-hidden="true" tabindex="-1"></a>  R Foundation for Statistical Computing, Vienna, Austria. URL</span>
<span id="cb37-385"><a href="#cb37-385" aria-hidden="true" tabindex="-1"></a>  https://www.R-project.org/.</span>
<span id="cb37-386"><a href="#cb37-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-387"><a href="#cb37-387" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">2</span><span class="co">]</span> H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New</span>
<span id="cb37-388"><a href="#cb37-388" aria-hidden="true" tabindex="-1"></a>  York, 2016.</span>
<span id="cb37-389"><a href="#cb37-389" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb37-390"><a href="#cb37-390" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">3</span><span class="co">]</span> Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G,</span>
<span id="cb37-391"><a href="#cb37-391" aria-hidden="true" tabindex="-1"></a>  Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller</span>
<span id="cb37-392"><a href="#cb37-392" aria-hidden="true" tabindex="-1"></a>  K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C,</span>
<span id="cb37-393"><a href="#cb37-393" aria-hidden="true" tabindex="-1"></a>  Woo K, Yutani H (2019). “Welcome to the tidyverse.” _Journal of Open Source</span>
<span id="cb37-394"><a href="#cb37-394" aria-hidden="true" tabindex="-1"></a>  Software_, *4*(43), 1686. doi:10.21105/joss.01686</span>
<span id="cb37-395"><a href="#cb37-395" aria-hidden="true" tabindex="-1"></a>  <span class="ot">&lt;https://doi.org/10.21105/joss.01686&gt;</span>.</span>
<span id="cb37-396"><a href="#cb37-396" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb37-397"><a href="#cb37-397" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">4</span><span class="co">]</span> Massachusetts. Department of Education: Statewide Public School Reports 2017, https://profiles.doe.mass.edu/state_report/</span>
<span id="cb37-398"><a href="#cb37-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-399"><a href="#cb37-399" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">5</span><span class="co">]</span> Wickham, H., &amp; Grolemund, G. (2016). R for data science: Visualize, model, transform, tidy, and import data. OReilly Media</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>