{
  "hash": "ecd6abb368464a743ae68ecd11bc8e89",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 Instructions\"\nauthor: \"Meredith Rolfe\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"08/16/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\n## Railroad dataset(railroad\\*.csv)-\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv('_data/railroad_2012_clean_county.csv')\ndata\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# … with 2,920 more rows\n```\n:::\n:::\n\n\nit shows state, county and total number of employees for a given dataset.\n\nIt's group by state and county.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(county,state) %>%\n  summarize_at(c('total_employees'),mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n# Groups:   county [1,709]\n   county    state total_employees\n   <chr>     <chr>           <dbl>\n 1 ABBEVILLE SC                124\n 2 ACADIA    LA                 13\n 3 ACCOMACK  VA                  4\n 4 ADA       ID                 81\n 5 ADAIR     IA                  5\n 6 ADAIR     KY                  1\n 7 ADAIR     MO                 21\n 8 ADAIR     OK                  2\n 9 ADAMS     CO                553\n10 ADAMS     IA                  7\n# … with 2,920 more rows\n```\n:::\n:::\n\n\nNow let's see the mean of the data set group by county.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(county) %>%\n  summarize_at(c('total_employees'),mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,709 × 2\n   county    total_employees\n   <chr>               <dbl>\n 1 ABBEVILLE          124   \n 2 ACADIA              13   \n 3 ACCOMACK             4   \n 4 ADA                 81   \n 5 ADAIR                7.25\n 6 ADAMS               73.2 \n 7 ADDISON              8   \n 8 AIKEN              193   \n 9 AITKIN              19   \n10 ALACHUA             22   \n# … with 1,699 more rows\n```\n:::\n:::\n\n\nlet's see the mean of the data set group by state.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(state) %>%\n  summarize_at(c('total_employees'),mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state total_employees\n   <chr>           <dbl>\n 1 AE                2  \n 2 AK               17.2\n 3 AL               63.5\n 4 AP                1  \n 5 AR               53.8\n 6 AZ              210. \n 7 CA              239. \n 8 CO               64.0\n 9 CT              324  \n10 DC              279  \n# … with 43 more rows\n```\n:::\n:::\n\n\nThe median of the data set group by state.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(state) %>%\n  summarize_at(c('total_employees'),median)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state total_employees\n   <chr>           <dbl>\n 1 AE                2  \n 2 AK                2.5\n 3 AL               26  \n 4 AP                1  \n 5 AR               16.5\n 6 AZ               94  \n 7 CA               61  \n 8 CO               10  \n 9 CT              125  \n10 DC              279  \n# … with 43 more rows\n```\n:::\n:::\n\n\nThe median of the data set group by county.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(county) %>%\n  summarize_at(c('total_employees'),median)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,709 × 2\n   county    total_employees\n   <chr>               <dbl>\n 1 ABBEVILLE           124  \n 2 ACADIA               13  \n 3 ACCOMACK              4  \n 4 ADA                  81  \n 5 ADAIR                 3.5\n 6 ADAMS                19.5\n 7 ADDISON               8  \n 8 AIKEN               193  \n 9 AITKIN               19  \n10 ALACHUA              22  \n# … with 1,699 more rows\n```\n:::\n:::\n\n\nCT, AZ, and DC all three are compared to check the difference in mean of the total_employees present in the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- c(\"CT\")\nfilter(data, state %in% result) %>% \n  summarize_at(c('total_employees'),mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  total_employees\n            <dbl>\n1             324\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- c(\"AZ\")\nfilter(data, state %in% result) %>% \n  summarize_at(c('total_employees'),mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  total_employees\n            <dbl>\n1            210.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- c(\"DC\")\nfilter(data, state %in% result) %>% \n  summarize_at(c('total_employees'),mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  total_employees\n            <dbl>\n1             279\n```\n:::\n:::\n\n\nThe mean value vary a lot i.e. for CT it's 324, AZ is 210.2 and DC is 279.\n\nNow let's see the Standard Deviation of the data set group by state and also by county.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(county) %>%\n  summarize_at(c('total_employees'),sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,709 × 2\n   county    total_employees\n   <chr>               <dbl>\n 1 ABBEVILLE           NA   \n 2 ACADIA              NA   \n 3 ACCOMACK            NA   \n 4 ADA                 NA   \n 5 ADAIR                9.32\n 6 ADAMS              155.  \n 7 ADDISON             NA   \n 8 AIKEN               NA   \n 9 AITKIN              NA   \n10 ALACHUA             NA   \n# … with 1,699 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(state) %>%\n  summarize_at(c('total_employees'),sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state total_employees\n   <chr>           <dbl>\n 1 AE               NA  \n 2 AK               34.8\n 3 AL              130. \n 4 AP               NA  \n 5 AR              131. \n 6 AZ              228. \n 7 CA              549. \n 8 CO              128. \n 9 CT              520. \n10 DC               NA  \n# … with 43 more rows\n```\n:::\n:::\n\n\nIf we see CA then CT had the highest SD but if we look at the mean then it's 324 and 238 which is a huge difference.\n\n## Bird dataset(birds.csv)-\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds <- read_csv(\"_data/birds.csv\")%>%\n  select(-c(contains(\"Code\"), Element, Domain, Unit))\nbirds\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 30,977 × 6\n   Area        Item      Year Value Flag  `Flag Description`\n   <chr>       <chr>    <dbl> <dbl> <chr> <chr>             \n 1 Afghanistan Chickens  1961  4700 F     FAO estimate      \n 2 Afghanistan Chickens  1962  4900 F     FAO estimate      \n 3 Afghanistan Chickens  1963  5000 F     FAO estimate      \n 4 Afghanistan Chickens  1964  5300 F     FAO estimate      \n 5 Afghanistan Chickens  1965  5500 F     FAO estimate      \n 6 Afghanistan Chickens  1966  5800 F     FAO estimate      \n 7 Afghanistan Chickens  1967  6600 F     FAO estimate      \n 8 Afghanistan Chickens  1968  6290 <NA>  Official data     \n 9 Afghanistan Chickens  1969  6300 F     FAO estimate      \n10 Afghanistan Chickens  1970  6000 F     FAO estimate      \n# … with 30,967 more rows\n```\n:::\n:::\n\n\nThis data set has many variables like Area, Item, year, value, flag, and flag description.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Area               Item                Year          Value         \n Length:30977       Length:30977       Min.   :1961   Min.   :       0  \n Class :character   Class :character   1st Qu.:1976   1st Qu.:     171  \n Mode  :character   Mode  :character   Median :1992   Median :    1800  \n                                       Mean   :1991   Mean   :   99411  \n                                       3rd Qu.:2005   3rd Qu.:   15404  \n                                       Max.   :2018   Max.   :23707134  \n                                                      NA's   :1036      \n     Flag           Flag Description  \n Length:30977       Length:30977      \n Class :character   Class :character  \n Mode  :character   Mode  :character  \n                                      \n                                      \n                                      \n                                      \n```\n:::\n:::\n\n\nLet's take a look at average and median stock values by year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds%>%\n    group_by(Year)%>%\n     summarise(mean(Value, na.rm=TRUE),median(Value, na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 3\n    Year `mean(Value, na.rm = TRUE)` `median(Value, na.rm = TRUE)`\n   <dbl>                       <dbl>                         <dbl>\n 1  1961                      36752.                         1033 \n 2  1962                      37787.                         1014 \n 3  1963                      38736.                         1106 \n 4  1964                      39325.                         1103 \n 5  1965                      40334.                         1104 \n 6  1966                      41229.                         1088.\n 7  1967                      43240.                         1193 \n 8  1968                      44420.                         1252.\n 9  1969                      45607.                         1267 \n10  1970                      47706.                         1259 \n# … with 48 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds%>%\n     filter(Area == \"Americas\")%>%\n     group_by(Item,Year)%>%\n     summarise(average = mean(Value, na.rm=TRUE))%>%\n     pivot_wider(names_from = Year, values_from = (average))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 59\n# Groups:   Item [4]\n  Item     `1961` `1962` `1963` `1964` `1965` `1966` `1967` `1968` `1969` `1970`\n  <chr>     <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>\n1 Chickens 1.19e6 1.22e6 1.24e6 1.29e6 1.33e6 1.37e6 1.43e6 1.47e6 1.53e6 1.56e6\n2 Ducks    9.64e3 9.99e3 1.07e4 1.10e4 1.13e4 1.19e4 1.18e4 1.20e4 1.20e4 1.21e4\n3 Geese a… 5.53e2 5.61e2 5.95e2 6.07e2 6.18e2 6.43e2 5.95e2 6.23e2 6.59e2 6.65e2\n4 Turkeys  1.19e5 1.03e5 1.05e5 1.13e5 1.18e5 1.30e5 1.39e5 1.20e5 1.20e5 1.31e5\n# … with 48 more variables: `1971` <dbl>, `1972` <dbl>, `1973` <dbl>,\n#   `1974` <dbl>, `1975` <dbl>, `1976` <dbl>, `1977` <dbl>, `1978` <dbl>,\n#   `1979` <dbl>, `1980` <dbl>, `1981` <dbl>, `1982` <dbl>, `1983` <dbl>,\n#   `1984` <dbl>, `1985` <dbl>, `1986` <dbl>, `1987` <dbl>, `1988` <dbl>,\n#   `1989` <dbl>, `1990` <dbl>, `1991` <dbl>, `1992` <dbl>, `1993` <dbl>,\n#   `1994` <dbl>, `1995` <dbl>, `1996` <dbl>, `1997` <dbl>, `1998` <dbl>,\n#   `1999` <dbl>, `2000` <dbl>, `2001` <dbl>, `2002` <dbl>, `2003` <dbl>, …\n```\n:::\n:::\n\n\nFrom the analysis I can see that the average stock value has increased over the years and it has increased almost every year for every stock.\n",
    "supporting": [
      "Manan_Patel_challenge2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}