{
  "hash": "dd95f908ba5f5f77b229e2da01bf7299",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Instructions\"\nauthor: \"Tejaswini_Ketineni\"\ndesription: \"Reading in data and creating a post\"\ndate: \"08/21/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - railroads\n  - faostat\n  - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nI am going to work with one data set: \n1. railroad_2012_clean_county.csv\n\n\n## Reading the Data\n\nInitially the data set-1(railroad_2012_clean_country) is read\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nrailroad_2012_clean_county <- read_csv(\"_data/railroad_2012_clean_county.csv\")\nView(railroad_2012_clean_county)\n```\n:::\n\n\nHead function is used to understand the population of data \n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(railroad_2012_clean_county)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               total_employees\n  <chr> <chr>                          <dbl>\n1 AE    APO                                2\n2 AK    ANCHORAGE                          7\n3 AK    FAIRBANKS NORTH STAR               2\n4 AK    JUNEAU                             3\n5 AK    MATANUSKA-SUSITNA                  2\n6 AK    SITKA                              1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrows_and_columns_ds1 <- dim(railroad_2012_clean_county)\nrows_and_columns_ds1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n:::\n\nThere are about 2930 rows and about 3 columns present in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames_col <- colnames(railroad_2012_clean_county)\nnames_col\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n:::\n\nThere are three columns present in the data set namely : state,county and total_employees present\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(railroad_2012_clean_county))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.null(railroad_2012_clean_county))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\nThere are no nulls or missing values present in the data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(railroad_2012_clean_county)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(data.table)\ndata_railroad <- data.table(railroad_2012_clean_county)\ndata_railroad[, .(distinct_states = length(unique(state)))]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   distinct_states\n1:              53\n```\n:::\n\n```{.r .cell-code}\ndata_railroad[, .(distinct_county = length(unique(county)))]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   distinct_county\n1:            1709\n```\n:::\n:::\n\n\nThere are 53 distinct states and 1709 distinct counties present.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(table(railroad_2012_clean_county$state))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n AE  AK  AL  AP  AR  AZ  CA  CO  CT  DC  DE  FL  GA  HI  IA  ID  IL  IN  KS  KY \n  1   6  67   1  72  15  55  57   8   1   3  67 152   3  99  36 103  92  95 119 \n LA  MA  MD  ME  MI  MN  MO  MS  MT  NC  ND  NE  NH  NJ  NM  NV  NY  OH  OK  OR \n 63  12  24  16  78  86 115  78  53  94  49  89  10  21  29  12  61  88  73  33 \n PA  RI  SC  SD  TN  TX  UT  VA  VT  WA  WI  WV  WY \n 65   5  46  52  91 221  25  92  14  39  69  53  22 \n```\n:::\n:::\n\n\n## Description of the data\n\n The data set taken is analysed and the following observations are made.There are about 2930 rows and about 3 columns namely (state, county and the total_employees) present in the data set.The data set is checked for null and missing values.We observe that there are no such values present and the data set is clean.The summary statistics are checked.the count of unique states present in the data set is 53 and 1709 unique counties are present.Tabulating the states and the total_employees, we see that the highest number of employees are present in Texas(TX) and Georgia(GA) while the lowest employee count is observed in Armed forces(AE),Armed forces Pacific(AP).We also observe that the no.of states with employee count <10 is very less.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}