---
title: "Alana Zanardo Mazur"
about:
  template: solana
  image-width: 15em
  image-shape: round
  links:
    - icon: github
      text: Github
      href: https://github.com/Azamazur
---

  
## Education/Work Background
I have a B.A. in Translation and Literature from the Federal University of Rio Grande do Sul and an M.A. in American Studies from Johannes Gutenberg University Mainz. I graduated in Translation Studies and Literature from the Federal University of Rio Grande do Sul. I am a doctoral student in Anthropology at the University of Massachusetts Amherst. My current research interests are focused on analyzing the convergence of environmental justice initiatives and clean energy solutions. 
 
B.A. Translation and Literature, Federal University of Rio Grande do Sul (UFRGS), Brazil
M.A. American Studies from Johannes Gutenberg University Mainz
Ph.D. Anthropology, University of Massachusetts Amherst (present)

## R experience
Very basic

## Research interests
My research interests are related to environmental issues, climate policies, and climate solutions. I draw on an interdisciplinary methodological approach that links environmental humanities, environmental studies, social sciences, and arts. 

Sustainability
Climate justice
Arts

## Hometown
Erechim, RS, Brazil

## Hobbies
I love spending time in green surroundings. I enjoy running, hiking, biking, swimming, doing yoga, and cooking. Cats are one of my passions.

Running
Hiking
Swimming
Yoga
Cooking
Pets

## Fun fact
I am currently training for my first marathon. 
