{
  "hash": "281923bce378df1bade43cb85e41cf6b",
  "result": {
    "markdown": "---\ntitle: \"Challenge 4 Instructions\"\nauthor: \"Matthew Norberg\"\ndesription: \"More data wrangling: pivoting\"\ndate: \"09/29/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_4\n  - abc_poll\n  - eggs\n  - fed_rates\n  - hotel_bookings\n  - debt\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lubridate)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  identify variables that need to be mutated\n4)  mutate variables and sanity check all mutations\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   abc_poll.csv ⭐\n-   poultry_tidy.xlsx or organiceggpoultry.xls⭐⭐\n-   FedFundsRate.csv⭐⭐⭐\n-   hotel_bookings.csv⭐⭐⭐⭐\n-   debt_in_trillions.xlsx ⭐⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in data set and display values\ndf <- read_csv('./_data/hotel_bookings.csv')\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 119,390 × 32\n   hotel  is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n   <chr>    <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n 1 Resor…       0     342    2015 July         27       1       0       0      2\n 2 Resor…       0     737    2015 July         27       1       0       0      2\n 3 Resor…       0       7    2015 July         27       1       0       1      1\n 4 Resor…       0      13    2015 July         27       1       0       1      1\n 5 Resor…       0      14    2015 July         27       1       0       2      2\n 6 Resor…       0      14    2015 July         27       1       0       2      2\n 7 Resor…       0       0    2015 July         27       1       0       2      2\n 8 Resor…       0       9    2015 July         27       1       0       2      2\n 9 Resor…       1      85    2015 July         27       1       0       3      2\n10 Resor…       1      75    2015 July         27       1       0       3      2\n# … with 119,380 more rows, 22 more variables: children <dbl>, babies <dbl>,\n#   meal <chr>, country <chr>, market_segment <chr>,\n#   distribution_channel <chr>, is_repeated_guest <dbl>,\n#   previous_cancellations <dbl>, previous_bookings_not_canceled <dbl>,\n#   reserved_room_type <chr>, assigned_room_type <chr>, booking_changes <dbl>,\n#   deposit_type <chr>, agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n\n```{.r .cell-code}\n# Print a summary of the data set to help describe it\nsummarytools::dfSummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \ndf  \nDimensions: 119390 x 32  \nDuplicates: 31994  \n\n-----------------------------------------------------------------------------------------------------------------------------------\nNo   Variable                         Stats / Values             Freqs (% of Valid)     Graph                  Valid      Missing  \n---- -------------------------------- -------------------------- ---------------------- ---------------------- ---------- ---------\n1    hotel                            1. City Hotel              79330 (66.4%)          IIIIIIIIIIIII          119390     0        \n     [character]                      2. Resort Hotel            40060 (33.6%)          IIIIII                 (100.0%)   (0.0%)   \n\n2    is_canceled                      Min  : 0                   0 : 75166 (63.0%)      IIIIIIIIIIII           119390     0        \n     [numeric]                        Mean : 0.4                 1 : 44224 (37.0%)      IIIIIII                (100.0%)   (0.0%)   \n                                      Max  : 1                                                                                     \n\n3    lead_time                        Mean (sd) : 104 (106.9)    479 distinct values    :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      0 < 69 < 737                                      :                                          \n                                      IQR (CV) : 142 (1)                                : : .                                      \n                                                                                        : : : . .                                  \n\n4    arrival_date_year                Mean (sd) : 2016.2 (0.7)   2015 : 21996 (18.4%)   III                    119390     0        \n     [numeric]                        min < med < max:           2016 : 56707 (47.5%)   IIIIIIIII              (100.0%)   (0.0%)   \n                                      2015 < 2016 < 2017         2017 : 40687 (34.1%)   IIIIII                                     \n                                      IQR (CV) : 1 (0)                                                                             \n\n5    arrival_date_month               1. August                  13877 (11.6%)          II                     119390     0        \n     [character]                      2. July                    12661 (10.6%)          II                     (100.0%)   (0.0%)   \n                                      3. May                     11791 ( 9.9%)          I                                          \n                                      4. October                 11160 ( 9.3%)          I                                          \n                                      5. April                   11089 ( 9.3%)          I                                          \n                                      6. June                    10939 ( 9.2%)          I                                          \n                                      7. September               10508 ( 8.8%)          I                                          \n                                      8. March                    9794 ( 8.2%)          I                                          \n                                      9. February                 8068 ( 6.8%)          I                                          \n                                      10. November                6794 ( 5.7%)          I                                          \n                                      [ 2 others ]               12709 (10.6%)          II                                         \n\n6    arrival_date_week_number         Mean (sd) : 27.2 (13.6)    53 distinct values           . : . . .        119390     0        \n     [numeric]                        min < med < max:                                    . : : : : : :        (100.0%)   (0.0%)   \n                                      1 < 28 < 53                                       . : : : : : : : : :                        \n                                      IQR (CV) : 22 (0.5)                               : : : : : : : : : :                        \n                                                                                        : : : : : : : : : :                        \n\n7    arrival_date_day_of_month        Mean (sd) : 15.8 (8.8)     31 distinct values     :                      119390     0        \n     [numeric]                        min < med < max:                                  : : : . : : . : :      (100.0%)   (0.0%)   \n                                      1 < 16 < 31                                       : : : : : : : : : :                        \n                                      IQR (CV) : 15 (0.6)                               : : : : : : : : : :                        \n                                                                                        : : : : : : : : : :                        \n\n8    stays_in_weekend_nights          Mean (sd) : 0.9 (1)        17 distinct values     :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      0 < 1 < 19                                        :                                          \n                                      IQR (CV) : 2 (1.1)                                : :                                        \n                                                                                        : :                                        \n\n9    stays_in_week_nights             Mean (sd) : 2.5 (1.9)      35 distinct values     :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      0 < 2 < 50                                        :                                          \n                                      IQR (CV) : 2 (0.8)                                :                                          \n                                                                                        :                                          \n\n10   adults                           Mean (sd) : 1.9 (0.6)      14 distinct values     :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      0 < 2 < 55                                        :                                          \n                                      IQR (CV) : 0 (0.3)                                :                                          \n                                                                                        :                                          \n\n11   children                         Mean (sd) : 0.1 (0.4)      0 : 110796 (92.8%)     IIIIIIIIIIIIIIIIII     119386     4        \n     [numeric]                        min < med < max:           1 :   4861 ( 4.1%)                            (100.0%)   (0.0%)   \n                                      0 < 0 < 10                 2 :   3652 ( 3.1%)                                                \n                                      IQR (CV) : 0 (3.8)         3 :     76 ( 0.1%)                                                \n                                                                 10 :      1 ( 0.0%)                                               \n\n12   babies                           Mean (sd) : 0 (0.1)        0 : 118473 (99.2%)     IIIIIIIIIIIIIIIIIII    119390     0        \n     [numeric]                        min < med < max:           1 :    900 ( 0.8%)                            (100.0%)   (0.0%)   \n                                      0 < 0 < 10                 2 :     15 ( 0.0%)                                                \n                                      IQR (CV) : 0 (12.3)        9 :      1 ( 0.0%)                                                \n                                                                 10 :      1 ( 0.0%)                                               \n\n13   meal                             1. BB                      92310 (77.3%)          IIIIIIIIIIIIIII        119390     0        \n     [character]                      2. FB                        798 ( 0.7%)                                 (100.0%)   (0.0%)   \n                                      3. HB                      14463 (12.1%)          II                                         \n                                      4. SC                      10650 ( 8.9%)          I                                          \n                                      5. Undefined                1169 ( 1.0%)                                                     \n\n14   country                          1. PRT                     48590 (40.7%)          IIIIIIII               119390     0        \n     [character]                      2. GBR                     12129 (10.2%)          II                     (100.0%)   (0.0%)   \n                                      3. FRA                     10415 ( 8.7%)          I                                          \n                                      4. ESP                      8568 ( 7.2%)          I                                          \n                                      5. DEU                      7287 ( 6.1%)          I                                          \n                                      6. ITA                      3766 ( 3.2%)                                                     \n                                      7. IRL                      3375 ( 2.8%)                                                     \n                                      8. BEL                      2342 ( 2.0%)                                                     \n                                      9. BRA                      2224 ( 1.9%)                                                     \n                                      10. NLD                     2104 ( 1.8%)                                                     \n                                      [ 168 others ]             18590 (15.6%)          III                                        \n\n15   market_segment                   1. Aviation                  237 ( 0.2%)                                 119390     0        \n     [character]                      2. Complementary             743 ( 0.6%)                                 (100.0%)   (0.0%)   \n                                      3. Corporate                5295 ( 4.4%)                                                     \n                                      4. Direct                  12606 (10.6%)          II                                         \n                                      5. Groups                  19811 (16.6%)          III                                        \n                                      6. Offline TA/TO           24219 (20.3%)          IIII                                       \n                                      7. Online TA               56477 (47.3%)          IIIIIIIII                                  \n                                      8. Undefined                   2 ( 0.0%)                                                     \n\n16   distribution_channel             1. Corporate                6677 ( 5.6%)          I                      119390     0        \n     [character]                      2. Direct                  14645 (12.3%)          II                     (100.0%)   (0.0%)   \n                                      3. GDS                       193 ( 0.2%)                                                     \n                                      4. TA/TO                   97870 (82.0%)          IIIIIIIIIIIIIIII                           \n                                      5. Undefined                   5 ( 0.0%)                                                     \n\n17   is_repeated_guest                Min  : 0                   0 : 115580 (96.8%)     IIIIIIIIIIIIIIIIIII    119390     0        \n     [numeric]                        Mean : 0                   1 :   3810 ( 3.2%)                            (100.0%)   (0.0%)   \n                                      Max  : 1                                                                                     \n\n18   previous_cancellations           Mean (sd) : 0.1 (0.8)      15 distinct values     :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      0 < 0 < 26                                        :                                          \n                                      IQR (CV) : 0 (9.7)                                :                                          \n                                                                                        :                                          \n\n19   previous_bookings_not_canceled   Mean (sd) : 0.1 (1.5)      73 distinct values     :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      0 < 0 < 72                                        :                                          \n                                      IQR (CV) : 0 (10.9)                               :                                          \n                                                                                        :                                          \n\n20   reserved_room_type               1. A                       85994 (72.0%)          IIIIIIIIIIIIII         119390     0        \n     [character]                      2. B                        1118 ( 0.9%)                                 (100.0%)   (0.0%)   \n                                      3. C                         932 ( 0.8%)                                                     \n                                      4. D                       19201 (16.1%)          III                                        \n                                      5. E                        6535 ( 5.5%)          I                                          \n                                      6. F                        2897 ( 2.4%)                                                     \n                                      7. G                        2094 ( 1.8%)                                                     \n                                      8. H                         601 ( 0.5%)                                                     \n                                      9. L                           6 ( 0.0%)                                                     \n                                      10. P                         12 ( 0.0%)                                                     \n\n21   assigned_room_type               1. A                       74053 (62.0%)          IIIIIIIIIIII           119390     0        \n     [character]                      2. D                       25322 (21.2%)          IIII                   (100.0%)   (0.0%)   \n                                      3. E                        7806 ( 6.5%)          I                                          \n                                      4. F                        3751 ( 3.1%)                                                     \n                                      5. G                        2553 ( 2.1%)                                                     \n                                      6. C                        2375 ( 2.0%)                                                     \n                                      7. B                        2163 ( 1.8%)                                                     \n                                      8. H                         712 ( 0.6%)                                                     \n                                      9. I                         363 ( 0.3%)                                                     \n                                      10. K                        279 ( 0.2%)                                                     \n                                      [ 2 others ]                  13 ( 0.0%)                                                     \n\n22   booking_changes                  Mean (sd) : 0.2 (0.7)      21 distinct values     :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      0 < 0 < 21                                        :                                          \n                                      IQR (CV) : 0 (2.9)                                :                                          \n                                                                                        :                                          \n\n23   deposit_type                     1. No Deposit              104641 (87.6%)         IIIIIIIIIIIIIIIII      119390     0        \n     [character]                      2. Non Refund               14587 (12.2%)         II                     (100.0%)   (0.0%)   \n                                      3. Refundable                 162 ( 0.1%)                                                    \n\n24   agent                            1. 9                       31961 (26.8%)          IIIII                  119390     0        \n     [character]                      2. NULL                    16340 (13.7%)          II                     (100.0%)   (0.0%)   \n                                      3. 240                     13922 (11.7%)          II                                         \n                                      4. 1                        7191 ( 6.0%)          I                                          \n                                      5. 14                       3640 ( 3.0%)                                                     \n                                      6. 7                        3539 ( 3.0%)                                                     \n                                      7. 6                        3290 ( 2.8%)                                                     \n                                      8. 250                      2870 ( 2.4%)                                                     \n                                      9. 241                      1721 ( 1.4%)                                                     \n                                      10. 28                      1666 ( 1.4%)                                                     \n                                      [ 324 others ]             33250 (27.8%)          IIIII                                      \n\n25   company                          1. NULL                    112593 (94.3%)         IIIIIIIIIIIIIIIIII     119390     0        \n     [character]                      2. 40                         927 ( 0.8%)                                (100.0%)   (0.0%)   \n                                      3. 223                        784 ( 0.7%)                                                    \n                                      4. 67                         267 ( 0.2%)                                                    \n                                      5. 45                         250 ( 0.2%)                                                    \n                                      6. 153                        215 ( 0.2%)                                                    \n                                      7. 174                        149 ( 0.1%)                                                    \n                                      8. 219                        141 ( 0.1%)                                                    \n                                      9. 281                        138 ( 0.1%)                                                    \n                                      10. 154                       133 ( 0.1%)                                                    \n                                      [ 343 others ]               3793 ( 3.2%)                                                    \n\n26   days_in_waiting_list             Mean (sd) : 2.3 (17.6)     128 distinct values    :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      0 < 0 < 391                                       :                                          \n                                      IQR (CV) : 0 (7.6)                                :                                          \n                                                                                        :                                          \n\n27   customer_type                    1. Contract                 4076 ( 3.4%)                                 119390     0        \n     [character]                      2. Group                     577 ( 0.5%)                                 (100.0%)   (0.0%)   \n                                      3. Transient               89613 (75.1%)          IIIIIIIIIIIIIII                            \n                                      4. Transient-Party         25124 (21.0%)          IIII                                       \n\n28   adr                              Mean (sd) : 101.8 (50.5)   8879 distinct values   :                      119390     0        \n     [numeric]                        min < med < max:                                  :                      (100.0%)   (0.0%)   \n                                      -6.4 < 94.6 < 5400                                :                                          \n                                      IQR (CV) : 56.7 (0.5)                             :                                          \n                                                                                        :                                          \n\n29   required_car_parking_spaces      Mean (sd) : 0.1 (0.2)      0 : 111974 (93.8%)     IIIIIIIIIIIIIIIIII     119390     0        \n     [numeric]                        min < med < max:           1 :   7383 ( 6.2%)     I                      (100.0%)   (0.0%)   \n                                      0 < 0 < 8                  2 :     28 ( 0.0%)                                                \n                                      IQR (CV) : 0 (3.9)         3 :      3 ( 0.0%)                                                \n                                                                 8 :      2 ( 0.0%)                                                \n\n30   total_of_special_requests        Mean (sd) : 0.6 (0.8)      0 : 70318 (58.9%)      IIIIIIIIIII            119390     0        \n     [numeric]                        min < med < max:           1 : 33226 (27.8%)      IIIII                  (100.0%)   (0.0%)   \n                                      0 < 0 < 5                  2 : 12969 (10.9%)      II                                         \n                                      IQR (CV) : 1 (1.4)         3 :  2497 ( 2.1%)                                                 \n                                                                 4 :   340 ( 0.3%)                                                 \n                                                                 5 :    40 ( 0.0%)                                                 \n\n31   reservation_status               1. Canceled                43017 (36.0%)          IIIIIII                119390     0        \n     [character]                      2. Check-Out               75166 (63.0%)          IIIIIIIIIIII           (100.0%)   (0.0%)   \n                                      3. No-Show                  1207 ( 1.0%)                                                     \n\n32   reservation_status_date          min : 2014-10-17           926 distinct values            . : : : :      119390     0        \n     [Date]                           med : 2016-08-07                                        : : : : : : .    (100.0%)   (0.0%)   \n                                      max : 2017-09-14                                      . : : : : : : :                        \n                                      range : 2y 10m 28d                                    : : : : : : : :                        \n                                                                                        .   : : : : : : : :                        \n-----------------------------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n### Briefly describe the data\n\nEach row in the data set describes a hotel booking for a hotel chain.  We can see that from the 'hotel' column that each hotel in the chain is classified as either a 'City Hotel' or a 'Resort Hotel'.  Looking at the 'arrival_date_year' column, we can see that the data was collected between 2015 and 2017.  Additionally, we can see from the 'country' column that the data was collected from all over the world.  In total, we can see that there are 178 different values in the 'country' column.  However, one of those values is \"NULL\", so there are only 177 known countries included in the data set. \n\n## Tidy Data (as needed)\n\nIs your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.\n\nThere are four rows in the data set that contain values that are not available.  They are all in the 'children' column.  I believe it is safe to remove these values since it is only 4 cases out of 119,390.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove NA values\ndf <- na.omit(df)\n```\n:::\n\n\nThe data is tidy after removing the values which are not available.  Every row represents an observation, each column represents one variable, and each value has its own cell.\n\nAny additional comments?\n\nLooking at the summary of the data frame, we can see that the 'agent' and 'company' columns are of type character.  However, upon inspection, it appears as though they are all integers.  We can inspect the two values in the two columns with the following R commands:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# List distinct values in agent and company\ndistinct(df, agent)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 334 × 1\n   agent\n   <chr>\n 1 NULL \n 2 304  \n 3 240  \n 4 303  \n 5 15   \n 6 241  \n 7 8    \n 8 250  \n 9 115  \n10 5    \n# … with 324 more rows\n```\n:::\n\n```{.r .cell-code}\ndistinct(df, company)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 353 × 1\n   company\n   <chr>  \n 1 NULL   \n 2 110    \n 3 113    \n 4 270    \n 5 178    \n 6 240    \n 7 154    \n 8 144    \n 9 307    \n10 268    \n# … with 343 more rows\n```\n:::\n:::\n\n\nBy inspection, we can see that the columns are of character type because of string \"NULL\" in each column.  This was likely placed in the data set to indicate that an agent or company was not used.  However, it is a bit annoying that the columns are character types.  For instance, this prevents you from sorting the columns by value.  Here is an example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort distinct values in agent column\narrange(distinct(df, agent), agent)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 334 × 1\n   agent\n   <chr>\n 1 1    \n 2 10   \n 3 103  \n 4 104  \n 5 105  \n 6 106  \n 7 107  \n 8 11   \n 9 110  \n10 111  \n# … with 324 more rows\n```\n:::\n:::\n\n\nWe can see in the tibble above, that 107 comes before 11.  That isn't quite right and it is only happening because the column is of type character.  If we look at the column a bit further, we can see that none of the values are less than 0.  These queries confirm that this is the case.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find agent and company values that have integer value less than 0\ndistinct(df, agent) %>% filter(agent != \"NULL\") %>% filter(as.integer(agent) <= 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 × 1\n# … with 1 variable: agent <chr>\n```\n:::\n\n```{.r .cell-code}\ndistinct(df, company) %>% filter(company != \"NULL\") %>% filter(as.integer(company) <= 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 × 1\n# … with 1 variable: company <chr>\n```\n:::\n:::\n\n\nTo change the type of the column from character to double, I think we should replace all of the \"NULL\" strings with \"-1\".  Then we can convert the type of the column.  We will just use the convention that a value of -1 in either column indicates that an agent or company was not used.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert agent and company columns to double type\n# Note: Replace \"NULL\" with \"-1\" first to do so\ndf <- df %>%\n      mutate(agent = str_replace(agent, \"NULL\", \"-1\")) %>%\n      mutate(company = str_replace(company, \"NULL\", \"-1\")) %>%\n      type_convert()\n```\n:::\n\n\nNow, the 'agent' and 'company' columns have been converted to double.\n\n## Identify variables that need to be mutated\n\nAre there any variables that require mutation to be usable in your analysis stream? For example, are all time variables correctly coded as dates? Are all string variables reduced and cleaned to sensible categories? Do you need to turn any variables into factors and reorder for ease of graphics and visualization?\n\nDocument your work here.\n\nFirst, I think that the 'arrival_date_week_number' is not useful.  We have the arrival month, year, and the day of the month.  I am not sure why we need the 'arrival_date_week_number' as well.  Also, certain dates do not always fall on the same date of the year.  For example, this year, January 1st was on a Friday and last year it was on a Saturday.  Consequently, the week of the year that someone arrives may not fall on the same date between years.  Lastly, I am not sure how they determine what the first week of the year is.  In the previous example, is the first week the span of Friday, Saturday, and Sunday because the first is on a Friday?  I don't know, but the first week could also be considered as the following week in the example because it is the first full week.  Due to these details, I think it's best to drop that column from the data set. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove arrival_date_week_number\ndf <- df %>% select(-(arrival_date_week_number))\n```\n:::\n\n\nThe next observation I had is that the 'adr' column stands for average daily rate.  I think it would be good to rename this column to make the data more readable. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rename adr column\ndf <- df %>% rename(average_daily_rate = adr)\n```\n:::\n\n\nLooking at the columns, it appears as though many of the columns represent categorical data.  These can all be converted to factors to make it easier to understand how many times each category appears in the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create factors for categorical data\n\nmonth_levels <- c(\n  \"January\", \"February\", \"March\", \"April\", \"May\", \"June\",\n  \"July\", \"August\", \"September\", \"October\", \"November\", \"December\"\n)\ndf$arrival_date_month <- factor(df$arrival_date_month, month_levels)\n\ndf$meal <- factor(df$meal, c(\"BB\", \"HB\", \"FB\", \"SC\", \"Undefined\"))\n\ndf$hotel <- factor(df$hotel, c(\"City Hotel\", \"Resort Hotel\"))\n\ndf$market_segment <- factor(df$market_segment, c(\"Aviation\", \"Complementary\", \"Corporate\", \"Direct\", \"Groups\",\n                                                 \"Offline TA/TO\", \"Online TA\"))\n\ndf$distribution_channel <- factor(df$distribution_channel, c(\"Corporate\", \"Direct\", \"GDS\", \"TA/TO\", \"Undefined\"))\n\ndf$assigned_room_type <- factor(df$assigned_room_type, unique(df$assigned_room_type))\n\ndf$reserved_room_type <- factor(df$reserved_room_type, unique(df$reserved_room_type))\n\ndf$deposit_type <- factor(df$deposit_type, unique(df$deposit_type))\n\ndf$customer_type <- factor(df$customer_type, unique(df$customer_type))\n\ndf$reservation_status <- factor(df$reservation_status, unique(df$reservation_status))\n```\n:::\n\n\nThe next observation is that we are recording the arrival date in three columns, instead of one.  We can use mutate to combine the information in these columns.  Afterwards, we can remove the old date columns to simplify the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert arrival information into single column and remove old columns\ndf <- df %>% mutate(date = make_date(arrival_date_year, arrival_date_month, arrival_date_day_of_month))\ndf <- df %>% relocate(date, .after = hotel)\ndf <- df %>% select(-c(arrival_date_year, arrival_date_month, arrival_date_day_of_month))\n```\n:::\n\n\nNext, we can see that the number of nights that the booking was scheduled for is recorded in two columns.  One records the weeknights and the other records the weekdays.  I think it would be a good idea to create  a new column called total nights using mutate.  This is done below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a column to store total number of nights stayed\ndf <- df %>% mutate(total_nights = stays_in_weekend_nights + stays_in_week_nights) %>%\n      relocate(total_nights, .after = stays_in_week_nights)\n```\n:::\n\n\nNow that we have tidied up the tibble, we need to present it in a way that is readable.  I think the best way to do that is to sort it by arrival date. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort by date\ndf <- df %>% arrange(date)\n```\n:::\n\n\nAny additional comments?\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}