{
  "hash": "995118d6cbb123065ac4428f6ef4d335",
  "result": {
    "markdown": "---\ntitle: \"Popular Baby Name Analysis\"\ndescription: \"DACSS 601 Fall 2022 Final Project\"\nauthor: \"Aleacia Messiah\"\ndate: \"12/18/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - final project\n  - Aleacia Messiah\n  - babynames\n  - tidyverse\n  - summarytools\n  - ggplot2\n  - devtools\n  - plotly\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(summarytools)\nlibrary(ggplot2)\nlibrary(devtools)\nlibrary(plotly)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n::: panel-tabset\n## Introduction and Data\n\n### *Introduction*\n\nIt's not hard to imagine a brand new mother and father leaving the hospital with their newborn child, cradling their bundle of joy as they eagerly drive home to spend time playing with the newest member of their family. Diaper changes, frequent feedings, and sleepless nights are among the multitude of things they will need to be prepared for during the baby's first years of life. However, the one thing that excites them at the arrival of the baby is choosing his or her name. Over the years, many parents have named their children various popular and unique names like Sarah, Gertrude, Michael, and Samuel based on lists of baby girl and boy names. These lists have become so popular that the Social Security Administration (SSA) compiled a dataset that includes not just the top 1,000 popular names but the majority of names that are assigned to a Social Security Number (SSN). In this final project, I will analyze the Social Security Administration dataset containing almost all names associated with an SSN to answer the below research questions.\n\n**1. What are the top five baby names for each year from 1910 to 2021?**\n\n**2. Which names have the largest difference in occurrences per region (i.e. which names have undergone the most change in usage)?**\n\n**3. Are there consistently more popular girl names or popular boy names?**\n\n### *Data*\n\nThis dataset from the SSA contains fifty-one text files containing the two-digit state code, sex, year of birth ranging from 1910 to 2021, name, and number of occurrences for each state and the District of Columbia where the individual has an SSN. The data is restricted to only include names with at least five occurrences to preserve privacy. All of these files combined has 6,311,504 observations corresponding to a name for each state and year and 5 variables consisting of `State`, `Gender`, `Year`, `Name`, and `Count`.\n\nReviewing the summary of this `baby_orig` dataset, I find there are no missing values which is helpful when I do my analysis and visualizations. The states that make up the majority of the data are California with 400,762 observations (6.3% of the data), Texas with 368,987 observations (5.8% of the data), and New York with 309,532 observations (4.9% of the data). There are more female names than male names in this dataset with 3,510,324 female names (55.6% of the data) and 2,801,180 male names (44.4% of the data), meaning some states had a larger concentration of those with feminine names than masculine names in some years, which I find interesting. The names that appear the most within this dataset (not counting occurrences) is James with 7,409 observations, Leslie with 7,407 observations, and Lee with 7,313 observations. The highest number of occurrences for a name is 10,026 which happens to be with the male name Robert in New York the year 1947.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# import baby names data \nbaby_orig <- read_delim(c(\"_data/namesbystate/AK.TXT\", \"_data/namesbystate/AL.TXT\", \"_data/namesbystate/AR.TXT\", \"_data/namesbystate/AZ.TXT\", \"_data/namesbystate/CA.TXT\", \"_data/namesbystate/CO.TXT\", \"_data/namesbystate/CT.TXT\", \"_data/namesbystate/DC.TXT\", \"_data/namesbystate/DE.TXT\", \"_data/namesbystate/FL.TXT\", \"_data/namesbystate/GA.TXT\", \"_data/namesbystate/HI.TXT\", \"_data/namesbystate/IA.TXT\", \"_data/namesbystate/ID.TXT\", \"_data/namesbystate/IL.TXT\", \"_data/namesbystate/IN.TXT\", \"_data/namesbystate/KS.TXT\", \"_data/namesbystate/KY.TXT\", \"_data/namesbystate/LA.TXT\", \"_data/namesbystate/MA.TXT\", \"_data/namesbystate/MD.TXT\", \"_data/namesbystate/ME.TXT\", \"_data/namesbystate/MI.TXT\", \"_data/namesbystate/MN.TXT\", \"_data/namesbystate/MO.TXT\", \"_data/namesbystate/MS.TXT\", \"_data/namesbystate/MT.TXT\", \"_data/namesbystate/NC.TXT\", \"_data/namesbystate/ND.TXT\", \"_data/namesbystate/NE.TXT\", \"_data/namesbystate/NH.TXT\", \"_data/namesbystate/NJ.TXT\", \"_data/namesbystate/NM.TXT\", \"_data/namesbystate/NV.TXT\", \"_data/namesbystate/NY.TXT\", \"_data/namesbystate/OH.TXT\", \"_data/namesbystate/OK.TXT\", \"_data/namesbystate/OR.TXT\", \"_data/namesbystate/PA.TXT\", \"_data/namesbystate/RI.TXT\", \"_data/namesbystate/SC.TXT\", \"_data/namesbystate/SD.TXT\", \"_data/namesbystate/TN.TXT\", \"_data/namesbystate/TX.TXT\", \"_data/namesbystate/UT.TXT\", \"_data/namesbystate/VA.TXT\", \"_data/namesbystate/VT.TXT\", \"_data/namesbystate/WA.TXT\", \"_data/namesbystate/WI.TXT\", \"_data/namesbystate/WV.TXT\", \"_data/namesbystate/WY.TXT\"), delim = \",\", col_names = c(\"State\", \"Gender\", \"Year\", \"Name\", \"Count\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 6311504 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): State, Gender, Name\ndbl (2): Year, Count\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\n# view baby_orig data frame\nbaby_orig\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6,311,504 × 5\n   State Gender  Year Name     Count\n   <chr> <chr>  <dbl> <chr>    <dbl>\n 1 AK    F       1910 Mary        14\n 2 AK    F       1910 Annie       12\n 3 AK    F       1910 Anna        10\n 4 AK    F       1910 Margaret     8\n 5 AK    F       1910 Helen        7\n 6 AK    F       1910 Elsie        6\n 7 AK    F       1910 Lucy         6\n 8 AK    F       1910 Dorothy      5\n 9 AK    F       1911 Mary        12\n10 AK    F       1911 Margaret     7\n# … with 6,311,494 more rows\n```\n:::\n\n```{.r .cell-code}\n# view summary of baby_orig\ndfSummary(baby_orig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nbaby_orig  \nDimensions: 6311504 x 5  \nDuplicates: 0  \n\n----------------------------------------------------------------------------------------------------------------\nNo   Variable      Stats / Values              Freqs (% of Valid)     Graph                 Valid      Missing  \n---- ------------- --------------------------- ---------------------- --------------------- ---------- ---------\n1    State         1. CA                        400762 ( 6.3%)        I                     6311504    0        \n     [character]   2. TX                        368987 ( 5.8%)        I                     (100.0%)   (0.0%)   \n                   3. NY                        309532 ( 4.9%)                                                  \n                   4. IL                        237839 ( 3.8%)                                                  \n                   5. FL                        218192 ( 3.5%)                                                  \n                   6. PA                        206944 ( 3.3%)                                                  \n                   7. OH                        204165 ( 3.2%)                                                  \n                   8. GA                        191367 ( 3.0%)                                                  \n                   9. MI                        190023 ( 3.0%)                                                  \n                   10. NC                       181647 ( 2.9%)                                                  \n                   [ 41 others ]               3802046 (60.2%)        IIIIIIIIIIII                              \n\n2    Gender        1. F                        3510324 (55.6%)        IIIIIIIIIII           6311504    0        \n     [character]   2. M                        2801180 (44.4%)        IIIIIIII              (100.0%)   (0.0%)   \n\n3    Year          Mean (sd) : 1977.2 (31.3)   112 distinct values                      :   6311504    0        \n     [numeric]     min < med < max:                                                 . : :   (100.0%)   (0.0%)   \n                   1910 < 1983 < 2021                                         . . : : : :                       \n                   IQR (CV) : 52 (0)                                  . : . : : : : : : :                       \n                                                                      : : : : : : : : : :                       \n\n4    Name          1. James                       7409 ( 0.1%)                              6311504    0        \n     [character]   2. Leslie                      7407 ( 0.1%)                              (100.0%)   (0.0%)   \n                   3. Lee                         7313 ( 0.1%)                                                  \n                   4. John                        7221 ( 0.1%)                                                  \n                   5. Robert                      7174 ( 0.1%)                                                  \n                   6. Jessie                      6922 ( 0.1%)                                                  \n                   7. William                     6880 ( 0.1%)                                                  \n                   8. Michael                     6756 ( 0.1%)                                                  \n                   9. Mary                        6699 ( 0.1%)                                                  \n                   10. Charles                    6624 ( 0.1%)                                                  \n                   [ 32393 others ]            6241099 (98.9%)        IIIIIIIIIIIIIIIIIII                       \n\n5    Count         Mean (sd) : 50.7 (173.1)    4938 distinct values   :                     6311504    0        \n     [numeric]     min < med < max:                                   :                     (100.0%)   (0.0%)   \n                   5 < 12 < 10026                                     :                                         \n                   IQR (CV) : 26 (3.4)                                :                                         \n                                                                      :                                         \n----------------------------------------------------------------------------------------------------------------\n```\n:::\n\n```{.r .cell-code}\n# find the name with the largest number of occurrences\nfilter(baby_orig, Count == 10026)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 5\n  State Gender  Year Name   Count\n  <chr> <chr>  <dbl> <chr>  <dbl>\n1 NY    M       1947 Robert 10026\n```\n:::\n:::\n\n\nAfter importing the data and looking at its summary statistics, I will refine some of the values to make it clearer what they represent. I will rename the values in the `State` and `Gender` columns to their appropriate state names and male and female as the `State_Full` and `Gender_Full` columns. I will also add a column called `Region` to compare names between different regions of the United States since it would be difficult to compare all fifty states and the District of Columbia. Note that the District of Columbia is included in the Middle Atlantic region despite not being a state. Additionally, `Gender_Full` will be converted into a factor for ease of visualization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaby <- baby_orig %>% \n  # create a Region column\n  mutate(Region = case_when(\n    State == c(\"CT\", \"ME\", \"MA\", \"NH\", \"RI\", \"VT\") ~ \"New England\",\n    State == c(\"DC\", \"DE\", \"MD\", \"NJ\", \"NY\", \"PA\") ~ \"Middle Atlantic\",\n    State == c(\"AL\", \"AR\", \"FL\", \"GA\", \"KY\", \"LA\", \"MS\", \"MO\", \"NC\", \"SC\", \"TN\", \"VA\", \"WV\") ~ \"South\",\n    State == c(\"IL\", \"IN\", \"IA\", \"KS\", \"MI\", \"MN\", \"NE\", \"ND\", \"OH\", \"SD\", \"WI\") ~ \"Midwest\",\n    State == c(\"AZ\", \"NM\", \"OK\", \"TX\") ~ \"Southwest\",\n    State == c(\"AK\", \"CA\", \"CO\", \"HI\", \"ID\", \"MT\", \"NV\", \"OR\", \"UT\", \"WA\", \"WY\") ~ \"West\",\n    TRUE ~ NA_character_\n    )) %>% \n  # replace NAs in Region column\n  fill(Region, .direction = \"down\") %>% \n  # recode State values\n  mutate(State_Full = recode(State, \"AL\" = \"Alabama\", \"AK\" = \"Alaska\", \"AZ\" = \"Arizona\", \"AR\" = \"Arkansas\", \"CA\" = \"California\", \"CO\" = \"Colorado\", \"CT\" = \"Connecticut\", \"DE\" = \"Delaware\", \"DC\" = \"District of Columbia\", \"FL\" = \"Florida\", \"GA\" = \"Georgia\", \"HI\" = \"Hawaii\", \"ID\" = \"Idaho\", \"IL\" = \"Illinois\", \"IN\" = \"Indiana\", \"IA\" = \"Iowa\", \"KS\" = \"Kansas\", \"KY\" = \"Kentucky\", \"LA\" = \"Louisiana\", \"ME\" = \"Maine\", \"MD\" = \"Maryland\", \"MA\" = \"Massachussetts\", \"MI\" = \"Michigan\", \"MN\" = \"Minnesota\", \"MS\" = \"Mississippi\", \"MO\" = \"Missouri\", \"MT\" = \"Montana\", \"NE\" = \"Nebraska\", \"NV\" = \"Nevada\", \"NH\" = \"New Hampshire\", \"NJ\" = \"New Jersey\", \"NM\" = \"New Mexico\", \"NY\" = \"New York\", \"NC\" = \"North Carolina\", \"ND\" = \"North Dakota\", \"OH\" = \"Ohio\", \"OK\" = \"Oklahoma\", \"OR\" = \"Oregon\", \"PA\" = \"Pennsylvania\", \"RI\" = \"Rhode Island\", \"SC\" = \"South Carolina\", \"SD\" = \"South Dakota\", \"TN\" = \"Tennessee\", \"TX\" = \"Texas\", \"UT\" = \"Utah\", \"VT\" = \"Vermont\", \"VA\" = \"Virginia\", \"WA\" = \"Washington\", \"WV\" = \"West Virginia\", \"WI\" = \"Wisconsin\", \"WY\" = \"Wyoming\")) %>% \n  # recode Gender values\n  mutate(Gender_Full = recode(Gender, \"M\" = \"Male\", \"F\" = \"Female\")) %>% \n  # delete State and Gender columns\n  select(!c(State, Gender))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in State == c(\"CT\", \"ME\", \"MA\", \"NH\", \"RI\", \"VT\"): longer object length\nis not a multiple of shorter object length\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in State == c(\"DC\", \"DE\", \"MD\", \"NJ\", \"NY\", \"PA\"): longer object length\nis not a multiple of shorter object length\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in State == c(\"AL\", \"AR\", \"FL\", \"GA\", \"KY\", \"LA\", \"MS\", \"MO\", \"NC\", :\nlonger object length is not a multiple of shorter object length\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in State == c(\"IL\", \"IN\", \"IA\", \"KS\", \"MI\", \"MN\", \"NE\", \"ND\", \"OH\", :\nlonger object length is not a multiple of shorter object length\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in State == c(\"AK\", \"CA\", \"CO\", \"HI\", \"ID\", \"MT\", \"NV\", \"OR\", \"UT\", :\nlonger object length is not a multiple of shorter object length\n```\n:::\n\n```{.r .cell-code}\n# convert Gender_Full into a factor\nbaby$Gender_Full <- factor(baby$Gender_Full)\n# view baby dataset\nbaby\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6,311,504 × 6\n    Year Name     Count Region State_Full Gender_Full\n   <dbl> <chr>    <dbl> <chr>  <chr>      <fct>      \n 1  1910 Mary        14 West   Alaska     Female     \n 2  1910 Annie       12 West   Alaska     Female     \n 3  1910 Anna        10 West   Alaska     Female     \n 4  1910 Margaret     8 West   Alaska     Female     \n 5  1910 Helen        7 West   Alaska     Female     \n 6  1910 Elsie        6 West   Alaska     Female     \n 7  1910 Lucy         6 West   Alaska     Female     \n 8  1910 Dorothy      5 West   Alaska     Female     \n 9  1911 Mary        12 West   Alaska     Female     \n10  1911 Margaret     7 West   Alaska     Female     \n# … with 6,311,494 more rows\n```\n:::\n\n```{.r .cell-code}\n# check that all states are in their appropriate regions\ntable(baby$Region)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMiddle Atlantic         Midwest     New England           South       Southwest \n         883857         1384692          371959         1876994          690296 \n           West \n        1103706 \n```\n:::\n\n```{.r .cell-code}\ntable(baby$State_Full)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n             Alabama               Alaska              Arizona \n              139293                29755               122085 \n            Arkansas           California             Colorado \n              105373               400762               112986 \n         Connecticut             Delaware District of Columbia \n               84948                33706                57265 \n             Florida              Georgia               Hawaii \n              218192               191367                56069 \n               Idaho             Illinois              Indiana \n               60445               237839               145357 \n                Iowa               Kansas             Kentucky \n               97515                97839               122608 \n           Louisiana                Maine             Maryland \n              153712                51852               116699 \n      Massachussetts             Michigan            Minnesota \n              123558               190023               119310 \n         Mississippi             Missouri              Montana \n              117316               144136                47144 \n            Nebraska               Nevada        New Hampshire \n               74699                50829                40557 \n          New Jersey           New Mexico             New York \n              159695                77755               309532 \n      North Carolina         North Dakota                 Ohio \n              181647                47666               204165 \n            Oklahoma               Oregon         Pennsylvania \n              121465                92410               206944 \n        Rhode Island       South Carolina         South Dakota \n               41540               122527                48865 \n           Tennessee                Texas                 Utah \n              147212               368987                93764 \n             Vermont             Virginia           Washington \n               29483               154400               130809 \n       West Virginia            Wisconsin              Wyoming \n               79250               121398                28751 \n```\n:::\n:::\n\n\nThis dataset is now pretty tidy, so I will prepare for my visualizations by generating some summary data frames that will make it easier to analyze and answer my research questions.\n\nThe first data frame consists of the top five baby names for each year by grouping the `baby` data frame by `Year`, arranging in descending order by `Count`, and then taking only the top five observations for each year.\n\nThe second data frame will help answer the second research question by calculating the difference between the minimum and maximum occurrences for each name in each region. This is done by grouping the `baby` data frame by `Region` and `Name` and then summarizing by the minimum `Count` (`min_count`), maximum `Count` (`max_count`), and the difference between the two (`difference`). For ease of visualization, I will only extract the top five names with the largest `difference` in each region.\n\nThe third data frame finds the number of popular names for each gender in each region in order to determine whether there are more popular girl names or popular boy names. This data frame filters the `baby` data frame with only names that have a `Count` of 2,000 or more, grouped by `Gender_Full` and `Region`, and summarized by the number of occurrences. The definition of \"popular\" is arbitrary but I chose a limit of 2,000 occurrences or more for each name to be considered popular because the mean `Count` is 50.7, so 2,000 seems like a good value determining whether the name is deemed popular or not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get the top 5 baby names for each year\ntop_5_baby <- baby %>% \n  group_by(Year) %>% \n  arrange(desc(Count)) %>% \n  slice_head(n = 5)\n# view top_5_baby data frame\ntop_5_baby\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 560 × 6\n# Groups:   Year [112]\n    Year Name  Count Region          State_Full   Gender_Full\n   <dbl> <chr> <dbl> <chr>           <chr>        <fct>      \n 1  1910 Mary   2913 West            Pennsylvania Female     \n 2  1910 Mary   1923 Middle Atlantic New York     Female     \n 3  1910 Helen  1604 Middle Atlantic Pennsylvania Female     \n 4  1910 Anna   1534 Middle Atlantic Pennsylvania Female     \n 5  1910 John   1326 Middle Atlantic Pennsylvania Male       \n 6  1911 Mary   3188 Middle Atlantic Pennsylvania Female     \n 7  1911 Mary   2322 Middle Atlantic New York     Female     \n 8  1911 Helen  1733 Middle Atlantic Pennsylvania Female     \n 9  1911 John   1672 Middle Atlantic Pennsylvania Male       \n10  1911 John   1624 Middle Atlantic New York     Male       \n# … with 550 more rows\n```\n:::\n\n```{.r .cell-code}\n# get the top 5 names with the largest difference between occurrences in each region\nchange_baby <- baby %>% \n  group_by(Region, Name) %>% \n  summarize(min_count = min(Count),\n            max_count = max(Count),\n            difference = max_count - min_count) %>% \n  arrange(desc(difference)) %>% \n  slice_head(n = 5)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'Region'. You can override using the\n`.groups` argument.\n```\n:::\n\n```{.r .cell-code}\n# view change_baby data frame\nchange_baby\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 30 × 5\n# Groups:   Region [6]\n   Region          Name    min_count max_count difference\n   <chr>           <chr>       <dbl>     <dbl>      <dbl>\n 1 Middle Atlantic Robert          5     10026      10021\n 2 Middle Atlantic John            5      9639       9634\n 3 Middle Atlantic Michael         5      9241       9236\n 4 Middle Atlantic Mary            5      8184       8179\n 5 Middle Atlantic Linda           5      7542       7537\n 6 Midwest         Michael         5      6221       6216\n 7 Midwest         Linda           5      5885       5880\n 8 Midwest         David           5      5495       5490\n 9 Midwest         Robert          5      5427       5422\n10 Midwest         James           5      5349       5344\n# … with 20 more rows\n```\n:::\n\n```{.r .cell-code}\n# get the most popular gender of names for each region\ngender_baby <- baby %>% \n  filter(Count >= 2000) %>% \n  group_by(Gender_Full, Region) %>% \n  summarize(n = n())\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'Gender_Full'. You can override using the\n`.groups` argument.\n```\n:::\n\n```{.r .cell-code}\n# view gender_baby data frame\ngender_baby\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 3\n# Groups:   Gender_Full [2]\n   Gender_Full Region              n\n   <fct>       <chr>           <int>\n 1 Female      Middle Atlantic   931\n 2 Female      Midwest           631\n 3 Female      New England        31\n 4 Female      South             191\n 5 Female      Southwest         213\n 6 Female      West              611\n 7 Male        Middle Atlantic  2010\n 8 Male        Midwest          1425\n 9 Male        New England       217\n10 Male        South             395\n11 Male        Southwest         563\n12 Male        West             1419\n```\n:::\n:::\n\n\n## Visualization\n\nFor my research question regarding the top five baby names for each year, I will use the `top_5_baby` data frame I created to aid in making this visualization. I created a scatterplot below with `Year` as the independent variable and `Count` as the dependent variable. I also added `Gender_Full` as a color aesthetic and `Name` as a fill aesthetic in order to see the gender and names for each year. Moreover, `Name` text labels were included to display the names for each point on this plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a scatterplot of Count vs. Year with Name labels and Gender colors\nggplot(top_5_baby, aes(Year, Count)) +\n  geom_point(aes(color = Gender_Full, fill = Name)) +\n  geom_text(\n    label = top_5_baby$Name,\n    nudge_x = 0.25, nudge_y = 0.25,\n    check_overlap = T\n  ) +\n  labs(\n    x = \"Year of Birth\",\n    y = \"Number of Occurrences\",\n    title = \"Scatterplot of Occurrences vs. Year of Birth\",\n    subtitle = \"Range of years is 1910 to 2021\",\n    caption = \"Data: https://www.ssa.gov/oact/babynames/limits.html\"\n  )\n```\n\n::: {.cell-output-display}\n![](AleaciaMessiah_FinalProject_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThis scatterplot illustrates well the top names and their occurrences over time. We can see from the early years around 1925 that the name \"Mary\" was very popular and shows up several times during those years. The name \"John\" was also a popular name at the same time. As we get to the 1950s, we see less female names and more male names such as \"Robert\", \"John\", and \"David\". This may be in correlation to the \"baby boom\" that occurred from the late 1940s to the early 1960s as World War II ended and families were settling down and having more children. Moving toward the 1970s through 1990s, girl names such as \"Jennifer\" and \"Jessica\" are rising in popularity while boy names like \"Robert\" dwindle in popularity in favor for \"Michael\" and \"Daniel\". Lastly, from the 2000s on, there's a good mix of popular male and female names like \"Jayden\", \"Mia\", and \"Isabella\", which could be related to celebrities and other well-known people naming their kids very unique names and the general public wanting to keep the trend with their children.\n\nAlthough this plot effectively portrays popular names over time, it is not clear which points correspond to each year. To resolve this, I created an interactive version of my scatterplot above to make it easier to view which points are with which year, gender, and name. I removed the text labels to reduce clutter on the graph. Hovering over each point shows the `Year`, `Count`, `Gender_Full`, and `Name`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create an interactive version of the scatterplot above\nggplotly(ggplot(top_5_baby, aes(Year, Count)) +\n  geom_point(aes(color = Gender_Full, fill = Name)) +\n  labs(\n    x = \"Year of Birth\",\n    y = \"Number of Occurrences\",\n    title = \"Scatterplot of Occurrences vs. Year of Birth\",\n    subtitle = \"Range of years is 1910 to 2021\",\n    caption = \"Data: https://www.ssa.gov/oact/babynames/limits.html\"\n  ))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-fd4a71344bb1665f054f\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-fd4a71344bb1665f054f\">{\"x\":{\"data\":[{\"x\":[1910],\"y\":[1534],\"text\":\"Year: 1910<br />Count:  1534<br />Gender_Full: Female<br />Name: Anna\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(231,133,30,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Anna)\",\"legendgroup\":\"(Female,Anna)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1938],\"y\":[4215],\"text\":\"Year: 1938<br />Count:  4215<br />Gender_Full: Female<br />Name: Barbara\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(208,148,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Barbara)\",\"legendgroup\":\"(Female,Barbara)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2020],\"y\":[2185],\"text\":\"Year: 2020<br />Count:  2185<br />Gender_Full: Female<br />Name: Camila\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(194,155,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Camila)\",\"legendgroup\":\"(Female,Camila)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2003,2004,2005],\"y\":[3416,3416,3283],\"text\":[\"Year: 2003<br />Count:  3416<br />Gender_Full: Female<br />Name: Emily\",\"Year: 2004<br />Count:  3416<br />Gender_Full: Female<br />Name: Emily\",\"Year: 2005<br />Count:  3283<br />Gender_Full: Female<br />Name: Emily\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(109,177,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Emily)\",\"legendgroup\":\"(Female,Emily)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2014,2015,2016,2017,2018,2019,2021],\"y\":[2687,2724,2608,2740,2746,2395,2171],\"text\":[\"Year: 2014<br />Count:  2687<br />Gender_Full: Female<br />Name: Emma\",\"Year: 2015<br />Count:  2724<br />Gender_Full: Female<br />Name: Emma\",\"Year: 2016<br />Count:  2608<br />Gender_Full: Female<br />Name: Emma\",\"Year: 2017<br />Count:  2740<br />Gender_Full: Female<br />Name: Emma\",\"Year: 2018<br />Count:  2746<br />Gender_Full: Female<br />Name: Emma\",\"Year: 2019<br />Count:  2395<br />Gender_Full: Female<br />Name: Emma\",\"Year: 2021<br />Count:  2171<br />Gender_Full: Female<br />Name: Emma\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(69,181,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Emma)\",\"legendgroup\":\"(Female,Emma)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1910,1911,1913,1915,1916,1917,1918,1919],\"y\":[1604,1733,2694,4617,4656,4921,5410,4724],\"text\":[\"Year: 1910<br />Count:  1604<br />Gender_Full: Female<br />Name: Helen\",\"Year: 1911<br />Count:  1733<br />Gender_Full: Female<br />Name: Helen\",\"Year: 1913<br />Count:  2694<br />Gender_Full: Female<br />Name: Helen\",\"Year: 1915<br />Count:  4617<br />Gender_Full: Female<br />Name: Helen\",\"Year: 1916<br />Count:  4656<br />Gender_Full: Female<br />Name: Helen\",\"Year: 1917<br />Count:  4921<br />Gender_Full: Female<br />Name: Helen\",\"Year: 1918<br />Count:  5410<br />Gender_Full: Female<br />Name: Helen\",\"Year: 1919<br />Count:  4724<br />Gender_Full: Female<br />Name: Helen\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,188,81,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Helen)\",\"legendgroup\":\"(Female,Helen)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2009,2010,2011,2012,2013,2014],\"y\":[3162,3370,3064,3112,2794,2732],\"text\":[\"Year: 2009<br />Count:  3162<br />Gender_Full: Female<br />Name: Isabella\",\"Year: 2010<br />Count:  3370<br />Gender_Full: Female<br />Name: Isabella\",\"Year: 2011<br />Count:  3064<br />Gender_Full: Female<br />Name: Isabella\",\"Year: 2012<br />Count:  3112<br />Gender_Full: Female<br />Name: Isabella\",\"Year: 2013<br />Count:  2794<br />Gender_Full: Female<br />Name: Isabella\",\"Year: 2014<br />Count:  2732<br />Gender_Full: Female<br />Name: Isabella\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,190,110,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Isabella)\",\"legendgroup\":\"(Female,Isabella)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1971,1971,1972,1972,1973,1973,1974,1974,1975,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984],\"y\":[5456,4962,6065,5523,5649,4955,5673,4921,5323,4154,5570,5543,5295,5462,5612,5629,5813,5830,5519],\"text\":[\"Year: 1971<br />Count:  5456<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1971<br />Count:  4962<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1972<br />Count:  6065<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1972<br />Count:  5523<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1973<br />Count:  5649<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1973<br />Count:  4955<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1974<br />Count:  5673<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1974<br />Count:  4921<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1975<br />Count:  5323<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1975<br />Count:  4154<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1976<br />Count:  5570<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1977<br />Count:  5543<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1978<br />Count:  5295<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1979<br />Count:  5462<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1980<br />Count:  5612<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1981<br />Count:  5629<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1982<br />Count:  5813<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1983<br />Count:  5830<br />Gender_Full: Female<br />Name: Jennifer\",\"Year: 1984<br />Count:  5519<br />Gender_Full: Female<br />Name: Jennifer\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,188,214,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Jennifer)\",\"legendgroup\":\"(Female,Jennifer)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995],\"y\":[5537,5964,6846,6492,6539,6636,6952,6341,5552,5306,4621],\"text\":[\"Year: 1985<br />Count:  5537<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1986<br />Count:  5964<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1987<br />Count:  6846<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1988<br />Count:  6492<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1989<br />Count:  6539<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1990<br />Count:  6636<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1991<br />Count:  6952<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1992<br />Count:  6341<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1993<br />Count:  5552<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1994<br />Count:  5306<br />Gender_Full: Female<br />Name: Jessica\",\"Year: 1995<br />Count:  4621<br />Gender_Full: Female<br />Name: Jessica\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,184,229,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Jessica)\",\"legendgroup\":\"(Female,Jessica)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1947,1948,1949],\"y\":[7542,6946,6652],\"text\":[\"Year: 1947<br />Count:  7542<br />Gender_Full: Female<br />Name: Linda\",\"Year: 1948<br />Count:  6946<br />Gender_Full: Female<br />Name: Linda\",\"Year: 1949<br />Count:  6652<br />Gender_Full: Female<br />Name: Linda\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(156,141,255,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Linda)\",\"legendgroup\":\"(Female,Linda)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1910,1910,1911,1911,1912,1912,1913,1913,1914,1914,1915,1915,1916,1916,1917,1917,1918,1918,1919,1919,1920,1920,1921,1921,1922,1922,1923,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937],\"y\":[2913,1923,3188,2322,4106,2909,4739,3267,5981,4245,7970,5342,7730,5497,7988,5502,8184,5523,7428,5060,7650,5299,7772,5413,7302,5305,7035,5158,7200,6563,6008,6227,5741,5303,5187,4916,4535,4122,4091,3929,3933,4037],\"text\":[\"Year: 1910<br />Count:  2913<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1910<br />Count:  1923<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1911<br />Count:  3188<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1911<br />Count:  2322<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1912<br />Count:  4106<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1912<br />Count:  2909<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1913<br />Count:  4739<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1913<br />Count:  3267<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1914<br />Count:  5981<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1914<br />Count:  4245<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1915<br />Count:  7970<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1915<br />Count:  5342<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1916<br />Count:  7730<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1916<br />Count:  5497<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1917<br />Count:  7988<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1917<br />Count:  5502<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1918<br />Count:  8184<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1918<br />Count:  5523<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1919<br />Count:  7428<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1919<br />Count:  5060<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1920<br />Count:  7650<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1920<br />Count:  5299<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1921<br />Count:  7772<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1921<br />Count:  5413<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1922<br />Count:  7302<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1922<br />Count:  5305<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1923<br />Count:  7035<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1923<br />Count:  5158<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1924<br />Count:  7200<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1925<br />Count:  6563<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1926<br />Count:  6008<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1927<br />Count:  6227<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1928<br />Count:  5741<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1929<br />Count:  5303<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1930<br />Count:  5187<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1931<br />Count:  4916<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1932<br />Count:  4535<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1933<br />Count:  4122<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1934<br />Count:  4091<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1935<br />Count:  3929<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1936<br />Count:  3933<br />Gender_Full: Female<br />Name: Mary\",\"Year: 1937<br />Count:  4037<br />Gender_Full: Female<br />Name: Mary\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(186,130,255,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Mary)\",\"legendgroup\":\"(Female,Mary)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2013,2015,2016,2017,2018,2019],\"y\":[2604,2866,2801,2603,2502,2361],\"text\":[\"Year: 2013<br />Count:  2604<br />Gender_Full: Female<br />Name: Mia\",\"Year: 2015<br />Count:  2866<br />Gender_Full: Female<br />Name: Mia\",\"Year: 2016<br />Count:  2801<br />Gender_Full: Female<br />Name: Mia\",\"Year: 2017<br />Count:  2603<br />Gender_Full: Female<br />Name: Mia\",\"Year: 2018<br />Count:  2502<br />Gender_Full: Female<br />Name: Mia\",\"Year: 2019<br />Count:  2361<br />Gender_Full: Female<br />Name: Mia\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(210,119,255,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Mia)\",\"legendgroup\":\"(Female,Mia)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2016,2017,2018,2019,2020,2021],\"y\":[2550,2490,2467,2608,2350,2395],\"text\":[\"Year: 2016<br />Count:  2550<br />Gender_Full: Female<br />Name: Olivia\",\"Year: 2017<br />Count:  2490<br />Gender_Full: Female<br />Name: Olivia\",\"Year: 2018<br />Count:  2467<br />Gender_Full: Female<br />Name: Olivia\",\"Year: 2019<br />Count:  2608<br />Gender_Full: Female<br />Name: Olivia\",\"Year: 2020<br />Count:  2350<br />Gender_Full: Female<br />Name: Olivia\",\"Year: 2021<br />Count:  2395<br />Gender_Full: Female<br />Name: Olivia\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(250,98,217,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Olivia)\",\"legendgroup\":\"(Female,Olivia)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2010,2011,2012,2013,2014,2015,2016,2017],\"y\":[3362,3569,3644,3468,3182,2956,2759,2442],\"text\":[\"Year: 2010<br />Count:  3362<br />Gender_Full: Female<br />Name: Sophia\",\"Year: 2011<br />Count:  3569<br />Gender_Full: Female<br />Name: Sophia\",\"Year: 2012<br />Count:  3644<br />Gender_Full: Female<br />Name: Sophia\",\"Year: 2013<br />Count:  3468<br />Gender_Full: Female<br />Name: Sophia\",\"Year: 2014<br />Count:  3182<br />Gender_Full: Female<br />Name: Sophia\",\"Year: 2015<br />Count:  2956<br />Gender_Full: Female<br />Name: Sophia\",\"Year: 2016<br />Count:  2759<br />Gender_Full: Female<br />Name: Sophia\",\"Year: 2017<br />Count:  2442<br />Gender_Full: Female<br />Name: Sophia\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(255,104,158,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\"}},\"hoveron\":\"points\",\"name\":\"(Female,Sophia)\",\"legendgroup\":\"(Female,Sophia)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1999,2000,2001,2002,2003,2004],\"y\":[3598,3600,3447,3557,3458,3493],\"text\":[\"Year: 1999<br />Count:  3598<br />Gender_Full: Male<br />Name: Andrew\",\"Year: 2000<br />Count:  3600<br />Gender_Full: Male<br />Name: Andrew\",\"Year: 2001<br />Count:  3447<br />Gender_Full: Male<br />Name: Andrew\",\"Year: 2002<br />Count:  3557<br />Gender_Full: Male<br />Name: Andrew\",\"Year: 2003<br />Count:  3458<br />Gender_Full: Male<br />Name: Andrew\",\"Year: 2004<br />Count:  3493<br />Gender_Full: Male<br />Name: Andrew\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Andrew)\",\"legendgroup\":\"(Male,Andrew)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2005,2006,2007,2008,2009],\"y\":[3519,3690,3500,3172,3006],\"text\":[\"Year: 2005<br />Count:  3519<br />Gender_Full: Male<br />Name: Angel\",\"Year: 2006<br />Count:  3690<br />Gender_Full: Male<br />Name: Angel\",\"Year: 2007<br />Count:  3500<br />Gender_Full: Male<br />Name: Angel\",\"Year: 2008<br />Count:  3172<br />Gender_Full: Male<br />Name: Angel\",\"Year: 2009<br />Count:  3006<br />Gender_Full: Male<br />Name: Angel\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(240,126,78,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Angel)\",\"legendgroup\":\"(Male,Angel)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010],\"y\":[3908,3884,3808,3840,3827,3772,3935,3808,3749,3776,3787,3640,3088,2861],\"text\":[\"Year: 1997<br />Count:  3908<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 1998<br />Count:  3884<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 1999<br />Count:  3808<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2000<br />Count:  3840<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2001<br />Count:  3827<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2002<br />Count:  3772<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2003<br />Count:  3935<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2004<br />Count:  3808<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2005<br />Count:  3749<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2006<br />Count:  3776<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2007<br />Count:  3787<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2008<br />Count:  3640<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2009<br />Count:  3088<br />Gender_Full: Male<br />Name: Anthony\",\"Year: 2010<br />Count:  2861<br />Gender_Full: Male<br />Name: Anthony\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(221,141,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Anthony)\",\"legendgroup\":\"(Male,Anthony)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1994,1995,1996],\"y\":[4718,4782,5179,6066,6351,6486,6722,6453,6515,6463,6489,6620,5764,5234,4267,4098,3945],\"text\":[\"Year: 1979<br />Count:  4718<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1980<br />Count:  4782<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1981<br />Count:  5179<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1982<br />Count:  6066<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1983<br />Count:  6351<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1984<br />Count:  6486<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1985<br />Count:  6722<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1986<br />Count:  6453<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1987<br />Count:  6515<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1988<br />Count:  6463<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1989<br />Count:  6489<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1990<br />Count:  6620<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1991<br />Count:  5764<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1992<br />Count:  5234<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1994<br />Count:  4267<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1995<br />Count:  4098<br />Gender_Full: Male<br />Name: Christopher\",\"Year: 1996<br />Count:  3945<br />Gender_Full: Male<br />Name: Christopher\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(178,161,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Christopher)\",\"legendgroup\":\"(Male,Christopher)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012],\"y\":[5458,5435,5407,5406,5608,5768,5478,5364,5229,5117,5005,4705,4453,4318,4354,4342,4165,4133,4033,4170,3915,3830,3870,3754,3394,3137,2910,2688],\"text\":[\"Year: 1985<br />Count:  5458<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1986<br />Count:  5435<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1987<br />Count:  5407<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1988<br />Count:  5406<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1989<br />Count:  5608<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1990<br />Count:  5768<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1991<br />Count:  5478<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1992<br />Count:  5364<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1993<br />Count:  5229<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1994<br />Count:  5117<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1995<br />Count:  5005<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1996<br />Count:  4705<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1997<br />Count:  4453<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1998<br />Count:  4318<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 1999<br />Count:  4354<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2000<br />Count:  4342<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2001<br />Count:  4165<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2002<br />Count:  4133<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2003<br />Count:  4033<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2004<br />Count:  4170<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2005<br />Count:  3915<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2006<br />Count:  3830<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2007<br />Count:  3870<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2008<br />Count:  3754<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2009<br />Count:  3394<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2010<br />Count:  3137<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2011<br />Count:  2910<br />Gender_Full: Male<br />Name: Daniel\",\"Year: 2012<br />Count:  2688<br />Gender_Full: Male<br />Name: Daniel\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(159,167,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Daniel)\",\"legendgroup\":\"(Male,Daniel)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1976,1977,1978,1979,1980,1981,1982,1983,1984,1996,1997,2005,2006,2007,2008],\"y\":[7386,7118,7468,7455,7619,7919,8116,7950,7605,7536,6817,6758,6931,6482,6565,6376,5243,4634,4350,4425,4581,4876,5083,4937,5128,5001,5115,4001,3731,3274,3156,3123,2917],\"text\":[\"Year: 1955<br />Count:  7386<br />Gender_Full: Male<br />Name: David\",\"Year: 1956<br />Count:  7118<br />Gender_Full: Male<br />Name: David\",\"Year: 1957<br />Count:  7468<br />Gender_Full: Male<br />Name: David\",\"Year: 1958<br />Count:  7455<br />Gender_Full: Male<br />Name: David\",\"Year: 1959<br />Count:  7619<br />Gender_Full: Male<br />Name: David\",\"Year: 1960<br />Count:  7919<br />Gender_Full: Male<br />Name: David\",\"Year: 1961<br />Count:  8116<br />Gender_Full: Male<br />Name: David\",\"Year: 1962<br />Count:  7950<br />Gender_Full: Male<br />Name: David\",\"Year: 1963<br />Count:  7605<br />Gender_Full: Male<br />Name: David\",\"Year: 1964<br />Count:  7536<br />Gender_Full: Male<br />Name: David\",\"Year: 1965<br />Count:  6817<br />Gender_Full: Male<br />Name: David\",\"Year: 1966<br />Count:  6758<br />Gender_Full: Male<br />Name: David\",\"Year: 1967<br />Count:  6931<br />Gender_Full: Male<br />Name: David\",\"Year: 1968<br />Count:  6482<br />Gender_Full: Male<br />Name: David\",\"Year: 1969<br />Count:  6565<br />Gender_Full: Male<br />Name: David\",\"Year: 1970<br />Count:  6376<br />Gender_Full: Male<br />Name: David\",\"Year: 1971<br />Count:  5243<br />Gender_Full: Male<br />Name: David\",\"Year: 1972<br />Count:  4634<br />Gender_Full: Male<br />Name: David\",\"Year: 1976<br />Count:  4350<br />Gender_Full: Male<br />Name: David\",\"Year: 1977<br />Count:  4425<br />Gender_Full: Male<br />Name: David\",\"Year: 1978<br />Count:  4581<br />Gender_Full: Male<br />Name: David\",\"Year: 1979<br />Count:  4876<br />Gender_Full: Male<br />Name: David\",\"Year: 1980<br />Count:  5083<br />Gender_Full: Male<br />Name: David\",\"Year: 1981<br />Count:  4937<br />Gender_Full: Male<br />Name: David\",\"Year: 1982<br />Count:  5128<br />Gender_Full: Male<br />Name: David\",\"Year: 1983<br />Count:  5001<br />Gender_Full: Male<br />Name: David\",\"Year: 1984<br />Count:  5115<br />Gender_Full: Male<br />Name: David\",\"Year: 1996<br />Count:  4001<br />Gender_Full: Male<br />Name: David\",\"Year: 1997<br />Count:  3731<br />Gender_Full: Male<br />Name: David\",\"Year: 2005<br />Count:  3274<br />Gender_Full: Male<br />Name: David\",\"Year: 2006<br />Count:  3156<br />Gender_Full: Male<br />Name: David\",\"Year: 2007<br />Count:  3123<br />Gender_Full: Male<br />Name: David\",\"Year: 2008<br />Count:  2917<br />Gender_Full: Male<br />Name: David\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(137,172,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,David)\",\"legendgroup\":\"(Male,David)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2013],\"y\":[2667],\"text\":\"Year: 2013<br />Count:  2667<br />Gender_Full: Male<br />Name: Ethan\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,185,39,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Ethan)\",\"legendgroup\":\"(Male,Ethan)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1998,2001,2002,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015],\"y\":[3567,3385,3385,3199,3122,3028,2976,3355,3171,2981,2891,2718,2561],\"text\":[\"Year: 1998<br />Count:  3567<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2001<br />Count:  3385<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2002<br />Count:  3385<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2006<br />Count:  3199<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2007<br />Count:  3122<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2008<br />Count:  3028<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2009<br />Count:  2976<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2010<br />Count:  3355<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2011<br />Count:  3171<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2012<br />Count:  2981<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2013<br />Count:  2891<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2014<br />Count:  2718<br />Gender_Full: Male<br />Name: Jacob\",\"Year: 2015<br />Count:  2561<br />Gender_Full: Male<br />Name: Jacob\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,192,135,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Jacob)\",\"legendgroup\":\"(Male,Jacob)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1950],\"y\":[6199],\"text\":\"Year: 1950<br />Count:  6199<br />Gender_Full: Male<br />Name: James\",\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,193,157,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,James)\",\"legendgroup\":\"(Male,James)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1973,1974,1975,1976,1977,1978],\"y\":[4407,4781,4386,4348,4427,4304],\"text\":[\"Year: 1973<br />Count:  4407<br />Gender_Full: Male<br />Name: Jason\",\"Year: 1974<br />Count:  4781<br />Gender_Full: Male<br />Name: Jason\",\"Year: 1975<br />Count:  4386<br />Gender_Full: Male<br />Name: Jason\",\"Year: 1976<br />Count:  4348<br />Gender_Full: Male<br />Name: Jason\",\"Year: 1977<br />Count:  4427<br />Gender_Full: Male<br />Name: Jason\",\"Year: 1978<br />Count:  4304<br />Gender_Full: Male<br />Name: Jason\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,192,178,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Jason)\",\"legendgroup\":\"(Male,Jason)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2011,2012],\"y\":[2753,2871],\"text\":[\"Year: 2011<br />Count:  2753<br />Gender_Full: Male<br />Name: Jayden\",\"Year: 2012<br />Count:  2871<br />Gender_Full: Male<br />Name: Jayden\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Jayden)\",\"legendgroup\":\"(Male,Jayden)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1910,1911,1911,1912,1912,1913,1913,1914,1914,1915,1915,1916,1916,1917,1917,1918,1918,1919,1919,1920,1920,1921,1921,1922,1922,1923,1923,1924,1924,1925,1925,1926,1926,1927,1927,1928,1928,1929,1929,1930,1930,1931,1931,1932,1932,1933,1933,1934,1934,1935,1935,1936,1936,1937,1937,1938,1938,1939,1939,1940,1940,1941,1941,1942,1942,1943,1943,1944,1944,1945,1945,1946,1946,1947,1947,1948,1948,1949,1949,1950,1950,1951,1951,1952,1952,1953,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1963,1964,1964,1965,1966,1967,1967,1968,1969,1970],\"y\":[1326,1672,1624,3067,2708,3706,3149,5192,4289,6443,5180,6543,5370,6620,5759,7557,6058,6791,5764,7041,5963,7194,6035,7073,6105,7211,6228,7262,6318,6937,6134,6647,6186,6684,6232,6353,6134,6253,5892,6239,6063,5827,5445,5873,5241,5709,5028,5467,5006,5494,4952,5421,4909,5526,4998,5629,5256,5672,5074,6165,5253,6279,5653,7266,6575,7501,6442,6935,5967,7123,5769,8685,7202,9639,8047,8976,7300,8610,7029,8310,6857,8651,7038,8672,7088,8202,6797,8493,8556,8603,8612,8548,8712,8329,8754,8589,8672,7035,8893,7324,7895,6924,6380,5651,5955,5904,5568],\"text\":[\"Year: 1910<br />Count:  1326<br />Gender_Full: Male<br />Name: John\",\"Year: 1911<br />Count:  1672<br />Gender_Full: Male<br />Name: John\",\"Year: 1911<br />Count:  1624<br />Gender_Full: Male<br />Name: John\",\"Year: 1912<br />Count:  3067<br />Gender_Full: Male<br />Name: John\",\"Year: 1912<br />Count:  2708<br />Gender_Full: Male<br />Name: John\",\"Year: 1913<br />Count:  3706<br />Gender_Full: Male<br />Name: John\",\"Year: 1913<br />Count:  3149<br />Gender_Full: Male<br />Name: John\",\"Year: 1914<br />Count:  5192<br />Gender_Full: Male<br />Name: John\",\"Year: 1914<br />Count:  4289<br />Gender_Full: Male<br />Name: John\",\"Year: 1915<br />Count:  6443<br />Gender_Full: Male<br />Name: John\",\"Year: 1915<br />Count:  5180<br />Gender_Full: Male<br />Name: John\",\"Year: 1916<br />Count:  6543<br />Gender_Full: Male<br />Name: John\",\"Year: 1916<br />Count:  5370<br />Gender_Full: Male<br />Name: John\",\"Year: 1917<br />Count:  6620<br />Gender_Full: Male<br />Name: John\",\"Year: 1917<br />Count:  5759<br />Gender_Full: Male<br />Name: John\",\"Year: 1918<br />Count:  7557<br />Gender_Full: Male<br />Name: John\",\"Year: 1918<br />Count:  6058<br />Gender_Full: Male<br />Name: John\",\"Year: 1919<br />Count:  6791<br />Gender_Full: Male<br />Name: John\",\"Year: 1919<br />Count:  5764<br />Gender_Full: Male<br />Name: John\",\"Year: 1920<br />Count:  7041<br />Gender_Full: Male<br />Name: John\",\"Year: 1920<br />Count:  5963<br />Gender_Full: Male<br />Name: John\",\"Year: 1921<br />Count:  7194<br />Gender_Full: Male<br />Name: John\",\"Year: 1921<br />Count:  6035<br />Gender_Full: Male<br />Name: John\",\"Year: 1922<br />Count:  7073<br />Gender_Full: Male<br />Name: John\",\"Year: 1922<br />Count:  6105<br />Gender_Full: Male<br />Name: John\",\"Year: 1923<br />Count:  7211<br />Gender_Full: Male<br />Name: John\",\"Year: 1923<br />Count:  6228<br />Gender_Full: Male<br />Name: John\",\"Year: 1924<br />Count:  7262<br />Gender_Full: Male<br />Name: John\",\"Year: 1924<br />Count:  6318<br />Gender_Full: Male<br />Name: John\",\"Year: 1925<br />Count:  6937<br />Gender_Full: Male<br />Name: John\",\"Year: 1925<br />Count:  6134<br />Gender_Full: Male<br />Name: John\",\"Year: 1926<br />Count:  6647<br />Gender_Full: Male<br />Name: John\",\"Year: 1926<br />Count:  6186<br />Gender_Full: Male<br />Name: John\",\"Year: 1927<br />Count:  6684<br />Gender_Full: Male<br />Name: John\",\"Year: 1927<br />Count:  6232<br />Gender_Full: Male<br />Name: John\",\"Year: 1928<br />Count:  6353<br />Gender_Full: Male<br />Name: John\",\"Year: 1928<br />Count:  6134<br />Gender_Full: Male<br />Name: John\",\"Year: 1929<br />Count:  6253<br />Gender_Full: Male<br />Name: John\",\"Year: 1929<br />Count:  5892<br />Gender_Full: Male<br />Name: John\",\"Year: 1930<br />Count:  6239<br />Gender_Full: Male<br />Name: John\",\"Year: 1930<br />Count:  6063<br />Gender_Full: Male<br />Name: John\",\"Year: 1931<br />Count:  5827<br />Gender_Full: Male<br />Name: John\",\"Year: 1931<br />Count:  5445<br />Gender_Full: Male<br />Name: John\",\"Year: 1932<br />Count:  5873<br />Gender_Full: Male<br />Name: John\",\"Year: 1932<br />Count:  5241<br />Gender_Full: Male<br />Name: John\",\"Year: 1933<br />Count:  5709<br />Gender_Full: Male<br />Name: John\",\"Year: 1933<br />Count:  5028<br />Gender_Full: Male<br />Name: John\",\"Year: 1934<br />Count:  5467<br />Gender_Full: Male<br />Name: John\",\"Year: 1934<br />Count:  5006<br />Gender_Full: Male<br />Name: John\",\"Year: 1935<br />Count:  5494<br />Gender_Full: Male<br />Name: John\",\"Year: 1935<br />Count:  4952<br />Gender_Full: Male<br />Name: John\",\"Year: 1936<br />Count:  5421<br />Gender_Full: Male<br />Name: John\",\"Year: 1936<br />Count:  4909<br />Gender_Full: Male<br />Name: John\",\"Year: 1937<br />Count:  5526<br />Gender_Full: Male<br />Name: John\",\"Year: 1937<br />Count:  4998<br />Gender_Full: Male<br />Name: John\",\"Year: 1938<br />Count:  5629<br />Gender_Full: Male<br />Name: John\",\"Year: 1938<br />Count:  5256<br />Gender_Full: Male<br />Name: John\",\"Year: 1939<br />Count:  5672<br />Gender_Full: Male<br />Name: John\",\"Year: 1939<br />Count:  5074<br />Gender_Full: Male<br />Name: John\",\"Year: 1940<br />Count:  6165<br />Gender_Full: Male<br />Name: John\",\"Year: 1940<br />Count:  5253<br />Gender_Full: Male<br />Name: John\",\"Year: 1941<br />Count:  6279<br />Gender_Full: Male<br />Name: John\",\"Year: 1941<br />Count:  5653<br />Gender_Full: Male<br />Name: John\",\"Year: 1942<br />Count:  7266<br />Gender_Full: Male<br />Name: John\",\"Year: 1942<br />Count:  6575<br />Gender_Full: Male<br />Name: John\",\"Year: 1943<br />Count:  7501<br />Gender_Full: Male<br />Name: John\",\"Year: 1943<br />Count:  6442<br />Gender_Full: Male<br />Name: John\",\"Year: 1944<br />Count:  6935<br />Gender_Full: Male<br />Name: John\",\"Year: 1944<br />Count:  5967<br />Gender_Full: Male<br />Name: John\",\"Year: 1945<br />Count:  7123<br />Gender_Full: Male<br />Name: John\",\"Year: 1945<br />Count:  5769<br />Gender_Full: Male<br />Name: John\",\"Year: 1946<br />Count:  8685<br />Gender_Full: Male<br />Name: John\",\"Year: 1946<br />Count:  7202<br />Gender_Full: Male<br />Name: John\",\"Year: 1947<br />Count:  9639<br />Gender_Full: Male<br />Name: John\",\"Year: 1947<br />Count:  8047<br />Gender_Full: Male<br />Name: John\",\"Year: 1948<br />Count:  8976<br />Gender_Full: Male<br />Name: John\",\"Year: 1948<br />Count:  7300<br />Gender_Full: Male<br />Name: John\",\"Year: 1949<br />Count:  8610<br />Gender_Full: Male<br />Name: John\",\"Year: 1949<br />Count:  7029<br />Gender_Full: Male<br />Name: John\",\"Year: 1950<br />Count:  8310<br />Gender_Full: Male<br />Name: John\",\"Year: 1950<br />Count:  6857<br />Gender_Full: Male<br />Name: John\",\"Year: 1951<br />Count:  8651<br />Gender_Full: Male<br />Name: John\",\"Year: 1951<br />Count:  7038<br />Gender_Full: Male<br />Name: John\",\"Year: 1952<br />Count:  8672<br />Gender_Full: Male<br />Name: John\",\"Year: 1952<br />Count:  7088<br />Gender_Full: Male<br />Name: John\",\"Year: 1953<br />Count:  8202<br />Gender_Full: Male<br />Name: John\",\"Year: 1953<br />Count:  6797<br />Gender_Full: Male<br />Name: John\",\"Year: 1954<br />Count:  8493<br />Gender_Full: Male<br />Name: John\",\"Year: 1955<br />Count:  8556<br />Gender_Full: Male<br />Name: John\",\"Year: 1956<br />Count:  8603<br />Gender_Full: Male<br />Name: John\",\"Year: 1957<br />Count:  8612<br />Gender_Full: Male<br />Name: John\",\"Year: 1958<br />Count:  8548<br />Gender_Full: Male<br />Name: John\",\"Year: 1959<br />Count:  8712<br />Gender_Full: Male<br />Name: John\",\"Year: 1960<br />Count:  8329<br />Gender_Full: Male<br />Name: John\",\"Year: 1961<br />Count:  8754<br />Gender_Full: Male<br />Name: John\",\"Year: 1962<br />Count:  8589<br />Gender_Full: Male<br />Name: John\",\"Year: 1963<br />Count:  8672<br />Gender_Full: Male<br />Name: John\",\"Year: 1963<br />Count:  7035<br />Gender_Full: Male<br />Name: John\",\"Year: 1964<br />Count:  8893<br />Gender_Full: Male<br />Name: John\",\"Year: 1964<br />Count:  7324<br />Gender_Full: Male<br />Name: John\",\"Year: 1965<br />Count:  7895<br />Gender_Full: Male<br />Name: John\",\"Year: 1966<br />Count:  6924<br />Gender_Full: Male<br />Name: John\",\"Year: 1967<br />Count:  6380<br />Gender_Full: Male<br />Name: John\",\"Year: 1967<br />Count:  5651<br />Gender_Full: Male<br />Name: John\",\"Year: 1968<br />Count:  5955<br />Gender_Full: Male<br />Name: John\",\"Year: 1969<br />Count:  5904<br />Gender_Full: Male<br />Name: John\",\"Year: 1970<br />Count:  5568<br />Gender_Full: Male<br />Name: John\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,179,242,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,John)\",\"legendgroup\":\"(Male,John)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004],\"y\":[5023,4772,4571,4645,4156,4281,3871,3804,3426,3557,3377,3385],\"text\":[\"Year: 1993<br />Count:  5023<br />Gender_Full: Male<br />Name: Jose\",\"Year: 1994<br />Count:  4772<br />Gender_Full: Male<br />Name: Jose\",\"Year: 1995<br />Count:  4571<br />Gender_Full: Male<br />Name: Jose\",\"Year: 1996<br />Count:  4645<br />Gender_Full: Male<br />Name: Jose\",\"Year: 1997<br />Count:  4156<br />Gender_Full: Male<br />Name: Jose\",\"Year: 1998<br />Count:  4281<br />Gender_Full: Male<br />Name: Jose\",\"Year: 1999<br />Count:  3871<br />Gender_Full: Male<br />Name: Jose\",\"Year: 2000<br />Count:  3804<br />Gender_Full: Male<br />Name: Jose\",\"Year: 2001<br />Count:  3426<br />Gender_Full: Male<br />Name: Jose\",\"Year: 2002<br />Count:  3557<br />Gender_Full: Male<br />Name: Jose\",\"Year: 2003<br />Count:  3377<br />Gender_Full: Male<br />Name: Jose\",\"Year: 2004<br />Count:  3385<br />Gender_Full: Male<br />Name: Jose\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,171,252,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Jose)\",\"legendgroup\":\"(Male,Jose)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1912,1914],\"y\":[2250,3328],\"text\":[\"Year: 1912<br />Count:  2250<br />Gender_Full: Male<br />Name: Joseph\",\"Year: 1914<br />Count:  3328<br />Gender_Full: Male<br />Name: Joseph\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(41,163,255,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Joseph)\",\"legendgroup\":\"(Male,Joseph)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2018,2019,2020,2020,2021,2021],\"y\":[2415,2395,2420,2209,2469,2410],\"text\":[\"Year: 2018<br />Count:  2415<br />Gender_Full: Male<br />Name: Liam\",\"Year: 2019<br />Count:  2395<br />Gender_Full: Male<br />Name: Liam\",\"Year: 2020<br />Count:  2420<br />Gender_Full: Male<br />Name: Liam\",\"Year: 2020<br />Count:  2209<br />Gender_Full: Male<br />Name: Liam\",\"Year: 2021<br />Count:  2469<br />Gender_Full: Male<br />Name: Liam\",\"Year: 2021<br />Count:  2410<br />Gender_Full: Male<br />Name: Liam\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(115,152,255,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Liam)\",\"legendgroup\":\"(Male,Liam)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1951,1952,1952,1953,1953,1954,1954,1955,1955,1956,1956,1957,1957,1958,1958,1959,1959,1960,1960,1961,1961,1962,1962,1963,1963,1964,1964,1965,1965,1966,1966,1967,1967,1968,1968,1969,1969,1970,1970,1971,1971,1972,1972,1973,1973,1974,1974,1975,1975,1976,1976,1977,1977,1978,1978,1979,1979,1980,1980,1981,1981,1982,1982,1983,1983,1984,1984,1985,1985,1986,1986,1987,1987,1988,1988,1989,1989,1990,1990,1991,1991,1992,1992,1993,1993,1994,1995,1996,1997,1998,1999,2000],\"y\":[6931,7475,7064,7853,7819,8229,8083,8443,7865,8715,8262,9115,8250,9215,7630,8690,7457,8926,7390,9054,7927,8865,7880,9241,7821,8856,7984,8670,7836,8546,7685,8193,8134,8081,7900,8244,8005,8197,7952,6838,6824,6344,6254,5880,5737,6060,5881,6215,6043,6180,5922,6322,6009,6491,5855,6587,5779,6909,5801,7151,5993,7160,5852,7399,5964,7478,5887,7216,5852,7261,5788,7453,5726,7761,6046,7857,6086,8247,6164,7572,5649,6638,5206,5847,4694,5098,4782,4353,4311,4132,3759,3572],\"text\":[\"Year: 1951<br />Count:  6931<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1952<br />Count:  7475<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1952<br />Count:  7064<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1953<br />Count:  7853<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1953<br />Count:  7819<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1954<br />Count:  8229<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1954<br />Count:  8083<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1955<br />Count:  8443<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1955<br />Count:  7865<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1956<br />Count:  8715<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1956<br />Count:  8262<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1957<br />Count:  9115<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1957<br />Count:  8250<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1958<br />Count:  9215<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1958<br />Count:  7630<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1959<br />Count:  8690<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1959<br />Count:  7457<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1960<br />Count:  8926<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1960<br />Count:  7390<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1961<br />Count:  9054<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1961<br />Count:  7927<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1962<br />Count:  8865<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1962<br />Count:  7880<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1963<br />Count:  9241<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1963<br />Count:  7821<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1964<br />Count:  8856<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1964<br />Count:  7984<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1965<br />Count:  8670<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1965<br />Count:  7836<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1966<br />Count:  8546<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1966<br />Count:  7685<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1967<br />Count:  8193<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1967<br />Count:  8134<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1968<br />Count:  8081<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1968<br />Count:  7900<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1969<br />Count:  8244<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1969<br />Count:  8005<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1970<br />Count:  8197<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1970<br />Count:  7952<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1971<br />Count:  6838<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1971<br />Count:  6824<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1972<br />Count:  6344<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1972<br />Count:  6254<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1973<br />Count:  5880<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1973<br />Count:  5737<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1974<br />Count:  6060<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1974<br />Count:  5881<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1975<br />Count:  6215<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1975<br />Count:  6043<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1976<br />Count:  6180<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1976<br />Count:  5922<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1977<br />Count:  6322<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1977<br />Count:  6009<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1978<br />Count:  6491<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1978<br />Count:  5855<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1979<br />Count:  6587<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1979<br />Count:  5779<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1980<br />Count:  6909<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1980<br />Count:  5801<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1981<br />Count:  7151<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1981<br />Count:  5993<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1982<br />Count:  7160<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1982<br />Count:  5852<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1983<br />Count:  7399<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1983<br />Count:  5964<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1984<br />Count:  7478<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1984<br />Count:  5887<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1985<br />Count:  7216<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1985<br />Count:  5852<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1986<br />Count:  7261<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1986<br />Count:  5788<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1987<br />Count:  7453<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1987<br />Count:  5726<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1988<br />Count:  7761<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1988<br />Count:  6046<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1989<br />Count:  7857<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1989<br />Count:  6086<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1990<br />Count:  8247<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1990<br />Count:  6164<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1991<br />Count:  7572<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1991<br />Count:  5649<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1992<br />Count:  6638<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1992<br />Count:  5206<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1993<br />Count:  5847<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1993<br />Count:  4694<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1994<br />Count:  5098<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1995<br />Count:  4782<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1996<br />Count:  4353<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1997<br />Count:  4311<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1998<br />Count:  4132<br />Gender_Full: Male<br />Name: Michael\",\"Year: 1999<br />Count:  3759<br />Gender_Full: Male<br />Name: Michael\",\"Year: 2000<br />Count:  3572<br />Gender_Full: Male<br />Name: Michael\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(228,109,245,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Michael)\",\"legendgroup\":\"(Male,Michael)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2014,2015,2016,2017,2018,2019,2020,2021],\"y\":[2782,2774,2698,2527,2571,2677,2625,2591],\"text\":[\"Year: 2014<br />Count:  2782<br />Gender_Full: Male<br />Name: Noah\",\"Year: 2015<br />Count:  2774<br />Gender_Full: Male<br />Name: Noah\",\"Year: 2016<br />Count:  2698<br />Gender_Full: Male<br />Name: Noah\",\"Year: 2017<br />Count:  2527<br />Gender_Full: Male<br />Name: Noah\",\"Year: 2018<br />Count:  2571<br />Gender_Full: Male<br />Name: Noah\",\"Year: 2019<br />Count:  2677<br />Gender_Full: Male<br />Name: Noah\",\"Year: 2020<br />Count:  2625<br />Gender_Full: Male<br />Name: Noah\",\"Year: 2021<br />Count:  2591<br />Gender_Full: Male<br />Name: Noah\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(241,102,232,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Noah)\",\"legendgroup\":\"(Male,Noah)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1939,1940,1941,1942,1943,1944,1945,1946],\"y\":[4103,4371,4718,5369,5594,5418,5524,7155],\"text\":[\"Year: 1939<br />Count:  4103<br />Gender_Full: Male<br />Name: Richard\",\"Year: 1940<br />Count:  4371<br />Gender_Full: Male<br />Name: Richard\",\"Year: 1941<br />Count:  4718<br />Gender_Full: Male<br />Name: Richard\",\"Year: 1942<br />Count:  5369<br />Gender_Full: Male<br />Name: Richard\",\"Year: 1943<br />Count:  5594<br />Gender_Full: Male<br />Name: Richard\",\"Year: 1944<br />Count:  5418<br />Gender_Full: Male<br />Name: Richard\",\"Year: 1945<br />Count:  5524<br />Gender_Full: Male<br />Name: Richard\",\"Year: 1946<br />Count:  7155<br />Gender_Full: Male<br />Name: Richard\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(255,97,199,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Richard)\",\"legendgroup\":\"(Male,Richard)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1924,1925,1926,1927,1927,1928,1928,1929,1929,1930,1930,1931,1931,1932,1932,1933,1933,1934,1934,1935,1935,1936,1936,1937,1937,1938,1938,1939,1939,1940,1940,1941,1941,1942,1942,1943,1943,1944,1944,1945,1945,1946,1946,1947,1947,1948,1948,1949,1949,1950,1950,1951,1951,1952,1953,1954,1954,1955,1956,1957,1958,1959,1960,1961,1962,1965,1966,1968,1969,1970],\"y\":[5274,5321,5355,5518,5471,5524,5176,5447,5199,5761,5295,5952,5419,5755,5029,5362,4781,5591,4883,5762,5087,6120,5285,6530,5701,6477,5560,6115,5322,6283,5351,6564,5598,7663,6201,7923,6244,7225,5625,7607,5443,9295,6907,10026,7755,9011,6934,8850,6673,8626,6563,9053,6895,9219,9060,8914,6817,8815,8581,8470,8148,7693,7424,7479,7094,6398,5902,5889,6023,5668],\"text\":[\"Year: 1924<br />Count:  5274<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1925<br />Count:  5321<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1926<br />Count:  5355<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1927<br />Count:  5518<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1927<br />Count:  5471<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1928<br />Count:  5524<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1928<br />Count:  5176<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1929<br />Count:  5447<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1929<br />Count:  5199<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1930<br />Count:  5761<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1930<br />Count:  5295<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1931<br />Count:  5952<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1931<br />Count:  5419<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1932<br />Count:  5755<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1932<br />Count:  5029<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1933<br />Count:  5362<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1933<br />Count:  4781<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1934<br />Count:  5591<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1934<br />Count:  4883<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1935<br />Count:  5762<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1935<br />Count:  5087<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1936<br />Count:  6120<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1936<br />Count:  5285<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1937<br />Count:  6530<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1937<br />Count:  5701<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1938<br />Count:  6477<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1938<br />Count:  5560<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1939<br />Count:  6115<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1939<br />Count:  5322<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1940<br />Count:  6283<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1940<br />Count:  5351<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1941<br />Count:  6564<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1941<br />Count:  5598<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1942<br />Count:  7663<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1942<br />Count:  6201<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1943<br />Count:  7923<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1943<br />Count:  6244<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1944<br />Count:  7225<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1944<br />Count:  5625<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1945<br />Count:  7607<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1945<br />Count:  5443<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1946<br />Count:  9295<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1946<br />Count:  6907<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1947<br />Count: 10026<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1947<br />Count:  7755<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1948<br />Count:  9011<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1948<br />Count:  6934<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1949<br />Count:  8850<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1949<br />Count:  6673<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1950<br />Count:  8626<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1950<br />Count:  6563<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1951<br />Count:  9053<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1951<br />Count:  6895<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1952<br />Count:  9219<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1953<br />Count:  9060<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1954<br />Count:  8914<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1954<br />Count:  6817<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1955<br />Count:  8815<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1956<br />Count:  8581<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1957<br />Count:  8470<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1958<br />Count:  8148<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1959<br />Count:  7693<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1960<br />Count:  7424<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1961<br />Count:  7479<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1962<br />Count:  7094<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1965<br />Count:  6398<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1966<br />Count:  5902<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1968<br />Count:  5889<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1969<br />Count:  6023<br />Gender_Full: Male<br />Name: Robert\",\"Year: 1970<br />Count:  5668<br />Gender_Full: Male<br />Name: Robert\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(255,99,180,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,Robert)\",\"legendgroup\":\"(Male,Robert)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1920,1921,1922,1923,1924,1925,1926],\"y\":[5115,5441,5162,5374,5504,5365,5306],\"text\":[\"Year: 1920<br />Count:  5115<br />Gender_Full: Male<br />Name: William\",\"Year: 1921<br />Count:  5441<br />Gender_Full: Male<br />Name: William\",\"Year: 1922<br />Count:  5162<br />Gender_Full: Male<br />Name: William\",\"Year: 1923<br />Count:  5374<br />Gender_Full: Male<br />Name: William\",\"Year: 1924<br />Count:  5504<br />Gender_Full: Male<br />Name: William\",\"Year: 1925<br />Count:  5365<br />Gender_Full: Male<br />Name: William\",\"Year: 1926<br />Count:  5306<br />Gender_Full: Male<br />Name: William\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,111,135,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,191,196,1)\"}},\"hoveron\":\"points\",\"name\":\"(Male,William)\",\"legendgroup\":\"(Male,William)\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":43.7625570776256,\"r\":7.30593607305936,\"b\":40.1826484018265,\"l\":54.7945205479452},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"title\":{\"text\":\"Scatterplot of Occurrences vs. Year of Birth\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.5342465753425},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[1904.45,2026.55],\"tickmode\":\"array\",\"ticktext\":[\"1925\",\"1950\",\"1975\",\"2000\",\"2025\"],\"tickvals\":[1925,1950,1975,2000,2025],\"categoryorder\":\"array\",\"categoryarray\":[\"1925\",\"1950\",\"1975\",\"2000\",\"2025\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Year of Birth\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[891,10461],\"tickmode\":\"array\",\"ticktext\":[\"2500\",\"5000\",\"7500\",\"10000\"],\"tickvals\":[2500,5000,7500,10000],\"categoryorder\":\"array\",\"categoryarray\":[\"2500\",\"5000\",\"7500\",\"10000\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Number of Occurrences\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895},\"title\":{\"text\":\"Name<br />Gender_Full\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"2f7087f2974\":{\"x\":{},\"y\":{},\"colour\":{},\"fill\":{},\"type\":\"scatter\"}},\"cur_data\":\"2f7087f2974\",\"visdat\":{\"2f7087f2974\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nThis scatterplot looks a lot cleaner and clearer as to which names are in the top five for each year. As we saw previously, \"Mary\" consistently ranks in the top five from 1910 to around 1937, with its highest number of occurrences in 1918 at 8,184. Also aforementioned in the data import paragraph, we see \"Robert\" with the highest number of occurrences overall at 10,026 in 1947. \"John\" has the lowest number of occurrences overall at 1,326 in 1910. It's interesting to observe how the number of occurrences changed over time from under 2,500 in 1910 to reaching over 10,000 to slowly coming back to 2,500 by 2021. This demonstrates that even with the American population increasing over the last century, not all parents are naming their children after the latest trending names.\n\nThe below bar graph will answer my second research question about the names that have the largest differences in occurrences per region. I used the `change_baby` data frame I made earlier with `Name` as the independent variable and `difference` as the dependent variable. I added color by `Region` and faceting by `Region` as well to make it easier to see which region has the names that went through the most change in usage over time. Additionally, text labels were added to show the `difference` for each name.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a bar graph of difference vs. Name colored and faceted by Region\nggplot(change_baby, aes(Name, difference)) +\n  geom_col(aes(fill = Region)) +\n  facet_wrap(vars(Region), scales = \"free_x\") +\n  guides(x = guide_axis(angle = 90)) +\n  geom_text(\n    label = change_baby$difference,\n    check_overlap = T\n  ) +\n  labs(\n    x = \"Name\", \n    y = \"Difference\",\n    title = \"Bar Graph of Difference vs. Name\",\n    subtitle = \"Note: This only includes names with the largest differences \\n between minimum and maximum occurrences per region\",\n    caption = \"Data: https://www.ssa.gov/oact/babynames/limits.html\"\n  )\n```\n\n::: {.cell-output-display}\n![](AleaciaMessiah_FinalProject_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nLooking at this chart, it's clear that the differences in minimum and maximum occurrences between names from different regions vary immensely. We see the Middle Atlantic region went through the most changes, along with the West, Midwest, Southwest, New England, and South in that order. \"Robert\" went through the greatest change in usage overall with a `difference` of 10,021 occurrences in the Middle Atlantic region. Furthermore, \"Robert\" also appeared in the Midwest, New England, and West graphs with large differences. The names that went through the greatest change in usage for the Midwest, New England, South, Southwest, and West are \"Michael\" with a `difference` of 6,216, \"Robert\" with a `difference` of 3,890, \"James\" with a `difference` of 3,877, \"Linda\" with a `difference` of 5,054, and \"Michael\" with a `difference` of 8,257 respectively.\n\nWhat's intriguing about this graph is that there are more male names that went through a larger change in usage than female names. There are only one to two female names in each region except for New England. I wonder if girl names were generally not as popular as boy names or if there is a different reason why this phenomenon occurred?\n\nFinally, my last visualization is a scatterplot that answers my last research question of whether there are more popular girl names or popular boy names, \"popular\" meaning the name has a number of occurrences of 2,000 or more. We've already seen part of the answer from the last visualization above but the scatterplot below uses the `gender_baby` data frame created earlier with `Region` as the independent variable and `n` as the dependent variable. A color aesthetic is added to portray `Gender_Full` for each point as well as a text label showing `n` for each point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a scatterplot of n vs. Region with color by Gender_Full\nggplot(gender_baby, aes(Region, n)) +\n  geom_point(aes(color = Gender_Full)) +\n  geom_text(\n    label = gender_baby$n,\n    nudge_x = 0.25, nudge_y = 0.25,\n    check_overlap = T\n  ) +\n  labs(\n    x = \"Region of the United States\",\n    y = \"Number of Popular Names\",\n    title = \"Scatterplot of Popular Names vs. Region\",\n    subtitle = \"Color by Gender\",\n    caption = \"Data: https://www.ssa.gov/oact/babynames/limits.html\"\n  )\n```\n\n::: {.cell-output-display}\n![](AleaciaMessiah_FinalProject_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThis plot illustrates there are more popular boy names for each region than popular girl names. The Middle Atlantic region has 2,010 popular boy names which is the highest overall, with the Midwest with 1,425 names, the West with 1,419 names, the Southwest with 563 names, the South with 395 names, and New England with 217 names following after. The Middle Atlantic also has the most popular girl names with 931 names, with the Midwest with 631 names, the West with 611 names, the Southwest with 213 names, the South with 191 names, and New England with 31 names following shortly after.\n\nThe reason why the Middle Atlantic consistently has the most popular baby names and the largest changes in usage for each name is most likely because New York and Pennsylvania are part of the Middle Atlantic and the population in both places grew exponentially over time, especially with immigration. There was a variety of names given to immigrants when they entered the United States so it makes sense that some who had foreign names that were difficult to pronounce in English were given more \"American\" names as American citizens. The other plausible reason may be due to the \"baby boom\" as aforementioned previously and the huge increase in newborn babies led to popular names changing rapidly.\n\n## Reflection and Conclusion\n\n### *Reflection*\n\nOverall, I feel excited and proud of this project. I have always been interested in learning the origins of baby names (especially mine since the spelling of my name is not common) and looking at their popularity. The process with this project seemed relatively straightforward but had some complexity to it with the addition of the \\`Region\\` variable and re-coding the \\`State\\` and \\`Gender\\` variables. It was easier to compare the frequency of baby names across \\`Region\\` versus \\`State\\` but if I had more time, I would do a comparison with \\`State\\` to see how the frequency of names vary within each \\`State\\` in each region.\n\nMoreover, I had to change the analysis for my second research question in order to show the baby names that went through the most change in usage over time. Limiting only to the top five names in each region that went through the most change was the best option for visualization purposes; otherwise, it would've been difficult to clearly view the graph with every name and its \\`difference\\` in each region.\n\nI would love to know the reasons behind why boy names are more popular than girl names and why boy names changed more often in usage than girl names. The answer to these observations would be a wonderful starting point for the next steps to this project in the future. I would also like to go more in depth with the analysis by looking into the names that had the least number of occurrences (in this dataset it would be five) and researching why these names were not as popular as the others.\n\n### *Conclusion*\n\nFrom this Social Security Administration dataset on baby names, we can conclude that the top five baby names vary each year but in several years we see \"Mary\", \"John\", \"Robert\", \"Jennifer\", and \"Michael\" consistently appear towards the top. The range of occurrences for each name had gone from 2,500 to 10,000 between 1910 and 2021. The Middle Atlantic region has the greatest change in usage for names with \"Robert\" having the largest change overall. In general, male names had a larger difference in occurrences than female names. Finally, in regards to popularity, boy names tend to be more popular than girl names, with the Middle Atlantic region again ranking the highest with popular names overall (2,010 boy and 931 girl names). All of the research questions have been answered but in the future it would be beneficial to research more about the reasoning behind these phenomenons such as the popularity and change in usage of boy names.\n\n## Bibliography and Appendix\n\n### *Bibliography*\n\n\"International Programs - Two- Letter State Abbreviations.\" Accessed December 18, 2022. https://www.ssa.gov/international/coc-docs/states.html.\n\n\"Popular Baby Names.\" Accessed December 17, 2022. https://www.ssa.gov/oact/babynames/limits.html.\n\n\"State Regions.\" Accessed December 18, 2022. https://www.infoplease.com/us/states/regions-of-the-us.\n\nC. Sievert. Interactive Web-Based Data Visualization with R, plotly, and shiny. Chapman and Hall/CRC Florida, 2020.\n\nComtois D (2022). *summarytools: Tools to Quickly and Neatly Summarize Data*. R package version 1.0.1, <https://CRAN.R-project.org/package=summarytools>.\n\nH. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.\n\nR Core Team (2022). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.\n\nWickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). \"Welcome to the tidyverse.\" *Journal of Open Source Software*, *4*(43), 1686. doi:10.21105/joss.01686 <https://doi.org/10.21105/joss.01686>.\n\nWickham, H., & Grolemund, G. (2016). R for data science: Visualize, model, transform, tidy, and import data. OReilly Media.\n\nWickham H, Hester J, Chang W, Bryan J (2022). *devtools: Tools to Make Developing R Packages Easier*. R package version 2.4.5, <https://CRAN.R-project.org/package=devtools>.\n\n### *Appendix*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view session info\nsession_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.2.1 (2022-06-23 ucrt)\n os       Windows 10 x64 (build 19044)\n system   x86_64, mingw32\n ui       RTerm\n language (EN)\n collate  English_India.utf8\n ctype    English_India.utf8\n tz       America/New_York\n date     2022-12-20\n pandoc   2.18 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package       * version date (UTC) lib source\n assertthat      0.2.1   2019-03-21 [1] CRAN (R 4.2.1)\n backports       1.4.1   2021-12-13 [1] CRAN (R 4.2.0)\n base64enc       0.1-3   2015-07-28 [1] CRAN (R 4.2.0)\n bit             4.0.5   2022-11-15 [1] CRAN (R 4.2.2)\n bit64           4.0.5   2020-08-30 [1] CRAN (R 4.2.1)\n broom           1.0.2   2022-12-15 [1] CRAN (R 4.2.2)\n cachem          1.0.6   2021-08-19 [1] CRAN (R 4.2.1)\n callr           3.7.3   2022-11-02 [1] CRAN (R 4.2.2)\n cellranger      1.1.0   2016-07-27 [1] CRAN (R 4.2.1)\n checkmate       2.1.0   2022-04-21 [1] CRAN (R 4.2.1)\n cli             3.4.1   2022-09-23 [1] CRAN (R 4.2.2)\n codetools       0.2-18  2020-11-04 [2] CRAN (R 4.2.1)\n colorspace      2.0-3   2022-02-21 [1] CRAN (R 4.2.1)\n crayon          1.5.2   2022-09-29 [1] CRAN (R 4.2.1)\n crosstalk       1.2.0   2021-11-04 [1] CRAN (R 4.2.1)\n data.table      1.14.6  2022-11-16 [1] CRAN (R 4.2.2)\n DBI             1.1.3   2022-06-18 [1] CRAN (R 4.2.1)\n dbplyr          2.2.1   2022-06-27 [1] CRAN (R 4.2.1)\n devtools      * 2.4.5   2022-10-11 [1] CRAN (R 4.2.2)\n digest          0.6.31  2022-12-11 [1] CRAN (R 4.2.2)\n dplyr         * 1.0.10  2022-09-01 [1] CRAN (R 4.2.1)\n ellipsis        0.3.2   2021-04-29 [1] CRAN (R 4.2.1)\n evaluate        0.19    2022-12-13 [1] CRAN (R 4.2.2)\n fansi           1.0.3   2022-03-24 [1] CRAN (R 4.2.1)\n farver          2.1.1   2022-07-06 [1] CRAN (R 4.2.1)\n fastmap         1.1.0   2021-01-25 [1] CRAN (R 4.2.1)\n forcats       * 0.5.2   2022-08-19 [1] CRAN (R 4.2.1)\n fs              1.5.2   2021-12-08 [1] CRAN (R 4.2.1)\n gargle          1.2.1   2022-09-08 [1] CRAN (R 4.2.1)\n generics        0.1.3   2022-07-05 [1] CRAN (R 4.2.1)\n ggplot2       * 3.4.0   2022-11-04 [1] CRAN (R 4.2.2)\n glue            1.6.2   2022-02-24 [1] CRAN (R 4.2.1)\n googledrive     2.0.0   2021-07-08 [1] CRAN (R 4.2.1)\n googlesheets4   1.0.1   2022-08-13 [1] CRAN (R 4.2.1)\n gtable          0.3.1   2022-09-01 [1] CRAN (R 4.2.1)\n haven           2.5.1   2022-08-22 [1] CRAN (R 4.2.1)\n hms             1.1.2   2022-08-19 [1] CRAN (R 4.2.1)\n htmltools       0.5.4   2022-12-07 [1] CRAN (R 4.2.2)\n htmlwidgets     1.6.0   2022-12-15 [1] CRAN (R 4.2.2)\n httpuv          1.6.7   2022-12-14 [1] CRAN (R 4.2.2)\n httr            1.4.4   2022-08-17 [1] CRAN (R 4.2.1)\n jsonlite        1.8.4   2022-12-06 [1] CRAN (R 4.2.2)\n knitr           1.41    2022-11-18 [1] CRAN (R 4.2.2)\n labeling        0.4.2   2020-10-20 [1] CRAN (R 4.2.0)\n later           1.3.0   2021-08-18 [1] CRAN (R 4.2.1)\n lazyeval        0.2.2   2019-03-15 [1] CRAN (R 4.2.1)\n lifecycle       1.0.3   2022-10-07 [1] CRAN (R 4.2.1)\n lubridate       1.9.0   2022-11-06 [1] CRAN (R 4.2.2)\n magick          2.7.3   2021-08-18 [1] CRAN (R 4.2.1)\n magrittr        2.0.3   2022-03-30 [1] CRAN (R 4.2.1)\n MASS            7.3-57  2022-04-22 [2] CRAN (R 4.2.1)\n matrixStats     0.63.0  2022-11-18 [1] CRAN (R 4.2.2)\n memoise         2.0.1   2021-11-26 [1] CRAN (R 4.2.1)\n mime            0.12    2021-09-28 [1] CRAN (R 4.2.0)\n miniUI          0.1.1.1 2018-05-18 [1] CRAN (R 4.2.1)\n modelr          0.1.10  2022-11-11 [1] CRAN (R 4.2.2)\n munsell         0.5.0   2018-06-12 [1] CRAN (R 4.2.1)\n pander          0.6.5   2022-03-18 [1] CRAN (R 4.2.1)\n pillar          1.8.1   2022-08-19 [1] CRAN (R 4.2.1)\n pkgbuild        1.4.0   2022-11-27 [1] CRAN (R 4.2.2)\n pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 4.2.1)\n pkgload         1.3.2   2022-11-16 [1] CRAN (R 4.2.2)\n plotly        * 4.10.1  2022-11-07 [1] CRAN (R 4.2.2)\n plyr            1.8.8   2022-11-11 [1] CRAN (R 4.2.2)\n prettyunits     1.1.1   2020-01-24 [1] CRAN (R 4.2.1)\n processx        3.8.0   2022-10-26 [1] CRAN (R 4.2.1)\n profvis         0.3.7   2020-11-02 [1] CRAN (R 4.2.1)\n promises        1.2.0.1 2021-02-11 [1] CRAN (R 4.2.1)\n pryr            0.1.5   2021-07-26 [1] CRAN (R 4.2.1)\n ps              1.7.2   2022-10-26 [1] CRAN (R 4.2.1)\n purrr         * 0.3.5   2022-10-06 [1] CRAN (R 4.2.1)\n R6              2.5.1   2021-08-19 [1] CRAN (R 4.2.1)\n rapportools     1.1     2022-03-22 [1] CRAN (R 4.2.1)\n Rcpp            1.0.9   2022-07-08 [1] CRAN (R 4.2.1)\n readr         * 2.1.3   2022-10-01 [1] CRAN (R 4.2.1)\n readxl          1.4.1   2022-08-17 [1] CRAN (R 4.2.1)\n remotes         2.4.2   2021-11-30 [1] CRAN (R 4.2.1)\n reprex          2.0.2   2022-08-17 [1] CRAN (R 4.2.1)\n reshape2        1.4.4   2020-04-09 [1] CRAN (R 4.2.1)\n rlang           1.0.6   2022-09-24 [1] CRAN (R 4.2.1)\n rmarkdown       2.19    2022-12-15 [1] CRAN (R 4.2.2)\n rstudioapi      0.14    2022-08-22 [1] CRAN (R 4.2.1)\n rvest           1.0.3   2022-08-19 [1] CRAN (R 4.2.2)\n scales          1.2.1   2022-08-20 [1] CRAN (R 4.2.1)\n sessioninfo     1.2.2   2021-12-06 [1] CRAN (R 4.2.1)\n shiny           1.7.4   2022-12-15 [1] CRAN (R 4.2.2)\n stringi         1.7.8   2022-07-11 [1] CRAN (R 4.2.1)\n stringr       * 1.5.0   2022-12-02 [1] CRAN (R 4.2.2)\n summarytools  * 1.0.1   2022-05-20 [1] CRAN (R 4.2.1)\n tibble        * 3.1.8   2022-07-22 [1] CRAN (R 4.2.1)\n tidyr         * 1.2.1   2022-09-08 [1] CRAN (R 4.2.1)\n tidyselect      1.2.0   2022-10-10 [1] CRAN (R 4.2.1)\n tidyverse     * 1.3.2   2022-07-18 [1] CRAN (R 4.2.1)\n timechange      0.1.1   2022-11-04 [1] CRAN (R 4.2.2)\n tzdb            0.3.0   2022-03-28 [1] CRAN (R 4.2.1)\n urlchecker      1.0.1   2021-11-30 [1] CRAN (R 4.2.1)\n usethis       * 2.1.6   2022-05-25 [1] CRAN (R 4.2.1)\n utf8            1.2.2   2021-07-24 [1] CRAN (R 4.2.1)\n vctrs           0.5.1   2022-11-16 [1] CRAN (R 4.2.2)\n viridisLite     0.4.1   2022-08-22 [1] CRAN (R 4.2.1)\n vroom           1.6.0   2022-09-30 [1] CRAN (R 4.2.1)\n withr           2.5.0   2022-03-03 [1] CRAN (R 4.2.1)\n xfun            0.35    2022-11-16 [1] CRAN (R 4.2.2)\n xml2            1.3.3   2021-11-30 [1] CRAN (R 4.2.1)\n xtable          1.8-4   2019-04-21 [1] CRAN (R 4.2.1)\n yaml            2.3.6   2022-10-18 [1] CRAN (R 4.2.1)\n\n [1] C:/Users/srika/AppData/Local/R/win-library/4.2\n [2] C:/Program Files/R/R-4.2.1/library\n\n──────────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n:::",
    "supporting": [
      "AleaciaMessiah_FinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.0/htmlwidgets.js\"></script>\r\n<script src=\"../site_libs/plotly-binding-4.10.1/plotly.js\"></script>\r\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\r\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}