{
  "hash": "f2bfbf993564fda917dc9ea4aecdab54",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3 Guanhua Tan\"\nauthor: \"Guanhua Tan\"\ndesription: \"Tidy Data: Pivoting\"\ndate: \"09/24/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - eggs\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl) \n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1.  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2.  identify what needs to be done to tidy the current data\n3.  anticipate the shape of pivoted data\n4.  pivot the data into tidy format using `pivot_longer`\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   animal_weights.csv ⭐\n-   eggs_tidy.csv ⭐⭐ or organiceggpoultry.xls ⭐⭐⭐\n-   australian_marriage\\*.xls ⭐⭐⭐\n-   USA Households\\*.xlsx ⭐⭐⭐⭐\n-   sce_labor_chart_data_public.xlsx 🌟🌟🌟🌟🌟\n\n\n::: {.cell}\n\n```{.r .cell-code}\norganic_egg<-read_excel(\"_data/organiceggpoultry.xls\")\nview(organic_egg)\nnrow(organic_egg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 124\n```\n:::\n\n```{.r .cell-code}\nncol(organic_egg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 11\n```\n:::\n\n```{.r .cell-code}\nnrow(organic_egg)*ncol(organic_egg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1364\n```\n:::\n:::\n\n\n### Briefly describe the data\n\nDescribe the data, and be sure to comment on why you are planning to pivot it to make it \"tidy\"\n\nThis dataset has two different parts of information with the same timeline covering from 2004 to 2012. One part is about the prices of one dozen and 1/2 dozen of large eggs and extra large eggs. The other part is about the prices of \"whole\", \"B/S Breast\", \"Bone-in Breast\", \"Whole Legs\", \"Thighs\"--different parts of a Chicken. In order to clean, I would like to divide it into two datesets. One just includes the information about the eggs and the other the data about the Chicken. Additionally, I'd like to separate \"Year\" and \"Month\" to make very cell have its own value.\n\n## Anticipate the End Result\n### Challenge: Describe the final dimensions\n\nI'll divide the existing dataset into two distinct dataset. Existing data has 124 rows, 11 columns and 1364 cases. Expected data 1 will have 118 rows, 6 columns and 708 cases. Expected data 2 will have 118 rows, 7 columns and 826 cases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#create a new dataset about the eggs\ncolumn_names <-c(\"Date\", \"Extra_Large 12\",\"Extra_Large 6\",\"Large 12\", \"Large 6\")\neggs1  <- organic_egg[5:122, 1:5]\ncolnames(eggs1) =column_names\neggs1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 118 × 5\n   Date      `Extra_Large 12` `Extra_Large 6` `Large 12` `Large 6`\n   <chr>     <chr>            <chr>           <chr>      <chr>    \n 1 Jan 2004  230              132             230        126      \n 2 February  230              134.5           226.25     128.5    \n 3 March     230              137             225        131      \n 4 April     234.5            137             225        131      \n 5 May       236              137             225        131      \n 6 June      241              137             231.375    133.5    \n 7 July      241              137             233.5      133.5    \n 8 August    241              137             233.5      133.5    \n 9 September 241              135.875         233.5      129.75   \n10 October   241              135.5           233.5      128.5    \n# … with 108 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# separate year and month and remove \"/1\"\neggs2 <-eggs1  %>%\n  mutate(Date = str_remove(Date, \" /1\")) %>%\n  separate(Date, into=c(\"Month\", \"Year\"), sep=\" \") %>%\n  fill(Year) %>%\n  select(Year, Month, `Extra_Large 12`, `Extra_Large 6`, `Large 12`, `Large 6`)\neggs2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 118 × 6\n   Year  Month     `Extra_Large 12` `Extra_Large 6` `Large 12` `Large 6`\n   <chr> <chr>     <chr>            <chr>           <chr>      <chr>    \n 1 2004  Jan       230              132             230        126      \n 2 2004  February  230              134.5           226.25     128.5    \n 3 2004  March     230              137             225        131      \n 4 2004  April     234.5            137             225        131      \n 5 2004  May       236              137             225        131      \n 6 2004  June      241              137             231.375    133.5    \n 7 2004  July      241              137             233.5      133.5    \n 8 2004  August    241              137             233.5      133.5    \n 9 2004  September 241              135.875         233.5      129.75   \n10 2004  October   241              135.5           233.5      128.5    \n# … with 108 more rows\n```\n:::\n:::\n\n\n### Challenge: Pivot the Chosen Data\n\nThrough the function pivot_longer, I reorganized the dataset. I created three new columns--categorizes, quantiy, and prices. I separated original column names with the whitespace. I moved the type description under the column name \"categories\" and the numbers (12 or 6) under the column name \"quantity.\" All values were moved to columns \"prices.\" New column names reflect the characteristics of all values that makes the dataset clean and clear.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pivot_longer\neggs2 %>%\n  pivot_longer(cols = contains(\"Large\"), \n               names_to = c(\"categroies\", \"quanity\"),\n               names_sep=\" \",\n               values_to= \"prices\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 472 × 5\n   Year  Month    categroies  quanity prices\n   <chr> <chr>    <chr>       <chr>   <chr> \n 1 2004  Jan      Extra_Large 12      230   \n 2 2004  Jan      Extra_Large 6       132   \n 3 2004  Jan      Large       12      230   \n 4 2004  Jan      Large       6       126   \n 5 2004  February Extra_Large 12      230   \n 6 2004  February Extra_Large 6       134.5 \n 7 2004  February Large       12      226.25\n 8 2004  February Large       6       128.5 \n 9 2004  March    Extra_Large 12      230   \n10 2004  March    Extra_Large 6       137   \n# … with 462 more rows\n```\n:::\n\n```{.r .cell-code}\nnrow(eggs2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 118\n```\n:::\n\n```{.r .cell-code}\nncol(eggs2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\nnrow(eggs2)*ncol(eggs2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 708\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a new dataset about the Chicken and tidy data\norganic_egg<-read_excel(\"_data/organiceggpoultry.xls\")\ncolumn_names <-c(\"Date\", \"Extra_Large 12\",\"Extra_Large 6\",\"Large 12\", \"Large 6\", \"NA\", \"Whole\", \"B/S Breast\",\n\"Bone-in Breast\", \"Whole Legs\", \"Thighs\")\nChicken<-organic_egg[5:122, 1:11]\ncolnames(Chicken) = column_names\nChicken1 <- Chicken %>%\n  select(`Date`, `Whole`, `B/S Breast`, `Bone-in Breast`, `Whole Legs`, `Thighs`)\nChicken1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 118 × 6\n   Date      Whole   `B/S Breast` `Bone-in Breast` `Whole Legs` Thighs \n   <chr>     <chr>   <chr>        <chr>            <chr>        <chr>  \n 1 Jan 2004  197.5   645.5        too few          193.5        too few\n 2 February  197.5   642.5        too few          193.5        203    \n 3 March     209     642.5        too few          193.5        203    \n 4 April     212     642.5        too few          193.5        203    \n 5 May       214.5   642.5        too few          193.5        203    \n 6 June      216.375 641          too few          201.875      200.375\n 7 July      217     642.5        390.5            203.5        199.5  \n 8 August    217     642.5        390.5            203.5        199.5  \n 9 September 217     642.5        390.5            203.5        199.5  \n10 October   217     642.5        390.5            203.5        199.5  \n# … with 108 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#tidy data 2 Separate year and month, remove \"/1\"\nChicken_tidy <- Chicken1 %>%\n  mutate(Date = str_remove(Date, \"/1\")) %>%\n  separate(Date, into=c(\"Month\", \"Year\"), sep=\" \") %>%\n  fill(Year)\nChicken_tidy\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 118 × 7\n   Month     Year  Whole   `B/S Breast` `Bone-in Breast` `Whole Legs` Thighs \n   <chr>     <chr> <chr>   <chr>        <chr>            <chr>        <chr>  \n 1 Jan       2004  197.5   645.5        too few          193.5        too few\n 2 February  2004  197.5   642.5        too few          193.5        203    \n 3 March     2004  209     642.5        too few          193.5        203    \n 4 April     2004  212     642.5        too few          193.5        203    \n 5 May       2004  214.5   642.5        too few          193.5        203    \n 6 June      2004  216.375 641          too few          201.875      200.375\n 7 July      2004  217     642.5        390.5            203.5        199.5  \n 8 August    2004  217     642.5        390.5            203.5        199.5  \n 9 September 2004  217     642.5        390.5            203.5        199.5  \n10 October   2004  217     642.5        390.5            203.5        199.5  \n# … with 108 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# find and replace \"too few\"\nChicken_tidy[Chicken_tidy== \"too few\"] <- NA\nChicken_tidy %>%\n  select(Year, Month, Whole, `B/S Breast`, `Bone-in Breast`, `Whole Legs`, Thighs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 118 × 7\n   Year  Month     Whole   `B/S Breast` `Bone-in Breast` `Whole Legs` Thighs \n   <chr> <chr>     <chr>   <chr>        <chr>            <chr>        <chr>  \n 1 2004  Jan       197.5   645.5        <NA>             193.5        <NA>   \n 2 2004  February  197.5   642.5        <NA>             193.5        203    \n 3 2004  March     209     642.5        <NA>             193.5        203    \n 4 2004  April     212     642.5        <NA>             193.5        203    \n 5 2004  May       214.5   642.5        <NA>             193.5        203    \n 6 2004  June      216.375 641          <NA>             201.875      200.375\n 7 2004  July      217     642.5        390.5            203.5        199.5  \n 8 2004  August    217     642.5        390.5            203.5        199.5  \n 9 2004  September 217     642.5        390.5            203.5        199.5  \n10 2004  October   217     642.5        390.5            203.5        199.5  \n# … with 108 more rows\n```\n:::\n:::\n\n\nFinally, I got two different datasets that clearly reflect two distinct datas.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}