{
  "hash": "06146d38209ab82981c5bb3f2758a03b",
  "result": {
    "markdown": "---\ntitle: \"Challenge 8 Instructions\"\nauthor: \"Tejaswini_Ketineni\"\ndescription: \"Joining Data\"\ndate: \"12/06/2022\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(readr)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\n3)  mutate variables as needed (including sanity checks)\n4)  join two or more data sets and analyze some aspect of the joined data\n\n(be sure to only include the category tags for the data you use!)\n\n## Read in data\n\nThe required data is initially read.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\negg_chicken <- read_csv(\"_data/FAOSTAT_egg_chicken.csv\")\ncattle_dairy <- read_csv(\"_data/FAOSTAT_cattle_dairy.csv\")\nlivestock <- read_csv(\"_data/FAOSTAT_livestock.csv\")\n```\n:::\n\n\n### Briefly describe the data\n\nWhile we make efforts to understand the data, we see all the column names present, the sample head of the three datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(egg_chicken)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Domain Code\"      \"Domain\"           \"Area Code\"        \"Area\"            \n [5] \"Element Code\"     \"Element\"          \"Item Code\"        \"Item\"            \n [9] \"Year Code\"        \"Year\"             \"Unit\"             \"Value\"           \n[13] \"Flag\"             \"Flag Description\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(cattle_dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Domain Code\"      \"Domain\"           \"Area Code\"        \"Area\"            \n [5] \"Element Code\"     \"Element\"          \"Item Code\"        \"Item\"            \n [9] \"Year Code\"        \"Year\"             \"Unit\"             \"Value\"           \n[13] \"Flag\"             \"Flag Description\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(livestock)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Domain Code\"      \"Domain\"           \"Area Code\"        \"Area\"            \n [5] \"Element Code\"     \"Element\"          \"Item Code\"        \"Item\"            \n [9] \"Year Code\"        \"Year\"             \"Unit\"             \"Value\"           \n[13] \"Flag\"             \"Flag Description\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(cattle_dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QL      Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1961  1961 Head \n2 QL      Lives…       2 Afgh…    5420 Yield       882 Milk…    1961  1961 hg/An\n3 QL      Lives…       2 Afgh…    5510 Produc…     882 Milk…    1961  1961 tonn…\n4 QL      Lives…       2 Afgh…    5318 Milk A…     882 Milk…    1962  1962 Head \n5 QL      Lives…       2 Afgh…    5420 Yield       882 Milk…    1962  1962 hg/An\n6 QL      Lives…       2 Afgh…    5510 Produc…     882 Milk…    1962  1962 tonn…\n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(egg_chicken)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QL      Lives…       2 Afgh…    5313 Laying     1062 Eggs…    1961  1961 1000…\n2 QL      Lives…       2 Afgh…    5410 Yield      1062 Eggs…    1961  1961 100m…\n3 QL      Lives…       2 Afgh…    5510 Produc…    1062 Eggs…    1961  1961 tonn…\n4 QL      Lives…       2 Afgh…    5313 Laying     1062 Eggs…    1962  1962 1000…\n5 QL      Lives…       2 Afgh…    5410 Yield      1062 Eggs…    1962  1962 100m…\n6 QL      Lives…       2 Afgh…    5510 Produc…    1062 Eggs…    1962  1962 tonn…\n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(livestock)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 14\n  Domai…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year Unit \n  <chr>   <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl> <chr>\n1 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1961  1961 Head \n2 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1962  1962 Head \n3 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1963  1963 Head \n4 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1964  1964 Head \n5 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1965  1965 Head \n6 QA      Live …       2 Afgh…    5111 Stocks     1107 Asses    1966  1966 Head \n# … with 3 more variables: Value <dbl>, Flag <chr>, `Flag Description` <chr>,\n#   and abbreviated variable names ¹​`Domain Code`, ²​`Area Code`,\n#   ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(egg_chicken$Item)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nEggs, hen, in shell \n              38170 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(cattle_dairy$Item)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMilk, whole fresh cow \n                36449 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(livestock$Item)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    Asses Buffaloes    Camels    Cattle     Goats    Horses     Mules      Pigs \n     8571      3505      3265     13086     12498     11104      6153     12015 \n    Sheep \n    11919 \n```\n:::\n:::\n\n\nwe observe that only in live stock table we have multiple items.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall(egg_chicken$Year==egg_chicken$`Year Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nall(cattle_dairy$Year==cattle_dairy$`Year Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nall(livestock$Year==livestock$`Year Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n\nwe observe duplicated columns in the data sets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(egg_chicken,function(x)sum(is.na(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Domain Code           Domain        Area Code             Area \n               0                0                0                0 \n    Element Code          Element        Item Code             Item \n               0                0                0                0 \n       Year Code             Year             Unit            Value \n               0                0                0               40 \n            Flag Flag Description \n            7548                0 \n```\n:::\n:::\n\n\nwe see that there are 40 missing values of value and 7548 missing values of flag description.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(cattle_dairy,function(x)sum(is.na(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Domain Code           Domain        Area Code             Area \n               0                0                0                0 \n    Element Code          Element        Item Code             Item \n               0                0                0                0 \n       Year Code             Year             Unit            Value \n               0                0                0               74 \n            Flag Flag Description \n           10044                0 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(livestock,function(x)sum(is.na(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Domain Code           Domain        Area Code             Area \n               0                0                0                0 \n    Element Code          Element        Item Code             Item \n               0                0                0                0 \n       Year Code             Year             Unit            Value \n               0                0                0             1301 \n            Flag Flag Description \n           38270                0 \n```\n:::\n:::\n\n\nIn live_stock there are 1301 missing values in values and 38270 missing values in flags \n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(egg_chicken,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.70, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>egg_chicken</h4>\n<strong>Dimensions</strong>: 38170 x 14\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">Domain Code\n[character]</td>\n      <td align=\"left\">1. QL</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMPguJBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDcrMDA6MDCJc5ypAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Domain\n[character]</td>\n      <td align=\"left\">1. Livestock Primary</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMPguJBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDcrMDA6MDCJc5ypAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 771.1 (1709.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 143 &le; 5504</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 145 (2.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">245 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAAuklEQVR42u3bQQqAIBQA0Qzv2B3qPHWHTlnbX9FCgmQ+83YihAOaK8sxZDX2XoBppkU1DrbHwVtK7wW2iQH1OjVdRnvvlX6SeEOaRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRpQ4rX7/xH/WppdaqLS2l1qJN6RpRKYRwf6Qd4/rIFwGJc5t+Kf181taLonPmmlEJ5RiDjhJ+6vIAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ3KzAwOjAw+C4kFQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMIlznKkAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Afghanistan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Albania</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Algeria</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. American Samoa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Americas</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Angola</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Antigua and Barbuda</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Argentina</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Asia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 235 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">36430</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">95.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHAAAAC9CAQAAADBnzGqAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAABQElEQVR42u3XQQrCQBQFQSPe0ZN5CE+p24kgggixP1WuQkDSZATf9jjNdj76AQQK/OCxfG5DfpBr0/g3KLBOYJ3AOoF1AusE1o0P3NaFtB39ND+yNo1/g7vAKYP3beBEAusE1gmsE1gnsE5g3fhAg7fO4K0TWCewTmCdwDqBdQLr7ME6e7BOYJ3AOoF1AusE1gmsGx9o8NYZvHUC6wTWCawTWCewTmDd+ECDt87grRNYJ7BOYJ3AOoF1AuvswTp7sE5gncA6gXUC6wTWCawbH2jw1hm8dQLrBNYJrBNYJ7BOYJ09WGcP1gmsE1gnsE5gncA6gXXjAw3eOoO3TmCdwDqBdQLrBNYJrBsfaPDWXdaLMYN3OYqX/Z3r0Y/2A/fd1fgjKrBOYJ3AOoF1Aute/ovev/uWP7ZNGRDvjD+iAuue6xM2YfTDG6AAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMDhUMTQ6Mjk6NDcrMDA6MDD4LiQVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTA4VDE0OjI5OjQ3KzAwOjAwiXOcqQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 5411.4 (80.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5313 &le; 5410 &le; 5510</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 197 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5313</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12679</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5410</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12651</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5510</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12840</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADAAAAA5CAQAAADaBGDEAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAAf0lEQVRYw+2VUQqAMAxDreyOHsLz6B12Sv1tC07QZtCS/JVBHjSjkWvBagX7FwA0PZwhgeyibZp93H7bdzfnz4AAAgioAHDHrn9zGcicVgky1Z5zV3QEFc4jgIVDAAEEVAWwcF4FKBy7ivDC8Tnm/6YEEEBABcDcwkEofwZwwA0xNhINZmLv/AAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMPguJBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDcrMDA6MDCJc5ypAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Laying</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Production</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Yield</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12679</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12840</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12651</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADAAAAA5CAQAAADaBGDEAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAAgklEQVRYw+2X0QmAMAxEjXRHh+g8ukOn1N8kHwqaKyTe/YXCPUhKrpVzwWoF+xcANF0cIQPpom2aPdw+2w9X558BAQQQUAHglt1453Ijs1olyFR7zm3RHvUCUK0IDxw/x/zXlAACCKgAYOA8ChA43TSCPxwCCCDgF4C5gYNQ/hnAARd/zhINxNsOzQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMPguJBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDcrMDA6MDCJc5ypAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item Code\n[numeric]</td>\n      <td align=\"left\">1 distinct value</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1062</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">38170</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMPguJBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDcrMDA6MDCJc5ypAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item\n[character]</td>\n      <td align=\"left\">1. Eggs, hen, in shell</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMPguJBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDcrMDA6MDCJc5ypAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.5 (16.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAA5ElEQVR42u3bQQ7CIBQAUTG9o3fQ8+gdPKVuEWORtBTmZ2bHpuGlLSRY0+sUtfPoCUiTlrfkgzR4MvfmF/9WTDm/wNJ0pe6Uy8foWR2vdSitTtmzg+9aT0pZ4GVEGrHAtE3LSPs+NA2tPvU996GutPYtdOaKu0aaeq3Ay4g0YtKISSMmjZg0YtKISSMWmDb0YHx7X+cC2W8AcNraqUDgB1IaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBELTEv55zKPqf/Z9E/X7GufhNf8LPADKY3YG9kRHia/c9x4AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ3KzAwOjAw+C4kFQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMIlznKkAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.5 (16.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHS9SruueAAAA5ElEQVR42u3bQQ7CIBQAUTG9o3fQ8+gdPKVuEWORtBTmZ2bHpuGlLSRY0+sUtfPoCUiTlrfkgzR4MvfmF/9WTDm/wNJ0pe6Uy8foWR2vdSitTtmzg+9aT0pZ4GVEGrHAtE3LSPs+NA2tPvU996GutPYtdOaKu0aaeq3Ay4g0YtKISSMmjZg0YtKISSMWmDb0YHx7X+cC2W8AcNraqUDgB1IaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBELTEv55zKPqf/Z9E/X7GufhNf8LPADKY3YG9kRHia/c9x4AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ3KzAwOjAw+C4kFQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMIlznKkAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Unit\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 1000 Head</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 100mg/An</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. tonnes</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12679</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12651</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12840</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADAAAAA5CAQAAADaBGDEAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAf0lEQVRYw+2VUQqAMAxDreyOHsLz6B12Sv1tC07QZtCS/JVBHjSjkWvBagX7FwA0PZwhgeyibZp93H7bdzfnz4AAAgioAHDHrn9zGcicVgky1Z5zV3QEFc4jgIVDAAEEVAWwcF4FKBy7ivDC8Tnm/6YEEEBABcDcwkEofwZwwA0xNhINZmLv/AAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0NyswMDowMPguJBUAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDcrMDA6MDCJc5ypAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Value\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 291341.2 (2232761)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 31996 &le; 76769955</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 91235.8 (7.7)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">21325 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAq0lEQVR42u3bsQ3CMBBAUYKyI0MwD+zAlNAhhwpEYX3rvcpWmvuSU972PK3qPHsAadJG+3i5H3686zZ7uN+NAfvx0+V9esye8m8LP0hpRdKKpBVJK5JWJK1IWpG0ImlF0oqkFUkrklYkrUhakbQiaUXSiqQVSSuSViStSFqRtCJpRdKKpBVJK5JWJK1IWpG0ImlFC6d9rMGOy6+34qL9sJW8Fef/zsIPUlrRCxSsCN+uq3WWAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwDmZU/AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMH877EAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">40\n(0.1%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. *</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Fc</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Im</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. M</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1435</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3186</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10538</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">34.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13344</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">43.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2079</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">40</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADoAAABrCAQAAACMYFnxAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAA1UlEQVRo3u3aQQ6CQBBEUcdwRw/hefQOnhI2mnTjgJB0SYf+tSGExQvMDAWENl7+n+sBZiF0sDtPM8D3FgvZuTP4Q7f39iU90zpjCgoKCpoHnd3wtTf6T5qtnOA2c7HO8Zf3sfCUFl3oCyVuEz/OdZYMKCgoaB6UEpdmU4nvz3rtbyjx/fk1M+osGVBQUNBu6FNpRH3aibmMkj79jp8rdZYMKCgoaB6UEpdmtcSjv2h3UV/iuvGts2RAQUFB86CUuDQOlb6JpzpTUFBQUNDzoo1f4k+HTh+HIV2fnQylAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwDmZU/AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMH877EAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">7548\n(19.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag Description\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Aggregate, may include of</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Calculated data</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Data not available</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. FAO data based on imputat</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. FAO estimate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Official data</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Unofficial figure</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3186</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13344</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">35.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">40</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2079</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10538</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">27.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7548</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">19.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1435</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADEAAAB7CAQAAAB3VqCdAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAA40lEQVRo3u3YUQ6DIBBF0dK4xy7C9dQ9dJXtpwMRxckAyeudP6PhRIfwhPR99K5nd0GEWOzFdtCYNXmGtQMt+a1X8egn4C00egEBAaFKFMtgxLJXVrLLrmvdPiw76ugP9Y77VzAf5CKSfJV3VGPSQkBATCHIi8bKiMC8mPgWEBAQEP9HaERSdQvjO027JPYtTORvgsaMgoCAUCXYJTVW2KlaPcKCTtXOeqgxaSEgIFQJIqmxnJF0Zw/liqR7HdOYtBAQEFMI8qKxKnkRd6ZWyYvYjmhMWggICFVidCT1KY1eDCB+RUInKi1J8YEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDAOZlT8AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwfzvsQAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-12-08</p>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(livestock,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.70, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>livestock</h4>\n<strong>Dimensions</strong>: 82116 x 14\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">Domain Code\n[character]</td>\n      <td align=\"left\">1. QA</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Domain\n[character]</td>\n      <td align=\"left\">1. Live Animals</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 912.7 (1855)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 146 &le; 5504</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 148 (2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">253 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAu0lEQVR42u3bQQqAIBQA0Qzv2B3qPHWHTlnbX9FCgmQ+83YihANKbizHkNXYewGmmRbVONgeB28pvRfYJgbU69R0Ge29V/pJ4g1pGpFpRKYRmUZkGpFpRKYRmUZkGpFpRKYRmUZkGpFpRKYRmUZkGpFpRKYRmUZkGpFpRKYRmUZkGpFpRKYRmUZUv3/iP2vTwxhUWtvDmMQb0jQi04hMI0qcBvtl3z3uJ+F2UuLchn9aP7+l5ZL4rJlGdAJSHg44NjiYRwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Asia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. China, mainland</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Eastern Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Eastern Asia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Eastern Europe</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Egypt</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Europe</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. India</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Northern Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 243 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">76896</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">93.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG8AAAC9CAQAAAAXOuvPAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAABQklEQVR42u3XQYrCUBRFQSPusVfWi3CV6elPQyYqxPOochQCkkO+4N3222T3qx9AnrxT+/L5HfFDXIuGvz15ZfLK5JXJK5NXJq9seN62bqDt6qf5iLVo+Ns75M2Ys6d588grk1cmr0xembwyeWXD88zZMnO2TF6ZvDJ5ZfLK5JXJK7P3yuy9Mnll8srklckrk1cmr2x4njlbZs6WySuTVyavTF6ZvDJ5ZcPzzNkyc7ZMXpm8Mnll8srklckrs/fK7L0yeWXyyuSVySuTVyavbHieOVtmzpbJK5NXJq9MXpm8Mnll9l6ZvVcmr0xembwyeWXyyuSVDc8zZ8vM2TJ5ZfLK5JXJK5NXJq9seJ45W/ZYL4bM2eUQPo53fq5+tLc9D1fDD6e8Mnll8srklckr+/ef8/nat3ytbcZIODP8cMor+wNzzzZhe592HQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element Code\n[numeric]</td>\n      <td align=\"left\">1 distinct value</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5111</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element\n[character]</td>\n      <td align=\"left\">1. Stocks</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1017.7 (83.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">866 &le; 1034 &le; 1126</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 120 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">866</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">13086</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">15.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">946</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3505</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">976</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">11919</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">14.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1016</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12498</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">15.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1034</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12015</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">14.6%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1096</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">11104</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">13.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1107</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">8571</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1110</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">6153</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">7.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1126</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3265</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAB0AAACcCAQAAAApdmj5AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAwklEQVRo3u2Z3Q2DMAwGk4od2YHOAzswJbxUVTDB+SkStXXfGxKH4pgjEOIWevPqJh9Ch/RgKRY+xQs0hFEF1z+oFRRURNzDawMaU1li8fT07LsGPH8v+i4PIO9rXcXm+goKKuJF9XyOD4CGpVnOg7m+goKK+Fb9ODDewkGto759ZWkGBf3Es+ryI7xa9fMsmOsrKKiIT9XzO20Vql/Vb66voD5Rb75qe+Kqr3rl5voKCiriRXV+e4GCqrlLdQu1/oDuIzIz4fC9fcQAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDAOZlT8AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwfzvsQAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Asses</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Buffaloes</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Camels</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Cattle</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Goats</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Horses</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Mules</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Pigs</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Sheep</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8571</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3505</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3265</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13086</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12498</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11104</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">13.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6153</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">7.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12015</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11919</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAB0AAACcCAQAAAApdmj5AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAw0lEQVRo3u2XUQ6EIAwFwewdPYTnce/gKfVrN1ApIpLstpn3pQmjLXUSjHvozdRN/gh9pTdvpfElfq52DQ1hLoDbX/UKCioivuHtBhpTF+Ll8nT1qILX70OX6wLKvrZ1bG6uoKAiqN70VnNzBQUV8aK6XqXa61zl8p0wN1dQnyi+KsFXUF+oZ9XlybxZ9fMumJsrKKiIN9VrP95V1eudm5srqE/Um695cntvnMLlPpibKyioCKoXg+qg3tBRqlvo9QF6AMiXNHZxIQFgAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwDmZU/AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMH877EAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.4 (16.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAA30lEQVR42u3bwQ3CMBAAQYzSIz1APdADVcL3CMKS5XDWnnZ/+QQPiY1kkvY6Ve28egDSpMW2eNCSP/w+PdFvuyHHE25DZzq8y8fRc/i4Vypt/iqNlHzVRr712QovI9KI/XWu5S4bXdrxQ8lcNrq0+d+ZlZR9heeaNGLSiEkjJo2YNGLSiEkjJo1YYdrijfHZvnZzwn8AcFpvL6bwDSmNmDRi0ohJIyaNmDRi0ohJIyaNmDRi0ohJIyaNmDRi0ohJIyaNmDRi0ogVprX4uMwD/2r9NTzt0/CanxW+IaURewNvgBr8VR8OGAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.4 (16.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAA30lEQVR42u3bwQ3CMBAAQYzSIz1APdADVcL3CMKS5XDWnnZ/+QQPiY1kkvY6Ve28egDSpMW2eNCSP/w+PdFvuyHHE25DZzq8y8fRc/i4Vypt/iqNlHzVRr712QovI9KI/XWu5S4bXdrxQ8lcNrq0+d+ZlZR9heeaNGLSiEkjJo2YNGLSiEkjJo1YYdrijfHZvnZzwn8AcFpvL6bwDSmNmDRi0ohJIyaNmDRi0ohJIyaNmDRi0ohJIyaNmDRi0ohJIyaNmDRi0ogVprX4uMwD/2r9NTzt0/CanxW+IaURewNvgBr8VR8OGAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Unit\n[character]</td>\n      <td align=\"left\">1. Head</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Value\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 11625569 (64779790)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 224667 &le; 1489744504</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2364200 (5.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">43667 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAr0lEQVR42u3bMQ6CQBBAUTHc0UN4HryDp9TOLCYUaEEe+a+CbDM/sOVMr8tZXY8eoLTSRvP48lhdvPt09HD7jQHz+uj2eXoePeXfTvxDliYqTVSaqDRRaaLSRKWJShOVJipNVJqoNFFpotJEpYlKE5UmKk1Umqg0UWmi0kSliUoTlSYqTVSaqDRRaaLSRKWJShOVJpq3jxZ8KfYrbXv5dTHW7ocPMBkT/+LEd6000RsQhgrhBdMm/gAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">1301\n(1.6%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. *</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Im</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. M</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2667</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12567</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">28.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">24550</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">56.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2877</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1185</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEcAAABaCAQAAABA8YPRAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAA2ElEQVRo3u3ZQQqDMBCFYSPe0UN4Hr2Dp2w3tU4GlNaGmSf930px4UcmkIeWR6eUPhsA5/MM9mapNtJUYgj2pUP9aHxfrbHL8orYsODAgQMHjlLEOO4IzTk49xR7vAc1ChcrUB7W/FOPb1HXDuvXt2mz68SGBQcOHDhwlCLGoX75/Ef9uhwzlGb162rq3So2LDhw4MCBoxQxDvXL5671K+r34wGnrl8Z+0hsWHDgwIEDRyliHOqXz93qV3zt2uJWZ0z4/nXCyQ4cOHDgwFGKct/Jj9iw4JzlCd+mHVVsYtxNAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwDmZU/AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMH877EAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">38270\n(46.6%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag Description\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Aggregate, may include of</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Data not available</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. FAO data based on imputat</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. FAO estimate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Official data</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Unofficial figure</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12567</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1185</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2877</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">24550</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">29.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38270</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">46.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2667</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAD0AAABrCAQAAABuvEKIAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAA1UlEQVRo3u3ZWw6DIBCF4dK4RxbR9dg9uEp8ajKYhovgQJj/vDXGfEE0c6ouvEblPUw2Sm/yxze78R/Xxklgiw/55IlH11Xb3GtoaGjoNejL+Og7INJxcow1TsSCSG2Wvd7DrtgSZ1k1NDQ0NDR0WWxWhaib/YpC67uDslxW7TPvFR6kNQMNDQ29Bs1fe+X8ndd3Uzfnq74CpFN7n9h8uKChoaHXoKkKyulaFQoiLmzHqpBPfCfZfLigoaGh16CpCsrhK4ByoKGhoaEbM0tV0I3NvR5InwWzIkkW1nw3AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwDmZU/AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMH877EAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-12-08</p>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(cattle_dairy,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.70, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>cattle_dairy</h4>\n<strong>Dimensions</strong>: 36449 x 14\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">Domain Code\n[character]</td>\n      <td align=\"left\">1. QL</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">36449</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Domain\n[character]</td>\n      <td align=\"left\">1. Livestock Primary</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">36449</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 775.2 (1713.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 141 &le; 5504</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 146 (2.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">232 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAuklEQVR42u3bQQqAIBQA0Qzv2B3qPHWHTlnbX9FCgmQ+83YihAOaK8sxZDX2XoBppkU1DrbHwVtK7wW2iQH1OjVdRnvvlX6SeEOaRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRmQakWlEphGZRpQ4rX7/xH/WppdaqLS2l1qJN6RpRKYRwf6Qd4/rIFwGJc5t+Kf181taLonPmmlEJ5RiDjhJ+6vIAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwDmZU/AAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMH877EAAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Afghanistan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Albania</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Algeria</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. American Samoa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Americas</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Angola</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Antigua and Barbuda</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Argentina</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Asia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 222 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">34709</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">95.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHAAAAC9CAQAAADBnzGqAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAABQElEQVR42u3XQQrCQBQFQSPe0ZN5CE+p24kgggixP1WuQkDSZATf9jjNdj76AQQK/OCxfG5DfpBr0/g3KLBOYJ3AOoF1AusE1o0P3NaFtB39ND+yNo1/g7vAKYP3beBEAusE1gmsE1gnsE5g3fhAg7fO4K0TWCewTmCdwDqBdQLr7ME6e7BOYJ3AOoF1AusE1gmsGx9o8NYZvHUC6wTWCawTWCewTmDd+ECDt87grRNYJ7BOYJ3AOoF1AuvswTp7sE5gncA6gXUC6wTWCawbH2jw1hm8dQLrBNYJrBNYJ7BOYJ09WGcP1gmsE1gnsE5gncA6gXXjAw3eOoO3TmCdwDqBdQLrBNYJrBsfaPDWXdaLMYN3OYqX/Z3r0Y/2A/fd1fgjKrBOYJ3AOoF1Aute/ovev/uWP7ZNGRDvjD+iAuue6xM2YfTDG6AAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDAOZlT8AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTA4VDE0OjI5OjQ4KzAwOjAwfzvsQAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 5416 (78.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5318 &le; 5420 &le; 5510</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 192 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5318</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12158</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5420</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12121</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5510</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12170</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADAAAAA5CAQAAADaBGDEAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAdklEQVRYw+2WQQqAMAwEE/GP/sH/6B/6Sr2mgq2UpNA6c8tlBxrIVi+JZQnOn0Cw2uF0WsiuLwKRzSE+ZdP4O0CAAMEMgsexS20pBdReaG2OybGZfZ/o8PoBUDgIECD4m4DCqULhVEGAAAGCD/QtnAjG30G44AbbVxCiJj46JgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Milk Animals</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Production</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Yield</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12158</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12121</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADAAAAA5CAQAAADaBGDEAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAdklEQVRYw+2WQQqAMAwEE/GP/sH/6B/6Sr2mgq2UpNA6c8tlBxrIVi+JZQnOn0Cw2uF0WsiuLwKRzSE+ZdP4O0CAAMEMgsexS20pBdReaG2OybGZfZ/o8PoBUDgIECD4m4DCqULhVEGAAAGCD/QtnAjG30G44AbbVxCiJj46JgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item Code\n[numeric]</td>\n      <td align=\"left\">1 distinct value</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">882</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">36449</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTDfpuZrAAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OCswMDowMA5mVPwAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDgrMDA6MDB/O+xAAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item\n[character]</td>\n      <td align=\"left\">1. Milk, whole fresh cow</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">36449</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAAAXCAQAAACfMchmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTGoodb9AAAAVUlEQVRYw+3YMQ4AEBBEUSvu6A4O5A5OSYka2WT81023PzrWwy+i9wGkknoiraP27H3PVS0Um+ujVyVVEamKSFVEqiJSFZGqKO2zed/zkPHhIohURQMdGAXYo3nwyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OSswMDowMKgRX0gAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDkrMDA6MDDZTOf0AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.4 (16.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTGoodb9AAAA3ElEQVR42u3bQQ7CIBQAUTG9o3fQ8+gdekrd/mJsQ0qL8zOzY9PwIkKCtbwvWbuOnoA0abEpDsrgyTybv/iPasrxAVPTkw6n3BajeXO81qm0bUrPTv7UjqTUJd5GpBFLTFtsI+3nyj9X7ZCt50rPc6h3iRekNGLSiEkjJo2YNGLSiEkjJo1YYtrQi/H9fd3mhN8A4LS1u5fEC1IaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBFLTCvxdZkX/p9Q9/C2T8FrfpZ4QUoj9gETahr6Snu0WAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OSswMDowMKgRX0gAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDkrMDA6MDDZTOf0AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.4 (16.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTGoodb9AAAA3ElEQVR42u3bQQ7CIBQAUTG9o3fQ8+gdekrd/mJsQ0qL8zOzY9PwIkKCtbwvWbuOnoA0abEpDsrgyTybv/iPasrxAVPTkw6n3BajeXO81qm0bUrPTv7UjqTUJd5GpBFLTFtsI+3nyj9X7ZCt50rPc6h3iRekNGLSiEkjJo2YNGLSiEkjJo1YYtrQi/H9fd3mhN8A4LS1u5fEC1IaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBGTRkwaMWnEpBFLTCvxdZkX/p9Q9/C2T8FrfpZ4QUoj9gETahr6Snu0WAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OSswMDowMKgRX0gAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDkrMDA6MDDZTOf0AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Unit\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Head</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. hg/An</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. tonnes</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12158</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12121</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADAAAAA5CAQAAADaBGDEAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTGoodb9AAAAdklEQVRYw+2WQQqAMAwEE/GP/sH/6B/6Sr2mgq2UpNA6c8tlBxrIVi+JZQnOn0Cw2uF0WsiuLwKRzSE+ZdP4O0CAAMEMgsexS20pBdReaG2OybGZfZ/o8PoBUDgIECD4m4DCqULhVEGAAAGCD/QtnAjG30G44AbbVxCiJj46JgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OSswMDowMKgRX0gAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDkrMDA6MDDZTOf0AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Value\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 4410235 (25744621)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7 &le; 43266 &le; 683217055</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 692151 (5.8)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">24088 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG0AAABPCAQAAABLlYPgAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTGoodb9AAAAsklEQVR42u3bsQ3CQBAAQYzcI0VQj+mBKiF9LIEEBK+xdiJbn9zK/vCWx+mozrMHKK200Tq+3HYX77rMHu9bY8D6enQZnu+z5/zTgX/I0kSliUoTlSYqTVSaqDRRaaLSRKWJShOVJipNVJqoNFFpotJEpYlKE5UmKk1Umqg0UWmi0kSliUoTlSYqTVSaqDRRaaLSROunw23YKvVWYndp71dfN2PtfvgAizHxLw5810oTPQELNArh9t3H/gAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OSswMDowMKgRX0gAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDkrMDA6MDDZTOf0AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">74\n(0.2%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. *</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Fc</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Im</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. M</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">810</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3070</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7045</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">26.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13136</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">49.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2270</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEEAAABrCAQAAACCySeeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTGoodb9AAAA6klEQVRo3u3bSw7CMAyEYQf1jj0E5yl34JRlQYXiKtAXjmfxe9cVnzKWMqpKmS17btkACO8Z6ofHshj3Ev2z9QauTmG0sfspCAQBAQIECBBECYN/fCYQSn1tht/Rn/lxWWeMC2L62mUjS8xqF9qFJXZDBIKAAAECBAiiBCqLmV4Q0+nXb1cqza7KsjXXNkggCAgQIECA0Br6gpleEOf7wuGpDvwvfeHo+I0TCAICBAgQIIgSqCxmekG0Kkv8RyUblaXHbggEAQECBAgQRAlUFjOJIByh41sW4VOAAAFCNgACBAh+Cn9agrDMCyojIQnEivUMAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA4VDE0OjI5OjQ5KzAwOjAwqBFfSAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wOFQxNDoyOTo0OSswMDowMNlM5/QAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">10044\n(27.6%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag Description\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Aggregate, may include of</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Calculated data</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Data not available</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. FAO data based on imputat</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. FAO estimate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Official data</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Unofficial figure</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3070</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13136</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">36.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2270</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7045</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">19.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10044</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">27.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">810</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADIAAAB7CAQAAACcYRueAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDAgOHTGoodb9AAAA6ElEQVRo3u3aYQ7CIAyGYTG74w7hefQOntL9tBDs0qbgUt7v3zLDEwahg1k+t/G5TzASIZu8eHUG6FF8DcumtvrW3vz0HdKTPGMCAgKyEtIskDELYpsil2Tnqt6NbHf+43pGvlWIx3JStLypxzbPFAYBAbkIQj0xpUJC68lfewICAgIC8k2eoqVsgrxndieI3ARFvlLkmV0gICArIey0THGe3NkKmuvkzjpyeaYwCAjISghFy5Swz01aGQv63KSPZZ4pDAICchGEemJKp57Endj96EnU3xdUZExAQEBAxiITitaknoDoOQBgJiZ9ZV6u0QAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0wOFQxNDoyOTo0OSswMDowMKgRX0gAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMDhUMTQ6Mjk6NDkrMDA6MDDZTOf0AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-12-08</p>\n</div>\n```\n:::\n:::\n\n\n### Tidy the data\nFirst we need to remove the duplicate columns from each of the data set\n\n::: {.cell}\n\n```{.r .cell-code}\ncattle_diary_new <- subset(cattle_dairy,select= -c(`Year Code`))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(cattle_diary_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 13\n  Domain …¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item   Year Unit  Value\n  <chr>     <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr> <dbl> <chr> <dbl>\n1 QL        Lives…       2 Afgh…    5318 Milk A…     882 Milk…  1961 Head  7  e5\n2 QL        Lives…       2 Afgh…    5420 Yield       882 Milk…  1961 hg/An 5  e3\n3 QL        Lives…       2 Afgh…    5510 Produc…     882 Milk…  1961 tonn… 3.5e5\n4 QL        Lives…       2 Afgh…    5318 Milk A…     882 Milk…  1962 Head  7  e5\n5 QL        Lives…       2 Afgh…    5420 Yield       882 Milk…  1962 hg/An 5  e3\n6 QL        Lives…       2 Afgh…    5510 Produc…     882 Milk…  1962 tonn… 3.5e5\n# … with 2 more variables: Flag <chr>, `Flag Description` <chr>, and\n#   abbreviated variable names ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`,\n#   ⁴​`Item Code`\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlivestock_new <- subset(livestock,select= -c(`Year Code`))\negg_new <- subset(egg_chicken,select= -c(`Year Code`))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncattle_diary_new<- cattle_diary_new%>%\n  mutate(Item=str_replace_all(Item,\"Milk, whole fresh cow\", \"Milk\"))\negg_new <- egg_new%>%\n  mutate(Item=str_replace_all(Item,\"Eggs, hen, in shell\",\"Poultry\"))\ntable(cattle_diary_mutate$Item)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in table(cattle_diary_mutate$Item): object 'cattle_diary_mutate' not found\n```\n:::\n\n```{.r .cell-code}\ntable(egg_new$Item)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPoultry \n  38170 \n```\n:::\n:::\n\n\nNow that we have renamed the columns, now we perform a join on the tidied data.\n\n\n## Join Data\n\nwe have same columns in cattle, diary and live stock tables. so when we join them the final data must have the rows summated together in all the tables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncattle_egg <- full_join(egg_new,cattle_diary_new)\njoined_data <- full_join(cattle_egg,livestock_new)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(joined_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 156735     13\n```\n:::\n:::\n\n\nwe now confirm that they are all joined together.\n\n## Visualizations\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(joined_data,aes(x=Item))+geom_bar(fill = \"lightpink\") +\n  labs(title = \"Item and count\", x = \"Item\", \n     y = \"Count\")+geom_text(stat='count', aes(label=..count..), vjust=1)\n```\n\n::: {.cell-output-display}\n![](Tejaswini_Ketineni_challenge8_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nNow, we have understood that we can perform visualizations too on joined data.\n\n\n",
    "supporting": [
      "Tejaswini_Ketineni_challenge8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}