{
  "hash": "8522a6b92f184b03e8688d6d66d740ae",
  "result": {
    "markdown": "---\ntitle: \"Homework 3\"\nauthor: \"Aleacia Messiah\"\ndescription: \"Descriptive Statistics, Visualizations, and Limitations\"\ndate: \"12/11/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw3\n  - Aleacia Messiah\n  - SIPRI_Milex\n  - tidyverse\n  - readxl\n  - ggplot2\n  - treemap\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(treemap)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n::: callout-note\n## Note\n\nSince Homework 3 is a continuation of Homework 2, the sections *Read in Data* through *Potential Research Questions* will be the same as Homework 2.\n:::\n\n## Read in Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in the Current USD sheet of the Milex dataset, skipping the first 6 rows and renaming the columns\nmilex <- read_excel(\"_data/SIPRI-Milex-data-1949-2021.xlsx\", sheet = \"Current USD\", skip = 6, col_names = c(\"Country\", \"Notes\", 1949:2021))\n# view milex data\nmilex\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 191 × 75\n   Country  Notes `1949` `1950` `1951` `1952` `1953` `1954` `1955` `1956` `1957`\n   <chr>    <chr> <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr> \n 1 Africa   <NA>  <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  \n 2 North A… <NA>  <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  \n 3 Algeria  §4    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx   \n 4 Libya    ‡§¶16 xxx    xxx    ...    ...    ...    ...    ...    ...    ...   \n 5 Morocco  §17   xxx    xxx    xxx    xxx    xxx    xxx    xxx    23.71… 35.40…\n 6 Tunisia  <NA>  xxx    xxx    xxx    xxx    xxx    xxx    xxx    3.714… 6.411…\n 7 sub-Sah… <NA>  <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  \n 8 Angola   §‖1   xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx   \n 9 Benin    §     xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx   \n10 Botswana <NA>  xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx   \n# … with 181 more rows, and 64 more variables: `1958` <chr>, `1959` <chr>,\n#   `1960` <chr>, `1961` <chr>, `1962` <chr>, `1963` <chr>, `1964` <chr>,\n#   `1965` <chr>, `1966` <chr>, `1967` <chr>, `1968` <chr>, `1969` <chr>,\n#   `1970` <chr>, `1971` <chr>, `1972` <chr>, `1973` <chr>, `1974` <chr>,\n#   `1975` <chr>, `1976` <chr>, `1977` <chr>, `1978` <chr>, `1979` <chr>,\n#   `1980` <chr>, `1981` <chr>, `1982` <chr>, `1983` <chr>, `1984` <chr>,\n#   `1985` <chr>, `1986` <chr>, `1987` <chr>, `1988` <chr>, `1989` <chr>, …\n```\n:::\n:::\n\n\n## Clean Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmilex_clean <- milex %>% \n  # remove Notes column\n  select(!contains(\"Notes\")) %>% \n  # create a column with region names\n  mutate(Region = case_when(\n    str_ends(Country, \"Africa\") ~ \"Africa\",\n      str_detect(Country, \"America\") ~ \"Americas\",\n      str_detect(Country, \"Asia & Oceania\") ~ \"Asia & Oceania\",\n      str_ends(Country, \"Europe\") ~ \"Europe\",\n      str_ends(Country, \"East\") ~ \"Middle East\",\n    TRUE ~ NA_character_\n  )) %>% \n  # replace NAs in Region column\n  fill(Region, .direction = \"down\") %>% \n  # create a column with sub region names\n  mutate(Sub_Region = case_when(\n    str_detect(Country, \"North Africa\") ~ \"North Africa\",\n    str_detect(Country, \"sub-Saharan Africa\") ~ \"sub-Saharan Africa\",\n    str_detect(Country, \"Central America and the Caribbean\") ~ \"Central America and the Caribbean\",\n    str_detect(Country, \"North America\") ~ \"North America\",\n    str_detect(Country, \"South America\") ~ \"South America\",\n    str_detect(Country, \"Oceania\") ~ \"Oceania\",\n    str_detect(Country, \"South Asia\") ~ \"South Asia\",\n    str_detect(Country, \"East Asia\") ~ \"East Asia\",\n    str_detect(Country, \"South East Asia\") ~ \"South East Asia\",\n    str_detect(Country, \"Central Asia\") ~ \"Central Asia\",\n    str_detect(Country, \"Central Europe\") ~ \"Central Europe\",\n    str_detect(Country, \"Eastern Europe\") ~ \"Eastern Europe\",\n    str_detect(Country, \"Western Europe\") ~ \"Western Europe\",\n    str_ends(Country, \"East\") ~ \"Middle East\",\n    TRUE ~ NA_character_\n  )) %>% \n  # replace NAs in Sub Region column\n  fill(Sub_Region, .direction = \"down\") %>% \n  # remove rows with region and sub-region names\n  slice(-c(1:2, 7, 55:56, 70, 73, 85:86, 91, 98, 105, 117, 123:124, 145, 154, 175)) %>% \n  # replace \"xxx\" and \"...\" with NAs\n  na_if(\"xxx\") %>%\n  na_if(\"...\") %>% \n  # combine Region and Sub Region into one column\n  unite(Region:Sub_Region, col = \"Region & Sub Region\", sep = \"/\" ) %>% \n  # combine year columns into one column\n  pivot_longer('1949':'2021', names_to = \"Year\", values_to = \"Military Expenditure in Millions of US$\")\n# view cleaned dataset\nmilex_clean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12,629 × 4\n   Country `Region & Sub Region` Year  `Military Expenditure in Millions of US$`\n   <chr>   <chr>                 <chr> <chr>                                    \n 1 Algeria Africa/North Africa   1949  <NA>                                     \n 2 Algeria Africa/North Africa   1950  <NA>                                     \n 3 Algeria Africa/North Africa   1951  <NA>                                     \n 4 Algeria Africa/North Africa   1952  <NA>                                     \n 5 Algeria Africa/North Africa   1953  <NA>                                     \n 6 Algeria Africa/North Africa   1954  <NA>                                     \n 7 Algeria Africa/North Africa   1955  <NA>                                     \n 8 Algeria Africa/North Africa   1956  <NA>                                     \n 9 Algeria Africa/North Africa   1957  <NA>                                     \n10 Algeria Africa/North Africa   1958  <NA>                                     \n# … with 12,619 more rows\n```\n:::\n\n```{.r .cell-code}\n# number of distinct countries\nn_distinct(milex_clean$Country)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 173\n```\n:::\n\n```{.r .cell-code}\n# list distinct countries\ndistinct(milex_clean[,1])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 173 × 1\n   Country     \n   <chr>       \n 1 Algeria     \n 2 Libya       \n 3 Morocco     \n 4 Tunisia     \n 5 Angola      \n 6 Benin       \n 7 Botswana    \n 8 Burkina Faso\n 9 Burundi     \n10 Cameroon    \n# … with 163 more rows\n```\n:::\n\n```{.r .cell-code}\n# list distinct region and sub-region combinations\ndistinct(milex_clean[,2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 13 × 1\n   `Region & Sub Region`                     \n   <chr>                                     \n 1 Africa/North Africa                       \n 2 Africa/sub-Saharan Africa                 \n 3 Americas/Central America and the Caribbean\n 4 Americas/North America                    \n 5 Americas/South America                    \n 6 Asia & Oceania/Oceania                    \n 7 Asia & Oceania/South Asia                 \n 8 Asia & Oceania/East Asia                  \n 9 Asia & Oceania/Central Asia               \n10 Europe/Central Europe                     \n11 Europe/Eastern Europe                     \n12 Europe/Western Europe                     \n13 Middle East/Middle East                   \n```\n:::\n\n```{.r .cell-code}\n# number of years\nn_distinct(milex_clean$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 73\n```\n:::\n\n```{.r .cell-code}\n# range of years\nrange(milex_clean$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"1949\" \"2021\"\n```\n:::\n:::\n\n\n## Narrative\n\nThe Current USD data from the SIPRI Milex dataset details the military expenditures in millions of US dollars for 173 countries for the period 1949-2021. There are 191 observations (173 actual observations) and 75 variables (`Country`, `Notes`, and Years `1949` through `2021`). Observations (countries) were grouped by region and sub-region. There are 5 regions (Africa, Americas, Asia & Oceania, Europe, and Middle East) and 14 sub-regions (North Africa, Sub-Saharan Africa, Central America and the Caribbean, North America, South America, Oceania, South Asia, East Asia, South East Asia, Central Asia, Central Europe, Eastern Europe, Western Europe, and Middle East). Some of the data is missing for several countries in various years due to the data not being available or the country did not exist or was not independent at the time the data was collected, so those values are replaced with NAs.\n\nAfter cleaning the data, the new dataset has 12,629 observations and 4 variables (`Country`, `Region & Sub Region`, `Year`, `Military Expenditure in Millions of US$`). The regions and sub-regions were extracted from the `Country` column and combined together into one column to illustrate the various combinations of region and sub-region. The years were also condensed into one column.\n\n## Potential Research Questions\n\nSince this data was taken over a large period of time, I can research whether using time series methods would be appropriate to visualize and analyze the trends in the data.\n\n**1. What trends are present in the data (e.g. are there certain patterns of military spending over the years)?**\n\n**2. What are the top spending countries for each year?**\n\n**3. What is the predicted amount of military expenditures in dollars for year 2022 for each country?**\n\n## Descriptive Statistics\n\nI decided to calculate the average military expenditures (`Military Expenditure in Millions of US$`) each year (`Year`) with missing values removed (missing values were removed in all further analyses in order to properly compute these statistics). It appears that the mean military expenditure amount in US dollars steadily increases over time, which makes sense as more warfare and increased tensions between foreign nations began to arise over time. The average military expenditure in US dollars across the entire dataset is 0.6591971. This is about the same as the average in the late 1970s and early 1980s. The standard deviation of military expenditures in millions of US dollars is 0.473998, meaning this data varies about 0.473998 million US dollars from the mean, so given that the mean is 0.6591971 million US dollars, the military expenditure amounts vary quite greatly. \n\nSince there are 13 `Region & Sub Region` categories, I want to look at the number of times each region and sub region combination is represented in the data. Africa/sub-Saharan Africa is represented the most at 3,431 times with Europe/Central Europe and Europe/Western Europe following at 1,460 times each. This seems correct as there are many sub-Saharan African countries compared to European countries and others. However, I did not specify to remove missing values, so this count may not be entirely accurate as not every country had a military expenditure amount for each year.\n\nLastly, I computed the average military expenditures in US dollars by country. The range is from 0.05479452 million US dollars to 1 million US dollars, so the USSR has the smallest average while 17 countries (including the United States of America) have the largest average. This is a bit strange since there were a lot of tensions, especially during the Cold War, between the USSR and the USA, but the reason why the USSR has the smallest average military expenditures in US dollars may be because the USSR broke up in the 1990s and most of the larger military expenditures occurred after the disbandment of the USSR. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate the average military expenditures by year \navg_exp <- milex_clean %>% \n  group_by(Year) %>% \n  summarize(avg_expenditure = mean(!is.na(`Military Expenditure in Millions of US$`)))\n# view avg_exp\navg_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 73 × 2\n   Year  avg_expenditure\n   <chr>           <dbl>\n 1 1949           0.0983\n 2 1950           0.127 \n 3 1951           0.162 \n 4 1952           0.173 \n 5 1953           0.202 \n 6 1954           0.185 \n 7 1955           0.208 \n 8 1956           0.254 \n 9 1957           0.306 \n10 1958           0.347 \n# … with 63 more rows\n```\n:::\n\n```{.r .cell-code}\n# calculate the average military expenditure in millions of US$ across all years\nmean(!is.na(milex_clean$`Military Expenditure in Millions of US$`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6591971\n```\n:::\n\n```{.r .cell-code}\n# compute the standard deviation of military expenditures in millions of US$\nsd(!is.na(milex_clean$`Military Expenditure in Millions of US$`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.473998\n```\n:::\n\n```{.r .cell-code}\n# count region & sub region combinations\nregion_subregion <- milex_clean %>% \n  group_by(`Region & Sub Region`) %>% \n  summarize(n = n())\n# view region_subregion\nregion_subregion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 13 × 2\n   `Region & Sub Region`                          n\n   <chr>                                      <int>\n 1 Africa/North Africa                          292\n 2 Africa/sub-Saharan Africa                   3431\n 3 Americas/Central America and the Caribbean   949\n 4 Americas/North America                       146\n 5 Americas/South America                       803\n 6 Asia & Oceania/Central Asia                  365\n 7 Asia & Oceania/East Asia                    1241\n 8 Asia & Oceania/Oceania                       292\n 9 Asia & Oceania/South Asia                    438\n10 Europe/Central Europe                       1460\n11 Europe/Eastern Europe                        584\n12 Europe/Western Europe                       1460\n13 Middle East/Middle East                     1168\n```\n:::\n\n```{.r .cell-code}\n# compute average military expenditures by country\ncountry_exp <- milex_clean %>% \n  group_by(Country) %>% \n  summarize(avg_expenditure = mean(!is.na(`Military Expenditure in Millions of US$`)))\n# view country_exp\ncountry_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 173 × 2\n   Country     avg_expenditure\n   <chr>                 <dbl>\n 1 Afghanistan           0.329\n 2 Albania               0.644\n 3 Algeria               0.808\n 4 Angola                0.603\n 5 Argentina             1    \n 6 Armenia               0.397\n 7 Australia             1    \n 8 Austria               0.890\n 9 Azerbaijan            0.411\n10 Bahrain               0.699\n# … with 163 more rows\n```\n:::\n\n```{.r .cell-code}\n# find the range of the average military expenditures in millions of US$ out of all countries\nrange(country_exp$avg_expenditure)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05479452 1.00000000\n```\n:::\n\n```{.r .cell-code}\n# find the country with the smallest average military expenditure in US$\nslice_min(country_exp, avg_expenditure)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  Country avg_expenditure\n  <chr>             <dbl>\n1 USSR             0.0548\n```\n:::\n\n```{.r .cell-code}\n# find the countries with the largest average military expenditure in US$\nslice_max(country_exp, avg_expenditure)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 17 × 2\n   Country                  avg_expenditure\n   <chr>                              <dbl>\n 1 Argentina                              1\n 2 Australia                              1\n 3 Belgium                                1\n 4 Costa Rica                             1\n 5 Denmark                                1\n 6 France                                 1\n 7 Greece                                 1\n 8 Italy                                  1\n 9 Luxembourg                             1\n10 Mexico                                 1\n11 Netherlands                            1\n12 Norway                                 1\n13 Peru                                   1\n14 Portugal                               1\n15 Spain                                  1\n16 Turkey                                 1\n17 United States of America               1\n```\n:::\n\n```{.r .cell-code}\n# find the top 5 spending countries for each year\ntop_country_exp <- milex_clean %>% \n  group_by(Year) %>% \n  arrange(desc(`Military Expenditure in Millions of US$`)) %>% \n  slice_head(n = 5)\n# view top_country_exp\ntop_country_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 365 × 4\n# Groups:   Year [73]\n   Country  `Region & Sub Region`                      Year  Military Expendit…¹\n   <chr>    <chr>                                      <chr> <chr>              \n 1 Denmark  Europe/Western Europe                      1949  69.297401347449465 \n 2 Norway   Europe/Western Europe                      1949  67.17745742401685  \n 3 Portugal Europe/Western Europe                      1949  54.441128511214352 \n 4 Italy    Europe/Western Europe                      1949  467.23430058061933 \n 5 Mexico   Americas/Central America and the Caribbean 1949  34.797687861271676 \n 6 Chile    Americas/South America                     1950  87.502552157771277 \n 7 Portugal Europe/Western Europe                      1950  52.732141362862961 \n 8 Denmark  Europe/Western Europe                      1950  51.975202471645282 \n 9 Italy    Europe/Western Europe                      1950  501.26509684299299 \n10 Norway   Europe/Western Europe                      1950  49.979980008007999 \n# … with 355 more rows, and abbreviated variable name\n#   ¹​`Military Expenditure in Millions of US$`\n```\n:::\n\n```{.r .cell-code}\n# filter the top 5 spending countries from 1949 to 1953\nfirst_5_yrs <- filter(top_country_exp, Year <= 1953)\n# view first 5 years data frame\nfirst_5_yrs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 25 × 4\n# Groups:   Year [5]\n   Country  `Region & Sub Region`                      Year  Military Expendit…¹\n   <chr>    <chr>                                      <chr> <chr>              \n 1 Denmark  Europe/Western Europe                      1949  69.297401347449465 \n 2 Norway   Europe/Western Europe                      1949  67.17745742401685  \n 3 Portugal Europe/Western Europe                      1949  54.441128511214352 \n 4 Italy    Europe/Western Europe                      1949  467.23430058061933 \n 5 Mexico   Americas/Central America and the Caribbean 1949  34.797687861271676 \n 6 Chile    Americas/South America                     1950  87.502552157771277 \n 7 Portugal Europe/Western Europe                      1950  52.732141362862961 \n 8 Denmark  Europe/Western Europe                      1950  51.975202471645282 \n 9 Italy    Europe/Western Europe                      1950  501.26509684299299 \n10 Norway   Europe/Western Europe                      1950  49.979980008007999 \n# … with 15 more rows, and abbreviated variable name\n#   ¹​`Military Expenditure in Millions of US$`\n```\n:::\n\n```{.r .cell-code}\n# filter the top 5 spending countries from 2017 to 2021\nlast_5_yrs <- filter(top_country_exp, Year >= 2017)\n# view last 5 years data frame\nlast_5_yrs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 25 × 4\n# Groups:   Year [5]\n   Country      `Region & Sub Region`     Year  Military Expenditure in Millio…¹\n   <chr>        <chr>                     <chr> <chr>                           \n 1 Poland       Europe/Central Europe     2017  9870.6806282722519              \n 2 Korea, North Asia & Oceania/East Asia  2017  961.48148148148152              \n 3 Netherlands  Europe/Western Europe     2017  9580.6854982163022              \n 4 Croatia      Europe/Central Europe     2017  920.83705291818819              \n 5 Cape Verde   Africa/sub-Saharan Africa 2017  9.3543841662816174              \n 6 Croatia      Europe/Central Europe     2018  966.35871679888726              \n 7 Bulgaria     Europe/Central Europe     2018  961.29727459449623              \n 8 Mongolia     Asia & Oceania/East Asia  2018  96.067489859811118              \n 9 Algeria      Africa/North Africa       2018  9583.7242883703002              \n10 Eswatini     Africa/sub-Saharan Africa 2018  95.863380323095569              \n# … with 15 more rows, and abbreviated variable name\n#   ¹​`Military Expenditure in Millions of US$`\n```\n:::\n:::\n\n\n## Visualizations\n\nTo visualize trends of military expenditures over time, I created a time series plot of `avg_expenditure` vs. `year` from the avg_exp data frame. To reiterate, missing values are not included in order to proceed with the analysis. As we can see from the plot, there is a clear increasing trend of military expenditures over time, with the data stabilizing around the late 2010s. As previously mentioned, there was quite a bit of warfare and rising tensions in the twentieth century but the reasoning behind the increasing trend leveling off later on may be due to some countries making an effort to decrease or cut military spending in order to not raise their national debt or the global COVID-19 pandemic taking place beginning in late 2019 and early 2020.\n\nThe second visualization is a tree map depicting the region and sub region counts by the sizes of the rectangles. Africa/sub-Saharan Africa is the largest rectangle which coincides with my observation in the previous section. Although Europe/Central Europe and Europe/Western Europe have the same count, their rectangles look different as Europe/Central Europe is longer and Europe/Western Europe looks wider. It would be easier to tell if the counts were listed under the labels but I did not find out how to do this. \n\nThese third and fourth visualizations illustrate the top five spending countries for the first five years and last five years respectively. The military expenditures in US millions of dollars have a wider range in the first five years of data versus the last five years of data, with the first five years ranging from 34 million US dollars to 986 million US dollars and the last five years ranging from 85 to 9,978 million US dollars. What I find interesting are the countries that repeatedly rank in the top five: for example, Denmark was in the top five for 1949 to 1952 while Algeria was in the top five for 2018, 2020, and 2021. I'm not up-to-date on world relations and current events, but for a country to be in the top five for military expenditures, most likely the military makes up a large portion of the country's budget and is therefore an important asset for them to maintain. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a time series plot of avg_expenditure vs. year with avg_exp data\nggplot(avg_exp, aes(Year, avg_expenditure)) +\n  geom_point() +\n  guides(x = guide_axis(n.dodge = 5)) +\n  labs(x = \"Year\",\n       y = \"Average Expenditure in Millions (US$)\",\n       title = \"Time Series of Average Expenditure in Millions (US$) vs. Year\",\n       subtitle = \"Missing values are not included\",\n       caption = \"Data: SIPRI-Milex-data-1949-2021.xlsx\")\n```\n\n::: {.cell-output-display}\n![](AleaciaMessiah_hw3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# create a treemap of region and sub region counts\ntreemap(region_subregion,\n            index=\"Region & Sub Region\",\n            vSize=\"n\",\n            type=\"index\",\n            title=\"Treemap of Region & Sub Region Counts\",\n            fontsize.title = 12)\n```\n\n::: {.cell-output-display}\n![](AleaciaMessiah_hw3_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# create a scatterplot of military expenditure in millions of US$ vs. year with top 5 highest spending countries from 1949 to 1953\nggplot(first_5_yrs, aes(Year, `Military Expenditure in Millions of US$`)) +\n  geom_point(aes(color = Country)) +\n  theme(legend.position = \"bottom\") +\n  labs(title = \"Scatterplot of Top 5 Highest Spending Countries from 1949 to 1953\",\n       caption = \"Data: SIPRI-Milex-data-1949-2021.xlsx\")\n```\n\n::: {.cell-output-display}\n![](AleaciaMessiah_hw3_files/figure-html/unnamed-chunk-5-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# create a scatterplot of military expenditure in millions of US$ vs. year with top 5 highest spending countries from 2017 to 2021\nggplot(last_5_yrs, aes(Year, `Military Expenditure in Millions of US$`)) +\n  geom_point(aes(color = Country)) +\n  theme(legend.position = \"bottom\") +\n  labs(title = \"Scatterplot of Top 5 Highest Spending Countries from 2017 to 2021\",\n       caption = \"Data: SIPRI-Milex-data-1949-2021.xlsx\")\n```\n\n::: {.cell-output-display}\n![](AleaciaMessiah_hw3_files/figure-html/unnamed-chunk-5-4.png){width=672}\n:::\n:::\n\n\n## Limitations\n\nThe biggest limitation to my visualizations is in relation to my third research question: What is the predicted amount of military expenditures in dollars for year 2022 for each country? I unfortunately ran out of time and space for this assignment to go in depth into this question but I would assume based on my math background, this would require some forecasting techniques. I would like to dive into more prediction-related analysis to answer this question, but this is outside the scope of this class, so I will have to come back to it later on after a refresher on forecasting methods. \n\nAs for the top spending countries of each year, it was very difficult to visualize the top five spending countries from 1949 to 2021 in one plot (or even faceted plots) which is why I had to limit to illustrating only the first five years (1949 to 1953) and the last five years (2017 to 2021). It would be better for comparison to display all the years in one chart but that was not possible. However, from what I was able to do, I could draw a good conclusion as to what the data was portraying. For the final project, I think it would be beneficial to look more into faceting and other techniques regarding fitting all data points in one plot. In addition, I'll also conduct further research on how to improve my titles and labels on my graphs as they can be better than they are now.",
    "supporting": [
      "AleaciaMessiah_hw3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}