{
  "hash": "34c6e6182cc61318abf7c47c234b19dc",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 Guanua Tan\"\nauthor: \"Guanhua Tan\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"09/19/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nrailroad<-read_csv(\"_data/railroad_2012_clean_county.csv\")\nrailroad\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# … with 2,920 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad %>%\n  summary(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n\nThe dataset of railroad across the United States includes three columns--state, county and total employees in each county -- and 2930 counties.Each county at least maintains one employees while the maximum number is 8207. The average of total employees each county hires is 81.18. However, the median of it is 27.00, which reflects that most counties maintain a small station. The numbers of 1st Qu. and 3rd Qu. further confirms the finding.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# top-ranking by county\nmax_railroad = railroad %>%\n  arrange(desc(`total_employees`)) %>%\n  slice(1:20)\nmax_railroad\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 20 × 3\n   state county           total_employees\n   <chr> <chr>                      <dbl>\n 1 IL    COOK                        8207\n 2 TX    TARRANT                     4235\n 3 NE    DOUGLAS                     3797\n 4 NY    SUFFOLK                     3685\n 5 VA    INDEPENDENT CITY            3249\n 6 FL    DUVAL                       3073\n 7 CA    SAN BERNARDINO              2888\n 8 CA    LOS ANGELES                 2545\n 9 TX    HARRIS                      2535\n10 NE    LINCOLN                     2289\n11 NY    NASSAU                      2076\n12 MO    JACKSON                     2055\n13 IN    LAKE                        1999\n14 IL    WILL                        1784\n15 PA    PHILADELPHIA                1649\n16 NE    LANCASTER                   1619\n17 CA    RIVERSIDE                   1567\n18 CT    NEW HAVEN                   1561\n19 NY    QUEENS                      1470\n20 KS    JOHNSON                     1286\n```\n:::\n:::\n\nCook county, IL, hires the largest size of employees and reaches to 8207 while Tarrant, TX, is second to it with 4235 employees. The city of Chicago, the third largest city of the United State in terms of population, is located in Cook county, which interprets why Cook hires a large group of employees to manage the operation of railroad. I also propose that residents in IL may be more willing to take train for commuting. Tarrant county hires a large number of employees because it serves the Dallas-Fort Worth-Arlington metropolitan area. Interestingly, New York City's railroad is not in the top ten. I don't think it means the city relies less on railroad. In fact, New York City is heavy reliance on railroad for public transportation. But several different authorities run railroads connecting between the city and the suburban area such as New Jersey and Connecticut. I have noted that New Haven, CT hires 1561 employees while Suffolk in Long Island, NY hires 3685. New Haven was the terminal of the Metro-North Railroad connecting between New York City and CT. Long Island Rail Road connects with New York City. (source: Wikipedia)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# each state's percentage in the US\nrailroad %>% group_by(state) %>% summarise(total=sum(total_employees)) %>% arrange(desc(total)) %>% mutate(total_national=sum(total) , ratio=total/total_national)  %>% slice(1:10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 4\n   state total total_national  ratio\n   <chr> <dbl>          <dbl>  <dbl>\n 1 TX    19839         255432 0.0777\n 2 IL    19131         255432 0.0749\n 3 NY    17050         255432 0.0667\n 4 NE    13176         255432 0.0516\n 5 CA    13137         255432 0.0514\n 6 PA    12769         255432 0.0500\n 7 OH     9056         255432 0.0355\n 8 GA     8605         255432 0.0337\n 9 IN     8537         255432 0.0334\n10 MO     8419         255432 0.0330\n```\n:::\n:::\n\n\nAlthough Cook county hires the largest size of employees, Illinois is not the NO.1 in terms of total employees. Texas outnumbers it by several hundreds employees.However, no state reaches 10 % of national total employees. Both Texas and Illinois are over 7% of national total employees. New York is even less 7% of them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# mean, median, and states of states\nrailroad %>% group_by(state) %>% summarise(total=sum(total_employees)) %>%  summarise(temployee_mean=mean(total),\n            templyee_sd=sd(total, na.rm=TRUE),\n            tempyee_median=median(total, na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 3\n  temployee_mean templyee_sd tempyee_median\n           <dbl>       <dbl>          <dbl>\n1          4819.       4782.           3379\n```\n:::\n:::\n\nThe mean, median and standard deviation of states reflect that total_employees of some big states are overwhelming and some small states only maintain a tiny number of total employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# state difference\nrailroad %>% group_by(state) %>%\n  summarise(temployee_mean=mean(total_employees),\n            templyee_sd=sd(total_employees, na.rm=TRUE),\n            tempyee_median=median(total_employees, na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 4\n   state temployee_mean templyee_sd tempyee_median\n   <chr>          <dbl>       <dbl>          <dbl>\n 1 AE               2          NA              2  \n 2 AK              17.2        34.8            2.5\n 3 AL              63.5       130.            26  \n 4 AP               1          NA              1  \n 5 AR              53.8       131.            16.5\n 6 AZ             210.        228.            94  \n 7 CA             239.        549.            61  \n 8 CO              64.0       128.            10  \n 9 CT             324         520.           125  \n10 DC             279          NA            279  \n# … with 43 more rows\n```\n:::\n:::\n\n  The big differences between mean, median and sd of each state reflect population distribution in he United State.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#TX as a case study\nrailroad %>% filter(state=='TX') %>% arrange(desc(total_employees)) %>% mutate(total_TX=sum(total_employees), ratio_TX=total_employees/total_TX) %>% filter(total_employees >100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 34 × 5\n   state county     total_employees total_TX ratio_TX\n   <chr> <chr>                <dbl>    <dbl>    <dbl>\n 1 TX    TARRANT               4235    19839   0.213 \n 2 TX    HARRIS                2535    19839   0.128 \n 3 TX    BEXAR                  950    19839   0.0479\n 4 TX    POTTER                 883    19839   0.0445\n 5 TX    EL PASO                863    19839   0.0435\n 6 TX    MONTGOMERY             474    19839   0.0239\n 7 TX    JOHNSON                429    19839   0.0216\n 8 TX    BELL                   413    19839   0.0208\n 9 TX    DALLAS                 406    19839   0.0205\n10 TX    DENTON                 394    19839   0.0199\n# … with 24 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# TX as a case study\nrailroad %>% filter(state=='TX') %>% summarise(total_mean=mean(total_employees), total_madian=median(total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  total_mean total_madian\n       <dbl>        <dbl>\n1       89.8           17\n```\n:::\n:::\n\n  Cast study 1 TX\n  Taking TX as case study, I try to looking the distribution in a state. The combination of TARRANT and HARRIS reaches 34 % of total employees in TX, which reflects high population density in these two areas.\n  \n\n::: {.cell}\n\n```{.r .cell-code}\n# case study IL\nrailroad %>% filter(state=='IL') %>% arrange(desc(total_employees)) %>% mutate(total_IL=sum(total_employees), ratio_IL=total_employees/total_IL) %>% filter(total_employees >100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 25 × 5\n   state county   total_employees total_IL ratio_IL\n   <chr> <chr>              <dbl>    <dbl>    <dbl>\n 1 IL    COOK                8207    19131   0.429 \n 2 IL    WILL                1784    19131   0.0933\n 3 IL    KNOX                 885    19131   0.0463\n 4 IL    DUPAGE               837    19131   0.0438\n 5 IL    KANE                 577    19131   0.0302\n 6 IL    ST CLAIR             495    19131   0.0259\n 7 IL    MADISON              427    19131   0.0223\n 8 IL    MACON                425    19131   0.0222\n 9 IL    LAKE                 340    19131   0.0178\n10 IL    KANKAKEE             289    19131   0.0151\n# … with 15 more rows\n```\n:::\n:::\n\n  Case study of IL\n  Cook county hire 42% employees of railroad in IL demonstrates the overwhelming population density in the city of Chicago as well as reflects the population distribution in IL.\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}