{
  "hash": "8f1e122887afd2f66ffa5b4be1ebc3c9",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 Kristin Abijaoude\"\nauthor: \"Kristin Abijaoude\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"08/16/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - kristin_abijaoude\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroads <- read_csv(\"_data/railroad_2012_clean_county.csv\")\nrailroads\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# … with 2,920 more rows\n```\n:::\n:::\n\n\nThis dataset is county-level data from censuses across 2930 counties with at least one railroad employee. Each row has information about the county name, the state that the county is in, and the total number of railroad employees in said county. The information is likely collected from the 2012 US Census.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(railroads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    state              county          total_employees  \n Length:2930        Length:2930        Min.   :   1.00  \n Class :character   Class :character   1st Qu.:   7.00  \n Mode  :character   Mode  :character   Median :  21.00  \n                                       Mean   :  87.18  \n                                       3rd Qu.:  65.00  \n                                       Max.   :8207.00  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Selecting county and total employees\nselect(railroads, `county`, `total_employees`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 2\n   county               total_employees\n   <chr>                          <dbl>\n 1 APO                                2\n 2 ANCHORAGE                          7\n 3 FAIRBANKS NORTH STAR               2\n 4 JUNEAU                             3\n 5 MATANUSKA-SUSITNA                  2\n 6 SITKA                              1\n 7 SKAGWAY MUNICIPALITY              88\n 8 AUTAUGA                          102\n 9 BALDWIN                          143\n10 BARBOUR                            1\n# … with 2,920 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Average # of employees in each state\nrailroads %>%\n  group_by(state) %>%\n  summarise(mean.employees = mean(total_employees, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state mean.employees\n   <chr>          <dbl>\n 1 AE               2  \n 2 AK              17.2\n 3 AL              63.5\n 4 AP               1  \n 5 AR              53.8\n 6 AZ             210. \n 7 CA             239. \n 8 CO              64.0\n 9 CT             324  \n10 DC             279  \n# … with 43 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## filtering counties with up to 100 railroad employees\nfilter(railroads,`total_employees` <= 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,400 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    BARBOUR                            1\n 9 AL    BIBB                              25\n10 AL    BULLOCK                           13\n# … with 2,390 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarize(railroads, mean.total_employees = mean(`total_employees`, na.rm = TRUE), median.total_employees = median(`total_employees`, na.rm = TRUE), min.total_employees = min(`total_employees`, na.rm = TRUE), max.total_employees = max(`total_employees`, na.rm = TRUE), sd.total_employees = sd(`total_employees`, na.rm = TRUE), var.total_employees = var(`total_employees`, na.rm = TRUE), IQR.total_employees = IQR(`total_employees`, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 7\n  mean.total_employees median.total_em…¹ min.t…² max.t…³ sd.to…⁴ var.t…⁵ IQR.t…⁶\n                 <dbl>             <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n1                 87.2                21       1    8207    284.  80449.      58\n# … with abbreviated variable names ¹​median.total_employees,\n#   ²​min.total_employees, ³​max.total_employees, ⁴​sd.total_employees,\n#   ⁵​var.total_employees, ⁶​IQR.total_employees\n```\n:::\n:::\n\nThere are many more counties with a lower number of total railroad employees than those with a higher number of them, which partially explains the low numbers for median and mean, and why the mean is greater than the median. The standard deviation is very high which shows there were outliers with large values, such as Cook County, IL with 8207 railroad employees. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(railroads, aes(x=state, y=total_employees)) + \n    geom_point()\n```\n\n::: {.cell-output-display}\n![](challenge2_kristinabijaoude_files/figure-html/Visualizing Population Density-1.png){width=672}\n:::\n:::\n\nI attempted to create a scatterplot graph to display the amount of railroad employees by state, with each dot representing county. Plenty of states have counties that are more clustered, while some states have one or outlier counties, such as Illinois and New York. When you look into population density of the those states, you can see that the majority of the population lives in a particular area, while the rest of the state is relatively sparse.\n",
    "supporting": [
      "challenge2_kristinabijaoude_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}