{
  "hash": "193f608945f638ef23273f298f13dfe5",
  "result": {
    "markdown": "---\ntitle: \"DACSS 601 Final Project - Caitlin Rowley\"\ndescription: \"My final project provides an analysis of data related to Boston Airbnb listings from 2021.\"\nauthor: \"Caitlin Rowley\"\ndate: \"2022-12-24\"\noutput: distill::distill_article\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Introduction\n\nFor my final project, I selected data from the Inside AirBnB website, which allows the public to access information regarding listings by geographic area. My data set captures host- and room-specific metrics related to all Airbnb rental listings in Boston, MA from September 2021 through September 2022. Information for each listing included in the data set is presented using the following variables: (1) ID number for the particular listing, (2) name of the listing, (3) listing host ID number, (4) listing host name, (5) listing neighborhood group, (6) listing neighborhood, (7) listing latitude, (8) listing longitude, (9) type of listing (i.e., private room, entire home/apartment, shared room, or hotel room), (10) listing price, (11) minimum number of nights per stay, (12) number of listing reviews, (13) most recent listing review, (14) number of listing reviews per month, (15) number listing-specific host listings (i.e., the number of unique listings by host), (16) listing availability over the next year, (17) number of reviews for listing over the past 12 months, and (18) listing licensure status. The combination of each of these variables makes up a case, which in this instance equates to a unique Airbnb listing.\n\nIn reviewing these data, I thought it would be interesting to evaluate the following research question: *Are there are particular listing features---specifically, listing neighborhood and listing type---that may contribute to listing price?* As part of this task, I will also be running analyses on additional summary statistics to gain a better understanding of patterns that may appear within the data.\n\n## Data\n\nTo begin this analysis, I will read in my data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install packages and load libraries:\n\ninstall.packages(\"readr\")\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in contrib.url(repos, \"source\"): trying to use CRAN without setting a mirror\n```\n:::\n\n```{.r .cell-code}\ninstall.packages(\"readxl\")\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in contrib.url(repos, \"source\"): trying to use CRAN without setting a mirror\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readr)\nlibrary(readxl)\nlibrary(dplyr)\nlibrary(ggtext)\n\n# read in dataset:\n\nBoston <- read_csv(\"Boston AirBnB Data.csv\")\nhead(Boston)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 18\n     id name       host_id host_…¹ neigh…² neigh…³ latit…⁴ longi…⁵ room_…⁶ price\n  <dbl> <chr>        <dbl> <chr>   <lgl>   <chr>     <dbl>   <dbl> <chr>   <dbl>\n1  3168 TudorStud…    3697 Mark    NA      Bright…    42.4   -71.2 Privat…    99\n2  3781 HARBORSID…    4804 Frank   NA      East B…    42.4   -71.0 Entire…   132\n3  5506 ** Fort H…    8229 Terry   NA      Roxbury    42.3   -71.1 Entire…   149\n4  6695 Fort Hill…    8229 Terry   NA      Roxbury    42.3   -71.1 Entire…   179\n5  7903 Colorful,…   14169 Stacy   NA      Charle…    42.4   -71.1 Privat…   116\n6  8521 Sunsplash…  306681 Janet   NA      Allston    42.4   -71.1 Entire…   300\n# … with 8 more variables: minimum_nights <dbl>, number_of_reviews <dbl>,\n#   last_review <chr>, reviews_per_month <dbl>,\n#   calculated_host_listings_count <dbl>, availability_365 <dbl>,\n#   number_of_reviews_ltm <dbl>, license <chr>, and abbreviated variable names\n#   ¹​host_name, ²​neighbourhood_group, ³​neighbourhood, ⁴​latitude, ⁵​longitude,\n#   ⁶​room_type\n```\n:::\n:::\n\n\n## Tidy Data\n\nI will now tidy the data to look for missing values and duplicates. I will also rename columns as needed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# look for duplicates\n# look for missing values\n# remember na.rm=TRUE for calculations\n\n# At first glance, it seems as though there are no values in the column titled \"neighbourhood_group.\" So, I will find all unique values within that column to determine whether it can be removed from my tidy data set.\n\nunique(Boston[c(\"neighbourhood_group\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  neighbourhood_group\n  <lgl>              \n1 NA                 \n```\n:::\n\n```{.r .cell-code}\n# I now know that there is no data within this column. I will remove it from my data set.\n\nBoston_tidy <- subset(Boston, select = -c(neighbourhood_group))\n\n# I can see from viewing this data frame that there are no other columns that are absent any values, so I will move on to other tidying tasks.\n\n# rename columns:\n\nnames(Boston_tidy) <- c('room_id', 'room_name', 'host_id', 'host_name', 'neighborhood', 'room_latitude', 'room_longitude', 'room_type', 'room_price', 'min_nights', 'number_reviews', 'last_review', 'reviews_per_month', 'host_listings', 'availability_next_365', 'number_reviews_LTM', 'room_license')\n\n# find duplicates:\n\nduplicates <- duplicated(Boston_tidy)\n\n# reached \"max.print\", so I will increase the limit and identify if any values within the vector = TRUE:\n\noptions(max.print=999999)\nduplicates[\"TRUE\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\nhead(Boston_tidy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 17\n  room_id room_name      host_id host_…¹ neigh…² room_…³ room_…⁴ room_…⁵ room_…⁶\n    <dbl> <chr>            <dbl> <chr>   <chr>     <dbl>   <dbl> <chr>     <dbl>\n1    3168 TudorStudio       3697 Mark    Bright…    42.4   -71.2 Privat…      99\n2    3781 HARBORSIDE-Wa…    4804 Frank   East B…    42.4   -71.0 Entire…     132\n3    5506 ** Fort Hill …    8229 Terry   Roxbury    42.3   -71.1 Entire…     149\n4    6695 Fort Hill Inn…    8229 Terry   Roxbury    42.3   -71.1 Entire…     179\n5    7903 Colorful, mod…   14169 Stacy   Charle…    42.4   -71.1 Privat…     116\n6    8521 SunsplashedSe…  306681 Janet   Allston    42.4   -71.1 Entire…     300\n# … with 8 more variables: min_nights <dbl>, number_reviews <dbl>,\n#   last_review <chr>, reviews_per_month <dbl>, host_listings <dbl>,\n#   availability_next_365 <dbl>, number_reviews_LTM <dbl>, room_license <chr>,\n#   and abbreviated variable names ¹​host_name, ²​neighborhood, ³​room_latitude,\n#   ⁴​room_longitude, ⁵​room_type, ⁶​room_price\n```\n:::\n:::\n\n\nThe \"Boston_tidy\" data frame now has 17 variables and 5,185 rows of data. After removing the \"neighborhood group\" column (blank values across each case) and all additional duplicate and blank observations, each row now represents one unique case---or in this instance, a unique rental listing.\n\nNext, I will mutate variables. I will start off by adding the variable \"room_coordinates\" to my overall data set. I think this may come in handy if I choose to use a map for visualization, as I may need to match coordinates between my data set and those included in mapping packages such as 'map_data().'\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# mutate lat and lon to create \"room_coordinates\"\n# keep lat and lon columns for now\n\nBoston_mutate <- Boston_tidy %>%\nmutate(\"room_coordinates\" = paste(room_latitude, room_longitude))\ncolnames(Boston_mutate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"room_id\"               \"room_name\"             \"host_id\"              \n [4] \"host_name\"             \"neighborhood\"          \"room_latitude\"        \n [7] \"room_longitude\"        \"room_type\"             \"room_price\"           \n[10] \"min_nights\"            \"number_reviews\"        \"last_review\"          \n[13] \"reviews_per_month\"     \"host_listings\"         \"availability_next_365\"\n[16] \"number_reviews_LTM\"    \"room_license\"          \"room_coordinates\"     \n```\n:::\n:::\n\n\n## Exploratory Analysis\n\nI will next conduct some exploratory analysis to glean more insight related to my data set. First, I will generate statistics using raw data (not excluding outliers or values equal to 0) related to room price, minimum number of nights per stay, number of reviews per room, and number of listings by host.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# summary statistics for entire data set: \n\nsummary.data.frame(Boston_mutate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    room_id           room_name            host_id           host_name        \n Min.   :3.168e+03   Length:5185        Min.   :     3697   Length:5185       \n 1st Qu.:2.083e+07   Class :character   1st Qu.: 18517776   Class :character  \n Median :4.322e+07   Mode  :character   Median : 87330733   Mode  :character  \n Mean   :1.440e+17                      Mean   :125494858                     \n 3rd Qu.:5.358e+07                      3rd Qu.:212359760                     \n Max.   :7.162e+17                      Max.   :479130189                     \n                                                                              \n neighborhood       room_latitude   room_longitude    room_type        \n Length:5185        Min.   :42.23   Min.   :-71.20   Length:5185       \n Class :character   1st Qu.:42.33   1st Qu.:-71.11   Class :character  \n Mode  :character   Median :42.35   Median :-71.08   Mode  :character  \n                    Mean   :42.35   Mean   :-71.09                     \n                    3rd Qu.:42.37   3rd Qu.:-71.06                     \n                    Max.   :42.41   Max.   :-70.91                     \n                                                                       \n   room_price        min_nights     number_reviews    last_review       \n Min.   :    0.0   Min.   :  1.00   Min.   :   0.00   Length:5185       \n 1st Qu.:  100.0   1st Qu.:  2.00   1st Qu.:   1.00   Class :character  \n Median :  179.0   Median : 10.00   Median :   9.00   Mode  :character  \n Mean   :  230.6   Mean   : 27.41   Mean   :  47.31                     \n 3rd Qu.:  275.0   3rd Qu.: 32.00   3rd Qu.:  54.00                     \n Max.   :10000.0   Max.   :730.00   Max.   :1100.00                     \n                                                                        \n reviews_per_month host_listings    availability_next_365 number_reviews_LTM\n Min.   : 0.010    Min.   :  1.00   Min.   :  0.0         Min.   :  0.00    \n 1st Qu.: 0.310    1st Qu.:  2.00   1st Qu.: 77.0         1st Qu.:  0.00    \n Median : 1.060    Median :  6.00   Median :187.0         Median :  2.00    \n Mean   : 1.806    Mean   : 62.29   Mean   :189.7         Mean   : 13.19    \n 3rd Qu.: 2.660    3rd Qu.: 45.00   3rd Qu.:315.0         3rd Qu.: 17.00    \n Max.   :18.110    Max.   :477.00   Max.   :365.0         Max.   :256.00    \n NA's   :1225                                                               \n room_license       room_coordinates  \n Length:5185        Length:5185       \n Class :character   Class :character  \n Mode  :character   Mode  :character  \n                                      \n                                      \n                                      \n                                      \n```\n:::\n\n```{.r .cell-code}\n# summary statistics for particular group of variables:\n\nBoston_mutate %>% \n  select(room_price, min_nights, number_reviews, host_listings, availability_next_365) %>% \n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   room_price        min_nights     number_reviews    host_listings   \n Min.   :    0.0   Min.   :  1.00   Min.   :   0.00   Min.   :  1.00  \n 1st Qu.:  100.0   1st Qu.:  2.00   1st Qu.:   1.00   1st Qu.:  2.00  \n Median :  179.0   Median : 10.00   Median :   9.00   Median :  6.00  \n Mean   :  230.6   Mean   : 27.41   Mean   :  47.31   Mean   : 62.29  \n 3rd Qu.:  275.0   3rd Qu.: 32.00   3rd Qu.:  54.00   3rd Qu.: 45.00  \n Max.   :10000.0   Max.   :730.00   Max.   :1100.00   Max.   :477.00  \n availability_next_365\n Min.   :  0.0        \n 1st Qu.: 77.0        \n Median :187.0        \n Mean   :189.7        \n 3rd Qu.:315.0        \n Max.   :365.0        \n```\n:::\n:::\n\n\nThis raw data indicates that room prices for Boston Airbnbs range from \\$0-\\$10,000 per night---both of which I would assume are outliers---with the median price equaling \\$179 per night and the average price equaling \\$231 per night. Regarding the minimum number of nights per stay, values ranged from 1-730 nights. At first, I assumed the maximum value was an outlier, but Airbnb does offer long-term stays (\"long-term\" being defined as more than 28 days), so it is possible that this particular listing is for long-terms stays only. I also included the number of reviews per listing in this analysis to see if this may be an indicator of the popularity of certain rooms and, by extension, certain hosts. In the same vein, I included number of room-specific host listings in this summary, with the values ranging from 1-477 listings. The median number of room-specific listings per host is 6, while the average is 62. The final component of this analysis is listing availability over the next 365 days. The values range from 0-365 days, with the median value being 187 days and the average being 190 days.\n\nAs a precursor to a deeper analysis on number of host listings, I filtered the data set to include only values greater than one in the \"host_listings\" column, which tells us the number of rooms listed by the same host.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# filter by hosts with more than one listing:\n\nBoston_id <- Boston_mutate%>%\n  filter(host_listings>1)%>%\n  group_by(host_id, host_listings)\nhead(Boston_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 18\n# Groups:   host_id, host_listings [4]\n  room_id room_name      host_id host_…¹ neigh…² room_…³ room_…⁴ room_…⁵ room_…⁶\n    <dbl> <chr>            <dbl> <chr>   <chr>     <dbl>   <dbl> <chr>     <dbl>\n1    5506 ** Fort Hill …    8229 Terry   Roxbury    42.3   -71.1 Entire…     149\n2    6695 Fort Hill Inn…    8229 Terry   Roxbury    42.3   -71.1 Entire…     179\n3    8521 SunsplashedSe…  306681 Janet   Allston    42.4   -71.1 Entire…     300\n4    8789 Curved Glass …   26988 Anne    Beacon…    42.4   -71.1 Entire…     110\n5   10813 Back Bay Apt-…   38997 Michel… Back B…    42.4   -71.1 Entire…     135\n6   10986 North End (Wa…   38997 Michel… North …    42.4   -71.1 Entire…     135\n# … with 9 more variables: min_nights <dbl>, number_reviews <dbl>,\n#   last_review <chr>, reviews_per_month <dbl>, host_listings <dbl>,\n#   availability_next_365 <dbl>, number_reviews_LTM <dbl>, room_license <chr>,\n#   room_coordinates <chr>, and abbreviated variable names ¹​host_name,\n#   ²​neighborhood, ³​room_latitude, ⁴​room_longitude, ⁵​room_type, ⁶​room_price\n```\n:::\n:::\n\n\nThis output indicates that that there are 3,918 room-specfic listings whose hosts have more than one unique listing in Boston's Airbnb database.\n\nWe can also dig a little deeper into the number of room-specific listings by host for some additional context.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax_listings <- Boston_mutate%>%\n  select(host_id, host_name, room_name, neighborhood, host_listings, room_price, room_type)\nmax_477 <- max_listings[max_listings$host_listings == '477',]\nunique(max_477$host_name)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Blueground\"\n```\n:::\n\n```{.r .cell-code}\n# check listing prices:\n\nsummary(max_477$room_price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  142.0   205.0   231.0   245.1   268.0   487.0 \n```\n:::\n\n```{.r .cell-code}\n# check listing room types:\n\nunique(max_477$room_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Entire home/apt\"\n```\n:::\n\n```{.r .cell-code}\n# check listing neighborhoods:\n\nunique(max_477$neighborhood)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Bay Village\"             \"South Boston\"           \n [3] \"Back Bay\"                \"South End\"              \n [5] \"West End\"                \"Allston\"                \n [7] \"Brighton\"                \"Beacon Hill\"            \n [9] \"Downtown\"                \"Charlestown\"            \n[11] \"Chinatown\"               \"Fenway\"                 \n[13] \"South Boston Waterfront\" \"Dorchester\"             \n[15] \"Mission Hill\"            \"Roxbury\"                \n[17] \"Longwood Medical Area\"   \"North End\"              \n[19] \"Jamaica Plain\"           \"West Roxbury\"           \n```\n:::\n:::\n\n\nWe now know that there is one host, \"Blueground,\" who has 477 unique listings. This is the highest number of listings for a unique host within the entire data set. We do not gain much valuable insight from the remaining analyses, which indicate (1) summary statistics for the room prices across Blueground's listings (prices range from \\$142-\\$487 per night), (2) room types included across listings (entire home/apartment), and (3) neighborhoods across listings (listings in 20 Boston neighborhoods); I just thought it would be interesting to see if there were any patterns. However, aside from room type, the data appear to be widely spread.\n\nI will next generate some summary statistics for the categorical variable indicating listing neighborhood. Specifically, I would like to know which neighborhoods have the most and least number of listings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# max listing by neighborhood:\n\nunique_neighbor <- unique(Boston_mutate$neighborhood)\nnames(which.max(table(Boston_mutate$neighborhood)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Allston\"\n```\n:::\n\n```{.r .cell-code}\n# min listing by neighborhood:\n\nunique_neighbor <- unique(Boston_mutate$neighborhood)\nnames(which.min(table(Boston_mutate$neighborhood)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Leather District\"\n```\n:::\n:::\n\n\nWe can see from this tabulation that the most frequently listed neighborhood is Allston, and the neighborhood with the least amount of listings is the Leather District I will keep this in mind as I continue with my exploratory analysis; it would be interesting to see if the number of listings in either of these two neighborhoods provides insight into room price.\n\nNext, I will create a subset of data that includes the new variable \"median_price,\" which will only include room prices greater than \\$0. I will be using the median as the unit of measure to account for outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find median room price by neighborhood:\n\nBoston_median_neighbor <- Boston_mutate%>%\n  filter(room_price>0) %>%\n  group_by(neighborhood)%>%\n    summarize(median_price = median(room_price))\nprint(head(Boston_median_neighbor))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  neighborhood median_price\n  <chr>               <dbl>\n1 Allston               161\n2 Back Bay              287\n3 Bay Village           160\n4 Beacon Hill           199\n5 Brighton              125\n6 Charlestown           187\n```\n:::\n\n```{.r .cell-code}\nsummary(Boston_median_neighbor$median_price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   82.5   142.9   174.0   186.8   235.2   388.0 \n```\n:::\n:::\n\n\nThinking back to my question regarding the relationship between number of listings, neighborhood, and room price, there does not seem to be a correlation. We know that Allston has the highest number of listings, but we can also see from this most recent analysis that it ranks 14th out of the 26 Boston neighborhoods in terms of median room price (\\$161 per night). The Leather District, despite having the lowest number of room listings, is ranked 16th out of the 26 neighborhoods (\\$159 per night).\n\nI will now see if we can glean any interesting insight from data related to median room price by room type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find median room price by neighborhood:\n\nBoston_median_type <- Boston_mutate%>%\n  filter(room_price>0) %>%\n  group_by(room_type)%>%\n    summarize(median_price = median(room_price))\nprint(head(Boston_median_type))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  room_type       median_price\n  <chr>                  <dbl>\n1 Entire home/apt        229  \n2 Hotel room             396  \n3 Private room            84  \n4 Shared room             41.5\n```\n:::\n\n```{.r .cell-code}\nsummary(Boston_median_type$median_price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  41.50   73.38  156.50  187.62  270.75  396.00 \n```\n:::\n:::\n\n\nThis analysis tells us that the median room price for a hotel across the city of Boston is \\$396 per night, the median price of an entire home/apartment is \\$229 per night, the median price of a private room is \\$84 per night, and the median price for a shared room is \\$42 per night. I will consider this as I move forward with additional analyses.\n\nI will continue working with this data set, but I will now group by the original variables \"room_type\" and \"neighborhood.\" This will be useful in terms of both summary statistics and visualization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find median room prices by neighborhood and room type:\n\nBoston_median <- Boston_mutate%>%\n  filter(room_price>0) %>%\n  group_by(room_type, neighborhood)%>%\n    summarize(median_price = median(room_price))\nprint(head(Boston_median))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n# Groups:   room_type [1]\n  room_type       neighborhood median_price\n  <chr>           <chr>               <dbl>\n1 Entire home/apt Allston              216 \n2 Entire home/apt Back Bay             278 \n3 Entire home/apt Bay Village          200 \n4 Entire home/apt Beacon Hill          207 \n5 Entire home/apt Brighton             191 \n6 Entire home/apt Charlestown          240.\n```\n:::\n\n```{.r .cell-code}\nsummary(Boston_median$median_price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  10.00   85.25  150.50  176.11  228.50  750.00 \n```\n:::\n:::\n\n\nWe can see from this data set that the highest median room price is \\$750/night for a shared room in the Fenway neighborhood. The lowest median room price is \\$10/night for a shared room in Charlestown. Additionally, while there is spread across room types when viewing the most expensive listings, many of the lower-cost listings are shared rooms, which aligns with our previous analysis.\n\nI would like to dig a bit more into this by running additional analyses on listings in the Fenway and Charlestown neighborhoods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# summary statistics for Fenway: \n\nFenway <- Boston_mutate%>%\nfilter(neighborhood==\"Fenway\")%>%\n  select(neighborhood, room_type, room_price)\nsummary(Fenway$room_price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   35.0   135.0   242.5   276.9   354.5  1277.0 \n```\n:::\n\n```{.r .cell-code}\n# group by room_type:\n\nFenway_group <- Fenway%>%\n  group_by(room_type)%>%\n  summarize(mean_price = mean(room_price, na.rm = TRUE))\nFenway_group\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  room_type       mean_price\n  <chr>                <dbl>\n1 Entire home/apt       320.\n2 Private room          148.\n3 Shared room           750 \n```\n:::\n\n```{.r .cell-code}\n# 'table()' function not working, so filter by room type:\n\nShared <- Fenway%>%\n  filter(room_type==\"Shared room\")\nhead(Shared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 3\n  neighborhood room_type   room_price\n  <chr>        <chr>            <dbl>\n1 Fenway       Shared room        750\n```\n:::\n\n```{.r .cell-code}\nPrivate <- Fenway%>%\n  filter(room_type==\"Private room\")\nhead(Private)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  neighborhood room_type    room_price\n  <chr>        <chr>             <dbl>\n1 Fenway       Private room        199\n2 Fenway       Private room        265\n3 Fenway       Private room        295\n4 Fenway       Private room        130\n5 Fenway       Private room        109\n6 Fenway       Private room         84\n```\n:::\n\n```{.r .cell-code}\nEntire <- Fenway%>%\n  filter(room_type==\"Entire home/apt\")\nhead(Entire)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  neighborhood room_type       room_price\n  <chr>        <chr>                <dbl>\n1 Fenway       Entire home/apt        415\n2 Fenway       Entire home/apt        275\n3 Fenway       Entire home/apt        299\n4 Fenway       Entire home/apt        499\n5 Fenway       Entire home/apt        250\n6 Fenway       Entire home/apt        250\n```\n:::\n:::\n\n\nWe now know that room prices in the Fenway neighborhood ranges from \\$35 per night to \\$1,277 per night. This is a substantial range, so I don't think it provides much useful insight. However, we can see that average room prices vary significantly based on the type of room listing: \\$750 for a shared room; \\$320 for an entire home/apartment; and \\$148 for a private room. This does not exactly align with the trends we saw related to price per night by room type across the city. We also know that, specifically for the Fenway neighborhood, the number of listings by room type varies; there are 179 listings for an entire home/apt, 64 listings for private rooms, but only one listing for a shared room. So, this finding lessens the relevance of our average prices, as there is not a comparable distribution of data across metrics. It also creates contrast between overall trends citywide and what we see within neighborhoods.\n\n## Visualization\n\nI will next focus on data visualization. I will first generate a bar chart portraying median room price by neighborhood, as was described during exploratory analysis. This visual does not exclude outliers, though it will exclude room prices that equal zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(RColorBrewer)\nlibrary(ggtext)\nlibrary(ggplot2)\n\n# group median price by neighborhood:\n\nBoston_median_price <- Boston_mutate%>%\n  filter(room_price>0) %>%\n  group_by(neighborhood)%>%\n    summarize(median_price = median(room_price))\n\n# generate bar chart:\n\nggplot(Boston_median_price, aes(x=neighborhood, y=median_price, fill=neighborhood)) +\ngeom_bar(stat=\"identity\") +\nscale_fill_hue() +\n  theme_classic() +\n  labs(x=\"Neighborhood\",y=\"Median Price per Night\", title = \"Boston Airbnb Median Rental Prices \\nby Neighborhood\")+\n  theme(axis.text.x = element_markdown(angle=90, hjust=1))\n```\n\n::: {.cell-output-display}\n![](Caitlin-Rowley---Final-Project_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThis bar chart provides us with a visual of the neighborhoods with the highest median room price per night. These are (1) Chinatown at \\$388 per night , (2) Back Bay at \\$287 per night, and (3) Downtown at about \\$261 per night. The neighborhoods with the lowest median prices are Roxbury at about \\$83 per night, (2) Dorchester at \\$97 per night, and (3) Hyde Park at about \\$99 per night.\n\nI will also adjust this visual to display median room price by room type, as was also described during exploratory analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# group median price by room_type:\n\nBoston_median_type <- Boston_mutate%>%\n  filter(room_price>0) %>%\n  group_by(room_type)%>%\n    summarize(median_price = median(room_price))\n\n# generate bar chart:\n\nggplot(Boston_median_type, aes(x=room_type, y=median_price, fill=room_type)) +\ngeom_bar(stat=\"identity\") +\nscale_fill_hue() +\n  theme_classic() +\n  labs(x=\"Room Type\",y=\"Median Price per Night\", title = \"Boston Airbnb Median Rental Prices \\nby Room Type\")+\n  theme(axis.text.x = element_markdown(angle=90, hjust=1))\n```\n\n::: {.cell-output-display}\n![](Caitlin-Rowley---Final-Project_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nAs we know, hotel rooms in the city of Boston are the most expensive when compared to other listing types at \\$396 per night. Next are entire homes/apartments at \\$229 per night, followed by private rooms (\\$84 per night) and shared rooms (about \\$42 per night).\n\nI will next generate a geom_point chart to visualize room price by neighborhood. I will also use facet wrapping to separate the values by room type. I will also apply a boxplot overlay to capture both the interquartile range and outliers. I will first need to exclude strong outliers\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# remove outliers:\n\nis_outlier <- function(x) {\n  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))\n}\n\nBoston_outlier <- Boston_mutate %>%\n  filter(!is_outlier(room_price))\n\n# create dataframe:\n\nBoston_outlier%>%\n  filter(room_price>0, room_price<800) %>%\n  group_by(room_type, neighborhood)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4,918 × 18\n# Groups:   room_type, neighborhood [65]\n   room_id room_name     host_id host_…¹ neigh…² room_…³ room_…⁴ room_…⁵ room_…⁶\n     <dbl> <chr>           <dbl> <chr>   <chr>     <dbl>   <dbl> <chr>     <dbl>\n 1    3168 TudorStudio      3697 Mark    Bright…    42.4   -71.2 Privat…      99\n 2    3781 HARBORSIDE-W…    4804 Frank   East B…    42.4   -71.0 Entire…     132\n 3    5506 ** Fort Hill…    8229 Terry   Roxbury    42.3   -71.1 Entire…     149\n 4    6695 Fort Hill In…    8229 Terry   Roxbury    42.3   -71.1 Entire…     179\n 5    7903 Colorful, mo…   14169 Stacy   Charle…    42.4   -71.1 Privat…     116\n 6    8521 SunsplashedS…  306681 Janet   Allston    42.4   -71.1 Entire…     300\n 7    8789 Curved Glass…   26988 Anne    Beacon…    42.4   -71.1 Entire…     110\n 8   10813 Back Bay Apt…   38997 Michel… Back B…    42.4   -71.1 Entire…     135\n 9   10986 North End (W…   38997 Michel… North …    42.4   -71.1 Entire…     135\n10   18711 230B1 · The …   71783 Lance   Dorche…    42.3   -71.1 Entire…     133\n# … with 4,908 more rows, 9 more variables: min_nights <dbl>,\n#   number_reviews <dbl>, last_review <chr>, reviews_per_month <dbl>,\n#   host_listings <dbl>, availability_next_365 <dbl>, number_reviews_LTM <dbl>,\n#   room_license <chr>, room_coordinates <chr>, and abbreviated variable names\n#   ¹​host_name, ²​neighborhood, ³​room_latitude, ⁴​room_longitude, ⁵​room_type,\n#   ⁶​room_price\n```\n:::\n\n```{.r .cell-code}\n# generate geom_point chart\n# facet wrap\n# boxplot overlay\n\nBoston_outlier%>%\n group_by(room_type, neighborhood)%>%\n  ggplot(aes(x=neighborhood, y=room_price)) +\n  geom_point(alpha=.08, size=3, color = \"light pink\")+\n  facet_wrap(\"room_type\")+\n  labs(x=\"Neighborhood\",y=\"Price per Night\", title = \"Boston Airbnb Rental Prices by Neighborhood and Room Type\")+\n  theme_light()+\n  geom_boxplot()+\n  theme(axis.text.x = element_markdown(angle = 90, hjust=1))\n```\n\n::: {.cell-output-display}\n![](Caitlin-Rowley---Final-Project_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThis visual is bit tricky to read, but at a quick glance, we can at the very least see that there are the most listings for entire homes/apartments across the city. We can also see the shared rooms have the lowest prices overall. Though I think this provides useful information, it is still too difficult to read due to the number of neighborhoods, so I am going to apply the three variables (room price, room type, and neighborhood) to another visual.\n\nI will instead display a simpler version of this geom_point chart without the facet wrap so that the visual only captures neighborhood and room price per night.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate geom_point chart with boxplot:\n\nBoston_outlier%>%\n group_by(room_type, neighborhood)%>%\n  ggplot(aes(x=neighborhood, y=room_price)) +\n  geom_point(alpha=.08, size=5, color = \"light pink\")+\n  labs(x=\"Neighborhood\",y=\"Price per Night\", title = \"Boston Airbnb Rental Prices by Neighborhood\")+\n  theme_light()+\n  geom_boxplot()+\n  theme(axis.text.x = element_markdown(angle = 90, hjust=1))\n```\n\n::: {.cell-output-display}\n![](Caitlin-Rowley---Final-Project_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# want to add values: text(x = Boston_outlier$room_price, y = Boston_outlier$room_price, labels = Boston_outlier$room_price)\n```\n:::\n\n\nHere, we can see the distribution of prices across neighborhoods using individual data points. We can also see the spread of data points with the boxplot overlay, which includes the minimum value, the values within the 25th quartile, the median value, the values within the 75th quartile, and the maximum value. The boxplot also indicates outliers. With this visualization, we can see that neighborhoods with the narrowest distribution of data points---or, in this case, room prices---are Chinatown and the Leather District, while the neighborhoods with the broadest distribution of data points seem to be Charlestown, Harbor Islands and Mattapan.\n\nI will next visualize the data using a choropleth map. I will generate a map of the Boston area and apply data related to neighborhood, room price, and room type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(maps)\nlibrary(viridisLite)\nlibrary(ggplot2)\nlibrary(tidyverse)\n\n# generate map\n\nstates_map <- map_data(\"state\")\nhead(states_map)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       long      lat group order  region subregion\n1 -87.46201 30.38968     1     1 alabama      <NA>\n2 -87.48493 30.37249     1     2 alabama      <NA>\n3 -87.52503 30.37249     1     3 alabama      <NA>\n4 -87.53076 30.33239     1     4 alabama      <NA>\n5 -87.57087 30.32665     1     5 alabama      <NA>\n6 -87.58806 30.32665     1     6 alabama      <NA>\n```\n:::\n\n```{.r .cell-code}\nma_map <- filter(states_map, region==\"massachusetts\") %>%\nggplot(., aes(x=long, y=lat, group=group)) +\n  geom_polygon(fill=\"light pink\", color=\"white\")\nprint(ma_map)\n```\n\n::: {.cell-output-display}\n![](Caitlin-Rowley---Final-Project_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nI've generated the map of Massachusetts, so now I will work on merging my data sets to apply as an overlay to the map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# merge 'ma_map' and 'Boston_tidy' by coordinates\n\n# mutate and rename columns\n\nBoston_coord <- Boston_mutate %>%\n  rename(\"coordinates\" = \"room_coordinates\")\nhead(Boston_coord)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 18\n  room_id room_name      host_id host_…¹ neigh…² room_…³ room_…⁴ room_…⁵ room_…⁶\n    <dbl> <chr>            <dbl> <chr>   <chr>     <dbl>   <dbl> <chr>     <dbl>\n1    3168 TudorStudio       3697 Mark    Bright…    42.4   -71.2 Privat…      99\n2    3781 HARBORSIDE-Wa…    4804 Frank   East B…    42.4   -71.0 Entire…     132\n3    5506 ** Fort Hill …    8229 Terry   Roxbury    42.3   -71.1 Entire…     149\n4    6695 Fort Hill Inn…    8229 Terry   Roxbury    42.3   -71.1 Entire…     179\n5    7903 Colorful, mod…   14169 Stacy   Charle…    42.4   -71.1 Privat…     116\n6    8521 SunsplashedSe…  306681 Janet   Allston    42.4   -71.1 Entire…     300\n# … with 9 more variables: min_nights <dbl>, number_reviews <dbl>,\n#   last_review <chr>, reviews_per_month <dbl>, host_listings <dbl>,\n#   availability_next_365 <dbl>, number_reviews_LTM <dbl>, room_license <chr>,\n#   coordinates <chr>, and abbreviated variable names ¹​host_name,\n#   ²​neighborhood, ³​room_latitude, ⁴​room_longitude, ⁵​room_type, ⁶​room_price\n```\n:::\n\n```{.r .cell-code}\nma_map_df <- filter(states_map, region==\"massachusetts\")\nma_mutate <- ma_map_df %>%\n  mutate(\"coordinates\" = paste(lat, long))\nhead(ma_mutate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       long      lat group order        region         subregion\n1 -70.45089 41.40193    20  5926 massachusetts martha's vineyard\n2 -70.45662 41.39047    20  5927 massachusetts martha's vineyard\n3 -70.45662 41.37328    20  5928 massachusetts martha's vineyard\n4 -70.46808 41.35609    20  5929 massachusetts martha's vineyard\n5 -70.50819 41.35609    20  5930 massachusetts martha's vineyard\n6 -70.56548 41.34464    20  5931 massachusetts martha's vineyard\n                         coordinates\n1  41.401927947998 -70.4508895874023\n2 41.3904724121094 -70.4566192626953\n3 41.3732833862305 -70.4566192626953\n4 41.3560943603516 -70.4680786132812\n5  41.3560943603516 -70.508186340332\n6 41.3446350097656 -70.5654830932617\n```\n:::\n\n```{.r .cell-code}\n# merge data \n\nmap_merge <- merge(ma_mutate, Boston_coord, by = \"coordinates\", all=T)\nhead(map_merge)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         coordinates      long      lat group order\n1 41.2415008544922 -70.0211715698242 -70.02117 41.24150    22  6202\n2 41.2415008544922 -70.0498199462891 -70.04982 41.24150    22  6203\n3 41.2529640197754 -69.9753341674805 -69.97533 41.25296    22  6201\n4 41.2529640197754 -70.0956573486328 -70.09566 41.25296    22  6204\n5 41.2586898803711 -69.9524230957031 -69.95242 41.25869    22  6200\n6 41.2586898803711 -70.1529541015625 -70.15295 41.25869    22  6205\n         region subregion room_id room_name host_id host_name neighborhood\n1 massachusetts nantucket      NA      <NA>      NA      <NA>         <NA>\n2 massachusetts nantucket      NA      <NA>      NA      <NA>         <NA>\n3 massachusetts nantucket      NA      <NA>      NA      <NA>         <NA>\n4 massachusetts nantucket      NA      <NA>      NA      <NA>         <NA>\n5 massachusetts nantucket      NA      <NA>      NA      <NA>         <NA>\n6 massachusetts nantucket      NA      <NA>      NA      <NA>         <NA>\n  room_latitude room_longitude room_type room_price min_nights number_reviews\n1            NA             NA      <NA>         NA         NA             NA\n2            NA             NA      <NA>         NA         NA             NA\n3            NA             NA      <NA>         NA         NA             NA\n4            NA             NA      <NA>         NA         NA             NA\n5            NA             NA      <NA>         NA         NA             NA\n6            NA             NA      <NA>         NA         NA             NA\n  last_review reviews_per_month host_listings availability_next_365\n1        <NA>                NA            NA                    NA\n2        <NA>                NA            NA                    NA\n3        <NA>                NA            NA                    NA\n4        <NA>                NA            NA                    NA\n5        <NA>                NA            NA                    NA\n6        <NA>                NA            NA                    NA\n  number_reviews_LTM room_license\n1                 NA         <NA>\n2                 NA         <NA>\n3                 NA         <NA>\n4                 NA         <NA>\n5                 NA         <NA>\n6                 NA         <NA>\n```\n:::\n\n```{.r .cell-code}\n# remove if room_id is NA when merged with map data\n\nmap_merged <- map_merge %>% filter(!is.na(map_merge$room_id))\nhead(map_merged)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         coordinates long lat group order region subregion  room_id\n1 42.23117 -71.15312   NA  NA    NA    NA   <NA>      <NA> 13997739\n2  42.2353 -71.12879   NA  NA    NA    NA   <NA>      <NA> 18305618\n3 42.23533 -71.13256   NA  NA    NA    NA   <NA>      <NA>  3164650\n4 42.23543 -71.13076   NA  NA    NA    NA   <NA>      <NA> 13697676\n5   42.23547 -71.131   NA  NA    NA    NA   <NA>      <NA> 15665935\n6  42.2355 -71.13134   NA  NA    NA    NA   <NA>      <NA> 16379917\n                                           room_name   host_id host_name\n1 Hidden Gem Near Boston w/ 2 bedrooms HighSpeedWifi  29538655 Hu And Lu\n2     Boston’s Luxury Cellar Apartment, Comfy & Cozy 126495858    Silvia\n3                 2bd APT 20min from Downtown Boston  16052189  Jonathan\n4                    Calm and cozy room in clean Apt  16052189  Jonathan\n5   Boston private room - Spacious, tidy, close to T  16052189  Jonathan\n6    Beautiful 2bd Boston open concept apt w/parking  16052189  Jonathan\n  neighborhood room_latitude room_longitude       room_type room_price\n1    Hyde Park      42.23117      -71.15312 Entire home/apt        119\n2    Hyde Park      42.23530      -71.12879 Entire home/apt        135\n3    Hyde Park      42.23533      -71.13256 Entire home/apt         89\n4    Hyde Park      42.23543      -71.13076    Private room         28\n5    Hyde Park      42.23547      -71.13100    Private room         30\n6    Hyde Park      42.23550      -71.13134 Entire home/apt        149\n  min_nights number_reviews last_review reviews_per_month host_listings\n1          1            677   9/13/2022              9.04             1\n2          2             43    9/4/2022              7.17             1\n3         29             33    3/2/2021              0.33             5\n4         91             11  11/25/2020              0.17             5\n5         91              6  12/31/2019              0.12             5\n6         29              7    7/2/2019              0.10             5\n  availability_next_365 number_reviews_LTM room_license\n1                   279                125         <NA>\n2                   313                 43   STR-467769\n3                   267                  0         <NA>\n4                   291                  0         <NA>\n5                   308                  0         <NA>\n6                   274                  0         <NA>\n```\n:::\n:::\n\n\nI now have my map and my merged data, but the data would be illegible if it the map is kept at its current scale. I'd like the data points to be mapped according to each listing's coordinates, so I will try an iteration of the above code to generate this visual. For this graph, I will include all listings by neighborhood and by price.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load map, plot data\n\nMA_map <- map_data(\"state\")\nBoston_map <- filter(states_map, region == \"massachusetts\")%>%\n  ggplot() + geom_polygon(data = map_merged, aes(x = long, y = lat, group = group), colour = \"black\", fill = NA) + geom_point(data = Boston_mutate, aes(x = room_latitude, y = room_longitude, size = room_price, color = neighborhood)) + scale_y_reverse() + scale_x_reverse() + labs(x=\"Latitude\",y=\"Longitude\", title = \"Boston Airbnb \\nRental Prices \\nby Neighborhood\") + coord_map() + theme(axis.text.x = element_markdown(angle = 90, hjust=1))\nBoston_map + theme(legend.position=\"left\")\n```\n\n::: {.cell-output-display}\n![](Caitlin-Rowley---Final-Project_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nWhile this is helpful in terms of understanding the geographic spread of Boston neighborhoods (though because there are so many, some colors appear to be very similar), there are too many data points included in this visual to accurately depict the spread of room price. I will instead return to measuring median room prices in a way that captures both neighborhood and room type.\n\nThis visual captures median room price by both neighborhood and room type. I think this is the clearest and most informative visual.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBoston_med_neigh_room <- Boston_median%>%\n  ggplot(aes(median_price, neighborhood))+\n  geom_point(aes(color=room_type, shape=room_type))+  \n  labs(x=\"Median Room Price\",y=\"Neighborhood\", title = \"Boston Airbnb Median Room Prices by \\nNeighborhood and Room Type\")\nprint(Boston_med_neigh_room)\n```\n\n::: {.cell-output-display}\n![](Caitlin-Rowley---Final-Project_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThis visual clearly depicts median room prices by neighborhood according to room type (as denoted by different shapes). We can observe general trends here: compared to private and shared rooms, entire homes/apartments tend to be priced higher; neighborhoods nearer Downtown or the water (e.g., Chinatown, Back Bay, Downtown) tend to have higher median prices. However, more notable is that not every neighborhood has listings for each room type, so it is quite difficult to determine trends in pricing across the entire city. Additionally, this visual does not account for the number of listings, so it is possible that there are instances---similar to that we saw in the Fenway neighborhood---where there may be significant variation in the number of listings for a particular room type, which ultimately skews the data. So, while this provides information that sets the groundwork for the foundation of my research question---we now know, for example, the spread of data across neighborhood, room price, and room type---I have very limited insight related to whether correlations exist between these variables.\n\n## Reflection\n\nI found this project to be extremely interesting, specifically in terms of selecting criteria to evaluate. The process of finalizing my research question was a combination of considering ways in which I could slice the data to gain insight into different patterns within the data, and also running various analyses to see which provided interesting outputs. Initially, I conducted analyses to identify trends across variables outside the scope of my research question to see if any links could be drawn to room price, but I did not find those analyses to be very informative; I eventually settled on investigating the correlation between room price and neighborhood/room type because I thought the latter two would prove to be the clearest indicators of pricing trends. So, I ran a plethora of code chunks that I hoped would determine patterns across these three variables, and provided visuals for outputs that I thought were most informative.\n\nHowever, upon deeper analysis, I realized that there are more factors that need to be considered if I were to determine any true patterns within the data. For example, as noted in my final visual, I now realize that it is important to understand the spread of listings across neighborhoods; in other words, in order to gauge the effect of room type on room price by neighborhood, I need to understand not only how many listings there are per neighborhood, but also the distribution of those listings across room types. This would then need to be incorporated into my analyses, which would, of course, require a more in-depth evaluation of the data.\n\nIn terms of challenges, I would say that I found adjusting certain aesthetics in my visuals to be difficult at times; I am, however, confident that this will improve as I gain more experience.\n\n## Conclusion\n\nAs someone who lives close to Boston, it is unsurprising to see certain trends across neighborhood rental prices; as previously noted, it would generally be expected that neighborhoods closer to the water and downtown Boston (e.g., Chinatown, Back Bay, and Downtown) would be more expensive per night compared to neighborhoods in lower Boston (e.g., Roxbury, Dorchester, and Hyde Park). However, these trends were not necessarily conclusive, as variation across room types indicated outliers, and I did not account for the spread of listings---by either sheer quantity nor by room type---across each neighborhood. So, aside from gathering insight from bivariate analyses---such as median room prices by neighborhood and room type *separately*, as displayed in the colored bar charts---it is difficult to summarize meaningful conclusions based on my research question.\n\nTo better assess the *combined* effects of neighborhood, I'd like to do more in-depth analysis considering number of listings per neighborhood within the context of room price *and* room type. Fenway is an example of a neighborhood for which the room type with the highest median price is a shared room, and while this contradicts overall pricing trends, there is only one shared room listing. So, I think this would be an interesting path to consider additional factors that may contribute to room prices, specifically in terms of median, average, and range values. I'd also like to do more analysis to determine outliers so that we can more accurately gauge average room prices. As an additional metric, it may also be interesting to dive deeper into the minimum number of nights per stay---as mentioned during exploratory analysis---to see if there are any implications of long-terms stays across the data set in terms of room price.\n\n## Citations\n\n-   Get the Data: Boston, Massachusetts, United States (2022). Inside Airbnb. http://insideairbnb.com/get-the-data/\n\n-   Grolemund, Hadley Wickham and Garrett. \"R For Data Science.\" *R For Data Science*, O'Reilly Media, Inc., Dec. 2016, https://r4ds.had.co.nz/index.html#welcome.\n\n-   RStudio Team (2020). RStudio: Integrated Development for R. RStudio, PBC, Boston, MA URL http://www.rstudio.com/\n",
    "supporting": [
      "Caitlin-Rowley---Final-Project_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}