{
  "hash": "d1f4a82f1015a2cc3dfbdffd2571f818",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3\"\nauthor: \"Jack Sniezek\"\ndesription: \"Tidy Data: Pivoting\"\ndate: \"12/1/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - animal_weights\n  - eggs\n  - australian_marriage\n  - usa_households\n  - sce_labor\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1.  read in a data set, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2.  identify what needs to be done to tidy the current data\n3.  anticipate the shape of pivoted data\n4.  pivot the data into tidy format using `pivot_longer`\n\n## Read in data\n\n-   eggs_tidy.csv ⭐⭐ \n\n\n::: {.cell}\n\n```{.r .cell-code}\neggs <- read_csv(\"_data/eggs_tidy.csv\")%>%\n    rename(\"xlarge_halfdozen\" = \"extra_large_half_dozen\", \n         \"xlarge_dozen\" = \"extra_large_dozen\", \n         \"large_halfdozen\" = \"large_half_dozen\")\neggs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 120 × 6\n   month      year large_halfdozen large_dozen xlarge_halfdozen xlarge_dozen\n   <chr>     <dbl>           <dbl>       <dbl>            <dbl>        <dbl>\n 1 January    2004            126         230              132          230 \n 2 February   2004            128.        226.             134.         230 \n 3 March      2004            131         225              137          230 \n 4 April      2004            131         225              137          234.\n 5 May        2004            131         225              137          236 \n 6 June       2004            134.        231.             137          241 \n 7 July       2004            134.        234.             137          241 \n 8 August     2004            134.        234.             137          241 \n 9 September  2004            130.        234.             136.         241 \n10 October    2004            128.        234.             136.         241 \n# … with 110 more rows\n```\n:::\n\n```{.r .cell-code}\nsummary(eggs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    month                year      large_halfdozen  large_dozen   \n Length:120         Min.   :2004   Min.   :126.0   Min.   :225.0  \n Class :character   1st Qu.:2006   1st Qu.:129.4   1st Qu.:233.5  \n Mode  :character   Median :2008   Median :174.5   Median :267.5  \n                    Mean   :2008   Mean   :155.2   Mean   :254.2  \n                    3rd Qu.:2011   3rd Qu.:174.5   3rd Qu.:268.0  \n                    Max.   :2013   Max.   :178.0   Max.   :277.5  \n xlarge_halfdozen  xlarge_dozen  \n Min.   :132.0    Min.   :230.0  \n 1st Qu.:135.8    1st Qu.:241.5  \n Median :185.5    Median :285.5  \n Mean   :164.2    Mean   :266.8  \n 3rd Qu.:185.5    3rd Qu.:285.5  \n Max.   :188.1    Max.   :290.0  \n```\n:::\n:::\n\n\n## Briefly describe the data\n\nAfter reading in the eggs dataset, I can see that there are 120 rows that contain each month from 2004-2013. There are 6 columns that represent the month and year, as well as average egg prices for 4 types/quantities of eggs.\n\nOn the read in, I also renamed the columns to keep the size and quantity of eggs separate, which will help me pivot the data.\n\n## Anticipate the End Result\n\nRight now the data consists of 6 columns, 4 of which contain values and 2 categorize the data. To make the data easier to work with, I want to make one column with values(Price) and add a column for size and quantity of eggs. So, my new matrix will contain the month, year, size, quantity, and price. I also anticipate that there will be 480 rows, as I will be putting all the price values into one column (120 months x 4 price variables).\n\n## Pivot the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\neggs_longer <- eggs %>%\n   pivot_longer(cols = contains(\"large\"),\n               names_to = c(\"size\", \"quantity\"),\n               names_sep = \"_\",\n               values_to = \"price\")\n\neggs_longer\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 480 × 5\n   month     year size   quantity  price\n   <chr>    <dbl> <chr>  <chr>     <dbl>\n 1 January   2004 large  halfdozen  126 \n 2 January   2004 large  dozen      230 \n 3 January   2004 xlarge halfdozen  132 \n 4 January   2004 xlarge dozen      230 \n 5 February  2004 large  halfdozen  128.\n 6 February  2004 large  dozen      226.\n 7 February  2004 xlarge halfdozen  134.\n 8 February  2004 xlarge dozen      230 \n 9 March     2004 large  halfdozen  131 \n10 March     2004 large  dozen      225 \n# … with 470 more rows\n```\n:::\n:::\n\n\n\nThe data matches my prediction, as I now have 480 rows and 5 columns. The data is now organized so that there is one column that contains all the price values.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}