{
  "hash": "f7543aca53ff8dfbdcc798a9ada1faee",
  "result": {
    "markdown": "---\ntitle: \"Challenge 8\"\nauthor: \"Aleacia Messiah\"\ndescription: \"Joining Data\"\ndate: \"12/08/2022\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_8\n  - Aleacia Messiah\n  - snl\n  - tidyverse\n  - ggplot2\n  - summarytools\n  - lubridate\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(summarytools)\nlibrary(lubridate)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to:\n\n1)  read in multiple data sets, and describe the data set using both words and any supporting information (e.g., tables, etc)\n2)  tidy data (as needed, including sanity checks)\n3)  mutate variables as needed (including sanity checks)\n4)  join two or more data sets and analyze some aspect of the joined data\n\n(be sure to only include the category tags for the data you use!)\n\n## Read in data\n\nRead in one (or more) of the following datasets, using the correct R package and command.\n\n-   military marriages ⭐⭐\n-   faostat ⭐⭐\n-   railroads ⭐⭐⭐\n-   fed_rate ⭐⭐⭐\n-   debt ⭐⭐⭐\n-   us_hh ⭐⭐⭐⭐\n-   snl ⭐⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in snl actors dataset\nactors_orig <- read_csv(\"_data/snl_actors.csv\")\n# read in snl casts dataset\ncasts_orig <- read_csv(\"_data/snl_casts.csv\")\n# read in snl seasons dataset\nseasons_orig <- read_csv(\"_data/snl_seasons.csv\")\n# view datasets\nactors_orig\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,306 × 4\n   aid            url           type  gender \n   <chr>          <chr>         <chr> <chr>  \n 1 Kate McKinnon  /Cast/?KaMc   cast  female \n 2 Alex Moffat    /Cast/?AlMo   cast  male   \n 3 Ego Nwodim     /Cast/?EgNw   cast  unknown\n 4 Chris Redd     /Cast/?ChRe   cast  male   \n 5 Kenan Thompson /Cast/?KeTh   cast  male   \n 6 Carey Mulligan /Guests/?3677 guest andy   \n 7 Marcus Mumford /Guests/?3679 guest male   \n 8 Aidy Bryant    /Cast/?AiBr   cast  female \n 9 Steve Higgins  /Crew/?StHi   crew  male   \n10 Mikey Day      /Cast/?MiDa   cast  male   \n# … with 2,296 more rows\n```\n:::\n\n```{.r .cell-code}\ncasts_orig\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 614 × 8\n   aid                sid featured first_epid last_epid update…¹ n_epi…² seaso…³\n   <chr>            <dbl> <lgl>         <dbl>     <dbl> <lgl>      <dbl>   <dbl>\n 1 A. Whitney Brown    11 TRUE       19860222        NA FALSE          8   0.444\n 2 A. Whitney Brown    12 TRUE             NA        NA FALSE         20   1    \n 3 A. Whitney Brown    13 TRUE             NA        NA FALSE         13   1    \n 4 A. Whitney Brown    14 TRUE             NA        NA FALSE         20   1    \n 5 A. Whitney Brown    15 TRUE             NA        NA FALSE         20   1    \n 6 A. Whitney Brown    16 TRUE             NA        NA FALSE         20   1    \n 7 Alan Zweibel         5 TRUE       19800409        NA FALSE          5   0.25 \n 8 Sasheer Zamata      39 TRUE       20140118        NA FALSE         11   0.524\n 9 Sasheer Zamata      40 TRUE             NA        NA FALSE         21   1    \n10 Sasheer Zamata      41 FALSE            NA        NA FALSE         21   1    \n# … with 604 more rows, and abbreviated variable names ¹​update_anchor,\n#   ²​n_episodes, ³​season_fraction\n```\n:::\n\n```{.r .cell-code}\nseasons_orig\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 46 × 5\n     sid  year first_epid last_epid n_episodes\n   <dbl> <dbl>      <dbl>     <dbl>      <dbl>\n 1     1  1975   19751011  19760731         24\n 2     2  1976   19760918  19770521         22\n 3     3  1977   19770924  19780520         20\n 4     4  1978   19781007  19790526         20\n 5     5  1979   19791013  19800524         20\n 6     6  1980   19801115  19810411         13\n 7     7  1981   19811003  19820522         20\n 8     8  1982   19820925  19830514         20\n 9     9  1983   19831008  19840512         19\n10    10  1984   19841006  19850413         17\n# … with 36 more rows\n```\n:::\n\n```{.r .cell-code}\n# view summaries of datasets\ndfSummary(actors_orig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nactors_orig  \nDimensions: 2306 x 4  \nDuplicates: 0  \n\n------------------------------------------------------------------------------------------------------------\nNo   Variable      Stats / Values            Freqs (% of Valid)   Graph                 Valid      Missing  \n---- ------------- ------------------------- -------------------- --------------------- ---------- ---------\n1    aid           1. 'N Sync                   1 ( 0.0%)                               2306       0        \n     [character]   2. 070 Shake                 1 ( 0.0%)                               (100.0%)   (0.0%)   \n                   3. 10,000 Maniacs            1 ( 0.0%)                                                   \n                   4. 14 Karat Soul             1 ( 0.0%)                                                   \n                   5. 2 Chainz                  1 ( 0.0%)                                                   \n                   6. 3-D                       1 ( 0.0%)                                                   \n                   7. 3RDEYEGIRL                1 ( 0.0%)                                                   \n                   8. 50 Cent                   1 ( 0.0%)                                                   \n                   9. A Tribe Called Quest      1 ( 0.0%)                                                   \n                   10. A$AP Rocky               1 ( 0.0%)                                                   \n                   [ 2296 others ]           2296 (99.6%)         IIIIIIIIIIIIIIIIIII                       \n\n2    url           1. /Cast/?AbEl               1 ( 0.0%)                               2249       57       \n     [character]   2. /Cast/?AdSa               1 ( 0.0%)                               (97.5%)    (2.5%)   \n                   3. /Cast/?AiBr               1 ( 0.0%)                                                   \n                   4. /Cast/?AlFr               1 ( 0.0%)                                                   \n                   5. /Cast/?AlMo               1 ( 0.0%)                                                   \n                   6. /Cast/?AlZw               1 ( 0.0%)                                                   \n                   7. /Cast/?AmPo               1 ( 0.0%)                                                   \n                   8. /Cast/?AnDi               1 ( 0.0%)                                                   \n                   9. /Cast/?AnGa               1 ( 0.0%)                                                   \n                   10. /Cast/?AnMH              1 ( 0.0%)                                                   \n                   [ 2239 others ]           2239 (99.6%)         IIIIIIIIIIIIIIIIIII                       \n\n3    type          1. cast                    154 ( 6.7%)         I                     2306       0        \n     [character]   2. crew                    170 ( 7.4%)         I                     (100.0%)   (0.0%)   \n                   3. guest                  1926 (83.5%)         IIIIIIIIIIIIIIII                          \n                   4. unknown                  56 ( 2.4%)                                                   \n\n4    gender        1. andy                     21 ( 0.9%)                               2306       0        \n     [character]   2. female                  671 (29.1%)         IIIII                 (100.0%)   (0.0%)   \n                   3. male                   1226 (53.2%)         IIIIIIIIII                                \n                   4. unknown                 388 (16.8%)         III                                       \n------------------------------------------------------------------------------------------------------------\n```\n:::\n\n```{.r .cell-code}\ndfSummary(casts_orig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \ncasts_orig  \nDimensions: 614 x 8  \nDuplicates: 0  \n\n------------------------------------------------------------------------------------------------------------------------\nNo   Variable          Stats / Values                    Freqs (% of Valid)   Graph                 Valid      Missing  \n---- ----------------- --------------------------------- -------------------- --------------------- ---------- ---------\n1    aid               1. Kenan Thompson                  18 ( 2.9%)                                614        0        \n     [character]       2. Darrell Hammond                 14 ( 2.3%)                                (100.0%)   (0.0%)   \n                       3. Seth Meyers                     13 ( 2.1%)                                                    \n                       4. Al Franken                      11 ( 1.8%)                                                    \n                       5. Fred Armisen                    11 ( 1.8%)                                                    \n                       6. Kate McKinnon                   10 ( 1.6%)                                                    \n                       7. Tim Meadows                     10 ( 1.6%)                                                    \n                       8. Aidy Bryant                      9 ( 1.5%)                                                    \n                       9. Bobby Moynihan                   9 ( 1.5%)                                                    \n                       10. Cecily Strong                   9 ( 1.5%)                                                    \n                       [ 146 others ]                    500 (81.4%)          IIIIIIIIIIIIIIII                          \n\n2    sid               Mean (sd) : 25.5 (13.1)           46 distinct values         .           :   614        0        \n     [numeric]         min < med < max:                                             :   :   : . :   (100.0%)   (0.0%)   \n                       1 < 26 < 46                                            : : . : : : : : : :                       \n                       IQR (CV) : 22 (0.5)                                    : : : : : : : : : :                       \n                                                                              : : : : : : : : : :                       \n\n3    featured          1. FALSE                          451 (73.5%)          IIIIIIIIIIIIII        614        0        \n     [logical]         2. TRUE                           163 (26.5%)          IIIII                 (100.0%)   (0.0%)   \n\n4    first_epid        Mean (sd) : 19909635 (111264.8)   35 distinct values     :                   50         564      \n     [numeric]         min < med < max:                                         :   :               (8.1%)     (91.9%)  \n                       19770115 < 19901110 < 20141025                           :   :                                   \n                       IQR (CV) : 156624.2 (0)                                : : . : :   : .                           \n                                                                              : : : : : . : :                           \n\n5    last_epid         Mean (sd) : 19944038 (126122.2)   17 distinct values           :             17         597      \n     [numeric]         min < med < max:                                       :       :             (2.8%)     (97.2%)  \n                       19751011 < 19950225 < 20140201                         :   .   : . . .                           \n                       IQR (CV) : 190005 (0)                                  :   :   : : : :                           \n                                                                              : : : : : : : :                           \n\n6    update_anchor     1. FALSE                          541 (88.1%)          IIIIIIIIIIIIIIIII     614        0        \n     [logical]         2. TRUE                            73 (11.9%)          II                    (100.0%)   (0.0%)   \n\n7    n_episodes        Mean (sd) : 18.7 (4)              22 distinct values                   :     614        0        \n     [numeric]         min < med < max:                                                       :     (100.0%)   (0.0%)   \n                       1 < 20 < 24                                                            :                         \n                       IQR (CV) : 2 (0.2)                                                     :                         \n                                                                                      . . . : : :                       \n\n8    season_fraction   Mean (sd) : 0.9 (0.2)             36 distinct values                     :   614        0        \n     [numeric]         min < med < max:                                                         :   (100.0%)   (0.0%)   \n                       0 < 1 < 1                                                                :                       \n                       IQR (CV) : 0 (0.2)                                                       :                       \n                                                                                                :                       \n------------------------------------------------------------------------------------------------------------------------\n```\n:::\n\n```{.r .cell-code}\ndfSummary(seasons_orig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Frame Summary  \nseasons_orig  \nDimensions: 46 x 5  \nDuplicates: 0  \n\n-------------------------------------------------------------------------------------------------------------------\nNo   Variable     Stats / Values                    Freqs (% of Valid)   Graph                 Valid      Missing  \n---- ------------ --------------------------------- -------------------- --------------------- ---------- ---------\n1    sid          Mean (sd) : 23.5 (13.4)           46 distinct values   : :   :   :   :   :   46         0        \n     [numeric]    min < med < max:                                       : : : : : : : : : :   (100.0%)   (0.0%)   \n                  1 < 23.5 < 46                                          : : : : : : : : : :                       \n                  IQR (CV) : 22.5 (0.6)                                  : : : : : : : : : :                       \n                                                                         : : : : : : : : : :                       \n\n2    year         Mean (sd) : 1997.5 (13.4)         46 distinct values   :                     46         0        \n     [numeric]    min < med < max:                                       : : : : : : : : :     (100.0%)   (0.0%)   \n                  1975 < 1997.5 < 2020                                   : : : : : : : : :                         \n                  IQR (CV) : 22.5 (0)                                    : : : : : : : : :                         \n                                                                         : : : : : : : : :                         \n\n3    first_epid   Mean (sd) : 19975965 (134209.3)   46 distinct values   : :   :   :   :   :   46         0        \n     [numeric]    min < med < max:                                       : : : : : : : : : :   (100.0%)   (0.0%)   \n                  19751011 < 19975927 < 20201003                         : : : : : : : : : :                       \n                  IQR (CV) : 224910.2 (0)                                : : : : : : : : : :                       \n                                                                         : : : : : : : : : :                       \n\n4    last_epid    Mean (sd) : 19985509 (134223.9)   46 distinct values   : :   :   :     : :   46         0        \n     [numeric]    min < med < max:                                       : : : : : : : : : :   (100.0%)   (0.0%)   \n                  19760731 < 19985512 < 20210410                         : : : : : : : : : :                       \n                  IQR (CV) : 225066.2 (0)                                : : : : : : : : : :                       \n                                                                         : : : : : : : : : :                       \n\n5    n_episodes   Mean (sd) : 19.7 (2.3)            12 :  1 ( 2.2%)                            46         0        \n     [numeric]    min < med < max:                  13 :  2 ( 4.3%)                            (100.0%)   (0.0%)   \n                  12 < 20 < 24                      17 :  2 ( 4.3%)                                                \n                  IQR (CV) : 1 (0.1)                18 :  2 ( 4.3%)                                                \n                                                    19 :  3 ( 6.5%)      I                                         \n                                                    20 : 23 (50.0%)      IIIIIIIIII                                \n                                                    21 :  7 (15.2%)      III                                       \n                                                    22 :  5 (10.9%)      II                                        \n                                                    24 :  1 ( 2.2%)                                                \n-------------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n### Briefly describe the data\n\nThese datasets consist of the actors, casts, and seasons of Saturday Night Live (SNL) from 1975 to 2020. There are 2,306 observations and 4 variables (`aid`, `url`, `type`, `gender`) in the actors dataset, 614 observations and 8 variables (`aid`, `sid`, `featured`, `first_epid`, `last_epid`, `update_anchor`, `n_episodes`, `season_fraction`) in the casts dataset, and 46 observations and 5 variables (`sid`, `year`, `first_epid`, `last_epid`, `n_episodes`) in the seasons dataset. Within 46 seasons, there are records of the date of each actor's (`aid`) first episode (`first_epid`) and last episode (`last_epid`) along with the date of the beginning (`first_epid`) and ending (`last_epid`) of each season. There is also `sid` which represents the season ID and `featured` which says whether the cast member was featured or not.\n\nThe mean number of episodes from the `n_episodes` variable is 19.7 per season and 18.7 per cast member. Out of all the cast members in the casts dataset, Kenan Thompson was involved in SNL the most often at 18 times with Darrell Hammond (14 times) and Seth Meyers (13 times) following after him.\n\n## Tidy Data (as needed)\n\nIs your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.\n\n::: callout-note\n## Note\n\nThese datasets are pretty tidy and organized well, so there's not much to do here.\n:::\n\nAre there any variables that require mutation to be usable in your analysis stream? For example, do you need to calculate new values in order to graph them? Can string values be represented numerically? Do you need to turn any variables into factors and reorder for ease of graphics and visualization?\n\nDocument your work here.\n\nThere are a few variables that require mutation: `type` and `gender` need to be converted into factors and `first_epid` and `last_epid` need to be converted to date format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# convert type and gender variables into factors\nactors <- actors_orig %>% \n  mutate(across(3:4, factor))\n# create a new data frame named casts\ncasts <- casts_orig\n# convert first_epid into date format\ncasts$first_epid <- ymd(casts$first_epid)\n# convert last_epid into date format\ncasts$last_epid <- ymd(casts$last_epid)\n# create a new data frame named seasons\nseasons <- seasons_orig\n# convert first_epid into date format\nseasons$first_epid <- ymd(seasons$first_epid)\n# convert last_epid into date format\nseasons$last_epid <- ymd(seasons$last_epid)\n```\n:::\n\n\n## Join Data\n\nBe sure to include a sanity check, and double-check that case count is correct!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# join actors and casts into one data frame\nac <- full_join(actors, casts, by = \"aid\")\n# create a jitter plot of gender vs. type with color based on whether the actor was featured or not\nggplot(ac, aes(`type`, `gender`)) +\n  geom_jitter(aes(color = `featured`)) +\n  labs(x = \"Group Actor Belongs To\",\n       y = \"Gender of Actor\",\n       title = \"Jitter Plot of Gender of Actor vs. Group Actor Belongs To\",\n       subtitle = \"The legend shows whether the actor was featured or not\",\n       caption = \"Data: snl_actors.csv & snl_casts.csv\")\n```\n\n::: {.cell-output-display}\n![](AleaciaMessiah_Challenge8_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nI decided to analyze the actors and casts datasets combined to compare the `type` of group the actor is in to the `gender` of the actor, with an aesthetic added to convey whether the actor was featured or not (`featured`). As illustrated by the jitter plot, the majority of featured actors are part of the cast, which is to be expected. However, there are a few that are part of the unknown group. Shown by the large concentration of points in the area, there is a large number of male, female, and unknown gender guests and more male cast members than female cast members. Although the crew is smaller than the number of cast members, most of the crew members are male like the cast. There is a `gender` factor called \"andy\" in this dataset which is hard to determine what it actually means. Although my first thought is that \"andy\" means non-binary or \"enby,\" looking through the guests that have this gender do not use non-binary pronouns or consider themselves non-binary. I would guess it either means androgynous or a placeholder for an unknown gender, but if it's the latter, why not use \"unknown\"? Overall, I found this combined dataset interesting, especially the larger concentrations of points in the guests column.   ",
    "supporting": [
      "AleaciaMessiah_Challenge8_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}