{
  "hash": "a8110712efa71359c262cbd4b0307629",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Aleacia Messiah\"\ndescription: \"Read, Clean, Describe, and Formulate Research Questions from Data\"\ndate: \"10/13/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Aleacia Messiah\n  - SIPRI_Milex\n  - tidyverse\n  - readxl\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Read in Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in the Current USD sheet of the Milex dataset, skipping the first 6 rows and renaming the columns\nmilex <- read_excel(\"_data/SIPRI-Milex-data-1949-2021.xlsx\", sheet = \"Current USD\", skip = 6, col_names = c(\"Country\", \"Notes\", 1949:2021))\n# view milex data\nmilex\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 191 × 75\n   Country  Notes `1949` `1950` `1951` `1952` `1953` `1954` `1955` `1956` `1957`\n   <chr>    <chr> <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr> \n 1 Africa   <NA>  <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  \n 2 North A… <NA>  <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  \n 3 Algeria  §4    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx   \n 4 Libya    ‡§¶16 xxx    xxx    ...    ...    ...    ...    ...    ...    ...   \n 5 Morocco  §17   xxx    xxx    xxx    xxx    xxx    xxx    xxx    23.71… 35.40…\n 6 Tunisia  <NA>  xxx    xxx    xxx    xxx    xxx    xxx    xxx    3.714… 6.411…\n 7 sub-Sah… <NA>  <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  \n 8 Angola   §‖1   xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx   \n 9 Benin    §     xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx   \n10 Botswana <NA>  xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx    xxx   \n# … with 181 more rows, and 64 more variables: `1958` <chr>, `1959` <chr>,\n#   `1960` <chr>, `1961` <chr>, `1962` <chr>, `1963` <chr>, `1964` <chr>,\n#   `1965` <chr>, `1966` <chr>, `1967` <chr>, `1968` <chr>, `1969` <chr>,\n#   `1970` <chr>, `1971` <chr>, `1972` <chr>, `1973` <chr>, `1974` <chr>,\n#   `1975` <chr>, `1976` <chr>, `1977` <chr>, `1978` <chr>, `1979` <chr>,\n#   `1980` <chr>, `1981` <chr>, `1982` <chr>, `1983` <chr>, `1984` <chr>,\n#   `1985` <chr>, `1986` <chr>, `1987` <chr>, `1988` <chr>, `1989` <chr>, …\n```\n:::\n:::\n\n\n## Clean Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmilex_clean <- milex %>% \n  # remove Notes column\n  select(!contains(\"Notes\")) %>% \n  # create a column with region names\n  mutate(Region = case_when(\n    str_ends(Country, \"Africa\") ~ \"Africa\",\n      str_detect(Country, \"America\") ~ \"Americas\",\n      str_detect(Country, \"Asia & Oceania\") ~ \"Asia & Oceania\",\n      str_ends(Country, \"Europe\") ~ \"Europe\",\n      str_ends(Country, \"East\") ~ \"Middle East\",\n    TRUE ~ NA_character_\n  )) %>% \n  # replace NAs in Region column\n  fill(Region, .direction = \"down\") %>% \n  # create a column with sub region names\n  mutate(Sub_Region = case_when(\n    str_detect(Country, \"North Africa\") ~ \"North Africa\",\n    str_detect(Country, \"sub-Saharan Africa\") ~ \"sub-Saharan Africa\",\n    str_detect(Country, \"Central America and the Caribbean\") ~ \"Central America and the Caribbean\",\n    str_detect(Country, \"North America\") ~ \"North America\",\n    str_detect(Country, \"South America\") ~ \"South America\",\n    str_detect(Country, \"Oceania\") ~ \"Oceania\",\n    str_detect(Country, \"South Asia\") ~ \"South Asia\",\n    str_detect(Country, \"East Asia\") ~ \"East Asia\",\n    str_detect(Country, \"South East Asia\") ~ \"South East Asia\",\n    str_detect(Country, \"Central Asia\") ~ \"Central Asia\",\n    str_detect(Country, \"Central Europe\") ~ \"Central Europe\",\n    str_detect(Country, \"Eastern Europe\") ~ \"Eastern Europe\",\n    str_detect(Country, \"Western Europe\") ~ \"Western Europe\",\n    str_ends(Country, \"East\") ~ \"Middle East\",\n    TRUE ~ NA_character_\n  )) %>% \n  # replace NAs in Sub Region column\n  fill(Sub_Region, .direction = \"down\") %>% \n  # remove rows with region and sub-region names\n  slice(-c(1:2, 7, 55:56, 70, 73, 85:86, 91, 98, 105, 117, 123:124, 145, 154, 175)) %>% \n  # replace \"xxx\" and \"...\" with NAs\n  na_if(\"xxx\") %>%\n  na_if(\"...\") %>% \n  # combine Region and Sub Region into one column\n  unite(Region:Sub_Region, col = \"Region & Sub Region\", sep = \"/\" ) %>% \n  # combine year columns into one column\n  pivot_longer('1949':'2021', names_to = \"Year\", values_to = \"Military Expenditure in Millions of US$\")\n# view cleaned dataset\nmilex_clean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12,629 × 4\n   Country `Region & Sub Region` Year  `Military Expenditure in Millions of US$`\n   <chr>   <chr>                 <chr> <chr>                                    \n 1 Algeria Africa/North Africa   1949  <NA>                                     \n 2 Algeria Africa/North Africa   1950  <NA>                                     \n 3 Algeria Africa/North Africa   1951  <NA>                                     \n 4 Algeria Africa/North Africa   1952  <NA>                                     \n 5 Algeria Africa/North Africa   1953  <NA>                                     \n 6 Algeria Africa/North Africa   1954  <NA>                                     \n 7 Algeria Africa/North Africa   1955  <NA>                                     \n 8 Algeria Africa/North Africa   1956  <NA>                                     \n 9 Algeria Africa/North Africa   1957  <NA>                                     \n10 Algeria Africa/North Africa   1958  <NA>                                     \n# … with 12,619 more rows\n```\n:::\n\n```{.r .cell-code}\n# number of distinct countries\nn_distinct(milex_clean$Country)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 173\n```\n:::\n\n```{.r .cell-code}\n# list distinct countries\ndistinct(milex_clean[,1])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 173 × 1\n   Country     \n   <chr>       \n 1 Algeria     \n 2 Libya       \n 3 Morocco     \n 4 Tunisia     \n 5 Angola      \n 6 Benin       \n 7 Botswana    \n 8 Burkina Faso\n 9 Burundi     \n10 Cameroon    \n# … with 163 more rows\n```\n:::\n\n```{.r .cell-code}\n# list distinct region and sub-region combinations\ndistinct(milex_clean[,2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 13 × 1\n   `Region & Sub Region`                     \n   <chr>                                     \n 1 Africa/North Africa                       \n 2 Africa/sub-Saharan Africa                 \n 3 Americas/Central America and the Caribbean\n 4 Americas/North America                    \n 5 Americas/South America                    \n 6 Asia & Oceania/Oceania                    \n 7 Asia & Oceania/South Asia                 \n 8 Asia & Oceania/East Asia                  \n 9 Asia & Oceania/Central Asia               \n10 Europe/Central Europe                     \n11 Europe/Eastern Europe                     \n12 Europe/Western Europe                     \n13 Middle East/Middle East                   \n```\n:::\n\n```{.r .cell-code}\n# number of years\nn_distinct(milex_clean$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 73\n```\n:::\n\n```{.r .cell-code}\n# range of years\nrange(milex_clean$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"1949\" \"2021\"\n```\n:::\n:::\n\n\n## Narrative\n\nThe Current USD data from the SIPRI Milex dataset details the military expenditures in millions of US dollars for 173 countries for the period 1949-2021. There are 191 observations (173 actual observations) and 75 variables (`Country`, `Notes`, and Years `1949` through `2021`). Observations (countries) were grouped by region and sub-region. There are 5 regions (Africa, Americas, Asia & Oceania, Europe, and Middle East) and 14 sub-regions (North Africa, Sub-Saharan Africa, Central America and the Caribbean, North America, South America, Oceania, South Asia, East Asia, South East Asia, Central Asia, Central Europe, Eastern Europe, Western Europe, and Middle East). Some of the data is missing for several countries in various years due to the data not being available or the country did not exist or was not independent at the time the data was collected, so those values are replaced with NAs.\n\nAfter cleaning the data, the new dataset has 12,629 observations and 4 variables (`Country`, `Region & Sub Region`, `Year`, `Military Expenditure in Millions of US$`). The regions and sub-regions were extracted from the `Country` column and combined together into one column to illustrate the various combinations of region and sub-region. The years were also condensed into one column.\n\n## Potential Research Questions\n\nSince this data was taken over a large period of time, I can research whether using time series methods would be appropriate to visualize and analyze the trends in the data.\n\n**1. What trends are present in the data (e.g. are there certain patterns of military spending over the years)?**\n\n**2. What are the top spending countries for each year?**\n\n**3. What is the predicted amount of military expenditures in dollars for year 2022 for each country?**\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}