{
  "hash": "04099a0f18fa01953b8340e735cba4f8",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 \"\nauthor: \"Emma Narkewicz\"\ndescription: \"Emma Narkewicz completes Challenge 1\"\ndate: \"09/18/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - railroads\n  - emma_narkewicz\n  \neditor: \n  markdown: \n    wrap: 72\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information\n    (e.g., tables, etc)\n\n## Read in the Data\n\nI read in the railroad_2012_clean_county.csv⭐ Using the read_csv\nfunction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#First I installed the readr function\ninstall.packages(\"readr\")\n#Next I loaded the tidyverse library\nlibrary(tidyverse)\n#open data set\nTrains <- read_csv(\"_data/railroad_2012_clean_county.csv\")\nTrains\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   state county               total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# … with 2,920 more rows\n```\n:::\n:::\n\n\n## Describe the data\n\nI chose to analyze the railroad_2012_clean_county.csv data set as a\nbeginner. There are 3 columns in this data set and 2930 rows. The\ncolumns values are \"state\", \"county\" and \"total_employees\". The state\ncolumn provides the 2 letter abbreviation for the state in which the\nrailroad data was collected from in 2012.\n\nThere were 53 \"states\" included in this data set, which was 50 states,\nas well as the District of Columbia, the Armed Forces, and the Armed\nForces Pacific. The county column refers to every county in the state\nthat railroad data was collected from, with data from 2930 counties\nincluded in the data set. The total_employees column refers to the total\nnumber of railroad employees in said county in the year 2012. Data was\nonly collected in the year 2012, meaning that this data set does not\nshow trends over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Determining min, max, median, and mean number of total employees\n\nsummarise(Trains, min = min(total_employees), max = max(total_employees), median = median(total_employees), mean = mean(total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n    min   max median  mean\n  <dbl> <dbl>  <dbl> <dbl>\n1     1  8207     21  87.2\n```\n:::\n:::\n\n\nThere was a wide range of total county railroad employees in counties in\n2012, with a minimum of 1 employee and a maximum of 8207 employees. The\nmedian number of employees was 21 and the mean number of employees was\n\\~87. A few counties with high totals employees in some counties skewed\nthe mean higher than the median.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating a boxplot of total county railroad employees\nggplot(Trains, aes(state,total_employees)) + geom_boxplot() + theme_minimal() + labs(title = \"Total County Railroad Employees in 2012\")\n```\n\n::: {.cell-output-display}\n![](Challenge1_EmmaNarkewicz_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Finding IQR of total employees\nsummarise(Trains, IQR= IQR(total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n    IQR\n  <dbl>\n1    58\n```\n:::\n\n```{.r .cell-code}\n#removing outlier from Trains\nOutlier_free_trains <- Trains %>%\n  filter(total_employees<8200) %>%\n  arrange(total_employees)\n\nOutlier_free_trains\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,929 × 3\n   state county   total_employees\n   <chr> <chr>              <dbl>\n 1 AK    SITKA                  1\n 2 AL    BARBOUR                1\n 3 AL    HENRY                  1\n 4 AP    APO                    1\n 5 AR    NEWTON                 1\n 6 CA    MONO                   1\n 7 CO    BENT                   1\n 8 CO    CHEYENNE               1\n 9 CO    COSTILLA               1\n10 CO    DOLORES                1\n# … with 2,919 more rows\n```\n:::\n\n```{.r .cell-code}\n#Calculating summary statistics with outlier removed\nsummarise(Outlier_free_trains, outlier_free_min = min(total_employees), outlier_free_max = max(total_employees), outlier_free_median = median(total_employees), outlier_free_mean = mean(total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  outlier_free_min outlier_free_max outlier_free_median outlier_free_mean\n             <dbl>            <dbl>               <dbl>             <dbl>\n1                1             4235                  21              84.4\n```\n:::\n:::\n\n\nLooking at the above box-plot, the maximum of 8027 total employees looks\nlike a visual outlier. To confirm, I calculated the IQR was 58\nemployees. From running summary statistics, I know that Q1 is 7\nemployees and Q3 is 65 employees. Using the rule that Q3 + 1.5(IQR) is\nthe threshold for upper outliers, which equals 152 employees, the\nmaximum value of 8,207 employees meets the criteria for outlier.\nHowever, removing this point from the data would not change the median\nfrom 21 employees and would only decrease the mean total employees\nslightly from \\~87 to \\~84.4 employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Identifying 10 counties with most total employees\nTrains %>%\n  arrange(desc(total_employees)) %>%\n  slice(1:10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n   state county           total_employees\n   <chr> <chr>                      <dbl>\n 1 IL    COOK                        8207\n 2 TX    TARRANT                     4235\n 3 NE    DOUGLAS                     3797\n 4 NY    SUFFOLK                     3685\n 5 VA    INDEPENDENT CITY            3249\n 6 FL    DUVAL                       3073\n 7 CA    SAN BERNARDINO              2888\n 8 CA    LOS ANGELES                 2545\n 9 TX    HARRIS                      2535\n10 NE    LINCOLN                     2289\n```\n:::\n:::\n\n\nAfter seeing visually from the box plot that most counties had lower\nnumbers of total employees, I used the arrange() and slice() functions\nto identify the counties with the top 10 total railroad employees in\n2012. These counties were in the states of IL,TX,NE,NY,VA,FL, and CA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Recode `total_employees` using case_when, numerical > categorical\nTrains <- Trains %>%\n  mutate(Number_employees = case_when(\n    total_employees>= 5000 ~ \"5000+ employees\",\n    total_employees>= 2500 & total_employees<5000 ~ \"2500-4999 employees\",\n    total_employees>= 1000 & total_employees<2500 ~ \"1000-2499 employees\",\n    total_employees>= 500 & total_employees<1000 ~ \"500-999 employees\",\n    total_employees>= 100 & total_employees<500 ~ \"100-499 employees\",\n    total_employees <100 ~ \"0-99 employees\")\n  )\n\n#Create table with the recoded values\ntable(select(Trains, Number_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber_employees\n     0-99 employees   100-499 employees 1000-2499 employees 2500-4999 employees \n               2396                 442                  18                   8 \n  500-999 employees     5000+ employees \n                 65                   1 \n```\n:::\n\n```{.r .cell-code}\n#Create prop.table with recoded values\nprop.table(table(select(Trains, Number_employees)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber_employees\n     0-99 employees   100-499 employees 1000-2499 employees 2500-4999 employees \n       0.8177474403        0.1508532423        0.0061433447        0.0027303754 \n  500-999 employees     5000+ employees \n       0.0221843003        0.0003412969 \n```\n:::\n:::\n\n\nLastly, I re-coded the numerical total_employees to the categorical\nnumber_employees mutate() and case_when() and created a table and\nprop.table with these new categorical values. Just as the box_plot\nsuggested, the majority of counties in the data set had fewer than 100\nrailroad employees in 2012, nearly 82%. Additionally over 95% of\ncounties had less than 500 total employees, and only 9 counties total\nhad more than 2500 total employees.\n",
    "supporting": [
      "Challenge1_EmmaNarkewicz_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}