<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Erika Nagai">
<meta name="dcterms.date" content="2022-10-12">
<meta name="description" content="Introduction to Visualization">

<title>DACSS 601: Data Science Fundamentals - FALL 2022 - Homework2 Erika Nagai</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta name="twitter:title" content="DACSS 601: Data Science Fundamentals - FALL 2022 - Homework2 Erika Nagai">
<meta name="twitter:description" content="Introduction to Visualization">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <img src="../images/UMass White Wordmark Horiz.png" alt="">
    <span class="navbar-title">DACSS 601: Data Science Fundamentals - FALL 2022</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page">Fall 2022 Posts</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">Contributors</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">DACSS</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/601_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 </a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Homework2 Erika Nagai</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Course information</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Syllabus.html" class="sidebar-item-text sidebar-link">Overview</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../instructional_team.html" class="sidebar-item-text sidebar-link">Instructional Team</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../course_schedule.html" class="sidebar-item-text sidebar-link">Course Schedule</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Weekly materials</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Fall 2022 posts</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://dacss.github.io/601_Fall_2022_final_posts/" class="sidebar-item-text sidebar-link">final posts</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#challenge-overview" id="toc-challenge-overview" class="nav-link active" data-scroll-target="#challenge-overview">Challenge Overview</a></li>
  <li><a href="#read-in-a-data" id="toc-read-in-a-data" class="nav-link" data-scroll-target="#read-in-a-data">Read in a data</a></li>
  <li><a href="#tidy-data" id="toc-tidy-data" class="nav-link" data-scroll-target="#tidy-data">Tidy data</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research questions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">Homework2 Erika Nagai</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw2</div>
    <div class="quarto-category">movie</div>
    <div class="quarto-category">gender</div>
  </div>
  </div>

<div>
  <div class="description">
    Introduction to Visualization
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Erika Nagai </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 12, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="challenge-overview" class="level2">
<h2 class="anchored" data-anchor-id="challenge-overview">Challenge Overview</h2>
<ul>
<li><p>Read in a dataset from the _data folder in the course blog repository, or choose your own data. If you decide to use one of the datasets we have provided, please use a challenging dataset - check with us if you are not sure.&nbsp;</p></li>
<li><p>Clean the data as needed using dplyr and related tidyverse packages.</p></li>
<li><p>Provide a narrative about the data set (look it up if you aren’t sure what you have got) and the variables in your dataset, including what type of data each variable is. The goal of this step is to communicate in a visually appealing way to non-experts - not to replicate r-code.</p></li>
<li><p>Identify potential research questions that your dataset can help answer.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   0.3.5 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.2.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'summarytools'

The following object is masked from 'package:tibble':

    view</code></pre>
</div>
</div>
</section>
<section id="read-in-a-data" class="level2">
<h2 class="anchored" data-anchor-id="read-in-a-data">Read in a data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>movie <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"_data/movies_metadata.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 45466 Columns: 24
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (14): belongs_to_collection, genres, homepage, imdb_id, original_langua...
dbl   (7): budget, id, popularity, revenue, runtime, vote_average, vote_count
lgl   (2): adult, video
date  (1): release_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>This movie dataset was generated by Movielens, a (non-profit) movie review website (https://movielens.org/), and was obtained from the following Kaggle link. (https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset?resource=download&amp;select=movies_metadata.csv)</p>
<p>The movie dataset is contains 45466 movies with a released date between December 9th 1874 and December 16th 2020.</p>
<p>The data includes the information of genres, revenue, runtime, languages, status (released/in production etc…).</p>
<p>This dataset includes the following columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(movie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "adult"                 "belongs_to_collection" "budget"               
 [4] "genres"                "homepage"              "id"                   
 [7] "imdb_id"               "original_language"     "original_title"       
[10] "overview"              "popularity"            "poster_path"          
[13] "production_companies"  "production_countries"  "release_date"         
[16] "revenue"               "runtime"               "spoken_languages"     
[19] "status"                "tagline"               "title"                
[22] "video"                 "vote_average"          "vote_count"           </code></pre>
</div>
</div>
<p>The data type of each column is as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(movie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [45,466 × 24] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ adult                : logi [1:45466] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ belongs_to_collection: chr [1:45466] "{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path"| __truncated__ NA "{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdro"| __truncated__ NA ...
 $ budget               : num [1:45466] 3.0e+07 6.5e+07 0.0 1.6e+07 0.0 6.0e+07 5.8e+07 0.0 3.5e+07 5.8e+07 ...
 $ genres               : chr [1:45466] "[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]" "[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]" "[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]" "[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]" ...
 $ homepage             : chr [1:45466] "http://toystory.disney.com/toy-story" NA NA NA ...
 $ id                   : num [1:45466] 862 8844 15602 31357 11862 ...
 $ imdb_id              : chr [1:45466] "tt0114709" "tt0113497" "tt0113228" "tt0114885" ...
 $ original_language    : chr [1:45466] "en" "en" "en" "en" ...
 $ original_title       : chr [1:45466] "Toy Story" "Jumanji" "Grumpier Old Men" "Waiting to Exhale" ...
 $ overview             : chr [1:45466] "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. "| __truncated__ "When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwi"| __truncated__ "A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanw"| __truncated__ "Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive \"good man\""| __truncated__ ...
 $ popularity           : num [1:45466] 21.95 17.02 11.71 3.86 8.39 ...
 $ poster_path          : chr [1:45466] "/rhIRbceoE9lR4veEXuwCC2wARtG.jpg" "/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg" "/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg" "/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg" ...
 $ production_companies : chr [1:45466] "[{'name': 'Pixar Animation Studios', 'id': 3}]" "[{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 2550}, {'name': 'Interscope Communicat"| __truncated__ "[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Lancaster Gate', 'id': 19464}]" "[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]" ...
 $ production_countries : chr [1:45466] "[{'iso_3166_1': 'US', 'name': 'United States of America'}]" "[{'iso_3166_1': 'US', 'name': 'United States of America'}]" "[{'iso_3166_1': 'US', 'name': 'United States of America'}]" "[{'iso_3166_1': 'US', 'name': 'United States of America'}]" ...
 $ release_date         : Date[1:45466], format: "1995-10-30" "1995-12-15" ...
 $ revenue              : num [1:45466] 3.74e+08 2.63e+08 0.00 8.15e+07 7.66e+07 ...
 $ runtime              : num [1:45466] 81 104 101 127 106 170 127 97 106 130 ...
 $ spoken_languages     : chr [1:45466] "[{'iso_639_1': 'en', 'name': 'English'}]" "[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'Français'}]" "[{'iso_639_1': 'en', 'name': 'English'}]" "[{'iso_639_1': 'en', 'name': 'English'}]" ...
 $ status               : chr [1:45466] "Released" "Released" "Released" "Released" ...
 $ tagline              : chr [1:45466] NA "Roll the dice and unleash the excitement!" "Still Yelling. Still Fighting. Still Ready for Love." "Friends are the people who let you be yourself... and never let you forget it." ...
 $ title                : chr [1:45466] "Toy Story" "Jumanji" "Grumpier Old Men" "Waiting to Exhale" ...
 $ video                : logi [1:45466] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ vote_average         : num [1:45466] 7.7 6.9 6.5 6.1 5.7 7.7 6.2 5.4 5.5 6.6 ...
 $ vote_count           : num [1:45466] 5415 2413 92 34 173 ...
 - attr(*, "spec")=
  .. cols(
  ..   adult = col_logical(),
  ..   belongs_to_collection = col_character(),
  ..   budget = col_double(),
  ..   genres = col_character(),
  ..   homepage = col_character(),
  ..   id = col_double(),
  ..   imdb_id = col_character(),
  ..   original_language = col_character(),
  ..   original_title = col_character(),
  ..   overview = col_character(),
  ..   popularity = col_double(),
  ..   poster_path = col_character(),
  ..   production_companies = col_character(),
  ..   production_countries = col_character(),
  ..   release_date = col_date(format = ""),
  ..   revenue = col_double(),
  ..   runtime = col_double(),
  ..   spoken_languages = col_character(),
  ..   status = col_character(),
  ..   tagline = col_character(),
  ..   title = col_character(),
  ..   video = col_logical(),
  ..   vote_average = col_double(),
  ..   vote_count = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>movieSummary <span class="ot">=</span> <span class="fu">dfSummary</span>(movie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tidy-data" class="level2">
<h2 class="anchored" data-anchor-id="tidy-data">Tidy data</h2>
<p>The values in some certain columns such as “belongs_to_collection”, “genres”, “production_companies”, “production_countries”, “spoken_languages” are in a list format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>movie <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"belongs_to_collection"</span>, <span class="st">"genres"</span>, <span class="st">"production_companies"</span>, <span class="st">"production_countries"</span>, <span class="st">"spoken_languages"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 45,466 × 5
   belongs_to_collection                          genres produ…¹ produ…² spoke…³
   &lt;chr&gt;                                          &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
 1 {'id': 10194, 'name': 'Toy Story Collection',… [{'id… [{'nam… [{'iso… [{'iso…
 2 &lt;NA&gt;                                           [{'id… [{'nam… [{'iso… [{'iso…
 3 {'id': 119050, 'name': 'Grumpy Old Men Collec… [{'id… [{'nam… [{'iso… [{'iso…
 4 &lt;NA&gt;                                           [{'id… [{'nam… [{'iso… [{'iso…
 5 {'id': 96871, 'name': 'Father of the Bride Co… [{'id… [{'nam… [{'iso… [{'iso…
 6 &lt;NA&gt;                                           [{'id… [{'nam… [{'iso… [{'iso…
 7 &lt;NA&gt;                                           [{'id… [{'nam… [{'iso… [{'iso…
 8 &lt;NA&gt;                                           [{'id… [{'nam… [{'iso… [{'iso…
 9 &lt;NA&gt;                                           [{'id… [{'nam… [{'iso… [{'iso…
10 {'id': 645, 'name': 'James Bond Collection', … [{'id… [{'nam… [{'iso… [{'iso…
# … with 45,456 more rows, and abbreviated variable names
#   ¹​production_companies, ²​production_countries, ³​spoken_languages</code></pre>
</div>
</div>
<ol type="1">
<li><p>Genre</p>
<p>First I need to delete “[” and “]”. I used a useful package that can remove brackets (round, square, curly or any shape), “qdapRegex”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(movie<span class="sc">$</span>genres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"                        
[2] "[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]"                       
[3] "[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]"                                                        
[4] "[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]"                           
[5] "[{'id': 35, 'name': 'Comedy'}]"                                                                                          
[6] "[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]"</code></pre>
</div>
</div></li>
<li><p><strong>Question</strong>: I had to use this package to remove the swuare brackets but I originally wanted to do so with str_extract or str_replace, but it didn’t work because “[ ]” have a special meaning in regex. I would appreciate it if you could show me how I could have done it by using str_ functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qdapRegex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'qdapRegex'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    explain</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    %+%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>clean_genres <span class="ot">&lt;-</span> <span class="fu">rm_square</span>(movie<span class="sc">$</span>genres, <span class="at">extract =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(movie<span class="sc">$</span>clean_genres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] "{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}"

[[2]]
[1] "{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}"

[[3]]
[1] "{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}"

[[4]]
[1] "{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}"

[[5]]
[1] "{'id': 35, 'name': 'Comedy'}"

[[6]]
[1] "{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}"</code></pre>
</div>
</div>
<p>I counted the number of “id” showed in the “genre” column to see how many genres each movie has.</p>
<p>The maximum number of genres is 8 and there are movies that do NOT have a genre assigned.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>num_genre <span class="ot">&lt;-</span> <span class="fu">str_count</span>(movie<span class="sc">$</span>genres, <span class="st">"id"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(movie<span class="sc">$</span>num_genre)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   1.000   2.000   2.004   3.000   8.000 </code></pre>
</div>
</div>
<p>Since a single column “genres” now contains multiple genres of information, let’s split the string so that each column contains only one genre of information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#str_split(movie$clean_genres, "\\},")</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>movie <span class="ot">&lt;-</span> movie <span class="sc">%&gt;%</span> </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(clean_genres, <span class="fu">c</span>(<span class="st">"genre1"</span>, <span class="st">"genre2"</span>, <span class="st">"genre3"</span>, <span class="st">"genre4"</span>, <span class="st">"genre5"</span>, <span class="st">"genre6"</span>, <span class="st">"genre7"</span>, <span class="st">"genre8"</span>), <span class="st">"</span><span class="sc">\\</span><span class="st">},"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expected 8 pieces. Missing pieces filled with `NA` in 45463 rows [1, 2,
3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].</code></pre>
</div>
</div>
<p>The values in the genre1 to genre8 columns still contain unnecessary {}, etc., so let’s clean them up!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#"\\{", "\\}",</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># I wanted to as follows but this misses some "{" "</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># movie$genre1 &lt;- str_replace(movie$genre1, c("\\{","\\}"), "")</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># remove {</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre1 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre1, <span class="st">"</span><span class="sc">\\</span><span class="st">{"</span>, <span class="st">""</span>)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre2 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre2, <span class="st">"</span><span class="sc">\\</span><span class="st">{"</span>, <span class="st">""</span>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre3 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre3, <span class="st">"</span><span class="sc">\\</span><span class="st">{"</span>, <span class="st">""</span>)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre4 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre4, <span class="st">"</span><span class="sc">\\</span><span class="st">{"</span>, <span class="st">""</span>)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre5 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre5, <span class="st">"</span><span class="sc">\\</span><span class="st">{"</span>, <span class="st">""</span>)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre6 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre6, <span class="st">"</span><span class="sc">\\</span><span class="st">{"</span>, <span class="st">""</span>)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre7 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre7, <span class="st">"</span><span class="sc">\\</span><span class="st">{"</span>, <span class="st">""</span>)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre8 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre8, <span class="st">"</span><span class="sc">\\</span><span class="st">{"</span>, <span class="st">""</span>)</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a><span class="co"># remove }</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre1 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre1, <span class="st">"</span><span class="sc">\\</span><span class="st">}"</span>, <span class="st">""</span>)</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre2 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre2, <span class="st">"</span><span class="sc">\\</span><span class="st">}"</span>, <span class="st">""</span>)</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre3 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre3, <span class="st">"</span><span class="sc">\\</span><span class="st">}"</span>, <span class="st">""</span>)</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre4 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre4, <span class="st">"</span><span class="sc">\\</span><span class="st">}"</span>, <span class="st">""</span>)</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre5 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre5, <span class="st">"</span><span class="sc">\\</span><span class="st">}"</span>, <span class="st">""</span>)</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre6 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre6, <span class="st">"</span><span class="sc">\\</span><span class="st">}"</span>, <span class="st">""</span>)</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre7 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre7, <span class="st">"</span><span class="sc">\\</span><span class="st">}"</span>, <span class="st">""</span>)</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre8 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre8, <span class="st">"</span><span class="sc">\\</span><span class="st">}"</span>, <span class="st">""</span>)</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a><span class="co"># remove "'id':"</span></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre1 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre1, <span class="st">"'id':"</span>, <span class="st">""</span>)</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre2 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre2, <span class="st">"'id':"</span>, <span class="st">""</span>)</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre3 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre3, <span class="st">"'id':"</span>, <span class="st">""</span>)</span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre4 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre4, <span class="st">"'id':"</span>, <span class="st">""</span>)</span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre5 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre5, <span class="st">"'id':"</span>, <span class="st">""</span>)</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre6 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre6, <span class="st">"'id':"</span>, <span class="st">""</span>)</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre7 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre7, <span class="st">"'id':"</span>, <span class="st">""</span>)</span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre8 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre8, <span class="st">"'id':"</span>, <span class="st">""</span>)</span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a><span class="co"># remove ", 'name':"</span></span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre1 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre1, <span class="st">", 'name': "</span>, <span class="st">""</span>)</span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre2 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre2, <span class="st">", 'name': "</span>, <span class="st">""</span>)</span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre3 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre3, <span class="st">", 'name': "</span>, <span class="st">""</span>)</span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre4 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre4, <span class="st">", 'name': "</span>, <span class="st">""</span>)</span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre5 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre5, <span class="st">", 'name': "</span>, <span class="st">""</span>)</span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre6 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre6, <span class="st">", 'name': "</span>, <span class="st">""</span>)</span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre7 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre7, <span class="st">", 'name': "</span>, <span class="st">""</span>)</span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a>movie<span class="sc">$</span>genre8 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(movie<span class="sc">$</span>genre8, <span class="st">", 'name': "</span>, <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next we will make the genre name columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_wider</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  movie,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">names_from =</span> genre1, <span class="at">values_from =</span> num_genre</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Values from `num_genre` are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = {summary_fun}` to summarise duplicates.
* Use the following dplyr code to identify duplicates.
  {data} %&gt;%
    dplyr::group_by(adult, belongs_to_collection, budget, genres, homepage, id, imdb_id, original_language, original_title, overview, popularity, poster_path, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, tagline, title, video, vote_average, vote_count, genre2, genre3, genre4, genre5, genre6, genre7, genre8, genre1) %&gt;%
    dplyr::summarise(n = dplyr::n(), .groups = "drop") %&gt;%
    dplyr::filter(n &gt; 1L)</code></pre>
</div>
<div class="cell-output cell-output-error">
<pre><code>Error in `values[spec$.name]`:
! Can't subset columns with `spec$.name`.
✖ Subscript `spec$.name` can't contain the empty string.
✖ It has an empty string at location 12.</code></pre>
</div>
</div></li>
</ol>
<p><strong>Question</strong>: I wanted to make genre options contained in genre 1 - 8 columns like the below image, but I haven’t figured out how… I tried to use the Pivot_wider feature, but it didn’t work the way I wanted it to.</p>
<p>Is there any function that I could use for this?</p>
<p><img src="images/paste-B3340D59.png" class="img-fluid"></p>
<p>After I figure out how to clean “genre” columns, I will do the same with the columns “belongs_to_collection”, “genres”, “production_companies”, “production_countries”, “spoken_languages”.</p>
<p>Then, I would love to join the bechdel test dataset (The movie has to have at least 2 [named] female characters, who talk to each other, about something other than a man) by using imdb_id.</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research questions</h2>
<ul>
<li><p>How does female representation in the movie affects its popularity and profitability (≒ revenue)?</p></li>
<li><p>How has changed the degree of female representation in the movies worldwide?</p></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/601_Fall_2022" data-repo-id="R_kgDOH564Gw" data-category="Announcements" data-category-id="DIC_kwDOH564G84CRdBB" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<pre class="markdown" data-shortcodes="false"><code>---
title: "Homework2 Erika Nagai"
author: "Erika Nagai"
description: "Introduction to Visualization"
date: "10/12/2022"
format:
  html:
    toc: true
    code-copy: true
    code-tools: true
categories:
  - hw2
  - movie
  - gender
---

## Challenge Overview

-   Read in a dataset from the \_data folder in the course blog repository, or choose your own data. If you decide to use one of the datasets we have provided, please use a challenging dataset - check with us if you are not sure.&nbsp;

-   Clean the data as needed using dplyr and related tidyverse packages.

-   Provide a narrative about the data set (look it up if you aren't sure what you have got) and the variables in your dataset, including what type of data each variable is. The goal of this step is to communicate in a visually appealing way to non-experts - not to replicate r-code.

-   Identify potential research questions that your dataset can help answer.

quarto-executable-code-5450563D

```r
# install libraries

library(tidyverse)
library(ggplot2)
library(stringr)
library(tidyr)
library(dplyr)
library(summarytools)
```

## Read in a data

quarto-executable-code-5450563D

```r
movie = read_csv("_data/movies_metadata.csv")
```

This movie dataset was generated by Movielens, a (non-profit) movie review website (https://movielens.org/), and was obtained from the following Kaggle link. (https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset?resource=download&amp;select=movies_metadata.csv)

The movie dataset is contains 45466 movies with a released date between December 9th 1874 and December 16th 2020.

The data includes the information of genres, revenue, runtime, languages, status (released/in production etc...).

This dataset includes the following columns.

quarto-executable-code-5450563D

```r
colnames(movie)
```

The data type of each column is as follows.

quarto-executable-code-5450563D

```r
str(movie)
```

quarto-executable-code-5450563D

```r
movieSummary = dfSummary(movie)
```

## Tidy data

The values in some certain columns such as "belongs_to_collection", "genres", "production_companies", "production_countries", "spoken_languages" are in a list format.

quarto-executable-code-5450563D

```r
movie %&gt;% select(c("belongs_to_collection", "genres", "production_companies", "production_countries", "spoken_languages"))
```

1.  Genre

    First I need to delete "\[" and "\]". I used a useful package that can remove brackets (round, square, curly or any shape), "qdapRegex".

    ```{r}
    head(movie$genres)
    ```

2.  **Question**: I had to use this package to remove the swuare brackets but I originally wanted to do so with str_extract or str_replace, but it didn't work because "\[ \]" have a special meaning in regex. I would appreciate it if you could show me how I could have done it by using str\_ functions.

    ```{r}

    library(qdapRegex)
    movie$clean_genres &lt;- rm_square(movie$genres, extract = TRUE)

    head(movie$clean_genres)
    ```

    I counted the number of "id" showed in the "genre" column to see how many genres each movie has.

    The maximum number of genres is 8 and there are movies that do NOT have a genre assigned.

    ```{r}
    movie$num_genre &lt;- str_count(movie$genres, "id")
    summary(movie$num_genre)
    ```

    Since a single column "genres" now contains multiple genres of information, let's split the string so that each column contains only one genre of information.

    ```{r}
    #str_split(movie$clean_genres, "\\},")

    movie &lt;- movie %&gt;% 
      separate(clean_genres, c("genre1", "genre2", "genre3", "genre4", "genre5", "genre6", "genre7", "genre8"), "\\},")
    ```

    The values in the genre1 to genre8 columns still contain unnecessary {}, etc., so let's clean them up!

    ```{r}
    #"\\{", "\\}",


    # I wanted to as follows but this misses some "{" "
    # movie$genre1 &lt;- str_replace(movie$genre1, c("\\{","\\}"), "")

    # remove {





    movie$genre1 &lt;- str_replace(movie$genre1, "\\{", "")
    movie$genre2 &lt;- str_replace(movie$genre2, "\\{", "")
    movie$genre3 &lt;- str_replace(movie$genre3, "\\{", "")
    movie$genre4 &lt;- str_replace(movie$genre4, "\\{", "")
    movie$genre5 &lt;- str_replace(movie$genre5, "\\{", "")
    movie$genre6 &lt;- str_replace(movie$genre6, "\\{", "")
    movie$genre7 &lt;- str_replace(movie$genre7, "\\{", "")
    movie$genre8 &lt;- str_replace(movie$genre8, "\\{", "")


    # remove }
    movie$genre1 &lt;- str_replace(movie$genre1, "\\}", "")
    movie$genre2 &lt;- str_replace(movie$genre2, "\\}", "")
    movie$genre3 &lt;- str_replace(movie$genre3, "\\}", "")
    movie$genre4 &lt;- str_replace(movie$genre4, "\\}", "")
    movie$genre5 &lt;- str_replace(movie$genre5, "\\}", "")
    movie$genre6 &lt;- str_replace(movie$genre6, "\\}", "")
    movie$genre7 &lt;- str_replace(movie$genre7, "\\}", "")
    movie$genre8 &lt;- str_replace(movie$genre8, "\\}", "")


    # remove "'id':"
    movie$genre1 &lt;- str_replace(movie$genre1, "'id':", "")
    movie$genre2 &lt;- str_replace(movie$genre2, "'id':", "")
    movie$genre3 &lt;- str_replace(movie$genre3, "'id':", "")
    movie$genre4 &lt;- str_replace(movie$genre4, "'id':", "")
    movie$genre5 &lt;- str_replace(movie$genre5, "'id':", "")
    movie$genre6 &lt;- str_replace(movie$genre6, "'id':", "")
    movie$genre7 &lt;- str_replace(movie$genre7, "'id':", "")
    movie$genre8 &lt;- str_replace(movie$genre8, "'id':", "")

    # remove ", 'name':"
    movie$genre1 &lt;- str_replace(movie$genre1, ", 'name': ", "")
    movie$genre2 &lt;- str_replace(movie$genre2, ", 'name': ", "")
    movie$genre3 &lt;- str_replace(movie$genre3, ", 'name': ", "")
    movie$genre4 &lt;- str_replace(movie$genre4, ", 'name': ", "")
    movie$genre5 &lt;- str_replace(movie$genre5, ", 'name': ", "")
    movie$genre6 &lt;- str_replace(movie$genre6, ", 'name': ", "")
    movie$genre7 &lt;- str_replace(movie$genre7, ", 'name': ", "")
    movie$genre8 &lt;- str_replace(movie$genre8, ", 'name': ", "")


    ```

    Next we will make the genre name columns.

    ```{r}

    pivot_wider(
      movie,
      names_from = genre1, values_from = num_genre
    )
    ```

**Question**: I wanted to make genre options contained in genre 1 - 8 columns like the below image, but I haven't figured out how... I tried to use the Pivot_wider feature, but it didn't work the way I wanted it to.

Is there any function that I could use for this?

![](images/paste-B3340D59.png)

After I figure out how to clean "genre" columns, I will do the same with the columns "belongs_to_collection", "genres", "production_companies", "production_countries", "spoken_languages".

Then, I would love to join the bechdel test dataset (The movie has to have at least 2 \[named\] female characters, who talk to each other, about something other than a man) by using imdb_id.

## Research questions

-   How does female representation in the movie affects its popularity and profitability (≒ revenue)?

-   How has changed the degree of female representation in the movies worldwide?</code></pre>
</div></div></div></div></div>
</div> <!-- /content -->



<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>