---
title: "Challenge1 Erika Nagai"
author: "Erika Nagai"
desription: "Reading in data and creating a post"
date: "09/13/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge_1
  - railroads
  - faostat
  - wildbirds
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Challenge Overview

Today's challenge is to


```{r}
# 1. Read in the data

bird_data <- read_csv('_data/birds.csv')
bird_data

```

## Describe the data

This "bird" data includes the some value related to birds livestock animals (number of chickens, ducks, goose?) of 248 countries/regions all over the world from 1961 to 2018. 

It is consisted of 30977 rows and 14 columns.

```{r}
#| label: summary
print(dim(bird_data))# count of columns and rows


n_country <- length(unique(bird_data$Area))
print(n_country)
```
This data includes 4 numeric data and the below table shows their basic statistics information
```{r}
summary(bird_data) # View the basic statistics information of each variables
```

```

