{
  "hash": "af6a94b27227fb43c0650dfc144f82fc",
  "result": {
    "markdown": "---\ntitle: \"Homework-2\"\nauthor: \"Nikita Masanagi\"\ndate: \"10/20/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - hotel_bookings\n  \n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.5.0 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(psych)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'psych'\n\nThe following objects are masked from 'package:ggplot2':\n\n    %+%, alpha\n```\n:::\n\n```{.r .cell-code}\nlibrary(summarytools)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'summarytools'\n\nThe following object is masked from 'package:tibble':\n\n    view\n```\n:::\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n\n## Read Data\n\nThe dataset I have chosen is the Hotel Bookings dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings <- read.csv(\"_data/hotel_bookings.csv\")\n```\n:::\n\n\n\n## Describe Data\n\nWe can use summary tools to view the different components of the data better.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         hotel is_canceled lead_time arrival_date_year arrival_date_month\n1 Resort Hotel           0       342              2015               July\n2 Resort Hotel           0       737              2015               July\n3 Resort Hotel           0         7              2015               July\n4 Resort Hotel           0        13              2015               July\n5 Resort Hotel           0        14              2015               July\n6 Resort Hotel           0        14              2015               July\n  arrival_date_week_number arrival_date_day_of_month stays_in_weekend_nights\n1                       27                         1                       0\n2                       27                         1                       0\n3                       27                         1                       0\n4                       27                         1                       0\n5                       27                         1                       0\n6                       27                         1                       0\n  stays_in_week_nights adults children babies meal country market_segment\n1                    0      2        0      0   BB     PRT         Direct\n2                    0      2        0      0   BB     PRT         Direct\n3                    1      1        0      0   BB     GBR         Direct\n4                    1      1        0      0   BB     GBR      Corporate\n5                    2      2        0      0   BB     GBR      Online TA\n6                    2      2        0      0   BB     GBR      Online TA\n  distribution_channel is_repeated_guest previous_cancellations\n1               Direct                 0                      0\n2               Direct                 0                      0\n3               Direct                 0                      0\n4            Corporate                 0                      0\n5                TA/TO                 0                      0\n6                TA/TO                 0                      0\n  previous_bookings_not_canceled reserved_room_type assigned_room_type\n1                              0                  C                  C\n2                              0                  C                  C\n3                              0                  A                  C\n4                              0                  A                  A\n5                              0                  A                  A\n6                              0                  A                  A\n  booking_changes deposit_type agent company days_in_waiting_list customer_type\n1               3   No Deposit  NULL    NULL                    0     Transient\n2               4   No Deposit  NULL    NULL                    0     Transient\n3               0   No Deposit  NULL    NULL                    0     Transient\n4               0   No Deposit   304    NULL                    0     Transient\n5               0   No Deposit   240    NULL                    0     Transient\n6               0   No Deposit   240    NULL                    0     Transient\n  adr required_car_parking_spaces total_of_special_requests reservation_status\n1   0                           0                         0          Check-Out\n2   0                           0                         0          Check-Out\n3  75                           0                         0          Check-Out\n4  75                           0                         0          Check-Out\n5  98                           0                         1          Check-Out\n6  98                           0                         1          Check-Out\n  reservation_status_date\n1              2015-07-01\n2              2015-07-01\n3              2015-07-02\n4              2015-07-02\n5              2015-07-03\n6              2015-07-03\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            hotel is_canceled lead_time arrival_date_year arrival_date_month\n119385 City Hotel           0        21              2017             August\n119386 City Hotel           0        23              2017             August\n119387 City Hotel           0       102              2017             August\n119388 City Hotel           0        34              2017             August\n119389 City Hotel           0       109              2017             August\n119390 City Hotel           0       205              2017             August\n       arrival_date_week_number arrival_date_day_of_month\n119385                       35                        30\n119386                       35                        30\n119387                       35                        31\n119388                       35                        31\n119389                       35                        31\n119390                       35                        29\n       stays_in_weekend_nights stays_in_week_nights adults children babies meal\n119385                       2                    5      2        0      0   BB\n119386                       2                    5      2        0      0   BB\n119387                       2                    5      3        0      0   BB\n119388                       2                    5      2        0      0   BB\n119389                       2                    5      2        0      0   BB\n119390                       2                    7      2        0      0   HB\n       country market_segment distribution_channel is_repeated_guest\n119385     BEL  Offline TA/TO                TA/TO                 0\n119386     BEL  Offline TA/TO                TA/TO                 0\n119387     FRA      Online TA                TA/TO                 0\n119388     DEU      Online TA                TA/TO                 0\n119389     GBR      Online TA                TA/TO                 0\n119390     DEU      Online TA                TA/TO                 0\n       previous_cancellations previous_bookings_not_canceled reserved_room_type\n119385                      0                              0                  A\n119386                      0                              0                  A\n119387                      0                              0                  E\n119388                      0                              0                  D\n119389                      0                              0                  A\n119390                      0                              0                  A\n       assigned_room_type booking_changes deposit_type agent company\n119385                  A               0   No Deposit   394    NULL\n119386                  A               0   No Deposit   394    NULL\n119387                  E               0   No Deposit     9    NULL\n119388                  D               0   No Deposit     9    NULL\n119389                  A               0   No Deposit    89    NULL\n119390                  A               0   No Deposit     9    NULL\n       days_in_waiting_list customer_type    adr required_car_parking_spaces\n119385                    0     Transient  96.14                           0\n119386                    0     Transient  96.14                           0\n119387                    0     Transient 225.43                           0\n119388                    0     Transient 157.71                           0\n119389                    0     Transient 104.40                           0\n119390                    0     Transient 151.20                           0\n       total_of_special_requests reservation_status reservation_status_date\n119385                         2          Check-Out              2017-09-06\n119386                         0          Check-Out              2017-09-06\n119387                         2          Check-Out              2017-09-07\n119388                         4          Check-Out              2017-09-07\n119389                         0          Check-Out              2017-09-07\n119390                         2          Check-Out              2017-09-07\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 119390     32\n```\n:::\n:::\n\nIn this dataset there are 32 variables(columns) and 119,390 observations(rows).By looking at the variable names, we can say that the it consists of reservation data of some hotels. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(hotel.bookings)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"hotel\"                          \"is_canceled\"                   \n [3] \"lead_time\"                      \"arrival_date_year\"             \n [5] \"arrival_date_month\"             \"arrival_date_week_number\"      \n [7] \"arrival_date_day_of_month\"      \"stays_in_weekend_nights\"       \n [9] \"stays_in_week_nights\"           \"adults\"                        \n[11] \"children\"                       \"babies\"                        \n[13] \"meal\"                           \"country\"                       \n[15] \"market_segment\"                 \"distribution_channel\"          \n[17] \"is_repeated_guest\"              \"previous_cancellations\"        \n[19] \"previous_bookings_not_canceled\" \"reserved_room_type\"            \n[21] \"assigned_room_type\"             \"booking_changes\"               \n[23] \"deposit_type\"                   \"agent\"                         \n[25] \"company\"                        \"days_in_waiting_list\"          \n[27] \"customer_type\"                  \"adr\"                           \n[29] \"required_car_parking_spaces\"    \"total_of_special_requests\"     \n[31] \"reservation_status\"             \"reservation_status_date\"       \n```\n:::\n:::\n\nWe can change the column name of column 28 from adr to average_daily_rate to make it more readable.\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(hotel.bookings)[28] <- \"average_daily_rate\"\n```\n:::\n\n\nWe can see the distinct datatypes for each column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(hotel.bookings, function(x) n_distinct(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         hotel                    is_canceled \n                             2                              2 \n                     lead_time              arrival_date_year \n                           479                              3 \n            arrival_date_month       arrival_date_week_number \n                            12                             53 \n     arrival_date_day_of_month        stays_in_weekend_nights \n                            31                             17 \n          stays_in_week_nights                         adults \n                            35                             14 \n                      children                         babies \n                             6                              5 \n                          meal                        country \n                             5                            178 \n                market_segment           distribution_channel \n                             8                              5 \n             is_repeated_guest         previous_cancellations \n                             2                             15 \nprevious_bookings_not_canceled             reserved_room_type \n                            73                             10 \n            assigned_room_type                booking_changes \n                            12                             21 \n                  deposit_type                          agent \n                             3                            334 \n                       company           days_in_waiting_list \n                           353                            128 \n                 customer_type             average_daily_rate \n                             4                           8879 \n   required_car_parking_spaces      total_of_special_requests \n                             5                              6 \n            reservation_status        reservation_status_date \n                             3                            926 \n```\n:::\n:::\n\n\n\n\nWe can observe the unique values, for some columns with repeated values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(hotel.bookings$hotel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Resort Hotel\" \"City Hotel\"  \n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$arrival_date_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2015 2016 2017\n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$reservation_status)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Check-Out\" \"Canceled\"  \"No-Show\"  \n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$distribution_channel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Direct\"    \"Corporate\" \"TA/TO\"     \"Undefined\" \"GDS\"      \n```\n:::\n\n```{.r .cell-code}\nunique(hotel.bookings$customer_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Transient\"       \"Contract\"        \"Transient-Party\" \"Group\"          \n```\n:::\n:::\n\n\n\nThere are two types of hotels in the dataset: Resort Hotel and City Hotel. Reservations are made in 2015, 2016 and 2017. The data covers reservations from 178 countries. So the data should belong to a big worldwide hotels chain. Both canceled and completed reservations are stored in the dataset as well as no-shows. Thus, each observation includes information about a reservation such as what type of hotel and in which country the reservation is for, number of visitors, dates, daily rates, stay durations and some categorical info about customer and the channel of reservation.\n\nWe do not need to pivot the data as each column repsresent a variable and each row is an observation. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings <- mutate(\n  hotel.bookings, \n  number_of_guests = adults + children + babies,\n  total_stay = stays_in_weekend_nights + stays_in_week_nights) # adding two new variables\n\nprint(dfSummary(hotel.bookings, \n                varnumbers= FALSE, \n                plain.ascii= FALSE, \n                style= \"grid\", \n                graph.magnif= 0.80, \n                valid.col= TRUE),\n      method= 'render', \n      table.classes= 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>hotel.bookings</h4>\n<strong>Dimensions</strong>: 119390 x 34\n  <br/><strong>Duplicates</strong>: 31994\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Valid</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">hotel\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. City Hotel</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Resort Hotel</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">79330</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">66.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">40060</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFwAAAAtCAQAAACJmMS3AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKDvq2mbBAAAAjElEQVRo3u3XQQqAIBRFUX+0x/ZQ66k9uMqaalCIpP4X986cyBm8IO0Mmk2jAcBVmtPD4Xzwqz3AQ1hG216K2Ul2KsCBA3cacODAnQYceGG339pYd8uALH07WPU1fUqtslORhWcb3z9/c27N1tf0zdnyU5edCnDgwJ0GHDhwpwEHXtg/3pxKyU4FeO8uwU0Ls83gVn4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDA6NTkrMDA6MDB7yt8DAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQwOjU5KzAwOjAwCpdnvwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">is_canceled\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.4</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">75166</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">63.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">44224</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">37.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFgAAAAtCAQAAACAc2TNAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKDvq2mbBAAAAiUlEQVRYw+3XwQ2AIBBEUdbYoz1oPdoDVeoVjF4ICzvJ/zcu5B3GROxOWi2zAYCjtZaHK+igd/sBp7TNtn2Uq5PcJAADBgwYMGDAoQLs3ev3MrfdMjAr/9mt+RrfSqPcJOTA1YZPtzfd0W1tQ950PT9luUkABgwYMGDAgEMF2DvtN51CcpMA7N0DGz4Ls/uQc8MAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDA6NTkrMDA6MDB7yt8DAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQwOjU5KzAwOjAwCpdnvwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">lead_time\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 104 (106.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 69 &le; 737</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 142 (1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">479 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKDvq2mbBAAABHElEQVR42u3c3Q2CMAAAYWu6ozvoPLCDU+pri6IhFPpzd29EE/mgFEjA8Lowu9ZeAeHCzymmC/PHAf8ItVewZCkv5h/dsqVn7TU9MOxQF05LOC3htITTEk5LOC3htITTEk5LOC3htITTEk5LOC3htITTEk5LOC3htITTEk5LOK34++Mpe5B7pIe4/8DTx7jHeogbO9SF0xJOSzgtLDxu+fJI13Gb4CNdx2GHunBam47xvGnx7nFfk90OeN9vHmOHunBawmlh4TtOZ8v6uoUpCO/rFqYgPK/1/X8YvPX9fxg8r73r+pPg7V3XY09nWPhJQ31Z/Tm/Ejyf82tMfZXg65vh24ZIK7VRQvob8+D/XHlPNloY3LoadlYXTusNq3gj0fs/rlkAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDA6NTkrMDA6MDB7yt8DAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQwOjU5KzAwOjAwCpdnvwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_year\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2016.2 (0.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2015 &le; 2016 &le; 2017</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2015</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">21996</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">18.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2016</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">56707</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">47.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2017</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">40687</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">34.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEYAAABACAQAAAANfskSAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKDvq2mbBAAAApElEQVRo3u3YwQmAMBBE0UTSo0VYj+nBKvW6EQxZ2ZA5/LmJoA93hdF8J51sqwFgRlLsQXUt0JEjAPaWpT21D1/kin4sSWxMYMCAAQMGDJhOXhViRjEYT7blJqQtOWPvLzUmKUyzM+eKjyizG787cEzaF0ZqTGDAgAEDBgyYTujANrIdeHLt9P2enVo7vRsoNSYwYMCAAQMGTCe6tXN1pMYE5isP1hoSG0pbBRQAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDA6NTkrMDA6MDB7yt8DAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQwOjU5KzAwOjAwCpdnvwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_month\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. August</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. July</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. May</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. October</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. April</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. June</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. September</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. March</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. February</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. November</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 2 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13877</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12661</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11791</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11160</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11089</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10939</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10508</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9794</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8068</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6794</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12709</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABsAAADXCAQAAABB9+IRAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKDvq2mbBAAAA3UlEQVRo3u3azQ3CMAxA4RixY3fA88AOnZJe0/w5ipoKk+cbqJ9EYvWdkG8YmceQupk94w+f5kFfUmEhbFW0+7sSGGwaS16cvZNJ/GZK89H4ySt+5LsaBZUGq0UhP7GLvcFg0xhRyL5xsTcYbBr7nyioNFk5CqXzutgbDDaNEYVsXOwNBpvGXESBlsBg97HFo6BisFIUypfkYt0wmD1EwboSogBbjC0cBZUOlkahfkEu1g2D2bNsFFS62DkKretxsW4YzJ5loxDPORCdf4RMr8rFumEwe66Iwq+ebZAd72FAHLwiDO4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDA6NTkrMDA6MDB7yt8DAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQwOjU5KzAwOjAwCpdnvwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_week_number\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 27.2 (13.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 28 &le; 53</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">53 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKDvq2mbBAAABKklEQVR42u2aUQ6CMBAFxXBH7qDnwTt4Sv2tcQ3Y0NLszPzBB+0km77thul1YXI9ewOKK96HuXyYTtvGGh4194M3VC4yV3/lYJavN8+m62FLXXEaitPofqqvg/TIJ8TZErxrG11Nxfu0IAOKxy3IKIXdVDyidz+2H+yprjgNrPgw19KIvZlQE5pDi0eZcFROWOr/MG5b0lh85MZkL9hSV5yG4jSw4ptxliGzq8QzZHYEttQVp6E4DcVpKE5j6GHjXqK2emvymkK8pqnGlrriNBSngRX/iLOsY6ZN8axjpghsqStOQ3EaitNQnIbiNLDiKYaNEeFNs5i8phXfumdiS11xGorTUJyG4jQUp6E4DcVpKE5DcRpTOZN7JP8V5FYMG6fkrj/BlrriNN6PhSNOGAl1MQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MDo1OSswMDowMHvK3wMAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDA6NTkrMDA6MDAKl2e/AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_day_of_month\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 15.8 (8.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 16 &le; 31</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 15 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">31 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABIklEQVR42u2c3Q2CMAAGqemO7qDz4A5OqW+mNaGW2oJyd08Q4CvXHyCEEh4Tk9PeJ6C44tsQ05WwceFzdoG5Di8+LS42p3RQnabza+nenNFWYRuLp6prZPtnVIv3qef6EkZ3/BUt3qOe98zP8ar+v7QNkbgcUR8yF597R4/WtiESSyEloXxbflx9Sh3fJ3wUL1VD/bbWPcdmrBDfk9ZWrh3xPyve2sa1x2FvZ4rTUJyG4jQUp6E4DcVpKE5DcRqK01CchuI0FKehOA3FaShOQ3EaitNQnIbiNBSnoTgNxWkoTgMr/rMf6vfhbZ5DMl/h4OLL8xWwXV1xGorTUJyG4jQUp6E4DcVpKE5DcRohfRt3O/ifKy/Jy8ZwcNdFsF1dcRpPMIAx1rGugHMAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDBJcP+KAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwOC1HNgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">stays_in_weekend_nights\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.9 (1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 1 &le; 19</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (1.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">17 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAA10lEQVR42u3cQQqDMBQAUSO5o3fQ89Q79JS6Un4WlhbaBv/MrJQg5EF0k2DZBmZj7wkIF/6farxZmxd+Kb0n9+0ir7ZD03n17D3LH4dd6sJpCaclnJZwWsJpCaclnJZwWsJpCaclnJZwWsJpCaclnJZwWsJpCaclnJZwWsJpCaeFhdfroUc43p3v7PoLeO6z69ilLpyWcFrCaQmnJZyWcFrCaQmnJZyWcFrCaQmnJZyWcFr10weybB6/CY/cY/v43pvHJf7cbU3+58o5rNCS3HoZ9uMmnNYOLGQRT4bncjsAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDBJcP+KAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwOC1HNgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">stays_in_week_nights\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.5 (1.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 50</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.8)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAA60lEQVR42u3cQQ6CMBQAUWt6R++A54E7eEpciOEbg2WhNvyZ2RiDi75QSUOalvnE7Nx7AMKF/6cav0zhD38tvYf2/eLzrL5euiyft95j/HnYqS6clnBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBawmkJpyWcVt26MC47XjNu5v0If2znzbuZFzvVhdMSTks4LeG0hNMSTks4LeG0hNPCwmvrB1nftjbhWd+2Yqe6cFrCaQmnJZwWFt5csj4b3844PPbqfTd8PfAsx+q9xBs5JT+5cghztCS3boZ9uAmndQcdCxO/sMpfxgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">adults\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1.9 (0.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 55</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (0.3)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">14 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAt0lEQVR42u3csQ3CMBBAUYKyI0MwD+zAlNAaSIMEWMr7r7Oc4r7ktLfcD6bj7AEKL/w/1vFw3fzhz8vsIb9lzFufr05vH99mT/sj7FMvXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK1xSuKVxTuKZwTeGawjWFawrXFK4pXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK17zsc9va3nbZzz7LYSXfsp+qz7BPvXDNA7SYCPUHQFToAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">children\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 10</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (3.8)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">110796</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">92.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">4861</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3652</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">76</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABmCAQAAACjWj3IAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAA8UlEQVR42u3aQQ6CMBQG4b/GO3IHPY/egVPCtlVxQaKEN/Pt2BCGtgteaEuYLkc/gOGG/8e1v3gWP/C3thGeTEc/2w/NwxV2qxtOYziN4TSG0xhOYzgNNvzls3Ted5cTav3soe2+zTn0rW71JHl0r+RefPk3Rk/1zzp2qxtOYziN4TSG0xhOYzgNNtzRU+LoCQEb/nHmVn3elryt+FT6h68v4RyG0xhOYziN4TSG0xhO4+gpcfSEYHgy/u5VnStOYziN4TSG0xhOYziN4TSG0zhzo3H0RGM4jeE0htMYTmM4jeE0htNgwxto9jDArrjhNCunORiizPJadQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119386\n(100.0%)</td>\n      <td align=\"center\">4\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">babies\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0 (0.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 10</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (12.3)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">118473</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">99.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">900</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">15</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAIMAAABmCAQAAABCHercAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABIElEQVR42u3YsU0DQRRF0WNEj/RAP6YHqoTkBcayEwJstPdmk6xmj2ZW2n/6Urw8egPPUQyIYb1eLj4O9aF4P91h4O3Re/uzPn+suhSIYcWAGFYMiGHFgBhWDIhhxYAYVgyIYV39aH/+7in/vtPlpOX068f8xy7fvEuBK4bz1/lQY7g7DMctBsSwYkAMKwbEsGJADCsGxLBiQAwrBsSwYkBDuNVpQAzrahb56O08BcNxiwExrBgQw4oBMawYEMOKATGsGBDDigExrIZw6DSsGNAQ7hbDcYsBMawYEMOKATGsGBDDigExrBgQw4oBMawY0CxydRrQEO4Ww3GLATGsGBDDigExrBgQw4oBMawYEMOKATGsGHA1hDtunQbEsGIA37EYFlRXrfVqAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">meal\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. BB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. FB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. HB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. SC</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">92310</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">77.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">798</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14463</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10650</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1169</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGkAAABmCAQAAABi3XdkAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAA+ElEQVR42u3aQQ6CMBQGYWq8o3fQ8+AdOCVuCwFDumnnZ2bHhvDFavKelHVK69H7ASTdk/SsL77YL9a7nJCm6dX72ZpaNleBB08SIUmEJBGSREgSIUmEAkm74WJpu8tQlXrqK8236V2tCDx4G9K8zthR/YSUkSRCkghJIiSJkCRCkghJIhRIclAnFEjaLL3+bx4+kHN5+SUBzoYv8OBJIiSJkCRCkghJIiSJkP+oj5qDOq0LgzplQD8kHQ3qvB+MwIMniZAkQpIISSIkiZAkQoEkdw+jdqfdg2/zD5okQpIISSIkiZAkQpIISSIUSCoBM9+uwE9JEqEfIjIcHh0Jcz8AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDBJcP+KAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwOC1HNgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">country\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. PRT</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. GBR</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. FRA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. ESP</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. DEU</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. ITA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. IRL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. BEL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. BRA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. NLD</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 168 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">48590</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">40.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12129</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10415</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8568</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">7.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7287</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3766</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3375</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2342</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2224</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2104</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">18590</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAD0AAADXCAQAAAADtJGGAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABTklEQVR42u3cQXKCQBBA0SGVO3qH5DzJHTylWaSsEEFEpJuZmtc7Nr6SZsq/UIdLOWreDpM7pd/HF9/hi/8Y7tClnELh87+rPneNRqPR6Hbpmw/N87ZX2TTDuA6GzS+zdsZaLTf8624gfQbckFWBFPME9Hm40Gg0Gt0uLZCSZ0UgRcTRhJ4LpLjt93m40Gg0Gt0uLZCS50EgRcXRhL4NpNjN93m40Gg0Gt0uLZCSZzGQIvNoMZCi997n4UKj0Wh0u7RASp5adv3XZrFVNkNf2yznYetz12g0Go1+cQRS8tSy62sgZeTR5F2fgn9Ct0BnDhqNRqPbpQVS8tSy699AysmjmUDKmz53jUaj0eh9aYEUPQKpCCQ0Go1Gt0YLpOgRSEUgodFoNLo1WiBFT12B9Gj2Cqin/8R7vwexz12j0Wg0+sWp5TtIudPnrg+kfwBb1z3BiU2kYwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">market_segment\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Aviation</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Complementary</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Corporate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Direct</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Groups</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Offline TA/TO</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Online TA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">237</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">743</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5295</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12606</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">19811</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">16.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">24219</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">20.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">56477</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">47.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEUAAACfCAQAAAAFIdzrAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABG0lEQVR42u3cPY6DMBRG0RCxxywi62ERWSVpYslGRhB+7FecO8UoFUfYkb5mZpgfUXr2BqBsNGc/U/OLkz890FtBQUFBQUFBQak25GtpaP74/OmB3kpBmeb2k3KF0jcUFBQUFBQUlGoGZa0x/5DPyXfzVzSWH1+/35/m7yTUAaGgoKCgoKAsR0KPcZAyKGsFoqxu27IWS3dl25a1ucyBDggFBQUFBaVXBmXKoNxq56BcdsfA3DUol91zuQMdEAoKCgoKSq8MypRBudXBQZm6clgeGpSpay95oANCQUFBQUHplUGZMii3OjkoT5fdiVOD8mzllyTQAaGgoKCgoPTKoEwZlH9Rev65edy3goKCgoKCgoKSGvyjUJSdfQEV/jVv2TYJJQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">distribution_channel\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Corporate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Direct</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. GDS</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. TA/TO</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6677</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14645</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">193</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">97870</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">82.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAG8AAABmCAQAAABvwwcjAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAA/ElEQVR42u3aQQrCMBgFYSO9o4fwPO0dPKXuNAlEVIQwL/OtlG46NFnkJ+V+Snae/QLmmTey1X+OZiNey+yX+00dsbWPLs9ft9lv+Rfhi9M8MvPIzCMzj8w8MvPIwvO6A1HGMeil1Ic/6Pm1UxettDj3t1NB4nBiOIzoMXdl+OI0j8w8MvPIzCMzj8w8svA8hxE0Cw0jVsrb425grfT18phHZh6ZeWTmkZlHZh5ZeJ7DCLLwvC8ufmBUe+zjix8U7aQ2fHGaR2YemXlk5pGZR2YeWXieFz9oVp21hAwjRnl5zCMzj8w8MvPIzCMzj8w8svC8EneCbYR/PfPIHqxGGYtPh+M4AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">is_repeated_guest\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">115580</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">96.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3810</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAIAAAAAtCAQAAADMtatwAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAsklEQVRo3u2asQ2AIBQF+cYd3UHn0R2YUjsDRBoKL+S962jIefGTSIw7abPQAjQOQAvQrOXiEjkQ9ugESGmj3X4gVyv5EXAAWoDGAWgBGgegBWgcgBagcQBagMYBaAEa+QDN53Ae22ViorwDieFt5qJ8ZvkRkA9QnQHn+24cKtPwfSeodBTKj4AD0AI0DkAL0DgALUDjALQAjQPQAjQOQAvQyAfwnaDIf1Fd5EfAAWgBmgeYLguzkKMpDAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">previous_cancellations\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 26</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (9.7)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">15 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAt0lEQVR42u3csQ3CMBBAUYKyI0MwD+zAlNCaQIMEWMr7r7Oc4r7ktLfcD6bj7AEKL/w/1vFwffPDn5fZI37PmLc+X502n95mz/oz7FMvXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK1xSuKVxTuKZwTeGawjWFawrXFK4pXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK12z2ub3ub7vsaZvlsJRv2VPXJ9inXrjmAbnqCPV+b3IVAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">previous_bookings_not_canceled\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (1.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 72</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (10.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">73 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAtklEQVR42u3csQ3CMBBAUYyyI0MwD+zAlNAmoaEALOX911lu7kt2e+N5Mp1nD1B44f+xrA/3tw9/HbMH/KZ13rK9umxOj9mT/hD71AvXFK4pXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK1xSuKVxTuKZwTeGawjWFawrXFK4pXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1u31u+w1ut2Ptslyt5RvHKvsc+9QL17wAvzwI9QRc5r0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDBJcP+KAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwOC1HNgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reserved_room_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. B</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. C</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. D</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. E</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. G</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. H</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. L</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. P</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">85994</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">72.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1118</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">932</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">19201</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">16.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6535</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2897</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2094</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">601</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGMAAADECAQAAAAhK1dIAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABiElEQVR42u3cQQqCUBhFYV+0R/dQ66k9uMoaNFGpEIne+a/nmzUJD76gS1J7DAlOvS/AjLyM8/zFvdQH5dI+ZAzD2PvaNpsWr0IOlRkkZpCYQWIGiRkkZpCEZKy+qE/73qW7Nl9Kbffb9DC/8pBDtci4PW6lZuyHjLrMIDGDxAwSM0jMIDGDxAySkAxHLIkjlsQMEjNIzCAxg8QMEjNIzCAJyXDEkix+3t86Ya+427bjcWLikwwhh8oMEjNIzCAxg8QMEjNIQjJ8nLi3Y41Y3lTdmDEfsbU+JSGHygwSM0jMIDGDxAwSM0hCMhyxvR1lxFaary+ruzEW+munLxlVmUFiBokZJGaQmEFiBklIhiO2t2OM2HoT9s2IrSnkUJlBYgaJGSRmkJhBYgZJZoYj9u8CR+zqj516X85PMuoyg8QMEjNIzCAxg8QMEjNIQjIcsSSOWBIzSMwgMYPEDBIzSMwgMYMkJMMRS+KIJTGDxAwSM0jMIDGDxAwSM0hCMlrZpbQQcjfMIHkCjucx6R2rB5QAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDBJcP+KAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwOC1HNgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">assigned_room_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. D</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. E</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. G</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. C</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. B</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. H</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. I</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. K</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 2 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74053</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">62.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">25322</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">21.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7806</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3751</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2553</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2375</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2163</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">712</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">363</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">279</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAADXCAQAAADFcQU/AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABaElEQVR42u3cwW0CMRCGUTuix/SQ1AM9UCU5RVogiYh3bc9Y77txQU+bOex/IPVWMvU2G4Abp9P2wyXkIX/UX7ilvM+2PXW9+5TsGHBxcXFxcXFxF+Q+vEBe275lWHX7Rl6bv6ZnW2HmYzg3jJ/PoX+SneNn9K0nOwZcXFxcXFxc3AW5xs/RrTt+xk6bf3Ifx0+8S052DLi4uLi4uLi4C3KNn6Nbb/xEGz0/cr/HT9wLTnYMuLi4uLi4uLgLco2fo1tr/EQdPqU8Pd14v/n5kxs9XFxcXFxcXNz1ucbP7hKPn2RcW20gN3q4uLi4uLi4uA1c42d3xs+ojJ+B3Ojh4uLi4uLi4jZwjZ/dGT9TuOdby7+nm8aNHy4uLi4uLi4u7uyMn55l5kafPrmfbvxwcXFxcXFxcRfkGj89y8w1fnAThYuLi4uLi4v7SsZPzzJzjR/cROHi4uLi4uLivlIN/4p7V7Kni9uzLzZYNz0k3LSEAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">booking_changes\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.2 (0.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 21</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (2.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">21 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAzUlEQVR42u3csQ2DMBQA0TjyjuwQ5oEdmBIaFD6FJQrA0r+7BpAp/GRw6bJ+mH17T0C48Heq8WEOP/xYek/t/uJ+Vs9Dw35des/x8bCfunBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBawmkJpyWclnBaWHhtDUzJT/pqwof/Xc6TvuqVl47Vz7P2JR7uNic/ufIXlq0ktzbD7urCaW20BA65CJnKTQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">deposit_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. No Deposit</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Non Refund</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Refundable</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">104641</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">87.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14587</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">162</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHUAAABACAQAAACOuvApAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAt0lEQVRo3u3YQQrCMBQG4Tzxjt5Bz6N36Cl1mwhVqULN/PPtsikdkhby6t5SHPZ+AVNN/caxX9xwH+65VlJbO+39bj+1DKugA2wqkalEphKZSmQqkalEQalPl7hl21OmUP1tvDY/5l/1dUEHOCh1+FavL2dLl8nP98ezpfl/WEEH2FQiU4lMJTKVyFQiU4mCUp0tUThbejdwmV3qrrKZSmQqkalEphKZSmQqkalEhb6ND4J21VSiB8OkD2tWf3CsAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">agent\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 9</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. NULL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 240</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 14</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 7</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 6</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 250</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 241</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 28</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 324 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">31961</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">26.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">16340</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">13.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13922</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7191</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3640</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3539</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3290</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2870</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1721</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1666</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">33250</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">27.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAC4AAADXCAQAAADPLattAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABIElEQVR42u3cwQ2DMAyF4aZiR4ZgHroDU9JDLwFMiIkd1eJ/N1TpE3UiHmoFaX355e1oB8aH/ODTvABTyolh++HYRC89xwIODg4eDt9dcpd7ykk2F/dkAOZev7HMlzU3qb6cqua0KxJ3K4KDg4N7hJoTo6g5XcUd8FLN3VmNuFsRHBwc3CPUnJhizemLrYBva659/nG3Ijg4OLhHqDkxYs211tvJmY+N/84VcduAg4ODh8OpOTF0aA1uG3BwcHCPUHNiqLka3Dbg4ODgHqHmxFBzNbhtwMHBwT1CzYnpXXNWJSfUnGXizhwcHBz8F2quNz6v14/l/eeZg4ODgz8ep+bEKJ89r0g2W9NXrOzve+LOHBwc/LF4vx8trRN35q74Fwh9Pi1cmvHfAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">company\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. NULL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 40</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 223</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 67</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 45</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 153</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 174</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 219</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 281</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 154</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 343 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">112593</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">927</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">784</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">267</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">250</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">215</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">149</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">141</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">138</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">133</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3793</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAH0AAADXCAQAAACdDpYmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABgElEQVR42u3aMW6DQABFwSXyHX2H5Dz2HTilU1AEkNxYipGZNx0N2ietC748PYbq6+gDlF76O13WD/fT//C/pyfpY1yPPtu/mjdP8IUvXVS6qHRR6aLSRaWL4PTdR+v82ls+0rReJ6aXX/Mp1rXwhd+k3x63009UT9ItpYtKF5UuKl1Uuqh0UekiOL2BStRAJSpdVLqodFHpotJFpYtKF8HpDVSi3UB19HEOS7eULipdVLqodFHpotJFpYvg9AYqUQOVqHRR6aLSRaWLSheVLipdBKc3UIlKX7TNIUoXlS4qXVS6qHRR6aLSRQ1UotIXDVSI0kWli0oXlS4qXVS6qHRRA5Wo9EUDFaJ0Uemi0kWli0oXlS4qXdRAJSp90UCFKF1Uuqh0Uemi0kWli0oXNVCJSl80UCFKF5UuKl1Uuqh0Uemi0kUNVCI4/bJ++Buofs5/97fpY1zHGGPMR5/qLeALX7qodFHpotJFpYtKF+2+3IxvtsVE/YdkA77wpYt+AQqnMFF2zVneAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">days_in_waiting_list\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.3 (17.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 391</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (7.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">128 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAwUlEQVR42u3cwQ2CQBRAQTH0aBHWoz1Ypd4MmBhigiKZNyfIXv5j2esO94PpuPUAhRf+G+P05To78Odh6+HWNs0b50un59Nt6ym/jP3VC9cUrilcU7imcE3hmsI1hWsK1xSuKVxTuKZwTeGawjWFawrXFK4pXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK1xSuKVxTuKZwTeEaNnx8v3RZuM5x3/e9vYR/covb0of5Q5OtGvY3/TrYM1645gELQAr3ZoJa2gAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">customer_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Contract</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Group</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Transient</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Transient-Party</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4076</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">577</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">89613</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">75.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">25124</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">21.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGYAAABTCAQAAADHYbr3AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAA4klEQVR42u3asQ3CMBQGYRtlR4ZgHtiBKaFAQnZEgUjhez/3dRGNT3EQfqE/Wo7T6gUY8w8x23hxez9Al756Yd8an/lt/ujcWmvtvnqFP4raZsZQGUNlDJUxVMZQGUMVFbM7AlT98f/Sx8NNmRPZYFx/1DabYq7F5065d6Y6Y6iMoTKGyhgqY6iMoTKGymMz1TSdKXlsHrbTx7fNdcyjsahtZgyVMVTGUBlDZQyVMVRRMb5tJok9NkfFHJ4BkP6bfnAGwPrCiNpmxlAZQ2UMlTFUxlAZQxUVkzsDqC5qmxlD9QT1qhXTxBNhHAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">average_daily_rate\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 101.8 (50.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">-6.4 &le; 94.6 &le; 5400</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 56.7 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">8879 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAxklEQVR42u3cuw3CMBRA0RixIzvAPLADU0IbEhANApFzT5dP4StbLt+4TabdrxdQeOHfsZ8/jNXn89Mr4DSmvzSP2b/7+bB6c/31+j+CPeqFawrXFK4pXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK1xSuKVxTuKZwTeGawjWFawrXFK4pXFO4pnBN4ZrCNYVrCtcUrilcU7imcM3DdK8zNMdwMdZsOcRsGyPMnhnzTb5sfMePswF8Y+OtL7GXW+GaO2QeDEtXP9zWAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">required_car_parking_spaces\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 8</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (3.9)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">111974</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">93.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">7383</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">6.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">28</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">8</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAH0AAABmCAQAAABMmFb2AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAA50lEQVR42u3aQQ5AMBQA0X5xR3fgPNzBKVmwKAkLCY3OvF030ol24UcsiaopvQHTTf9Smy+m6i9+HxfpKXWl9/aq+bACH3jTiUwnMp3IdCLTiUwnAqefPlrnZ0/5pcinE/H4MX+R13rgN+NpQDVUfQxuBlS133vwgTedyHQi04lMJzKdyHQicLoDqn1Rejevc0Blemas/uexy3QW04lMJzKdyHQi04lMJzKdyAEVkekbB1QQphOZTmQ6kelEphOZTmQ6ETjd2RyRAyoi04lMJzKdyHQi04lMJzKdCJweqOnEAfitm060AuS6Ftv0rdl5AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">total_of_special_requests\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.6 (0.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 5</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (1.4)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">70318</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">58.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">33226</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">27.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12969</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2497</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">340</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">40</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFMAAAB4CAQAAAAk0AZ+AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABAklEQVR42u3aTQ6CMBgGYWq8o3fQ8+gdOKXuTEvAaGnpfHFmx4Y84SfhTUjPKUKn0QCZx3fODx6oB/WaNpjTdBltezcXR0FuukyZ1GTKpCZTJrXFF9Jcd5bupfwTM1Wfpke5LMhND8Isns17g5Fx6/LkNB4ZvV7BIDddpkxqMmVSkymTmiNjb46MXn09MvqMhyrm9sgY/WoFuekyZVKTKZOaTJnUgjDdQnsLuIVWRsbYObHe4mpyfpf6yKQmUyY1mTKpyZRJLSbTkfFzAUdGwWzxu9QBTG4yZVKTKZOaTJnUZP4h05HRMkeGTGoyZVKTKZOaTJnUgjAT9ku4KMjVlNmyF5UsHhp8xUq7AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reservation_status\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Canceled</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Check-Out</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. No-Show</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">43017</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">36.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">75166</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">63.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1207</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFgAAABACAQAAAA0GXhJAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAqElEQVRo3u3YQQqFMAxFUSPdo4twPboHV1mnaXHWPk3k3pl8lMMnSKrVJVfr1wDA0Sr+4hQN9G5j93tWaX/aBNxr6tPSjQRgwIABAwYMOFSA1XXr5dxVUJH55Xhwz5bljelGIh24meEj6kcKN6svnOlGa18E6UYCMGDAgAEDBhwqwOo40yn6z5nuqGEPSc/gDAEGDBgwYMCAQwUYcHawhd/Yu9L9w4DV3RWPEZT5p3EDAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reservation_status_date\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 2015-10-21</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 2015-07-06</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 2016-11-25</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 2015-01-01</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 2016-01-18</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 2015-07-02</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 2016-12-07</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 2015-12-18</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 2016-02-09</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 2016-04-04</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 916 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1461</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">805</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">790</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">763</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">625</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">469</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">450</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">423</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">412</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">382</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">112810</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAH4AAADXCAQAAAB2OS0lAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAABbUlEQVR42u3YUWrCQABF0UnJHruIrsfuwVWmXwNR7I+gQ3vu+QuCzCVRyNuO4fpYfYDii3+//XzxfYzxta0+0mud/+PoO1+8qnhV8ariVcWrilcVr6Ljt/PL/T/fMcYYjRmP4y/HhVqyu/Oq4lXFq4pXFa8qXlW8qnhVM5aqGUtVvKp4VfGq4lXFq4pXFa+i45uxVM1YquJVxauKVxWvKl5VvKp4FR3fjKW6m7FWH2dhvKZ4VfGq4lXFq4pXFa8qXkXHN2Opip/a8CDFq4pXFa8qXlW8qnhV8apmLFXxUzMWpHhV8ariVcWrilcVrype1YylKn5qxoIUrypeVbyqeFXxquJVxauasVTFT81YkOJVxauKVxWvKl5VvKp4VTOWqvipGQtSvKp4VfGq4lXFq4pXFa9qxlLR8fv5gpixTr/t/faTz9VHe7HrzRX92BevKl5VvKp4VfGq4lV3b3XX577lj9qEV/jf0I998aof0RAwzVrvmwQAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDBJcP+KAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwOC1HNgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">number_of_guests\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2 (0.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 55</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (0.4)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">15 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAt0lEQVR42u3csQ3CMBBAUYKyI0MwD+zAlNAaSIMEWMr7r7Oc4r7ktLfcD6bj7AEKL/w/1vFw3fzhz8vsIb9lzFufr05vH99mT/sj7FMvXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK1xSuKVxTuKZwTeGawjWFawrXFK4pXFO4pnBN4ZrCNYVrCtcUrilcU7imcE3hmsI1hWsK17zsc9va3nbZzz7LYSXfsp+qz7BPvXDNA7SYCPUHQFToAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAxLTEzVDA4OjQxOjAwKzAwOjAwSXD/igAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMDgtRzYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">119386\n(100.0%)</td>\n      <td align=\"center\">4\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">total_stay\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 3.4 (2.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 3 &le; 69</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.7)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">45 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAHwAAABaCAQAAADQ4voeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfnAQ0IKQBCyr6kAAAAzUlEQVR42u3cQQ5AMBQAUZXe0R04D3dwSrZFEAma/JnZNbXoi5KumpaGWVt7AcKF/1MuB9Phgx9S7QW+WcnL26luM5prr/TDsFtdOC3htITTEk5LOC3htITTEk5LOC3htITTEk5LOC3htITTEk5LOC3htITTEk5LOC3htITTEk5LOC3htITTEk5LOC3htITTEk4LC8/X0+Pu1og4d0bcwOPeGYHd6sJpCaclnJZwWvnZ43GOsA/hcY6wqXyFU/CbK/tif6bg1tOwPzfhtFZ1HQ+7I8lMfQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xM1QwODo0MTowMCswMDowMElw/4oAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMDEtMTNUMDg6NDE6MDArMDA6MDA4LUc2AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">119390\n(100.0%)</td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.2)<br/>2023-01-13</p>\n</div>\n```\n:::\n:::\n\nFrom the above detail we get a lot more information about the descriptive statistics for numeric variables in the data.\nThe percentage of cancelled reservation sis 37.On average, reservations are made 104 days before date of stay. On average, every reservation is made for 1.97 people. \nOut of the bookings,one out of 10 reservations included a infant present.\nThe daily rate of hotels is $101 on an average and average stay duration is 3.34 days. Around average stay duration is 3.43 days. 22% of the booking is changed afterwards. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(hotel.bookings))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         hotel                    is_canceled \n                             0                              0 \n                     lead_time              arrival_date_year \n                             0                              0 \n            arrival_date_month       arrival_date_week_number \n                             0                              0 \n     arrival_date_day_of_month        stays_in_weekend_nights \n                             0                              0 \n          stays_in_week_nights                         adults \n                             0                              0 \n                      children                         babies \n                             4                              0 \n                          meal                        country \n                             0                              0 \n                market_segment           distribution_channel \n                             0                              0 \n             is_repeated_guest         previous_cancellations \n                             0                              0 \nprevious_bookings_not_canceled             reserved_room_type \n                             0                              0 \n            assigned_room_type                booking_changes \n                             0                              0 \n                  deposit_type                          agent \n                             0                              0 \n                       company           days_in_waiting_list \n                             0                              0 \n                 customer_type             average_daily_rate \n                             0                              0 \n   required_car_parking_spaces      total_of_special_requests \n                             0                              0 \n            reservation_status        reservation_status_date \n                             0                              0 \n              number_of_guests                     total_stay \n                             4                              0 \n```\n:::\n:::\n\n\n\nOf the numerical variables, only 4 value is missing. \nHowever, when we examine the summary table above and the dataset itself we can see that there are some \"NULL\" entries that shows up as string. From summary table, `agent` and `company` variables have \"NULL\" values. \n\nWe can check the null values individually.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnulls <- sapply(hotel.bookings, function(x) table(grepl(\"NULL\", x)))\n\nfor (i in 1:32) {\n  if (!is.na(nulls[[i]][2])) {\n    print(nulls[i])\n    }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$country\n\n FALSE   TRUE \n118902    488 \n\n$agent\n\n FALSE   TRUE \n103050  16340 \n\n$company\n\n FALSE   TRUE \n  6797 112593 \n```\n:::\n:::\n\n\nSo, actully 3 variables, `country`, `agent` and `company` have \"NULL\" values. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(100*prop.table(table(grepl(\"NULL\", hotel.bookings$country))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n99.59  0.41 \n```\n:::\n\n```{.r .cell-code}\nround(100*prop.table(table(grepl(\"NULL\", hotel.bookings$agent))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n86.31 13.69 \n```\n:::\n\n```{.r .cell-code}\nround(100*prop.table(table(grepl(\"NULL\", hotel.bookings$company))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n 5.69 94.31 \n```\n:::\n:::\n\n\n\n0.41% of `country` data, 13.89% of `agent` data and 94.31% of `company` data of reservations are missing.\n\n\n\n## Some analysis\n\nAccording to the summary table, daily rate of a city hotel may go up to 5400 dollars while it is only 508 dollars for resort hotels. \nThis seems suspicious.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  arrange(desc(average_daily_rate)) %>% \n  slice_head(n=10) %>% \n  select(hotel, arrival_date_year, \n         country, \n         agent, \n         number_of_guests, \n         total_stay, \n         reservation_status, \n         average_daily_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          hotel arrival_date_year country agent number_of_guests total_stay\n1    City Hotel              2016     PRT    12                2          1\n2    City Hotel              2017     ITA   159                1          1\n3  Resort Hotel              2015     PRT  NULL                2          1\n4    City Hotel              2016     PRT  NULL                4          2\n5  Resort Hotel              2017     PRT   314                2         14\n6  Resort Hotel              2017     PRT   250                4          6\n7  Resort Hotel              2017     PRT   250                4          8\n8  Resort Hotel              2017     ESP   240                4          5\n9  Resort Hotel              2017     MAR   250                5          8\n10 Resort Hotel              2017     PRT   250                3         10\n   reservation_status average_daily_rate\n1            Canceled            5400.00\n2           Check-Out             510.00\n3           Check-Out             508.00\n4           Check-Out             451.50\n5            Canceled             450.00\n6            Canceled             437.00\n7           Check-Out             426.25\n8           Check-Out             402.00\n9           Check-Out             397.38\n10           Canceled             392.00\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  arrange(average_daily_rate) %>% \n  slice_head(n=10) %>% \n  select(hotel, arrival_date_year, \n         country, \n         agent, \n         number_of_guests, \n         total_stay, \n         reservation_status, \n         average_daily_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          hotel arrival_date_year country agent number_of_guests total_stay\n1  Resort Hotel              2017     GBR   273                2         10\n2  Resort Hotel              2015     PRT  NULL                2          0\n3  Resort Hotel              2015     PRT  NULL                2          0\n4  Resort Hotel              2015     PRT  NULL                4          1\n5  Resort Hotel              2015     PRT   240                2          0\n6  Resort Hotel              2015     PRT   250                1          0\n7  Resort Hotel              2015     PRT  NULL                2          0\n8  Resort Hotel              2015     PRT   240                2          0\n9  Resort Hotel              2015     PRT   305                2          2\n10 Resort Hotel              2015     PRT   305                1          2\n   reservation_status average_daily_rate\n1           Check-Out              -6.38\n2           Check-Out               0.00\n3           Check-Out               0.00\n4           Check-Out               0.00\n5           Check-Out               0.00\n6           Check-Out               0.00\n7           Check-Out               0.00\n8           Check-Out               0.00\n9            Canceled               0.00\n10          Check-Out               0.00\n```\n:::\n:::\n\n\nWe can observe that the row with 5,400 dollars average daily rate is a wrong entry. There is also a row with negative average daily rate. \nWe can remove both of them.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings <- hotel.bookings %>% filter(average_daily_rate>=0 & average_daily_rate<=510)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  select(hotel, average_daily_rate) %>% \n  group_by(hotel) %>% \n  summarise_if(is.numeric, list(min = min, max = max, mean = mean, std_dev = sd, median = median), na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  hotel          min   max  mean std_dev median\n  <chr>        <dbl> <dbl> <dbl>   <dbl>  <dbl>\n1 City Hotel       0   510 105.     39.3   99.9\n2 Resort Hotel     0   508  95.0    61.4   75  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  select(country) %>% \n  group_by(country) %>% \n  count() %>% \n  arrange(desc(n)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n# Groups:   country [10]\n   country     n\n   <chr>   <int>\n 1 PRT     48589\n 2 GBR     12128\n 3 FRA     10415\n 4 ESP      8568\n 5 DEU      7287\n 6 ITA      3766\n 7 IRL      3375\n 8 BEL      2342\n 9 BRA      2224\n10 NLD      2104\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  select(country, is_canceled) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, sum, na.rm = TRUE) %>% \n  arrange(desc(is_canceled)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   country is_canceled\n   <chr>         <int>\n 1 PRT           27518\n 2 GBR            2453\n 3 ESP            2177\n 4 FRA            1934\n 5 ITA            1333\n 6 DEU            1218\n 7 IRL             832\n 8 BRA             830\n 9 USA             501\n10 BEL             474\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  filter(country %in% c(\"PRT\", \"GBR\", \"ESP\", \"FRA\", \"ITA\")) %>% \n  select(country,is_canceled) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, mean, na.rm = TRUE) %>% \n  arrange(desc(is_canceled))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 2\n  country is_canceled\n  <chr>         <dbl>\n1 PRT           0.566\n2 ITA           0.354\n3 ESP           0.254\n4 GBR           0.202\n5 FRA           0.186\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  filter(reservation_status == \"Check-Out\") %>% \n  select(country, number_of_guests) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, sum, na.rm = TRUE) %>% \n  arrange(desc(number_of_guests)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   country number_of_guests\n   <chr>              <int>\n 1 PRT                37670\n 2 GBR                19256\n 3 FRA                17299\n 4 ESP                13213\n 5 DEU                11659\n 6 IRL                 5102\n 7 ITA                 4894\n 8 BEL                 3855\n 9 NLD                 3374\n10 USA                 3212\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  filter(reservation_status == \"Check-Out\") %>% \n  select(country, number_of_guests) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, sum, na.rm = TRUE) %>% \n  arrange(desc(number_of_guests)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   country number_of_guests\n   <chr>              <int>\n 1 PRT                37670\n 2 GBR                19256\n 3 FRA                17299\n 4 ESP                13213\n 5 DEU                11659\n 6 IRL                 5102\n 7 ITA                 4894\n 8 BEL                 3855\n 9 NLD                 3374\n10 USA                 3212\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  select(country, average_daily_rate) %>% \n  group_by(country) %>% \n  summarise_if(is.numeric, mean, na.rm = TRUE) %>% \n  arrange(desc(average_daily_rate)) %>% \n  head(n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   country average_daily_rate\n   <chr>                <dbl>\n 1 DJI                   273 \n 2 AIA                   265 \n 3 AND                   203.\n 4 UMI                   200 \n 5 LAO                   182.\n 6 MYT                   178.\n 7 NCL                   176.\n 8 GEO                   169.\n 9 COM                   165.\n10 FRO                   155.\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(hotel.bookings$arrival_date_month)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    April    August  December  February   January      July      June     March \n    11089     13877      6780      8068      5929     12661     10939      9792 \n      May  November   October September \n    11791      6794     11160     10508 \n```\n:::\n:::\n\n\n\nFrom the above tables we can form some observations.\n\nThe average daily rate for City Hotels is 11 dollars higher than Resort Hotels. However the variance in price of Resort Hotels is greater than that of City Hotels.\n\nThe most popular 10 countries in terms of total reservations are Portugal, Great Britain, France, Spain, Germany, Italy, Ireland, Belgium, Brasil and Netherlands. However, we can see that 56% reservations made for Portugal hotels are actually canceled. This ratio is 35% for Italy and 25% for Spain. \nAmong all of them, the country that hosts the highest number of guests is Portugal with total of 37,670 guests in 3 years.\n\nInterestingly, in terms of average daily rate, the most expensive hotels are in Djibouti, Anguilla, Andorra, United States Minor Outlying Islands, Laos and so on. It looks that hotels in small countries that host a small number of guests are much more expensive.\n\nAugust, July and May, respectively, are the months when hotels are the busiest throughout the year.\n\n\nWe can check the bookings with zero daily rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  filter(average_daily_rate == 0) %>% \n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     n\n1 1959\n```\n:::\n:::\n\n\nThere are 1959 reservations with zero daily rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel.bookings %>% \n  filter(average_daily_rate == 0) %>% \n  group_by(country) %>% \n  count() %>% \n  arrange(desc(n)) %>% \n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n# Groups:   country [6]\n  country     n\n  <chr>   <int>\n1 PRT      1550\n2 ESP        79\n3 GBR        73\n4 FRA        55\n5 DEU        41\n6 NULL       21\n```\n:::\n:::\n\n\nWe can observe that most of the zero values from Portugal.So we need to delve further into the the accuracy.\n\n\n## Potential research questions\n\n1. How do hotel room rates change seasonally?\n2. Are the room rates change according to the length of stay or not?\n3. How is the performance of agents in terms of number of reservations and length of stay?\n4. How the preferences of families with children differ from other visitors?\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}