{
  "hash": "24054f1ab95426919f3aab6f955dba8a",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 Solutions\"\nauthor: \"Vinitha Maheswaran\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"10/12/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xls ⭐\n-   FAOstat\\*.csv or birds.csv ⭐⭐⭐\n-   hotel_bookings.csv ⭐⭐⭐⭐\n\n\nFor this challenge I will be working with the \"hotel_bookings\" data set. It is a publicly available data set containing booking transactions from a city hotel and a resort hotel in Portugal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reading the hotel_bookings.csv data set and storing in a data frame\nhotel_data <- read_csv(\"_data/hotel_bookings.csv\")\nprint(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 119,390 × 32\n   hotel  is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n   <chr>    <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n 1 Resor…       0     342    2015 July         27       1       0       0      2\n 2 Resor…       0     737    2015 July         27       1       0       0      2\n 3 Resor…       0       7    2015 July         27       1       0       1      1\n 4 Resor…       0      13    2015 July         27       1       0       1      1\n 5 Resor…       0      14    2015 July         27       1       0       2      2\n 6 Resor…       0      14    2015 July         27       1       0       2      2\n 7 Resor…       0       0    2015 July         27       1       0       2      2\n 8 Resor…       0       9    2015 July         27       1       0       2      2\n 9 Resor…       1      85    2015 July         27       1       0       3      2\n10 Resor…       1      75    2015 July         27       1       0       3      2\n# … with 119,380 more rows, 22 more variables: children <dbl>, babies <dbl>,\n#   meal <chr>, country <chr>, market_segment <chr>,\n#   distribution_channel <chr>, is_repeated_guest <dbl>,\n#   previous_cancellations <dbl>, previous_bookings_not_canceled <dbl>,\n#   reserved_room_type <chr>, assigned_room_type <chr>, booking_changes <dbl>,\n#   deposit_type <chr>, agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\nAfter reading the data using read_csv function, it is stored in a dataframe \"hotel_data\". The hotel_bookings data set contains 119390 rows (observations) and 32 columns (attributes/variables) including information such as when the booking was made, length of stay, the number of adults, children, and/or babies, the number of available parking spaces, and many others for the respective hotels. Each row/observation represents a hotel booking. Since this is a public data set, all data elements pertaining to hotel or customer identification are not included in the data set. This data set can have an important role for research and educational purposes in hotel administration, revenue management, machine learning, data mining and other fields. This data set will be helpful for (i) Tourists (people who are booking hotels) to check and understand trends of hotel price over a period of time and plan their travel accordingly within budget, learn about hotel accommodations and features before booking (ii) Hotel Management to keep track of the relevant information about themselves as well as their competitors. Understand and analyze the seasonal trend of hotel booking and accommodate different types of visitors that they have (iii) Tourist / hospitality services - (e.g. travel agency, airlines / car rental companies) to observe the times when hotels in the region are in high demand, analyze the duration of typical stays, and use the information to help plan their own services (iv)  Local Government / independent data analysts to observe the overall trend of tourist activities in the region and analyzing the different types of visitors in the hotels during different seasons.\n\nUsing the \"dfSummary\" function from \"summarytools\" package we find that there are 31994 duplicates in the data. The reason for the identified duplication is that there is no unique id for each booking. It is possible that the booking was made by different tourists and the values for each attribute was exactly the same. This confusion could have been avoided by adding a Booking ID which would be unique for each booking. We can also see that there are 4 NA's in the data for the column \"Children\". We can ignore this for now as 4 NA values out of 119390 values would not change the grouped summary statistics significantly. 66.4% of the data represents city hotel and the remaining 33.6% of the data represents resort hotel. 18.4%, 47.5% and 34.1% of the data correspondingly represents years 2015, 2016 and 2017. I wanted to check the unequal distribution in data for the 3 consecutive years. I further investigated the data and found that the data we have represents hotel bookings from the period July 2015 - August 2017. Hence, we cannot compare the summary statistics between 2015, 2016 and 2017 as we do not have data for the entire years of 2015 and 2017. I performed group summary statistics on \"hotel\", arrival_date_year\" and \"arrival_date_month\" combined.\n\nFew interesting finds!!\nThe maximum \"lead_time\" is 737 indicating that someone had made a booking 2 years in advance! 37% of the bookings were cancelled. A booking was made for a maximum of 55 \"adults\" once. A booking was made for a maximum of 10 \"children\" once and a maximum of 10 \"babies\" another time. About 77% of the bookings preferred BB (Bed & Breakfast) \"meal\" package. The \"country\" of origin was PRT (Portugal) for around 41% of the bookings. Most of the bookings are made by Offline TA/TO and Online TA \"market segment\". The maximum \"previous_cancellations\" done by a person making the hotel booking is 26. Most of the tourists prefer \"reserved_room_type\" A which may be the best bang for your buck. A maximum of 21 \"booking_changes\" was made for a particular booking. A certain booking was on a maximum of 391 \"days_in_waiting_list\". The maximum \"adr\" (Average Daily Rate) for a booking was 5400. The maximum \"required_car_parking_spaces\" was a maximum of 8 in two separate booking instances.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Finding dimension of the data set\ndim(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 119390     32\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Finding column names\ncolnames(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"hotel\"                          \"is_canceled\"                   \n [3] \"lead_time\"                      \"arrival_date_year\"             \n [5] \"arrival_date_month\"             \"arrival_date_week_number\"      \n [7] \"arrival_date_day_of_month\"      \"stays_in_weekend_nights\"       \n [9] \"stays_in_week_nights\"           \"adults\"                        \n[11] \"children\"                       \"babies\"                        \n[13] \"meal\"                           \"country\"                       \n[15] \"market_segment\"                 \"distribution_channel\"          \n[17] \"is_repeated_guest\"              \"previous_cancellations\"        \n[19] \"previous_bookings_not_canceled\" \"reserved_room_type\"            \n[21] \"assigned_room_type\"             \"booking_changes\"               \n[23] \"deposit_type\"                   \"agent\"                         \n[25] \"company\"                        \"days_in_waiting_list\"          \n[27] \"customer_type\"                  \"adr\"                           \n[29] \"required_car_parking_spaces\"    \"total_of_special_requests\"     \n[31] \"reservation_status\"             \"reservation_status_date\"       \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Structure of hotel_data\nstr(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspec_tbl_df [119,390 × 32] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ hotel                         : chr [1:119390] \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" \"Resort Hotel\" ...\n $ is_canceled                   : num [1:119390] 0 0 0 0 0 0 0 0 1 1 ...\n $ lead_time                     : num [1:119390] 342 737 7 13 14 14 0 9 85 75 ...\n $ arrival_date_year             : num [1:119390] 2015 2015 2015 2015 2015 ...\n $ arrival_date_month            : chr [1:119390] \"July\" \"July\" \"July\" \"July\" ...\n $ arrival_date_week_number      : num [1:119390] 27 27 27 27 27 27 27 27 27 27 ...\n $ arrival_date_day_of_month     : num [1:119390] 1 1 1 1 1 1 1 1 1 1 ...\n $ stays_in_weekend_nights       : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ stays_in_week_nights          : num [1:119390] 0 0 1 1 2 2 2 2 3 3 ...\n $ adults                        : num [1:119390] 2 2 1 1 2 2 2 2 2 2 ...\n $ children                      : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ babies                        : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ meal                          : chr [1:119390] \"BB\" \"BB\" \"BB\" \"BB\" ...\n $ country                       : chr [1:119390] \"PRT\" \"PRT\" \"GBR\" \"GBR\" ...\n $ market_segment                : chr [1:119390] \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ distribution_channel          : chr [1:119390] \"Direct\" \"Direct\" \"Direct\" \"Corporate\" ...\n $ is_repeated_guest             : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ previous_cancellations        : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ previous_bookings_not_canceled: num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ reserved_room_type            : chr [1:119390] \"C\" \"C\" \"A\" \"A\" ...\n $ assigned_room_type            : chr [1:119390] \"C\" \"C\" \"C\" \"A\" ...\n $ booking_changes               : num [1:119390] 3 4 0 0 0 0 0 0 0 0 ...\n $ deposit_type                  : chr [1:119390] \"No Deposit\" \"No Deposit\" \"No Deposit\" \"No Deposit\" ...\n $ agent                         : chr [1:119390] \"NULL\" \"NULL\" \"NULL\" \"304\" ...\n $ company                       : chr [1:119390] \"NULL\" \"NULL\" \"NULL\" \"NULL\" ...\n $ days_in_waiting_list          : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ customer_type                 : chr [1:119390] \"Transient\" \"Transient\" \"Transient\" \"Transient\" ...\n $ adr                           : num [1:119390] 0 0 75 75 98 ...\n $ required_car_parking_spaces   : num [1:119390] 0 0 0 0 0 0 0 0 0 0 ...\n $ total_of_special_requests     : num [1:119390] 0 0 0 0 1 1 0 1 1 0 ...\n $ reservation_status            : chr [1:119390] \"Check-Out\" \"Check-Out\" \"Check-Out\" \"Check-Out\" ...\n $ reservation_status_date       : Date[1:119390], format: \"2015-07-01\" \"2015-07-01\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   hotel = col_character(),\n  ..   is_canceled = col_double(),\n  ..   lead_time = col_double(),\n  ..   arrival_date_year = col_double(),\n  ..   arrival_date_month = col_character(),\n  ..   arrival_date_week_number = col_double(),\n  ..   arrival_date_day_of_month = col_double(),\n  ..   stays_in_weekend_nights = col_double(),\n  ..   stays_in_week_nights = col_double(),\n  ..   adults = col_double(),\n  ..   children = col_double(),\n  ..   babies = col_double(),\n  ..   meal = col_character(),\n  ..   country = col_character(),\n  ..   market_segment = col_character(),\n  ..   distribution_channel = col_character(),\n  ..   is_repeated_guest = col_double(),\n  ..   previous_cancellations = col_double(),\n  ..   previous_bookings_not_canceled = col_double(),\n  ..   reserved_room_type = col_character(),\n  ..   assigned_room_type = col_character(),\n  ..   booking_changes = col_double(),\n  ..   deposit_type = col_character(),\n  ..   agent = col_character(),\n  ..   company = col_character(),\n  ..   days_in_waiting_list = col_double(),\n  ..   customer_type = col_character(),\n  ..   adr = col_double(),\n  ..   required_car_parking_spaces = col_double(),\n  ..   total_of_special_requests = col_double(),\n  ..   reservation_status = col_character(),\n  ..   reservation_status_date = col_date(format = \"\")\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Summary of hotel_data\nsummary(hotel_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    hotel            is_canceled       lead_time   arrival_date_year\n Length:119390      Min.   :0.0000   Min.   :  0   Min.   :2015     \n Class :character   1st Qu.:0.0000   1st Qu.: 18   1st Qu.:2016     \n Mode  :character   Median :0.0000   Median : 69   Median :2016     \n                    Mean   :0.3704   Mean   :104   Mean   :2016     \n                    3rd Qu.:1.0000   3rd Qu.:160   3rd Qu.:2017     \n                    Max.   :1.0000   Max.   :737   Max.   :2017     \n                                                                    \n arrival_date_month arrival_date_week_number arrival_date_day_of_month\n Length:119390      Min.   : 1.00            Min.   : 1.0             \n Class :character   1st Qu.:16.00            1st Qu.: 8.0             \n Mode  :character   Median :28.00            Median :16.0             \n                    Mean   :27.17            Mean   :15.8             \n                    3rd Qu.:38.00            3rd Qu.:23.0             \n                    Max.   :53.00            Max.   :31.0             \n                                                                      \n stays_in_weekend_nights stays_in_week_nights     adults      \n Min.   : 0.0000         Min.   : 0.0         Min.   : 0.000  \n 1st Qu.: 0.0000         1st Qu.: 1.0         1st Qu.: 2.000  \n Median : 1.0000         Median : 2.0         Median : 2.000  \n Mean   : 0.9276         Mean   : 2.5         Mean   : 1.856  \n 3rd Qu.: 2.0000         3rd Qu.: 3.0         3rd Qu.: 2.000  \n Max.   :19.0000         Max.   :50.0         Max.   :55.000  \n                                                              \n    children           babies              meal             country         \n Min.   : 0.0000   Min.   : 0.000000   Length:119390      Length:119390     \n 1st Qu.: 0.0000   1st Qu.: 0.000000   Class :character   Class :character  \n Median : 0.0000   Median : 0.000000   Mode  :character   Mode  :character  \n Mean   : 0.1039   Mean   : 0.007949                                        \n 3rd Qu.: 0.0000   3rd Qu.: 0.000000                                        \n Max.   :10.0000   Max.   :10.000000                                        \n NA's   :4                                                                  \n market_segment     distribution_channel is_repeated_guest\n Length:119390      Length:119390        Min.   :0.00000  \n Class :character   Class :character     1st Qu.:0.00000  \n Mode  :character   Mode  :character     Median :0.00000  \n                                         Mean   :0.03191  \n                                         3rd Qu.:0.00000  \n                                         Max.   :1.00000  \n                                                          \n previous_cancellations previous_bookings_not_canceled reserved_room_type\n Min.   : 0.00000       Min.   : 0.0000                Length:119390     \n 1st Qu.: 0.00000       1st Qu.: 0.0000                Class :character  \n Median : 0.00000       Median : 0.0000                Mode  :character  \n Mean   : 0.08712       Mean   : 0.1371                                  \n 3rd Qu.: 0.00000       3rd Qu.: 0.0000                                  \n Max.   :26.00000       Max.   :72.0000                                  \n                                                                         \n assigned_room_type booking_changes   deposit_type          agent          \n Length:119390      Min.   : 0.0000   Length:119390      Length:119390     \n Class :character   1st Qu.: 0.0000   Class :character   Class :character  \n Mode  :character   Median : 0.0000   Mode  :character   Mode  :character  \n                    Mean   : 0.2211                                        \n                    3rd Qu.: 0.0000                                        \n                    Max.   :21.0000                                        \n                                                                           \n   company          days_in_waiting_list customer_type           adr         \n Length:119390      Min.   :  0.000      Length:119390      Min.   :  -6.38  \n Class :character   1st Qu.:  0.000      Class :character   1st Qu.:  69.29  \n Mode  :character   Median :  0.000      Mode  :character   Median :  94.58  \n                    Mean   :  2.321                         Mean   : 101.83  \n                    3rd Qu.:  0.000                         3rd Qu.: 126.00  \n                    Max.   :391.000                         Max.   :5400.00  \n                                                                             \n required_car_parking_spaces total_of_special_requests reservation_status\n Min.   :0.00000             Min.   :0.0000            Length:119390     \n 1st Qu.:0.00000             1st Qu.:0.0000            Class :character  \n Median :0.00000             Median :0.0000            Mode  :character  \n Mean   :0.06252             Mean   :0.5714                              \n 3rd Qu.:0.00000             3rd Qu.:1.0000                              \n Max.   :8.00000             Max.   :5.0000                              \n                                                                         \n reservation_status_date\n Min.   :2014-10-17     \n 1st Qu.:2016-02-01     \n Median :2016-08-07     \n Mean   :2016-07-30     \n 3rd Qu.:2017-02-08     \n Max.   :2017-09-14     \n                        \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Summary of hotel_data\nlibrary(summarytools)\nprint(summarytools::dfSummary(hotel_data,\n                        varnumbers = FALSE,\n                        plain.ascii  = FALSE, \n                        style        = \"grid\", \n                        graph.magnif = 0.60, \n                        valid.col    = FALSE),\n      method = 'render',\n      table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>hotel_data</h4>\n<strong>Dimensions</strong>: 119390 x 32\n  <br/><strong>Duplicates</strong>: 31994\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">hotel\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. City Hotel</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Resort Hotel</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">79330</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">66.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">40060</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEgAAAAjCAQAAACd14RVAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAd0lEQVRYw+2WQQqAQAhFNbpjd6jz1B3mlLW1IKIZwb94b+dGHn5B/TQtpmoBhP4yx+IoWqjVX4TMlgKddqvkIkMIIYQQqkZO6HE6Wl+XRDzeU+9uM0Z00I5sH3o/tpQBp70fWdsnFxlCCCGEUDXa114BucgQ+uICqNkLn1NBYVkAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">is_canceled\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.4</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">75166</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">63.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">44224</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">37.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEUAAAAjCAQAAABoKQ/lAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAd0lEQVRYw+2WsQ2AMAwEY8SO7ADzwA6ZElqDgMJYyQvddW6SU96KbXtRYegtgMo7oy+25o0z24NKKVNTkXqqhAJCBRVUUPmxyuXjr7FTUjA/AS18TBR/u2pAa8KSsISfNnlJ+NJrQgGhggoqqGSjOpn7IhQQKnccKlQLn6Fu+0oAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">lead_time\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 104 (106.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 69 &le; 737</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 142 (1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">479 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAA/UlEQVRo3u2bwQ3DIAxFS8WO3aGdh+zQKdtTgyMlKRE0z1b/OxHBwU+yAckkvS6xudIBSIAOoJdsP6ZFQTwSHdwWNsy8nLrNoycdZSPhU0gCNBKgkQCNBGgkQCMBGgnQSIBGAjQSoJEAjQRoJEAjARoJ0EiAJm9PlbmT47fZtCvwaTf5bjaFTyEJ0EiAJrxAbllUTG/f25nQJOD5AUL4FAov0JRCFm83pMMC3m5I4VNIAjSHa6Di43jrEPBxvHUIWLjNdZAAt7kOEqicXRnDBc6ujH/eRr9TVt/2j02snwrU0raJta9VDr7fTnb9FORviLvRSkFi3iR8EUuA5g2eyyOnmO8fmgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMDA5EMMAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDBBZKh/AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2016.2 (0.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2015 &le; 2016 &le; 2017</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2015</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">21996</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">18.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2016</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">56707</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">47.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2017</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">40687</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">34.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAyCAQAAABSH4t+AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAjElEQVRYw+2X0Q2AIAxEqWFHh3Ae3cEp9bf4gQXKkTR3f4TACy3tgTwJqQ1KC47LenD9JvKQdoTeNJdTe3XhPXy62Lkjjjji8LhPExtvU3WJbqAd/dcgTVgZzHPOS0IFrcmAelTehtiFQBxxxCU6gqscHcHyXXFzBFvWYxcCccQRh8etNKD5ip07MO4FQucR/6/Xhu0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_month\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. August</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. July</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. May</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. October</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. April</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. June</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. September</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. March</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. February</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. November</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 2 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13877</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12661</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11791</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11160</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11089</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10939</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">9.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10508</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">9794</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8068</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6794</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12709</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABcAAACjCAQAAADLeE1IAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAwUlEQVRYw+3Y0QnDMAxFUSl0x+xQzZPukCmbX8fWSzFRsEyf/wonYIlLWqpf6TlLl36Yv8oPH3eQtwIusjZ4zzsqeRCvIth/cC2rUpeU4s5lNidgU8jbgOtZUu2dHB0WiQ75GD5TkaYXvC6ynSTV3smD+LMBs0jyXEXylUrOIuEkqfZOjs48RZpe8nOR3hyp9k4exIf97DTnaVikf61UiyQP4oOKNPdZUCS6VKpFkgfxeb7kRfhv5z/wO0WOvnsnPwB4iz+0VNKytwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMDA5EMMAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDBBZKh/AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_week_number\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 27.2 (13.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 28 &le; 53</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 22 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">53 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAABEElEQVRo3u2YSw6DMAxEm4o7cof2PHCHnrJs7SAsQj6TkebtsknykO3YpP+Lmzf6AhJAX6CWxS5St2O2U6p9Kw6zmy2Pdylkdatfs33pQ0gCaLrlwDboheyYxDZt2yVtQ4H8G9cURohA/o1HBU1DgWudnkHjoa9C9ALDWomcOGPuFwSYgC8Az/OnQABTZRoKoOpMDH0SSwANvUCYxHPWnQKBUS1xDfQhJAE0EkBDLwBrp2P8CxRNB5MK3H9/6ENIAmgkgMZVIYb2ORSYc2yPoQ8hCaCRABoJoKEXmHQe8Jw6BDPgUAhE/QF9CEkAjQTQSACNBNBIAI0E0NALJNtq7yR/5j5mHkgkd76EPoQkgOYAegsjJsIk1aEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">arrival_date_day_of_month\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 15.8 (8.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 16 &le; 31</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 15 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">31 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAA/UlEQVRo3u2bYQ6CMAxGN7M7cgc9j96BU+ofoyUZdoMtzybf+wOEdPSNNoEM8jPF5kInIAE6gbMUe5AnXOBumuw26AK2b8vhURqTTml5b9cpoq7ANpnWoZfP3toW0CzaLXAsGW8yRhXTpBLypuLsRGACrfT0Q9kL9IceneqXnqIt9dB153bXznsxv/FivL6BSqj9TnqCkMC4dg7/KCEBGgnQSIBGAjQSoJEAjQRoJEAjARoJ0EiARgI0EqCRAI0EaCRAIwGav1wnrmMWBs16ZSCB+sJg+BKSAI0EaCRAIwEaCdBIgCa8QLZf3z2C/A1xNe8DOUjOu4QvIQnQvADhiCwYof4LAAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMDA5EMMAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDBBZKh/AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">stays_in_weekend_nights\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.9 (1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 1 &le; 19</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (1.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">17 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAwklEQVRo3u3bSw6CQBAA0R4zd+QOeh64A6fUjZA2EcW4qOmk3oagLLqSmQ2fdo/aLvQABtAD/Kvnk2XfELdGD/ZJ3rf99a8pIiJWesIflF9CBtAMoBlAM4BmAM0AmgE0A2gG0AygGUAzgGYAzQCaATQDaOUD+vuf5yJPyw4Dpudx/Kdl5ZeQATQDaAbQDKAZQDOAZgDNAJoBNANo/dxlc3rbd6wbLV8DttFHvdHS8ovUS5GvIa5pDbQiMx8qv4kNoD0ABwoRJ2Mt7BUAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">stays_in_week_nights\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.5 (1.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 50</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.8)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAzUlEQVRo3u3bvQ3CMBgGYRt5R+8A85AdMiUUobAQMUEUl1e6p+On+I7YQiGhPkq2Cz2AAfQA/2rjg+W1IW6VHmtu3LdvR6CXTk/3o/glZADNAJoBNANoBtAMoBlAM4BmAM0AmgE0A2gG0AygGUCLD2ifnryHXKnZDdiu0qz0bIfELyEDaAbQDKAZQDOAZgAtPqDNXtzOC859VjA9Agn3b8UvIQNoBtAMoLXvbzn319mBgF5KWU/7a10db6ReQv4NcR0+xBoy8674TWwA7QkBbRPvXLCQJwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMDA5EMMAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDBBZKh/AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">adults\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1.9 (0.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 55</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (0.3)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">14 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAnklEQVRo3u3bsQ3CMBBAUYyyI0MwD+zAlNA6gSISxUuk/zorzX3J6c7jfTm3qx6gAD3Av5b58Pz6Ie5DD/jLPOay/nRbnV560h1Of4UK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQCtAK0ArQNrvT223pxzHfR0wr6eOYE+53+itUgPYBnFoIzZpXvxoAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">children\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 10</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (3.8)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">110796</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">92.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">4861</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3652</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">76</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABOCAQAAAB1N9v1AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAzElEQVRo3u3aQQqCUBRG4XejPbqHWo/twVXWpMF7hREKHn4538yJ3MNTvET1bNku9AAG0APsde0vHiEvxK1WAlqb6Nn+sAxX8Y+QATQDaAbQDKB9fImXbXcBVb/+1ObbHKuf+VyP0PxOu6ccRfs6gSliH/0RkMcAmgE0A2gG0OIDXKcJ/cxuo7T4l9gAmgE0A2gG0OID3EYJp/pxdwiYQ/5qsBqQyACaATQDaAbQDKC5jdLcRmkG0AygGUAzgGYALT6gAve3QfwJGEB7AcFyGB4o2EV1AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwMDkQwwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMEFkqH8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">4\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">babies\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0 (0.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 10</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (12.3)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">118473</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">99.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">900</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">15</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">9</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">10</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGYAAABOCAQAAAB4KauyAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAvElEQVRo3u3XsQ2EMBAAQR/6Hunh++F7oEpI7ZcIIPHesZM5sbzCSOc4Wh3L7AMY84aYT7/4JfyBvnER09o6+2w37cOq1DUzhsoYKmOojKH6mwD2Z7tARD+OxeNt5unPX+qaDTFbwqn5MiY7Y6iMoTKGyhgqY6hKxdR9Ajg1gxhDZQyVMVTGUBlDVSqm7tScnU8AKmOojKEyhsoYKmOonJqpnJqpjKEyhsoYKmOojKEqFRPJZ8tBqS9jDNUJk1kUkAOXFDYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">meal\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. BB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. FB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. HB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. SC</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">92310</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">77.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">798</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14463</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10650</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1169</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFIAAABOCAQAAAAZMYnwAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAA0UlEQVRo3u3ZwQ3CMBBEUS9Kj/QA9UAPqRIuHGwLiygx7Iz4/5ZL9BRb8sqJR9HvlA0A+cuW+uEutEEvMUCWcs62vVqbJ4vlBglSLZAg1epOnHXfW75c1Md17H7N/GqXxXI3yJvQFDREqgYSpFogQaoF8q+QFqNaM/SOpqBrsn7DXVD+tG6xJ0GCVAskSLUskFxYHcnuwurDqJY9pL1B9qOayg61WG6QINUCCVItpqAj2U1B3W87zR93fl9SNZAg1QIJUi2QswrJiaLL4kuCnNUTjcEaWsVSh8gAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">country\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. PRT</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. GBR</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. FRA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. ESP</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. DEU</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. ITA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. IRL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. BEL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. BRA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. NLD</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 168 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">48590</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">40.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12129</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10415</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8568</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">7.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7287</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3766</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3375</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2342</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2224</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2104</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">18590</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADEAAACjCAQAAACJOz7fAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAABDklEQVRo3u2byw3DIBAFTZQe3UNSD+nBVTpXYr7CCxFP825cGMGuRjbY7txG5zGcIIJ4hoOPWWFeLoPYtt0EcPyMNGoBAgSIOBeBHH2zFONC87nuaa4JZ529UT4h8/ftpVVkblEbjaYFAWI5BKZtTMW09z1bMa1NZTSaFgSI5RCYtjEF01pYNkKEprWrikbTggABIo6GzLOmtfJs1rSWG6bRUSBAgIijYdp/PTbbiTyxit3oZq+AGBEQIEDEwbSNSZjW1rMJ09pHo2lBgFgdgWlzwbQgQIBYCKEgc3/6AR9sS5YbBAgQMghMCwIECBCjI3tAkUvvwUXzz3T9bx4aHQUCxHKI2ZduY6JRiwmIL6XnPPixWbQYAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwMDkQwwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMEFkqH8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">market_segment\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Aviation</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Complementary</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Corporate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Direct</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Groups</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Offline TA/TO</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Online TA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">237</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">743</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5295</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12606</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">19811</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">16.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">24219</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">20.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">56477</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">47.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAB4CAQAAAD83KJ0AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAA5ElEQVRo3u3byw2DMBCE4XGUHlNE6kkRqZIcfGCJQMSxd4HVPxw5fMKvkRCUSZG5hWrJOU3merlMpBVyDyYcHFx6rthjsrgQVjhyMH0aYZMLfjo4ODi4q3HBBXS3N+ZGePrIS056SJLePpayLxU4OLh47usQ8zu+as7RCHPGdsNqI8wZPbi5VyYcHFw8l7sRjhzMvZdU/WW0U0A2I+Y190aAg4MTjTA0TY1Q09MLDY1Q0ze7uTcCHBxcPJe7gP5ohPZH2uB+aYTWLKcn98qEg4OL53I3Ap82wcHBwZ2WK/xLclnuA3H1M43ux6laAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwMDkQwwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMEFkqH8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">distribution_channel\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Corporate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Direct</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. GDS</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. TA/TO</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Undefined</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6677</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14645</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">193</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">97870</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">82.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">5</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFYAAABOCAQAAAAQ2imKAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAyUlEQVRo3u3YTQqDMBCGYSO5o4fwPHoHT6kLf5iIgSwMMx+876aUbh7aKRmT9kGn0RsANkLZvlnNAM/Jm3Zm/1O5/Gi6Xjdv42dSYwAWLFiwYPv2OsFinlx3yZ69QdaBIuvTHYOl8tgQZQOrbF22OHMsNQZgwYIFCxbsEyvin1VXxCX4Za3UzIIFCxYsWLBgu6e7dUWv6WLONfNzN1zMeVY+uUiNAViwYMGC7Rt3XX8mu3VxMQcWLFiwYMGClcWm4LtLkdQ3C7ZXB8BNGVt+RHUgAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwMDkQwwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMEFkqH8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">is_repeated_guest\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">115580</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">96.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3810</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGMAAAAjCAQAAAAqanxyAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAhklEQVRYw+2WsQ2AMAwEbcSO2QHmgR0yJTQUIQiE0vj9+uvcWD7Zlt4PY2CKHkAafBpzW+ypHmXxFw2zEj3bb+qtIjkqaSAhDSSkgYQ0kCDR6MJIHesSjrdp0IfbRNBOznhU2yW45lqLPbZREkX1D42sSAMJaSAhDSSkgQRjws0LyVFJA4kTTuULS0ZN1/wAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDAwORDDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwQWSofwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">previous_cancellations\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 26</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (9.7)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">15 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAAn0lEQVRo3u3bwQnCQBBAUVfSo0VYj/ZglXqTjRAIeHgJ/HdKyGU+7N4m4305t6seoAA9wL+W+eW5uhD3oYfbMo+5rD/dvk8vPeVOpz9CBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaAVoBWgFaD+70/PG9OO4/0ZMa+njuFPuc/ojVID2Aab+CM3x0/HFAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwMDkQwwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMEFkqH8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">previous_bookings_not_canceled\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (1.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 72</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (10.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">73 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAAApklEQVRo3u3bsQ2AIBQAUTHs6BDOozs4pXYEoiQai+Mn9yoNzT8DHaZzim2mBzCAHuCvXL/szYFYEz1cTz1mbpeW8nTQU74UfgsZQDOAZgDNAJoBNANoBtAMoBlAM4BmAM0AmgE0A2gG0AygGUAzgGYAzQCaATQDaAbQDKAZQDOAZgDNAFr4gNxf2soV5XFvUd8Cnm9Mb6P9JVF90DTabF+FPwMG0C5xkQrPBJiq2AAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMDA5EMMAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTEtMjVUMDg6MTA6MDkrMDA6MDBBZKh/AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reserved_room_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. B</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. C</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. D</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. E</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. G</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. H</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. L</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. P</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">85994</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">72.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1118</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">932</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">19201</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">16.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6535</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2897</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2094</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">601</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAE0AAACVCAQAAAC3bb95AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAABF0lEQVR42u3aQQ7CIBAF0GK8o3fQ89Q7eEpduLA0tjYThal5f9dN8wIk/ADlPmTNoTcA7bs5Tj+u3RfeuSzQhuHUFXarvhJPKBoaGhpas8w2qlvsLz9Jme7oJfybb2WqqSZ0vI/du8cCLVfQ0NDQ0NBS0/bSPHJlVop6cxZpuYKGhoaGhqZ5xFIdYq03j0vjQd18EdT+5C3xhKKhoaH9G81ty9bsvXm07hkfaK/mkWHNJZ5QNDQ0NLRmUYq2Zqp50zz6d45nZmut7+PXVVqmoKGhoaH1omkei9nJcYx3uWhoaGhoaLFoHpF4/IqGhoaGhhaL5hGJ5oGGhoaGhvZ3tL2UIs0DDS1Z0NDQ0EIpqXb0KolHDS2SB/kLL8QTU5AMAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwMDkQwwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMEFkqH8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">assigned_room_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. D</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. E</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. G</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. C</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. B</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. H</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. I</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. K</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 2 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74053</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">62.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">25322</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">21.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7806</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3751</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2553</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2375</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2163</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">712</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">363</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">279</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEQAAACjCAQAAACZW3ADAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgnbKHqtAAABIElEQVR42u3cS47CMBAFwPZo7sgdmPPAHTgls2ATLD5RiO3GqrfLJpTSVl4LIco1cuRnNADkWX6XF+fOB+ZYnkAiDh0Zl7urNKMBAQEBmQZSveIv2+6yQ8qy58rm22zL8rNzjua0cg34a/DoNqwBbc5RmtGAgICAfBrtG/F97duiY1dClu3b+7SkGQ0ICAjIp9G+Ed/Uvn1795bqiRy6fgn+AjIuICAgINNArAER92vAg/Yd0b0P2ndU0hxWEBAQkFkh2jfPaKwBbyDjAgICArIzRPsmHc3puvYHYI0hIwMCAgICsne0b52qfZNARgYEBAQEZFpIzjVA+4KAgICAzAzRvnXSjAYEBAQEZFpIzvYdGWsACAgICEjrFH+LCvIm/3opNRNCgp/dAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjA5KzAwOjAwMDkQwwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDowOSswMDowMEFkqH8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">booking_changes\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.2 (0.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 21</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (2.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">21 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAAsklEQVRo3u3bsQ2EMBAAwfPLPdIDXw/0QJWQAPK/AAkRLCftZEByi+zMLnPk9qEHMIAe4KnaPoz7hvgWerAr7b6tv5+6iIiY6AlvSL+EDKAZQDOAZgDNAJoBNANoBtAMoBlAM4BmAM0AmgE0A2gG0AygGUAzgGYAzQCaATQDaAbQDKAZQDOAZgCtHr8e1tO97z6CfBGwHUEe/q4XvC+otBOOSW5D9M1vLElmPpV+ExtAWwDtkw6P7dty4wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMS0yNVQwODoxMDoxMCswMDowMGkLVY4AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTEtMjVUMDg6MTA6MTArMDA6MDAYVu0yAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">deposit_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. No Deposit</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Non Refund</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Refundable</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">104641</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">87.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">14587</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">12.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">162</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFsAAAAyCAQAAACZxG+AAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAAmklEQVRo3u3YQQqAIBBGYSe6Y3eo89gdPGVtNZBCSP+R93Zu5KMGGrIreGwZDYCt35ofTulB363CDmEbbauWipPTIYENG7ZUsGHPyn583FPbLd2zfHuy5mt6lEtnGJJYWVwPudfwYXFVnHenQwIbNmypYMN+jQ3w7ybYAAt2lP51WWX7CTZs2FLBhg1bKqdsc7M9FTl92rB7dgOdxw9P8zuHywAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMS0yNVQwODoxMDoxMCswMDowMGkLVY4AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTEtMjVUMDg6MTA6MTArMDA6MDAYVu0yAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">agent\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 9</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. NULL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 240</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 14</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 7</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 6</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 250</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 241</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 28</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 324 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">31961</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">26.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">16340</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">13.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13922</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">11.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7191</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3640</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3539</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3290</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2870</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1721</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1666</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">33250</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">27.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACYAAACjCAQAAABMSaROAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAA+ElEQVRo3u3aUQ6CMBBFUWrYI4tgPXUPrBJ/NLbQMTMtNdNw358xnNihvIAa9um6PC60HGNz+uJpHuAa0kPm/M3FRG09lwkGNhx2uJy2OuWd7EINFUB6fL9lRrGCVtWHVlWQdpJ+twYYmBBa4xNdY5ywUmtYpuh3a4CBCbl7a+i7QsC+rVE3O79bAwzsH5jfCiq2Rk1jTNNpZovxa5KfWFvAwIbD/LZG7xuX2gIqVFBL/G4NMDAdRmsoQmuAgSWhNRShNcDAemFeKyjusenPOMOcADCwm2G0BhgYmC1DPe5Y1yZg9sed/H7O79kEAxPS7wcZV8v0i70AF2c84K6FJZMAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MTArMDA6MDBpC1WOAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjEwKzAwOjAwGFbtMgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">company\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. NULL</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 40</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 223</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 67</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 45</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 153</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 174</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 219</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 281</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 154</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 343 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">112593</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">927</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">784</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">267</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">250</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">215</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">149</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">141</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">138</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">133</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3793</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGEAAACjCAQAAAAwL7iXAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAABOElEQVR42u3dQUrDUBhG0UTcY/eg69E9dJU6ElKlIh2Y+37OmWUScskLfLPsH9vqns5+AAkzEp6PF+/LfBgv+52Ebbuc/Wx/cr25GnCQJBRIKJBQIKFgQMK3gXF97C6n2o/Lbn/4Nv/t+NQDDtJNwtsyY/tuwpokFEgokFAgoUBCgaVaYKkWSCiQUCChQEKBhAJLtcBSLZBQIKFAQoGEAgkFAxKmjW1LVYKElUkokFAgoUBCwbSluiZju0BCgYQCCQUSCiQUWKoFlmqBhAIJBRIKJBRIKLBUCyzVAgkFEgokFEgokFAwIGHa2LZUJUhYmYQCCQUSCiQUWKoFAw6ShAIJBRIKJBRIKBiQMG2prunmRx5fY/t1ndex/XgLl0V+d/ZLwookFEgokFAgoWDan8LWNOAgSSj4BEfQLG0jOjx0AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjEwKzAwOjAwaQtVjgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDoxMCswMDowMBhW7TIAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">days_in_waiting_list\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.3 (17.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 391</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (7.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">128 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAApUlEQVRo3u3bTQ5AMBQA4VfpHR3CebiDU7KTEvETkdGY2WHzPml3bZqi7hp6AAH0AE/L5cOwbIgu0YMdVe7bvP7URkTESE94o+qXkAA6AXQC6ATQCaATQCeATgCdADoBdALoBNAJoBNAJ4BOAJ0AOgF0AugE0AmgE0AngE4AnQA6AXQC6ATQVQ/I+6/702sFXzldvQFcPzV9Tnyx4uclb3AI+DlgBlQ1Cs90amnoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjEwKzAwOjAwaQtVjgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDoxMCswMDowMBhW7TIAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">customer_type\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Contract</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Group</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Transient</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Transient-Party</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">4076</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">577</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">89613</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">75.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">25124</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">21.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFAAAABACAQAAAAnzji9AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAAtElEQVRo3u2ZwQ2AIBAExdAjRViP9mCV+jEGNPEBkV2SmR+/yd0RNkc4Jm9mtQCCfxPzw3YN5BK0Uvm9eFQwTUnr9sK+xQgiqAZBBNXYC8byuKt9XoT8YRZnhJuPsOBHIbga5v+xKugIggiqQRBBNQi2Yh+3isBqk2aySj0StcPqqEz19jOIIIJqEERQjb0gy6MahloeVcWtnn95FXGr75zatxhBBNUgiKCasdKMI/YtRrCVE0kDFVmlgNVsAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjEwKzAwOjAwaQtVjgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDoxMCswMDowMBhW7TIAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">adr\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 101.8 (50.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">-6.4 &le; 94.6 &le; 5400</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 56.7 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">8879 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAApklEQVRo3u3bUQpAQBRAUU+zR4uwnlmEVfI7o1CUO6/u+SLSu8XfE/uU20wPYAA9wFelPYnuUj19Hms8Pu0n7WDl7salOd7oqS+kf4UMoBlAM4BmAM0AmgE0A2gG0AygGUAzgGYAzQCaATQDaAbQDKAZQDOAZgDNAJoBNANoBtAMoBlAM4BmAC19QLd6XBP+THC7O93vSw+U16yhxzhTvZP+GzCAdgBvwApj46SqIgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMS0yNVQwODoxMDoxMCswMDowMGkLVY4AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTEtMjVUMDg6MTA6MTArMDA6MDAYVu0yAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">required_car_parking_spaces\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.1 (0.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 8</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 0 (3.9)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">111974</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">93.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">7383</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">6.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">28</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">8</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGEAAABOCAQAAACa9bDLAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAAyUlEQVRo3u3YwQnDMAxAUat0x+7QzpPukCnbq1IwhBzqL/HfzZfgT2wiEp9R3W31BkzokXDPi3eZi/GMScIYj9V7O2U/rBocJBMITCAwgcAEgp+v837tKUtFHovi8mP+Le+620HaUtyrzCuZTKqV7kSDg2QCgQkEJhCYQNAgwWF7lemwvZX5p5o1uAsmEJhAYAKBCQQmEDRI6Dap1uSwTWACgQkEJhCYQGACgZMqgZMqgQkEJhCYQGACgQkEDRKi5GR30OAtmEDwBYFgFqucqA7eAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjEwKzAwOjAwaQtVjgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDoxMCswMDowMBhW7TIAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">total_of_special_requests\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 0.6 (0.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 5</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 1 (1.4)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">70318</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">58.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">33226</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">27.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12969</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2497</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">2.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">340</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">40</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">0.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEEAAABcCAQAAACbthCLAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAAy0lEQVRo3u3awQ2DMBBE0d0oPdJDUg/0QJXhQCIZQyLhDd45/Ln5Ak9ei5Es/GXZuWUDIKy5l4up28F4+BeC2dAFMG9WAoOAAAECBEFC9YGe254SipfN5M2POZvyrZtdGBua8hl2B5vyH4MTOI4QIECAIEigKc30BnFc1vE6PkE4KuvrT4fAICBAgAChDk1ppjeItSmvbsY61S70uQD+ScgIBAgQIOgTKOu2C+B49M4CBAgQsgMBwic05Y6QEwgQIECAIEpw/oOG8M4ClU0d4tkGJE0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MTArMDA6MDBpC1WOAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjEwKzAwOjAwGFbtMgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reservation_status\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Canceled</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Check-Out</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. No-Show</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">43017</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">36.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">75166</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">63.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1207</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEUAAAAyCAQAAACgo97bAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAAAkElEQVRYw+3ZYQqAIAyG4RbesUN0HrtDp7RfwQyJZCNHvd+/0PCBiROUMkXJPBoA5T5Jf2zmjbNK33y9YKqHFhNkN/0dqEBQoECB8mHK5eC3Hd22iG5Inb3MIXr1qAXK798uVSFcLwm9qXdmoAJBgQIFinfozGeCduaKksuA3tymjA0UKFCgQPkZRXj5gPIwB/HzEXjyZignAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTExLTI1VDA4OjEwOjEwKzAwOjAwaQtVjgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMS0yNVQwODoxMDoxMCswMDowMBhW7TIAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">reservation_status_date\n[Date]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min : 2014-10-17</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">med : 2016-08-07</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">max : 2017-09-14</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">range : 2y 10m 28d</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">926 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAABGCAQAAACZZFmYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCxkICgpCISsXAAABOklEQVRo3u2aWw6CMBBFwbhH9qDrwT24Sv2QkmoYmaHT3g6550/TYM88WimMryE2F/QEKICeQCnX/MPofPF5abC784Xzvq2cgWmY6v7AdwZaMq9hLMsPTGBYcvMs1GkioOmFpGPtmyYCeay1Yz8i+xpVBGbT9r49elIqOwn81rA15rqRFQUsU7blp5mAhjT1spgDBSyFpSX8f6HwAsCdWMP+tta5wH7XhC+h8AKFJeS7KQEE6qztFsKXEAXQdL4PJOTbmyAZkE83DmdAWkBbL6wFGdiOSv2TIDeBPqAAGgqgoQAaCqChABoKoKEAGgqgoQAaCqChABoKoKEAGgqg+XO87vVaHkxg+wkk/sGqQUCvheNcPSBVfW9lIwpI5ZG+9XxV7AhrILPwjnlwHx1HOucmCUQkfBNTAM0bGapAMig/FXoAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTEtMjVUMDg6MTA6MTArMDA6MDBpC1WOAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTExLTI1VDA4OjEwOjEwKzAwOjAwGFbtMgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.1.1)<br/>2022-11-25</p>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check for missing/null data in the hotel_data\nsum(is.na(hotel_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n\n```{.r .cell-code}\nsum(is.null(hotel_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Check for the period of hotel booking dates\nhotel_data%>%\n  select(hotel, arrival_date_year, arrival_date_month)%>%distinct()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 3\n   hotel        arrival_date_year arrival_date_month\n   <chr>                    <dbl> <chr>             \n 1 Resort Hotel              2015 July              \n 2 Resort Hotel              2015 August            \n 3 Resort Hotel              2015 September         \n 4 Resort Hotel              2015 October           \n 5 Resort Hotel              2015 November          \n 6 Resort Hotel              2015 December          \n 7 Resort Hotel              2016 January           \n 8 Resort Hotel              2016 February          \n 9 Resort Hotel              2016 March             \n10 Resort Hotel              2016 April             \n# … with 42 more rows\n```\n:::\n:::\n\n\n\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the total number of adults, children and babies who stayed in the hotels\n\nhotel_data%>%\n  select(hotel, adults, children, babies)%>%\n  summarise(total = sum(adults+children+babies, na.rm = TRUE), total_adults = sum(adults), total_children = sum(children, na.rm = TRUE), total_babies = sum(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n   total total_adults total_children total_babies\n   <dbl>        <dbl>          <dbl>        <dbl>\n1 234979       221636          12403          949\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the total number of adults, children and babies for each hotel\n\nhotel_data%>%\n  select(hotel, adults, children, babies)%>%\n  group_by(hotel)%>%\n  summarise(total = sum(adults+children+babies, na.rm = TRUE), total_adults = sum(adults), total_children = sum(children, na.rm = TRUE), total_babies = sum(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  hotel         total total_adults total_children total_babies\n  <chr>         <dbl>        <dbl>          <dbl>        <dbl>\n1 City Hotel   154469       146838           7248          392\n2 Resort Hotel  80510        74798           5155          557\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the total number of adults, children and babies for each hotel, year\n\nhotel_data%>%\n  select(hotel, arrival_date_year, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year)%>%\n  summarise(total = sum(adults+children+babies, na.rm = TRUE), total_adults = sum(adults), total_children = sum(children, na.rm = TRUE), total_babies = sum(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n# Groups:   hotel [2]\n  hotel        arrival_date_year total total_adults total_children total_babies\n  <chr>                    <dbl> <dbl>        <dbl>          <dbl>        <dbl>\n1 City Hotel                2015 24972        24385            512           84\n2 City Hotel                2016 74577        70568           3814          195\n3 City Hotel                2017 54920        51885           2922          113\n4 Resort Hotel              2015 16861        15877            845          139\n5 Resort Hotel              2016 36758        34396           2094          268\n6 Resort Hotel              2017 26891        24525           2216          150\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the total number of adults, children and babies for each hotel, year, month\n\nhotel_data%>%\n  select(hotel, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year, arrival_date_month)%>%\n  summarise(total = sum(adults+children+babies, na.rm = TRUE), total_adults = sum(adults), total_children = sum(children, na.rm = TRUE), total_babies = sum(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 7\n# Groups:   hotel, arrival_date_year [6]\n   hotel      arrival_date_year arrival_date_month total total…¹ total…² total…³\n   <chr>                  <dbl> <chr>              <dbl>   <dbl>   <dbl>   <dbl>\n 1 City Hotel              2015 August              4869    4697     165      16\n 2 City Hotel              2015 December            3050    2907     120      23\n 3 City Hotel              2015 July                2687    2671      14       2\n 4 City Hotel              2015 November            1951    1918      25       8\n 5 City Hotel              2015 October             6029    5910      98      21\n 6 City Hotel              2015 September           6386    6282      90      14\n 7 City Hotel              2016 April               7021    6671     339      11\n 8 City Hotel              2016 August              7660    6904     730      26\n 9 City Hotel              2016 December            5095    4702     378      15\n10 City Hotel              2016 February            4331    4124     194      13\n# … with 42 more rows, and abbreviated variable names ¹​total_adults,\n#   ²​total_children, ³​total_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the total number of adults, children and babies for each hotel, year for the July month\n\nhotel_data%>%\n  select(hotel, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  filter(arrival_date_month=='July')%>%\n  group_by(hotel, arrival_date_year, arrival_date_month)%>%\n  summarise(total = sum(adults+children+babies, na.rm = TRUE), total_adults = sum(adults), total_children = sum(children, na.rm = TRUE), total_babies = sum(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n# Groups:   hotel, arrival_date_year [6]\n  hotel        arrival_date_year arrival_date_mo…¹ total total…² total…³ total…⁴\n  <chr>                    <dbl> <chr>             <dbl>   <dbl>   <dbl>   <dbl>\n1 City Hotel                2015 July               2687    2671      14       2\n2 City Hotel                2016 July               6857    6231     605      21\n3 City Hotel                2017 July               7659    7073     574      12\n4 Resort Hotel              2015 July               3028    2752     252      24\n5 Resort Hotel              2016 July               3244    2887     319      38\n6 Resort Hotel              2017 July               4132    3550     558      24\n# … with abbreviated variable names ¹​arrival_date_month, ²​total_adults,\n#   ³​total_children, ⁴​total_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the total number of adults, children and babies for each hotel, year for the August month\n\nhotel_data%>%\n  select(hotel, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  filter(arrival_date_month=='August')%>%\n  group_by(hotel, arrival_date_year, arrival_date_month)%>%\n  summarise(total = sum(adults+children+babies, na.rm = TRUE), total_adults = sum(adults), total_children = sum(children, na.rm = TRUE), total_babies = sum(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n# Groups:   hotel, arrival_date_year [6]\n  hotel        arrival_date_year arrival_date_mo…¹ total total…² total…³ total…⁴\n  <chr>                    <dbl> <chr>             <dbl>   <dbl>   <dbl>   <dbl>\n1 City Hotel                2015 August             4869    4697     165      16\n2 City Hotel                2016 August             7660    6904     730      26\n3 City Hotel                2017 August             6863    6240     604      19\n4 Resort Hotel              2015 August             3162    2848     263      51\n5 Resort Hotel              2016 August             3940    3447     438      55\n6 Resort Hotel              2017 August             4268    3659     580      29\n# … with abbreviated variable names ¹​arrival_date_month, ²​total_adults,\n#   ³​total_children, ⁴​total_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the total number of adults, children and babies for year 2016 for each month\n\nhotel_data%>%\n  select(hotel, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  filter(hotel=='City Hotel' & arrival_date_year==2016)%>%\n  group_by(arrival_date_year, arrival_date_month)%>%\n  summarise(total = sum(adults, children, babies), total_adults = sum(adults), total_children = sum(children, na.rm = TRUE), total_babies = sum(babies))%>%\n  arrange(match(arrival_date_month,month.name))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 6\n# Groups:   arrival_date_year [1]\n   arrival_date_year arrival_date_month total total_adults total_child…¹ total…²\n               <dbl> <chr>              <dbl>        <dbl>         <dbl>   <dbl>\n 1              2016 January             2285         2200            69      16\n 2              2016 February            4331         4124           194      13\n 3              2016 March               5893         5599           279      15\n 4              2016 April               7021         6671           339      11\n 5              2016 May                 6932         6671           254       7\n 6              2016 June                7251         7012           222      17\n 7              2016 July                6857         6231           605      21\n 8              2016 August              7660         6904           730      26\n 9              2016 September           7575         7287           261      27\n10              2016 October             8104         7755           336      13\n11              2016 November            5573         5412           147      14\n12              2016 December            5095         4702           378      15\n# … with abbreviated variable names ¹​total_children, ²​total_babies\n```\n:::\n:::\n\n\nFrom the above statistics, we can see that most people have stayed in Portugal hotels during Fall (September and October) and during August (summer break for children).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the mean of adr, adults, children and babies for each hotel\n\nhotel_data%>%\n  select(hotel, adr, adults, children, babies)%>%\n  group_by(hotel)%>%\n  summarise(avg_adr = mean(adr), avg_total = mean(adults+children+babies, na.rm = TRUE), avg_adults = mean(adults), avg_children = mean(children, na.rm = TRUE), avg_babies = mean(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 6\n  hotel        avg_adr avg_total avg_adults avg_children avg_babies\n  <chr>          <dbl>     <dbl>      <dbl>        <dbl>      <dbl>\n1 City Hotel     105.       1.95       1.85       0.0914    0.00494\n2 Resort Hotel    95.0      2.01       1.87       0.129     0.0139 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the median of adr, adults, children and babies for each hotel\n\nhotel_data%>%\n  select(hotel, adr, adults, children, babies)%>%\n  group_by(hotel)%>%\n  summarise(median_adr = median(adr), median_adults = median(adults), median_children = median(children, na.rm = TRUE), median_babies = median(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  hotel        median_adr median_adults median_children median_babies\n  <chr>             <dbl>         <dbl>           <dbl>         <dbl>\n1 City Hotel         99.9             2               0             0\n2 Resort Hotel       75               2               0             0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the sd of adr, adults, children and babies for each hotel\n\nhotel_data%>%\n  select(hotel, adr, adults, children, babies)%>%\n  group_by(hotel)%>%\n  summarise(sd_adr = sd(adr), sd_adults = sd(adults), sd_children = sd(children, na.rm = TRUE), sd_babies = sd(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  hotel        sd_adr sd_adults sd_children sd_babies\n  <chr>         <dbl>     <dbl>       <dbl>     <dbl>\n1 City Hotel     43.6     0.509       0.372    0.0843\n2 Resort Hotel   61.4     0.697       0.445    0.119 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the mean of adr, adults, children and babies for each hotel, year\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year)%>%\n  summarise(avg_adr = mean(adr), avg_adults = mean(adults), avg_children = mean(children, na.rm = TRUE), avg_babies = mean(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n# Groups:   hotel [2]\n  hotel        arrival_date_year avg_adr avg_adults avg_children avg_babies\n  <chr>                    <dbl>   <dbl>      <dbl>        <dbl>      <dbl>\n1 City Hotel                2015    85.9       1.78       0.0374    0.00614\n2 City Hotel                2016   103.        1.85       0.100     0.00511\n3 City Hotel                2017   118.        1.89       0.106     0.00411\n4 Resort Hotel              2015    89.4       1.91       0.102     0.0167 \n5 Resort Hotel              2016    87.7       1.85       0.113     0.0144 \n6 Resort Hotel              2017   109.        1.86       0.168     0.0114 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the median of adr, adults, children and babies for each hotel, year\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year)%>%\n  summarise(median_adr = median(adr),  median_adults = median(adults), median_children = median(children, na.rm = TRUE), median_babies = median(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n# Groups:   hotel [2]\n  hotel        arrival_date_year median_adr median_adults median_child…¹ media…²\n  <chr>                    <dbl>      <dbl>         <dbl>          <dbl>   <dbl>\n1 City Hotel                2015       80               2              0       0\n2 City Hotel                2016       99               2              0       0\n3 City Hotel                2017      110               2              0       0\n4 Resort Hotel              2015       75               2              0       0\n5 Resort Hotel              2016       70               2              0       0\n6 Resort Hotel              2017       86.2             2              0       0\n# … with abbreviated variable names ¹​median_children, ²​median_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the sd of adr, adults, children and babies for each hotel, year\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year)%>%\n  summarise(sd_adr = sd(adr), sd_adults = sd(adults), sd_children = sd(children, na.rm = TRUE), sd_babies = sd(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n# Groups:   hotel [2]\n  hotel        arrival_date_year sd_adr sd_adults sd_children sd_babies\n  <chr>                    <dbl>  <dbl>     <dbl>       <dbl>     <dbl>\n1 City Hotel                2015   34.3     0.452       0.250    0.107 \n2 City Hotel                2016   45.2     0.520       0.387    0.0875\n3 City Hotel                2017   41.6     0.518       0.399    0.0651\n4 Resort Hotel              2015   53.8     1.25        0.406    0.130 \n5 Resort Hotel              2016   57.1     0.450       0.416    0.121 \n6 Resort Hotel              2017   69.1     0.448       0.502    0.108 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the max of adr, adults, children and babies for each hotel, year\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year)%>%\n  summarise(max_adr = max(adr), max_adults = max(adults), max_children = max(children, na.rm = TRUE), max_babies = max(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n# Groups:   hotel [2]\n  hotel        arrival_date_year max_adr max_adults max_children max_babies\n  <chr>                    <dbl>   <dbl>      <dbl>        <dbl>      <dbl>\n1 City Hotel                2015     290          3            3          9\n2 City Hotel                2016    5400          4            3         10\n3 City Hotel                2017     510          4            3          2\n4 Resort Hotel              2015     508         55           10          2\n5 Resort Hotel              2016     384          4            3          2\n6 Resort Hotel              2017     450          4            3          2\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the min of adr, adults, children and babies for each hotel, year\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year)%>%\n  summarise(min_adr = min(adr), min_total = min(adults+children+babies, na.rm = TRUE), min_adults = min(adults), min_children = min(children, na.rm = TRUE), min_babies = min(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n# Groups:   hotel [2]\n  hotel        arrival_date_year min_adr min_total min_adults min_chil…¹ min_b…²\n  <chr>                    <dbl>   <dbl>     <dbl>      <dbl>      <dbl>   <dbl>\n1 City Hotel                2015    0            0          0          0       0\n2 City Hotel                2016    0            0          0          0       0\n3 City Hotel                2017    0            0          0          0       0\n4 Resort Hotel              2015    0            0          0          0       0\n5 Resort Hotel              2016    0            0          0          0       0\n6 Resort Hotel              2017   -6.38         0          0          0       0\n# … with abbreviated variable names ¹​min_children, ²​min_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the mean of adr, adults, children and babies for each hotel, year, month\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year, arrival_date_month)%>%\n  summarise(avg_adr = mean(adr), avg_adults = mean(adults), avg_children = mean(children, na.rm = TRUE), avg_babies = mean(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 7\n# Groups:   hotel, arrival_date_year [6]\n   hotel      arrival_date_year arrival_date_m…¹ avg_adr avg_a…² avg_c…³ avg_b…⁴\n   <chr>                  <dbl> <chr>              <dbl>   <dbl>   <dbl>   <dbl>\n 1 City Hotel              2015 August              77.7    1.89  0.0666 0.00645\n 2 City Hotel              2015 December            81.1    1.76  0.0726 0.0139 \n 3 City Hotel              2015 July                69.8    1.91  0.0100 0.00143\n 4 City Hotel              2015 November            73.5    1.55  0.0202 0.00648\n 5 City Hotel              2015 October             89.4    1.75  0.0289 0.00620\n 6 City Hotel              2015 September          101.     1.78  0.0255 0.00397\n 7 City Hotel              2016 April               99.5    1.87  0.0952 0.00309\n 8 City Hotel              2016 August             119.     2.04  0.216  0.00770\n 9 City Hotel              2016 December            94.0    1.90  0.153  0.00605\n10 City Hotel              2016 February            80.0    1.74  0.0818 0.00548\n# … with 42 more rows, and abbreviated variable names ¹​arrival_date_month,\n#   ²​avg_adults, ³​avg_children, ⁴​avg_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the median of adr, adults, children and babies for each hotel, year, month\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year, arrival_date_month)%>%\n  summarise(median_adr = median(adr),  median_adults = median(adults), median_children = median(children, na.rm = TRUE), median_babies = median(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 7\n# Groups:   hotel, arrival_date_year [6]\n   hotel      arrival_date_year arrival_date_m…¹ media…² media…³ media…⁴ media…⁵\n   <chr>                  <dbl> <chr>              <dbl>   <dbl>   <dbl>   <dbl>\n 1 City Hotel              2015 August              75         2       0       0\n 2 City Hotel              2015 December            77.4       2       0       0\n 3 City Hotel              2015 July                62.8       2       0       0\n 4 City Hotel              2015 November            72.2       2       0       0\n 5 City Hotel              2015 October             87.8       2       0       0\n 6 City Hotel              2015 September           95         2       0       0\n 7 City Hotel              2016 April               96.3       2       0       0\n 8 City Hotel              2016 August             115.        2       0       0\n 9 City Hotel              2016 December            88         2       0       0\n10 City Hotel              2016 February            79         2       0       0\n# … with 42 more rows, and abbreviated variable names ¹​arrival_date_month,\n#   ²​median_adr, ³​median_adults, ⁴​median_children, ⁵​median_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the sd of adr, adults, children and babies for each hotel, year, month\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year, arrival_date_month)%>%\n  summarise(sd_adr = sd(adr), sd_adults = sd(adults), sd_children = sd(children, na.rm = TRUE), sd_babies = sd(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 7\n# Groups:   hotel, arrival_date_year [6]\n   hotel      arrival_date_year arrival_date_mo…¹ sd_adr sd_ad…² sd_ch…³ sd_ba…⁴\n   <chr>                  <dbl> <chr>              <dbl>   <dbl>   <dbl>   <dbl>\n 1 City Hotel              2015 August              26.9   0.365   0.340  0.0801\n 2 City Hotel              2015 December            32.1   0.504   0.340  0.117 \n 3 City Hotel              2015 July                19.4   0.365   0.107  0.0378\n 4 City Hotel              2015 November            20.7   0.512   0.177  0.0803\n 5 City Hotel              2015 October             30.7   0.463   0.221  0.166 \n 6 City Hotel              2015 September           43.7   0.440   0.209  0.0629\n 7 City Hotel              2016 April               30.5   0.478   0.381  0.0555\n 8 City Hotel              2016 August              39.8   0.499   0.544  0.0874\n 9 City Hotel              2016 December            36.0   0.538   0.466  0.0776\n10 City Hotel              2016 February            24.7   0.535   0.355  0.0845\n# … with 42 more rows, and abbreviated variable names ¹​arrival_date_month,\n#   ²​sd_adults, ³​sd_children, ⁴​sd_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the max of adr, adults, children and babies for each hotel, year, month\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year, arrival_date_month)%>%\n  summarise(max_adr = max(adr), max_adults = max(adults), max_children = max(children, na.rm = TRUE), max_babies = max(babies))%>%\n  arrange(desc(max_adr))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 7\n# Groups:   hotel, arrival_date_year [6]\n   hotel        arrival_date_year arrival_date…¹ max_adr max_a…² max_c…³ max_b…⁴\n   <chr>                    <dbl> <chr>            <dbl>   <dbl>   <dbl>   <dbl>\n 1 City Hotel                2016 March            5400        3       2       1\n 2 City Hotel                2017 May               510        4       3       1\n 3 Resort Hotel              2015 July              508        4      10       2\n 4 City Hotel                2016 December          452.       4       3       1\n 5 Resort Hotel              2017 August            450        4       3       2\n 6 Resort Hotel              2017 July              397.       4       2       1\n 7 Resort Hotel              2016 December          384        3       3       2\n 8 City Hotel                2017 August            372.       4       3       1\n 9 Resort Hotel              2016 August            369        4       3       1\n10 City Hotel                2016 July              365        4       3       2\n# … with 42 more rows, and abbreviated variable names ¹​arrival_date_month,\n#   ²​max_adults, ³​max_children, ⁴​max_babies\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding the min of adr, adults, children and babies for each hotel, year, month\n\nhotel_data%>%\n  select(hotel, adr, arrival_date_year, arrival_date_month, adults, children, babies)%>%\n  group_by(hotel, arrival_date_year, arrival_date_month)%>%\n  summarise(min_adr = min(adr), min_total = min(adults+children+babies, na.rm = TRUE), min_adults = min(adults), min_children = min(children, na.rm = TRUE), min_babies = min(babies))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 8\n# Groups:   hotel, arrival_date_year [6]\n   hotel      arrival_date_year arriva…¹ min_adr min_t…² min_a…³ min_c…⁴ min_b…⁵\n   <chr>                  <dbl> <chr>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n 1 City Hotel              2015 August         0       0       0       0       0\n 2 City Hotel              2015 December       0       0       0       0       0\n 3 City Hotel              2015 July           0       0       0       0       0\n 4 City Hotel              2015 November       0       0       0       0       0\n 5 City Hotel              2015 October        0       0       0       0       0\n 6 City Hotel              2015 Septemb…       0       0       0       0       0\n 7 City Hotel              2016 April          0       0       0       0       0\n 8 City Hotel              2016 August         0       0       0       0       0\n 9 City Hotel              2016 December       0       0       0       0       0\n10 City Hotel              2016 February       0       0       0       0       0\n# … with 42 more rows, and abbreviated variable names ¹​arrival_date_month,\n#   ²​min_total, ³​min_adults, ⁴​min_children, ⁵​min_babies\n```\n:::\n:::\n\n\n\n\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\n\nA total of 221636 adults, 12403 children and 949 babies stayed in both hotels from July 2015 - August 2017. I grouped by “hotel” to find the total number of “adults”, “children” and “babies” that stayed in the (i) city hotel as 146838, 7248, 392 and (ii) resort hotel as 74798, 5155, 557 respectively. Looking at the group by “hotel”, we can find that families with babies prefer to stay at resort hotel compared to city hotel. This may be due to the fact that resort hotels are generally closer to the beach or has swimming pool and fun outdoor activities for babies. City hotels are preferred more by adults traveling alone without kids. City hotel may be more suitable for people traveling for business purposes. I also find the mean, median, and sd for the “adr”, “adults”, “children” and “babies” grouped by “hotel”. The difference between the mean and median values are almost similar indicating that the data is not skewed. The average “adr” for City Hotel is more than the Resort Hotel which makes sense as city hotels are usually located in central locations making transportation easier. \n\nNext, I grouped by “hotel”, “arrival_date_year” to find the total number of “adults”, “children” and “babies” that stayed in the city hotel and resort hotel for years 2015, 2016 and 2017. I also find the mean, median, sd, max, and min for the “adr”, “adults”, “children” and “babies” grouped by “hotel” and “arrival_date_year”. We do not interpret anything new from the mean, median and sd. From the max, we identify few interesting bookings where the maximum number of “adults” is 55 / max “children” is 10 in resort hotel for the year 2015 and max “babies” is 9 / max “babies” is 10 for city hotel in years 2015 and 2016 respectively. The min values are mostly 0s except for the year 2017 in resort hotel where the min “adr” is -6.38. Having a negative “adr” is unusual and needs to be investigated further. \n\nFinally, I grouped by “hotel”, “arrival_date_year”, ”arrival_date_month” to find the total number of “adults”, “children” and “babies” that stayed in the city hotel and resort hotel for July 2015 - August 2017. For the city hotel, the months September and October had the highest number of people as this is the best time to visit Portugal during Fall when the weather is warm and the crowd is relatively less compared to Summer. For the resort hotel, August month had the highest number of people (children and babies in particular) as this is the best time to stay in resort during Summer and enjoy outdoor activities. Hence, hotel management can price the rooms accordingly during peak season and off-season. I also find the mean, median, sd, max, and min for the “adr”, “adults”, “children” and “babies” grouped by “hotel”, “arrival_date_year”,  and ”arrival_date_month”. We do not interpret anything new from the mean, median and sd. The max “adr” for City Hotel in March 2016 is the highest with 5400. The max “adults” for resort hotel in September and October 2015 is 55 and 50 respectively. The min values are mostly 0s or 1s. \n\nI also grouped by “hotel”, “arrival_date_year”, ”arrival_date_month” to find the total number of “adults”, “children” and “babies” that stayed in the city hotel and resort hotel and filtered for the months July and August. We have data available for July and August for all the three years. We see an increasing trend in the number of people staying in hotels from year 2015 to year 2017.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}