{
  "hash": "2a3177936d40a451dfc04eeeb1ce97c8",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Darron Bunt\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"10/09/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Step 1 - Read in the Data\n\n*Read in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.*\n\n-   -   hotel_bookings.csv ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotels <- read_csv(\"_data/hotel_bookings.csv\")\n```\n:::\n\n\n*Add any comments or documentation as needed. More challenging data may require additional code chunks and documentation.*\n\n## Step 2 - Describe the data\n\n*Using a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).*\n\nThe hotels dataset contains data relating to two types of hotels - city, and resort, from 178 countries. There are 32 total columns of data that provide a high degree of insight into each hotel stay. Some of these details include: \n* The arrival year, month, week, and day\n* The number of week-end and weekday nights stayed\n* The number of adults, children, and babies in the booking\n* The ADR (Average Daily Rate) for each booking.\n\nOverall, this dataset affords the opportunity to extrapolate a wide variety of details regarding city and resort hotel stays between October 2014 and September 2017.\n\n\n\n::: {.cell}\n\n:::\n\n\n## Step 3 - Provide Grouped Summary Statistics\n\n*Conduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.*\n\n**group_by**\n\nGroup_by is going to allow me to make some groupings between columns in the dataset. \n\nLet's say I wanted to make a grouping of the hotel type and the arrival month. If I do this right, (and bookings of both types occurred in every month), I should get 24 groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_by(hotels, hotel, arrival_date_month)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 119,390 × 32\n# Groups:   hotel, arrival_date_month [24]\n   hotel  is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n   <chr>    <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n 1 Resor…       0     342    2015 July         27       1       0       0      2\n 2 Resor…       0     737    2015 July         27       1       0       0      2\n 3 Resor…       0       7    2015 July         27       1       0       1      1\n 4 Resor…       0      13    2015 July         27       1       0       1      1\n 5 Resor…       0      14    2015 July         27       1       0       2      2\n 6 Resor…       0      14    2015 July         27       1       0       2      2\n 7 Resor…       0       0    2015 July         27       1       0       2      2\n 8 Resor…       0       9    2015 July         27       1       0       2      2\n 9 Resor…       1      85    2015 July         27       1       0       3      2\n10 Resor…       1      75    2015 July         27       1       0       3      2\n# … with 119,380 more rows, 22 more variables: children <dbl>, babies <dbl>,\n#   meal <chr>, country <chr>, market_segment <chr>,\n#   distribution_channel <chr>, is_repeated_guest <dbl>,\n#   previous_cancellations <dbl>, previous_bookings_not_canceled <dbl>,\n#   reserved_room_type <chr>, assigned_room_type <chr>, booking_changes <dbl>,\n#   deposit_type <chr>, agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n**select()**\n\nSelect is going to let me pull a subset of the entire data based on the names of the variables.\n\nSo let's say of the 34 columns of hotel data that I have, I'm really only interested in a few of them. I can select those.\n\nI'm interested in the hotel type, the arrival month, and the average daily rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(hotels, hotel, arrival_date_month, adr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 119,390 × 3\n   hotel        arrival_date_month   adr\n   <chr>        <chr>              <dbl>\n 1 Resort Hotel July                  0 \n 2 Resort Hotel July                  0 \n 3 Resort Hotel July                 75 \n 4 Resort Hotel July                 75 \n 5 Resort Hotel July                 98 \n 6 Resort Hotel July                 98 \n 7 Resort Hotel July                107 \n 8 Resort Hotel July                103 \n 9 Resort Hotel July                 82 \n10 Resort Hotel July                106.\n# … with 119,380 more rows\n```\n:::\n:::\n\n**filter()**\n\nFilter is going to let me pull some specific data that I might be interested in. Maybe I really only care about bookings that had a lead time that was greater that 400 days. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(hotels, lead_time>400)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,114 × 32\n   hotel  is_ca…¹ lead_…² arriv…³ arriv…⁴ arriv…⁵ arriv…⁶ stays…⁷ stays…⁸ adults\n   <chr>    <dbl>   <dbl>   <dbl> <chr>     <dbl>   <dbl>   <dbl>   <dbl>  <dbl>\n 1 Resor…       0     737    2015 July         27       1       0       0      2\n 2 Resor…       0     460    2015 August       32       3       2       5      1\n 3 Resor…       0     709    2016 Februa…       9      25       8      20      2\n 4 Resor…       1     468    2016 May          20      12       0       2      2\n 5 Resor…       1     468    2016 May          20      12       0       2      2\n 6 Resor…       1     468    2016 May          20      12       0       2      2\n 7 Resor…       1     468    2016 May          20      12       0       2      2\n 8 Resor…       1     468    2016 May          20      12       0       2      2\n 9 Resor…       1     468    2016 May          20      12       0       2      2\n10 Resor…       1     468    2016 May          20      12       0       2      2\n# … with 2,104 more rows, 22 more variables: children <dbl>, babies <dbl>,\n#   meal <chr>, country <chr>, market_segment <chr>,\n#   distribution_channel <chr>, is_repeated_guest <dbl>,\n#   previous_cancellations <dbl>, previous_bookings_not_canceled <dbl>,\n#   reserved_room_type <chr>, assigned_room_type <chr>, booking_changes <dbl>,\n#   deposit_type <chr>, agent <chr>, company <chr>, days_in_waiting_list <dbl>,\n#   customer_type <chr>, adr <dbl>, required_car_parking_spaces <dbl>, …\n```\n:::\n:::\n\n\n**summarize()**\n\nSummarize is going to come in handy if I want to collapse the large set of data down into something a little smaller. An example would be what the average ADR is across the full dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarize(hotels, adr = mean(adr))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n    adr\n  <dbl>\n1  102.\n```\n:::\n:::\n\nNow we know that the average ADR is $101.83.\n\n**Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.**\n\nI can also start finding random and specific things, like the average lead time by hotel type for bookings with a lead time greater than 400 days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotels %>% \n  filter(lead_time>400) %>% \n  group_by(hotel) %>% \n  summarize(lead_time = mean(lead_time))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  hotel        lead_time\n  <chr>            <dbl>\n1 City Hotel        468.\n2 Resort Hotel      467 \n```\n:::\n:::\n\n\nI could add some additional layers to the group_by, too. Maybe I want to figure out the average lead time for bookings with a 400+ day lead time, and break that down by the month of the year of the booking and the type of hotel. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotels%>%\n  filter(lead_time>400)%>%\n  group_by(hotel, arrival_date_month)%>%\n  summarize(lead_time = mean(lead_time))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 18 × 3\n# Groups:   hotel [2]\n   hotel        arrival_date_month lead_time\n   <chr>        <chr>                  <dbl>\n 1 City Hotel   April                   443 \n 2 City Hotel   August                  460.\n 3 City Hotel   December                482.\n 4 City Hotel   February                584.\n 5 City Hotel   January                 556.\n 6 City Hotel   July                    438.\n 7 City Hotel   June                    435.\n 8 City Hotel   March                   615 \n 9 City Hotel   May                     424.\n10 City Hotel   November                533.\n11 City Hotel   October                 483.\n12 City Hotel   September               428.\n13 Resort Hotel August                  424.\n14 Resort Hotel February                709 \n15 Resort Hotel July                    580.\n16 Resort Hotel May                     453.\n17 Resort Hotel October                 443.\n18 Resort Hotel September               523.\n```\n:::\n:::\n\n\n### Step 4 - Explain and Interpret\n\n*Be sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.*\n\nSo I'm really interested in people who plan ahead by 400+ days, and how doing so might vary between people who book at city hotels vs. resort hotels. I'm also really curious about whether the lead time varies depending on the month of the booking. \n\nInterestingly, the highest average 400+ day lead time can be found in resort hotel bookings for the month of February (709), while for city hotels, the highest average was in March (615). ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}