{
  "hash": "e097c506cca5e11cd7f6db232d6ffedd",
  "result": {
    "markdown": "---\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n|                                                                                                                                                                                      |\n|-------------------|\n| title: \"Final Paper\" description: \"Final Project and Paper\" author: \"Sanjana Jhaveri\" date: \"2022-12-18\" output: distill::distill_article categories: - final_project - nfl_2019 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nnfl <- read_csv(\"_data/nfl2019.csv\")\nView(nfl)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in check_for_XQuartz(): X11 library is missing: install XQuartz from xquartz.macosforge.org\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnfl <- read_csv(\"_data/nfl2019.csv\",\n                          skip = 1,\n                          col_names = c(\"delete\", \"Opponent\", \"Home_Ranking\", \"Opponent_Ranking\", \"Home_1st_Downs\", \"Home_Total_Yards\", \"Home_Passing_Yards\", \"Home_Rushing_Yards\", \"Home_Turnovers\", \"Opponent_1st_Downs\", \"Opponent_Total_Yards\",\"Opponent_Passing_Yards\", \"Opponent_Rushing_Yards\", \"Opponent_Turnovers\", \"Home_Offensive_Ranking\", \"Home_Defensive_Ranking\", \"Home_Special_Teams\", \"Home\", \"Year\", \"Winner\")) %>%\n  select(!starts_with(\"delete\")) %>%\n  na_if(\"Skipped\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(nfl$Home_Total_Yards)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 348.048\n```\n:::\n\n```{.r .cell-code}\nmean(nfl$Opponent_Total_Yards)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 346.2134\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(nfl$Home_Passing_Yards)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 231.8302\n```\n:::\n\n```{.r .cell-code}\nmean(nfl$Opponent_Passing_Yards)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 230.5542\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(nfl$Home_Rushing_Yards)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 116.2179\n```\n:::\n\n```{.r .cell-code}\nmean(nfl$Opponent_Rushing_Yards)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 115.6592\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnfl%>%\n  ggplot(aes(x=`Home_Passing_Yards`, y=`Year`)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](SanjanaJhaveri_FinalPaper_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnfl%>%\n  ggplot(aes(x=`Opponent_Passing_Yards`, y=`Year`)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](SanjanaJhaveri_FinalPaper_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnfl$home_winner <- with(nfl, ifelse(Home == Winner, 'Win', 'Loss'))\n\nview(nfl)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(filter(nfl,home_winner == \"Win\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 451\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(nfl$Home_Passing_Yards > nfl$Opponent_Passing_Yards & nfl$home_winner == \"Win\") \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 262\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(nfl$Home_Rushing_Yards > nfl$Opponent_Rushing_Yards & nfl$home_winner == \"Win\") \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 311\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nscatter <- nfl %>%\n  ggplot(mapping=aes(x = Year, y = `Home_Passing_Yards`))+ \n  geom_point(aes(color=home_winner))\nscatter\n```\n\n::: {.cell-output-display}\n![](SanjanaJhaveri_FinalPaper_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nscatter <- nfl %>%\n  ggplot(mapping=aes(x = Year, y = `Home_Rushing_Yards`))+ \n  geom_point(aes(color=home_winner))\nscatter\n```\n\n::: {.cell-output-display}\n![](SanjanaJhaveri_FinalPaper_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n##Final Paper\n\nMy final project was focused on an NFL (National Football League)\ndataset. I chose this particular dataset because I like to watch the NFL\ngames every Sunday and I think I understand the game pretty well.\nHowever, during the games, I seem to have a couple of questions. My\nresearch question focuses on if each team's stats in yardage (passing\nand rushing yards), correlate to each other and to the win. First, I\nwanted to see if the home team has more passing yards than the opponent\nthen would it correlate to an automatic win? If that answer was yes that\nthe two correlate directly to each other, it would tell us that rushing\nyards don't matter as much in the game and that teams should focus on\ndominating in the passing game. It might even affect what kind of\nquarterback the teams draft. Do you pick a quarterback that is fast and\ncan run or do you pick one that has a good arm and can throw for many\nyards. If that answer was no that the two don't correlate directly to\neach other it would suggest two other hypotheses. The first would be\nthat since the passing game doesn't matter to the win, maybe the rushing\ngame does, so the logical next step would be to look at whichever team\nhas the most rushing yards and see how many times they pulled off the\nwin. If we see that the number of times the team with the most rushing\nyards ends up winning, then we have our answer that rushing yards in the\ngame matter more than passing yards. Again, I imagine that would affect\ndraft picks in focusing more on running backs and quarterbacks that can\nrun. If the answer is no there is no direct correlation, we have to look\nat the second hypothesis. The second would be that neither the passing\nyards nor the rushing yards in the game matter. We cannot predict the\nwinner by just looking at the number of passing yards or the number of\nrushing yards. I think that the more passing yards a team has the more\nlikely chance they have of winning. Obviously, the team with the most\npassing yards or rushing yards will win every game so arbitrarily I will\nsay the team with the most passing yards or rushing yards has to win\n65%+ of the games in order to say that either yardage has a significant\nimpact. I think this because every team has a quarterback that can throw\nreally well and throw for many yards but not every team has a\nquarterback that can run a lot or successfully in a consistent manner. I\nthink that rushing yards do not matter as much as passing yards and\nmaybe that's why the average number of rushing yards in a game tends to\nbe less than the passing yards. I think this research question can not\nonly help teams select quarterbacks, wide receivers and running backs\nduring the draft, but also identify weak points in the team's roster to\nsee where the team needs to practice more. Additionally, it can also\nhelp predict wins/losses within the league. The dataset I chose was the\nNFL team stats and outcomes from 2019-2022. It includes stats on the\ndefense, offense and special teams units for the home team. It also\nincludes information on team standings (rankings) and the outcomes of\neach game. When looking at the dataset, I renamed each column into\nsomething that made more sense to me, using opponent or home at the\nbeginning of each name to specify which team. I deleted the first column\nbecause I did not think that the week of the NFL season that the game\nwas played mattered to me to answer my research question. The next\ncolumn is the opponent's name. For the next column, instead of Tm I\nrenamed that column to the Home_Ranking because this is what the home\nteam ranked as during the week that the game was played and Tm is a very\nvague name. The next column is the Opponent_Ranking which is what the\nopponent team ranked as during the week the game was played, which I\nrenamed from the nonspecific name Opp.1. Next, I renamed 1stD and TotYd\ninto home 1st downs and home total yards respectively. I kept 1st downs\nbecause I feel like it's a good stat to have. It won't necessarily be a\ngood predictor for who wins the game, but the more first downs you have\nthe more likely you are going to be closer to the touchdowns and to make\na field goal. Basically, the more first downs you have you probably are\ncloser to getting more points on the board (either 3 points or 7). The\ntotal yards field is extremely important because this the sum of the\npassing yards and the rushing yards. The team with the win is\nautomatically going to have the most total yards. Next couple of columns\nwe have home passing yards and home rushing yards. These two columns are\nthe main columns that I'll be looking at to answer my research question.\nIn the next column we have home turnovers, which is not a great\nindicator of whether or not a team wins that game but a lot of turnovers\nmeans that the other team got an additional chance to put more points on\nthe board. The next couple of columns are the same as before but for the\nopponent: opponent 1st downs, opponent total yards, opponent passing\nyards, opponent rushing yards and opponent turnovers, which all now have\nopponent leading the name instead of a .1 differentiating these columns\nfrom the home team stats. These columns have the same importance as the\nparallel columns do for the home team. I will be looking closely as the\nopponent passing yards and opponent rushing yards columns to answer my\nquestion. The next couple of columns describe the different unit\nrankings for the home team. We have the home offensive ranking, the home\ndefensive ranking and the home special teams ranking. Next, I have\nlisted the home team name and the year that the game was played. This\ndataset only shows games that were played in the 2019-2022 regular\nseason, meaning that playoff games and the Superbowl game stats are not\ncounted here. I kept the column naming the winner, but this column lists\nthe whole team name, which is why I have created another column called\nhome_winner. This column looks at the team name of the winner and shows\nif it is the same team name listed as the home team. If it is the same\nteam name, we put 'Win' in the home_winner column and if it is not\nequal, which means that the opponent won, we put a 'Loss' in the\nhome_winner column. The home_winner column is relative to the home team.\nThis is how I renamed the columns and cleaned the data. I needed to\nclean the data by renaming the columns because the original dataset had\ncolumn names that were not descriptive of what team (opponent or home)\nwe were looking at. A lot of the numeric valued columns like passing\nyards or rushing yards had names like PassY and RushY for the home team\nand PassY.1 and RushY.1 for the opponent, which gets confusing after a\nwhile. This is why I decided to rename all the columns as something\ndescriptive and make sure that they all have opponent or home attached\nto the column name. After cleaning the dataset, we have 20 total columns\nand 895 rows. For my visualizations, I am focusing on 6 columns:\nHome_Passing_Yards, Home_Rushing_Yards, Opponent_Passing_Yards,\nOpponent_Rushing_Yards, Year and home_winner. I have run the basic\nstatistics operations on Home/Opponent total yards, Home/Opponent\npassing yards and Home/Opponent rushing yards by calculating the mean of\neach of these columns. This is just to establish some sort of arbitrary\nbaseline. For example, the mean of Home_Passing_Yards and\nOpponent_Passing_Yards is 231.83 and 230.55 respectively. Although these\nvalues are close, this operation tells me that the home team edged out\nthe opponent team most of the time in passing yards and that in most\ngames the passing yard total should be somewhere around 230 yards to be\nsignificant. This tells me that if for example the home team has 175\nyards in the passing game, the opponent team probably won because 175\nyards is significantly less than the average 230 yards. The baseline for\nthe rushing yards is home at 116.22 and the opponent at 115.66. Again,\nthe values are so close that it is not really significant. I expect the\nmean for the home and opponent total yards to be very close too,\nespecially because both the passing yards and the rushing yards averages\nwere very close. Calculating the average of these two comes out to home\ntotal yards at 348.05 and the opponent total yards at 346.21. Again, too\nclose to be significantly leaning towards either team but this\nestablishes a nice baseline for very value we will be looking at. I\ndecided to not calculate the maximum or minimum values of each team's\npassing, rushing or total yards because I feel like that information\ndoes not do anything to further answer my research question nor does it\nprovide any additional missing information and I can adequately deduce\nthat information from the data visualizations I have created. I decided\nto plot the Home Passing Yards vs the year to see how over the 4 years,\nhow the passing yards have evolved. This visualization allows me to see\nwith an overall view what is the average range of passing yards by the\nhome team and which data points are outliers. I next decided to plot the\nOpponent Passing Yards vs the year so I can compare the two\nHome_Passing_Yards and Opponent_Passing_Yards in the big picture.\nLooking at the big picture, I don't see much of a difference. The\noverall range of the average each year looks about the same and the\noutliers also look around the same which seems accurate since the\naverage of each were so close to each other. From there, I decided to\ndraw a real conclusion on my research question of whether the team's\npassing yards correlate to a win if they have more passing yards than\nthe opposing team. I needed to have a visual depicting the wins and\nlosses with the home passing yards to see if the home team won more\ngames with a lot of passing yards or not. So, I had to create a new\nfield called home_winner. To get the values in this new column, I\ncreated a simple conditional statement. Basically, if the home team name\nis equal to the winner team name, then put the value 'Win' in the\nhome_winner column. Else, if the opponent team name equals the winning\nteam name, then put the value 'Loss' in the home_winner column. The\nhome_winner column is all relative to the home team. Next, I decided to\nfilter for the 'Win' value in home_winner to see how many times the home\nteam won. They have 451 wins over 4 years. To determine the answer to my\nresearch question, I must count how many times the home team passing\nyards were greater than the opposing teams passing yards and that the\nhome_winner has the value 'Win'. Meeting that conditional came out to\n262 times. I also counted how many times the home team rushing yards\nwere greater than the opposing teams rushing yards to answer the\nquestion of whether a team's rushing yards correlate to the win if they\nrushed more than the other team. Again, I used the conditional of\nHome_Rushing_Yards are greater than Opposing_Rushing_Yards and\nhome_winning is equal to 'Win'. Meeting than conditional came out to\n311. Looking at the visual I created, the loss is shown as the color red\nand the win depicted as blue, we plot the year against the home passing\nyards. We see that the different colors dots are kind of all over the\nplace. In 2019 and 2020, we see that the home passing yards are very\nhigh around 500 and 450 respectively but both of those come out as a\nloss. On the other hand, in 2021 and 2022 we see that the highest home\npassing yard around 450 comes out to wins. We can also see that when the\nhome passing yards is at a minimum in all 4 years, anywhere from around\n0 to 50, all of those show as a loss. However, instead of seeing a lot\nof blue congregated towards the top of the y axis and the red towards\nthe bottom, we see no real divisive line between the two colors. I\ncreated the same kind of visual to look at the rushing yards for the\nhome team. Again, I have red depicting a loss and blue showing a win and\nplotted the year against the home rushing yards. With the rushing yards,\nwe can see a little more division already. We can see in all the years\nexcept for maybe 2021, the highest number of rushing yards clearly are\nhome team wins. Additionally, we also see that the lowest number of\nrushing yards are clearly home team losses. We see more division with\nthe rushing yards in that the blue or wins are mostly concentrated\ntowards the top of the y-axis as more rushing yards for the home team\nand that conversely the red are more concentrated towards the bottom of\nthe y-axis as fewer rushing yards for the home team. From my\nvisualizations I learned that looking at the bigger picture in visuals\ntells you a lot of information. I can see when depicting wins and losses\nwith color where wins and losses are more concentrated and if a divisive\nline exists. I enjoyed my experience with this project. It allowed me to\nsee NFL games in a new light, a more logical statistical light. After I\nstarted this project, I started paying more attention to the passing\nyardage and rushing yardage that each team put up at the end of the\ngame. I started noticing that certain teams usually have more passing\nyardage than rushing yardage because they are a more pass reliant team\nor vice versa with a more run heavy team. Looking back at my analysis in\nthis project, I realize that I am only looking at the offensive side of\neach team and not accounting for the defense at all, even though some\nteams win based on defense alone. I now realize that some teams are more\nequipped to handle a pass heavy team with their defense and vice versa\nand defense definitely plays a role in whether a team wins or loses. I\nthink if I was continuing this project, I would have tried to\nincorporate a team's defensive strategy into my analysis somehow. Maybe\nsee if the defensive ranking affects the win or loss. Or compare each\nteam's defensive and offensive rankings and try to see how those\ncorrelates to the win. It would be interesting to see if a team's\noffensive or defensive ranking holds more weight to the win or if it's a\ntossup and it really doesn't matter. The most challenging aspect of this\nproject definitely was figuring out how to visualize the home passing\nyardage and home rushing yardage and how to see which team won at the\nsame time. Once I figured out that I have to base everything off the\nhome team and create a new column win/loss for the home team, creating\nthe visual became way easier. I originally was thinking of assigning\neach team a number and instead of a team name being displayed a number\nwould be displayed, which would basically be the new win/loss column.\nHowever, since there are 32 NFL teams, I would have to assign 32 numbers\nand remember the number for each team. In addition to that, I would be\nplotting based on 32 teams for each graph which would further complicate\nmatters and would make reading the graph impossibly difficult. I also\ndid not think about the fact that these numbers are spread over 4 years\nand the quarterbacks, wide receivers and running backs are not the same\nfor all 4 years. Some quarterbacks are more pass reliant and some\nquarterbacks are running quarterbacks which means their rushing yardage\nis usually higher whether they win or lose. If I was continuing this\nproject, I would have to look at the quarterback rating and whether\nthere are more running quarterbacks or pass heavy quarterbacks within\nthe league. I think I would somehow incorporate what kind of quarterback\nthe winning team had so that I can see whether a running quarterback or\na pass heavy quarterback tends to do better within the league. Other\nareas of growth in this project could be to look at whether the team's\nranking as you go further through the weeks of the regular season plays\nan impact on which team wins or loses. For example, if the San Francisco\n49ers are ranked at #9 in week 1 vs. ranked at #9 in week 15 of a\nregular 18-week season, is it more likely they will win in week 1 or\nweek 15 when in both weeks they are ranked in the top 10. Another area I\nwould consider looking at if I were to continue with this project would\nbe to see if covid 19 played a big impact on the team's not putting in\nas much passing or rushing yardage in 2020. If the fans were not allowed\nto be there, would the teams still have enough of a push to keep pushing\nthe numbers up in each category. In regards to fans, it would be\ninteresting to see how big the stadium of the home team was and how\nlarge of a fan base of each team came out to see them play and if that\naffected the win. I know the atmosphere of the game is a big thing in\ncollege football, like how big the stadium is, how many fans come out to\nsee their team, how loud it can get, etc. but is it as big of a factor\nin the NFL? In continuing this project, another idea I had would be to\ncontinue looking at the rest of the 2019-2022 seasons. Like not only\nlooking at the statistics of the regular 18-week season but looking at\nthe numbers from the post season of the playoffs and the Superbowl. Do\nthe playoffs and the Superbowl automatically assure bigger passing and\nrushing yardage? Do these numbers matter more or less in the postseason?\nDoes rushing yardage matter more in the playoffs and the Superbowl than\npassing yardage or vice versa? Another area to look at would be if\npenalties had a significant impact on any of the games. Since yards\ngiven or taken away during penalties are not counted in passing or\nrushing yards or even the total yardage, a team might have won because\nof more penalties against the other team giving one team more advantages\nand more yards that are not technically accounted for in any statistics.\nMy final thoughts on this are yes, a win is a win no matter how big or\nsmall, by 1 point or 50 points but if the home team and opposing team\nhave a small deficit in passing yardage but a big deficit in rushing\nyardage does that directly link to a smaller deficit in points or a\nbigger deficit or does it not matter? What about the opposite scenario\n(a big deficit in passing yardage but a small deficit in rushing\nyardage)? In conclusion, I can answer both my research questions using\nthe data I have gathered and from the visuals I have created using that\ndata. My first research question was if one team has more passing yards\nthan the other team, does that directly link to a win? The answer to\nthat is no, not necessarily since the data doesn't show that happens\nmost of the time. I arrived to this answer by seeing that in the 4-year\ntime frame of my data, there are 451 times that the home team has\nclaimed the win. In those 451 times, if you apply the conditional that\nthe home team has more passing yards than the opposing team and that the\nhome team claims the win, then you get 262 times those conditions were\nmet. This means that only 58% of the home wins also had the home team\ncashing in more passing yards than the opposing team. 58% is a majority\nbut it is not the arbitrary 65% I defined in my introduction where the\nnumber of wins is significant enough that it cannot be disputed that the\npassing yards played a role in the win. With 58%, you also cannot\naccurately predict the winner of the game by only looking at passing\nyardage numbers. The visual depicting the home passing yards vs year\nwith colors showing a win or loss corroborates this answer as both blue\nand red are shown all over the graph with no real separating line\nbetween the wins and losses. My second research question was if one team\nhas more rushing yards than the other team, does that directly link to a\nwin? The answer to that is yes, I think we can see the data shows this\nhappens most of the time. Again, we have 451 wins with the home team.\nLooking at the conditional we have for the rushing yards, if the home\nteam has more rushing yards than the opposing team and the home team has\nthe win, we see that condition is met 311 times. This means that 69% of\nthe home wins also had the home team cashing in more rushing yards than\nthe opposing team. 69% is definitely a majority and is larger than the\n65% that I defined in my introduction. In my opinion, it is a big enough\nmajority that you can usually know the winner by only comparing the\nrushing yards of the two teams and 69% is significant enough that you\ncan definitely say that rushing yards plays a big role in determining\nwhich team gets the W. Also, if you look at the visual for home rushing\nyards and look at the blue and red colors, you can see they are a little\nmore isolated from each other than the passing yard graph. The red is\nmore towards the bottom and means a loss and the blue is more towards\nthe top, meaning more rushing yards and a win. These answers are\nopposite of my hypothesis since I originally thought that more passing\nyards would equivalate a win and more rushing yards would not matter.\nThe only real question I have that is left unanswered is that do these\nfindings really change a general manager's outlook on how to draft a\nquarterback.\n\n##Bibliography Finnstats. \"COUNTIF Function in R: R-Bloggers.\" R, 18\nJuly 2021, https://www.r-bloggers.com/2021/07/countif-function-in-r/.\nGrolemund, Hadley Wickham and Garrett. \"R For Data Science.\" Welcome,\nhttps://r4ds.had.co.nz/index.html. \"NFL Teams Stats and Outcomes.\"\nKaggle,\nhttps://www.kaggle.com/datasets/thedevastator/nfl-team-stats-and-outcomes.\n\"The R Project for Statistical Computing.\" R,\nhttps://www.r-project.org/.\n",
    "supporting": [
      "SanjanaJhaveri_FinalPaper_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}