{
  "hash": "9da9bab6e6de14e9bf455c36ec8a137f",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 Instructions\"\nauthor: \"Kim Darkenwald\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"10/12/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n  - faostat\n  - hotel_bookings\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\n## Data Read In\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds <- read_csv(\"_data/birds.csv\")\nbirds\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 30,977 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1961  1961\n 2 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1962  1962\n 3 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1963  1963\n 4 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1964  1964\n 5 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1965  1965\n 6 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1966  1966\n 7 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1967  1967\n 8 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1968  1968\n 9 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1969  1969\n10 QA           Live …       2 Afgh…    5112 Stocks     1057 Chic…    1970  1970\n# … with 30,967 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n\n```{.r .cell-code}\nview(birds)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30977    14\n```\n:::\n\n```{.r .cell-code}\ncolnames(birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Domain Code\"      \"Domain\"           \"Area Code\"        \"Area\"            \n [5] \"Element Code\"     \"Element\"          \"Item Code\"        \"Item\"            \n [9] \"Year Code\"        \"Year\"             \"Unit\"             \"Value\"           \n[13] \"Flag\"             \"Flag Description\"\n```\n:::\n\n```{.r .cell-code}\nbirds %>%\n  select(\"Area\", \"Item\", \"Year\", \"Unit\", \"Value\", \"Flag Description\") %>%\n  filter(Area == \"World\", Item == \"Chickens\") %>%\n  arrange(desc(\"Year\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 6\n   Area  Item      Year Unit        Value `Flag Description`                    \n   <chr> <chr>    <dbl> <chr>       <dbl> <chr>                                 \n 1 World Chickens  1961 1000 Head 3906690 Aggregate, may include official, semi…\n 2 World Chickens  1962 1000 Head 4048728 Aggregate, may include official, semi…\n 3 World Chickens  1963 1000 Head 4163131 Aggregate, may include official, semi…\n 4 World Chickens  1964 1000 Head 4231221 Aggregate, may include official, semi…\n 5 World Chickens  1965 1000 Head 4349674 Aggregate, may include official, semi…\n 6 World Chickens  1966 1000 Head 4445629 Aggregate, may include official, semi…\n 7 World Chickens  1967 1000 Head 4666511 Aggregate, may include official, semi…\n 8 World Chickens  1968 1000 Head 4823170 Aggregate, may include official, semi…\n 9 World Chickens  1969 1000 Head 4988438 Aggregate, may include official, semi…\n10 World Chickens  1970 1000 Head 5209733 Aggregate, may include official, semi…\n# … with 48 more rows\n```\n:::\n\n```{.r .cell-code}\nbirds %>%\n  select(\"Area\", \"Item\", \"Year\", \"Unit\", \"Value\", \"Flag Description\") %>%\n  filter(Area == \"World\", Item == \"Turkeys\") %>%\n  arrange(desc(\"Year\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 6\n   Area  Item     Year Unit       Value `Flag Description`                      \n   <chr> <chr>   <dbl> <chr>      <dbl> <chr>                                   \n 1 World Turkeys  1961 1000 Head 204241 Aggregate, may include official, semi-o…\n 2 World Turkeys  1962 1000 Head 174077 Aggregate, may include official, semi-o…\n 3 World Turkeys  1963 1000 Head 161262 Aggregate, may include official, semi-o…\n 4 World Turkeys  1964 1000 Head 153758 Aggregate, may include official, semi-o…\n 5 World Turkeys  1965 1000 Head 154790 Aggregate, may include official, semi-o…\n 6 World Turkeys  1966 1000 Head 166655 Aggregate, may include official, semi-o…\n 7 World Turkeys  1967 1000 Head 174158 Aggregate, may include official, semi-o…\n 8 World Turkeys  1968 1000 Head 155205 Aggregate, may include official, semi-o…\n 9 World Turkeys  1969 1000 Head 157950 Aggregate, may include official, semi-o…\n10 World Turkeys  1970 1000 Head 178971 Aggregate, may include official, semi-o…\n# … with 48 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbirds %>%\n   select(\"Area\", \"Item\", \"Year\", \"Unit\", \"Value\", \"Flag Description\") %>%\n  filter(Area == \"World\") %>%\n  summarize(Item, Year, Value) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 290 × 3\n   Item      Year   Value\n   <chr>    <dbl>   <dbl>\n 1 Chickens  1961 3906690\n 2 Chickens  1962 4048728\n 3 Chickens  1963 4163131\n 4 Chickens  1964 4231221\n 5 Chickens  1965 4349674\n 6 Chickens  1966 4445629\n 7 Chickens  1967 4666511\n 8 Chickens  1968 4823170\n 9 Chickens  1969 4988438\n10 Chickens  1970 5209733\n# … with 280 more rows\n```\n:::\n:::\n\n\n##Summary\n\nThis dataset contains information regarded birds around the world and by region. Specifically, chickens, turkeys, and pigeons. Between 1961 and 2018, the total amount of chickens worldwide increaed from 3,906,690 units to 23,707,134 units. A unit consists of 1000.  From 1964 to 2018, the number of turkeys increased from 204241\tunits in 1961 to  466787 units. However, there was not steady increase every year, with some years descreasing in total.\n\n*Please note I tried getting the data for 1961 & 2018 only, but had trouble doing so. I also struggled to get a list of \"Items\" or birds. I would like to know how to do this.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n\nbirds %>%\n   select(\"Area\", \"Item\", \"Year\", \"Unit\", \"Value\", \"Flag Description\") %>%\n  filter(Area == \"World\") %>%\n  summarize(Item, Year, Value) %>%\n  summarize(mean, `1960:1969`, `1970:1979`, `1980:1989`, `1990:1999`, `2000:2009`, `2010;2018)\n    \n  \n   \n  \n```\n\n::: {.cell-output .cell-output-error}\n```\nError: <text>:6:84: unexpected INCOMPLETE_STRING\n10:   \n11: \n                                                                                       ^\n```\n:::\n:::\n\n\n## Provide Grouped Summary Statistics\n\nI was trying to get the summary of total amounts of chickens for each decade, but struggled to do so.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}